---
title: "Reporting LM analysis"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

Published academic articles typically contain something like the following sections:

- **Introduction** (where the authors use the literature to motivate the study they've performed)
- **Methods** (where they discuss the study design, the study procedure, their participants, and the materials they used)
- **Results** (where they report what they found)
- **Discussion** (where they interpret the results in depth, explaining to readers what it all means)
- **Conclusion** (where they summarise their findings and give a take-home message about their original contribution)

In DAPR, we will train you to write something like an article-style **Results** section, to prepare you for writing in this style for your dissertations.

This page doesn't contain an example write-up, because we want you to learn to write your own reports instead of using ours as a template.
But below you'll find guidelines and checklists for you to follow, so that you know you've included all the important information.


## Checklist for a strong Results section

**Set the scene (so the reader knows what you're talking about).**

- [ ] Remind the reader briefly what the study aimed to test (e.g., what the predictions were).


**Describe and show the sample data (so that the reader knows how generalisable your analysis might be).**

- [ ] Introduce the variables the study is using to test this prediction, but avoid using R variable names; describe the variables in human-readable terms instead (e.g., what scale are they on? how were they measured?)
- [ ] Briefly describe the data set: how many observations? what does each observation represent? 
- [ ] Include a table of descriptive statistics for all the relevant variables (and make sure to refer to it in the text).
  - Tip: If this table is really long, then you can keep the main text streamlined by putting the table in an Appendix section.
- [ ] If applicable, mention any data cleaning / outlier removal / transformations.
  
  
**Visualise and summarise data patterns that address the RQ (so the reader knows the basic pattern of what you found).**

- [ ] Include a plot of the data which includes all relevant variables (and make sure to refer to it in the text).
  - Tip: If you transform any continuous predictors for analysis, use the transformed version of the predictor in the plot.
  - Tip: Academic writing styles vary, but Elizabeth likes it when figure captions give the reader a brief take-home message about what they should see in the plot.
- [ ] In a sentence or two, describe the overall pattern of results.
  - Tip: If you find yourself listing loads of numbers in the text, consider using tables or plots instead (and they're better for your word count too!). 
  - Tip: No inferential stats have been done yet, so we can't make any claims just yet about whether the predictions were supported. But it is OK to say whether the results appear broadly in line with the prediction.


**Introduce your statistical analysis (so the reader can interpret the numbers you will report).**

- [ ] State that you're running your analysis using R, and cite the developers (run `citation()` in the console to get the citation for your version of R). 
- [ ] State the $\alpha$ level that you're using for all your analyses (in Psychology, the convention is 5%).
- [ ] Describe the structure of your model in words, e.g.: "We fit a linear model predicting Y as a function of X1, X2, and their interaction".
- [ ] Include the mathematical model formulation of your model.
- [ ] Explain the hypotheses that your analysis will test and include them in mathematical notation.
- [ ] If fitting a GLM, describe the model family and the link function, e.g.: "Since we are modelling a binary outcome, the model is binomial with a logit link".
- [ ] If categorical predictors, describe contrast coding, e.g.: "X1 has two levels, A (coded as –1) and B (coded as 1)".
- [ ] If continuous predictors have been transformed, describe the transformation, e.g.: "X2 has been z-scored".
- [ ] For each model assumption, state whether you are satisfied that the assumption has been met.
- [ ] Include plots for each assumption check as figures in the Appendix section of the document (and refer to them in the main text).
- [ ] If applicable, check for multicollinearity and report VIF or GVIF.
- [ ] If you detected any high-influence observations and then conducted a sensitivity analysis, mention whether the pattern of results stayed the same even after removing each influential observation.
  - Tip: If you'll report your results using the full regression table for your coefficients, then also include the full regression table for the sensitivity analysis in another Appendix section.


**Report the results of your analysis (so the reader knows exactly what you found).**

- [ ] State which model coefficient(s) are related to which prediction(s), and what direction/sign (positive or negative) you would expect the coefficients to have if the predictions were borne out, if applicable.
- [ ] State the key coefficient estimates along with their 95% CI and p-value, e.g.: "The slope associating X1 and Y was significantly different from zero ($b$ = 0.26, 95% CI [0.23, 0.29], $p$ < .001)" or "The slope associating X1 and Y was not significantly different from zero ($b$ = 0.26, 95% CI [–0.04, 0.56], $p$ = .18)", if applicable.
  - Tip: You don't need to report every single parameter estimate. Focus on the one(s) you identified as being relevant to your prediction(s).
  - Tip: Briefly link the direction and significance of the effect back to your earlier predictions—is the prediction supported by the parameter estimate?
- [ ] Include a table of all coefficients estimated by the linear model (and make sure to refer to it in the text), if applicable. The function `tab_model()` from the package `sjPlot` may be useful here, but note that `tab_model()` causes Rmd files to fail to knit to PDF, so you might want to manually recreate the table it produces.
  - Tip: if you DO report all coefficient estimates in the text, then there's no need to include the coefficient table because the information is redundant.
- [ ] Plot the model-fitted values (and refer to the plot in the text), if applicable.
- [ ] Report the results of a model comparison, if applicable.
- [ ] Report any other information you consider important for your story!


**Appendices might include:**

- [ ] Descriptives tables that are too big/disruptive to include in main text
- [ ] Figures that visualise assumption checks
- [ ] Sensitivity analysis regression table / any other useful details


## General guidelines

- Your golden guiding principle should be: **does the reader have all the information they would need to replicate your analysis in whatever statistical software they might be using?**

- Follow the [APA guidelines on how to report numbers and statistics](https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf).

- If you make a plot that contains error bars/shaded error ribbons, always tell the reader what they represent (standard deviation? standard error? 95% CI?).

- To make tables look extra professional, use horizontal lines only.

- If you have multiple research questions and multiple analyses, it's usually most reader-friendly to run through this whole sequence with one analysis to address the first RQ, and then run through it again with the second analysis to address the second RQ, etc.
