---
title: "Block 1 – LM analysis workflow"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

**You do not need to memorise these steps. This page is here so you can refer to it while working through analyses using linear models.**

You won't need to use every step below for every analysis, and they don't need to be in this specific order either.
This is just the order Elizabeth usually uses 😊

Think of these steps like a buffet to pick and choose from, depending on what your analysis needs.


## Phase 1: Before model fitting

#### 1a: Set up your code and data

- **Load the required R packages.** You'll probably need at least:
  - `tidyverse` (for managing and wrangling data)
  - `psych` (for descriptives)
  - `sjPlot` (for nice regression tables and plots)
- **Read in your data.**
- **Tidy data** (e.g., any missingness, any implausible values? are data types set correctly?).


#### 1b: Set up the variables you'll model

- **Based on the RQ, identify your outcome variable and the predictors.**
- **Based on the RQ, decide whether your model requires an interaction between predictors.**
  - see [DAPR2 interaction flash card](https://uoepsy.github.io/dapr2/2526/labs/1_b4_reading.html#interaction-models)
- **Based on the RQ, decide whether you'll test your hypotheses using coefficient significance tests or model comparison.**
  - see model comparison flash cards
- **Based on the outcome variable, decide whether to use regular regression or logistic regression.**
  - see [DAPR2 logistic regression flash card](https://uoepsy.github.io/dapr2/2526/labs/1_b4_reading.html#logistic-regression)
- **Set up categorical predictors.** (e.g., factor levels? which a priori coding scheme?)
  - see [DAPR2 categorical predictors flash card](https://uoepsy.github.io/dapr2/2526/labs/1_b4_reading.html#numeric-outcomes-categorical-predictors)
- **Set up continuous predictors.** (e.g., any transformations?)
  - see [DAPR2 data transformation flash card](https://uoepsy.github.io/dapr2/2526/labs/1_b4_reading.html#data-transformations)
- **Explore patterns in the data by plotting outcome and predictor variables together.** (It's most reader-friendly to plot the transformed version of the data, the version that you'll also be modelling.)
  - see [DAPR2 visual exploration flash card](https://uoepsy.github.io/dapr2/2526/labs/1_b4_reading.html#visual-exploration)


## Phase 2: Model fitting

- Fit your model using `lm()` or `glm()` as appropriate.


## Phase 3: After model fitting

#### 3a: Check assumptions and diagnostics

- **Check model assumptions.**
   - see [Check assumptions flash card](../block1/assump.html)
  - **If model assumptions about normality/equal variance of errors are violated, bootstrap model estimates.**
	  - see [DAPR2 bootstrapping flash card](https://uoepsy.github.io/dapr2/2526/labs/1_b4_reading.html#bootstrap) for how to bootstrap simple linear models.
	  - for bootstrapping LMMs (not covered in DAPR3), you could try `lme4::bootMer()` ([documentation here](https://www.rdocumentation.org/packages/lme4/versions/1.1-38/topics/bootMer)).
- **Run diagnostics for multicollinearity.**
  - see [DAPR2 assumptions flash card](https://uoepsy.github.io/dapr2/2526/labs/1_b4_reading.html#linear-models-2)
- **Run diagnostics for influential observations.**
  - see [Detect influential points and groups flash card](../block1/influence.html)
- **If you find extreme influential observations: run sensitivity analysis.**
   
   
#### 3b: Plot and interpret model estimates
   
- **Plot model-fitted values.**
  - see [plotting fitted values](../block1/plot-fitted.qmd)
- **Interpret the coefficient estimates.**
  - see [DAPR2 statistical models flash cards](https://uoepsy.github.io/dapr2/2526/labs/1_b4_reading.html#statistical-models)
  - see [DAPR2 logistic regression flash cards](https://uoepsy.github.io/dapr2/2526/labs/1_b4_reading.html#logistic-regression) 
  - see [DAPR2 interaction models flash cards](https://uoepsy.github.io/dapr2/2526/labs/1_b4_reading.html#interaction-models)
  
  
#### 3c: Write up methods and results
  
- **Write up your analysis and results.**
  - see [Report LM analyses and results flash card](../block1/reporting.html)
