---
title: "LM analysis workflow (Block 2)"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

**You do not need to memorise these steps. This page is here so you can refer to it while working through analyses using linear models.**

You won't need to use every step below for every analysis, and they don't need to be in this specific order either.
This is just the order Elizabeth usually uses 😊

Think of these steps like a buffet to pick and choose from, depending on what your analysis needs.


## Phase 1: Before model fitting

#### 1a: Set up your code and data

- **Load the required R packages.** You'll probably need at least:
  - `tidyverse` (for managing and wrangling data)
  - `psych` (for descriptives)
  - `sjPlot` (for nice regression tables and plots)
  - `kableExtra` (for nicely-formatted tables)
  - `patchwork` (for combining multiple plots into one graphic)
  - `performance` (for assumption checks)
  - `car` (for multicollinearity check)
- **Read in your data.**
- **Tidy data** (e.g., any missingness, any implausible values? are data types set correctly?).


#### 1b: Set up the variables you'll model

- **Based on the RQ, decide whether you'll test your hypotheses using coefficient significance tests or model comparison.**
  - see [Comparing LMs flash card](https://uoepsy.github.io/dapr2/2627/flashcards/block1/lm-comparisons.html){target="_blank"}
- **Based on the RQ, identify your outcome variable and the predictors.**
- **Set up categorical predictors.** (e.g., factor levels? which contrast coding scheme?)
  - see [Contrast coding flash card](http://localhost:5196/block2/contrast-coding.html){target="_blank"}
- **Set up continuous predictors.** (e.g., any transformations?)
- **Explore patterns in the data by plotting outcome and predictor variables together.** (It's most reader-friendly to plot the transformed version of the data, the version that you'll also be modelling.)
  - see [Exploring data visually flash card](https://uoepsy.github.io/dapr2/2627/flashcards/block1/exploration-visual.html){target="_blank"}
- **Make a nice descriptives table of all relevant variables for the write-up.**
  - see [Exploring data numerically flash card](https://uoepsy.github.io/dapr2/2627/flashcards/block1/exploration-numeric.html){target="_blank"}


## Phase 2: Model fitting

- **Write the mathematical model formulation for your model(s).**
- **Explicitly define the hypotheses that your RQ is aiming to test.**
- **Fit your model(s) using `lm()`.**


## Phase 3: After model fitting

#### 3a: Check assumptions and diagnostics

- **Check model assumptions.**
  - see [LM assumptions flash card](https://uoepsy.github.io/dapr2/2627/flashcards/block2/assump.html){target="_blank"}
- **If model assumptions about normality/equal variance of errors are violated, consider why; if appropriate, bootstrap model estimates.**
  - see [Bootstrapping flash card](https://uoepsy.github.io/dapr2/2627/flashcards/block2/bootstrapping.html){target="_blank"}
- **Run diagnostics for multicollinearity.**
  - see [Checking multicollinearity flash card](https://uoepsy.github.io/dapr2/2627/flashcards/block2/multicollinearity.html){target="_blank"}
- **Run diagnostics for influential observations.**
  - see [Influential observations flash card](https://uoepsy.github.io/dapr2/2627/flashcards/block2/influence.html){target="_blank"}
- **If you find extreme influential observations: run sensitivity analysis.**
  - see [Sensitivity analysis flash card](https://uoepsy.github.io/dapr2/2627/flashcards/block2/sensitivity-analysis.html){target="_blank"}
   
   
#### 3b: Plot and interpret model estimates
   
- **Interpret the coefficient estimates** (if appropriate for your RQ).
- **Generate a nicely-formatted regression table** (if appropriate for your RQ).
  - see [Formatting and presenting results flash card](https://uoepsy.github.io/dapr2/2627/flashcards/resources/formatting.html){target="_blank"}
- **Compare models and interpret model comparison statistics** (if appropriate for your RQ).
  - see [Comparing LMs flash card](https://uoepsy.github.io/dapr2/2627/flashcards/block1/lm-comparisons.html){target="_blank"}
- **Plot model-fitted values** (if appropriate for your RQ).
  
#### 3c: Write up methods and results

  - **Write up your analysis and results.**
  - see [Reporting LM analysis flash card](https://uoepsy.github.io/dapr2/2627/flashcards/resources/reporting-lm.html){target="_blank"}