<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.587">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Model Fit and Standardization</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR2</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intro-to-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Intro to Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intro-to-linear-models">
<li>
    <a class="dropdown-item" href="./1_01_function.html">
 <span class="dropdown-text">1/1: Functions and Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_slr.html">
 <span class="dropdown-text">1/2: Intro to Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_mlr.html">
 <span class="dropdown-text">1/3: More Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_model_fit.html">
 <span class="dropdown-text">1/4: Model Fit and Standardization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_05_recap_writeup.html">
 <span class="dropdown-text">1/5: Recap &amp; Write Up</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">More Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more-linear-models">
<li>
    <a class="dropdown-item" href="./1_07_int1_nc+nn.html">
 <span class="dropdown-text">1/7: Interactions I: Num x Cat &amp; Num x Num</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_08_int2_cc.html">
 <span class="dropdown-text">1/8: Interactions II: Cat x Cat</span></a>
  </li>  
        <li class="dropdown-header">1/9: Assumptions &amp; Diagnostics</li>
        <li class="dropdown-header">1/10: Bootstrap &amp; Troubleshooting</li>
        <li class="dropdown-header">1/11: Recap &amp; Write Up</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysing-experimental-studies" role="button" data-bs-toggle="dropdown" aria-expanded="false">Analysing Experimental Studies</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysing-experimental-studies">
<li class="dropdown-header">2/1: Functions and Models</li>
        <li class="dropdown-header">2/2: Intro to Linear Regression</li>
        <li class="dropdown-header">2/3: More Linear Regression</li>
        <li class="dropdown-header">2/4: Multiple Predictors</li>
        <li class="dropdown-header">2/5: Recap &amp; Write Up</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-topics-for-lm" role="button" data-bs-toggle="dropdown" aria-expanded="false">Advanced Topics for LM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-topics-for-lm">
<li class="dropdown-header">2/6: Functions and Models</li>
        <li class="dropdown-header">2/7: Intro to Linear Regression</li>
        <li class="dropdown-header">2/8: More Linear Regression</li>
        <li class="dropdown-header">2/9: Multiple Predictors</li>
        <li class="dropdown-header">2/10: Recap &amp; Write Up</li>
    </ul>
</li>
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#study-overview" id="toc-study-overview" class="nav-link active" data-scroll-target="#study-overview">Study Overview</a>
  <ul class="collapse">
<li><a href="#data-recap" id="toc-data-recap" class="nav-link" data-scroll-target="#data-recap">Data recap</a></li>
  </ul>
</li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li>
<a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
<li><a href="#back-to-regression-coefficients" id="toc-back-to-regression-coefficients" class="nav-link" data-scroll-target="#back-to-regression-coefficients">Back to regression coefficients</a></li>
  <li><a href="#binary-predictors" id="toc-binary-predictors" class="nav-link" data-scroll-target="#binary-predictors">Binary predictors</a></li>
  <li><a href="#standardization" id="toc-standardization" class="nav-link" data-scroll-target="#standardization">Standardization</a></li>
  </ul>
</li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Model Fit and Standardization</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand the calculation and interpretation of the coefficient of determination.</li>
<li>Understand the calculation and interpretation of the F-test of model utility.</li>
<li>Understand how to standardize model coefficients and when this is appropriate to do.</li>
<li>Understand the relationship between the correlation coefficient and the regression slope.</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed previous lab exercises</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>patchwork</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/riverview.csv">here</a> or read it in via this link https://uoepsy.github.io/data/riverview.csv. <strong>Note</strong>: this is the same data as Lab 2.</p>
</section>
</div>
<section id="study-overview" class="level1"><h1>Study Overview</h1>
<section id="data-recap" class="level2"><h2 class="anchored" data-anchor-id="data-recap">Data recap</h2>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Riverview data codebook</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>The riverview data come from <span class="citation" data-cites="Lewis-Beck2015">(<a href="#ref-Lewis-Beck2015" role="doc-biblioref"><strong>Lewis-Beck2015?</strong></a>)</span> and contain five attributes collected from a random sample of <span class="math inline">\(n=32\)</span> employees working for the city of Riverview, a hypothetical midwestern city in the US. The attributes include:</p>
<ul>
<li>
<code>education</code>: Years of formal education</li>
<li>
<code>income</code>: Annual income (in thousands of U.S. dollars)</li>
<li>
<code>seniority</code>: Years of seniority</li>
<li>
<code>gender</code>: Employee’s gender</li>
<li>
<code>male</code>: Dummy coded gender variable (0 = Female, 1 = Male)</li>
<li>
<code>party</code>: Political party affiliation</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 32 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): gender, party
dbl (4): education, income, seniority, male

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:center;"> education </th>
   <th style="text-align:center;"> income </th>
   <th style="text-align:center;"> seniority </th>
   <th style="text-align:center;"> gender </th>
   <th style="text-align:center;"> male </th>
   <th style="text-align:center;"> party </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 37.449 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> male </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> Democrat </td>
  </tr>
<tr>
<td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 26.430 </td>
   <td style="text-align:center;"> 9 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Independent </td>
  </tr>
<tr>
<td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 47.034 </td>
   <td style="text-align:center;"> 14 </td>
   <td style="text-align:center;"> male </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> Democrat </td>
  </tr>
<tr>
<td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 34.182 </td>
   <td style="text-align:center;"> 16 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Independent </td>
  </tr>
<tr>
<td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 25.479 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Republican </td>
  </tr>
<tr>
<td style="text-align:center;"> 12 </td>
   <td style="text-align:center;"> 46.488 </td>
   <td style="text-align:center;"> 11 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Democrat </td>
  </tr>
</tbody>
</table>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section></section><section id="setup" class="level1"><h1>Setup</h1>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the riverview dataset into R assigning it to an object named <code>riverview</code>
</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="co">#Loading the required package(s)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span>

<span class="co"># Reading in data and storing to an object named 'riverview'</span>
<span class="va">riverview</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">'https://uoepsy.github.io/data/riverview.csv'</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 32 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): gender, party
dbl (4): education, income, seniority, male

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="exercises" class="level1"><h1>Exercises</h1>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Fit a linear model to investigate how income varies with years of formal education.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>

<span class="va">riverview</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span>file <span class="op">=</span> <span class="st">"https://uoepsy.github.io/data/riverview.csv"</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 32 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): gender, party
dbl (4): education, income, seniority, male

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">riverview</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  education income seniority gender  male party      
      &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;      
1         8   37.4         7 male       1 Democrat   
2         8   26.4         9 female     0 Independent
3        10   47.0        14 male       1 Democrat   
4        10   34.2        16 female     0 Independent
5        10   25.5         1 female     0 Republican 
6        12   46.5        11 female     0 Democrat   </code></pre>
</div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">income</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="va">education</span>, data <span class="op">=</span> <span class="va">riverview</span><span class="op">)</span>
<span class="va">mdl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ 1 + education, data = riverview)

Coefficients:
(Intercept)    education  
     11.321        2.651  </code></pre>
</div>
</div>
<p>The fitted model is:</p>
<p><span class="math display">\[
\widehat{Income} = 11.32 + 2.65 \times Education
\]</span></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>What is the proportion of the total variability in incomes explained by the linear relationship with education level?</p>
<p><strong>Hint:</strong> The question asks to compute the value of <span class="math inline">\(R^2\)</span>.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>The proportion of the total variability in incomes explained by the linear relationship with education level is given by R-squared.</p>
<p><strong>Option 1</strong></p>
<p>The R-squared coefficient is defined as:</p>
<p><span class="math display">\[
R^2 = \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\]</span></p>
<p>In <code>R</code> we can write:</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">riverview_fitted</span> <span class="op">&lt;-</span> <span class="va">riverview</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>
    income_hat <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span>,
    resid <span class="op">=</span> <span class="va">income</span> <span class="op">-</span> <span class="va">income_hat</span>
  <span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">riverview_fitted</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  education income seniority gender  male party       income_hat  resid
      &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt;
1         8   37.4         7 male       1 Democrat          32.5   4.92
2         8   26.4         9 female     0 Independent       32.5  -6.10
3        10   47.0        14 male       1 Democrat          37.8   9.20
4        10   34.2        16 female     0 Independent       37.8  -3.65
5        10   25.5         1 female     0 Republican        37.8 -12.4 
6        12   46.5        11 female     0 Democrat          43.1   3.35</code></pre>
</div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">riverview_fitted</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>
    SSModel <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span> <span class="op">(</span><span class="va">income_hat</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">income</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">)</span>,
    SSTotal <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span> <span class="op">(</span><span class="va">income</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">income</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">)</span>
  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>
    RSquared <span class="op">=</span> <span class="va">SSModel</span> <span class="op">/</span> <span class="va">SSTotal</span>
  <span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  RSquared
     &lt;dbl&gt;
1    0.632</code></pre>
</div>
</div>
<hr>
<p><strong>Option 2</strong></p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ 1 + education, data = riverview)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.809  -5.783   2.088   5.127  18.379 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  11.3214     6.1232   1.849   0.0743 .  
education     2.6513     0.3696   7.173 5.56e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.978 on 30 degrees of freedom
Multiple R-squared:  0.6317,    Adjusted R-squared:  0.6194 
F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
</div>
</div>
<p>The output of <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> displays the R-squared value in the following line:</p>
<pre><code>Multiple R-squared:  0.6317</code></pre>
<p>For the moment, ignore “Adjusted R-squared”. We will come back to this later in the course.</p>
<hr>
<p><strong>Option 3</strong></p>
<p>We can perform an <strong>AN</strong>alysis <strong>O</strong>f <strong>VA</strong>riance or, in short, ANOVA. It simply means that we are examining/partitioning the total variability of a response variable.</p>
<p>The <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> function returns the sum of squares of interest in the column <code>Sum Sq</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">mdl_anova</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span>
<span class="va">mdl_anova</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: income
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
education  1 4147.3  4147.3  51.452 5.562e-08 ***
Residuals 30 2418.2    80.6                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Consider the column <code>Sum Sq</code>. The entry corresponding to <code>education</code> gives <span class="math inline">\(SS_{Model}\)</span> = 4147.3, as education is the explanatory variable. The entry corresponding to <code>Residuals</code> gives <span class="math inline">\(SS_{Residual}\)</span> = 2418.2.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="co"># Because the column name Sum Sq has a space, we need to wrap it with backticks</span>
<span class="va">SSModel</span> <span class="op">&lt;-</span> <span class="va">mdl_anova</span><span class="op">$</span><span class="va">`Sum Sq`</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>
<span class="va">SSResidual</span> <span class="op">&lt;-</span> <span class="va">mdl_anova</span><span class="op">$</span><span class="va">`Sum Sq`</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>
<span class="va">SSTotal</span> <span class="op">&lt;-</span> <span class="va">SSModel</span> <span class="op">+</span> <span class="va">SSResidual</span>

<span class="va">RSquared</span> <span class="op">&lt;-</span> <span class="va">SSModel</span> <span class="op">/</span> <span class="va">SSTotal</span>
<span class="va">RSquared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6316828</code></pre>
</div>
</div>
<hr>
<p><strong>Interpretation</strong></p>
<div class="int">
<p>Approximately 63% of the total variability in employee incomes is explained by the linear association with education level.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Perform a model utility test at the 5% significance level, by computing the F-statistic using its definition.</p>
<p><strong>Hint:</strong> The relevant test-statistic is the F-statistic:</p>
<p><span class="math display">\[
\begin{split}
F = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model} / 1}{SS_{Residual} / (n-2)}
\end{split}
\]</span></p>
<p>which compares the amount of variation in the response explained by the model to the amount of variation left unexplained in the residuals.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">df1</span> <span class="op">&lt;-</span> <span class="fl">1</span>
<span class="va">df2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">riverview</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2</span>
<span class="va">f_star</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Fdist.html">qf</a></span><span class="op">(</span><span class="fl">0.95</span>, <span class="va">df1</span>, <span class="va">df2</span><span class="op">)</span>
<span class="va">f_star</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.170877</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">model_utility</span> <span class="op">&lt;-</span> <span class="va">riverview_fitted</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>
    SSModel <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span> <span class="op">(</span><span class="va">income_hat</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">income</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">)</span>,
    SSResid <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span> <span class="va">resid</span><span class="op">^</span><span class="fl">2</span> <span class="op">)</span>,
    MSModel <span class="op">=</span> <span class="va">SSModel</span> <span class="op">/</span> <span class="fl">1</span>,
    MSResid <span class="op">=</span> <span class="va">SSResid</span> <span class="op">/</span> <span class="va">df2</span>,
    FObs <span class="op">=</span> <span class="va">MSModel</span> <span class="op">/</span> <span class="va">MSResid</span>
  <span class="op">)</span>
<span class="va">model_utility</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  SSModel SSResid MSModel MSResid  FObs
    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1   4147.   2418.   4147.    80.6  51.5</code></pre>
</div>
</div>
<div class="int">
<p>We performed an F-test of model utility at the 5% significance level, where <span class="math inline">\(F(1,30) = 51.45\)</span>.</p>
<p>As the observed <span class="math inline">\(F = 51.45\)</span> is much larger than the critical value <span class="math inline">\(F^* = 4.17\)</span>, we have strong evidence to reject the null hypothesis that the model is ineffective.</p>
</div>
<p><br> Alternatively, we can compute the p-value: ::: {.cell}</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pvalue</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Fdist.html">pf</a></span><span class="op">(</span><span class="va">model_utility</span><span class="op">$</span><span class="va">FObs</span>, <span class="va">df1</span>, <span class="va">df2</span><span class="op">)</span>
<span class="va">pvalue</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.562116e-08</code></pre>
</div>
<p>::: The value <code>5.562116e-08</code> simply means <span class="math inline">\(5.56 \times 10^{-8}\)</span>, so it’s a really small number.</p>
<div class="int">
<p>We performed an F-test of model utility at the 5% significance level, where <span class="math inline">\(F(1,30) = 51.45, p&lt;.001\)</span>.</p>
<p>The p-value (&lt; .001) is much lower than the specified significance level, meaning that we have very strong evidence against the null hypothesis.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="optional-begin">
<span id="opt-start-6" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-6', 'opt-start-6')"> <span class="olab">Optional: Another formula for the F-test.</span></span>
</div>
<div id="opt-body-6" class="optional-body" style="display: none;">
<p>With some algebra we can also show that: <span class="math display">\[
F = \frac{R^2 / 1}{(1 - R^2) / (n - 2) } = \frac{R^2 / df_{Model}}{(1 - R^2) / df_{Residual} }
\]</span></p>
<p>Proof:</p>
<p><span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)}
= \frac{\frac{SS_{Model}}{SS_{Total}}}{\frac{SS_{Residual}}{SS_{Total}} \cdot \frac{1}{(n - 2)}}
= \frac{R^2 / 1}{(1 - R^2) / (n - 2)}
\end{aligned}
\]</span></p>
</div>
<p class="optional-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Look at the output of <code>summary(mdl)</code> and <code>anova(mdl)</code>.</p>
<p>For each output, identify the relevant information to conduct an F-test against the null hypothesis that the model is ineffective at predicting income using education level.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ 1 + education, data = riverview)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.809  -5.783   2.088   5.127  18.379 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  11.3214     6.1232   1.849   0.0743 .  
education     2.6513     0.3696   7.173 5.56e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.978 on 30 degrees of freedom
Multiple R-squared:  0.6317,    Adjusted R-squared:  0.6194 
F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
</div>
</div>
<p>The relevant row is the following:</p>
<pre><code>F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<hr>
<p>Instead, the <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> output is:</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: income
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
education  1 4147.3  4147.3  51.452 5.562e-08 ***
Residuals 30 2418.2    80.6                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>And the relevant entries are:</p>
<ul>
<li>the <code>Df</code> column, which contains the degrees of freedom;</li>
<li>
<code>F value = 51.452</code>, which is the F-statistic;</li>
<li>
<code>Pr(&gt;F) = 5.562e-08</code> = <span class="math inline">\(5.562 \times 10^{-8}\)</span>, which is the p-value.</li>
</ul>
<hr>
<p>We might write up the test results as,</p>
<div class="int">
<p>We performed an F-test for the overall significance of the regression, <span class="math inline">\(F(1, 30) = 51.45, p &lt; .001\)</span>. The large F-statistic leads to a very small p-value (<span class="math inline">\(&lt;.001\)</span>), meaning that we have very strong evidence against the null hypothesis that the model is ineffective.</p>
<p>In other words, the data provide strong evidence that education is an effective predictor of income.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Consider the <code>F value</code> output of <code>anova(mdl)</code> and the <code>t value</code> for education returned by <code>summary(mdl)</code></p>
<pre><code>F value = 51.452
t value = 7.173</code></pre>
<p>Do you notice any relationship between the F-statistic for overall model utility and the t-statistic for <span class="math inline">\(H_0: \beta_1 = 0\)</span>?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p><strong>In simple linear regression only</strong>, the F-statistic for overall model significance is equal to the square of the t-statistic for <span class="math inline">\(H_0: \beta_1 = 0\)</span>.</p>
<p>You can check that the squared t-statistic is equal, up to rounding error, to the F-statistic: <span class="math display">\[
t^2 = F \\
7.173^2 = 51.452
\]</span></p>
<div class="optional-begin">
<span id="opt-start-9" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-9', 'opt-start-9')"> <span class="olab">Optional: Equivalence of t-test for the slope and model utility F-test in SLR.</span></span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p>Here we will show the equivalence of the F-test for model effectiveness and t-test for the slope.</p>
<p>Recall the formula of the sum of squares due to the model. We will rewrite it in an equivalent form below: <span class="math display">\[
\begin{aligned}
SS_{Model} &amp;= \sum_i (\hat y_i - \bar y)^2 \\
&amp;= \sum_i (\hat \beta_0 + \hat \beta_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\bar y - \hat \beta_1 \bar x + \hat \beta_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\hat \beta_1 (x_i - \bar x))^2 \\
&amp;= \hat \beta_1^2 \sum_i (x_i - \bar x)^2
\end{aligned}
\]</span></p>
<p>The F-statistic is given by: <span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)}
= \frac{\hat \beta_1^2 \sum_i (x_i - \bar x)^2}{\hat \sigma^2}
= \frac{\hat \beta_1^2 }{\hat \sigma^2 / \sum_i (x_i - \bar x)^2}
\end{aligned}
\]</span></p>
<p>Now recall the formula of the t-statistic, <span class="math display">\[
t = \frac{\hat \beta_1}{SE(\hat \beta_1)} = \frac{\hat \beta_1}{\hat \sigma / \sqrt{\sum_i (x_i - \bar x)^2}}
\]</span></p>
<p>It is evident that the latter is obtained as the square root of the former.</p>
</div>
<p class="optional-end">
</p>
</div>
<p class="solution-end">
</p>
<section id="back-to-regression-coefficients" class="level2"><h2 class="anchored" data-anchor-id="back-to-regression-coefficients">Back to regression coefficients</h2>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Compute the average education level and the average income in the sample.</p>
<p>Use the <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function to compute the predicted income for those with average education level.</p>
<p>What do you notice?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<p>Sample means: ::: {.cell}</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">stats</span> <span class="op">&lt;-</span> <span class="va">riverview</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>
    mean_education <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">education</span><span class="op">)</span>,
    mean_income <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">income</span><span class="op">)</span>
  <span class="op">)</span>
<span class="va">stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  mean_education mean_income
           &lt;dbl&gt;       &lt;dbl&gt;
1             16        53.7</code></pre>
</div>
<p>:::</p>
<p>Prediction: ::: {.cell}</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">query</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>education <span class="op">=</span> <span class="va">stats</span><span class="op">$</span><span class="va">mean_education</span><span class="op">)</span>
<span class="va">query</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  education
      &lt;dbl&gt;
1        16</code></pre>
</div>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mdl</span>, newdata <span class="op">=</span> <span class="va">query</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
53.74212 </code></pre>
</div>
<p>:::</p>
<p><br> The predicted average income for those having average education level is equal to the average income in the sample.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Let’s formalise the previous question using symbols. Consider the fitted model <span class="math inline">\(\hat{y} = \hat \beta_0 + \hat \beta_1 x\)</span>.</p>
<p>What is the predicted response for an individual having an explanatory variable at the average level <span class="math inline">\(\bar{x}\)</span>?</p>
<p><strong>Hint:</strong> Substitute the formula of <span class="math inline">\(\hat \beta_0\)</span> into the equation of the fitted model.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<p>We require the prediction at <span class="math inline">\(x = \bar{x}\)</span>, that is: <span class="math display">\[
\hat{y} = \hat \beta_0 + \hat \beta_1 \bar{x}
\]</span></p>
<p>Recall the formula for the fitted intercept: <span class="math inline">\(\hat \beta_0 = \bar{y} - \hat \beta_1 \bar{x}\)</span>. Let’s substitute it into the equation:</p>
<p><span class="math display">\[
\begin{split}
\hat{y} &amp;= \hat \beta_0 + \hat \beta_1 \bar{x} \\
&amp;= \bar{y} - \hat \beta_1 \bar{x} + \hat \beta_1 \bar{x} \\
&amp;= \bar{y}
\end{split}
\]</span></p>
<p>This highlights an important property of the fitted regression line: it always passes through the point of averages <span class="math inline">\((\bar x, \bar y)\)</span>.</p>
<p>Intuitively, what would be your prediction <span class="math inline">\(\hat y\)</span> when <span class="math inline">\(x\)</span> equals <span class="math inline">\(\bar{x}\)</span>? If you guessed <span class="math inline">\(\bar{y}\)</span> you’re on track!</p>
</div>
<p class="solution-end">
</p>
<div class="boxy boxy-primary boxy-lightbulb">


<section id="binary-predictors" class="level2"><h2 class="anchored" data-anchor-id="binary-predictors">Binary predictors</h2>
<p>Let’s suppose that instead of having measured education in years, we had data instead on “Obtained College Degree: Yes/No”. Our explanatory variable would be binary categorical (think back to our discussion of <a href="https://uoepsy.github.io/dapr1/2122/labs/1_01_data_types.html#Types_of_data">types of data</a>).</p>
<p>Let us pretend that everyone with &gt;18 years of education has a college degree: ::: {.cell}</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="co">#create new variable called 'degree', where those over age 18 are allocated to Yes condition, and those under 18 to No.</span>
<span class="va">riverview</span> <span class="op">&lt;-</span> 
  <span class="va">riverview</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>
      degree <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">education</span> <span class="op">&gt;</span> <span class="fl">18</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span><span class="op">)</span>
    <span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<p>We may then plot our relationship as a boxplot. If you want to see the individual points, you could always “jitter” them (right-hand plot below) ::: {.cell}</p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">riverview</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">degree</span>, y <span class="op">=</span> <span class="va">income</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">riverview</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">degree</span>, y <span class="op">=</span> <span class="va">income</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>height<span class="op">=</span><span class="fl">0</span>, width<span class="op">=</span><span class="fl">.05</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="1_04_model_fit_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<p>:::</p>
</section><section id="standardization" class="level2"><h2 class="anchored" data-anchor-id="standardization">Standardization</h2>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Add to the riverview dataset two variables called <code>z_education</code> and <code>z_income</code> representing the standardized education and income variables, respectively.</p>
<p><strong>Without using R</strong>, if you were to fit a linear regression model using the standardized response and standardized predictor, what would the intercept be?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">riverview</span> <span class="op">&lt;-</span> <span class="va">riverview</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>
    z_education <span class="op">=</span> <span class="op">(</span><span class="va">education</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">education</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">education</span><span class="op">)</span>,
    z_income <span class="op">=</span> <span class="op">(</span><span class="va">income</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">income</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">income</span><span class="op">)</span>
  <span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Check that they are standardized: ::: {.cell}</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">riverview</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>
    M_z_education <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">z_education</span><span class="op">)</span>, SD_z_education <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">z_education</span><span class="op">)</span>, 
    M_z_income <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">z_income</span><span class="op">)</span>, SD_z_income <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">z_income</span><span class="op">)</span>
  <span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  M_z_education SD_z_education M_z_income SD_z_income
          &lt;dbl&gt;          &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;
1      1.73e-18              1  -1.28e-16           1</code></pre>
</div>
<p>:::</p>
<p>A standardized variable has mean 0 and standard deviation equal to 1. We can substitute this in the formula of the estimated intercept:</p>
<p><span class="math display">\[
\hat \beta_0 = \bar{y} - \hat \beta_1 \bar{x} = 0 - \hat \beta_1 0 = 0
\]</span></p>
<p>The intercept of the linear model between the standardized variables is zero — that is, the regression line passes through the origin of the graph.</p>
<p>But wait… The origin is also the average of <span class="math inline">\(z_x\)</span> and the average of <span class="math inline">\(z_y\)</span> as they are standardized. In symbols <span class="math inline">\((0, 0) = (\bar{z}_x, \bar{z}_y)\)</span>.</p>
<p>We expected the fitted line to pass through the point of averages — in this case, the origin.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p><strong>Using R</strong>, fit the regression model using the standardized response and explanatory variables.</p>
<p>What is the slope equal to?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-13" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')"> Solution </span>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<p>Linear model for standardized variables: ::: {.cell}</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">mdl_z</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">z_income</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="va">z_education</span>, data <span class="op">=</span> <span class="va">riverview</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_z</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = z_income ~ 1 + z_education, data = riverview)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.0863 -0.3974  0.1435  0.3523  1.2629 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -8.055e-18  1.091e-01   0.000        1    
z_education  7.948e-01  1.108e-01   7.173 5.56e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6169 on 30 degrees of freedom
Multiple R-squared:  0.6317,    Adjusted R-squared:  0.6194 
F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
</div>
<p>:::</p>
<p><br> Correlation coefficient of original variables: ::: {.cell}</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">riverview</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">education</span>, <span class="va">income</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          education    income
education 1.0000000 0.7947847
income    0.7947847 1.0000000</code></pre>
</div>
<p>:::</p>
<p><br> The slope of the standardized variables is equal to the correlation between the original variables.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Interpret the slope of the standardized variables.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-14" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-14', 'sol-start-14')"> Solution </span>
</div>
<div id="sol-body-14" class="solution-body" style="display: none;">
<div class="int">
<p>For every standard deviation increase in education, income increases on average by 0.79 standard deviations.</p>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="references" class="level1"><h1>References</h1>


</section><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
      <div class="nav-footer-center">© Copyright 2019-2022 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
  </div>
</footer></section></section></main>
</div>


</body></html>