---
title: "Linear models: Study brief"
author: "Emma Waterston, Elizabeth Pankratz"
format: 
  html:
    toc: true
    number_sections: false
    toc-location: left
editor_options: 
  chunk_output_type: console
---

## Research questions and predictions

**RQ1: How is people's sense of Fear of Missing Out (FOMO) associated with their age and how many Instagram followers they have?**

Specific predictions for RQ1:

- As age increases, FOMO will decrease.
- As the number of Instagram followers increases, FOMO will increase.

**RQ2 (bonus challenge, if time): Do the Big 5 personality traits significantly predict FOMO, in addition to the effects of age and total Instagram followers?**



## Study background

The data are available at: <https://uoepsy.github.io/data/FOMOdataset.csv>   

The data used for this write-up exercise are simulated, drawing on recent work on Fear of Missing Out (FOMO), socio-demographic factors, and the Big Five personality traits. The simulated data are based on the findings of this work, and acted to expand upon the methods and results reported in the following paper:

Rozgonjuk, D., Sindermann, C., Elhai, J. D., & Montag, C. (2021). Individual differences in Fear of Missing Out (FOMO): Age, gender, and the Big Five personality trait domains, facets, and items. *Personality and Individual Differences, 171*, 110546.  [https://doi.org/10.1016/j.paid.2020.110546](https://doi.org/10.1016/j.paid.2020.110546)

*NOTE: You are not expected to write an introduction, so you do not have to read this article.*


## Study procedure

In the current study, participants were invited to an online study investigating the associations among FOMO, socio-demographic factors, and personality. The final sample comprised 3370 people. 

Participants completed a FOMO scale and a personality inventory. 
The 10-item FOMO scale measured the extent of experiencing apprehension regarding missing out on interesting events of others on a 5-point scale (1 = “not at all true of me” to 5 = “extremely true of me”), producing a possible range of scores between 10 and 50. 

The Big Five Inventory (BFI) is a 45-item personality assessment questionnaire (note that only 44 items were used to match the study above) that uses a five-point response scale (1 = “very inapplicable” to 5 = “very applicable”). 
The BFI consists of five domains: Neuroticism (8 items; possible range of scores 8-40), Extraversion (8 items; possible range of scores 8-40), Openness to Experience (10 items; possible range of scores 10-50), Agreeableness (9 items; possible range of scores 9-45), and Conscientiousness (9 items; possible range of scores 9-45). 

We extended the aforementioned study to include an extra socio-demographic variable - a measure of popularity on social media based on the number of followers.
Unlike the original study, we do not have measures of gender, education level, or specific country of residence.   

## Data dictionary

The data in `FOMOdataset.csv` contain eight attributes collected from a simulated sample of $n=3370$ hypothetical individuals across the UK, and include: 

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
fomo <- read_csv("https://uoepsy.github.io/data/FOMOdataset.csv")
tibble(
Variable = names(fomo),
Description = c("FOMO Score (as measured by the 10-item FOMO scale)", "Age (in years)", "Score on personality items assessing Neuroticism from the Big Five Inventory (BFI)", "Score on personality items assessing Extraversion from the Big Five Inventory (BFI)", "Score on personality items assessing Openness from the Big Five Inventory (BFI)", "Score on personality items assessing Agreeableness from the Big Five Inventory (BFI)", "Score on personality items assessing Conscientiousness from the Big Five Inventory (BFI)", "Total Number of Instagram Followers")
) |> gt::gt()
```
 
