<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Simple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-circle-right')) {
    f.classList.add('fa-circle-down')
    f.classList.remove('fa-circle-right')
} else {
    f.classList.add('fa-circle-right')
    f.classList.remove('fa-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR2</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="./csstests.html" rel="" target="">
 <span class="menu-text">CSS TEST</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intro-to-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Intro to Linear Models</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intro-to-linear-models">
<li class="dropdown-header">1/1: Functions and Models</li>
        <li class="dropdown-header">1/2: Intro to Linear Regression</li>
        <li>
    <a class="dropdown-item" href="./1_03_mlr.html" rel="" target="">
 <span class="dropdown-text">1/3: Multiple Regression</span></a>
  </li>  
        <li class="dropdown-header">1/4: Model Fit and Standardization</li>
        <li class="dropdown-header">1/5: Cat Predictors &amp; Recap</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">More Linear Models</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more-linear-models">
<li class="dropdown-header">1/7: Interactions I: Num x Cat</li>
        <li class="dropdown-header">1/8: Interactions II: Num x Num</li>
        <li class="dropdown-header">1/9: Interactions III: Cat x Cat</li>
        <li class="dropdown-header">1/10: Assumptions &amp; Diagnostics</li>
        <li class="dropdown-header">1/11: Write Up &amp; Recap</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysing-experimental-studies" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Analysing Experimental Studies</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysing-experimental-studies">
<li class="dropdown-header">2/1: Model Comparison</li>
        <li class="dropdown-header">2/2: Effects Coding</li>
        <li class="dropdown-header">2/3: Contrasts</li>
        <li class="dropdown-header">2/4: Simple Effects &amp; Pairwise Comparisons</li>
        <li class="dropdown-header">2/5: Write Up &amp; Recap</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-topics-for-lm" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Advanced Topics for LM</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-topics-for-lm">
<li class="dropdown-header">2/6: Binary Logistic Regression</li>
        <li class="dropdown-header">2/7: More Logistic Regression</li>
        <li class="dropdown-header">2/8: Sample Size &amp; Power Analysis</li>
        <li class="dropdown-header">2/9: Write Up &amp; Recap</li>
        <li class="dropdown-header">2/10: Mock Exam</li>
    </ul>
</li>
</ul>
<div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#study-overview" id="toc-study-overview" class="nav-link active" data-scroll-target="#study-overview">Study Overview</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li>
<a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
<li>
<a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration">Data Exploration</a>
  <ul class="collapse">
<li><a href="#marginal-distributions" id="toc-marginal-distributions" class="nav-link" data-scroll-target="#marginal-distributions">Marginal Distributions</a></li>
  <li><a href="#associations-among-variables" id="toc-associations-among-variables" class="nav-link" data-scroll-target="#associations-among-variables">Associations among Variables</a></li>
  </ul>
</li>
  <li><a href="#model-specification-and-fitting" id="toc-model-specification-and-fitting" class="nav-link" data-scroll-target="#model-specification-and-fitting">Model Specification and Fitting</a></li>
  <li><a href="#predicted-values-residuals" id="toc-predicted-values-residuals" class="nav-link" data-scroll-target="#predicted-values-residuals">Predicted Values &amp; Residuals</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Simple Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Be able to specify a simple linear model.</li>
<li>Understand what fitted values and residuals are.</li>
<li>Be able to interpret the coefficients of a fitted model.</li>
</ol></section><section id="requirements" class="level3"><h3 class="anchored" data-anchor-id="requirements">
<i class="fa fa-check-square-o fa-2"></i> Requirements</h3>
<ol type="1">
<li>Be up to date with lectures from Weeks 1 &amp; 2</li>
<li>Have completed <a href="https://uoepsy.github.io/dapr2/2223/labs/1_01_function.html">Week 1 lab exercises</a>
</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>sjPlot</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/riverview.csv">here</a> or read it in via this link https://uoepsy.github.io/data/riverview.csv.</p>
</section>
</div>
<section id="study-overview" class="level1"><h1>Study Overview</h1>
<blockquote class="blockquote">
<p><strong>Research Question</strong></p>
<p>Is there an overall effect of the number of social interactions on wellbeing scores?</p>
</blockquote>
<div class="optional-begin">
<span id="opt-start-1" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Wellbeing/Rurality data codebook.</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>From the Edinburgh &amp; Lothians, 100 city/suburb residences and 100 rural residences were chosen at random and contacted to participate in the study. The Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), was used to measure mental health and well-being.</p>
<p>Participants filled out a questionnaire including items concerning: estimated average number of hours spent outdoors each week, estimated average number of social interactions each week (whether on-line or in-person), whether a daily routine is followed (yes/no). For those respondents who had an activity tracker app or smart watch, they were asked to provide their average weekly number of steps.</p>
<p>The data in <code>wellbeing.csv</code> contain seven attributes collected from a random sample of <span class="math inline">\(n=200\)</span> hypothetical residents over Edinburgh &amp; Lothians, and include:</p>
<ul>
<li>
<code>wellbeing</code>: Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br>
</li>
<li>
<code>outdoor_time</code>: Self report estimated number of hours per week spent outdoors<br>
</li>
<li>
<code>social_int</code>: Self report estimated number of social interactions per week (both online and in-person)</li>
<li>
<code>routine</code>: Binary 1=Yes/0=No response to the question “Do you follow a daily routine throughout the week?”</li>
<li>
<code>location</code>: Location of primary residence (City, Suburb, Rural)</li>
<li>
<code>steps_k</code>: Average weekly number of steps in thousands (as given by activity tracker if available)</li>
<li>
<code>age</code>: Age in years of respondent</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="ydgabwknrs" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ydgabwknrs table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ydgabwknrs thead, #ydgabwknrs tbody, #ydgabwknrs tfoot, #ydgabwknrs tr, #ydgabwknrs td, #ydgabwknrs th {
  border-style: none;
}

#ydgabwknrs p {
  margin: 0;
  padding: 0;
}

#ydgabwknrs .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ydgabwknrs .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ydgabwknrs .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ydgabwknrs .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ydgabwknrs .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ydgabwknrs .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ydgabwknrs .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ydgabwknrs .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ydgabwknrs .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ydgabwknrs .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ydgabwknrs .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ydgabwknrs .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ydgabwknrs .gt_spanner_row {
  border-bottom-style: hidden;
}

#ydgabwknrs .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ydgabwknrs .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ydgabwknrs .gt_from_md > :first-child {
  margin-top: 0;
}

#ydgabwknrs .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ydgabwknrs .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ydgabwknrs .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ydgabwknrs .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ydgabwknrs .gt_row_group_first td {
  border-top-width: 2px;
}

#ydgabwknrs .gt_row_group_first th {
  border-top-width: 2px;
}

#ydgabwknrs .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ydgabwknrs .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ydgabwknrs .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ydgabwknrs .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ydgabwknrs .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ydgabwknrs .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ydgabwknrs .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ydgabwknrs .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ydgabwknrs .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ydgabwknrs .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ydgabwknrs .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ydgabwknrs .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ydgabwknrs .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ydgabwknrs .gt_left {
  text-align: left;
}

#ydgabwknrs .gt_center {
  text-align: center;
}

#ydgabwknrs .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ydgabwknrs .gt_font_normal {
  font-weight: normal;
}

#ydgabwknrs .gt_font_bold {
  font-weight: bold;
}

#ydgabwknrs .gt_font_italic {
  font-style: italic;
}

#ydgabwknrs .gt_super {
  font-size: 65%;
}

#ydgabwknrs .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ydgabwknrs .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ydgabwknrs .gt_indent_1 {
  text-indent: 5px;
}

#ydgabwknrs .gt_indent_2 {
  text-indent: 10px;
}

#ydgabwknrs .gt_indent_3 {
  text-indent: 15px;
}

#ydgabwknrs .gt_indent_4 {
  text-indent: 20px;
}

#ydgabwknrs .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="age">age</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="outdoor_time">outdoor_time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="social_int">social_int</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="routine">routine</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="wellbeing">wellbeing</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="location">location</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="steps_k">steps_k</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="age" class="gt_row gt_right">28</td>
<td headers="outdoor_time" class="gt_row gt_right">12</td>
<td headers="social_int" class="gt_row gt_right">13</td>
<td headers="routine" class="gt_row gt_right">1</td>
<td headers="wellbeing" class="gt_row gt_right">36</td>
<td headers="location" class="gt_row gt_left">rural</td>
<td headers="steps_k" class="gt_row gt_right">21.6</td>
</tr>
<tr>
<td headers="age" class="gt_row gt_right">56</td>
<td headers="outdoor_time" class="gt_row gt_right">5</td>
<td headers="social_int" class="gt_row gt_right">15</td>
<td headers="routine" class="gt_row gt_right">1</td>
<td headers="wellbeing" class="gt_row gt_right">41</td>
<td headers="location" class="gt_row gt_left">rural</td>
<td headers="steps_k" class="gt_row gt_right">12.3</td>
</tr>
<tr>
<td headers="age" class="gt_row gt_right">25</td>
<td headers="outdoor_time" class="gt_row gt_right">19</td>
<td headers="social_int" class="gt_row gt_right">11</td>
<td headers="routine" class="gt_row gt_right">1</td>
<td headers="wellbeing" class="gt_row gt_right">35</td>
<td headers="location" class="gt_row gt_left">rural</td>
<td headers="steps_k" class="gt_row gt_right">49.8</td>
</tr>
<tr>
<td headers="age" class="gt_row gt_right">60</td>
<td headers="outdoor_time" class="gt_row gt_right">25</td>
<td headers="social_int" class="gt_row gt_right">15</td>
<td headers="routine" class="gt_row gt_right">0</td>
<td headers="wellbeing" class="gt_row gt_right">35</td>
<td headers="location" class="gt_row gt_left">rural</td>
<td headers="steps_k" class="gt_row gt_right">NA</td>
</tr>
<tr>
<td headers="age" class="gt_row gt_right">19</td>
<td headers="outdoor_time" class="gt_row gt_right">9</td>
<td headers="social_int" class="gt_row gt_right">18</td>
<td headers="routine" class="gt_row gt_right">1</td>
<td headers="wellbeing" class="gt_row gt_right">32</td>
<td headers="location" class="gt_row gt_left">rural</td>
<td headers="steps_k" class="gt_row gt_right">48.1</td>
</tr>
<tr>
<td headers="age" class="gt_row gt_right">34</td>
<td headers="outdoor_time" class="gt_row gt_right">18</td>
<td headers="social_int" class="gt_row gt_right">13</td>
<td headers="routine" class="gt_row gt_right">1</td>
<td headers="wellbeing" class="gt_row gt_right">34</td>
<td headers="location" class="gt_row gt_left">rural</td>
<td headers="steps_k" class="gt_row gt_right">67.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section><section id="setup" class="level1"><h1>Setup</h1>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the wellbeing dataset into R, assigning it to an object named <code>mwdata</code>
</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#Loading the required package(s)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://strengejacke.github.io/sjPlot/">sjPlot</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Reading in data and storing to an object named 'mwdata'</span></span>
<span><span class="va">mwdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/wellbeing_rural.csv"</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section><section id="exercises" class="level1"><h1>Exercises</h1>
<section id="data-exploration" class="level2"><h2 class="anchored" data-anchor-id="data-exploration">Data Exploration</h2>
<p>The common first port of call for almost any statistical analysis is to explore the data, and we can do this visually and/or numerically.</p>
<table class="table">
<colgroup>
<col style="width: 4%">
<col style="width: 43%">
<col style="width: 46%">
<col style="width: 5%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2">================ <strong>Description</strong>
</td>
<td colspan="3" rowspan="2">Marginal Distributions | Bivariate Associations | =================================================================================================================================================================+==============================================================================================================================================================================+ The distribution of each variable <em>without</em> reference to the values of the other variables | Describing the relationship between two numeric variables |</td>
</tr>
<tr class="even"></tr>
<tr class="odd">
<td>
<p><strong>Visually</strong> <br><br></p>
<p><br><br></p>
</td>
<td>Plot each variable individually. <br><br> You could use, for example, <code><a href="https://ggplot2.tidyverse.org/reference/geom_density.html">geom_density()</a></code> for a density plot or <code><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram()</a></code> for a histogram to comment on and/or examine: <br><br><ul>
<li>
The <em>shape</em> of the distribution. Look at the shape, centre and spread of the distribution. Is it symmetric or skewed? Is it unimodal or bimodal?
</li>
<li>
Identify any <em>unusual observations</em>. Do you notice any extreme observations (i.e., outliers)?
</li>
</ul>
</td>
<td colspan="2">Plot associations among two variables. | <br> | <br> | You could use, for example, <code><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point()</a></code> for a scatterplot to comment on and/or examine: <br> | <br> |
<li>
The <em>direction</em> of the association indicates whether there is a positive or negative association
</li>
<li>
The <em>form</em> of association refers to whether the relationship between the variables can be summarized well with a straight line or some more complicated pattern
</li>
<li>
The <em>strength</em> of association entails how closely the points fall to a recognizable pattern such as a line
</li>
<li>
<em>Unusual observations</em> that do not fit the pattern of the rest of the observations and which are worth examining in more detail
</li>
</td>
</tr>
<tr class="even">
<td>
<strong>Numerically</strong> <br><br>
</td>
<td>Compute and report summary statistics e.g., mean, standard deviation, median, min, max, etc. <br><br> You could, for example, calculate summary statistics such as the mean (<code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>) and standard deviation (<code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code>), etc. within <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code>
</td>
<td>Compute and report the correlation coefficient. <br><br><br> You can use the <code><a href="https://rdrr.io/r/stats/cor.html">cor()</a></code> function to calculate this</td>
<td></td>
</tr>
</tbody>
</table>
<section id="marginal-distributions" class="level3"><h3 class="anchored" data-anchor-id="marginal-distributions">Marginal Distributions</h3>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Visualise and describe the marginal distributions of wellbeing scores and social interactions.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Wellbeing (WEMWBS) Scores</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Social Interactions</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Visualisation of distribution:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">mwdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">wellbeing</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_density.html">geom_density</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Wellbeing (WEMWBS) Scores"</span>, </span>
<span>       y <span class="op">=</span> <span class="st">"Probability density"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div id="fig-densbox-wb" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_02_slr_new_files/figure-html/fig-densbox-wb-1.png" class="img-fluid figure-img" style="width:80.0%" alt="Density plot of wellbeing scores. Unimodal distribution, with most of the wellbeing scores were between roughly 30 and 45. All scores within range."></p>
<figcaption class="figure-caption">Figure&nbsp;1: Distribution of Wellbeing (WEMWBS) Scores</figcaption></figure>
</div>
</div>
</div>
<p>Initial observations from plot:</p>
<ul>
<li>The distribution of wellbeing scores was unimodal</li>
<li>Most of the wellbeing scores were between roughly 30 and 45</li>
<li>The lowest wellbeing in the sample was approximately 22 and the highest approximately 59. This suggested there was a fair high degree of variation in the data</li>
<li>Scores were within the range of possible values</li>
</ul>
<p>Descriptive (or summary) statistics for wellbeing scores:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">desc_wellbeing</span> <span class="op">&lt;-</span> <span class="va">mwdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span></span>
<span>    M <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">wellbeing</span><span class="op">)</span>, </span>
<span>    SD <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">wellbeing</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span><span class="va">desc_wellbeing</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
      M    SD
  &lt;dbl&gt; &lt;dbl&gt;
1  36.3  5.39</code></pre>
</div>
</div>
<p>Following the exploration above, we can describe the wellbeing variable as follows:</p>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The marginal distribution of scores on the WEMWBS was unimodal with a mean of approximately 36.3. There was variation in WEMWBS scores (SD = 5.39)</p>
</div>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Visualisation of distribution:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">mwdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">social_int</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_density.html">geom_density</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Social Interactions (Number per Week)"</span>, </span>
<span>       y <span class="op">=</span> <span class="st">"Probability density"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div id="fig-densbox-soc-int" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_02_slr_new_files/figure-html/fig-densbox-soc-int-1.png" class="img-fluid figure-img" style="width:80.0%" alt="Density plot of number of weekly social interactions. Unimodal distribution, with most of the weekly number of social interactions between roughly 8 and 15."></p>
<figcaption class="figure-caption">Figure&nbsp;2: Distribution of Number of Social Interactions</figcaption></figure>
</div>
</div>
</div>
<p>Initial observations from plot:</p>
<ul>
<li>The distribution of social interactions was unimodal</li>
<li>Most of the participants had between 8 and 15 social interactions per week</li>
<li>The fewest social interactions per week was approximately 3, and the highest approximately 24. This suggested there was a fair high degree of variation in the data</li>
</ul>
<p>Descriptive (or summary) statistics for the number of weekly social interactions per week:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">desc_social</span> <span class="op">&lt;-</span> <span class="va">mwdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span></span>
<span>    M <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">social_int</span><span class="op">)</span>, </span>
<span>    SD <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">social_int</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span><span class="va">desc_social</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
      M    SD
  &lt;dbl&gt; &lt;dbl&gt;
1  12.1  4.02</code></pre>
</div>
</div>
<p>Following the exploration above, we can describe the social interactions variable as follows:</p>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The marginal distribution of numbers of social interactions per week was unimodal with a mean of approximately 12.06. There was variation in numbers of social interactions (SD = 4.02)</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="associations-among-variables" class="level3"><h3 class="anchored" data-anchor-id="associations-among-variables">Associations among Variables</h3>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Create a scatterplot of wellbeing score and social interactions <em>before</em> calculating the correlation between them.</p>
<div class="imp">
<p><strong>Correlation Matrix</strong></p>
<p>A table showing the correlation coefficients - <span class="math inline">\(r_{(x,y)}=\frac{\mathrm{cov}(x,y)}{s_xs_y}\)</span> - between variables. Each cell in the table shows the association between two variables. The diagonals show the correlation of a variable with itself (and are therefore always equal to 1).</p>
<div class="blue">
<p>In <code>R</code>, we can create a correlation matrix by giving the <code><a href="https://rdrr.io/r/stats/cor.html">cor()</a></code> function a dataframe. However, we only want to give it 2 columns here. Think about how we select specific columns, either giving the column numbers inside <code>[]</code>, or using <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>.</p>
</div>
</div>
<p>Making reference to both the plot and correlation coefficient, describe the association between wellbeing and social interactions among participants in the Edinburgh &amp; Lothians sample.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>Plot</em><br>
We are trying to investigate how wellbeing varies by varying numbers of weekly social interactions. Hence, wellbeing is the dependent variable (on the y-axis), and social interactions is the independent variable (on the x-axis).</p>
<p><em>Correlation</em><br>
Make sure to round your numbers in-line with APA 7th edition guidelines. The <code><a href="https://rdrr.io/r/base/Round.html">round()</a></code> function will come in handy here, as might this <a href="https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf">APA numbers and statistics guide</a>!</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>Let’s produce a scatterplot:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">mwdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">social_int</span>, y <span class="op">=</span> <span class="va">wellbeing</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Social Interactions (Number per Week)"</span>, </span>
<span>       y <span class="op">=</span> <span class="st">"Wellbeing (WEMWBS) Scores"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div id="fig-mwdata-scatterplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_02_slr_new_files/figure-html/fig-mwdata-scatterplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Association between Wellbeing and Social Interactions</figcaption></figure>
</div>
</div>
</div>
<p>To comment on the strength of the linear association we compute the correlation coefficient in either of the following ways:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Indexing (<code>[]</code>)</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Selection (<code>select()</code>)</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># correlation matrix of the two columns of interest - 3 &amp; 5</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">mwdata</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>,<span class="fl">5</span><span class="op">)</span><span class="op">]</span><span class="op">)</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           social_int wellbeing
social_int       1.00      0.24
wellbeing        0.24      1.00</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># select only the columns we want by name, and pass this to cor()</span></span>
<span><span class="va">mwdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">social_int</span>, <span class="va">wellbeing</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           social_int wellbeing
social_int       1.00      0.24
wellbeing        0.24      1.00</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>And we can see that via either method, the correlation is <span class="math display">\[
r_{\text({Social~Interactions,~~ Wellbeing})} = .24
\]</span> <br></p>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>There was a weak, positive, linear association between the weekly number of social interactions and WEMWBS scores for the participants in the sample (<span class="math inline">\(r\)</span> = .24). More social interactions were associated, on average, with higher wellbeing scores.</p>
</div>
</div>
</div>
<p><br></p>
</div>
<p class="solution-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section></section><section id="model-specification-and-fitting" class="level2"><h2 class="anchored" data-anchor-id="model-specification-and-fitting">Model Specification and Fitting</h2>
<p>The scatterplot highlighted a linear relationship, where the data points were scattered around an underlying linear pattern with a roughly-constant spread as x varied.</p>
<p>Hence, we will try to fit a simple (i.e., one x variable only) linear regression model:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\\
\quad \text{where} \quad \epsilon_i \sim N(0, \sigma) \text{ independently}
\]</span></p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What does <span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + \epsilon_i \quad \text{where} \quad \epsilon_i \sim N(0, \sigma) \text{ independently}\)</span> mean?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Lets break the statement down into smaller parts:</p>
<section id="y_i-beta_0-beta_1-x_i-epsilon_i" class="level6"><h6 class="anchored" data-anchor-id="y_i-beta_0-beta_1-x_i-epsilon_i"><span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + \epsilon_i\)</span></h6>
<ul>
<li>
<span class="math inline">\(y_i\)</span> is our measured outcome variable (our DV)</li>
<li>
<span class="math inline">\(x_i\)</span> is our measured predictor variable (our IV)</li>
<li>
<span class="math inline">\(\beta_0\)</span> is the model intercept</li>
<li>
<span class="math inline">\(\beta_1\)</span> is the model slope</li>
</ul></section><section id="epsilon-sim-n0-sigma-text-independently" class="level6"><h6 class="anchored" data-anchor-id="epsilon-sim-n0-sigma-text-independently"><span class="math inline">\(\epsilon \sim N(0, \sigma) \text{ independently}\)</span></h6>
<ul>
<li>
<span class="math inline">\(\epsilon\)</span> is the residual error</li>
<li>
<span class="math inline">\(\sim\)</span> means ‘distributed according to’</li>
<li>
<span class="math inline">\(\sim N(0, \sigma) \text{ independently}\)</span> means ‘normal distribution with a mean of 0 and a variance of <span class="math inline">\(\sigma\)</span>’</li>
<li>Together, we can say that the errors around the line have a mean of zero and constant spread as x varies.</li>
</ul></section>
</div>
</div>
</div>
<p><br></p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>First, write the equation of the fitted line.</p>
<p>Next, using the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function, fit a simple linear model to predict wellbeing (DV) by social interactions (IV), naming the output <code>mdl</code>.</p>
<p>Lastly, update your equation of the fitted line to include the estimated coefficients.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The syntax of the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function is:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>[model name] <span class="ot">&lt;-</span> <span class="fu">lm</span>([response variable i.e., dependent variable] <span class="sc">~</span> [explanatory variable i.e., independent variable], <span class="at">data =</span> [dataframe])</span></code></pre></div>
</div>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>First, lets specify the fitted model, which can be written either as:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Option A</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Option B</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p><span class="math display">\[
\widehat{Wellbeing} = \hat \beta_0 + \hat \beta_1 \cdot Social~Interactions
\]</span></p>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<p><span class="math display">\[
\widehat{Wellbeing} = \hat \beta_0 \cdot 1 + \hat \beta_1 \cdot Social~Interactions
\]</span></p>
</div>
</div>
</div>
<p>To fit the model in <code>R</code>, as the variables are in the <code>mwdata</code> dataframe, we would write:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">Option A</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Option B</a></li>
</ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wellbeing</span> <span class="op">~</span> <span class="va">social_int</span>, data <span class="op">=</span> <span class="va">mwdata</span><span class="op">)</span></span>
<span><span class="va">mdl</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ social_int, data = mwdata)

Coefficients:
(Intercept)   social_int  
    32.4077       0.3222  </code></pre>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wellbeing</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="va">social_int</span>, data <span class="op">=</span> <span class="va">mwdata</span><span class="op">)</span></span>
<span><span class="va">mdl</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ 1 + social_int, data = mwdata)

Coefficients:
(Intercept)   social_int  
    32.4077       0.3222  </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why is there a 1 in the Option B’s?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>When we specify the linear model in <code>R</code>, we include after the tilde sign (<span class="math inline">\(\sim\)</span>), the variables that appear to the right of the <span class="math inline">\(\hat \beta\)</span>s. The intercept, or <span class="math inline">\(\beta_0\)</span>, is a constant. That is, we could write it as multiplied by 1.</p>
<p>Including the 1 explicitly is not necessary because it is included by default (you can check this by comparing the outputs of A &amp; B above with and without the 1 included - the estimates are the same!). After a while, you will find you just want to drop the 1 (i.e., Option B) when calling <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> because you know that it’s going to be there, but in these early weeks we tried to keep it explicit to make it clear that you want to the intercept to be estimated.</p>
</div>
</div>
</div>
<p>Note that by calling the name of the fitted model, <code>mdl</code>, you can see the estimated regression coefficients <span class="math inline">\(\hat \beta_0\)</span> and <span class="math inline">\(\hat \beta_1\)</span>. We can add these values to the fitted line:</p>
<p><span class="math display">\[
\widehat{Wellbeing} = 32.41 + 0.32 \cdot Social~Interactions \\
\]</span></p>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Explore the following equivalent ways to obtain the estimated regression coefficients — that is, <span class="math inline">\(\hat \beta_0\)</span> and <span class="math inline">\(\hat \beta_1\)</span> — from the fitted model:</p>
<ul>
<li><code>mdl</code></li>
<li><code>mdl$coefficients</code></li>
<li><code>coef(mdl)</code></li>
<li><code>coefficients(mdl)</code></li>
<li><code>summary(mdl)</code></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<p>The estimated parameters returned by the below methods are all equivalent. However, <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> returns more information.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">mdl()</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">mdl$coefficients</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-3" role="tab" aria-controls="tabset-5-3" aria-selected="false">coef(mdl)</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-4" role="tab" aria-controls="tabset-5-4" aria-selected="false">coefficients(mdl)</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-5" role="tab" aria-controls="tabset-5-5" aria-selected="false">summary(mdl)</a></li>
</ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<p>Simply invoke the name of the fitted model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ 1 + social_int, data = mwdata)

Coefficients:
(Intercept)   social_int  
    32.4077       0.3222  </code></pre>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl</span><span class="op">$</span><span class="va">coefficients</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)  social_int 
 32.4077070   0.3221959 </code></pre>
</div>
</div>
</div>
<div id="tabset-5-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-3-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)  social_int 
 32.4077070   0.3221959 </code></pre>
</div>
</div>
</div>
<div id="tabset-5-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-4-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coefficients</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)  social_int 
 32.4077070   0.3221959 </code></pre>
</div>
</div>
</div>
<div id="tabset-5-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-5-tab">
<p>Look under the “Estimate” column:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ 1 + social_int, data = mwdata)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.5628  -3.2741  -0.7908   3.3703  20.4706 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 32.40771    1.17532  27.573  &lt; 2e-16 ***
social_int   0.32220    0.09243   3.486 0.000605 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.247 on 198 degrees of freedom
Multiple R-squared:  0.05781,   Adjusted R-squared:  0.05306 
F-statistic: 12.15 on 1 and 198 DF,  p-value: 0.0006045</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The estimated intercept is <span class="math inline">\(\hat \beta_0 = 32.41\)</span> and the estimated slope is <span class="math inline">\(\hat \beta_1 = 0.32\)</span>.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Explore the following equivalent ways to obtain the estimated standard deviation of the errors — that is, <span class="math inline">\(\hat \sigma\)</span> — from the fitted model <code>mdl</code>:</p>
<ul>
<li><code>sigma(mdl)</code></li>
<li><code>summary(mdl)</code></li>
</ul>
<div class="optional-begin">
<span id="opt-start-7" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-7', 'opt-start-7')"> <span class="olab">Huh? What is <span class="math inline">\(\sigma\)</span>?</span></span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<p>The standard deviation of the errors, denoted by <span class="math inline">\(\sigma\)</span>, is an important quantity that our model estimates. It represents how much individual data points tend to deviate above and below the regression line.</p>
<p>A small <span class="math inline">\(\sigma\)</span> indicates that the points hug the line closely and we should expect fairly accurate predictions, while a large <span class="math inline">\(\sigma\)</span> suggests that, even if we estimate the line perfectly, we can expect individual values to deviate from it by substantial amounts.</p>
<p>The <em>estimated</em> standard deviation of the errors is denoted <span class="math inline">\(\hat \sigma\)</span>, and is estimated by essentially averaging squared residuals (giving the variance) and taking the square-root:</p>
<p><span class="math display">\[
\begin{align}
&amp; \hat \sigma = \sqrt{\frac{SS_{Residual}}{n - k - 1}} \\
\qquad \\
&amp; \text{where} \\
&amp; SS_{Residual} = \textrm{Sum of Squared Residuals} = \sum_{i=1}^n{(\epsilon_i)^2}
\end{align}
\]</span></p>
</div>
<p class="optional-end">
</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>The estimated standard deviation of the errors can be equivalently obtained by the below methods. However, <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> returns more information.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">sigma(mdl)</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">summary(mdl)</a></li>
</ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/sigma.html">sigma</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.246982</code></pre>
</div>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<p>Look at the “Residual standard error” entry of the <code>summary(mdl)</code> output:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ 1 + social_int, data = mwdata)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.5628  -3.2741  -0.7908   3.3703  20.4706 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 32.40771    1.17532  27.573  &lt; 2e-16 ***
social_int   0.32220    0.09243   3.486 0.000605 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.247 on 198 degrees of freedom
Multiple R-squared:  0.05781,   Adjusted R-squared:  0.05306 
F-statistic: 12.15 on 1 and 198 DF,  p-value: 0.0006045</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The term “Residual standard error” is a misnomer, as the help page for <code>sigma</code> says (check <code><a href="https://rdrr.io/r/stats/sigma.html">?sigma</a></code>). However, it’s hard to get rid of this bad name as it has been used in too many books showing R output.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The estimated standard deviation of the errors is <span class="math inline">\(\hat \sigma = 5.25\)</span>.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Interpret the estimated intercept, slope, and standard deviation of the errors in the context of the research question.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>To interpret the estimated standard deviation of the errors we can use the fact that about 95% of values from a normal distribution fall within two standard deviations of the center.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">Intercept</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Slope</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-3" role="tab" aria-controls="tabset-7-3" aria-selected="false">Standard deviation of the errors</a></li>
</ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<p>The estimated wellbeing score associated to zero weekly social interactions is 32.41.</p>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<p>The estimated increase in wellbeing associated to one additional weekly social interaction is 0.32.</p>
</div>
<div id="tabset-7-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-3-tab">
<p>For any particular numnber of weekly social interactions, participants’ wellbeing scores should be distributed above and below the regression line with standard deviation estimated to be <span class="math inline">\(\hat \sigma = 5.25\)</span>. Since <span class="math inline">\(2 \hat \sigma = 10.49\)</span>, we expect most (about 95%) of the participants’ wellbeing scores to be within about 11 points from the regression line.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Plot the data and the fitted regression line. To do so:</p>
<ul>
<li>Extract the estimated regression coefficients e.g., via <code>betas &lt;- coef(mdl)</code>
</li>
<li>Extract the first entry of <code>betas</code> (i.e., the intercept) via <code>betas[1]</code>
</li>
<li>Extract the second entry of <code>betas</code> (i.e., the slope) via <code>betas[2]</code>
</li>
<li>Provide the intercept and slope to the function</li>
</ul>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>Extracting values</em><br>
The function <code>coef(mdl)</code> returns a vector (a sequence of numbers all of the same type). To get the first element of the sequence you append <code>[1]</code>, and <code>[2]</code> for the second.</p>
<p><em>Plotting</em><br>
In your <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code>, you will need to specify <code><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline()</a></code>. This might help get you started:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="sc">&lt;</span>intercept<span class="sc">&gt;</span>, <span class="at">slope =</span> <span class="sc">&lt;</span>slope<span class="sc">&gt;</span>)</span></code></pre></div>
</div>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<p>First extract the values required:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">betas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span>
<span><span class="va">intercept</span> <span class="op">&lt;-</span> <span class="va">betas</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="va">slope</span> <span class="op">&lt;-</span> <span class="va">betas</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span></code></pre></div>
</div>
<p>We can plot the model as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">mwdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">social_int</span>, y <span class="op">=</span> <span class="va">wellbeing</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span>intercept <span class="op">=</span> <span class="va">intercept</span>, slope <span class="op">=</span> <span class="va">slope</span>, color <span class="op">=</span> <span class="st">'blue'</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Social Interactions (Number per Week)"</span>, y <span class="op">=</span> <span class="st">"Wellbeing (WEMWBS) Scores"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="1_02_slr_new_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section><section id="predicted-values-residuals" class="level2"><h2 class="anchored" data-anchor-id="predicted-values-residuals">Predicted Values &amp; Residuals</h2>
<div class="statbox">
<section id="predicted-values" class="level3"><h3 class="anchored" data-anchor-id="predicted-values">Predicted Values</h3>
<section id="model-predicted-values-for-sample-data" class="level4"><h4 class="anchored" data-anchor-id="model-predicted-values-for-sample-data">Model predicted values for sample data:</h4>
<p>We can get out the model predicted values for <span class="math inline">\(y\)</span>, the “y hats” (<span class="math inline">\(\hat y\)</span>), for the data in the sample using various functions:</p>
<ul>
<li><code>predict(&lt;fitted model&gt;)</code></li>
<li><code>fitted(&lt;fitted model&gt;)</code></li>
<li><code>fitted.values(&lt;fitted model&gt;)</code></li>
<li><code>mdl$fitted.values</code></li>
</ul>
<p>For example, this will give us the estimated wellbeing score (point on our regression line) for each observed value of social interactions for each of our 200 participants.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7        8 
36.59625 37.24064 35.95186 37.24064 38.20723 36.59625 38.52943 36.27406 
       9       10       11       12       13       14       15       16 
36.59625 37.24064 34.66308 35.62967 34.66308 36.27406 36.91845 37.88504 
      17       18       19       20       21       22       23       24 
37.56284 37.56284 35.62967 35.30747 35.62967 38.20723 36.27406 35.30747 
      25       26       27       28       29       30       31       32 
38.52943 38.52943 37.56284 36.27406 37.56284 35.30747 37.56284 36.91845 
      33       34       35       36       37       38       39       40 
37.56284 34.34088 37.56284 36.27406 36.27406 36.91845 38.85162 35.30747 
      41       42       43       44       45       46       47       48 
38.20723 36.59625 37.56284 36.27406 36.27406 35.95186 34.34088 38.85162 
      49       50       51       52       53       54       55       56 
35.62967 37.24064 35.62967 34.98527 37.56284 37.24064 34.01869 35.95186 
      57       58       59       60       61       62       63       64 
34.66308 37.88504 36.91845 34.66308 37.88504 35.95186 36.27406 35.95186 
      65       66       67       68       69       70       71       72 
36.27406 36.91845 38.20723 34.01869 35.30747 35.30747 34.66308 39.17382 
      73       74       75       76       77       78       79       80 
34.01869 35.30747 33.69649 38.52943 35.62967 37.56284 39.17382 36.91845 
      81       82       83       84       85       86       87       88 
34.98527 35.95186 36.59625 36.27406 34.66308 35.95186 37.24064 37.88504 
      89       90       91       92       93       94       95       96 
35.62967 37.56284 34.66308 34.66308 37.24064 35.95186 34.98527 35.62967 
      97       98       99      100      101      102      103      104 
35.95186 34.66308 37.24064 35.95186 34.34088 34.66308 37.56284 34.98527 
     105      106      107      108      109      110      111      112 
36.27406 37.88504 39.17382 37.24064 38.52943 35.30747 35.62967 35.95186 
     113      114      115      116      117      118      119      120 
37.24064 36.27406 36.27406 36.59625 36.27406 35.95186 36.59625 35.95186 
     121      122      123      124      125      126      127      128 
37.56284 36.91845 34.34088 34.66308 34.98527 35.95186 34.01869 35.62967 
     129      130      131      132      133      134      135      136 
34.98527 35.62967 33.69649 38.20723 38.20723 35.30747 34.66308 37.56284 
     137      138      139      140      141      142      143      144 
36.91845 35.62967 36.91845 38.52943 36.91845 35.30747 35.62967 37.88504 
     145      146      147      148      149      150      151      152 
36.27406 34.98527 35.30747 36.91845 36.59625 36.59625 35.95186 34.34088 
     153      154      155      156      157      158      159      160 
36.59625 36.59625 34.66308 36.91845 36.27406 35.30747 33.69649 35.62967 
     161      162      163      164      165      166      167      168 
36.27406 37.24064 35.95186 36.59625 33.37429 36.59625 38.20723 36.27406 
     169      170      171      172      173      174      175      176 
38.85162 34.66308 37.24064 35.62967 38.20723 36.27406 36.59625 40.14041 
     177      178      179      180      181      182      183      184 
35.30747 34.98527 34.34088 35.95186 36.59625 34.98527 34.98527 35.62967 
     185      186      187      188      189      190      191      192 
34.66308 34.98527 36.27406 37.88504 36.27406 35.95186 35.95186 36.59625 
     193      194      195      196      197      198      199      200 
37.56284 36.27406 36.27406 35.95186 34.66308 35.62967 36.27406 37.24064 </code></pre>
</div>
</div>
</section><section id="model-predicted-values-for-other-unobserved-data" class="level4"><h4 class="anchored" data-anchor-id="model-predicted-values-for-other-unobserved-data">Model predicted values for other (unobserved) data:</h4>
<p>To compute the model-predicted values for unobserved data (i.e., data not contained in the sample), we can use the following function:</p>
<ul>
<li><code>predict(&lt;fitted model&gt;, newdata = &lt;dataframe&gt;)</code></li>
</ul>
<p>For this example, we first need to remember that the model predicts <code>wellbeing</code> using the independent variable <code>social_int</code>. Hence, if we want predictions for new (unobserved) data, we first need to create a tibble with a column called <code>social_int</code> containing the number of weekly social interactions for which we want the prediction, and store this as a dataframe.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#Create dataframe 'newdata' containing 2, 25, and 28 weekly social interactions</span></span>
<span><span class="va">newdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>social_int <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">25</span>, <span class="fl">28</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">newdata</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 1
  social_int
       &lt;dbl&gt;
1          2
2         25
3         28</code></pre>
</div>
</div>
<p>Then we take <code>newdata</code> and add a new column called <code>wellbeing_hat</code>, computed as the prediction from the fitted <code>mdl</code> using the <code>newdata</code> above:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">newdata</span> <span class="op">&lt;-</span> <span class="va">newdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    wellbeing_hat <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mdl</span>, newdata <span class="op">=</span> <span class="va">newdata</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="va">newdata</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  social_int wellbeing_hat
       &lt;dbl&gt;         &lt;dbl&gt;
1          2          33.1
2         25          40.5
3         28          41.4</code></pre>
</div>
</div>
</section></section><section id="residuals" class="level3"><h3 class="anchored" data-anchor-id="residuals">Residuals</h3>
<p>The residuals represent the deviations between the actual responses and the predicted responses and can be obtained either as</p>
<ul>
<li><code>mdl$residuals</code></li>
<li><code>resid(mdl)</code></li>
<li><code>residuals(mdl)</code></li>
<li>computing them as the difference between the response (<span class="math inline">\(y_i\)</span>) and the predicted response (<span class="math inline">\(\hat y_i\)</span>)</li>
</ul></section>
</div>
<p><br></p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Use <code>predict(mdl)</code> to compute the fitted values and residuals. Mutate the <code>mwdata</code> dataframe to include the fitted values and residuals as extra columns.</p>
<p>Assign to the following symbols the corresponding numerical values:</p>
<ul>
<li>
<span class="math inline">\(y_{3}\)</span> (response variable for unit <span class="math inline">\(i = 3\)</span> in the sample data)</li>
<li>
<span class="math inline">\(\hat y_{3}\)</span> (fitted value for the third unit)</li>
<li>
<span class="math inline">\(\hat \epsilon_{5}\)</span> (the residual corresponding to the 5th unit, i.e., <span class="math inline">\(y_{5} - \hat y_{5}\)</span>)</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mwdata_fitted</span> <span class="op">&lt;-</span> <span class="va">mwdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    wellbeing_hat <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span>,</span>
<span>    resid <span class="op">=</span> <span class="va">wellbeing</span> <span class="op">-</span> <span class="va">wellbeing_hat</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">mwdata_fitted</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
    age outdoor_time social_int routine wellbeing location steps_k wellbeing_hat
  &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;         &lt;dbl&gt;
1    28           12         13       1        36 rural       21.6          36.6
2    56            5         15       1        41 rural       12.3          37.2
3    25           19         11       1        35 rural       49.8          36.0
4    60           25         15       0        35 rural       NA            37.2
5    19            9         18       1        32 rural       48.1          38.2
6    34           18         13       1        34 rural       67.3          36.6
# ℹ 1 more variable: resid &lt;dbl&gt;</code></pre>
</div>
</div>
<ul>
<li>
<span class="math inline">\(y_{3}\)</span> = 35 (see row 3, column 5)</li>
<li>
<span class="math inline">\(\hat y_{3}\)</span> = 35.95 (see row 3, column 8)</li>
<li>
<span class="math inline">\(\hat \epsilon_{5} = y_{5} - \hat y_{5}\)</span> = 32 - 38.21 = -6.21 (see row 5, columns 5 and 8)</li>
</ul>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Provide key model results in a formatted table.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Use <code><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model()</a></code> from the <strong>sjPlot</strong> package.</p>
<p>You can rename your DV and IV labels by specifying <code>dv.labels</code> and <code>pred.labels</code>. To do so, specify your variable name on the left, and what you would like this to be named in the table on the right.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">mdl</span>,</span>
<span>          dv.labels <span class="op">=</span> <span class="st">"Wellbeing (WEMWBS) Scores"</span>,</span>
<span>          pred.labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"social_int"</span> <span class="op">=</span> <span class="st">"Social Interactions (Number per Week)"</span><span class="op">)</span>,</span>
<span>          title <span class="op">=</span> <span class="st">"Regression Table for Wellbeing Model"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div id="tbl-wb-socint-modresults" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;1: Regression Table for Wellbeing Model</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Wellbeing (WEMWBS) Scores</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">32.41</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">30.09&nbsp;–&nbsp;34.73</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Social Interactions<br>
(Number per Week)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.32</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.14&nbsp;–&nbsp;0.50</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">200</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.058 / 0.053</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Describe the design of the study, and the analyses that you undertook. Interpret your results in the context of the research question and report your model results in full.</p>
<p>Make reference to your descriptive plots and/or statistics and regression table.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Make sure to write your results up following <a href="https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf">APA guidelines</a></p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-13" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')"> Solution </span>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The <code>mwdata</code> dataset contained information on 200 hypothetical participants who lived in Edinburgh &amp; Lothians area. Using a between-subjects design, the researchers collected information on participants’ wellbeing, outdoor time (hours per week), social interactions (number per week), routine, location of residence, average weekly steps, and age.</p>
<p>To visualise the marginal distributions of wellbeing and social interactions, density plots were used. To understand the strength of association between the two variables, the correlation coefficient was estimated. To investigate whether there was an association between there was an overall effect of the number of weekly social interactions on wellbeing (WEMWBS) scores, the following simple linear regression model was used:</p>
<p><span class="math display">\[
\text{Wellbeing} = \beta_0 + \beta_1 \cdot \text{Social Interactions}
\]</span> From <a href="#fig-densbox-wb">Figure&nbsp;1</a> and <a href="#fig-densbox-soc-int">Figure&nbsp;2</a>, we can see that both wellbeing <span class="math inline">\((M = 36.3, SD = 5.39)\)</span> and social interactions <span class="math inline">\((M = 12.06, SD = 4.02)\)</span> followed unimodal distributions. There was a weak, positive, linear association between WEMWBS scores and the weekly number of social interactions for the participants in the sample (<span class="math inline">\(r\)</span> = .24).</p>
<p>Full regression results are displayed in <a href="#tbl-wb-socint-modresults">Table&nbsp;1</a>. The estimated wellbeing score with no social interactions per week was 32.41. Each additional social interaction was associated with a 0.32 point increase in wellbeing scores.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2023 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>