<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Simple Effects, Pairwise Comparisons, &amp; Corrections</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-circle-right')) {
    f.classList.add('fa-circle-down')
    f.classList.remove('fa-circle-right')
} else {
    f.classList.add('fa-circle-right')
    f.classList.remove('fa-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      DAPR2
      </li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DAPR2</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Semester 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Intro to Linear Models</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_01_slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_02_mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_03_mlr_stz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression &amp; Standardization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_04_model_fit_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model Fit and Comparisons</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_05_writeup_recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Write Up &amp; Block 1 Recap</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Analysing and Evaluating Experimental Studies</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_06_dummy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dummy Coding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_07_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Effects Coding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_08_assump_diag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assumptions and Diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_09_bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrapping</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_10_writeup_recap_blk2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Write Up &amp; Block 2 Recap</span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Semester 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Interaction Models</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_01_int1_nc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactions I: Num x Cat</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Advanced Topics for LM</span></span>
  </li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#study-overview" id="toc-study-overview" class="nav-link active" data-scroll-target="#study-overview">Study Overview</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li>
<a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
<li><a href="#study-analysis-plan-overview" id="toc-study-analysis-plan-overview" class="nav-link" data-scroll-target="#study-analysis-plan-overview">Study &amp; Analysis Plan Overview</a></li>
  <li><a href="#descriptive-statistics-visualisations" id="toc-descriptive-statistics-visualisations" class="nav-link" data-scroll-target="#descriptive-statistics-visualisations">Descriptive Statistics &amp; Visualisations</a></li>
  <li><a href="#model-fitting-interpretation" id="toc-model-fitting-interpretation" class="nav-link" data-scroll-target="#model-fitting-interpretation">Model Fitting &amp; Interpretation</a></li>
  <li><a href="#contrast-analysis" id="toc-contrast-analysis" class="nav-link" data-scroll-target="#contrast-analysis">Contrast Analysis</a></li>
  <li><a href="#simple-effects" id="toc-simple-effects" class="nav-link" data-scroll-target="#simple-effects">Simple Effects</a></li>
  <li><a href="#pairwise-comparisons-multiple-corrections" id="toc-pairwise-comparisons-multiple-corrections" class="nav-link" data-scroll-target="#pairwise-comparisons-multiple-corrections">Pairwise Comparisons &amp; Multiple Corrections</a></li>
  </ul>
</li>
  <li><a href="#compile-report" id="toc-compile-report" class="nav-link" data-scroll-target="#compile-report">Compile Report</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Simple Effects, Pairwise Comparisons, &amp; Corrections</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand how to interpret simple effects for experimental designs</li>
<li>Understand how to conduct pairwise comparisons</li>
<li>Understand how to apply corrections available for multiple comparisons</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed previous lab exercises from <a href="https://uoepsy.github.io/dapr2/2223/labs/2_01_model_comps.html">Week 1</a>, <a href="https://uoepsy.github.io/dapr2/2223/labs/2_02_effects.html">Week 2</a>, and <a href="https://uoepsy.github.io/dapr2/2223/labs/2_03_contrasts.html">Week 3</a>
</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>psych</strong></li>
<li><strong>kableExtra</strong></li>
<li><strong>sjPlot</strong></li>
<li><strong>interactions</strong></li>
<li><strong>patchwork</strong></li>
<li><strong>emmeans</strong></li>
</ul></section><section id="presenting-results" class="level3"><h3 class="anchored" data-anchor-id="presenting-results">
<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Presenting Results</h3>
<p>All results should be presented following <a href="https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf">APA guidelines</a>. If you need a reminder on how to hide code, format tables/plots, etc., make sure to review the <a href="https://uoepsy.github.io//rmd-bootcamp/">rmd bootcamp</a>.</p>
<p>The example write-up sections included as part of the solutions are <strong>not perfect</strong> - they instead should give you a good example of what information you should include and how to structure this. Note that you must <strong>not</strong> copy any of the write-ups included below for future reports - if you do, you will be committing plagiarism, and this type of academic misconduct is taken very seriously by the University. You can find out more <a href="https://www.ed.ac.uk/academic-services/students/conduct/academic-misconduct">here</a>.</p>
</section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/cognitive_experiment.csv">here</a> or read it in via this link https://uoepsy.github.io/data/cognitive_experiment.csv. Note, you have already worked with <em>some</em> of this data last week - see <a href="">Semester 2 Week 3 lab</a>, but we now have a third Task condition - Classification.</p>
</section>
</div>
<section id="study-overview" class="level1"><h1>Study Overview</h1>
<blockquote class="blockquote">
<p><strong>Research Question</strong></p>
<p>Are there differences in types of memory deficits for those experiencing different cognitive impairment(s)?</p>
</blockquote>
<p>In this week’s exercises, we will further explore questions such as:</p>
<ul>
<li>Does level <span class="math inline">\(i\)</span> of the first factor have an effect on the response?</li>
<li>Does level <span class="math inline">\(j\)</span> of the second factor have an effect on the response?</li>
<li>Is there a combined effect of level <span class="math inline">\(i\)</span> of the first factor and level <span class="math inline">\(j\)</span> of the second factor on the response? In other words, is there interaction of the two factors so that the combined effect is not simply the additive effect of level <span class="math inline">\(i\)</span> of the first factor plus the effect of level <span class="math inline">\(j\)</span> of the second factor?</li>
</ul>
<div class="optional-begin">
<span id="opt-start-1" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Cognitive Exp 3x3 data codebook.</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>The researchers designed a study yielding a <span class="math inline">\(3 \times 3\)</span> factorial design to test whether there are differences in types of memory deficits for those experiencing different cognitive impairment(s).</p>
<p>The tasks chosen by the researchers have been picked to map onto the theoretical differences between the three types of research participants. The Grammar and Classification tasks are known to reflect <em>implicit</em> memory processes, whereas the recognition task is known to reflect <em>explicit</em> memory processes. If the theory is correct, we would expect the difference in scores between the recognition and grammar/classification tasks to be relatively similar for the control and amnesiac groups, but relatively larger for the Huntingtons group compared to controls.</p>
<p><strong>Data Dictionary</strong></p>
<p>The data in <code>cognitive_experiment.csv</code> contain three attributes collected from <span class="math inline">\(n=45\)</span> participants, and includes:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="ezlgdzhkht" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ezlgdzhkht table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ezlgdzhkht thead, #ezlgdzhkht tbody, #ezlgdzhkht tfoot, #ezlgdzhkht tr, #ezlgdzhkht td, #ezlgdzhkht th {
  border-style: none;
}

#ezlgdzhkht p {
  margin: 0;
  padding: 0;
}

#ezlgdzhkht .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ezlgdzhkht .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ezlgdzhkht .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ezlgdzhkht .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ezlgdzhkht .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ezlgdzhkht .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ezlgdzhkht .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ezlgdzhkht .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ezlgdzhkht .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ezlgdzhkht .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ezlgdzhkht .gt_spanner_row {
  border-bottom-style: hidden;
}

#ezlgdzhkht .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ezlgdzhkht .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ezlgdzhkht .gt_from_md > :first-child {
  margin-top: 0;
}

#ezlgdzhkht .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ezlgdzhkht .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ezlgdzhkht .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ezlgdzhkht .gt_row_group_first td {
  border-top-width: 2px;
}

#ezlgdzhkht .gt_row_group_first th {
  border-top-width: 2px;
}

#ezlgdzhkht .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ezlgdzhkht .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ezlgdzhkht .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ezlgdzhkht .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ezlgdzhkht .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ezlgdzhkht .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ezlgdzhkht .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ezlgdzhkht .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_left {
  text-align: left;
}

#ezlgdzhkht .gt_center {
  text-align: center;
}

#ezlgdzhkht .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ezlgdzhkht .gt_font_normal {
  font-weight: normal;
}

#ezlgdzhkht .gt_font_bold {
  font-weight: bold;
}

#ezlgdzhkht .gt_font_italic {
  font-style: italic;
}

#ezlgdzhkht .gt_super {
  font-size: 65%;
}

#ezlgdzhkht .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ezlgdzhkht .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ezlgdzhkht .gt_indent_1 {
  text-indent: 5px;
}

#ezlgdzhkht .gt_indent_2 {
  text-indent: 10px;
}

#ezlgdzhkht .gt_indent_3 {
  text-indent: 15px;
}

#ezlgdzhkht .gt_indent_4 {
  text-indent: 20px;
}

#ezlgdzhkht .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="variable">variable</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="description">description</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="variable" class="gt_row gt_left">Diagnosis</td>
<td headers="description" class="gt_row gt_left">Diagnosis classifies the three types of individuals: 1 = Amnesic patients, 2 = Huntingtons patients, and 3 = Control group of individuals with no known neurological disorder</td>
</tr>
<tr>
<td headers="variable" class="gt_row gt_left">Task</td>
<td headers="description" class="gt_row gt_left">Task tells us to which one of three tasks each study participant was randomly assigned to: 1 = Grammar (which consists of classifying letter sequences as either following or not following grammatical rules), 2 = Classification (which consists of classifying stimuli into certain groupings, based on previously indicated information about the groups characteristics), and 3 = Recognition (which consists of recognising particular stimuli as stimuli that have previously been presented during the task)</td>
</tr>
<tr>
<td headers="variable" class="gt_row gt_left">Y</td>
<td headers="description" class="gt_row gt_left">Score</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Data Overview</strong></p>
<p>We have data from the 45 participants (15 amnesiacs, 15 Huntington individuals, and 15 controls). Recall that study involves two factors, now with three levels each. For each combination of factor levels we have 5 observations:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Task
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Diagnosis</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">grammar</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">classification</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">recognition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">amnesic</td>
<td style="text-align: left;">44, 63, 76, 72, 45</td>
<td style="text-align: left;">72, 66, 55, 82, 75</td>
<td style="text-align: left;">70, 51, 82, 66, 56</td>
</tr>
<tr class="even">
<td style="text-align: left;">huntingtons</td>
<td style="text-align: left;">24, 30, 51, 55, 40</td>
<td style="text-align: left;">53, 59, 33, 37, 43</td>
<td style="text-align: left;">107, 80, 98, 82, 108</td>
</tr>
<tr class="odd">
<td style="text-align: left;">control</td>
<td style="text-align: left;">76, 98, 71, 70, 85</td>
<td style="text-align: left;">92, 65, 86, 67, 90</td>
<td style="text-align: left;">107, 80, 101, 82, 105</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The five observations are assumed to come from a population having a specific mean. The population means corresponding to each combination of factor levels can be schematically written as:</p>
<p><span class="math display">\[
\begin{matrix}
                   &amp;         &amp;         &amp; \textbf{Task} &amp; \\
                   &amp;         &amp; (j=1)\text{ grammar} &amp; (j=2)\text{ classification} &amp; (j=3)\text{ recognition} \\
                   &amp; (i=1)\text{ control} &amp; \mu_{1,1} &amp; \mu_{1,2} &amp; \mu_{1,3} \\
\textbf{Diagnosis} &amp; (i=2)\text{ amnesic} &amp; \mu_{2,1} &amp; \mu_{2,2} &amp; \mu_{2,3} \\
                   &amp; (i=3)\text{ huntingtons} &amp; \mu_{3,1} &amp; \mu_{3,2} &amp; \mu_{3,3}
\end{matrix}
\]</span></p>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="jwhphheblm" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#jwhphheblm table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#jwhphheblm thead, #jwhphheblm tbody, #jwhphheblm tfoot, #jwhphheblm tr, #jwhphheblm td, #jwhphheblm th {
  border-style: none;
}

#jwhphheblm p {
  margin: 0;
  padding: 0;
}

#jwhphheblm .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#jwhphheblm .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#jwhphheblm .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#jwhphheblm .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#jwhphheblm .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jwhphheblm .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jwhphheblm .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jwhphheblm .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#jwhphheblm .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#jwhphheblm .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#jwhphheblm .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#jwhphheblm .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#jwhphheblm .gt_spanner_row {
  border-bottom-style: hidden;
}

#jwhphheblm .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#jwhphheblm .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#jwhphheblm .gt_from_md > :first-child {
  margin-top: 0;
}

#jwhphheblm .gt_from_md > :last-child {
  margin-bottom: 0;
}

#jwhphheblm .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#jwhphheblm .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#jwhphheblm .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#jwhphheblm .gt_row_group_first td {
  border-top-width: 2px;
}

#jwhphheblm .gt_row_group_first th {
  border-top-width: 2px;
}

#jwhphheblm .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jwhphheblm .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#jwhphheblm .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#jwhphheblm .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jwhphheblm .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jwhphheblm .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#jwhphheblm .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#jwhphheblm .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#jwhphheblm .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jwhphheblm .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jwhphheblm .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jwhphheblm .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jwhphheblm .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jwhphheblm .gt_left {
  text-align: left;
}

#jwhphheblm .gt_center {
  text-align: center;
}

#jwhphheblm .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#jwhphheblm .gt_font_normal {
  font-weight: normal;
}

#jwhphheblm .gt_font_bold {
  font-weight: bold;
}

#jwhphheblm .gt_font_italic {
  font-style: italic;
}

#jwhphheblm .gt_super {
  font-size: 65%;
}

#jwhphheblm .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#jwhphheblm .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#jwhphheblm .gt_indent_1 {
  text-indent: 5px;
}

#jwhphheblm .gt_indent_2 {
  text-indent: 10px;
}

#jwhphheblm .gt_indent_3 {
  text-indent: 15px;
}

#jwhphheblm .gt_indent_4 {
  text-indent: 20px;
}

#jwhphheblm .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Diagnosis">Diagnosis</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Task">Task</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Y">Y</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="Diagnosis" class="gt_row gt_right">1</td>
<td headers="Task" class="gt_row gt_right">1</td>
<td headers="Y" class="gt_row gt_right">44</td>
</tr>
<tr>
<td headers="Diagnosis" class="gt_row gt_right">1</td>
<td headers="Task" class="gt_row gt_right">1</td>
<td headers="Y" class="gt_row gt_right">63</td>
</tr>
<tr>
<td headers="Diagnosis" class="gt_row gt_right">1</td>
<td headers="Task" class="gt_row gt_right">1</td>
<td headers="Y" class="gt_row gt_right">76</td>
</tr>
<tr>
<td headers="Diagnosis" class="gt_row gt_right">1</td>
<td headers="Task" class="gt_row gt_right">1</td>
<td headers="Y" class="gt_row gt_right">72</td>
</tr>
<tr>
<td headers="Diagnosis" class="gt_row gt_right">1</td>
<td headers="Task" class="gt_row gt_right">1</td>
<td headers="Y" class="gt_row gt_right">45</td>
</tr>
<tr>
<td headers="Diagnosis" class="gt_row gt_right">1</td>
<td headers="Task" class="gt_row gt_right">2</td>
<td headers="Y" class="gt_row gt_right">72</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section><section id="setup" class="level1"><h1>Setup</h1>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the cognitive_experiment dataset into R, assigning it to an object named <code>cog</code> (recall that you have already worked with <em>some</em> of this data last week - see <a href="">Semester 2 Week 3 lab</a>, but we now have a third Task condition - Classification)</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#load packages</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://personality-project.org/r/psych/">psych</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/rvlenth/emmeans">emmeans</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://strengejacke.github.io/sjPlot/">sjPlot</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://interactions.jacob-long.com">interactions</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co">#read in data</span></span>
<span><span class="va">cog</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">'https://uoepsy.github.io/data/cognitive_experiment.csv'</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section><section id="exercises" class="level1"><h1>Exercises</h1>
<section id="study-analysis-plan-overview" class="level2"><h2 class="anchored" data-anchor-id="study-analysis-plan-overview">Study &amp; Analysis Plan Overview</h2>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Firstly, examine the dataset, and perform any necessary and appropriate data management steps.</p>
<p>Next, consider would be the most appropriate coding constraint to apply in order to best address the research question - i.e., are we interested in whether group X (e.g., Amnesic) differed from group Y (e.g., Huntingtons), or whether group X (e.g., Amnesic) differed from the global/grand mean?</p>
<p>Choose appropriate reference levels for the Diagnosis and Task variables based on your decision above.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Convert categorical variables to factors</li>
<li>Label appropriately factors to aid with your model interpretations</li>
<li>If needed, provide better variable names</li>
</ul>
<p>Note that all of these steps can be done in combination - the <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> and <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code> functions will likely be useful here.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>Let’s have a look at the data to see what we’re working with - <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code> or <code><a href="https://rdrr.io/r/utils/head.html">head()</a></code> are a good place to start - and then we should check for any missing data (<code>NA</code> values):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#first look at dataset structure</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">cog</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [45 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Diagnosis: num [1:45] 1 1 1 1 1 1 1 1 1 1 ...
 $ Task     : num [1:45] 1 1 1 1 1 2 2 2 2 2 ...
 $ Y        : num [1:45] 44 63 76 72 45 72 66 55 82 75 ...
 - attr(*, "spec")=
  .. cols(
  ..   Diagnosis = col_double(),
  ..   Task = col_double(),
  ..   Y = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#now lets look at top 6 rows (or the head) of the dataset</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">cog</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Diagnosis  Task     Y
      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1         1     1    44
2         1     1    63
3         1     1    76
4         1     1    72
5         1     1    45
6         1     2    72</code></pre>
</div>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#check for NAs </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">cog</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
FALSE 
  135 </code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># there are none - all FALSE</span></span></code></pre></div>
</div>
<p>Next, lets convert <code>Diagnosis</code> and <code>Task</code> into factors, making the labels of each factor level more meaningful. According to the data description, the encoding of the factor <code>Diagnosis</code> is: 1 = amnesic patients, 2 = Huntingtons patients, and 3 are control patients. The encoding for the factor <code>Task</code> is: 1 = grammar task, 2 = classification task, and 3 = recognition task.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog</span> <span class="op">&lt;-</span> <span class="va">cog</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>        Diagnosis <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Diagnosis</span>, </span>
<span>                           levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>                           labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'amnesic'</span>, <span class="st">'huntingtons'</span>, <span class="st">'control'</span><span class="op">)</span>,</span>
<span>                           ordered <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>,</span>
<span>        Task <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Task</span>, </span>
<span>                      levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>                      labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'grammar'</span>, <span class="st">'classification'</span>, <span class="st">'recognition'</span><span class="op">)</span>,</span>
<span>                      ordered <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>Score <span class="op">=</span> <span class="va">Y</span><span class="op">)</span></span></code></pre></div>
</div>
<p>Since we are interested in comparing groups, we should use dummy coding. By default, <code>R</code> uses dummy coding, so we do not need to make any changes to the coding constraint.</p>
<p>However, for our reference groups, we’re likely to want it to be the Control group for Diagnosis, and recognition for Task:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span>, <span class="st">"control"</span><span class="op">)</span></span>
<span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span>, <span class="st">"recognition"</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Provide a brief overview of the study design and data, before detailing your analysis plan to address the research question.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Give the reader some background on the context of the study (you might be able to re-use some of the content you wrote for <a href="">Semester 2 Week 3 lab</a> here, but note that we now have an extra condition within Task)</li>
<li>Outline data checks / data cleaning</li>
<li>State what type of analysis you will conduct in order to address the research question</li>
<li>Specify the model to be fitted to address the research question (note that you will need to specify the reference level of your categorical variables. This will be somewhat similar to last week, but with the addition of Classification in Task, our model will contain a different number of parameters)</li>
<li>Specify your chosen significance (<span class="math inline">\(\alpha\)</span>) level</li>
<li>State your hypotheses</li>
</ul>
<p>Much of the information required can be found in the <a href="#study-overview">Study Overview</a> codebook.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>The <code>cog</code> dataset contained information on 45 hypothetical participants from a between-subjects study. Participants belonged to one of three ‘Diagnosis’ groups, which had 15 participants in each - Control, Amnesic, or Huntingtons. Participants from each of the Diagnosis groups were equally and randomly assigned to one of three ‘Tasks’ to measure different memory processes - Grammar, Classification, or Recognition - the former two measuring implicit memory and the latter explicit. This resulted in 5 participants from each Diagnosis group in each of the three Task conditions.</p>
<p>All participant data was complete, and categorical variables were coded as factors. For the purpose of this analysis, ‘Control’ was designated as the reference group for Diagnosis, since it was the only group of participants with no known neurological disorder. For Task, the recognition task measures explicit memory whereas the other two measure implicit memory, so this was specified as the reference group.</p>
<p>Boxplots will be used to visualise the associations among Diagnosis and Task conditions. To address the research question of whether the difference in performance between explicit and implicit memory tasks will be greatest for Huntington patients in comparison to controls, we first need to define the dummy variables:</p>
<p>For Diagnosis:</p>
<p><span class="math display">\[
D_\text{Amnesic} = \begin{cases}
1 &amp; \text{if Diagnosis is Amnesic} \\
0 &amp; \text{otherwise}
\end{cases}
\quad  
\\  
D_\text{Huntingtons} = \begin{cases}
1 &amp; \text{if Diagnosis is Huntingtons} \\
0 &amp; \text{otherwise}
\end{cases}
\quad  
\\  
\\  
(\text{Control is base level})
\]</span></p>
<p>And for Task:</p>
<p><span class="math display">\[
T_\text{Grammar} = \begin{cases}
1 &amp; \text{if Task is Grammar} \\
0 &amp; \text{otherwise}
\end{cases}
\quad  
\\  
T_\text{Classification} = \begin{cases}
1 &amp; \text{if Task is Classification} \\
0 &amp; \text{otherwise}
\end{cases}
\quad  
\\  
\\  
(\text{Recognition is base level})
\]</span></p>
<p>Based on the above dummy coding, we are going to fit the following interaction model:</p>
<p><span class="math display">\[
\begin{aligned}
\text{Interaction Model}: \text{Score} &amp;= \beta_0 \\
      &amp;+ \beta_1 \cdot D_\text{Amnseic} + \beta_2 \cdot  D_\text{Huntingtons}   \\
      &amp;+ \beta_3 \cdot  T_\text{Grammar}  + \beta_4 \cdot  T_\text{Classification} \\
      &amp;+ \beta_5 \cdot  (D_\text{Amnseic} \cdot  T_\text{Grammar}) + \beta_6 \cdot  (D_\text{Huntingtons} \cdot  T_\text{Grammar})  \\
      &amp;+ \beta_7 \cdot  (D_\text{Amnseic} \cdot  T_\text{Classification}) + \beta_8 \cdot  (D_\text{Huntingtons} \cdot  T_\text{Classification})  \\
      &amp;+ \epsilon
\end{aligned}
\]</span></p>
<p>Effects will be considered statistically significant at <span class="math inline">\(\alpha = .05\)</span></p>
<p>Our hypotheses are:</p>
<p><span class="math inline">\(H_0:\)</span> All <span class="math inline">\(\beta_j = 0\)</span> (for <span class="math inline">\(j = 5, 6, 7, 8\)</span>)</p>
<p>There are no significant differences in performance between explicit and implicit memory tasks for patients with different cognitive impairment(s).</p>
<p><span class="math inline">\(H_1:\)</span> At least one <span class="math inline">\(\beta_j \neq 0\)</span> (for <span class="math inline">\(j = 5, 6, 7, 8\)</span>)</p>
<p>There are significant differences in performance between explicit and implicit memory tasks for patients with different cognitive impairment(s).</p>
</div>
<p class="solution-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section><section id="descriptive-statistics-visualisations" class="level2"><h2 class="anchored" data-anchor-id="descriptive-statistics-visualisations">Descriptive Statistics &amp; Visualisations</h2>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Provide a table of descriptive statistics and visualise your data.</p>
<p>Interpret the descriptive statistics and visualisations in the context of the study (i.e., comment on any observed differences among treatment groups).</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>For your table of descriptive statistics, both the <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> functions will come in handy here<br>
</li>
<li>Recall that when visualising a continuous outcome across several groups, <code><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot()</a></code> may be most appropriate to use<br>
</li>
<li>Make sure to comment on any observed differences among the sample means of the four treatment conditions</li>
</ol>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Numeric</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Visual</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Descriptive statistics presented in a well formatted table:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog_stats</span> <span class="op">&lt;-</span> <span class="va">cog</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">Diagnosis</span>, <span class="va">Task</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>        Mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Score</span><span class="op">)</span>, </span>
<span>        SD <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Score</span><span class="op">)</span>,</span>
<span>        SE <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Score</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span>,</span>
<span>        Min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">Score</span><span class="op">)</span>,</span>
<span>        Max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">Score</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span>caption <span class="op">=</span> <span class="st">"Descriptive Statistics of Score"</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">cog_stats</span></span></code></pre></div>
<div class="cell-output-display">
<div id="tbl-cog-descript" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;1: Descriptive Statistics</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Diagnosis</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Task</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">control</td>
<td style="text-align: left;">recognition</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">12.98</td>
<td style="text-align: right;">5.81</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">107</td>
</tr>
<tr class="even">
<td style="text-align: left;">control</td>
<td style="text-align: left;">grammar</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">11.68</td>
<td style="text-align: right;">5.22</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">98</td>
</tr>
<tr class="odd">
<td style="text-align: left;">control</td>
<td style="text-align: left;">classification</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">12.98</td>
<td style="text-align: right;">5.81</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">92</td>
</tr>
<tr class="even">
<td style="text-align: left;">amnesic</td>
<td style="text-align: left;">recognition</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">12.17</td>
<td style="text-align: right;">5.44</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">amnesic</td>
<td style="text-align: left;">grammar</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">14.92</td>
<td style="text-align: right;">6.67</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">76</td>
</tr>
<tr class="even">
<td style="text-align: left;">amnesic</td>
<td style="text-align: left;">classification</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">10.17</td>
<td style="text-align: right;">4.55</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">huntingtons</td>
<td style="text-align: left;">recognition</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">13.38</td>
<td style="text-align: right;">5.98</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">108</td>
</tr>
<tr class="even">
<td style="text-align: left;">huntingtons</td>
<td style="text-align: left;">grammar</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">13.25</td>
<td style="text-align: right;">5.92</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">huntingtons</td>
<td style="text-align: left;">classification</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">10.86</td>
<td style="text-align: right;">4.86</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">59</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Since we have a continuous outcome and 2 categorical predictors - a boxplot would be most appropriate for visualisations:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog_plt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">cog</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Diagnosis</span>, y <span class="op">=</span> <span class="va">Score</span>, color <span class="op">=</span> <span class="va">Task</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">'Diagnosis'</span>, y <span class="op">=</span> <span class="st">'Score'</span><span class="op">)</span></span>
<span><span class="va">cog_plt</span></span></code></pre></div>
<div class="cell-output-display">
<div id="fig-cog-desc" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_04_simp_pair_files/figure-html/fig-cog-desc-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Association between Task Condition, Diagnosis, and Score</figcaption></figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<ul>
<li><p>Control patients consistently performed best across all tasks. They doid not appear to differ substantially in their scores between grammar and classification tasks, but they clearly performed better in the recognition task in comparison to both the grammar and classification ones.</p></li>
<li><p>Amnesic patients appeared to perform better than Huntingtons patients in grammar and classification tasks (reflecting intrinsic memory processes), and performed worse than Huntingtons patients in the recognition task (reflecting extrinsic memory processes).</p></li>
</ul>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section><section id="model-fitting-interpretation" class="level2"><h2 class="anchored" data-anchor-id="model-fitting-interpretation">Model Fitting &amp; Interpretation</h2>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Fit the specified model using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, and store the model in an object named “mdl_int”.</p>
<p>Provide key model results in a formatted table and plot the interaction model before reporting in-text the overall model fit.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>Table tips</em> - Use <code><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model()</a></code> from the <strong>sjPlot</strong> package. Remember that you can rename your DV and IV labels by specifying <code>dv.labels</code> and <code>pred.labels</code>.</p>
<p><em>Plotting tips</em> - Using the <code><a href="https://interactions.jacob-long.com/reference/cat_plot.html">cat_plot()</a></code> function from the <strong>interactions</strong> package, visualise the interaction effects from your model.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Build &amp; Check Model</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Results Table</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false">Interaction Plot</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p>Fit model &amp; check summary:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#fit interaction model</span></span>
<span><span class="va">mdl_int</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Score</span> <span class="op">~</span> <span class="va">Diagnosis</span> <span class="op">*</span> <span class="va">Task</span>, data <span class="op">=</span> <span class="va">cog</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#check model output</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_int</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Score ~ Diagnosis * Task, data = cog)

Residuals:
   Min     1Q Median     3Q    Max 
   -16    -12      2     11     18 

Coefficients:
                                          Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                              9.500e+01  5.617e+00  16.912  &lt; 2e-16
Diagnosisamnesic                        -3.000e+01  7.944e+00  -3.776 0.000576
Diagnosishuntingtons                     2.960e-14  7.944e+00   0.000 1.000000
Taskgrammar                             -1.500e+01  7.944e+00  -1.888 0.067085
Taskclassification                      -1.500e+01  7.944e+00  -1.888 0.067085
Diagnosisamnesic:Taskgrammar             1.000e+01  1.123e+01   0.890 0.379329
Diagnosishuntingtons:Taskgrammar        -4.000e+01  1.123e+01  -3.560 0.001063
Diagnosisamnesic:Taskclassification      2.000e+01  1.123e+01   1.780 0.083490
Diagnosishuntingtons:Taskclassification -3.500e+01  1.123e+01  -3.115 0.003597
                                           
(Intercept)                             ***
Diagnosisamnesic                        ***
Diagnosishuntingtons                       
Taskgrammar                             .  
Taskclassification                      .  
Diagnosisamnesic:Taskgrammar               
Diagnosishuntingtons:Taskgrammar        ** 
Diagnosisamnesic:Taskclassification     .  
Diagnosishuntingtons:Taskclassification ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.56 on 36 degrees of freedom
Multiple R-squared:  0.7318,    Adjusted R-squared:  0.6722 
F-statistic: 12.28 on 8 and 36 DF,  p-value: 2.844e-08</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>Table containing the results from model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">mdl_int</span>,</span>
<span>          dv.labels <span class="op">=</span> <span class="st">"Scores"</span>,</span>
<span>          pred.labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Diagnosisamnesic"</span> <span class="op">=</span> <span class="st">"Diagnosis - Amnesic"</span>,</span>
<span>                          <span class="st">"Diagnosishuntingtons"</span> <span class="op">=</span> <span class="st">"Diagnosis - Huntingtons"</span>,</span>
<span>                          <span class="st">"Taskgrammar"</span> <span class="op">=</span> <span class="st">"Task - Grammar"</span>,</span>
<span>                          <span class="st">"Taskclassification"</span> <span class="op">=</span> <span class="st">"Task - Classification"</span>,</span>
<span>                          <span class="st">"Diagnosisamnesic:Taskgrammar"</span> <span class="op">=</span> <span class="st">"Diagnosis - Amnesic : Task - Grammar"</span>,</span>
<span>                          <span class="st">"Diagnosishuntingtons:Taskgrammar"</span> <span class="op">=</span> <span class="st">"Diagnosis - Huntingtons : Task - Grammar"</span>,</span>
<span>                          <span class="st">"Diagnosisamnesic:Taskclassification"</span> <span class="op">=</span> <span class="st">"Diagnosis - Amnesic : Task - Classification"</span>,</span>
<span>                          <span class="st">"Diagnosishuntingtons:Taskclassification"</span> <span class="op">=</span> <span class="st">"Diagnosis - Huntingtons : Task - Classification"</span><span class="op">)</span>,</span>
<span>          title <span class="op">=</span> <span class="st">"Regression Table for Scores Model"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div id="tbl-w4-modresults" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;2: Regression Table for Scores Model</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Scores</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">95.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">83.61&nbsp;–&nbsp;106.39</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Diagnosis - Amnesic</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-30.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-46.11&nbsp;–&nbsp;-13.89</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Diagnosis - Huntingtons</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-16.11&nbsp;–&nbsp;16.11</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Task - Grammar</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-15.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-31.11&nbsp;–&nbsp;1.11</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.067</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Task - Classification</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-15.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-31.11&nbsp;–&nbsp;1.11</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.067</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Diagnosis - Amnesic :<br>
Task - Grammar</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">10.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-12.79&nbsp;–&nbsp;32.79</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.379</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Diagnosis - Huntingtons :<br>
Task - Grammar</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-40.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-62.79&nbsp;–&nbsp;-17.21</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Diagnosis - Amnesic :<br>
Task - Classification</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">20.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-2.79&nbsp;–&nbsp;42.79</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.083</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Diagnosis - Huntingtons :<br>
Task - Classification</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-35.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-57.79&nbsp;–&nbsp;-12.21</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.004</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">45</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.732 / 0.672</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<p>Plot interaction model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">plt_cog_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://interactions.jacob-long.com/reference/cat_plot.html">cat_plot</a></span><span class="op">(</span>model <span class="op">=</span> <span class="va">mdl_int</span>, </span>
<span>                  pred <span class="op">=</span> <span class="va">Diagnosis</span>, </span>
<span>                  modx <span class="op">=</span> <span class="va">Task</span>, </span>
<span>                  main.title <span class="op">=</span> <span class="st">"Scores across Diagnosis and Task"</span>,</span>
<span>                  x.label <span class="op">=</span> <span class="st">"Diagnosis"</span>,</span>
<span>                  y.label <span class="op">=</span> <span class="st">"Score"</span>,</span>
<span>                  legend.main <span class="op">=</span> <span class="st">"Task"</span><span class="op">)</span></span>
<span><span class="va">plt_cog_mdl</span></span></code></pre></div>
<div class="cell-output-display">
<div id="fig-cog-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_04_simp_pair_files/figure-html/fig-cog-4-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Interaction Plot</figcaption></figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Full regression results including 95% Confidence Intervals are shown in <a href="#tbl-w4-modresults">Table&nbsp;2</a>, and the interaction model is visually presented in <a href="#fig-cog-4">Figure&nbsp;2</a>. The <span class="math inline">\(F\)</span>-test for model utility was significant <span class="math inline">\((F(8, 36) = 12.28, p &lt; .001)\)</span>, and the model explained approximately 67% of the variability in Scores.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section><section id="contrast-analysis" class="level2"><h2 class="anchored" data-anchor-id="contrast-analysis">Contrast Analysis</h2>
<p>We will now begin by looking at each factor separately.</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>In terms of the diagnostic groups, we want to compare the individuals with amnesia to those with Huntingtons. This corresponds to a contrast with coefficients of 0, 1, and −1, for control, amnesic, and Huntingtons, respectively.</p>
<p>Similarly, in terms of the tasks, we want to compare the average of the two implicit memory tasks with the explicit memory task. This corresponds to a contrast with coefficients of 0.5, 0.5, and −1 for the three tasks.</p>
<p>When we are in presence of a significant interaction, the coefficients for a contrast between the means are found by multiplying each row coefficient with all column coefficients as shown below:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/contr_interaction.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Specify the coefficients to be used in the contrast analysis.</p>
<p>Formally state the contrast that the researchers were interested in as testable hypotheses.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>This can be done in <code>R</code> using:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Option 1</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Option 2</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">diag_coef</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'control'</span> <span class="op">=</span> <span class="fl">0</span>, <span class="st">'amnesic'</span> <span class="op">=</span> <span class="fl">1</span>, <span class="st">'huntingtons'</span> <span class="op">=</span> <span class="op">-</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">task_coef</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'grammar'</span> <span class="op">=</span> <span class="fl">0.5</span>, <span class="st">'classification'</span> <span class="op">=</span> <span class="fl">0.5</span>, <span class="st">'recognition'</span> <span class="op">=</span> <span class="op">-</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">contr_coef</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/outer.html">outer</a></span><span class="op">(</span><span class="va">diag_coef</span>, <span class="va">task_coef</span><span class="op">)</span></span>
<span><span class="va">contr_coef</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            grammar classification recognition
control         0.0            0.0           0
amnesic         0.5            0.5          -1
huntingtons    -0.5           -0.5           1</code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">diag_coef</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'control'</span> <span class="op">=</span> <span class="fl">0</span>, <span class="st">'amnesic'</span> <span class="op">=</span> <span class="fl">1</span>, <span class="st">'huntingtons'</span> <span class="op">=</span> <span class="op">-</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">task_coef</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'grammar'</span> <span class="op">=</span> <span class="fl">0.5</span>, <span class="st">'classification'</span> <span class="op">=</span> <span class="fl">0.5</span>, <span class="st">'recognition'</span> <span class="op">=</span> <span class="op">-</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">contr_coef</span> <span class="op">&lt;-</span> <span class="va">diag_coef</span> <span class="op"><a href="https://rdrr.io/r/base/outer.html">%o%</a></span> <span class="va">task_coef</span></span>
<span><span class="va">contr_coef</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            grammar classification recognition
control         0.0            0.0           0
amnesic         0.5            0.5          -1
huntingtons    -0.5           -0.5           1</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>The above coefficients correspond to the following hypotheses:</p>
<p><span class="math display">\[
H_0: \quad \left(\frac{\mu_{2,1} + \mu_{2,2}}{2} - \mu_{2,3} \right) - \left( \frac{\mu_{3,1} + \mu_{3,2}}{2} - \mu_{3,3} \right) = 0
\\  
\\  
H_1: \quad \left(\frac{\mu_{2,1} + \mu_{2,2}}{2} - \mu_{2,3} \right) - \left( \frac{\mu_{3,1} + \mu_{3,2}}{2} - \mu_{3,3} \right) \neq 0
\]</span></p>
<center>
<p>which can be equivalently specified as:</p>
</center>
<p><span class="math display">\[
H_0: \quad \frac{\mu_{2,1} + \mu_{2,2}}{2} - \mu_{2,3} \quad = \quad \frac{\mu_{3,1} + \mu_{3,2}}{2} - \mu_{3,3}
\\  
\\  
H_1: \quad \frac{\mu_{2,1} + \mu_{2,2}}{2} - \mu_{2,3} \quad \neq \quad  \frac{\mu_{3,1} + \mu_{3,2}}{2} - \mu_{3,3}
\]</span></p>
<p>both statements state that, in the population, the difference between the mean implicit memory and the explicit memory score is the same for individuals with amnesia and Huntingtons.</p>
<p>Note that the scores for the grammar and classification tasks have been averaged to obtain a single measure of ‘implicit memory’ score.</p>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Firstly, use <code><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans()</a></code> to obtain the estimated means and uncertainties for your factors.</p>
<p>Next, specify the coefficients of the comparison and run the contrast analysis, obtaining 95% confidence intervals.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>Now that we have the coefficients, let’s firstly call the <code>emmeans</code> function to get the estimated means of our groups (this is also helpful to look at the ordering of the groups):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">diag_task_mean</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="op">~</span> <span class="va">Diagnosis</span><span class="op">*</span><span class="va">Task</span><span class="op">)</span></span>
<span><span class="va">diag_task_mean</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Diagnosis   Task           emmean   SE df lower.CL upper.CL
 control     recognition        95 5.62 36     83.6    106.4
 amnesic     recognition        65 5.62 36     53.6     76.4
 huntingtons recognition        95 5.62 36     83.6    106.4
 control     grammar            80 5.62 36     68.6     91.4
 amnesic     grammar            60 5.62 36     48.6     71.4
 huntingtons grammar            40 5.62 36     28.6     51.4
 control     classification     80 5.62 36     68.6     91.4
 amnesic     classification     70 5.62 36     58.6     81.4
 huntingtons classification     45 5.62 36     33.6     56.4

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>Next, from <code>contr_coef</code>, insert the coefficients <strong>following the order specified by the rows of</strong> <code>diag_task_mean</code> above. That is, the first one should be for <code>control</code> <code>recognition</code> and have a value of 0, the second for <code>amnesic</code> <code>recognition</code> with a value of -1, and so on…</p>
<p>Let’s specify our weights, and give a name to this contrast (in this example ‘Research Hyp’):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">diag_task_comp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">diag_task_mean</span>, </span>
<span>                     method <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">'Research Hyp'</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">0.5</span>, <span class="op">-</span><span class="fl">0.5</span>, <span class="fl">0</span>, <span class="fl">0.5</span>, <span class="op">-</span><span class="fl">0.5</span><span class="op">)</span><span class="op">)</span></span>
<span>                     <span class="op">)</span></span></code></pre></div>
</div>
<p>Next, let’s look at the output via one of two ways:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">Option 1</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Option 2</a></li>
</ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#examine output</span></span>
<span><span class="va">diag_task_comp</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast     estimate   SE df t.ratio p.value
 Research Hyp     52.5 9.73 36   5.396  &lt;.0001</code></pre>
</div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#obtain confidence intervals</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">diag_task_comp</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast     estimate   SE df lower.CL upper.CL
 Research Hyp     52.5 9.73 36     32.8     72.2

Confidence level used: 0.95 </code></pre>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#examine summary output and state `infer = TRUE` to include confidence intervals</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">diag_task_comp</span>, infer <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast     estimate   SE df lower.CL upper.CL t.ratio p.value
 Research Hyp     52.5 9.73 36     32.8     72.2   5.396  &lt;.0001

Confidence level used: 0.95 </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>We performed a test against <span class="math inline">\(H_0: \quad \frac{\mu_{2,1} + \mu_{2,2}}{2} - \mu_{2,3} \quad = \quad \frac{\mu_{3,1} + \mu_{3,2}}{2} - \mu_{3,3}\)</span>. At the 5% significance level, there was evidence that individuals with Amnesia and Huntingtons did differ in the difference between implicit and explicit memory tasks <span class="math inline">\(t(36) = 5.40, p &lt; .001, \text{two-sided})\)</span>, and this difference was estimated to be 52.50. We are 95% confident that the difference in implicit and explicit memory scores between individuals with Amnesia and Huntingtons was between 32.80 to 72.20 points. Therefore, we can reject the null hypothesis that the difference in differences was equal to zero.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section><section id="simple-effects" class="level2"><h2 class="anchored" data-anchor-id="simple-effects">Simple Effects</h2>
<p>By considering the simple effects<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, we can identify at which levels of the interacting condition we see different effects.</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Examine the simple effects for Task at each level of Diagnosis; and then the simple effects for Diagnosis at each level of Task.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">Simple Effects of Task</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Simple Effects of Diagnosis</a></li>
</ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<p>From <code>mdl_int_simple1</code> we can see the differences between between tasks for each diagnosis group:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl_int_simple1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="va">diag_task_mean</span>, simple <span class="op">=</span> <span class="st">"Task"</span><span class="op">)</span></span>
<span><span class="va">mdl_int_simple1</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Diagnosis = control:
 contrast                     estimate   SE df t.ratio p.value
 recognition - grammar              15 7.94 36   1.888  0.1567
 recognition - classification       15 7.94 36   1.888  0.1567
 grammar - classification            0 7.94 36   0.000  1.0000

Diagnosis = amnesic:
 contrast                     estimate   SE df t.ratio p.value
 recognition - grammar               5 7.94 36   0.629  0.8050
 recognition - classification       -5 7.94 36  -0.629  0.8050
 grammar - classification          -10 7.94 36  -1.259  0.4273

Diagnosis = huntingtons:
 contrast                     estimate   SE df t.ratio p.value
 recognition - grammar              55 7.94 36   6.923  &lt;.0001
 recognition - classification       50 7.94 36   6.294  &lt;.0001
 grammar - classification           -5 7.94 36  -0.629  0.8050

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<p>From <code>mdl_int_simple2</code> we can see the differences between diagnoses for each task group:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl_int_simple2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="va">diag_task_mean</span>, simple <span class="op">=</span> <span class="st">"Diagnosis"</span><span class="op">)</span></span>
<span><span class="va">mdl_int_simple2</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Task = recognition:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           30 7.94 36   3.776  0.0016
 control - huntingtons        0 7.94 36   0.000  1.0000
 amnesic - huntingtons      -30 7.94 36  -3.776  0.0016

Task = grammar:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           20 7.94 36   2.518  0.0424
 control - huntingtons       40 7.94 36   5.035  &lt;.0001
 amnesic - huntingtons       20 7.94 36   2.518  0.0424

Task = classification:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           10 7.94 36   1.259  0.4273
 control - huntingtons       35 7.94 36   4.406  0.0003
 amnesic - huntingtons       25 7.94 36   3.147  0.0091

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Visualise the interaction, displaying two plots - one with Diagnosis on the x-axis, and the other with Task on the x-axis.</p>
<p>Considering the simple effects that you noted above, identify the significant effects and match them to the corresponding points of your interaction plot.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>To visualise the interaction, you can use <code><a href="https://rdrr.io/pkg/emmeans/man/emmip.html">emmip()</a></code>.</p>
<p>Recall that the <strong>patchwork</strong> package allows us to arrange multiple plots using either <code>/</code> or <code>|</code> or <code>+</code></p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">Simple Effects of Task</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">Simple Effects of Diagnosis</a></li>
</ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">plt_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmip.html">emmip</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="va">Diagnosis</span> <span class="op">~</span> <span class="va">Task</span>, CIs <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">plt_1</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_04_simp_pair_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>For the simple effects of task (see <code>plt_1</code>), we saw the significant differences (those for which <span class="math inline">\(p&lt;.05\)</span>):</p>
<ul>
<li>Only in the Huntingtons group, between recognition &amp; grammar and recognition &amp; classification tasks
<ul>
<li>left-most blue point compared to the middle blue point, and then compared to the right-most blue point</li>
</ul>
</li>
</ul>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">plt_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmip.html">emmip</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="va">Task</span> <span class="op">~</span> <span class="va">Diagnosis</span>, CIs <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">plt_2</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_04_simp_pair_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>For the simple effects of Diagnosis (see <code>plt_2</code>), we saw significant differences (those for which <span class="math inline">\(p&lt;.05\)</span>):</p>
<ul>
<li>in the recognition task, between control &amp; amnesic
<ul>
<li>left-most red point to middle red point</li>
</ul>
</li>
<li>in the recognition task, between amnesic &amp; huntingtons
<ul>
<li>middle red-point to right-most red point</li>
</ul>
</li>
<li>in the grammar task, between control &amp; amnesic
<ul>
<li>left-most green point to middle green point</li>
</ul>
</li>
<li>in the grammar task, between control &amp; huntingtons
<ul>
<li>left-most green point to right-most green point</li>
</ul>
</li>
<li>in the grammar task, between amnesic &amp; huntingtons
<ul>
<li>middle green point to right-most green point</li>
</ul>
</li>
<li>in the classification task, between control &amp; huntingtons
<ul>
<li>left-most blue point to right-most blue point</li>
</ul>
</li>
<li>in the classification task, between amnesic &amp; huntingtons
<ul>
<li>middle blue point to right-most blue point</li>
</ul>
</li>
</ul>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section><section id="pairwise-comparisons-multiple-corrections" class="level2"><h2 class="anchored" data-anchor-id="pairwise-comparisons-multiple-corrections">Pairwise Comparisons &amp; Multiple Corrections</h2>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Conduct exploratory pairwise comparisons to compare all levels of Diagnosis with all levels of Task, applying no correction (note that Tukey will be automatically applied since we are comparing groups of means, so you will need to overwrite this).</p>
<p>Without adjusting our <span class="math inline">\(\alpha\)</span> (or <span class="math inline">\(p\)</span>-value), why might any inferences drawn from your output be problematic?</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You can specify the adjustment using <code>adjust = "</code>. Possible options include:</p>
<ul>
<li><code>adjust = "none"</code></li>
<li><code>adjust =  "bonferroni"</code></li>
<li><code>adjust = "sidak"</code></li>
<li><code>adjust = "Tukey"</code></li>
<li><code>adjust = scheffe"</code></li>
</ul>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">pairs_res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="va">diag_task_mean</span>, adjust <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span>
<span><span class="va">pairs_res</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                             estimate   SE df t.ratio
 control recognition - amnesic recognition                  30 7.94 36   3.776
 control recognition - huntingtons recognition               0 7.94 36   0.000
 control recognition - control grammar                      15 7.94 36   1.888
 control recognition - amnesic grammar                      35 7.94 36   4.406
 control recognition - huntingtons grammar                  55 7.94 36   6.923
 control recognition - control classification               15 7.94 36   1.888
 control recognition - amnesic classification               25 7.94 36   3.147
 control recognition - huntingtons classification           50 7.94 36   6.294
 amnesic recognition - huntingtons recognition             -30 7.94 36  -3.776
 amnesic recognition - control grammar                     -15 7.94 36  -1.888
 amnesic recognition - amnesic grammar                       5 7.94 36   0.629
 amnesic recognition - huntingtons grammar                  25 7.94 36   3.147
 amnesic recognition - control classification              -15 7.94 36  -1.888
 amnesic recognition - amnesic classification               -5 7.94 36  -0.629
 amnesic recognition - huntingtons classification           20 7.94 36   2.518
 huntingtons recognition - control grammar                  15 7.94 36   1.888
 huntingtons recognition - amnesic grammar                  35 7.94 36   4.406
 huntingtons recognition - huntingtons grammar              55 7.94 36   6.923
 huntingtons recognition - control classification           15 7.94 36   1.888
 huntingtons recognition - amnesic classification           25 7.94 36   3.147
 huntingtons recognition - huntingtons classification       50 7.94 36   6.294
 control grammar - amnesic grammar                          20 7.94 36   2.518
 control grammar - huntingtons grammar                      40 7.94 36   5.035
 control grammar - control classification                    0 7.94 36   0.000
 control grammar - amnesic classification                   10 7.94 36   1.259
 control grammar - huntingtons classification               35 7.94 36   4.406
 amnesic grammar - huntingtons grammar                      20 7.94 36   2.518
 amnesic grammar - control classification                  -20 7.94 36  -2.518
 amnesic grammar - amnesic classification                  -10 7.94 36  -1.259
 amnesic grammar - huntingtons classification               15 7.94 36   1.888
 huntingtons grammar - control classification              -40 7.94 36  -5.035
 huntingtons grammar - amnesic classification              -30 7.94 36  -3.776
 huntingtons grammar - huntingtons classification           -5 7.94 36  -0.629
 control classification - amnesic classification            10 7.94 36   1.259
 control classification - huntingtons classification        35 7.94 36   4.406
 amnesic classification - huntingtons classification        25 7.94 36   3.147
 p.value
  0.0006
  1.0000
  0.0671
  0.0001
  &lt;.0001
  0.0671
  0.0033
  &lt;.0001
  0.0006
  0.0671
  0.5331
  0.0033
  0.0671
  0.5331
  0.0164
  0.0671
  0.0001
  &lt;.0001
  0.0671
  0.0033
  &lt;.0001
  0.0164
  &lt;.0001
  1.0000
  0.2162
  0.0001
  0.0164
  0.0164
  0.2162
  0.0671
  &lt;.0001
  0.0006
  0.5331
  0.2162
  0.0001
  0.0033</code></pre>
</div>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#can also plot if you'd like:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">pairs_res</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_04_simp_pair_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>From the above, we can see comparisons for all different possible pairs of diagnosis-task combinations.</p>
<p>In total, there are 9 different estimates, but comparing them all means that we have 36 comparisons being tested! By not adjusting our <span class="math inline">\(p\)</span>-value, we are increasing the experimentwise Type I error rate - we could wrongly reject the null hypothesis at a much higher rate than 5/100 (or 1/20 as is assumed when <span class="math inline">\(\alpha = .05\)</span>). To overcome this, we might adjust and determine a result to be statistically significant if <span class="math inline">\(p &lt; .005\)</span>, as opposed to <span class="math inline">\(p &lt; .05\)</span>, depending on how many tests are in our family of tests).</p>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Select an appropriate method to adjust for multiple comparisons, and then obtain confidence intervals.</p>
<p>Comment on how these <span class="math inline">\(p\)</span>-values differ from your raw (i.e., unadjusted) <span class="math inline">\(p\)</span>-values.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<p>Note what the functions in <code>R</code> do is adjust the <span class="math inline">\(p\)</span>-value, rather than the <span class="math inline">\(\alpha\)</span>.</p>
<p>Since we’re interested in all pairwise comparisons of means, the Tukey adjustment might be a sensible approach. However, we’ll also show the Bonferroni to show how it differs (note, in practice you would only apply one correction and justify this choice based on your design - we are only applying two to note how they differ!)</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">Tukey</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Bonferroni</a></li>
</ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">diag_task_mean</span>, method <span class="op">=</span> <span class="st">"pairwise"</span>, adjust<span class="op">=</span><span class="st">"Tukey"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                             estimate   SE df t.ratio
 control recognition - amnesic recognition                  30 7.94 36   3.776
 control recognition - huntingtons recognition               0 7.94 36   0.000
 control recognition - control grammar                      15 7.94 36   1.888
 control recognition - amnesic grammar                      35 7.94 36   4.406
 control recognition - huntingtons grammar                  55 7.94 36   6.923
 control recognition - control classification               15 7.94 36   1.888
 control recognition - amnesic classification               25 7.94 36   3.147
 control recognition - huntingtons classification           50 7.94 36   6.294
 amnesic recognition - huntingtons recognition             -30 7.94 36  -3.776
 amnesic recognition - control grammar                     -15 7.94 36  -1.888
 amnesic recognition - amnesic grammar                       5 7.94 36   0.629
 amnesic recognition - huntingtons grammar                  25 7.94 36   3.147
 amnesic recognition - control classification              -15 7.94 36  -1.888
 amnesic recognition - amnesic classification               -5 7.94 36  -0.629
 amnesic recognition - huntingtons classification           20 7.94 36   2.518
 huntingtons recognition - control grammar                  15 7.94 36   1.888
 huntingtons recognition - amnesic grammar                  35 7.94 36   4.406
 huntingtons recognition - huntingtons grammar              55 7.94 36   6.923
 huntingtons recognition - control classification           15 7.94 36   1.888
 huntingtons recognition - amnesic classification           25 7.94 36   3.147
 huntingtons recognition - huntingtons classification       50 7.94 36   6.294
 control grammar - amnesic grammar                          20 7.94 36   2.518
 control grammar - huntingtons grammar                      40 7.94 36   5.035
 control grammar - control classification                    0 7.94 36   0.000
 control grammar - amnesic classification                   10 7.94 36   1.259
 control grammar - huntingtons classification               35 7.94 36   4.406
 amnesic grammar - huntingtons grammar                      20 7.94 36   2.518
 amnesic grammar - control classification                  -20 7.94 36  -2.518
 amnesic grammar - amnesic classification                  -10 7.94 36  -1.259
 amnesic grammar - huntingtons classification               15 7.94 36   1.888
 huntingtons grammar - control classification              -40 7.94 36  -5.035
 huntingtons grammar - amnesic classification              -30 7.94 36  -3.776
 huntingtons grammar - huntingtons classification           -5 7.94 36  -0.629
 control classification - amnesic classification            10 7.94 36   1.259
 control classification - huntingtons classification        35 7.94 36   4.406
 amnesic classification - huntingtons classification        25 7.94 36   3.147
 p.value
  0.0149
  1.0000
  0.6257
  0.0026
  &lt;.0001
  0.6257
  0.0711
  &lt;.0001
  0.0149
  0.6257
  0.9993
  0.0711
  0.6257
  0.9993
  0.2575
  0.6257
  0.0026
  &lt;.0001
  0.6257
  0.0711
  &lt;.0001
  0.2575
  0.0004
  1.0000
  0.9367
  0.0026
  0.2575
  0.2575
  0.9367
  0.6257
  0.0004
  0.0149
  0.9993
  0.9367
  0.0026
  0.0711

P value adjustment: tukey method for comparing a family of 9 estimates </code></pre>
</div>
</div>
<p>Note that 8 of the comparisons are no longer significant when using Tukey’s adjustment, suggesting that these might have been (when using no adjustment) Type I errors!</p>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">diag_task_mean</span>, method <span class="op">=</span> <span class="st">"pairwise"</span>, adjust<span class="op">=</span><span class="st">"bonferroni"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                             estimate   SE df t.ratio
 control recognition - amnesic recognition                  30 7.94 36   3.776
 control recognition - huntingtons recognition               0 7.94 36   0.000
 control recognition - control grammar                      15 7.94 36   1.888
 control recognition - amnesic grammar                      35 7.94 36   4.406
 control recognition - huntingtons grammar                  55 7.94 36   6.923
 control recognition - control classification               15 7.94 36   1.888
 control recognition - amnesic classification               25 7.94 36   3.147
 control recognition - huntingtons classification           50 7.94 36   6.294
 amnesic recognition - huntingtons recognition             -30 7.94 36  -3.776
 amnesic recognition - control grammar                     -15 7.94 36  -1.888
 amnesic recognition - amnesic grammar                       5 7.94 36   0.629
 amnesic recognition - huntingtons grammar                  25 7.94 36   3.147
 amnesic recognition - control classification              -15 7.94 36  -1.888
 amnesic recognition - amnesic classification               -5 7.94 36  -0.629
 amnesic recognition - huntingtons classification           20 7.94 36   2.518
 huntingtons recognition - control grammar                  15 7.94 36   1.888
 huntingtons recognition - amnesic grammar                  35 7.94 36   4.406
 huntingtons recognition - huntingtons grammar              55 7.94 36   6.923
 huntingtons recognition - control classification           15 7.94 36   1.888
 huntingtons recognition - amnesic classification           25 7.94 36   3.147
 huntingtons recognition - huntingtons classification       50 7.94 36   6.294
 control grammar - amnesic grammar                          20 7.94 36   2.518
 control grammar - huntingtons grammar                      40 7.94 36   5.035
 control grammar - control classification                    0 7.94 36   0.000
 control grammar - amnesic classification                   10 7.94 36   1.259
 control grammar - huntingtons classification               35 7.94 36   4.406
 amnesic grammar - huntingtons grammar                      20 7.94 36   2.518
 amnesic grammar - control classification                  -20 7.94 36  -2.518
 amnesic grammar - amnesic classification                  -10 7.94 36  -1.259
 amnesic grammar - huntingtons classification               15 7.94 36   1.888
 huntingtons grammar - control classification              -40 7.94 36  -5.035
 huntingtons grammar - amnesic classification              -30 7.94 36  -3.776
 huntingtons grammar - huntingtons classification           -5 7.94 36  -0.629
 control classification - amnesic classification            10 7.94 36   1.259
 control classification - huntingtons classification        35 7.94 36   4.406
 amnesic classification - huntingtons classification        25 7.94 36   3.147
 p.value
  0.0207
  1.0000
  1.0000
  0.0033
  &lt;.0001
  1.0000
  0.1190
  &lt;.0001
  0.0207
  1.0000
  1.0000
  0.1190
  1.0000
  1.0000
  0.5907
  1.0000
  0.0033
  &lt;.0001
  1.0000
  0.1190
  &lt;.0001
  0.5907
  0.0005
  1.0000
  1.0000
  0.0033
  0.5907
  0.5907
  1.0000
  1.0000
  0.0005
  0.0207
  1.0000
  1.0000
  0.0033
  0.1190

P value adjustment: bonferroni method for 36 tests </code></pre>
</div>
</div>
<p>The first Bonferroni adjusted <span class="math inline">\(p\)</span>-value is 0.0207.</p>
<p>The raw (unadjusted) <span class="math inline">\(p\)</span>-value from the previous question was 0.0005759265.</p>
<p>The Bonferroni method simply multiplies the ‘raw’ <span class="math inline">\(p\)</span>-value by the number of the tests, which we know is 36.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fl">0.0005759265</span> <span class="op">*</span> <span class="fl">36</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02073335</code></pre>
</div>
</div>
<p>In terms of differences in Bonferroni to raw <span class="math inline">\(p\)</span>-values, they are thus 36 times the size.</p>
<p>One benefit of Bonferroni is that it can be applied to any set of <span class="math inline">\(p\)</span>-values, whereas Tukey only applies when comparing the means of levels of a factor. The downside, however, is that it may be overly conservative (i.e.&nbsp;reduce our power to detect an effect that is truly there).</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="divider div-transparent div-dot">

</div>
</section></section><section id="compile-report" class="level1"><h1>Compile Report</h1>
<div class="question-begin">
Compile Report
</div>
<div class="question-body">
<p>Knit your report to PDF, and check over your work. To do so, you should make sure:</p>
<ul>
<li>Only the output you want your reader to see is visible (e.g., do you want to hide your code?)</li>
<li>Check that the <strong>tinytex</strong> package is installed</li>
<li>Ensure that the ‘yaml’ (bit at the very top of your document) looks something like this:</li>
</ul>
<pre><code>---
title: "this is my report title"
author: "B1234506"
date: "07/09/2024"
output: bookdown::pdf_document2
---</code></pre>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What to do if you cannot knit to PDF
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If you are having issues knitting directly to PDF, try the following:</p>
<ul>
<li>Knit to HTML file<br>
</li>
<li>Open your HTML in a web-browser (e.g.&nbsp;Chrome, Firefox)<br>
</li>
<li>Print to PDF (Ctrl+P, then choose to save to PDF)<br>
</li>
<li>Open file to check formatting</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hiding Code and/or Output
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true">Hiding R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false">Hiding R Output</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-3" role="tab" aria-controls="tabset-8-3" aria-selected="false">Hiding R Code and Output</a></li>
</ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<p>To not show the code of an R code chunk, and only show the output, write:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode markdown"><code class="sourceCode markdown"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE}</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co"># code goes here</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code></pre></div>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<p>To show the code of an R code chunk, but hide the output, write:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode markdown"><code class="sourceCode markdown"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='hide'}</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># code goes here</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code></pre></div>
</div>
<div id="tabset-8-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-3-tab">
<p>To hide both code and output of an R code chunk, write:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode markdown"><code class="sourceCode markdown"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, include=FALSE}</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co"># code goes here</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code></pre></div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tinytex
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You must make sure you have <strong>tinytex</strong> installed in R so that you can “Knit” your Rmd document to a PDF file:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"tinytex"</span><span class="op">)</span></span>
<span><span class="fu">tinytex</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/tinytex/man/install_tinytex.html">install_tinytex</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-13" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')"> Solution </span>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<p>You should end up with a PDF file. If you have followed the above instructions and still have issues with knitting, speak with a Tutor.</p>
</div>
<p class="solution-end">
</p>


</section><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1"><p>simple effects are the effects of one variable <em>at a specific level of another variable</em><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2023 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>