<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Write Up &amp; Block 3 Recap</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-circle-right')) {
    f.classList.add('fa-circle-down')
    f.classList.remove('fa-circle-right')
} else {
    f.classList.add('fa-circle-right')
    f.classList.remove('fa-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Semester 2</li><li class="breadcrumb-item"><a href="./2_01_int1_nc.html">Interaction Models</a></li><li class="breadcrumb-item"><a href="./2_05_writeup_recap_blk3.html">Write Up &amp; Block 3 Recap</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DAPR2</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Semester 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Intro to Linear Models</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_01_slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_02_mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_03_mlr_stz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression &amp; Standardization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_04_model_fit_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model Fit and Comparisons</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_05_writeup_recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Write Up &amp; Block 1 Recap</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Analysing and Evaluating Experimental Studies</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_06_dummy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dummy Coding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_07_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Effects Coding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_08_assump_diag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assumptions and Diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_09_bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrapping</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_10_writeup_recap_blk2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Write Up &amp; Block 2 Recap</span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Semester 2</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Interaction Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_01_int1_nc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactions I: Num x Cat</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_02_int2_nn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactions II: Num x Num</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_03_int3_cc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactions III: Cat x Cat</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_04_simp_pair.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple Effects, Pairwise Comparisons, &amp; Corrections</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_05_writeup_recap_blk3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Write Up &amp; Block 3 Recap</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Advanced Topics for LM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_06_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sample Size and Power Analysis</span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#section-a-write-up" id="toc-section-a-write-up" class="nav-link active" data-scroll-target="#section-a-write-up">Section A: Write-Up</a>
  <ul class="collapse">
<li>
<a href="#study-overview" id="toc-study-overview" class="nav-link" data-scroll-target="#study-overview">Study Overview</a>
  <ul class="collapse">
<li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#analysis-code" id="toc-analysis-code" class="nav-link" data-scroll-target="#analysis-code">Analysis Code</a></li>
  <li><a href="#the-3-act-structure" id="toc-the-3-act-structure" class="nav-link" data-scroll-target="#the-3-act-structure">The 3-Act Structure</a></li>
  </ul>
</li>
  </ul>
</li>
  <li><a href="#section-b-weeks-1-5-recap" id="toc-section-b-weeks-1-5-recap" class="nav-link" data-scroll-target="#section-b-weeks-1-5-recap">Section B: Weeks 1-5 Recap</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Write Up &amp; Block 3 Recap</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand how to write-up and provide interpretation of a 4x2 factorial ANOVA<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>
</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed Labs 1-4</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>psych</strong></li>
<li><strong>kableExtra</strong></li>
<li><strong>sjPlot</strong></li>
<li><strong>interactions</strong></li>
<li><strong>emmeans</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/laptop_vs_longhand.csv">here</a> or read it in via this link https://uoepsy.github.io/data/laptop_vs_longhand.csv</p>
</section>
</div>
<section id="section-a-write-up" class="level1"><h1>Section A: Write-Up</h1>
<p>In this lab you will be presented with the output from a statistical analysis, and your job will be to write-up and present the results. We’re going to use two simulated datasets based on a paper (the same two that you have worked on in lectures this week) concerning academic outcomes, student/class characteristics, and attendance.</p>
<p>The aim in writing should be that a reader is able to more or less replicate your analyses <strong>without</strong> referring to your R code. This requires detailing all of the steps you took in conducting the analysis.</p>
<p>The point of using RMarkdown is that you can pull your results <strong>directly</strong> from the code. If your analysis changes, so does your report!</p>
<p>Make sure that your final report doesn’t show any R functions or code. Remember you are interpreting and reporting your results in text, tables, or plots, targeting a generic reader who may use different software or may not know R at all. If you need a reminder on how to hide code, format tables, etc., make sure to review the <a href="https://uoepsy.github.io//rmd-bootcamp/">rmd bootcamp</a>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important - Write-Up Examples &amp; Plagiarism
</div>
</div>
<div class="callout-body-container callout-body">
<p>The example write-up sections included below are not <strong>perfect</strong> - they instead should give you a good example of what information you should include within each section, and how to structure this. For example, some information is missing (e.g., description of data checks, interpretation of descriptive statistics), some information could be presented more clearly (e.g., variable names in tables, table/figure titles/captions, and rationales for choices), and writing could be more concise in places (e.g., discussion section is quite long).</p>
<p>Further, <strong>you must not copy any of the write-up included below for future reports</strong> - if you do, you will be committing plagiarism, and this type of academic misconduct is taken very seriously by the University. You can find out more <a href="https://www.ed.ac.uk/academic-services/students/conduct/academic-misconduct">here</a>.</p>
</div>
</div>
<section id="study-overview" class="level2"><h2 class="anchored" data-anchor-id="study-overview">Study Overview</h2>
<blockquote class="blockquote">
<p><strong>Research Aim</strong></p>
<p>Explore the associations among study time and note-taking medium on test scores.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Research Questions</strong></p>
<ul>
<li>RQ1: Do differences in test scores between study conditions differ by the note-taking medium used?</li>
<li>RQ2: Are there differences in test scores between participants when comparing pairs of study and note-taking conditions? If so, what are these specific differences?</li>
</ul>
</blockquote>
<div class="optional-begin">
<span id="opt-start-1" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Note Taking: Data Codebook</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>The data used for this write-up exercise are simulated, drawing on a research paper that explored the association between student note taking, and performance when answering different types of questions. The simulated data are loosely based on the findings of this work, and acted to expand upon the methods and results reported in the paper:</p>
<p>Mueller, P. A., &amp; Oppenheimer, D. M. (2014). The pen is mightier than the keyboard: Advantages of longhand over laptop note taking. <em>Psychological Science, 25</em>(6), 1159–1168. <a href="https://doi.org/10.1177/0956797614524581">https://doi.org/10.1177/0956797614524581</a></p>
<p>In the current study, participants were invited to take part in a study investigating the the medium of note taking and study time on test scores. The sample comprised of 160 students who took notes on a lecture via one of two mediums - either on a laptop or longhand (i.e., using pen and paper). After watching the lecture and taking notes, they then randomly allocated to one of four study time conditions, either engaging in no, minimal, moderate, or extensive study of the notes taken on their assigned medium. After engaging in study for their allocated time, participants took a test on the lecture content. The test involved a series of questions, where participants could score a maximum of 100 points.</p>
<p><strong>Data Dictionary</strong></p>
<p>The data in <code>laptop_vs_longhand.csv</code> contain three attributes collected from a simulated sample of <span class="math inline">\(n=160\)</span> hypothetical individuals, and includes:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="pqxkbfqhgj" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#pqxkbfqhgj table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#pqxkbfqhgj thead, #pqxkbfqhgj tbody, #pqxkbfqhgj tfoot, #pqxkbfqhgj tr, #pqxkbfqhgj td, #pqxkbfqhgj th {
  border-style: none;
}

#pqxkbfqhgj p {
  margin: 0;
  padding: 0;
}

#pqxkbfqhgj .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#pqxkbfqhgj .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#pqxkbfqhgj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#pqxkbfqhgj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#pqxkbfqhgj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#pqxkbfqhgj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#pqxkbfqhgj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#pqxkbfqhgj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#pqxkbfqhgj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#pqxkbfqhgj .gt_spanner_row {
  border-bottom-style: hidden;
}

#pqxkbfqhgj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#pqxkbfqhgj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#pqxkbfqhgj .gt_from_md > :first-child {
  margin-top: 0;
}

#pqxkbfqhgj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#pqxkbfqhgj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#pqxkbfqhgj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#pqxkbfqhgj .gt_row_group_first td {
  border-top-width: 2px;
}

#pqxkbfqhgj .gt_row_group_first th {
  border-top-width: 2px;
}

#pqxkbfqhgj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#pqxkbfqhgj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#pqxkbfqhgj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#pqxkbfqhgj .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#pqxkbfqhgj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_left {
  text-align: left;
}

#pqxkbfqhgj .gt_center {
  text-align: center;
}

#pqxkbfqhgj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#pqxkbfqhgj .gt_font_normal {
  font-weight: normal;
}

#pqxkbfqhgj .gt_font_bold {
  font-weight: bold;
}

#pqxkbfqhgj .gt_font_italic {
  font-style: italic;
}

#pqxkbfqhgj .gt_super {
  font-size: 65%;
}

#pqxkbfqhgj .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#pqxkbfqhgj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#pqxkbfqhgj .gt_indent_1 {
  text-indent: 5px;
}

#pqxkbfqhgj .gt_indent_2 {
  text-indent: 10px;
}

#pqxkbfqhgj .gt_indent_3 {
  text-indent: 15px;
}

#pqxkbfqhgj .gt_indent_4 {
  text-indent: 20px;
}

#pqxkbfqhgj .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Variable">Variable</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Description">Description</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="Variable" class="gt_row gt_left">test_score</td>
<td headers="Description" class="gt_row gt_left">Test Score (0-100)</td>
</tr>
<tr>
<td headers="Variable" class="gt_row gt_left">medium</td>
<td headers="Description" class="gt_row gt_left">Medium of note-taking (levels = Longhand, Laptop)</td>
</tr>
<tr>
<td headers="Variable" class="gt_row gt_left">study</td>
<td headers="Description" class="gt_row gt_left">Study time (levels = No, Minimal, Moderate, Extensive)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="xqiwkyfqay" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#xqiwkyfqay table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#xqiwkyfqay thead, #xqiwkyfqay tbody, #xqiwkyfqay tfoot, #xqiwkyfqay tr, #xqiwkyfqay td, #xqiwkyfqay th {
  border-style: none;
}

#xqiwkyfqay p {
  margin: 0;
  padding: 0;
}

#xqiwkyfqay .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xqiwkyfqay .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#xqiwkyfqay .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xqiwkyfqay .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xqiwkyfqay .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xqiwkyfqay .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xqiwkyfqay .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xqiwkyfqay .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xqiwkyfqay .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xqiwkyfqay .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xqiwkyfqay .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xqiwkyfqay .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xqiwkyfqay .gt_spanner_row {
  border-bottom-style: hidden;
}

#xqiwkyfqay .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#xqiwkyfqay .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xqiwkyfqay .gt_from_md > :first-child {
  margin-top: 0;
}

#xqiwkyfqay .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xqiwkyfqay .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xqiwkyfqay .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#xqiwkyfqay .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#xqiwkyfqay .gt_row_group_first td {
  border-top-width: 2px;
}

#xqiwkyfqay .gt_row_group_first th {
  border-top-width: 2px;
}

#xqiwkyfqay .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqiwkyfqay .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#xqiwkyfqay .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#xqiwkyfqay .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xqiwkyfqay .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqiwkyfqay .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xqiwkyfqay .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#xqiwkyfqay .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xqiwkyfqay .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xqiwkyfqay .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xqiwkyfqay .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqiwkyfqay .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xqiwkyfqay .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqiwkyfqay .gt_left {
  text-align: left;
}

#xqiwkyfqay .gt_center {
  text-align: center;
}

#xqiwkyfqay .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xqiwkyfqay .gt_font_normal {
  font-weight: normal;
}

#xqiwkyfqay .gt_font_bold {
  font-weight: bold;
}

#xqiwkyfqay .gt_font_italic {
  font-style: italic;
}

#xqiwkyfqay .gt_super {
  font-size: 65%;
}

#xqiwkyfqay .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#xqiwkyfqay .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#xqiwkyfqay .gt_indent_1 {
  text-indent: 5px;
}

#xqiwkyfqay .gt_indent_2 {
  text-indent: 10px;
}

#xqiwkyfqay .gt_indent_3 {
  text-indent: 15px;
}

#xqiwkyfqay .gt_indent_4 {
  text-indent: 20px;
}

#xqiwkyfqay .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="test_score">test_score</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="medium">medium</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="study">study</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="test_score" class="gt_row gt_right">47.47812</td>
<td headers="medium" class="gt_row gt_left">Laptop</td>
<td headers="study" class="gt_row gt_left">No</td>
</tr>
<tr>
<td headers="test_score" class="gt_row gt_right">50.41772</td>
<td headers="medium" class="gt_row gt_left">Laptop</td>
<td headers="study" class="gt_row gt_left">No</td>
</tr>
<tr>
<td headers="test_score" class="gt_row gt_right">49.88763</td>
<td headers="medium" class="gt_row gt_left">Laptop</td>
<td headers="study" class="gt_row gt_left">No</td>
</tr>
<tr>
<td headers="test_score" class="gt_row gt_right">48.47961</td>
<td headers="medium" class="gt_row gt_left">Laptop</td>
<td headers="study" class="gt_row gt_left">No</td>
</tr>
<tr>
<td headers="test_score" class="gt_row gt_right">48.44368</td>
<td headers="medium" class="gt_row gt_left">Laptop</td>
<td headers="study" class="gt_row gt_left">No</td>
</tr>
<tr>
<td headers="test_score" class="gt_row gt_right">48.02715</td>
<td headers="medium" class="gt_row gt_left">Laptop</td>
<td headers="study" class="gt_row gt_left">No</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<section id="setup" class="level3"><h3 class="anchored" data-anchor-id="setup">Setup</h3>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the laptop_vs_longhand dataset into R, assigning it to an object named <code>notes</code>
</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://personality-project.org/r/psych/">psych</a></span><span class="op">)</span> </span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://strengejacke.github.io/sjPlot/">sjPlot</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://interactions.jacob-long.com">interactions</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/rvlenth/emmeans">emmeans</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co">#read in data</span></span>
<span><span class="va">notes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/laptop_vs_longhand.csv"</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="analysis-code" class="level3"><h3 class="anchored" data-anchor-id="analysis-code">Analysis Code</h3>
<p>Try to answer the research question above without referring to the provided analysis code below, and then check how your script matches up - is there anything you missed or done differently? If so, discuss the differences with a tutor - there are lots of ways to code to the same solution!</p>
<div class="optional-begin">
<span id="opt-start-3" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-3', 'opt-start-3')"> <span class="olab">Provided Analysis Code</span></span>
</div>
<div id="opt-body-3" class="optional-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">######Step 1 is always to read in the data, then to explore, check, describe, and visualise it.</span></span>
<span></span>
<span><span class="co">#check coding of variables - are they coded as they should be?</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">notes</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [160 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ test_score: num [1:160] 47.5 50.4 49.9 48.5 48.4 ...
 $ medium    : chr [1:160] "Laptop" "Laptop" "Laptop" "Laptop" ...
 $ study     : chr [1:160] "No" "No" "No" "No" ...
 - attr(*, "spec")=
  .. cols(
  ..   test_score = col_double(),
  ..   medium = col_character(),
  ..   study = col_character()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">notes</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  test_score medium study
       &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;
1       47.5 Laptop No   
2       50.4 Laptop No   
3       49.9 Laptop No   
4       48.5 Laptop No   
5       48.4 Laptop No   
6       48.0 Laptop No   </code></pre>
</div>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#check for NAs - none in dataset, so no missing values</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">notes</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
FALSE 
  480 </code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#make variables factors</span></span>
<span><span class="va">notes</span> <span class="op">&lt;-</span> <span class="va">notes</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>medium <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">medium</span><span class="op">)</span>,</span>
<span>           study <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">study</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#create descriptives table</span></span>
<span><span class="va">descript</span> <span class="op">&lt;-</span> <span class="va">notes</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">study</span>, <span class="va">medium</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>   <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>       M_Score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">test_score</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>       SD_Score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">test_score</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>       SE_Score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">test_score</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>       Min_Score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">test_score</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>       Max_Score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">test_score</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span><span class="va">descript</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 7
# Groups:   study [4]
  study     medium   M_Score SD_Score SE_Score Min_Score Max_Score
  &lt;fct&gt;     &lt;fct&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 No        Laptop      48.1        2     0.45      44.9      51.2
2 No        Longhand    51.0        2     0.45      48.0      54.9
3 Minimal   Laptop      55.6        2     0.45      52.1      60.1
4 Minimal   Longhand    60.9        2     0.45      57.8      65.3
5 Moderate  Laptop      59.3        2     0.45      55.8      63.0
6 Moderate  Longhand    80.7        2     0.45      76.3      84.6
7 Extensive Laptop      61.2        2     0.45      56.9      64.3
8 Extensive Longhand    90.6        2     0.45      86.8      94.3</code></pre>
</div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#boxplot</span></span>
<span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">notes</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">study</span>, y <span class="op">=</span> <span class="va">test_score</span>, color <span class="op">=</span> <span class="va">medium</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/lims.html">ylim</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">100</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Study Condition"</span>, y <span class="op">=</span> <span class="st">"Test Score"</span><span class="op">)</span></span>
<span><span class="va">p1</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#plot showing the mean score for each condition</span></span>
<span><span class="co"># p2 is useful to notice that lines do not run in parallel - suggests interaction</span></span>
<span><span class="va">p2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">descript</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">study</span>, y <span class="op">=</span> <span class="va">M_Score</span>, color <span class="op">=</span> <span class="va">medium</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_linerange</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">M_Score</span> <span class="op">-</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">SE_Score</span>, ymax <span class="op">=</span> <span class="va">M_Score</span> <span class="op">+</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">SE_Score</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">study</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">p2</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">######Step 2 is to run your model(s) of interest to answer your research question, and make sure that the data meet the assumptions of your chosen test</span></span>
<span></span>
<span><span class="co">#set reference levels</span></span>
<span><span class="va">notes</span><span class="op">$</span><span class="va">medium</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">notes</span><span class="op">$</span><span class="va">medium</span> , <span class="st">"Longhand"</span><span class="op">)</span></span>
<span><span class="va">notes</span><span class="op">$</span><span class="va">study</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">notes</span><span class="op">$</span><span class="va">study</span> , <span class="st">"No"</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#build model</span></span>
<span><span class="va">notes_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">test_score</span> <span class="op">~</span> <span class="va">study</span><span class="op">*</span><span class="va">medium</span>, data <span class="op">=</span> <span class="va">notes</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#check assumptions - note should check diagnostics here too!</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">notes_mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># look at model output - summary()</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">notes_mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = test_score ~ study * medium, data = notes)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3485 -1.4764 -0.1018  1.4039  4.5321 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  51.0200     0.4472 114.084  &lt; 2e-16 ***
studyMinimal                  9.8900     0.6325  15.637  &lt; 2e-16 ***
studyModerate                29.6700     0.6325  46.912  &lt; 2e-16 ***
studyExtensive               39.5600     0.6325  62.550  &lt; 2e-16 ***
mediumLaptop                 -2.9000     0.6325  -4.585 9.41e-06 ***
studyMinimal:mediumLaptop    -2.4400     0.8944  -2.728  0.00712 ** 
studyModerate:mediumLaptop  -18.4900     0.8944 -20.672  &lt; 2e-16 ***
studyExtensive:mediumLaptop -26.5200     0.8944 -29.650  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2 on 152 degrees of freedom
Multiple R-squared:  0.9803,    Adjusted R-squared:  0.9794 
F-statistic:  1081 on 7 and 152 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#table results</span></span>
<span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">notes_mdl</span>, </span>
<span>          pred.labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'Intercept'</span>, <span class="st">'Study - Minimal'</span>, <span class="st">'Study - Moderate'</span>, <span class="st">'Study - Extensive'</span>, <span class="st">'Medium - Laptop'</span>, <span class="st">'Study - Minimal : Medium - Laptop'</span>, <span class="st">'Study - Moderate : Medium - Laptop'</span>, <span class="st">'Study - Extensive : Medium - Laptop'</span><span class="op">)</span>,</span>
<span>          title <span class="op">=</span> <span class="st">'RQ1 - Regression Table for Total Scores Model'</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>RQ1 - Regression Table for Total Scores Model</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">test score</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Intercept</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">51.02</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">50.14&nbsp;–&nbsp;51.90</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Minimal</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9.89</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">8.64&nbsp;–&nbsp;11.14</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Moderate</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">29.67</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">28.42&nbsp;–&nbsp;30.92</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Extensive</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">39.56</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">38.31&nbsp;–&nbsp;40.81</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Medium - Laptop</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-2.90</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-4.15&nbsp;–&nbsp;-1.65</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Minimal : Medium - Laptop</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-2.44</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-4.21&nbsp;–&nbsp;-0.67</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.007</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Moderate : Medium - Laptop</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-18.49</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-20.26&nbsp;–&nbsp;-16.72</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Extensive : Medium - Laptop</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-26.52</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-28.29&nbsp;–&nbsp;-24.75</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">160</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.980 / 0.979</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#int model plot</span></span>
<span><span class="va">plt_notes_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://interactions.jacob-long.com/reference/cat_plot.html">cat_plot</a></span><span class="op">(</span>model <span class="op">=</span> <span class="va">notes_mdl</span>, </span>
<span>                  pred <span class="op">=</span> <span class="va">study</span>, </span>
<span>                  modx <span class="op">=</span> <span class="va">medium</span>, </span>
<span>                  main.title <span class="op">=</span> <span class="st">"Scores across Study and Medium"</span>,</span>
<span>                  x.label <span class="op">=</span> <span class="st">"Study"</span>,</span>
<span>                  y.label <span class="op">=</span> <span class="st">"Score"</span>,</span>
<span>                  legend.main <span class="op">=</span> <span class="st">"Medium"</span><span class="op">)</span></span>
<span><span class="va">plt_notes_mdl</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#####Step 3 somewhat depends on the outcomes of step 2. Here, you may need to consider conducting further analyses before writing up / describing your results in relation to the research question. </span></span>
<span></span>
<span><span class="co">#Perform a pairwise comparison of the mean accuracy (as measured by points accrued) across the 2×2 factorial design, making sure to adjust for multiple comparisons. </span></span>
<span></span>
<span><span class="va">m1_emm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">notes_mdl</span>, <span class="op">~</span><span class="va">study</span><span class="op">*</span><span class="va">medium</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pairs_res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="va">m1_emm</span><span class="op">)</span></span>
<span><span class="va">pairs_res</span> </span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                               estimate    SE  df t.ratio p.value
 No Longhand - Minimal Longhand            -9.89 0.632 152 -15.637  &lt;.0001
 No Longhand - Moderate Longhand          -29.67 0.632 152 -46.912  &lt;.0001
 No Longhand - Extensive Longhand         -39.56 0.632 152 -62.550  &lt;.0001
 No Longhand - No Laptop                    2.90 0.632 152   4.585  0.0002
 No Longhand - Minimal Laptop              -4.55 0.632 152  -7.194  &lt;.0001
 No Longhand - Moderate Laptop             -8.28 0.632 152 -13.092  &lt;.0001
 No Longhand - Extensive Laptop           -10.14 0.632 152 -16.033  &lt;.0001
 Minimal Longhand - Moderate Longhand     -19.78 0.632 152 -31.275  &lt;.0001
 Minimal Longhand - Extensive Longhand    -29.67 0.632 152 -46.912  &lt;.0001
 Minimal Longhand - No Laptop              12.79 0.632 152  20.223  &lt;.0001
 Minimal Longhand - Minimal Laptop          5.34 0.632 152   8.443  &lt;.0001
 Minimal Longhand - Moderate Laptop         1.61 0.632 152   2.546  0.1847
 Minimal Longhand - Extensive Laptop       -0.25 0.632 152  -0.395  0.9999
 Moderate Longhand - Extensive Longhand    -9.89 0.632 152 -15.637  &lt;.0001
 Moderate Longhand - No Laptop             32.57 0.632 152  51.498  &lt;.0001
 Moderate Longhand - Minimal Laptop        25.12 0.632 152  39.718  &lt;.0001
 Moderate Longhand - Moderate Laptop       21.39 0.632 152  33.821  &lt;.0001
 Moderate Longhand - Extensive Laptop      19.53 0.632 152  30.880  &lt;.0001
 Extensive Longhand - No Laptop            42.46 0.632 152  67.135  &lt;.0001
 Extensive Longhand - Minimal Laptop       35.01 0.632 152  55.356  &lt;.0001
 Extensive Longhand - Moderate Laptop      31.28 0.632 152  49.458  &lt;.0001
 Extensive Longhand - Extensive Laptop     29.42 0.632 152  46.517  &lt;.0001
 No Laptop - Minimal Laptop                -7.45 0.632 152 -11.779  &lt;.0001
 No Laptop - Moderate Laptop              -11.18 0.632 152 -17.677  &lt;.0001
 No Laptop - Extensive Laptop             -13.04 0.632 152 -20.618  &lt;.0001
 Minimal Laptop - Moderate Laptop          -3.73 0.632 152  -5.898  &lt;.0001
 Minimal Laptop - Extensive Laptop         -5.59 0.632 152  -8.839  &lt;.0001
 Moderate Laptop - Extensive Laptop        -1.86 0.632 152  -2.941  0.0717

P value adjustment: tukey method for comparing a family of 8 estimates </code></pre>
</div>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#plot</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">pairs_res</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/unnamed-chunk-4-5.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section><section id="the-3-act-structure" class="level3"><h3 class="anchored" data-anchor-id="the-3-act-structure">The 3-Act Structure</h3>
<p>We need to present our report in three clear sections - think of your sections like the 3 key parts of a play or story - we need to (1) provide some background and scene setting for the reader, (2) present our results in the context of the research question, and (3) present a resolution to our story - relate our findings back to the question we were asked and provide our answer.</p>
<section id="act-i-analysis-strategy" class="level4"><h4 class="anchored" data-anchor-id="act-i-analysis-strategy">Act I: Analysis Strategy</h4>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Attempt to draft a discussion section based on the above research question and analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Analysis Strategy - What to Include***
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Your analysis strategy will contain a number of different elements detailing plans and changes to your plan. Remember, your analysis strategy should <strong>not</strong> contain any results. You may wish to include the following sections:</p>
<ul>
<li>Very brief data and design description:
<ul>
<li>Give the reader some background on the context of your write-up. For example, you may wish to describe the data source, data collection strategy, study design, number of observational units.</li>
<li>Specify the variables of interest in relation to the research question, including their unit of measurement, the allowed range (for Likert scales), and how they are scored. If you have categorical data, you will need to specify the levels and coding of your variables, and what was specified as your reference level and the justification for this choice.</li>
</ul>
</li>
<li>Data management:
<ul>
<li>Describe any data cleaning and/or recoding.</li>
<li>Are there any observations that have been excluded based on pre-defined criteria? How/why, and how many?</li>
<li>Describe any transformations performed to aid your interpretation (i.e., mean centering, standardisation, etc.)</li>
</ul>
</li>
<li>Model specification:
<ul>
<li>Clearly state your hypotheses and specify your chosen significance level.</li>
<li>What type of statistical analysis do you plan to use to answer the research question? (e.g., simple linear regression, multiple linear regression, binary logistic regression, etc.)</li>
<li>In some cases, you may wish to include some visualisations and descriptive tables to motivate your model specification.</li>
<li>Specify the model(s) to be fitted to answer your given research question and analysis structure. Clearly specify the response and explanatory variables included in your model(s). This includes specifying the type of coding scheme applied if using categorical data.</li>
<li>* Specify the assumption and diagnostic checks that you will conduct. Specify what plots you will use, and how you will evaluate these.</li>
</ul>
</li>
</ul>
<div class="frame">
<p>*** Note, given time constraints in labs, we have not included any reference to diagnostic checks in this write-up example - you would be expected to include this in your report. You can find more information on diagnostic checks in the <a href="https://uoepsy.github.io/dapr2/2324/labs/1_08_assump_diag.html">S1 Week 9 Lab</a> and <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_08_assumptions_diagnostics.html#1">S1 Week 9 Lectures</a>.</p>
</div>
<p>As noted and encouraged throughout the course, one of the main benefits of using RMarkdown is the ability to include inline R code in your document. Try to incorporate this in your write up so you can automatically pull the specified values from your code. If you need a reminder on how to do this, see <a href="https://uoepsy.github.io//rmd-bootcamp/">Lesson 4 of the Rmd Bootcamp</a>.</p>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-4" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-4', 'opt-start-4')"> <span class="olab">Example Write-Up of Analysis Strategy Section</span></span>
</div>
<div id="opt-body-4" class="optional-body" style="display: none;">
<p>The <code>notes</code> dataset contained information on 160 participants who took part in a study concerning the role(s) of note taking and study time on test scores. Participants took notes on a lecture via one of two mediums - either on a laptop <span class="math inline">\((n = 80)\)</span> or long-hand using pen and paper <span class="math inline">\((n = 80)\)</span>. They were then randomly allocated to one of four study time conditions, either engaging in no <span class="math inline">\((n = 40)\)</span>, minimal <span class="math inline">\((n = 40)\)</span>, moderate <span class="math inline">\((n = 40)\)</span>, or extensive <span class="math inline">\((n = 40)\)</span> study of the notes taken on their assigned medium. Participants then answered a series of questions based on the lecture content. The maximum score was 100, where higher scores reflected better test performance.</p>
<p>The aim of this report was to address the following two research questions:</p>
<ol type="1">
<li>Do differences in test scores between study conditions differ by the note-taking medium used?</li>
<li>Are there differences in test scores between participants when comparing pairs of study and note-taking conditions? If so, what are these specific differences?</li>
</ol>
<p>All participant data was complete, and test scores within range i.e., 0-100. Categorical variables were coded as factors, where ‘No’ was designated as the reference level for study condition, and ‘Longhand’ as the reference level for medium.</p>
<p>To investigate whether study condition (No, Minimal, Moderate, Extensive) and note-taking medium (Longhand, Laptop) interacted to influence test scores, a two-way ANOVA model was used. Effects were considered statistically significant at <span class="math inline">\(\alpha = .05\)</span>. Using dummy coding, the following model specification was used:</p>
<p><span class="math display">\[
\begin{align}
\text{Test Score} &amp;= \beta_0  \\
      &amp;+ \beta_1 \cdot S_\text{Minimal} \\
      &amp;+ \beta_2 \cdot S_\text{Moderate} \\
      &amp;+ \beta_3 \cdot S_\text{Extensive} \\
      &amp;+ \beta_4 \cdot M_\text{Laptop} \\        
      &amp;+ \beta_5 \cdot  (S_\text{Minimal} \cdot M_\text{Laptop})  \\
      &amp;+ \beta_6 \cdot  (S_\text{Moderate} \cdot M_\text{Laptop})  \\
      &amp;+ \beta_7 \cdot  (S_\text{Extensive} \cdot M_\text{Laptop})  \\
      &amp;+ \epsilon  
\end{align}
\]</span></p>
<p>where we tested whether there was a significant interaction between study condition and note-taking medium:</p>
<p><span class="math display">\[
H_0: \text{All}~~ \beta_j = 0 ~\text{(for j = 5, 6, 7)}
\]</span></p>
<p><span class="math display">\[
H_1: \text{At least one}~ \beta_j \neq \text{(for j = 5, 6, 7)}
\]</span></p>
<p>As we were using between-subjects datasets, we assumed independence of our error terms. We assumed linearity as all predictor variables were categorical. Equal variances was assessed via partial residual plots (residuals should be evenly spread across the range of fitted values, where the spread should be constant across the range of fitted values), and normality was assessed via a qqplot of the residuals (points should follow along the diagonal line).</p>
<p>To address RQ2 and explore if there are pairwise differences and determine which conditions significantly differed from each other, we will conduct a series of pairwise comparisons. Since we are interested in all pairwise comparisons of means, we will apply a Tukey correction.</p>
</div>
<p class="optional-end">
</p>
</section><section id="act-ii-results" class="level4"><h4 class="anchored" data-anchor-id="act-ii-results">Act II: Results</h4>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Attempt to draft a results section based on your detailed analysis strategy and the analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Results - What To Include***
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The results section should follow from your analysis strategy. This is where you would present the evidence and results that will be used to answer the research questions and can support your conclusions. Make sure that you address all aspects of the approach you outlined in the analysis strategy (including the evaluation of assumptions and diagnostics***).</p>
<p>In this section, it is useful to include tables and plots to clearly present your findings to your reader. It is important, however, to carefully select what is the key information that should be presented. You don’t want to overload the reader with unnecessary or duplicate information, and you also want to save space in case there is a page limit. Make use of figures with multiple panels where you can.</p>
<p>As a broad guideline, you want to start with the results of any exploratory data analysis, presenting tables of summary statistics and exploratory plots. You may also want to visualise associations between/among variables and report covariances or correlations. Then, you should move on to the results from your model.</p>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-5" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-5', 'opt-start-5')"> <span class="olab">Example Write-Up of Results Section</span></span>
</div>
<div id="opt-body-5" class="optional-body" style="display: none;">
<p>Descriptive statistics are displayed in <a href="#tbl-descript">Table&nbsp;1</a>.</p>
<div class="cell" data-layout-align="center" data-caption="Descriptives Table">
<div class="cell-output-display">
<div id="tbl-descript" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;1: Descriptive Statistics</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">study</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">medium</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">M_Score</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD_Score</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SE_Score</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min_Score</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max_Score</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">51.02</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">48.02</td>
<td style="text-align: right;">54.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">No</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">48.12</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">44.86</td>
<td style="text-align: right;">51.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">60.91</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">57.84</td>
<td style="text-align: right;">65.29</td>
</tr>
<tr class="even">
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">55.57</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">52.07</td>
<td style="text-align: right;">60.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">80.69</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">76.34</td>
<td style="text-align: right;">84.64</td>
</tr>
<tr class="even">
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">59.30</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">55.77</td>
<td style="text-align: right;">62.98</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Extensive</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">90.58</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">86.82</td>
<td style="text-align: right;">94.32</td>
</tr>
<tr class="even">
<td style="text-align: left;">Extensive</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">61.16</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">56.93</td>
<td style="text-align: right;">64.32</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>In the No and Minimal study conditions, there did not appear to be differences in test score between those using a laptop or longhand when note-taking. However, those in the longhand note-taking condition scored higher than those using laptops in the moderate and extensive study conditions. This suggested that there may be an interaction (see <a href="#fig-notes-plot">Figure&nbsp;1</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-notes-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/fig-notes-plot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Association between Test Score and Medium / Study Conditions</figcaption></figure>
</div>
</div>
</div>
<p>Test scores were analysed with a 4 (study: no vs minimal vs moderate vs extensive) <span class="math inline">\(\times\)</span> 2 (medium: longhand vs laptop) between-subjects ANOVA.</p>
<p>The model met assumptions of linearity and independence (see Appendix A, top left panel of <a href="#fig-assumpt">Figure&nbsp;4</a>; residuals were randomly scattered with a mean of zero and there was no clear dependence), homoscedasticity (see Appendix A, bottom left panel of <a href="#fig-assumpt">Figure&nbsp;4</a>; there was a constant spread of residuals), and normality (see Appendix A, top right panel of <a href="#fig-assumpt">Figure&nbsp;4</a>; the QQplot showed very little deviation from the diagonal line).</p>
<p>There was a significant interaction between study condition and note-taking medium <span class="math inline">\(F(7, 152) = 1081, p &lt; . 001\)</span>. Full regression results, including 95% Confidence Intervals, are shown in <a href="#tbl-rq1-results">Table&nbsp;2</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="tbl-rq1-results" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;2: RQ1 - Regression Table for Total Scores Model</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">test score</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Intercept</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">51.02</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">50.14&nbsp;–&nbsp;51.90</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Minimal</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9.89</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">8.64&nbsp;–&nbsp;11.14</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Moderate</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">29.67</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">28.42&nbsp;–&nbsp;30.92</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Extensive</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">39.56</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">38.31&nbsp;–&nbsp;40.81</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Medium - Laptop</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-2.90</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-4.15&nbsp;–&nbsp;-1.65</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Minimal : Medium - Laptop</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-2.44</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-4.21&nbsp;–&nbsp;-0.67</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.007</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Moderate : Medium - Laptop</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-18.49</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-20.26&nbsp;–&nbsp;-16.72</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Study - Extensive : Medium - Laptop</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-26.52</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-28.29&nbsp;–&nbsp;-24.75</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">160</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.980 / 0.979</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>As displayed in <a href="#fig-intplot">Figure&nbsp;2</a>, results suggested that the difference in scores did differ significantly across the note-taking medium and study conditions, where scores differences appeared to get larger as the period of study increased (i.e., there was little difference between longhand and laptop note-taking conditions when participants engaged in no study, but the gap in test scores seemed to grow as the length of study time increased).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-intplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/fig-intplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Interaction Plot</figcaption></figure>
</div>
</div>
</div>
<p>To explore the interaction further, and address RQ2, pairwise comparisons were conducted. Tukey’s Honestly Significant Difference comparisons (see <a href="#fig-pairwise-plot">Figure&nbsp;3</a>) indicated that the vast majority of pairwise comparisons were statistically significant. There were only three pairs of comparisons that were not - those in the minimal longhand condition did not significantly differ from those in either the moderate laptop (95% CI [-0.33 - 3.55]) or extensive laptop (95% CI [-2.19 - 1.69]) conditions; and there was no difference between those in the laptop condition who studied either for a moderate or extensive period of time (95% CI [-3.80 - 0.08]). Overall, test differences appeared more pronounced when using the longhand note-taking medium across study conditions.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pairwise-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/fig-pairwise-plot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Tukey HSD Pairwise Comparisons</figcaption></figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section><section id="act-iii-discussion" class="level4"><h4 class="anchored" data-anchor-id="act-iii-discussion">Act III: Discussion</h4>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Attempt to draft a discussion section based on your results and the analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion - What To Include
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In the discussion section, you should summarise the key findings from the results section and provide the reader with a few take-home sentences drawing the analysis together and relating it back to the original question.</p>
<p>The discussion should be relatively brief, and should not include any statistical analysis - instead think of the discussion as a conclusion, providing an answer to the research question(s).</p>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-6" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-6', 'opt-start-6')"> <span class="olab">Example Write-Up of Discussion Section</span></span>
</div>
<div id="opt-body-6" class="optional-body" style="display: none;">
<p>The findings indicated that, in general, people who engaged in no study regardless of note-taking medium performed at chance level. Overall, participants who had taken notes with laptops performed worse on tests regardless of study time in comparison to those who took notes by hand. Our results led us to reject the null hypothesis, as the results indicated that the association between study condition and note-taking medium did interact to influence test scores. The direction of this association was somewhat surprising, as it suggested that laptop use can negatively influence performance on educational tests, and that engaging in hours of study is not enough to mitigate these effects.</p>
</div>
<p class="optional-end">
</p>
</section><section id="assumptions-diagnostics-appendix" class="level4"><h4 class="anchored" data-anchor-id="assumptions-diagnostics-appendix">Assumptions &amp; Diagnostics Appendix</h4>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Given we want to keep the report as concise as possible, we may wish to utilize the appendix to present assumption and diagnostic plots. We must however ensure that:</p>
<ul>
<li>We have described what assumptions we will check in the analysis strategy, including how we will evaluate them</li>
<li>We have summarized the evaluations of our assumptions and diagnostic checks in the results section of the main report</li>
<li>We have accurately refereed to the figures and tables labels presented in the appendix in the main report (if we don’t refer to them, the reader won’t know what they are relevant to!)</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="optional-begin">
<span id="opt-start-7" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-7', 'opt-start-7')"> <span class="olab">Example Assumptions &amp; Diagnostics Appendix</span></span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<section id="appendix-a" class="level5"><h5 class="anchored" data-anchor-id="appendix-a">Appendix A</h5>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-assumpt" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/fig-assumpt-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Assumption Plots</figcaption></figure>
</div>
</div>
</div>
</section>
</div>
<p class="optional-end">
</p>
<p><br></p>
</section></section></section></section><section id="section-b-weeks-1-5-recap" class="level1"><h1>Section B: Weeks 1-5 Recap</h1>
<p>In the second part of the lab, there is no new content - the purpose of the recap section is for you to revisit and revise the concepts you have learned over the last 4/5 weeks.</p>
<div class="red">
<p>Before you expand each of the boxes below, think about how comfortable you feel with each concept.</p>
</div>
<div class="optional-begin">
<span id="opt-start-8" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-8', 'opt-start-8')"> <span class="olab">Specifying Interaction Models</span></span>
</div>
<div id="opt-body-8" class="optional-body" style="display: none;">
<p><strong>Formula:</strong></p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 (x_1 \cdot x_2) + \epsilon
\]</span> In <strong>R</strong>:</p>
<div class="blue">
<p>There are basically two pieces of information that we need to pass to the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function:</p>
<ol type="1">
<li><p>The formula: The regression formula should be specified in the form <code>y ~ x</code> where <span class="math inline">\(y\)</span> is the dependent variable (DV), <span class="math inline">\(x_1\)</span> the first independent variable (IV1), and <span class="math inline">\(x_2\)</span> the second independent variable (IV2).</p></li>
<li><p>The data: Specify which dataframe contains the variables specified in the formula.</p></li>
</ol>
<ul>
<li>run interaction model via <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">model_name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">DV</span> <span class="op">~</span> <span class="va">IV1</span><span class="op">*</span><span class="va">IV2</span>, data <span class="op">=</span> <span class="va">data_name</span><span class="op">)</span></span></code></pre></div>
</div>
<p><strong>OR</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">model_name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">data_name</span><span class="op">$</span><span class="va">DV</span> <span class="op">~</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV1</span> <span class="op">+</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV2</span> <span class="op">+</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV1</span><span class="op">:</span><span class="va">data_name</span><span class="op">$</span><span class="va">IV2</span><span class="op">)</span></span></code></pre></div>
</div>
<p><strong>OR</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">model_name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">data_name</span><span class="op">$</span><span class="va">DV</span> <span class="op">~</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV1</span> <span class="op">+</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV2</span> <span class="op">+</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV1</span><span class="op">*</span><span class="va">data_name</span><span class="op">$</span><span class="va">IV2</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_11_interactions1.html#1">S2 Week 1 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/2_01_int1_nc.html">S2 Week 1 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/2_01_int1_nc.html">S2 Week 1 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_12_interactions2.html#1">S2 Week 2 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/2_02_int2_nn.html">S2 Week 2 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_13_interactions3.html#1">S2 Week 3 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/2_03_int3_cc.html">S2 Week 3 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_14_analysingexperiments.html#1">S2 Week 4 Lectures</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_04_simp_pair.html">S2 Week 4 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-9" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-9', 'opt-start-9')"> <span class="olab">Interpreting Coefficients</span></span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p><strong>Interpreting coefficients for A and B in the presence of an interaction A:B</strong></p>
<p>When you include an interaction between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> in a regression model, you are estimating the extent to which the effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> is different across the values of <span class="math inline">\(x_2\)</span>.</p>
<p>What this means is that the effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> <em>depends on/is conditional upon</em> the value of <span class="math inline">\(x_2\)</span>.<br>
(and vice versa, the effect of <span class="math inline">\(x_2\)</span> on <span class="math inline">\(y\)</span> is different across the values of <span class="math inline">\(x_1\)</span>).<br>
This means that we can no longer talk about the “effect of <span class="math inline">\(x_1\)</span> <em>holding <span class="math inline">\(x_2\)</span> constant</em>”. Instead we can talk about a <em>marginal effect</em> of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> at a specific value of <span class="math inline">\(x_2\)</span>.</p>
<div class="frame">
<p>When we fit the model <span class="math inline">\(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 (x_1 \cdot x_2) + \epsilon\)</span> using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>:</p>
<ul>
<li>the parameter estimate <span class="math inline">\(\hat \beta_1\)</span> is the <em>marginal effect</em> of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> where <span class="math inline">\(x_2 = 0\)</span><br>
</li>
<li>the parameter estimate <span class="math inline">\(\hat \beta_2\)</span> is the <em>marginal effect</em> of <span class="math inline">\(x_2\)</span> on <span class="math inline">\(y\)</span> where <span class="math inline">\(x_1 = 0\)</span><br>
</li>
</ul>
</div>
<div style="margin-left: 15px">
<p><small> <strong>N.B.</strong> Regardless of whether or not there is an interaction term in our model, all parameter estimates in multiple regression are “conditional” in the sense that they are dependent upon the inclusion of other variables in the model. For instance, in <span class="math inline">\(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon\)</span> the coefficient <span class="math inline">\(\hat \beta_1\)</span> is conditional upon holding <span class="math inline">\(x_2\)</span> constant. </small></p>
</div>
<p><strong>Interpreting the interaction term A:B</strong></p>
<p>The coefficient for an interaction term can be thought of as providing an <em>adjustment to the slope.</em></p>
<p>Let’s take the following model as an example:</p>
<pre><code>lm(formula = y ~ x1 * x2, data = df)
...

...
Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  ...        ....       ...      ...  
x1           ...        ....       ...      ...  
x2           ...        ....       ...      ...  
x1:x2        ...        ....       ...      ...  
---</code></pre>
<p>These coefficients can be interpreted, in turn as:</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Coefficient</th>
<th>Interpretation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>(Intercept)</code></td>
<td>the estimated <span class="math inline">\(y\)</span> when all predictors (<span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>) are zero is [<em>estimate</em>]</td>
</tr>
<tr class="even">
<td><code>x1</code></td>
<td>
<strong>when <span class="math inline">\(x_2\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_1\)</span> is associated with a [<em>estimate</em>] change in <span class="math inline">\(y\)</span>
</td>
</tr>
<tr class="odd">
<td><code>x2</code></td>
<td>
<strong>when <span class="math inline">\(x_1\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_2\)</span> is associated with a [<em>estimate</em>] change in <span class="math inline">\(y\)</span>.</td>
</tr>
<tr class="even">
<td><code>x1:x2</code></td>
<td>as <span class="math inline">\(x_2\)</span> increases by 1, the association between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span> changes by [<em>estimate</em>]<br><em><strong>or</strong></em><br>as <span class="math inline">\(x_1\)</span> increases by 1, the association between <span class="math inline">\(x_2\)</span> and <span class="math inline">\(y\)</span> changes by [<em>estimate</em>]</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What if there are other things (e.g., other predictors/covatiates) in the model too?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Note that the interaction <code>x1:x2</code> changes how we interpret the individual coefficients for <code>x1</code> and <code>x2</code>.</p>
<p>It does <strong><em>not</em></strong> change how we interpret coefficients for other predictors that might be in our model. For variables that <strong>aren’t</strong> involved in the interaction term, these are still held constant.</p>
<p>For example, suppose we <em>also</em> had another predictor <span class="math inline">\(c_1\)</span> in our model:</p>
<pre><code>lm(y ~ c1 + x1 + x2 + x1:x2)</code></pre>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Coefficient</th>
<th>Interpretation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>(Intercept)</code></td>
<td>the estimated <span class="math inline">\(y\)</span> when all predictors (<span class="math inline">\(c_1\)</span>, <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>) are zero is [<em>estimate</em>]</td>
</tr>
<tr class="even">
<td><code>c1</code></td>
<td>a 1 unit increase in <span class="math inline">\(c_1\)</span> is associated with a [<em>estimate</em>] increase in <span class="math inline">\(y\)</span>, holding constant all other variables in the model (<span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>)</td>
</tr>
<tr class="odd">
<td><code>x1</code></td>
<td>holding <span class="math inline">\(c_1\)</span> constant, <strong>when <span class="math inline">\(x_2\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_1\)</span> is associated with a [<em>estimate</em>] change in <span class="math inline">\(y\)</span>
</td>
</tr>
<tr class="even">
<td><code>x2</code></td>
<td>holding <span class="math inline">\(c_1\)</span> constant, <strong>when <span class="math inline">\(x_1\)</span> is zero,</strong> a 1 unit increase in <span class="math inline">\(x_2\)</span> is associated with a [<em>estimate</em>] change in <span class="math inline">\(y\)</span>.</td>
</tr>
<tr class="odd">
<td><code>x1:x2</code></td>
<td>holding <span class="math inline">\(c_1\)</span> constant, as <span class="math inline">\(x_2\)</span> increases by 1, the association between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span> changes by [<em>estimate</em>]<br><em><strong>or</strong></em><br>holding <span class="math inline">\(c_1\)</span> constant, as <span class="math inline">\(x_1\)</span> increases by 1, the association between <span class="math inline">\(x_2\)</span> and <span class="math inline">\(y\)</span> changes by [<em>estimate</em>]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_11_interactions1.html#1">S2 Week 1 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/2_01_int1_nc.html">S2 Week 1 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/2_01_int1_nc.html">S2 Week 1 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_12_interactions2.html#1">S2 Week 2 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/2_02_int2_nn.html">S2 Week 2 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_13_interactions3.html#1">S2 Week 3 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/2_03_int3_cc.html">S2 Week 3 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_14_analysingexperiments.html#1">S2 Week 4 Lectures</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_04_simp_pair.html">S2 Week 4 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-10" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-10', 'opt-start-10')"> <span class="olab">Assumptions: Interactions</span></span>
</div>
<div id="opt-body-10" class="optional-body" style="display: none;">
<p>A few points to note when assessing the assumptions of an interaction model:</p>
<ul>
<li>When there is an interaction in the model, assessing linearity becomes difficult. In fact, <code>crPlots()</code> will not work. To assess, you can create a residuals-vs-fitted plot.<br>
</li>
<li>Interaction terms often result in multicollinearity, because these terms are made up of the product of some ‘main effects’. Mean-centering the variables like we have here will reduce this source of structural multicollinearity (“structural” here refers to the fact that multicollinearity is due to our model specification, rather than the data itself).</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2324/labs/1_08_assump_diag.html">S1 Week 9 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_08_assumptions_diagnostics.html#1">S1 Week 9 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_11_interactions1.html#1">S2 Week 1 Lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-11" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-11', 'opt-start-11')"> <span class="olab">Mean Centering</span></span>
</div>
<div id="opt-body-11" class="optional-body" style="display: none;">
<p>By mean centering a continuous predictor, we change what <strong>0</strong> means/represents. Mean centering a variable involves subtracting the mean of that variable from every individual value. Normally, when we don’t have an interaction, this simply changes the intercept value (see 8A #centering-and-scaling-predictors).</p>
<p>If we have the interaction <code>y ~ x1 + x2 + x1:x2</code>, then mean centering <code>x1</code> will make the coefficient for <code>x2</code> now represent “the association between <code>x2</code> and <code>y</code> for someone at the average of <code>x1</code>”. When working with models that contain interaction terms, it is generally a good idea to center your continuous predictor variables. This is because:</p>
<ul>
<li>centering helps to address issues of multicollinearity</li>
<li>centering makes the model coefficients easier to interpret</li>
</ul>
<p>Remember that the underlying model <strong>does not</strong> change, it is just extracting different information as we have changed what “zero” represents.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_11_interactions1.html#1">S2 Week 1 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_12_interactions2.html#1">S2 Week 2 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/2_01_int1_nc.html">S2 Week 1 Lab</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/1_09_bootstrap.html#model-fitting-interpretation">S1 Week 10 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-12" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-12', 'opt-start-12')"> <span class="olab">Side Contraints</span></span>
</div>
<div id="opt-body-12" class="optional-body" style="display: none;">
<p>Possible side-constraints on the parameters are:</p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 30%">
<col style="width: 38%">
<col style="width: 16%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Name</th>
<th style="text-align: center;">Constraint</th>
<th style="text-align: center;">Meaning of <span class="math inline">\(\beta_0\)</span>
</th>
<th style="text-align: center;">R</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Sum to zero (Effects Coding)</td>
<td style="text-align: center;"><span class="math inline">\(\beta_1 + \beta_2 + \beta_3 = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\beta_0 = \mu\)</span></td>
<td style="text-align: center;"><code>contr.sum</code></td>
</tr>
<tr class="even">
<td style="text-align: center;">Reference group (Dummy Coding)</td>
<td style="text-align: center;"><span class="math inline">\(\beta_1 = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\beta_0 = \mu_1\)</span></td>
<td style="text-align: center;"><code>contr.treatment</code></td>
</tr>
</tbody>
</table>
<div class="blue">
<p><strong>IMPORTANT</strong></p>
<ul>
<li><p>By default <code>R</code> uses the reference group constraint. If your factor has <span class="math inline">\(g\)</span> levels, your regression model will have <span class="math inline">\(g-1\)</span> dummy variables (<code>R</code> creates them for you)</p></li>
<li><p>We can switch back to the default reference group constraint by applying either of these:</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># Option 1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span><span class="co"># Option 2</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.treatment"</span></span></code></pre></div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2324/labs/1_06_dummy.html">S1 Week 7 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/1_07_effects.html">S1 Week 8 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_06_LMcategorical1.html#1">S1 Week 7 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_07_lmcategorical2.html#1">S1 Week 8 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_13_interactions3.html#1">S2 Week 3 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/2_03_int3_cc.html">S2 Week 3 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_14_analysingexperiments.html#1">S2 Week 4 Lectures</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_04_simp_pair.html">S2 Week 4 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-13" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-13', 'opt-start-13')"> <span class="olab">Interactions &amp; Coding Constraints</span></span>
</div>
<div id="opt-body-13" class="optional-body" style="display: none;">
<p>When we have categorical predictors, our choice of contrasts coding changes the bits that we’re getting our of our model.</p>
<p>Suppose we have a 2x2 design (condition A and B, in groups 1 and 2):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sumplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/fig-sumplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Categorical x Categorical Interaction plot</figcaption></figure>
</div>
</div>
</div>
<p>When we are using the default contrasts coding (i.e., treatment or dummy) in R, then our coefficients for the individual predictors represent moving between the dots in <a href="#fig-sumplot">Figure&nbsp;5</a>.</p>
<pre><code>Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            1.9098     0.1759  10.855  &lt; 2e-16 ***
conditionB             1.1841     0.2488   4.759 5.65e-06 ***
grouping2             -1.6508     0.2488  -6.635 1.09e-09 ***
conditionB:grouping2  -2.1627     0.3519  -6.146 1.15e-08 ***
---</code></pre>
<ul>
<li>The intercept is the red circle in <a href="#fig-sumplot">Figure&nbsp;5</a>.<br>
</li>
<li>The coefficient for condition is the difference between the red circle and the red triangle in <a href="#fig-sumplot">Figure&nbsp;5</a>.<br>
</li>
<li>The coefficient for grouping is the difference between the red circle and the blue circle in <a href="#fig-sumplot">Figure&nbsp;5</a>.<br>
</li>
<li>The interaction coefficient is the difference from the slope of the red line to the slope of the blue line.</li>
</ul>
<p>However, when we change to using effects (or sum-to-zero) coding, we’re switching where zero is in our model. So if we change to sum contrasts (here we’ve changed <strong>both</strong> predictors to using sum-to-zero coding), then we end up estimating the effect of each predictor averaged across the other.</p>
<pre><code>Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           1.13577    0.08796  12.912  &lt; 2e-16 ***
conditionB            0.05141    0.08796   0.584     0.56    
grouping2            -1.36607    0.08796 -15.530  &lt; 2e-16 ***
conditionB:grouping2 -0.54066    0.08796  -6.146 1.15e-08 ***
---</code></pre>
<ul>
<li>The intercept is the grey X in <a href="#fig-sumplot2">Figure&nbsp;6</a>.<br>
</li>
<li>The coefficient for condition is the difference between the grey X and the grey triangle in <a href="#fig-sumplot2">Figure&nbsp;6</a>.<br>
</li>
<li>The coefficient for grouping is the difference between the grey X and the blue line in <a href="#fig-sumplot2">Figure&nbsp;6</a>.<br>
</li>
<li>The interaction coefficient is the difference from the slope of the grey line to slope of the blue line.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sumplot2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/fig-sumplot2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Visualisation of sum-to-zero for categorical x categorical interaction plot</figcaption></figure>
</div>
</div>
</div>
<p>It can get quite confusing when we start switching up the contrasts, but it’s all just because we’re changing what “zero” means, and what “moving 1” means:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Dummy/Treatment Coding</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Effects/Sum-to-Zero Coding</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_05_writeup_recap_blk3_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2324/labs/1_06_dummy.html">S1 Week 7 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/1_07_effects.html">S1 Week 8 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_06_LMcategorical1.html#1">S1 Week 7 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_07_lmcategorical2.html#1">S1 Week 8 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_13_interactions3.html#1">S2 Week 3 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/labs/2_03_int3_cc.html">S2 Week 3 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_14_analysingexperiments.html#1">S2 Week 4 Lectures</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_04_simp_pair.html">S2 Week 4 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-14" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-14', 'opt-start-14')"> <span class="olab">Contrasts: Rules for Assigning Weights</span></span>
</div>
<div id="opt-body-14" class="optional-body" style="display: none;">
<ul>
<li>
<strong>Rule 1</strong>: Weights are -1 <span class="math inline">\(\geq\)</span> x <span class="math inline">\(\leq\)</span> 1</li>
<li>
<strong>Rule 2</strong>: The group(s) in one chunk are given negative weights, the group(s) in the other get positive weights</li>
<li>
<strong>Rule 3</strong>: The sum of the weights of the comparison must be 0</li>
<li>
<strong>Rule 4</strong>: If a group is not involved in the comparison, weight is 0</li>
<li>
<strong>Rule 5</strong>: For a given comparison, weights assigned to group(s) are equal to 1 divided by the number of groups in that chunk.</li>
<li>
<strong>Rule 6</strong>: Restrict yourself to running <span class="math inline">\(k\)</span> - 1 comparisons (where <span class="math inline">\(k\)</span> = number of groups)</li>
<li>
<strong>Rule 7</strong>: Each contrast can only compare 2 chunks of variance</li>
<li>
<strong>Rule 8</strong>: Once a group singled out, it can not enter other contrasts</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2324/labs/1_07_effects.html">S1 Week 8 Lab</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_07_lmcategorical2.html#1">S1 Week 8 Lectures</a>, <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_14_analysingexperiments.html#1">S2 Week 4 Lectures</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_04_simp_pair.html">S2 Week 4 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-15" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-15', 'opt-start-15')"> <span class="olab">Multiple Comparisons: Why does the Number of Tests Matter?</span></span>
</div>
<div id="opt-body-15" class="optional-body" style="display: none;">
<p>If we are conducting all possible pairwise comparisons, we can calculate how many tests are being conducted via the following rule:</p>
<p><span class="math display">\[
_nC_r = \frac{n!}{r!(n-r)!} \\
\]</span> <span class="math display">\[
\begin{align} \\
&amp; \text{Where:} \\
&amp; n = \text{total number in the set} \\
&amp; r = \text{number chosen} \\
&amp; _nC_r = \text{number of combinations of r from n} \\
\end{align}
\]</span></p>
<p>So, why does the number of tests matter? First, think back to <a href="https://uoepsy.github.io/dapr1/2223/lectures/dapr1_2_05_errorspower.pdf">“Type 1 errors” from DAPR1</a> - when we conduct an hypothesis test, and we set <span class="math inline">\(\alpha = .05\)</span>, we will reject the null hypothesis <span class="math inline">\(H_0\)</span> when we find a <span class="math inline">\(p &lt; .05\)</span>. Now remember what a <span class="math inline">\(p\)</span>-value represents - it is the chance of observing a statistic at least as extreme as the one we do have, assuming the null hypothesis to be true. This means that <em>if</em> <span class="math inline">\(H_0\)</span> <strong>is</strong> true, then we will still observe a <span class="math inline">\(p &lt; .05\)</span> 5% of the time. So our chance of making this error = the threshold (<span class="math inline">\(\alpha\)</span>) at which below a p-value results in us rejecting <span class="math inline">\(H_0\)</span>.</p>
<p>But this error-rate applies to each statistical hypothesis we test. So if we conduct an experiment in which we plan on conducting lots of tests of different comparisons, the chance of an error being made increases substantially. Across the family of tests performed that chance will be much higher than 5%.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Each test conducted at <span class="math inline">\(\alpha = .05\)</span> has a .05 (or 5%) probability of Type I error (wrongly rejecting the null hypothesis). If we do 9 tests, that experiment-wise error rate is <span class="math inline">\(\alpha_{ew} \leq 9 \times .05\)</span>, where 9 is the number of comparisons made as part of the experiment.</p>
<p>Thus, if nine <strong>independent</strong> comparisons were made at the <span class="math inline">\(\alpha = .05\)</span> level, the experiment-wise Type I error rate <span class="math inline">\(\alpha_{ew}\)</span> would be at most <span class="math inline">\(9 \times .05 = 0.45\)</span>. That is, we could wrongly reject the null hypothesis on average 45 times out of 100. To make this more confusing, many of the tests in a family are not <strong>independent</strong> (see the lecture slides for the calculation of error rate for dependent tests).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_14_analysingexperiments.html#1">S2 Week 4 Lectures</a> and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_04_simp_pair.html">S2 Week 4 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-16" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-16', 'opt-start-16')"> <span class="olab">Multiple Comparisons: When to use Which Correction</span></span>
</div>
<div id="opt-body-16" class="optional-body" style="display: none;">
<p><strong>Bonferroni</strong></p>
<ul>
<li>Use Bonferroni’s method when you are interested in a small number of planned contrasts (or pairwise comparisons).</li>
<li>Bonferroni’s method is to divide alpha by the number of tests/confidence intervals.</li>
<li>Assumes that all comparisons are independent of one another.<br>
</li>
<li>It sacrifices slightly more power than Tukey’s method (discussed below), but it can be applied to any set of contrasts or linear combinations (i.e., it is useful in more situations than Tukey).</li>
<li>It is usually better than Tukey if we want to do a small number of planned comparisons.</li>
</ul>
<p><strong>Šídák</strong></p>
<ul>
<li>(A bit) more powerful than the Bonferroni method.</li>
<li>Assumes that all comparisons are independent of one another.</li>
<li>Less common than Bonferroni method, largely because it is more difficult to calculate (not a problem now we have computers).</li>
</ul>
<p><strong>Tukey</strong></p>
<ul>
<li>It specifies an exact family significance level for comparing all pairs of treatment means.<br>
</li>
<li>Use Tukey’s method when you are interested in all (or most) pairwise comparisons of means.</li>
</ul>
<p><strong>Scheffe</strong></p>
<ul>
<li>It is the most conservative (least powerful) of all tests.</li>
<li>It controls the family alpha level for testing all possible contrasts.</li>
<li>It should be used if you have not planned contrasts in advance.</li>
<li>For testing pairs of treatment means it is too conservative (you should use Bonferroni or Šídák).</li>
</ul>
<div class="blue">
<p>In <strong>R</strong>, you can easily change which correction you are using via the <code>adjust =</code> argument.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2324/lectures/dapr2_14_analysingexperiments.html#1">S2 Week 4 Lectures</a> and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_04_simp_pair.html">S2 Week 4 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>


</section><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1"><p>A factorial ANOVA compares means across two or more independent variables (each with two or more levels) and their interaction.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>what defines a ‘family’ of tests is debatable.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2023 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>