{
  "hash": "f4a610fb5a1262e37ad026d0568746dc",
  "result": {
    "markdown": "---\ntitle: \"Multiple Linear Regression & Standardization\"\nlink-citations: TRUE\nparams: \n    SHOW_SOLS: FALSE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n:::lo\n### <i class=\"fa fa-graduation-cap\"></i> Learning Objectives\nAt the end of this lab, you will:\n\n1. Extend the ideas of single linear regression to consider regression models with two or more predictors\n1. Understand how to interpret significance tests for $\\beta$ coefficients\n1. Understand how to standardize model coefficients and when this is appropriate to do\n1. Understand how to interpret standardized model coefficients in multiple linear regression models\n\n### <i class=\"fa fa-check-square-o fa-2\"></i> Requirements\n1. Be up to date with lectures\n2. Have completed [Week 1](https://uoepsy.github.io/dapr2/2425/labs/1_01_slr.html) and [Week 2](https://uoepsy.github.io/dapr2/2425/labs/1_02_mlr.html) lab exercises\n\n### <i class=\"fab fa-r-project\"></i> Required R Packages\nRemember to load all packages within a code chunk at the start of your RMarkdown file using `library()`. If you do not have a package and need to install, do so within the console using `install.packages(\" \")`. For further guidance on installing/updating packages, see Section C [here](https://uoepsy.github.io/files/install-update-r#update-pkgs). \n\nFor this lab, you will need to load the following package(s):\n\n* **tidyverse**\n* **patchwork**\n* **sjPlot**\n* **ppcor**\n* **kableExtra**\n\n### <i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i> Presenting Results\nAll results should be presented following [APA guidelines](https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf).If you need a reminder on how to hide code, format tables/plots, etc., make sure to review the [rmd bootcamp](https://uoepsy.github.io/scs/rmd-bootcamp/).\n\nThe example write-up sections included as part of the solutions are **not perfect** - they instead should give you a good example of what information you should include and how to structure this. Note that you must **not** copy any of the write-ups included below for future reports - if you do, you will be committing plagiarism, and this type of academic misconduct is taken very seriously by the University. You can find out more [here](https://www.ed.ac.uk/academic-services/students/conduct/academic-misconduct).\n\n### <i class=\"fa fa-file\"></i> Lab Data\nYou can download the data required for this lab [here](https://uoepsy.github.io/data/wellbeing_rural.csv) or read it in via this link https://uoepsy.github.io/data/wellbeing_rural.csv   \n\n:::\n\n# Study Overview \n\n> **Research Question** \n>\n> Is there an association between wellbeing and time spent outdoors *after* taking into account the association between wellbeing and social interactions? \n\n\n\n<div class=\"optional-begin\"><span id='opt-start-1' class=\"fa-solid fa-circle-right optional-icon clickable\" onclick=\"toggle_visibility('opt-body-1', 'opt-start-1')\"> <span class=\"olab\">Wellbeing/Rurality data codebook.</span></span></div><div class=\"optional-body\" id = \"opt-body-1\" style=\"display: none;\">\n\n  \n\n__Description__\n\nFrom the Edinburgh & Lothians, 100 city/suburb residences and 100 rural residences were chosen at random and contacted to participate in the study. The Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS) was used to measure mental health and well-being. \n\nParticipants filled out a questionnaire including items concerning: estimated average number of hours spent outdoors each week, estimated average number of social interactions each week (whether on-line or in-person), whether a daily routine is followed (yes/no). For those respondents who had an activity tracker app or smart watch, they were asked to provide their average weekly number of steps.  \n  \n  \n__Data Dictionary__\n\nThe data in `wellbeing_rural.csv` contain seven attributes collected from a random sample of $n=200$ hypothetical residents over Edinburgh & Lothians, and include: \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"xpqxkbfqhg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xpqxkbfqhg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xpqxkbfqhg thead, #xpqxkbfqhg tbody, #xpqxkbfqhg tfoot, #xpqxkbfqhg tr, #xpqxkbfqhg td, #xpqxkbfqhg th {\n  border-style: none;\n}\n\n#xpqxkbfqhg p {\n  margin: 0;\n  padding: 0;\n}\n\n#xpqxkbfqhg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xpqxkbfqhg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xpqxkbfqhg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xpqxkbfqhg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xpqxkbfqhg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xpqxkbfqhg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xpqxkbfqhg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xpqxkbfqhg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xpqxkbfqhg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xpqxkbfqhg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xpqxkbfqhg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xpqxkbfqhg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xpqxkbfqhg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xpqxkbfqhg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xpqxkbfqhg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpqxkbfqhg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xpqxkbfqhg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xpqxkbfqhg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xpqxkbfqhg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpqxkbfqhg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xpqxkbfqhg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpqxkbfqhg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xpqxkbfqhg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpqxkbfqhg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpqxkbfqhg .gt_left {\n  text-align: left;\n}\n\n#xpqxkbfqhg .gt_center {\n  text-align: center;\n}\n\n#xpqxkbfqhg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xpqxkbfqhg .gt_font_normal {\n  font-weight: normal;\n}\n\n#xpqxkbfqhg .gt_font_bold {\n  font-weight: bold;\n}\n\n#xpqxkbfqhg .gt_font_italic {\n  font-style: italic;\n}\n\n#xpqxkbfqhg .gt_super {\n  font-size: 65%;\n}\n\n#xpqxkbfqhg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xpqxkbfqhg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xpqxkbfqhg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xpqxkbfqhg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xpqxkbfqhg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xpqxkbfqhg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xpqxkbfqhg .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Age in years of respondent</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">outdoor_time</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Self report estimated number of hours per week spent outdoors </td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">social_int</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Self report estimated number of social interactions per week (both online and in-person)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">routine</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Binary 1=Yes/0=No response to the question 'Do you follow a daily routine throughout the week?'</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">wellbeing</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">location</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Location of primary residence (City, Suburb, Rural)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">steps_k</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Average weekly number of steps in thousands (as given by activity tracker if available)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n  \n  \n__Preview__\n\nThe first six rows of the data are:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"jxqiwkyfqa\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jxqiwkyfqa table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jxqiwkyfqa thead, #jxqiwkyfqa tbody, #jxqiwkyfqa tfoot, #jxqiwkyfqa tr, #jxqiwkyfqa td, #jxqiwkyfqa th {\n  border-style: none;\n}\n\n#jxqiwkyfqa p {\n  margin: 0;\n  padding: 0;\n}\n\n#jxqiwkyfqa .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jxqiwkyfqa .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jxqiwkyfqa .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jxqiwkyfqa .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jxqiwkyfqa .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jxqiwkyfqa .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jxqiwkyfqa .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jxqiwkyfqa .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jxqiwkyfqa .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jxqiwkyfqa .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jxqiwkyfqa .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jxqiwkyfqa .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jxqiwkyfqa .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jxqiwkyfqa .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jxqiwkyfqa .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxqiwkyfqa .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jxqiwkyfqa .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jxqiwkyfqa .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jxqiwkyfqa .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxqiwkyfqa .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jxqiwkyfqa .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxqiwkyfqa .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jxqiwkyfqa .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxqiwkyfqa .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxqiwkyfqa .gt_left {\n  text-align: left;\n}\n\n#jxqiwkyfqa .gt_center {\n  text-align: center;\n}\n\n#jxqiwkyfqa .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jxqiwkyfqa .gt_font_normal {\n  font-weight: normal;\n}\n\n#jxqiwkyfqa .gt_font_bold {\n  font-weight: bold;\n}\n\n#jxqiwkyfqa .gt_font_italic {\n  font-style: italic;\n}\n\n#jxqiwkyfqa .gt_super {\n  font-size: 65%;\n}\n\n#jxqiwkyfqa .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jxqiwkyfqa .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jxqiwkyfqa .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jxqiwkyfqa .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jxqiwkyfqa .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jxqiwkyfqa .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jxqiwkyfqa .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age\">age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"outdoor_time\">outdoor_time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"social_int\">social_int</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"routine\">routine</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wellbeing\">wellbeing</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"location\">location</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"steps_k\">steps_k</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">28</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">12</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">13</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">36</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">21.6</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">56</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">5</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">15</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">41</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">12.3</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">25</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">19</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">11</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">35</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">49.8</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">60</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">25</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">15</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">0</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">35</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">19</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">9</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">18</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">32</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">48.1</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">34</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">18</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">13</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">34</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">67.3</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n  \n\n\n</div><p class=\"optional-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Setup\n\n\n\n<div class='question-begin'>Setup</div><div class='question-body'>\n\n  \n\n1. Create a new RMarkdown file\n2. Load the required package(s)\n3. Read the wellbeing dataset into R, assigning it to an object named `mwdata`\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#Loading the required package(s)\nlibrary(tidyverse)\nlibrary(patchwork)\nlibrary(sjPlot)\nlibrary(ppcor)\nlibrary(kableExtra)\n\n# Reading in data and storing to an object named 'mwdata'\nmwdata <- read_csv(\"https://uoepsy.github.io/data/wellbeing_rural.csv\")\n```\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Exercises \n\nIn the first section of this lab, you will focus on the statistics contained within the highlighted sections of the `summary()` output below. You will be both calculating these by hand and deriving via `R` code before interpreting these values in the context of the research question following [APA guidelines](https://uoepsy.github.io/dapr2/2425/labs/1_b1_reading.html#apa-formatting). In the second section of this lab, you will focus on standardization. We will be building on last weeks lab example throughout these exercises.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/mdl_output_params.PNG){fig-align='center' width=85%}\n:::\n:::\n\n\n## Lab 2 Recap\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\n\nFit the following multiple linear regression model, and assign the output to an object called `mdl`, and examine the summary output.\n\n$$\n\\text{Wellbeing} = \\beta_0 + \\beta_1 \\cdot Social~Interactions + \\beta_2 \\cdot Outdoor~Time + \\epsilon \n$$\n\n\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nWe can fit our multiple regression model using the `lm()` function. For a recap, see the [statistical models flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b1_reading.html#statistical-models), specifically the multiple linear regression models - description & specification card. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmdl <- lm(wellbeing ~ social_int + outdoor_time, data = mwdata)\nsummary(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = wellbeing ~ social_int + outdoor_time, data = mwdata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.7611  -3.1308  -0.4213   3.3126  18.8406 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  28.62018    1.48786  19.236  < 2e-16 ***\nsocial_int    0.33488    0.08929   3.751 0.000232 ***\noutdoor_time  0.19909    0.05060   3.935 0.000115 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.065 on 197 degrees of freedom\nMultiple R-squared:  0.1265,\tAdjusted R-squared:  0.1176 \nF-statistic: 14.26 on 2 and 197 DF,  p-value: 1.644e-06\n```\n:::\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Significance Tests for $\\beta$ Coefficients\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\n\nTest the hypothesis that the population slope for outdoor time is zero --- that is, that there is no linear association between wellbeing and outdoor time (*after* controlling for the number of social interactions) in the population. \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nSee the [t value flashcard](https://uoepsy.github.io/dapr2/2425/labs/1_b1_reading.html#statistical-models) (within simple & multiple regression models - extracting Information > model coefficients > t value). \n\n\nReview this weeks lecture slides for an example of how to do this by-hand and in `R`. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n::: {.panel-tabset}\n\n## Manually\n\nWe calculate the test statistic for $\\beta_2$ as:\n\n$$\nt = \\frac{\\hat \\beta_2 - 0}{SE(\\hat \\beta_2)} = \\frac{0.19909 - 0}{0.05060} = 3.934585\n$$\n\nand compare it with the 5% critical value from a $t$-distribution with $n-3$ degrees of freedom (since $k = 2$, we have $n-2-1$), which is:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn <- nrow(mwdata)\nk <- 2\ntstar <- qt(0.975, df = n - k - 1)\ntstar\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.972079\n```\n:::\n\n```{.r .cell-code}\n#tstar = 1.972079\n```\n:::\n\n\nAs $|t|$ ($|t|$ = 3.93) is much larger than $t^*$ ($t^*$ = 1.97), we can reject the null hypothesis as we have strong evidence against it.\n\nThe $p$-value, shown below, also confirms this conclusion.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n2 * (1 - pt(3.934585, n - 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.0001154709\n```\n:::\n:::\n\n\n## R Function\n\nPlease note that the same information was already contained in the row corresponding to the variable \"outdoor_time\" in the output of `summary(mdl)`, which reported the $t$-statistic under `t value` and the $p$-value under `Pr(>|t|)`:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = wellbeing ~ social_int + outdoor_time, data = mwdata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.7611  -3.1308  -0.4213   3.3126  18.8406 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  28.62018    1.48786  19.236  < 2e-16 ***\nsocial_int    0.33488    0.08929   3.751 0.000232 ***\noutdoor_time  0.19909    0.05060   3.935 0.000115 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.065 on 197 degrees of freedom\nMultiple R-squared:  0.1265,\tAdjusted R-squared:  0.1176 \nF-statistic: 14.26 on 2 and 197 DF,  p-value: 1.644e-06\n```\n:::\n:::\n\n\nThe result is exactly the same (up to rounding errors) as calculating manually.\n\nBefore we interpret the results, note that sometimes $p$-values will be reported to $e^X$. For example, look in the `Pr(>|t|)` column for \"(Intercept)\". The value $2e^{-16}$ simply means $2 \\times 10^{-16}$. This is a very small value (i.e., 0.0000000000000002), hence we would simply report it as <.001 following the [APA guidelines](https://uoepsy.github.io/dapr2/2425/labs/1_b1_reading.html#apa-formatting).\n\n:::\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nWe performed a $t$-test against the null hypothesis that outdoor time was not associated with wellbeing scores after controlling for social interactions. A significant association was found between outdoor time (hours per week) and wellbeing (WEMWBS scores) $t(197) = 3.94,\\ p < .001$, two-sided. Thus, we have evidence to reject the null hypothesis.\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\n\nObtain 95% confidence intervals for the regression coefficients, and write a sentence about each one.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nRecall the formula for obtaining a **confidence interval**:\n\nA confidence interval for the population slope is\n$$\n\\hat \\beta_j \\pm t^* \\cdot SE(\\hat \\beta_j)\n$$\nwhere $t^*$ denotes the critical value chosen from t-distribution with $n-k-1$ degrees of freedom (where $k$ = number of predictors and $n$ = sample size) for a desired $\\alpha$ level of confidence. \n\nReview this weeks lecture slides for an example of how to do this by-hand and in `R`. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n::: {.panel-tabset}\n\n## Manually\n\nFor 95\\% confidence we have $t^* = 1.97$:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn <- nrow(mwdata)\nk <- 2\ntstar <- qt(0.975, df = n - k - 1)\ntstar\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.972079\n```\n:::\n:::\n\n\nThe confidence intervals are:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntibble(\n  b0_LowerCI = round(28.62018 - (qt(0.975, n-3) * 1.48786), 3),\n  b0_UpperCI = round(28.62018 + (qt(0.975, n-3)* 1.48786), 3),\n  b1_LowerCI = round(0.33488 - (qt(0.975, n-3) * 0.08929), 3),\n  b1_UpperCI = round(0.33488 + (qt(0.975, n-3)* 0.08929), 3),\n  b2_LowerCI = round(0.19909 - (qt(0.975, n-3) * 0.05060), 3),\n  b2_UpperCI = round(0.19909 + (qt(0.975, n-3)* 0.05060), 3)\n      )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 6\n  b0_LowerCI b0_UpperCI b1_LowerCI b1_UpperCI b2_LowerCI b2_UpperCI\n       <dbl>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>\n1       25.7       31.6      0.159      0.511      0.099      0.299\n```\n:::\n:::\n\n\n## R Function\nWe can much more easily obtain the confidence intervals for the regression coefficients using the command `confint()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nconfint(mdl, level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                   2.5 %     97.5 %\n(Intercept)  25.68600170 31.5543598\nsocial_int    0.15880045  0.5109638\noutdoor_time  0.09931273  0.2988759\n```\n:::\n:::\n\n\nThe result is exactly the same (up to rounding errors) as calculating manually. \n\n:::\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\n+ The average wellbeing score for all those with zero hours of outdoor time and zero social interactions per week was between 25.69 and 31.55.  \n+ When _holding weekly outdoor time constant_, each increase of one social interaction per week was associated with a difference in wellbeing scores between 0.16 and 0.51, on average.  \n+ When _holding the number of social interactions per week constant_, each one hour increase in weekly outdoor time was associated with a difference in wellbeing scores between 0.1 and 0.3, on average.  \n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Standardization\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\n\nFit two regression models using the standardized response and explanatory variables. For demonstration purposes, fit one model using z-scored variables, and the other using the `scale()` function.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nBoth of these methods - z-scoring and `scale()` - will give us a standardized model. \n\nSee the [scaling and standardisation flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b1_reading.html#data-transformations). \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n::: {.panel-tabset}\n\n## z-score\n\nz-score variables:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmwdata <- mwdata %>%\n  mutate(\n    z_wellbeing = (wellbeing - mean(wellbeing)) / sd(wellbeing),\n    z_social_int = (social_int - mean(social_int)) / sd(social_int),\n    z_outdoor_time = (outdoor_time - mean(outdoor_time)) / sd(outdoor_time)\n  )\n```\n:::\n\n\nCheck that they are standardized:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmwdata %>%\n  summarise(\n    M_z_wellbeing = round(mean(z_wellbeing),2), SD_z_wellbeing = sd(z_wellbeing), \n    M_z_social_int = round(mean(z_social_int),2), SD_z_social_int = sd(z_social_int),\n    M_z_outdoor_time = round(mean(z_outdoor_time),2), SD_z_outdoor_time = sd(z_outdoor_time)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 6\n  M_z_wellbeing SD_z_wellbeing M_z_social_int SD_z_social_int M_z_outdoor_time\n          <dbl>          <dbl>          <dbl>           <dbl>            <dbl>\n1             0              1              0               1                0\n# ℹ 1 more variable: SD_z_outdoor_time <dbl>\n```\n:::\n\n```{.r .cell-code}\n#mean of 0, SD of 1 - all good to go\n```\n:::\n\n\nRun model:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmdl_z <- lm(z_wellbeing ~ z_social_int + z_outdoor_time, data = mwdata)\n```\n:::\n\n\n## `scale()` function\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmdl_s <- lm(scale(wellbeing) ~ scale(social_int) + scale(outdoor_time), data = mwdata)\n```\n:::\n\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\n\nExamine the estimates from both standardized models - what do you notice?\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\nReview the [simple & multiple regression models - extracting information > model coefficients flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b1_reading.html#statistical-models). \n\nConsider whether the values the same, or different? What would you expect them to be and why?\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n::: {.panel-tabset}\n\n## Z-Score\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mdl_z)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = z_wellbeing ~ z_social_int + z_outdoor_time, data = mwdata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.9231 -0.5806 -0.0781  0.6144  3.4942 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    -4.168e-16  6.642e-02   0.000 1.000000    \nz_social_int    2.499e-01  6.663e-02   3.751 0.000232 ***\nz_outdoor_time  2.622e-01  6.663e-02   3.935 0.000115 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9394 on 197 degrees of freedom\nMultiple R-squared:  0.1265,\tAdjusted R-squared:  0.1176 \nF-statistic: 14.26 on 2 and 197 DF,  p-value: 1.644e-06\n```\n:::\n\n```{.r .cell-code}\nround(summary(mdl_z)$coefficients, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Estimate Std. Error t value Pr(>|t|)\n(Intercept)        0.00       0.07    0.00        1\nz_social_int       0.25       0.07    3.75        0\nz_outdoor_time     0.26       0.07    3.93        0\n```\n:::\n:::\n\n\n## `scale()` function\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mdl_s)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = scale(wellbeing) ~ scale(social_int) + scale(outdoor_time), \n    data = mwdata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.9231 -0.5806 -0.0781  0.6144  3.4942 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         -4.106e-16  6.642e-02   0.000 1.000000    \nscale(social_int)    2.499e-01  6.663e-02   3.751 0.000232 ***\nscale(outdoor_time)  2.622e-01  6.663e-02   3.935 0.000115 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9394 on 197 degrees of freedom\nMultiple R-squared:  0.1265,\tAdjusted R-squared:  0.1176 \nF-statistic: 14.26 on 2 and 197 DF,  p-value: 1.644e-06\n```\n:::\n\n```{.r .cell-code}\nround(summary(mdl_s)$coefficients, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    Estimate Std. Error t value Pr(>|t|)\n(Intercept)             0.00       0.07    0.00        1\nscale(social_int)       0.25       0.07    3.75        0\nscale(outdoor_time)     0.26       0.07    3.93        0\n```\n:::\n:::\n\n\n:::\n\nFrom comparing either the `summary()` or rounded output, we can see that the estimates are the same under both approaches. That means you can use either approach to standardize the variables in your model. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\n\nExamine the 'Coefficients' section of the `summary()` output from the standardized and unstandardized models - what do you notice? In other words, what is the same / different?\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\nReview the [simple & multiple regression models - extracting information > model coefficients flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b1_reading.html#statistical-models). \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n::: {.panel-tabset}\n\n## Unstandardized\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = wellbeing ~ social_int + outdoor_time, data = mwdata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.7611  -3.1308  -0.4213   3.3126  18.8406 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  28.62018    1.48786  19.236  < 2e-16 ***\nsocial_int    0.33488    0.08929   3.751 0.000232 ***\noutdoor_time  0.19909    0.05060   3.935 0.000115 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.065 on 197 degrees of freedom\nMultiple R-squared:  0.1265,\tAdjusted R-squared:  0.1176 \nF-statistic: 14.26 on 2 and 197 DF,  p-value: 1.644e-06\n```\n:::\n\n```{.r .cell-code}\nround(summary(mdl)$coefficients, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Estimate Std. Error t value Pr(>|t|)\n(Intercept)     28.62       1.49   19.24        0\nsocial_int       0.33       0.09    3.75        0\noutdoor_time     0.20       0.05    3.93        0\n```\n:::\n:::\n\n\n## Standardized \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mdl_z)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = z_wellbeing ~ z_social_int + z_outdoor_time, data = mwdata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.9231 -0.5806 -0.0781  0.6144  3.4942 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    -4.168e-16  6.642e-02   0.000 1.000000    \nz_social_int    2.499e-01  6.663e-02   3.751 0.000232 ***\nz_outdoor_time  2.622e-01  6.663e-02   3.935 0.000115 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9394 on 197 degrees of freedom\nMultiple R-squared:  0.1265,\tAdjusted R-squared:  0.1176 \nF-statistic: 14.26 on 2 and 197 DF,  p-value: 1.644e-06\n```\n:::\n\n```{.r .cell-code}\nround(summary(mdl_z)$coefficients, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Estimate Std. Error t value Pr(>|t|)\n(Intercept)        0.00       0.07    0.00        1\nz_social_int       0.25       0.07    3.75        0\nz_outdoor_time     0.26       0.07    3.93        0\n```\n:::\n:::\n\n\n:::\n\n**Similarities**  \n\n+ The $t$ and $p$-values for the two predictor variables in both models are the same. This is because the significance of these values remains the same for the standardized coefficients as for unstandardized coefficients  \n\n**Differences**  \n\n+ The estimates and standard errors for the intercept and both predictor variables are different under the unstandardized and standardized models  \n+ The $t$ and $p$-values are different in each model for the intercept. This is because:\n    + In the unstandardized model, the intercept is significantly different from 0 (it is 28.62), and hence has a very small $p$-value (< .001)  \n    + In the standardized model, the intercept is not significantly different from 0 (it is 0!), and hence has a $p$-value of 1. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\n\nHow do these standardized estimates relate to the semi-partial correlation coefficients?\n\nProduce a visualisation of the association between wellbeing and outdoor time, after accounting for social interactions.  \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\n*Semi-partial (part) correlation coefficient*  \n\nFirstly, think about what semi-partial correlation coefficients and standardized $\\beta$ coefficients represent: \n\n+ Semi-partial correlation coefficients (which you may also see referred to as part correlations) estimate the **unique** contribution of each predictor variable to the explained variance in the dependent variable, while controlling for the influence of all other predictors in the model.  \n+ Standardized $\\beta$ estimates represent the change in the dependent variable in standard deviation units for a one-standard-deviation change in the predictor variable, whilst holding all other predictors constant.  \n  \nTo calculate semi-partial (part) correlation coefficients, you will need to use the `spcor.test()` from the **ppcor** package.  \n\nRecall that you can look at the estimates from either 'mdl_s' or 'mdl_z' - they contain the same standardized model estimates. \n\n*Note* this is quite a difficult question (really it could be optional), and the exercise is designed to get you to think about how semi-partial correlation coefficients and standardized $\\beta$ coefficients are related. \n\n*Plotting*  \nTo visualise just one association, you need to specify the `terms` argument in `plot_model()`. Don't forget you can look up the documentation by typing `?plot_model` in the console. \n\nSince using `plot_model()`, We need to use 'mdl_z' here **not** 'mdl_s' - it won't work with a model that's used the `scale()` function.  \n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n::: {.panel-tabset}\n\n# Semi-partial (part) correlation coefficient\n\nFirst, lets recall the estimates from our standardized model (rounding to 2 decimal places):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nround(mdl_z$coefficients, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   (Intercept)   z_social_int z_outdoor_time \n          0.00           0.25           0.26 \n```\n:::\n:::\n\n\nNext, lets calculate the semi-partial correlation coefficients:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#semi-partial (part) correlation between wellbeing & social interactions\nwb_soc <- spcor.test(mwdata$wellbeing, mwdata$social_int, mwdata$outdoor_time,  method=\"pearson\")\n#round correlation coefficient estimate to 2 decimal places\nround(wb_soc$estimate, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.25\n```\n:::\n\n```{.r .cell-code}\n#semi-partial (part) correlation between wellbeing & outdoor time\nwb_out <- spcor.test(mwdata$wellbeing, mwdata$outdoor_time, mwdata$social_int, method=\"pearson\")\n#round correlation coefficient estimate to 2 decimal places\nround(wb_out$estimate, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.26\n```\n:::\n:::\n\n\nWe can see that the slope estimates from the standardized model are equivalent to the semi-partial (part) correlation coefficients. This makes theoretical sense given that:\n\nIn our example, we had a multiple regression model with two predictors, so in our case this means that the $\\beta^*$ coefficients quantify the change in the dependent variable when one predictor (i.e., outdoor time) changes by one standard deviation while the other predictor remains constant (i.e., number of weekly social interactions); whilst the semi-partial correlation for a given predictor (i.e., outdoor time) represents the correlation between the dependent variable and that predictor (i.e., wellbeing and outdoor time) while controlling for the other predictor (i.e., number of weekly social interactions). Thus, the standardized estimate (i.e., $\\beta^*$ coefficient) for one predictor in a multiple regression model with two predictors is equivalent to the semi-partial correlation coefficient for that predictor because, in this context, “holding all other predictors constant” refers to the one remaining predictor.\n\n*Note*  \nIf this seems a bit confusing, try not to worry - it was more a demonstration of the relationship between $r$ and $\\beta^*$ for when you have 2 predictors (since you saw how this worked with 1 predictor in lecture, we thought it would be useful to extend to 2 predictors). Also, this can become pretty messy very quickly when you have a model with 3+ predictors as the associations among variables becomes more complex.\n\n# Visualisation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_model(mdl_z, type = \"eff\",\n           terms = c(\"z_outdoor_time\"), \n           show.data = TRUE)\n```\n\n::: {.cell-output-display}\n![](1_03_mlr_stz_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\n\nPlot the data and the fitted regression line from both the unstandardized and standardized models. To do so, for each model:\n\n- Extract the estimated regression coefficients e.g., via `betas <- coef(mdl)`\n- Extract the first entry of `betas` (i.e., the intercept) via `betas[1]`\n- Extract the second entry of `betas` (i.e., the slope) via `betas[2]`\n- Provide the intercept and slope to the function\n\nNote down what you observe from the plots - what is the same / different?\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nThis is very similar to [Lab 1 Q7](https://uoepsy.github.io/dapr2/2425/labs/1_01_slr.html).\n\n*Extracting values*  \nThe function `coef()` returns a vector (a sequence of numbers all of the same type). To get the first element of the sequence you append `[1]`, and `[2]` for the second.\n\n*Plotting*  \nIn your `ggplot()`, you will need to specify `geom_abline()`. This might help get you started:\n\n<center>\n<code>\ngeom_abline(intercept = **intercept**, slope = **slope**)\n</code>\n</center>\n<br>\n\nYou may also want to plot these side by side to more easily compare, so consider using `|` from **patchwork**. For further `ggplot()` guidance, see the [how to visualise data flashcard](https://uoepsy.github.io/dapr2/2425/labs/1_b1_reading.html#visual-exploration).\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nFirst extract the values required for both non-standardized and standardized models:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#non-standardized (from 'mdl')\nbetas <- coef(mdl)\nintercept <- betas[1]\nslope <- betas[2]\n\n#standardized (from 'mdl_z')\nbetas_z <- coef(mdl_z)\nintercept_z <- betas_z[1]\nslope_z <- betas_z[2]\n```\n:::\n\n\nWe can plot the models as follows:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np1 <- ggplot(data = mwdata, aes(x = social_int, y = wellbeing)) +\n  geom_point() +\n  geom_abline(intercept = intercept, slope = slope, color = 'blue') + \n  labs(x = \"Social Interactions \\n(Number per Week)\", y = \"Wellbeing (WEMWBS) Scores\")\n\np2 <- ggplot(data = mwdata, aes(x = z_social_int, y = z_wellbeing)) +\n  geom_point() +\n  geom_abline(intercept = intercept_z, slope = slope_z, color = 'red') + \n  labs(x = \"Social Interactions \\n(Number per Week; Z-Scored)\", y = \"Wellbeing (WEMWBS) Scores; Z-Scored\")\n\np1 | p2\n```\n\n::: {.cell-output-display}\n![](1_03_mlr_stz_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n**Similarities**  \n\n+ The data points are distributed in the same pattern  \n+ The slope of the line follows the same gradient\n\n**Differences**  \n\n+ The x- and y-axis scales are different for each plot. This is because:  \n    + The unstandardized is in the original units where we interpret the slope as the change in $y$ units for a unit change in $x$  \n    + The standardized is in SD units where we interpret the slope as the SD change in $y$ for 1 SD change in $x$\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Writing Up & Presenting Results\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\n\nProvide key model results from the standardized model in a formatted table.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nUse `tab_model()` from the __sjPlot__ package. For a quick guide, review the [tables flashcard](https://uoepsy.github.io/dapr2/2425/labs/1_b1_reading.html#tables).\n\nSince using `tab_model()`, We need to use 'mdl_z' here **not** 'mdl_s' - it won't work with a model that's used the `scale()` function.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n::: {#tbl-w3-modresults .cell layout-align=\"center\" tbl-cap='Regression Results for Wellbeing Model (both DV and IVs z-scored)'}\n\n```{.r .cell-code}\ntab_model(mdl_z,\n          dv.labels = \"Wellbeing (WEMWBS Scores)\",\n          pred.labels = c(\"z_social_int\" = \"Social Interactions (number per week)\",\n                          \"z_outdoor_time\" = \"Outdoor Time (hours per week)\"),\n          title = \"Regression Results for Wellbeing Model (both DV and IVs z-scored)\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<caption style=\"font-weight: bold; text-align:left;\">Regression Results for Wellbeing Model (both DV and IVs z-scored)</caption>\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Wellbeing (WEMWBS Scores)</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.00</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.13&nbsp;&ndash;&nbsp;0.13</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.000</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Social Interactions<br>(number per week)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.25</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.12&nbsp;&ndash;&nbsp;0.38</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Outdoor Time (hours per<br>week)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.26</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.13&nbsp;&ndash;&nbsp;0.39</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">200</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.126 / 0.118</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\n\nInterpret the results from the standardized model the context of the research question.\n\nMake reference to the your regression table.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nRemember to inform the reader of the scale of your variables. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nA multiple regression model was used to determine if there was an association between well-being and time spent outdoors after taking into account the association between well-being and social interactions. All variables (wellbeing, social interactions, and outdoor time) were $z$-scored. As presented in @tbl-w3-modresults, outdoor time was significantly associated with wellbeing scores $(\\beta = 0.26, SE = 0.07, p < .001)$ after controlling for the number of weekly social interactions. Results suggested that, holding constant social interactions, for every standard deviation increase in outdoor time, wellbeing scores increased on average by 0.26 standard deviations. Therefore, we should reject the null hypothesis since $p < .05$.\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Compile Report\n\n\n\n<div class='question-begin'>Compile Report</div><div class='question-body'>\n\n  \n\nKnit your report to PDF, and check over your work. To do so, you should make sure:\n\n- Only the output you want your reader to see is visible (e.g., do you want to hide your code?)\n- Check that the **tinytex** package is installed\n- Ensure that the ‘yaml’ (bit at the very top of your document) looks something like this:\n\n```{}\n---\ntitle: \"this is my report title\"\nauthor: \"B1234506\"\ndate: \"07/09/2024\"\noutput: bookdown::pdf_document2\n---\n```\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n# What to do if you cannot knit to PDF\nIf you are having issues knitting directly to PDF, try the following:  \n\n- Knit to HTML file  \n- Open your HTML in a web-browser (e.g. Chrome, Firefox)  \n- Print to PDF (Ctrl+P, then choose to save to PDF)  \n- Open file to check formatting\n:::\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n# Hiding Code and/or Output\n\n:::{.panel-tabset}\n## Hiding R Code\n\nTo not show the code of an R code chunk, and only show the output, write:\n\n````\n```{{r, echo=FALSE}}\n# code goes here\n```\n````\n\n## Hiding R Output\n\nTo show the code of an R code chunk, but hide the output, write:\n\n````\n```{{r, results='hide'}}\n# code goes here\n```\n````\n\n## Hiding R Code and Output\n\nTo hide both code and output of an R code chunk, write:\n\n````\n```{{r, include=FALSE}}\n# code goes here\n```\n````\n:::\n\n:::\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Tinytex\nYou must make sure you have **tinytex** installed in R so that you can “Knit” your Rmd document to a PDF file:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninstall.packages(\"tinytex\")\ntinytex::install_tinytex()\n```\n:::\n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nYou should end up with a PDF file. If you have followed the above instructions and still have issues with knitting, speak with a Tutor. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n",
    "supporting": [
      "1_03_mlr_stz_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}