<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>15: Practice write-up – DAPR2 Lab Exercises</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-773453d6402ea9fb31d9a98ebd0e2882.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-circle-right')) {
    f.classList.add('fa-circle-down')
    f.classList.remove('fa-circle-right')
} else {
    f.classList.add('fa-circle-right')
    f.classList.remove('fa-circle-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">DAPR2 Lab Exercises</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-block-1-intro-lm" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Block 1: Intro LM</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-block-1-intro-lm">    
        <li>
    <a class="dropdown-item" href="../block1_introLM/01.html">
 <span class="dropdown-text">01: Simple linear regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../block1_introLM/02.html">
 <span class="dropdown-text">02: Multiple regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../block1_introLM/03.html">
 <span class="dropdown-text">03: Significance tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../block1_introLM/04.html">
 <span class="dropdown-text">04: Model comparison</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../block1_introLM/05.html">
 <span class="dropdown-text">05: Practice write-up</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-block-2-extending-lm" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Block 2: Extending LM</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-block-2-extending-lm">    
        <li>
    <a class="dropdown-item" href="../block2_moreLM/06.html">
 <span class="dropdown-text">06: Treatment coding</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../block2_moreLM/07.html">
 <span class="dropdown-text">07: Sum coding</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../block2_moreLM/08.html">
 <span class="dropdown-text">08: Assumptions and diagnostics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../block2_moreLM/09.html">
 <span class="dropdown-text">09: Bootstrapping</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../block2_moreLM/10.html">
 <span class="dropdown-text">10: Practice write-up</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <span class="nav-link">
<span class="menu-text">Block 3: Interactions</span>
    </span>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-block-4-logistic-regression" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Block 4: Logistic regression</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-block-4-logistic-regression">    
        <li>
    <a class="dropdown-item" href="../block4_logistic/16.html">
 <span class="dropdown-text">16: Probabilities and log-odds</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">15: Practice write-up</h1>
</div>



<div class="quarto-title-meta column-page">

    
  
    
  </div>
  


</header>


<!-- when rendering in RStudio / not production profile (tutor-facing):      SHOW_SOLS: TRUE  -->
<!-- when rendering in terminal / with production profile (student-facing):  SHOW_SOLS: FALSE -->
<p>This week (and every fifth week this year), you’ll practice writing up the analysis that was developed live during lectures.</p>
<p>Your goal is to present your analysis in a journal-article-style Results section that a reader could reproduce in any statistical software, not just R.</p>
<p>Quick links to key flash cards:</p>
<ul>
<li>🗂️ <a href="https://uoepsy.github.io/dapr2/2627/flashcards/resources/workflow-b3.html" target="_blank">Analysis workflow (Block 3)</a></li>
<li>🗂️ <a href="https://uoepsy.github.io/dapr2/2627/flashcards/resources/reporting-lm.html" target="_blank">Reporting LM analysis checklist</a></li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The example write-ups that will be provided <strong>are not perfect.</strong></p>
<p>You must not copy them directly for this write-up or any future assessment, as copying and presenting them as your own work would constitute academic misconduct. But you may refer to them for stylistic guidance.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Get set up
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Open RStudio.</li>
<li>Create a new .Rmd file for this week’s exercises.</li>
<li>Save it somewhere you can find it again.</li>
<li>Give it a clear name (for example, <code>dapr2_lab15.Rmd</code>).</li>
<li>In the first code chunk, load the packages you’ll need this week (and install them if you don’t have them already):
<ul>
<li><code>tidyverse</code></li>
<li><code>psych</code></li>
<li><code>sjPlot</code></li>
<li><code>kableExtra</code></li>
<li><code>patchwork</code></li>
<li><code>car</code></li>
<li><code>interactions</code></li>
</ul></li>
</ol>
</div>
</div>
<hr>
<div class="frame">
<p>The data in <code>laptop_vs_longhand.csv</code> contain three attributes collected from a simulated sample of <span class="math inline">\(n=160\)</span> hypothetical individuals, and includes:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="hjsnneuxbl" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#hjsnneuxbl table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#hjsnneuxbl thead, #hjsnneuxbl tbody, #hjsnneuxbl tfoot, #hjsnneuxbl tr, #hjsnneuxbl td, #hjsnneuxbl th {
  border-style: none;
}

#hjsnneuxbl p {
  margin: 0;
  padding: 0;
}

#hjsnneuxbl .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hjsnneuxbl .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hjsnneuxbl .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hjsnneuxbl .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hjsnneuxbl .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hjsnneuxbl .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hjsnneuxbl .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hjsnneuxbl .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hjsnneuxbl .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hjsnneuxbl .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hjsnneuxbl .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hjsnneuxbl .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hjsnneuxbl .gt_spanner_row {
  border-bottom-style: hidden;
}

#hjsnneuxbl .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hjsnneuxbl .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hjsnneuxbl .gt_from_md > :first-child {
  margin-top: 0;
}

#hjsnneuxbl .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hjsnneuxbl .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hjsnneuxbl .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hjsnneuxbl .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hjsnneuxbl .gt_row_group_first td {
  border-top-width: 2px;
}

#hjsnneuxbl .gt_row_group_first th {
  border-top-width: 2px;
}

#hjsnneuxbl .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hjsnneuxbl .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hjsnneuxbl .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hjsnneuxbl .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hjsnneuxbl .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hjsnneuxbl .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hjsnneuxbl .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#hjsnneuxbl .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hjsnneuxbl .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hjsnneuxbl .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hjsnneuxbl .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hjsnneuxbl .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hjsnneuxbl .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hjsnneuxbl .gt_left {
  text-align: left;
}

#hjsnneuxbl .gt_center {
  text-align: center;
}

#hjsnneuxbl .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hjsnneuxbl .gt_font_normal {
  font-weight: normal;
}

#hjsnneuxbl .gt_font_bold {
  font-weight: bold;
}

#hjsnneuxbl .gt_font_italic {
  font-style: italic;
}

#hjsnneuxbl .gt_super {
  font-size: 65%;
}

#hjsnneuxbl .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#hjsnneuxbl .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hjsnneuxbl .gt_indent_1 {
  text-indent: 5px;
}

#hjsnneuxbl .gt_indent_2 {
  text-indent: 10px;
}

#hjsnneuxbl .gt_indent_3 {
  text-indent: 15px;
}

#hjsnneuxbl .gt_indent_4 {
  text-indent: 20px;
}

#hjsnneuxbl .gt_indent_5 {
  text-indent: 25px;
}

#hjsnneuxbl .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#hjsnneuxbl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="Variable" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Variable</th>
<th id="Description" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Description</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">test_score</td>
<td class="gt_row gt_left" headers="Description">Test Score (0-100)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">medium</td>
<td class="gt_row gt_left" headers="Description">Medium of note-taking (levels = Longhand, Laptop)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">study</td>
<td class="gt_row gt_left" headers="Description">Study time (levels = No, Minimal, Moderate, Extensive)</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>More detail about this dataset
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The data used for this write-up exercise are simulated, drawing on a research paper that explored the association between student note taking and performance when answering different types of questions. The simulated data are loosely based on the findings of this work, and act to expand upon the methods and results reported in the paper:</p>
<p>Mueller, P. A., &amp; Oppenheimer, D. M. (2014). The pen is mightier than the keyboard: Advantages of longhand over laptop note taking. Psychological Science, 25(6), 1159–1168. <a href="https://doi.org/10.1177/0956797614524581" class="uri">https://doi.org/10.1177/0956797614524581</a></p>
<p>In the current study, participants were invited to take part in a study investigating the the medium of note taking and study time on test scores. The sample comprised 160 students who took notes on a lecture via one of two mediums—either on a laptop or longhand (i.e., using pen and paper). After watching the lecture and taking notes, they were then randomly allocated to one of four study time conditions, either engaging in no, minimal, moderate, or extensive study of the notes taken on their assigned medium. After engaging in study for their allocated time, participants took a test on the lecture content. The test involved a series of questions, where participants could score a maximum of 100 points.</p>
</div>
</div>
</div>
</div>
<div class="frame">
<p>RQ: Is the association between amount of studying and test scores affected by the note-taking medium that people used?</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Provided analysis code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This code should resemble the analysis developed during lectures this week.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interactions: Practice analysis</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Follows workflow here: dapr2/2627/dapr2_flashcards/resources/workflow-b3.html</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Phase 1: Before model fitting ---- </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="do">## 1a: Set up code and data ---- </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the required R packages</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in data</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>notes_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'https://uoepsy.github.io/data/laptop_vs_longhand.csv'</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy data (e.g., any missingness, any implausible values? are data types set correctly?).</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(notes_df)  <span class="co"># no NAs, test_score range looks plausible</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(notes_df)  <span class="co"># lets us see example values for categorical preds, looks OK</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="do">## 1b: Set up the variables you'll model ----</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Based on the RQ, decide whether you'll test your hypotheses using coefficient significance tests or model comparison.</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co"># - RQ: Is the association between amount of studying and test scores affected by the note-taking medium that people used (notes either written longhand or typed on a laptop)?</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co"># - This question asks about associations between predictors and outcomes (and whether other predictors affect this association), so test using coef significance tests.</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Based on the RQ, decide whether your model requires an interaction between predictors.</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co"># - RQ asks whether an association between predictor and outcome is affected by the value of another predictor, so this is a classic interaction RQ.</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Based on the RQ, identify your outcome variable and the predictors.</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co"># - Outcome: `test_score`</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="co"># - Predictors: `medium`, `study`, and their interaction</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up categorical predictors (e.g., factor levels? which contrast coding scheme?)</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co"># - Both categ preds should be converted to factors</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="co"># - We've been using treatment coding for all interaction models so far, so we'll do that here</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="co"># - Reference level of `study` should be "No" (the smallest amount of studying, </span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="co">#   so coefs will tell us how much improvement)</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="co"># - Reference level of `medium` doesn't really matter, let's say "Laptop" so we can see</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="co">#   if "Longhand" is an improvement</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>notes_df <span class="ot">&lt;-</span> notes_df <span class="sc">|&gt;</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">medium =</span> <span class="fu">factor</span>(medium, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'Laptop'</span>, <span class="st">'Longhand'</span>)),</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">study =</span> <span class="fu">factor</span>(study, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'No'</span>, <span class="st">'Minimal'</span>, <span class="st">'Moderate'</span>, <span class="st">'Extensive'</span>))</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="co"># - Check contrast coding</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(notes_df<span class="sc">$</span>medium)</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(notes_df<span class="sc">$</span>study)</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up continuous predictors –  NA.</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="co"># Explore patterns in the data by plotting outcome and predictor variables together</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="co"># - For multiple regression, we plotted predictors separately, but for interactions,</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="co">#   it's nice to combine them all into a single plot.</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>notes_df <span class="sc">|&gt;</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> study, <span class="at">y =</span> test_score, <span class="at">fill =</span> study, <span class="at">colour =</span> study)) <span class="sc">+</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">'point'</span>, <span class="at">colour =</span> <span class="st">'black'</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">'none'</span>) <span class="sc">+</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> medium) <span class="sc">+</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">'Test score'</span>,</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">'Amount of study'</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a nice descriptives table of all relevant variables for the write-up</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>notes_df <span class="sc">|&gt;</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(study, medium) <span class="sc">|&gt;</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(), </span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(test_score), </span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD =</span> <span class="fu">sd</span>(test_score),</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>    <span class="at">Minimum =</span> <span class="fu">min</span>(test_score),</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>    <span class="at">Maximum =</span> <span class="fu">max</span>(test_score)</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>  <span class="co"># rename study and medium column headers for nicer display</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Amount of study'</span> <span class="ot">=</span> study,</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Note-taking medium'</span> <span class="ot">=</span> medium</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Descriptive statistics about test score by amount of study and note-taking medium"</span>, </span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()   </span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="co"># Phase 2: Model fitting ----</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a><span class="co"># Write the mathematical model formulation for your model(s)</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a><span class="co"># - Refer back to contrast matrices to know what the dummy variables will be.</span></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="co">#   $$</span></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a><span class="co">#   \begin{align}</span></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a><span class="co">#   \text{test score} ~=~&amp; \beta_0 ~+ \\</span></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; (\beta_1 \cdot \text{study}_\text{Minimal}) ~+ \\</span></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; (\beta_2 \cdot \text{study}_\text{Moderate}) ~+ \\</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; (\beta_3 \cdot \text{study}_\text{Extensive}) ~+ \\</span></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; (\beta_4 \cdot \text{medium}_\text{Longhand}) ~+ \\</span></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; (\beta_5 \cdot \text{study}_\text{Minimal}   \cdot \text{medium}_\text{Longhand}) ~+ \\</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; (\beta_6 \cdot \text{study}_\text{Moderate}  \cdot \text{medium}_\text{Longhand}) ~+ \\</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; (\beta_7 \cdot \text{study}_\text{Extensive} \cdot \text{medium}_\text{Longhand}) ~+ \\</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; \epsilon</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="co">#   \end{align}</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="co">#   $$</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="co"># - </span><span class="al">NOTE</span><span class="co">: Incorrect model formula (because disregards dummy variables):</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="co">#   $$</span></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="co">#   \begin{align}</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a><span class="co">#   \text{test score} ~=~&amp; \beta_0 ~+ \\</span></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; (\beta_1 \cdot \text{study}) ~+ \\</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; (\beta_2 \cdot \text{medium}) ~+ \\</span></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; (\beta_3 \cdot \text{study} \cdot \text{medium}) ~+ \\</span></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="co">#     &amp; \epsilon</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="co">#   \end{align}</span></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="co">#   $$</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a><span class="co"># Explicitly define the hypotheses that your RQ is aiming to test.</span></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a><span class="co"># - Are any of the interaction terms significant?</span></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a><span class="co">#   $$</span></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="co">#   \begin{align}</span></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a><span class="co">#   H_0 &amp;: \text{All } \beta_j = 0 \text{ for } j = 5, 6, 7\\</span></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="co">#   H_1 &amp;: \text{Any } \beta_j \neq 0\\</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a><span class="co">#   \end{align}</span></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="co">#   $$</span></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit your model(s) using `lm()`.</span></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>notes_mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(test_score <span class="sc">~</span> study <span class="sc">*</span> medium, <span class="at">data =</span> notes_df)</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>notes_mdl</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="co"># Phase 3: After model fitting ----</span></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="do">## 3a: Check assumptions and diagnostics ----</span></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a><span class="co"># Check model assumptions:</span></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a><span class="co"># - Linearity of association -- assume it's met bc all preds are categorical</span></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a><span class="co"># - Independence of errors -- assume it's met bc we have one obs per person</span></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a><span class="co"># - Normality of errors</span></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(notes_mdl, <span class="at">which =</span> <span class="dv">2</span>)  <span class="co"># good!</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="co"># - Equal variance of errors</span></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(notes_mdl, <span class="at">which =</span> <span class="dv">1</span>)  <span class="co"># good! </span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="co">#   (the indiv lines are bc we only observed a handful of diff test scores)</span></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a><span class="co"># Run diagnostics for multicollinearity.</span></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(notes_mdl)  <span class="co"># obviously the interaction term is correlated with both, hence R's recommendation</span></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(notes_mdl, <span class="at">type =</span> <span class="st">'predictor'</span>)  <span class="co"># all GVIF = 1, ideal!</span></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="co"># Run diagnostics for influential observations.</span></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(notes_mdl, <span class="at">which =</span> <span class="dv">4</span>)  <span class="co"># no super extreme influential points, prob no need for sensitivity analysis</span></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="co"># If you find extreme influential observations: run sensitivity analysis. - NA</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="do">## 3b: Plot and interpret model estimates ----</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="co"># Interpret the coefficient estimates</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(notes_mdl)</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(notes_mdl) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="co"># - `(Intercept)`</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="co">#   - The estimated mean test score for people who didn't study at all and who took notes on their laptop was 48.12 points.</span></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="co"># - `studyMinimal`                 </span></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="co">#   - When people took notes on their laptop and studied minimally, their test scores were estimated to increase by 7.45 points compared to laptop note-takers who didn't study at all.</span></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a><span class="co">#   - This estimate is significantly different from zero ($p$ &lt; .001).</span></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a><span class="co"># - `studyModerate`                </span></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a><span class="co">#   - When people took notes on their laptop and studied moderately, their test scores were estimated to increase by 11.18 points compared to laptop note-takers who didn't study at all.</span></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="co">#   - This estimate is significantly different from zero ($p$ &lt; .001).</span></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="co"># - `studyExtensive`               </span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="co">#   - When people took notes on their laptop and studied extensively, their test scores were estimated to increase by 13.04 points compared to laptop note-takers who didn't study at all.</span></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="co">#   - This estimate is significantly different from zero ($p$ &lt; .001).</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="co"># - `mediumLonghand`               </span></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a><span class="co">#   - When people did not study at all and took longhand notes, their test scores were estimated to increase by 2.90 points compared to non-studiers who took notes on a laptop.</span></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="co">#   - This estimate is significantly different from zero ($p$ &lt; .001).</span></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="co"># - `studyMinimal:mediumLonghand`  </span></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="co">#   - For people who take notes longhand, the effect of minimal studying is estimated to increase by 2.44 points.</span></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="co">#   - Or: For people who study minimally, the effect of taking notes longhand is estimated to increase by 2.44 points.</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="co">#   - This estimate is significantly different from zero ($p$ &lt; .001).</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="co"># - `studyModerate:mediumLonghand` </span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="co">#   - For people who take notes longhand, the effect of moderate studying is estimated to increase by 18.49 points.</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a><span class="co">#   - Or: For people who study moderately, the effect of taking notes longhand is estimated to increase by 18.49 points.</span></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a><span class="co">#   - This estimate is significantly different from zero ($p$ &lt; .001).</span></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a><span class="co"># - `studyExtensive:mediumLonghand`</span></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a><span class="co">#   - For people who take notes longhand, the effect of extensive studying is estimated to increase by 26.52 points.</span></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="co">#   - Or: For people who study extensively, the effect of taking notes longhand is estimated to increase by 26.52 points.</span></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a><span class="co">#   - This estimate is significantly different from zero ($p$ &lt; .001).</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate a nicely-formatted regression table.</span></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>  notes_mdl,</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>  <span class="at">dv.labels =</span> <span class="st">'Test score'</span>,</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Linear model coefficient estimates"</span></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare models and interpret model comparison statistics (if appropriate for your RQ) - NA.</span></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot model-fitted values and/or simple slopes/simple effects.</span></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a><span class="fu">cat_plot</span>(</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>  notes_mdl,</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>  <span class="at">pred =</span> <span class="st">'study'</span>,</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>  <span class="at">modx =</span> <span class="st">'medium'</span>,</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>  <span class="at">geom =</span> <span class="st">'line'</span>  <span class="co"># clearly shows the different pattern in each medium</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="do">## 3c: Write up -- in labs! ----</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<!-- # q1 -->
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p><strong>Set the scene (so the reader knows what you’re talking about).</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Remind the reader briefly what the study aimed to test (e.g., what the predictions were).</label></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">

</div>
<div class="solution-body">
<p>In this study, researchers are interested in finding out how people’s test scores are associated with how much they studied for the test, and how this association might depend on whether people initially took notes using a laptop or by writing longhand.</p>
</div>
<p class="solution-end">
</p>
<!-- # q2 -->
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p><strong>Describe and show the sample data (so that the reader knows how generalisable your analysis might be).</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Introduce the variables the study is using to test this prediction, but avoid using R variable names; describe the variables in human-readable terms instead (e.g., what scale are they on? how were they measured?)</label></li>
<li><label><input type="checkbox">Briefly describe the data set: how many observations? what does each observation represent?</label></li>
<li><label><input type="checkbox">Include a table of descriptive statistics for all the relevant variables (and make sure to refer to it in the text).</label>
<ul>
<li>Tip: If this table is really long, then you can keep the main text streamlined by putting the table in an Appendix section.</li>
</ul></li>
<li><label><input type="checkbox">If applicable, mention any data cleaning / outlier removal / transformations.</label></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">

</div>
<div class="solution-body">
<p>We have data from 160 people. Of those people, 80 took notes on a laptop, and the other 80 took notes longhand. Then people were assigned at random to do a certain amount of studying (either none, minimal, moderate, or extensive). Twenty people from each note-taking condition were assigned to each studying condition. Then everybody took a test, and their test scores were recorded. Table 1 summarises the test scores for each group of participants.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>notes_df <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(study, medium) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(), </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(test_score), </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD =</span> <span class="fu">sd</span>(test_score),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Minimum =</span> <span class="fu">min</span>(test_score),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Maximum =</span> <span class="fu">max</span>(test_score)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Amount of study'</span> <span class="ot">=</span> study,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Note-taking medium'</span> <span class="ot">=</span> medium</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Table 1: Descriptive statistics about test score by amount of study and note-taking medium"</span>, </span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>Table 1: Descriptive statistics about test score by amount of study and note-taking medium</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Amount of study</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Note-taking medium</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Minimum</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Maximum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">48.12</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">44.86</td>
<td style="text-align: right;">51.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">No</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">51.02</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">48.02</td>
<td style="text-align: right;">54.92</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">55.57</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">52.07</td>
<td style="text-align: right;">60.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">60.91</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">57.84</td>
<td style="text-align: right;">65.29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">59.30</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">55.77</td>
<td style="text-align: right;">62.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">80.69</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">76.34</td>
<td style="text-align: right;">84.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Extensive</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">61.16</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">56.93</td>
<td style="text-align: right;">64.32</td>
</tr>
<tr class="even">
<td style="text-align: left;">Extensive</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">90.58</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">86.82</td>
<td style="text-align: right;">94.32</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p class="solution-end">
</p>
<!-- # q3 -->
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p><strong>Visualise and summarise data patterns that address the RQ (so the reader knows the basic pattern of what you found).</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Include a plot of the data which includes all relevant variables (and make sure to refer to it in the text).</label>
<ul>
<li>Tip: If you transform any continuous predictors for analysis, use the transformed version of the predictor in the plot.</li>
<li>Tip: Academic writing styles vary, but Elizabeth likes it when figure captions give the reader a brief take-home message about what they should see in the plot.</li>
</ul></li>
<li><label><input type="checkbox">In a sentence or two, describe the overall pattern of results.</label>
<ul>
<li>Tip: If you find yourself listing loads of numbers in the text, consider using tables or plots instead (and they’re better for your word count too!).</li>
<li>Tip: No inferential stats have been done yet, so we can’t make any claims just yet about whether the predictions were supported. But it is OK to say whether the results appear broadly in line with the prediction.</li>
</ul></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">

</div>
<div class="solution-body">
<p>Test scores for each group of participants are also visualised in Figure 1. It appears that people who study more do tend to achieve higher test scores and that taking notes longhand may amplify this effect: people who took notes longhand outperformed laptop note-takers even with less time spent studying.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>notes_df <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> study, <span class="at">y =</span> test_score, <span class="at">fill =</span> study, <span class="at">colour =</span> study)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">'point'</span>, <span class="at">colour =</span> <span class="st">'black'</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">'none'</span>) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> medium) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">'Test score'</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">'Amount of study'</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figure 1: How test scores are associated with amount of study and note-taking medium. Each participant’s data is represented by one coloured dot, and black dots represent the mean test score for each group. In general, as people study more, their test scores tend to increase, and this increase appears much stronger for people who took notes by hand.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<!-- # q4 -->
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p><strong>Introduce your statistical analysis (so the reader can interpret the numbers you will report).</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">State that you’re running your analysis using R, and cite the developers (run <code>citation()</code> in the console to get the citation for your version of R).</label></li>
<li><label><input type="checkbox">State the <span class="math inline">\(\alpha\)</span> level that you’re using for all your analyses (in Psychology, the convention is 5%).</label></li>
<li><label><input type="checkbox">Describe the structure of your model in words, e.g.: “We fit a linear model predicting Y as a function of X1, X2, and their interaction”.</label></li>
<li><label><input type="checkbox">Include the mathematical model formulation of your model.</label></li>
<li><label><input type="checkbox">Explain the hypotheses that your analysis will test and include them in mathematical notation.</label></li>
<li><label><input type="checkbox">If categorical predictors, describe contrast coding, e.g.: “X1 has two levels, A (coded as –1) and B (coded as 1)”.</label></li>
<li><label><input type="checkbox">If continuous predictors have been transformed, describe the transformation, e.g.: “X2 has been z-scored”.</label></li>
<li><label><input type="checkbox">For each model assumption, state whether you are satisfied that the assumption has been met.</label></li>
<li><label><input type="checkbox">Include plots for each assumption check as figures in the Appendix section of the document (and refer to them in the main text).</label></li>
<li><label><input type="checkbox">If you detected any high-influence observations and then conducted a sensitivity analysis, mention whether the pattern of results stayed the same even after removing each influential observation.</label>
<ul>
<li>Tip: If you’ll report your results using the full regression table for your coefficients, then also include the full regression table for the sensitivity analysis in another Appendix section.</li>
</ul></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">

</div>
<div class="solution-body">
<p>We conducted all statistical analyses using R (R Core Team, 2025), and we will consider effects significant at <span class="math inline">\(\alpha = .05\)</span>.</p>
<p>To test whether the association between amount of study and test scores is significantly affected by note-taking medium, we fit a linear model predicting people’s test scores as a function of how much they studied, what note-taking medium they used, and the interaction between these two variables. We coded the “study” variable using treatment coding, with “no studying” as the reference level. We also coded the “medium” variable using treatment coding, and there, “Laptop” is the reference level.</p>
<p>Formally, the model we fit is the following:</p>
<p><span class="math display">\[
\begin{align}
\text{test score} ~=~&amp; \beta_0 ~+ \\
  &amp; (\beta_1 \cdot \text{study}_\text{Minimal}) ~+ \\
  &amp; (\beta_2 \cdot \text{study}_\text{Moderate}) ~+ \\
  &amp; (\beta_3 \cdot \text{study}_\text{Extensive}) ~+ \\
  &amp; (\beta_4 \cdot \text{medium}_\text{Longhand}) ~+ \\
  &amp; (\beta_5 \cdot \text{study}_\text{Minimal}   \cdot \text{medium}_\text{Longhand}) ~+ \\
  &amp; (\beta_6 \cdot \text{study}_\text{Moderate}  \cdot \text{medium}_\text{Longhand}) ~+ \\
  &amp; (\beta_7 \cdot \text{study}_\text{Extensive} \cdot \text{medium}_\text{Longhand}) ~+ \\
  &amp; \epsilon
\end{align}
\]</span></p>
<p>Our aim was to test the null hypothesis that all of the interaction coefficients are equal to zero:</p>
<p><span class="math display">\[
\begin{align}
H_0 &amp;: \text{All } \beta_j = 0 \text{ for } j = 5, 6, 7\\
H_1 &amp;: \text{Any } \beta_j \neq 0\\
\end{align}
\]</span> After we fit the model, we made sure we were satisfied that its assumptions were met. Linearity of association can be assumed, since the predictors are categorical, and independence of errors can be assumed, since each participant contributed only one observation to the dataset. We are also satisfied that errors are sufficiently normally distributed (see Figure A.1 in Appendix A) with sufficiently equal variance (see Figure A.2 in Appendix A). Additionally, we checked for multicollinearity between predictors and found that all GVIF values were equal to 1, indicating no problematic correlation between predictors, and we found no observations that influenced the model’s estimates unduly. We therefore proceed to report the results of our analysis.</p>
</div>
<p class="solution-end">
</p>
<!-- # q5 -->
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p><strong>Report the results of your analysis (so the reader knows exactly what you found).</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">State which model coefficient(s) are related to which prediction(s), and what direction/sign (positive or negative) you would expect the coefficients to have if the predictions were borne out, if applicable.</label></li>
<li><label><input type="checkbox">State the key coefficient estimates along with their 95% CI and p-value, e.g.: “The slope associating X1 and Y was significantly different from zero (<span class="math inline">\(b\)</span> = 0.26, 95% CI [0.23, 0.29], <span class="math inline">\(p\)</span> &lt; .001)” or “The slope associating X1 and Y was not significantly different from zero (<span class="math inline">\(b\)</span> = 0.26, 95% CI [–0.04, 0.56], <span class="math inline">\(p\)</span> = .18)”, if applicable.</label>
<ul>
<li>Tip: You don’t need to report every single parameter estimate. Focus on the one(s) you identified as being relevant to your prediction(s).</li>
<li>Tip: Briefly link the direction and significance of the effect back to your earlier predictions—is the prediction supported by the parameter estimate?</li>
</ul></li>
<li><label><input type="checkbox">Include a table of all coefficients estimated by the linear model (and make sure to refer to it in the text), if applicable. The function <code>tab_model()</code> from the package <code>sjPlot</code> may be useful here, but note that <code>tab_model()</code> causes Rmd files to fail to knit to PDF, so you might want to manually recreate the table it produces.</label>
<ul>
<li>Tip: if you DO report all coefficient estimates in the text, then there’s no need to include the coefficient table because the information is redundant.</li>
</ul></li>
<li><label><input type="checkbox">Plot the model-fitted values (and refer to the plot in the text), if applicable.</label></li>
<li><label><input type="checkbox">Report the results of a model comparison, if applicable.</label></li>
<li><label><input type="checkbox">Report any other information you consider important for your story!</label></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">

</div>
<div class="solution-body">
<p>If with the same amount of studying, people achieved higher test scores after taking longhand notes, we would expect all the interaction coefficients to be positive and significantly different from zero. (This is because an already-positive effect of studying would become more positive still after adjustment from a positive interaction term.) That is indeed what we find; we therefore reject the null hypothesis that there is no difference between how amount of study is associated with test score for each note-taking medium.</p>
<p>Specifically: for laptop note-takers, we found that minimal studying was estimated to increase test score by 7.45 points compared to no studying (<span class="math inline">\(b\)</span> = 7.45, 95% CI [6.20, 8.70], <span class="math inline">\(p\)</span> &lt; .001); for longhand note-takers, this effect was estimated to increase by a further 2.44 points (<span class="math inline">\(b\)</span> = 2.44, 95% CI [0.67, 4.21], <span class="math inline">\(p\)</span> &lt; .001).</p>
<p>Next, laptop note-takers’ scores increased after moderate study by an estimated 11.18 points compared to no studying (<span class="math inline">\(b\)</span> = 11.18, 95% CI [9.93, 12.43], <span class="math inline">\(p\)</span> &lt; .001), while longhand note-takers’ scores were estimated to increase by an additional 18.49 points (<span class="math inline">\(b\)</span> = 18.49, 95% CI [16.72, 20.26], <span class="math inline">\(p\)</span> &lt; .001).</p>
<p>Finally, after extensive study, laptop note-takers’ scores were estimated to increase by 13.04 points compared to no studying (<span class="math inline">\(b\)</span> = 13.04, 95% CI [11.79, 14.29], <span class="math inline">\(p\)</span> &lt; .001), and for longhand note-takers, this increase was estimated to grow by another 26.52 points (<span class="math inline">\(b\)</span> = 26.52, 95% CI [24.75, 28.29], <span class="math inline">\(p\)</span> &lt; .001).</p>
<p>For an overview of all regression coefficients, see Table 2.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  notes_mdl,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">dv.labels =</span> <span class="st">'Test score'</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Table 2: Linear model coefficient estimates"</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2: Linear model coefficient estimates</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Test score</th>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">48.12</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">47.24&nbsp;–&nbsp;49.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Minimal]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.45</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6.20&nbsp;–&nbsp;8.70</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Moderate]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">11.18</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9.93&nbsp;–&nbsp;12.43</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Extensive]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">13.04</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">11.79&nbsp;–&nbsp;14.29</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">medium [Longhand]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.90</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.65&nbsp;–&nbsp;4.15</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Minimal] × medium<br>
[Longhand]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.44</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.67&nbsp;–&nbsp;4.21</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.007</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Moderate] × medium<br>
[Longhand]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">18.49</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">16.72&nbsp;–&nbsp;20.26</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Extensive] ×<br>
medium [Longhand]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">26.52</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">24.75&nbsp;–&nbsp;28.29</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">160</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.980 / 0.979</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The pattern of model-estimated test scores for all combinations of conditions is shown in Figure 2.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat_plot</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  notes_mdl,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">pred =</span> <span class="st">'study'</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">modx =</span> <span class="st">'medium'</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">geom =</span> <span class="st">'line'</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figure 2: Model-estimated test scores for all combinations of amounts of studying and note-taking medium. Points represent the estimated test score for each group, and error bars represent their 95% CIs. Test scores are estimated to improve substantially more with study after people took longhand notes, compared to taking notes on a laptop.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<!-- # q6 -->
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p><strong>Appendices might include:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Descriptives tables that are too big/disruptive to include in main text</label></li>
<li><label><input type="checkbox">Figures that visualise assumption checks</label></li>
<li><label><input type="checkbox">Sensitivity analysis regression table / any other useful details</label></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">

</div>
<div class="solution-body">
<p><strong>Appendix A: Model assumption checks</strong></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(notes_mdl, <span class="at">which =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figure A.1: In a Q-Q plot, normally-distributed errors should follow the dashed diagonal line. The residuals of our model appear sufficiently normally distributed.</figcaption>
</figure>
</div>
</div>
</div>
<p><br></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(notes_mdl, <span class="at">which =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figure A.2: In a residuals vs.&nbsp;fitted plot, errors with equal variance should be evenly vertically distributed across the whole range of the fitted values on the x axis. Our model’s residuals appear to have sufficiently equal variance.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="solution-begin">

</div>
<div class="solution-body">
<p>In this study, researchers are interested in finding out how people’s test scores are associated with how much they studied for the test, and how this association might depend on whether people initially took notes using a laptop or by writing longhand.</p>
<p>We have data from 160 people. Of those people, 80 took notes on a laptop, and the other 80 took notes longhand. Then people were assigned at random to do a certain amount of studying (either none, minimal, moderate, or extensive). Twenty people from each note-taking condition were assigned to each studying condition. Then everybody took a test, and their test scores were recorded. Table 1 summarises the test scores for each group of participants.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>Table 1: Descriptive statistics about test score by amount of study and note-taking medium</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Amount of study</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Note-taking medium</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Minimum</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Maximum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">48.12</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">44.86</td>
<td style="text-align: right;">51.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">No</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">51.02</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">48.02</td>
<td style="text-align: right;">54.92</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">55.57</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">52.07</td>
<td style="text-align: right;">60.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">60.91</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">57.84</td>
<td style="text-align: right;">65.29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">59.30</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">55.77</td>
<td style="text-align: right;">62.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">80.69</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">76.34</td>
<td style="text-align: right;">84.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Extensive</td>
<td style="text-align: left;">Laptop</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">61.16</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">56.93</td>
<td style="text-align: right;">64.32</td>
</tr>
<tr class="even">
<td style="text-align: left;">Extensive</td>
<td style="text-align: left;">Longhand</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">90.58</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">86.82</td>
<td style="text-align: right;">94.32</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<p>Test scores for each group of participants are also visualised in Figure 1. It appears that people who study more do tend to achieve higher test scores and that taking notes longhand may amplify this effect: people who took notes longhand outperformed laptop note-takers even with less time spent studying.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figure 1: How test scores are associated with amount of study and note-taking medium. Each participant’s data is represented by one coloured dot, and black dots represent the mean test score for each group. In general, as people study more, their test scores tend to increase, and this increase appears much stronger for people who took notes by hand.</figcaption>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>We conducted all statistical analyses using R (R Core Team, 2025), and we will consider effects significant at <span class="math inline">\(\alpha = .05\)</span>.</p>
<p>To test whether the association between amount of study and test scores is significantly affected by note-taking medium, we fit a linear model predicting people’s test scores as a function of how much they studied, what note-taking medium they used, and the interaction between these two variables. We coded the “study” variable using treatment coding, with “no studying” as the reference level. We also coded the “medium” variable using treatment coding, and there, “Laptop” is the reference level.</p>
<p>Formally, the model we fit is the following:</p>
<p><span class="math display">\[
\begin{align}
\text{test score} ~=~&amp; \beta_0 ~+ \\
  &amp; (\beta_1 \cdot \text{study}_\text{Minimal}) ~+ \\
  &amp; (\beta_2 \cdot \text{study}_\text{Moderate}) ~+ \\
  &amp; (\beta_3 \cdot \text{study}_\text{Extensive}) ~+ \\
  &amp; (\beta_4 \cdot \text{medium}_\text{Longhand}) ~+ \\
  &amp; (\beta_5 \cdot \text{study}_\text{Minimal}   \cdot \text{medium}_\text{Longhand}) ~+ \\
  &amp; (\beta_6 \cdot \text{study}_\text{Moderate}  \cdot \text{medium}_\text{Longhand}) ~+ \\
  &amp; (\beta_7 \cdot \text{study}_\text{Extensive} \cdot \text{medium}_\text{Longhand}) ~+ \\
  &amp; \epsilon
\end{align}
\]</span></p>
<p>Our aim was to test the null hypothesis that all of the interaction coefficients are equal to zero:</p>
<p><span class="math display">\[
\begin{align}
H_0 &amp;: \text{All } \beta_j = 0 \text{ for } j = 5, 6, 7\\
H_1 &amp;: \text{Any } \beta_j \neq 0\\
\end{align}
\]</span></p>
<p>After we fit the model, we made sure we were satisfied that its assumptions were met. Linearity of association can be assumed, since the predictors are categorical, and independence of errors can be assumed, since each participant contributed only one observation to the dataset. We are also satisfied that errors are sufficiently normally distributed (see Figure A.1 in Appendix A) with sufficiently equal variance (see Figure A.2 in Appendix A). Additionally, we checked for multicollinearity between predictors and found that all GVIF values were equal to 1, indicating no problematic correlation between predictors, and we found no observations that influenced the model’s estimates unduly. We therefore proceed to report the results of our analysis.</p>
<p>If with the same amount of studying, people achieved higher test scores after taking longhand notes, we would expect all the interaction coefficients to be positive and significantly different from zero. (This is because an already-positive effect of studying would become more positive still after adjustment from a positive interaction term.) That is indeed what we find; we therefore reject the null hypothesis that there is no difference between how amount of study is associated with test score for each note-taking medium.</p>
<p>Specifically: for laptop note-takers, we found that minimal studying was estimated to increase test score by 7.45 points compared to no studying (<span class="math inline">\(b\)</span> = 7.45, 95% CI [6.20, 8.70], <span class="math inline">\(p\)</span> &lt; .001); for longhand note-takers, this effect was estimated to increase by a further 2.44 points (<span class="math inline">\(b\)</span> = 2.44, 95% CI [0.67, 4.21], <span class="math inline">\(p\)</span> &lt; .001).</p>
<p>Next, laptop note-takers’ scores increased after moderate study by an estimated 11.18 points compared to no studying (<span class="math inline">\(b\)</span> = 11.18, 95% CI [9.93, 12.43], <span class="math inline">\(p\)</span> &lt; .001), while longhand note-takers’ scores were estimated to increase by an additional 18.49 points (<span class="math inline">\(b\)</span> = 18.49, 95% CI [16.72, 20.26], <span class="math inline">\(p\)</span> &lt; .001).</p>
<p>Finally, after extensive study, laptop note-takers’ scores were estimated to increase by 13.04 points compared to no studying (<span class="math inline">\(b\)</span> = 13.04, 95% CI [11.79, 14.29], <span class="math inline">\(p\)</span> &lt; .001), and for longhand note-takers, this increase was estimated to grow by another 26.52 points (<span class="math inline">\(b\)</span> = 26.52, 95% CI [24.75, 28.29], <span class="math inline">\(p\)</span> &lt; .001).</p>
<p>For an overview of all regression coefficients, see Table 2.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2: Linear model coefficient estimates</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Test score</th>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">48.12</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">47.24&nbsp;–&nbsp;49.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Minimal]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.45</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6.20&nbsp;–&nbsp;8.70</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Moderate]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">11.18</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9.93&nbsp;–&nbsp;12.43</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Extensive]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">13.04</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">11.79&nbsp;–&nbsp;14.29</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">medium [Longhand]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.90</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.65&nbsp;–&nbsp;4.15</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Minimal] × medium<br>
[Longhand]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.44</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.67&nbsp;–&nbsp;4.21</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.007</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Moderate] × medium<br>
[Longhand]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">18.49</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">16.72&nbsp;–&nbsp;20.26</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">study [Extensive] ×<br>
medium [Longhand]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">26.52</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">24.75&nbsp;–&nbsp;28.29</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">160</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.980 / 0.979</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<p>The pattern of model-estimated test scores for all combinations of conditions is shown in Figure 2.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figure 2: Model-estimated test scores for all combinations of amounts of studying and note-taking medium. Points represent the estimated test score for each group, and error bars represent their 95% CIs. Test scores are estimated to improve substantially more with study after people took longhand notes, compared to taking notes on a laptop.</figcaption>
</figure>
</div>
</div>
</div>
<p><br></p>
<p><strong>Appendix A: Model assumption checks</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figure A.1: In a Q-Q plot, normally-distributed errors should follow the dashed diagonal line. The residuals of our model appear sufficiently normally distributed.</figcaption>
</figure>
</div>
</div>
</div>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figure A.2: In a residuals vs.&nbsp;fitted plot, errors with equal variance should be evenly vertically distributed across the whole range of the fitted values on the x axis. Our model’s residuals appear to have sufficiently equal variance.</figcaption>
</figure>
</div>
</div>
</div>
<p><br></p>
<p><strong>References</strong></p>
<p>R Core Team (2025). <em>R: A Language and Environment for Statistical Computing</em>. R Foundation for Statistical Computing, Vienna, Austria. <a href="https://www.R-project.org/" class="uri">https://www.R-project.org/</a>.</p>
</div>
<p class="solution-end">
</p>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>