---
title: 'dapR2 (week 1): Functions Quiz'
author: "Tom Booth"
date: "14/09/2020"
output: html_document
---

# Function 1

For the input $x = [0,1,2,3,4,5,6,7,8,9,10]$, which of the following best describes the function in plot 1?

a. $f(x) = 10 + 2x$
b. $f(x) = 10 + x$
c. $f(x) = x + 2x$
d. $f(x) = 6x$

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
df <- tibble(
  x = 0:10
  ) %>%
  mutate(
    f1 = x + 2*x,
    f2 = x -5,
    f3 = 5 + (x-1)^2
  )
 
ggplot(df, aes(x=x, y = f1)) +
  geom_line() +
  scale_x_continuous(breaks=1:10) +
  scale_y_continuous(breaks=seq(0,30,5)) +
  ggtitle("Plot 1") -> p1

ggsave(filename = "../docs/quiz_images/functions_quiz1.png",plot = p1)

p1
```


# Function 2

For the input $x = [0,1,2,3,4,5,6,7,8,9,10]$, which of the following best describes the function in plot 2?

a. $f(x) = 1 + 4x$
b. $f(x) = 10 + x + 2$
c. $f(x) = x^2$
d. $f(x) = x - 5$

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ggplot(df, aes(x=x, y = f2)) +
  geom_line() +
  scale_x_continuous(breaks=1:10) +
  scale_y_continuous(breaks=seq(-5,5,1)) +
  ggtitle("Plot 2") -> p2

ggsave(filename = "../docs/quiz_images/functions_quiz2.png",plot = p2)
p2
```


# Function 3

For the input $x = [0,1,2,3,4,5,6,7,8,9,10]$, which of the following best describes the function in plot 3?

a. $f(x) = x - 2x$
b. $f(x) = 5 + (x-1)^2$
c. $f(x) = x^3$
d. $f(x) = xz$

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ggplot(df, aes(x=x, y = f3)) +
  geom_line() +
  scale_x_continuous(breaks=1:10) +
  scale_y_continuous(breaks=seq(0,100,10)) +
  ggtitle("Plot 3") -> p3

ggsave(filename = "../docs/quiz_images/functions_quiz3.png",plot = p3)
p3
```