---
title: ' Lecture 17:Evaluating and interpreting solutions '
subtitle: 'Research Methods & Statistics 3  Alex Weiss: alex.weiss@ed.ac.uk, B18 7 George Square '
author: Tom Booth
date: 2020-06-23
output:
  xaringan::moon_reader:
  lib_dir: libs
  nature:
    highlightStyle: github
    highlightLines: true
    countIncrementalSlides: false
---
#  Todays lecture 


**Before all of this, a decision is made on the data reduction approach.**
+ Check the appropriateness of the data and decide of the appropriate estimator .
+ Decide which methods to use to select a number of factors.
+ Decide conceptually whether to apply rotation and how to do so.
+ **Decide** **on the criteria** **to assess and modify your solution** **.**
+ **Run** **the** **analysis.**
+ **Evaluate** **the solution** **(apply 4)**
+ **Select** **a final** **solution and interpret the model, labelling the factors.**
+ Report your results (problem set task)

---
#  Big picture 

+ Once we have….
	+ Made a decision on data reduction approach.
	+ Made a decision on model estimation.
	+ Checked our data.
	+ Decided on a plausible range for the number of factors…
+ We then need to look at each solution within that range and evaluate it and interpret it.
	+ We can evaluate different aspects of the results.
	+ Ideally we should make decisions on what information to use before we begin.

---
#  Evaluating Factor Solutions 

+ Overall model:
	+ Conceptual sense
	+ Total variance explained
+ Factor:
	+ Number of factors
	+ Number of items per factor
+ Individual items:
	+ Communalities
	+ Pattern and magnitude of factor loadings
		+ Item complexity


---
#  Evaluating Factor Solutions: Overall Model 

+ Ultimate criteria here is do our factors make conceptual sense.
	+ If a questionnaire has a known structure, does it match?
	+ Read the items, do they seem coherent?
	+ Are there other features of the items which may lead them to group? Think design issues. 


---
#  Evaluating Factor Solutions: Overall Model 

+ Sometimes we may consider total variance explained.
	+ Some target 50%
		+ Setting a cut like this not optimal.
	+ Remember if we add factors we will always explain more variance.
	+ Should always report explained variance by retained factors .


---
#  Evaluating Factor Solutions: Factors 

+ Selecting which solution within your plausible range of factors would fall under evaluation.
	+ Which of your solutions looks like it is most coherent?
	+ When you add or remove factors, which sets of items change in their patterns of loadings?
+ Each factor should have at least 3 items for which it has the primary loading.
	+ This is a minimum, and is based on model identification.
	+ Conceptually, if you only have 2 items with primary loadings, your factor is one correlation – not a strong common cause.
	+ Note, this can be due to questionnaire design (again) – how many items were included to measure a given construct?


---
#  Evaluating Factor Solutions: Items 

+ The item must relate to other items.
	+ We can assess this using the communality estimates, KMO stats for items or simply conceptually.
+ Generally, each item must have at least 1 factor loading above a set level.
	+ Often people use loadings > .30
	+ This is arbitrary and relates to ~9% explained variance in item by the factor .
+ Items should not be too complex unless theoretically justified.


---
#  What is complexity? 

+ Think back to simple structure:
	+ If an item has a large primary loading, and small cross-loadings.
		+ These items are considered ***simple*** **.**
	+ If an item has evenly distributed loadings, then it relates equally to lots of factors.
		+ It is then not clear where it “belongs”
		+ These items are considered ***complex.***
+ In R, this is quantified by a complexity index (which we will show shortly).

---
#  Evaluating Factor Solutions:A priori criteria 

+ There are lots of decisions which need to be made in an EFA analysis.
+ There are lots of ways to evaluate solutions.
+ Thus it is very important that the particular criteria you wish to use are set out a priori, and then consistently applied in your analysis.


---
#  Modifying Factor Solutions: Some general guidelines 

+ If we do not have 3 items on all factors, run a model with 1 factor less.
	+ Important to check conceptual consistency when we do this.
+ If we have a factor which has more than 3 loadings, but none are primary loadings, run a model with 1 factor less.
	+ Important to check conceptual consistency when we do this.


---
#  Modifying Factor Solutions: Some general guidelines 

+ If an item has low communality, or does not load on any factor above our minimum value:
	+ Remove the item.
+ If an item is highly complex (loads on more than one factor at ~the same factor loading)
	+ Consider if this is theoretically reasonable.
	+ If not, remove the item.
		+ R provides a metric of complexity which we can use to judge items.
		+ Ranges from 1 (simple) to no. of factors (most complex)


---
#  Modifying Factor Solutions:Some general guidelines 

+ Set out how you will modify at the start of the analysis and be consistent.
+ Modification is an iterative process.
	+ May take a few iterations and adjustments  to settle at a model you believe is reasonable .
	+ That is OK, this is just the nature of **exploratory** factor analysis.
		+ Clue is in the title.


---
#  Things to consider 

+ If you remove an item from an analysis, the analysis needs to be re-run before you evaluate other items.
	+ The solution will change when this item is dropped .
	+ Modification is iterative.
+ If you remove items from, say, a 3 factor solution, you should return to the full set when you evaluate, say, a 2 factor solution.
	+ That is you evaluate items in the context of each solution.
+ The most important thing is that the final solution is substantively coherent.

---
#  Let’s run an analysis 



---
#  Example:A priori decisions 

+ Initial decisions:
	+ Factor analysis not PCA.
	+ Maximum likelihood estimation.
	+ Oblique rotation
	+ Theoretical no. of factors 3.
		+ Additional tests: scree plot; MAP; PA with components.
+ Evaluating and modifying solution:
	+ Minimal no. of items per factor = 3
	+ Minimal loadings considered salient = .33 (10%)
	+ Consider complexity values
+ Overarching: Do the factors make conceptual sense?

---
#  Tasks for this week… 

+ **Problem** **set:** Glossary, and evaluation of a published paper.
+ **Lab:** Weeks 3 to 5 you will be doing a large EFA analysis.
	+ This week you will be running, modifying and interpreting the main FA.
+ **Reading:** Reading list on LEARN.
+ **Homework:** Factor analysis 1 .
	+ Live now, closes Sunday at 17:00
