<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Write Up Example &amp; Block 4 Recap</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-circle-right')) {
    f.classList.add('fa-circle-down')
    f.classList.remove('fa-circle-right')
} else {
    f.classList.add('fa-circle-right')
    f.classList.remove('fa-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      DAPR2
      </li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DAPR2</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Semester 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Intro to Linear Models</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_01_slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_02_mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_03_mlr_stz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression &amp; Standardization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_04_model_fit_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model Fit and Comparisons</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_05_writeup_recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 1 Analysis &amp; Write-Up Example</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Analysing and Evaluating Experimental Studies</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_06_dummy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dummy Coding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_07_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Effects Coding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_08_assump_diag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assumptions and Diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_09_bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrapping</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_10_writeup_recap2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 2 Analysis &amp; Write-Up Example</span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Semester 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Interaction Models</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_b3_reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Blocks 1, 2, &amp; 3 Flash Cards</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_01_int1_nc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactions I: Num x Cat</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_02_int2_nn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactions II: Num x Num</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_03_int3_cc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactions III: Cat x Cat</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_04_simp_pair.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple Effects, Pairwise Comparisons, &amp; Corrections</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_05_writeup_recap3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Block 3 Analysis &amp; Write-Up Example</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Advanced Topics for LM</span></span>
  </li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#section-a-write-up" id="toc-section-a-write-up" class="nav-link active" data-scroll-target="#section-a-write-up">Section A: Write-Up</a>
  <ul class="collapse">
<li>
<a href="#study-overview" id="toc-study-overview" class="nav-link" data-scroll-target="#study-overview">Study Overview</a>
  <ul class="collapse">
<li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#analysis-code" id="toc-analysis-code" class="nav-link" data-scroll-target="#analysis-code">Analysis Code</a></li>
  <li><a href="#the-3-act-structure-analysis-strategy-results-discussion" id="toc-the-3-act-structure-analysis-strategy-results-discussion" class="nav-link" data-scroll-target="#the-3-act-structure-analysis-strategy-results-discussion">The 3-Act Structure: Analysis Strategy, Results, &amp; Discussion</a></li>
  </ul>
</li>
  </ul>
</li>
  <li><a href="#section-b-weeks-6-9-recap" id="toc-section-b-weeks-6-9-recap" class="nav-link" data-scroll-target="#section-b-weeks-6-9-recap">Section B: Weeks 6-9 Recap</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Write Up Example &amp; Block 4 Recap</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand how to write-up and provide interpretation of a binary logistic regression model</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed previous lab exercises from <a href="https://uoepsy.github.io/dapr2/2324/labs/2_07_glm1.html">Semester 2 Week 7</a> and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_08_glm2.html">Semester 2 Week 8</a>
</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>patchwork</strong></li>
<li><strong>kableExtra</strong></li>
<li><strong>psych</strong></li>
<li><strong>sjPlot</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/mallow2.csv">here</a> or read it in via this link https://uoepsy.github.io/data/mallow2.csv</p>
</section>
</div>
<section id="section-a-write-up" class="level1"><h1>Section A: Write-Up</h1>
<p>In this section of the lab you will be be presented with a research question, and tasked with writing up and presenting your analyses.</p>
<p>The aim in writing should be that a reader is able to more or less replicate your analyses <strong>without</strong> referring to your <code>R</code> code. This requires detailing all of the steps you took in conducting the analysis. The point of using RMarkdown is that you can pull your results <strong>directly</strong> from the code. If your analysis changes, so does your report!</p>
<p>Make sure that your final report doesn’t show any R functions or code. Remember you are interpreting and reporting your results in text, tables, or plots, targeting a generic reader who may use different software or may not know R at all. If you need a reminder on how to hide code, format tables, etc., make sure to review the <a href="https://uoepsy.github.io//rmd-bootcamp/">rmd bootcamp</a>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important - Write-Up Examples &amp; Plagiarism
</div>
</div>
<div class="callout-body-container callout-body">
<p>The example write-up sections included below are not <strong>perfect</strong> - they instead should give you a good example of what information you should include within each section, and how to structure this. For example, some information is missing (e.g., interpretation of descriptive statistics, what type of interaction is present), some information could be presented more clearly (e.g., variable names in tables, table/figure titles/captions, and rationales for choices), and writing could be more concise in places (e.g., discussion section is quite long).</p>
<p>Further, <strong>you must not copy any of the write-up included below for future reports</strong> - if you do, you will be committing plagiarism, and this type of academic misconduct is taken very seriously by the University. You can find out more <a href="https://www.ed.ac.uk/academic-services/students/conduct/academic-misconduct">here</a>.</p>
</div>
</div>
<section id="study-overview" class="level2"><h2 class="anchored" data-anchor-id="study-overview">Study Overview</h2>
<blockquote class="blockquote">
<p><strong>Research Aim</strong></p>
<p>Explore the associations among the ability to delay gratification and age, visibility, and time of day.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Research Question</strong></p>
<ul>
<li>Does the probability of delaying gratification change as a function of age, marshmallow visibility, and time of day?</li>
</ul>
</blockquote>
<div class="optional-begin">
<span id="opt-start-1" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Marshmallows: Data Codebook</span></span>
</div>
<div class="optional-body" id="opt-body-1" style="display: none;">



<p><strong>Description</strong></p>
<p>The data used for this write-up exercise are simulated, drawing on the Stanford marshmallow experiment - a study on delayed gratification in children. The simulated data are loosely based on the findings of this work, and acted to expand upon the methods and results reported in the paper:</p>
<p>Mischel, W., Ebbesen, E. B., &amp; Raskoff Zeiss, A. (1972). Cognitive and attentional mechanisms in delay of gratification. <em>Journal of Personality and Social Psychology, 21</em>(2), 204–218. <a href="https://doi.org/10.1037/h0032198">https://doi.org/10.1037/h0032198</a></p>
<p>In the current study, a sample of 304 children, ranging in ages from 3 to 10 years old, took part. Each child was shown a marshmallow, and it was explained that they were about to be left alone for 10 minutes. They were told that they were welcome to eat the marshmallow while they were waiting, but if the marshmallow was still there after 10 minutes, they would be rewarded with <strong>two</strong> marshmallows.</p>
<p>For half of the children who took part, the marshmallow was visible for the entire 10 minutes (or until they ate it!). For the other half, the marshmallow was placed under a plastic cup.</p>
<p>The experiment took part at various times throughout the working day, and researchers were worried about children being more hungry at certain times of day, so they kept track of whether each child completed the task in the morning or the afternoon, so that they could control for this in their analyses.</p>
<p>For an example of the marshmallow experiment, watch the following video:</p>
<p align="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/QX_oy9614HQ?si=xC0fAVA34i3ha_7L" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="">
</iframe>
</p>
<p><br></p>
<p><strong>Data Dictionary</strong></p>
<p>The data in <code>mallow2.csv</code> contain five attributes collected from a simulated sample of <span class="math inline">\(n=304\)</span> hypothetical individuals, and includes:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="pqxkbfqhgj" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#pqxkbfqhgj table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#pqxkbfqhgj thead, #pqxkbfqhgj tbody, #pqxkbfqhgj tfoot, #pqxkbfqhgj tr, #pqxkbfqhgj td, #pqxkbfqhgj th {
  border-style: none;
}

#pqxkbfqhgj p {
  margin: 0;
  padding: 0;
}

#pqxkbfqhgj .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#pqxkbfqhgj .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#pqxkbfqhgj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#pqxkbfqhgj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#pqxkbfqhgj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#pqxkbfqhgj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#pqxkbfqhgj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#pqxkbfqhgj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#pqxkbfqhgj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#pqxkbfqhgj .gt_spanner_row {
  border-bottom-style: hidden;
}

#pqxkbfqhgj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#pqxkbfqhgj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#pqxkbfqhgj .gt_from_md > :first-child {
  margin-top: 0;
}

#pqxkbfqhgj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#pqxkbfqhgj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#pqxkbfqhgj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#pqxkbfqhgj .gt_row_group_first td {
  border-top-width: 2px;
}

#pqxkbfqhgj .gt_row_group_first th {
  border-top-width: 2px;
}

#pqxkbfqhgj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#pqxkbfqhgj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#pqxkbfqhgj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#pqxkbfqhgj .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#pqxkbfqhgj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_left {
  text-align: left;
}

#pqxkbfqhgj .gt_center {
  text-align: center;
}

#pqxkbfqhgj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#pqxkbfqhgj .gt_font_normal {
  font-weight: normal;
}

#pqxkbfqhgj .gt_font_bold {
  font-weight: bold;
}

#pqxkbfqhgj .gt_font_italic {
  font-style: italic;
}

#pqxkbfqhgj .gt_super {
  font-size: 65%;
}

#pqxkbfqhgj .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#pqxkbfqhgj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#pqxkbfqhgj .gt_indent_1 {
  text-indent: 5px;
}

#pqxkbfqhgj .gt_indent_2 {
  text-indent: 10px;
}

#pqxkbfqhgj .gt_indent_3 {
  text-indent: 15px;
}

#pqxkbfqhgj .gt_indent_4 {
  text-indent: 20px;
}

#pqxkbfqhgj .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Variable">Variable</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Description">Description</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="Variable" class="gt_row gt_left">name</td>
<td headers="Description" class="gt_row gt_left">Participant name</td>
</tr>
<tr>
<td headers="Variable" class="gt_row gt_left">agemonths</td>
<td headers="Description" class="gt_row gt_left">Age (in months)</td>
</tr>
<tr>
<td headers="Variable" class="gt_row gt_left">timeofday</td>
<td headers="Description" class="gt_row gt_left">Time of day that the experiment took place ('am' = morning, 'pm' = afternoon)</td>
</tr>
<tr>
<td headers="Variable" class="gt_row gt_left">visibility</td>
<td headers="Description" class="gt_row gt_left">Experimental condition - whether the marshmallow was 'visible' or 'hidden' for the 10 minutes</td>
</tr>
<tr>
<td headers="Variable" class="gt_row gt_left">taken</td>
<td headers="Description" class="gt_row gt_left">Whether or not the participant took ('taken') the marshmallow within the 10 minutes or left it ('waited')</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="xqiwkyfqay" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#xqiwkyfqay table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#xqiwkyfqay thead, #xqiwkyfqay tbody, #xqiwkyfqay tfoot, #xqiwkyfqay tr, #xqiwkyfqay td, #xqiwkyfqay th {
  border-style: none;
}

#xqiwkyfqay p {
  margin: 0;
  padding: 0;
}

#xqiwkyfqay .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xqiwkyfqay .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#xqiwkyfqay .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xqiwkyfqay .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xqiwkyfqay .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xqiwkyfqay .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xqiwkyfqay .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xqiwkyfqay .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xqiwkyfqay .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xqiwkyfqay .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xqiwkyfqay .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xqiwkyfqay .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xqiwkyfqay .gt_spanner_row {
  border-bottom-style: hidden;
}

#xqiwkyfqay .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#xqiwkyfqay .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xqiwkyfqay .gt_from_md > :first-child {
  margin-top: 0;
}

#xqiwkyfqay .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xqiwkyfqay .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xqiwkyfqay .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#xqiwkyfqay .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#xqiwkyfqay .gt_row_group_first td {
  border-top-width: 2px;
}

#xqiwkyfqay .gt_row_group_first th {
  border-top-width: 2px;
}

#xqiwkyfqay .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqiwkyfqay .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#xqiwkyfqay .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#xqiwkyfqay .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xqiwkyfqay .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqiwkyfqay .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xqiwkyfqay .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#xqiwkyfqay .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xqiwkyfqay .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xqiwkyfqay .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xqiwkyfqay .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqiwkyfqay .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xqiwkyfqay .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqiwkyfqay .gt_left {
  text-align: left;
}

#xqiwkyfqay .gt_center {
  text-align: center;
}

#xqiwkyfqay .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xqiwkyfqay .gt_font_normal {
  font-weight: normal;
}

#xqiwkyfqay .gt_font_bold {
  font-weight: bold;
}

#xqiwkyfqay .gt_font_italic {
  font-style: italic;
}

#xqiwkyfqay .gt_super {
  font-size: 65%;
}

#xqiwkyfqay .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#xqiwkyfqay .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#xqiwkyfqay .gt_indent_1 {
  text-indent: 5px;
}

#xqiwkyfqay .gt_indent_2 {
  text-indent: 10px;
}

#xqiwkyfqay .gt_indent_3 {
  text-indent: 15px;
}

#xqiwkyfqay .gt_indent_4 {
  text-indent: 20px;
}

#xqiwkyfqay .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="name">name</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="agemonths">agemonths</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="timeofday">timeofday</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="visibility">visibility</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="taken">taken</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="name" class="gt_row gt_left">Lauren</td>
<td headers="agemonths" class="gt_row gt_right">60</td>
<td headers="timeofday" class="gt_row gt_left">pm</td>
<td headers="visibility" class="gt_row gt_left">visible</td>
<td headers="taken" class="gt_row gt_left">taken</td>
</tr>
<tr>
<td headers="name" class="gt_row gt_left">Taraleah</td>
<td headers="agemonths" class="gt_row gt_right">100</td>
<td headers="timeofday" class="gt_row gt_left">pm</td>
<td headers="visibility" class="gt_row gt_left">visible</td>
<td headers="taken" class="gt_row gt_left">waited</td>
</tr>
<tr>
<td headers="name" class="gt_row gt_left">Connor</td>
<td headers="agemonths" class="gt_row gt_right">109</td>
<td headers="timeofday" class="gt_row gt_left">pm</td>
<td headers="visibility" class="gt_row gt_left">visible</td>
<td headers="taken" class="gt_row gt_left">waited</td>
</tr>
<tr>
<td headers="name" class="gt_row gt_left">Siengthong</td>
<td headers="agemonths" class="gt_row gt_right">61</td>
<td headers="timeofday" class="gt_row gt_left">pm</td>
<td headers="visibility" class="gt_row gt_left">hidden</td>
<td headers="taken" class="gt_row gt_left">waited</td>
</tr>
<tr>
<td headers="name" class="gt_row gt_left">Naseem</td>
<td headers="agemonths" class="gt_row gt_right">90</td>
<td headers="timeofday" class="gt_row gt_left">pm</td>
<td headers="visibility" class="gt_row gt_left">hidden</td>
<td headers="taken" class="gt_row gt_left">waited</td>
</tr>
<tr>
<td headers="name" class="gt_row gt_left">Martin</td>
<td headers="agemonths" class="gt_row gt_right">636</td>
<td headers="timeofday" class="gt_row gt_left">am</td>
<td headers="visibility" class="gt_row gt_left">hidden</td>
<td headers="taken" class="gt_row gt_left">taken</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<section id="setup" class="level3"><h3 class="anchored" data-anchor-id="setup">Setup</h3>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the mallow2 dataset into R, assigning it to an object named <code>marshmallow</code>
</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://personality-project.org/r/psych/">psych</a></span><span class="op">)</span> </span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://strengejacke.github.io/sjPlot/">sjPlot</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co">#read in data</span></span>
<span><span class="va">marshmallow</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/mallow2.csv"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="analysis-code" class="level3"><h3 class="anchored" data-anchor-id="analysis-code">Analysis Code</h3>
<p>Try to answer the research question above without referring to the provided analysis code below, and then check how your script matches up - is there anything you missed or done differently? If so, discuss the differences with a tutor - there are lots of ways to code to the same solution!</p>
<div class="optional-begin">
<span id="opt-start-3" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-3', 'opt-start-3')"> <span class="olab">Provided Analysis Code</span></span>
</div>
<div id="opt-body-3" class="optional-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">######Step 1 ######</span></span>
<span><span class="co">## TASKS: read in the data, then check, clean, describe, and visualise it.</span></span>
<span></span>
<span></span>
<span><span class="co">############## CHECK ###################</span></span>
<span></span>
<span><span class="co">#check coding of variables - are they coded as they should be?</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">marshmallow</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [304 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ name      : chr [1:304] "Lauren" "Taraleah" "Connor" "Siengthong" ...
 $ agemonths : num [1:304] 60 100 109 61 90 636 115 70 105 114 ...
 $ timeofday : chr [1:304] "pm" "pm" "pm" "pm" ...
 $ visibility: chr [1:304] "visible" "visible" "visible" "hidden" ...
 $ taken     : chr [1:304] "taken" "waited" "waited" "waited" ...
 - attr(*, "spec")=
  .. cols(
  ..   name = col_character(),
  ..   agemonths = col_double(),
  ..   timeofday = col_character(),
  ..   visibility = col_character(),
  ..   taken = col_character()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">marshmallow</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  name       agemonths timeofday visibility taken 
  &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt; 
1 Lauren            60 pm        visible    taken 
2 Taraleah         100 pm        visible    waited
3 Connor           109 pm        visible    waited
4 Siengthong        61 pm        hidden     waited
5 Naseem            90 pm        hidden     waited
6 Martin           636 am        hidden     taken </code></pre>
</div>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#time of day, visibility, and taken all currently coded as character variables when should be factors, need to fix this.</span></span>
<span><span class="co"># age also in months - likely more useful to have in years given age included up to 10 years old.</span></span>
<span></span>
<span></span>
<span><span class="co">### check range of values, NAs, etc. for each variable </span></span>
<span></span>
<span><span class="co"># age - should range 36-120 months</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.html">describe</a></span><span class="op">(</span><span class="va">marshmallow</span><span class="op">$</span><span class="va">agemonths</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   vars   n  mean    sd median trimmed   mad min max range skew kurtosis   se
X1    1 304 81.47 43.06     79   79.18 29.65  36 636   600 8.24    96.98 2.47</code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># ISSUE - we have values WAY above what should be included from the sample</span></span>
<span></span>
<span><span class="co">#visibility - should either be hidden or visible, with same number of ppts in each condition</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">marshmallow</span><span class="op">$</span><span class="va">visibility</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 hidden visible 
    152     152 </code></pre>
</div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># All good</span></span>
<span></span>
<span><span class="co">#time of day - should either be am or pm</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">marshmallow</span><span class="op">$</span><span class="va">timeofday</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
5 pm   am noon   pm 
   1  145    1  157 </code></pre>
</div>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># ISSUE - we have one mis-coded as “5 pm”, which I’m guessing should just be “pm”. And we have one at “noon”. There’s no way of knowing whether that was morning or afternoon, so safest option is to just remove</span></span>
<span></span>
<span><span class="co">#taken - shold either be taken or waited</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">marshmallow</span><span class="op">$</span><span class="va">taken</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 taken waited 
   136    168 </code></pre>
</div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># All good</span></span>
<span></span>
<span><span class="co">############## CLEAN ###################</span></span>
<span><span class="co"># We can do all cleaning in one long command.</span></span>
<span><span class="co"># First create age (in years) variable</span></span>
<span><span class="co"># Second fix time of day - make factor and specify correct levels</span></span>
<span><span class="co"># Third make visibility a factor and specify levels</span></span>
<span><span class="co"># Fourth make taken a factor and specify levels</span></span>
<span><span class="co"># Lastly we want to remove anyone over 120 months (i.e., 10 years) and those with NA values for time of day (i.e., the value of noon)</span></span>
<span></span>
<span><span class="va">marshmallow</span> <span class="op">&lt;-</span> <span class="va">marshmallow</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>      age <span class="op">=</span> <span class="va">agemonths</span><span class="op">/</span><span class="fl">12</span>,</span>
<span>      timeofday <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">timeofday</span>, </span>
<span>                         levels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"am"</span>,<span class="st">"pm"</span>,<span class="st">"5 pm"</span><span class="op">)</span>, <span class="co"># possible levels</span></span>
<span>                         labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"am"</span>,<span class="st">"pm"</span>,<span class="st">"pm"</span><span class="op">)</span><span class="op">)</span>, <span class="co"># make the levels these</span></span>
<span>      visibility <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">visibility</span>, </span>
<span>                          levels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"visible"</span>,<span class="st">"hidden"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>      taken <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">taken</span>, </span>
<span>                     levels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"waited"</span>,<span class="st">"taken"</span><span class="op">)</span><span class="op">)</span></span>
<span>      <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">agemonths</span> <span class="op">&lt;=</span> <span class="fl">120</span>, <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">timeofday</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#check cleaning has worked:</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.html">describe</a></span><span class="op">(</span><span class="va">marshmallow</span><span class="op">$</span><span class="va">agemonths</span><span class="op">)</span> <span class="co">#min over 36, and max 120 - all good</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   vars   n  mean    sd median trimmed   mad min max range  skew kurtosis   se
X1    1 301 78.73 22.44     79   79.07 28.17  39 120    81 -0.06    -1.19 1.29</code></pre>
</div>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.html">describe</a></span><span class="op">(</span><span class="va">marshmallow</span><span class="op">$</span><span class="va">age</span><span class="op">)</span> <span class="co">#min over 3 yo, and max 10 yo - all good</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   vars   n mean   sd median trimmed  mad  min max range  skew kurtosis   se
X1    1 301 6.56 1.87   6.58    6.59 2.35 3.25  10  6.75 -0.06    -1.19 0.11</code></pre>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">marshmallow</span><span class="op">$</span><span class="va">timeofday</span><span class="op">)</span> <span class="co">#now only am or pm as should be </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 am  pm 
144 157 </code></pre>
</div>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">############## DESCRIBE ###################</span></span>
<span></span>
<span><span class="co">#create descriptives table</span></span>
<span><span class="va">descript</span> <span class="op">&lt;-</span> <span class="va">marshmallow</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">visibility</span>, <span class="va">timeofday</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>   <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>       M_Age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span>,</span>
<span>       SD_Age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span>,</span>
<span>       percent_pm <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">timeofday</span><span class="op">==</span><span class="st">"pm"</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">*</span><span class="fl">100</span>,</span>
<span>       percent_taken <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">taken</span><span class="op">==</span><span class="st">"taken"</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">*</span><span class="fl">100</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span>caption <span class="op">=</span> <span class="st">"Descriptive Statistics"</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">descript</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Descriptive Statistics</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">visibility</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">timeofday</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">M_Age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD_Age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">percent_pm</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">percent_taken</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">visible</td>
<td style="text-align: left;">am</td>
<td style="text-align: right;">7.17</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">52.70</td>
</tr>
<tr class="even">
<td style="text-align: left;">visible</td>
<td style="text-align: left;">pm</td>
<td style="text-align: right;">6.04</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">59.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hidden</td>
<td style="text-align: left;">am</td>
<td style="text-align: right;">7.47</td>
<td style="text-align: right;">1.72</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">28.57</td>
</tr>
<tr class="even">
<td style="text-align: left;">hidden</td>
<td style="text-align: left;">pm</td>
<td style="text-align: right;">5.71</td>
<td style="text-align: right;">1.71</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">37.04</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">############## VISUALISE ###################</span></span>
<span></span>
<span><span class="co">#bar plot</span></span>
<span><span class="va">mallow_plt1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">marshmallow</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">taken</span><span class="op">)</span>, fill <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">taken</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Taken Marshmallow (0 = No, 1 = Yes)"</span>, fill <span class="op">=</span> <span class="st">"Marshmallow Status"</span>, y <span class="op">=</span> <span class="st">"Frequency"</span><span class="op">)</span></span>
<span><span class="va">mallow_plt1</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_09_writeup_recap_blk4LEEK_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#density plot</span></span>
<span><span class="va">mallow_plt2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">marshmallow</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, fill <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">taken</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_density.html">geom_density</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Age"</span>, fill <span class="op">=</span> <span class="st">"Marshmallow Status"</span><span class="op">)</span></span>
<span><span class="va">mallow_plt2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_09_writeup_recap_blk4LEEK_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#density plot with facets</span></span>
<span><span class="va">mallow_plt3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">marshmallow</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, fill <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">taken</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_density.html">geom_density</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_grid.html">facet_grid</a></span><span class="op">(</span><span class="va">visibility</span> <span class="op">~</span> <span class="va">timeofday</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Age"</span>, fill <span class="op">=</span> <span class="st">"Marshmallow Status"</span><span class="op">)</span></span>
<span><span class="va">mallow_plt3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_09_writeup_recap_blk4LEEK_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">######Step 2 ######</span></span>
<span><span class="co">## TASKS: run your model(s) of interest to answer your research question, and make sure that the data meet the assumptions of your chosen test</span></span>
<span></span>
<span><span class="co">############## BUILD MODEL &amp; EXAMINE OUTPUT ###################</span></span>
<span></span>
<span><span class="va">mm1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">taken</span> <span class="op">~</span> <span class="va">timeofday</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">visibility</span>, data <span class="op">=</span> <span class="va">marshmallow</span>, family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mm1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = taken ~ timeofday + age + visibility, family = binomial, 
    data = marshmallow)

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       4.40584    0.68525   6.430 1.28e-10 ***
timeofdaypm      -0.48621    0.29202  -1.665   0.0959 .  
age              -0.58448    0.08622  -6.779 1.21e-11 ***
visibilityhidden -1.19939    0.27296  -4.394 1.11e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 413.65  on 300  degrees of freedom
Residual deviance: 338.63  on 297  degrees of freedom
AIC: 346.63

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coefficients</a></span><span class="op">(</span><span class="va">mm1</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept)      timeofdaypm              age visibilityhidden 
      81.9282592        0.6149502        0.5573964        0.3013777 </code></pre>
</div>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">############## ASSUMPTIONS ###################</span></span>
<span></span>
<span><span class="co">#std deviance residuals</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">rstandard</a></span><span class="op">(</span><span class="va">mm1</span>, type <span class="op">=</span> <span class="st">"deviance"</span><span class="op">)</span>, ylab <span class="op">=</span> <span class="st">"Standardised Deviance Residuals"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_09_writeup_recap_blk4LEEK_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#cooks D</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">cooks.distance</a></span><span class="op">(</span><span class="va">mm1</span><span class="op">)</span>, ylab <span class="op">=</span> <span class="st">"Cook's Distance"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_09_writeup_recap_blk4LEEK_files/figure-html/unnamed-chunk-4-5.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">############## MODEL FIT ###################</span></span>
<span></span>
<span><span class="co">#compare to null - conduct model comparison</span></span>
<span><span class="co">#fit null</span></span>
<span><span class="va">mm0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">taken</span> <span class="op">~</span> <span class="fl">1</span>, family <span class="op">=</span> <span class="st">"binomial"</span>, data <span class="op">=</span> <span class="va">marshmallow</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#compare models - models are nested</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mm0</span>, <span class="va">mm1</span>, test <span class="op">=</span> <span class="st">"Chisq"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: taken ~ 1
Model 2: taken ~ timeofday + age + visibility
  Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
1       300     413.65                          
2       297     338.63  3   75.021 3.586e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">AIC</a></span><span class="op">(</span><span class="va">mm0</span>, <span class="va">mm1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    df      AIC
mm0  1 415.6494
mm1  4 346.6284</code></pre>
</div>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">BIC</a></span><span class="op">(</span><span class="va">mm0</span>, <span class="va">mm1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    df      BIC
mm0  1 419.3565
mm1  4 361.4569</code></pre>
</div>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">############## PLOT / TABLE MODEL RESULTS ###################</span></span>
<span></span>
<span><span class="co">#results in formatted table</span></span>
<span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">mm1</span>,</span>
<span>          dv.labels <span class="op">=</span> <span class="st">"Marshmallow Taken"</span>,</span>
<span>          pred.labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Intercept"</span>, <span class="st">"Time of Day - PM"</span>, <span class="st">"Age (in years)"</span>, <span class="st">"Visibility - Hidden"</span><span class="op">)</span>,</span>
<span>          title <span class="op">=</span> <span class="st">"Regression Table for Marshmallow Model"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Regression Table for Marshmallow Model</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Marshmallow Taken</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Odds Ratios</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Intercept</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">81.93</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">22.47&nbsp;–&nbsp;332.30</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Time of Day - PM</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.61</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.34&nbsp;–&nbsp;1.08</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.096</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Age (in years)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.56</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.47&nbsp;–&nbsp;0.66</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Visibility - Hidden</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.30</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.17&nbsp;–&nbsp;0.51</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">301</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> Tjur</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.233</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section><section id="the-3-act-structure-analysis-strategy-results-discussion" class="level3"><h3 class="anchored" data-anchor-id="the-3-act-structure-analysis-strategy-results-discussion">The 3-Act Structure: Analysis Strategy, Results, &amp; Discussion</h3>
<p>We need to present our report in three clear sections - think of your sections like the 3 key parts of a play or story - we need to (1) provide some background and scene setting for the reader, (2) present our results in the context of the research question, and (3) present a resolution to our story - relate our findings back to the question we were asked and provide our answer.</p>
<section id="act-i-analysis-strategy" class="level4"><h4 class="anchored" data-anchor-id="act-i-analysis-strategy">Act I: Analysis Strategy</h4>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Attempt to draft a discussion section based on the above research question and analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Analysis Strategy - What to Include
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Your analysis strategy will contain a number of different elements detailing plans and changes to your plan. Remember, your analysis strategy should <strong>not</strong> contain any results. You may wish to include the following sections:</p>
<ul>
<li>Very brief data and design description:
<ul>
<li>Give the reader some background on the context of your write-up. For example, you may wish to describe the data source, data collection strategy, study design, number of observational units.</li>
<li>Specify the variables of interest in relation to the research question, including their unit of measurement, the allowed range (for Likert scales), and how they are scored. If you have categorical data, you will need to specify the levels and coding of your variables, and what was specified as your reference level and the justification for this choice.</li>
</ul>
</li>
<li>Data management:
<ul>
<li>Describe any data cleaning and/or recoding.</li>
<li>Are there any observations that have been excluded based on pre-defined criteria? How/why, and how many?</li>
<li>Describe any transformations performed to aid your interpretation (i.e., mean centering, standardisation, etc.)</li>
</ul>
</li>
<li>Model specification:
<ul>
<li>Clearly state your hypotheses and specify your chosen significance level.</li>
<li>What type of statistical analysis do you plan to use to answer the research question? (e.g., simple linear regression, multiple linear regression, binary logistic regression, etc.)</li>
<li>In some cases, you may wish to include some visualisations and descriptive tables to motivate your model specification.</li>
<li>Specify the model(s) to be fitted to answer your given research question and analysis structure. Clearly specify the response and explanatory variables included in your model(s). This includes specifying the type of coding scheme applied if using categorical data.</li>
<li>Specify the assumption and diagnostic checks that you will conduct. Specify what plots you will use, and how you will evaluate these.</li>
</ul>
</li>
</ul>
<p>As noted and encouraged throughout the course, one of the main benefits of using RMarkdown is the ability to include inline R code in your document. Try to incorporate this in your write up so you can automatically pull the specified values from your code. If you need a reminder on how to do this, see <a href="https://uoepsy.github.io//rmd-bootcamp/">Lesson 4 of the Rmd Bootcamp</a>.</p>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-4" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-4', 'opt-start-4')"> <span class="olab">Example Write-Up of Analysis Strategy Section</span></span>
</div>
<div id="opt-body-4" class="optional-body" style="display: none;">
<p>The <code>mallow2</code> dataset contained information on 304 participants who took part in a study concerning delayed gratification - where children were presented with a single marshmallow, but were told that if they could leave it for 10 minutes, they would be rewarded with two marshmallows (scored dichotomously as taken or waited). The children participated in either the morning (am) or afternoon (pm), and the marshmallow was either visible or hidden for the 10 minute duration of the experiment. The age of each child was also recorded. All participant data was complete (no missing values), but two participants were excluded due to their age being outside of the range included in the study, and so the final sample size was 302.</p>
<p>To investigate whether the probability of taking the marshmallow changed as a function of time of day (am/pm), age, and marshmallow visibility (visible/hidden), a binary logistic regression model was used. Effects were considered statistically significant at <span class="math inline">\(\alpha = .05\)</span>. The following model specification was used:</p>
<p><span class="math display">\[
\begin{aligned}
M_1 &amp;: \qquad \log \left( \frac{p}{1 - p}\right) = \beta_0 + \beta_1 \cdot \text{Time of day}_{PM} +  \beta_2 \cdot \text{Age} + \beta_3 \cdot \text{Visibility}_{Hidden}
\end{aligned}
\]</span></p>
<p><span class="math display">\[
\begin{aligned}
\text{where}~{p}~ &amp;=~ \text{probability of taking the marshmallow}
\end{aligned}
\]</span></p>
<p>To address the research question of whether the probability of taking the marshmallow changed as a function of time of day, age, and marshmallow visibility, this formally corresponded to:</p>
<p><span class="math display">\[
H_0: \text{All} ~~ \beta_j ~~ = ~~ 0 ~~ (for ~~ j ~~ = 1, 2, 3)
\]</span></p>
<p><span class="math display">\[
H_1: \text{At least one} ~~ \beta_j ~~ \neq ~~ 0 ~~ (for ~~ j ~~ = 1, 2, 3)
\]</span></p>
<p>To assess model fit, we visually assessed the standardized deviance residuals and Cook’s Distance. We expected the former to identify outliers (or extreme values), and we expected residuals to fall within the range of -2 to 2. We used the latter to check for influential observations, and visually assessed if any of our 302 observations had a Cook’s distance &gt; 0.5 (moderately influential) or &gt; 1 (highly influential).</p>
</div>
<p class="optional-end">
</p>
</section><section id="act-ii-results" class="level4"><h4 class="anchored" data-anchor-id="act-ii-results">Act II: Results</h4>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Attempt to draft a results section based on your detailed analysis strategy and the analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Results - What To Include
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The results section should follow from your analysis strategy. This is where you would present the evidence and results that will be used to answer the research questions and can support your conclusions. Make sure that you address all aspects of the approach you outlined in the analysis strategy (including the evaluation of assumptions and diagnostics).</p>
<p>In this section, it is useful to include tables and plots to clearly present your findings to your reader. It is important, however, to carefully select what is the key information that should be presented. You don’t want to overload the reader with unnecessary or duplicate information, and you also want to save space in case there is a page limit. Make use of figures with multiple panels where you can.</p>
<p>As a broad guideline, you want to start with the results of any exploratory data analysis, presenting tables of summary statistics and exploratory plots. You may also want to visualise associations between/among variables and report covariances or correlations. Then, you should move on to the results from your model.</p>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-5" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-5', 'opt-start-5')"> <span class="olab">Example Write-Up of Results Section</span></span>
</div>
<div id="opt-body-5" class="optional-body" style="display: none;">
<p>Descriptive statistics are displayed in <a href="#tbl-descript">Table&nbsp;1</a>.</p>
<div class="cell" data-layout-align="center" data-caption="Descriptives Table">
<div class="cell-output-display">
<div id="tbl-descript" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;1: Descriptive Statistics</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">visibility</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">timeofday</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">M_Age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD_Age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">percent_taken</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">visible</td>
<td style="text-align: left;">am</td>
<td style="text-align: right;">7.17</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: right;">52.70</td>
</tr>
<tr class="even">
<td style="text-align: left;">visible</td>
<td style="text-align: left;">pm</td>
<td style="text-align: right;">6.04</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">59.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hidden</td>
<td style="text-align: left;">am</td>
<td style="text-align: right;">7.47</td>
<td style="text-align: right;">1.72</td>
<td style="text-align: right;">28.57</td>
</tr>
<tr class="even">
<td style="text-align: left;">hidden</td>
<td style="text-align: left;">pm</td>
<td style="text-align: right;">5.71</td>
<td style="text-align: right;">1.71</td>
<td style="text-align: right;">37.04</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>It appeared that when the marshmallow was visible, a greater percentage of children took it; and the percentage of children who engaged in delayed gratification was higher in the morning sessions (see <a href="#fig-taken-plot">Figure&nbsp;1</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-taken-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_09_writeup_recap_blk4LEEK_files/figure-html/fig-taken-plot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Association between Delayed Gratification, Age, Visibility of Marshmallow, and Time of Day</figcaption></figure>
</div>
</div>
</div>
<p>A binary logistic regression model was fitted to determine whether the probability of taking the marshmallow changed as a function of time of day, age, and marshmallow visibility.</p>
<p>Our model did not raise any concerns regarding fit. Though there appeared to be a few residuals with a value slightly larger than 2 in absolute value (see left-hand plot in <a href="#fig-assumpt">Figure&nbsp;2</a>), they were not influential points (see right-hand plot in <a href="#fig-assumpt">Figure&nbsp;2</a>), since none of our observations had a Cook’s distance value &gt; 0.5.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-assumpt" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_09_writeup_recap_blk4LEEK_files/figure-html/fig-assumpt-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Model Fit Plots</figcaption></figure>
</div>
</div>
</div>
<p>Age and visibility were significant predictors of delayed gratification (see <a href="#tbl-res">Table&nbsp;2</a>). For every year increase in age, the odds of taking the marshmallow decreased by a factor of 0.56 (<span class="math inline">\(95\%\, CI\, [0.47, 0.66])\)</span>. When the marshmallow was hidden (as opposed to visible), the odds of taking the marshmallow decreased by a factor of 0.3 (<span class="math inline">\(95\%\, CI\, [0.17, 0.51])\)</span>. Thus, we rejected the null hypothesis.</p>
<div class="cell" data-layout-align="center" data-caption="Model Results">
<div class="cell-output-display">
<div id="tbl-res" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;2: Regression Table for Marshmallow Model</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Marshmallow Taken</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Odds Ratios</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Intercept</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">81.93</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">22.47&nbsp;–&nbsp;332.30</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Time of Day - PM</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.61</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.34&nbsp;–&nbsp;1.08</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.096</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Age (in years)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.56</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.47&nbsp;–&nbsp;0.66</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Visibility - Hidden</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.30</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.17&nbsp;–&nbsp;0.51</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">301</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> Tjur</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.233</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</div>
<p class="optional-end">
</p>
</section><section id="act-iii-discussion" class="level4"><h4 class="anchored" data-anchor-id="act-iii-discussion">Act III: Discussion</h4>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Attempt to draft a discussion section based on your results and the analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion - What To Include
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In the discussion section, you should summarise the key findings from the results section and provide the reader with a few take-home sentences drawing the analysis together and relating it back to the original question.</p>
<p>The discussion should be relatively brief, and should not include any statistical analysis - instead think of the discussion as a conclusion, providing an answer to the research question(s).</p>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-6" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-6', 'opt-start-6')"> <span class="olab">Example Write-Up of Discussion Section</span></span>
</div>
<div id="opt-body-6" class="optional-body" style="display: none;">
<p>The probability of children delaying gratification did change as a function of age and marshmallow visibility (but not time of day). In summary, older age and conditions where the marshmallow was hidden appeared to be associated with greater odds of successfully delaying gratification.</p>
</div>
<p class="optional-end">
</p>
</section></section></section></section><section id="section-b-weeks-6-9-recap" class="level1"><h1>Section B: Weeks 6-9 Recap</h1>
<p>In the second part of the lab, there is no new content - the purpose of the recap section is for you to revisit and revise the concepts you have learned over the last 4 weeks.</p>
<div class="red">
<p>Before you expand each of the boxes below, think about how comfortable you feel with each concept.</p>
</div>
<div class="optional-begin">
<span id="opt-start-7" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-7', 'opt-start-7')"> <span class="olab">Errors and Power in Hypothesis Testing</span></span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<p>When testing a hypothesis, we reach one of the following two decisions:</p>
<ul>
<li>failing to reject <span class="math inline">\(H_0\)</span> as the evidence against it is not sufficient<br>
</li>
<li>rejecting <span class="math inline">\(H_0\)</span> as we have enough evidence against it</li>
</ul>
<p>However, irrespective of our decision, the underlying truth can either be that</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span> is actually false<br>
</li>
<li>
<span class="math inline">\(H_0\)</span> is actually true</li>
</ul>
<p>Hence, we have four possible outcomes following a hypothesis test:</p>
<ol type="1">
<li>We failed to reject <span class="math inline">\(H_0\)</span> when it was true, meaning we made a <strong>Correct</strong> decision<br>
</li>
<li>We rejected <span class="math inline">\(H_0\)</span> when it was false, meaning we made a <strong>Correct</strong> decision<br>
</li>
<li>We rejected <span class="math inline">\(H_0\)</span> when it was true, committing a <strong>Type I error</strong><br>
</li>
<li>We failed to reject <span class="math inline">\(H_0\)</span> when it was false, committing a <strong>Type II error</strong>
</li>
</ol>
<p>In the first two cases we are correct, while in the latter two we committed an error.</p>
<p>When we reject the null hypothesis, we never know if we were correct or committed a Type I error, however we can control the chance of us committing a Type I error.</p>
<p>Similarly, when we fail to reject the null hypothesis, we never know if we are correct or we committed a Type II error, but we can also control the chance of us committing a Type II error.</p>
<p>The following table summarises the two types of errors that we can commit:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/ht-errors-table-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>A Type I error corresponds to a false discovery, while a type II error corresponds to a failed discovery/missed opportunity.</p>
<p>Each error has a corresponding probability:</p>
<ul>
<li>The probability of incorrectly rejecting a true null hypothesis is <span class="math inline">\(\alpha = P(\text{Type I error})\)</span><br>
</li>
<li>The probability of incorrectly not rejecting a false null hypothesis is <span class="math inline">\(\beta = P(\text{Type II error})\)</span>
</li>
</ul>
<p>A related quantity is <strong>Power</strong>, which is defined as the probability of correctly rejecting a false null hypothesis.</p>
<div class="yellow">
<p><strong>Power</strong></p>
<p>Power is the probability of rejecting a false null hypothesis. That is, it is the probability that we will find an effect when it is in fact present. <span class="math display">\[
\text{Power} = 1 - P(\text{Type II error}) = 1 - \beta
\]</span></p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 6 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_06_power.html">S2 Week 6 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-8" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-8', 'opt-start-8')"> <span class="olab">Factors Affecting Power</span></span>
</div>
<div id="opt-body-8" class="optional-body" style="display: none;">
<p>In practice, it is ideal for studies to have high power while using a relatively small significance level such as .05 or .01. For a fixed <span class="math inline">\(\alpha\)</span>, the power increases in the same cases that P(Type II error) decreases, namely as the sample size increases and as the parameter value moves farther into the H values away from the H0 value.</p>
<p>The <strong>power</strong> of a test is affected by the following factors:</p>
<ul>
<li>
<strong>sample size.</strong> Power increases as the sample size increases.</li>
<li>
<strong>effect size.</strong> Power increases as the parameter value moves farther into the <span class="math inline">\(H_1\)</span> values away from the <span class="math inline">\(H_0\)</span> value.</li>
<li>
<strong>significance level.</strong> Power increases as the significance level increases.</li>
</ul>
<p>Out of these, increasing the significance level <span class="math inline">\(\alpha\)</span> is never an acceptable way to increase power as it leads to more Type I errors, i.e.&nbsp;a higher chance of incorrectly rejecting a true null hypothesis (false discoveries).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 6 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_06_power.html">S2 Week 6 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-9" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-9', 'opt-start-9')"> <span class="olab">Effect Size</span></span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p>Effect size refers to the “detectability” of your alternative hypothesis. In simple terms, it compares the distance between the alternative and the null hypothesis to the variability in your data.</p>
<p>For simplicity consider comparing a mean: <span class="math inline">\(H_0: \mu = 0\)</span> vs <span class="math inline">\(H_1: \mu \neq 0\)</span>. If the sample mean were really 0.1 and the null hypothesis is 0, the distance is 0.1 - 0 = 0.1.</p>
<p>Now, a distance of 0.1 has a different weight in the following two scenarios.</p>
<p><strong>Scenario 1.</strong> Data vary between -1 and 1.</p>
<p><strong>Scenario 2.</strong> Data vary between -1000 and 1000.</p>
<p>Clearly, in Scenario 1 a distance of of 0.1 is a big difference. Conversely, in Scenario 2 a distance of 0.1 is not an interesting difference, it’s negligible compared to the magnitude of the data.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="2_09_writeup_recap_blk4LEEK_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 6 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_06_power.html">S2 Week 6 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-10" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-10', 'opt-start-10')"> <span class="olab">The pwr Package</span></span>
</div>
<div id="opt-body-10" class="optional-body" style="display: none;">
<p>You will perform power analysis using the <code>pwr</code> package. To install it, run <code>install.packages("pwr")</code> in your console, then run <code><a href="https://github.com/heliosdrm/pwr">library(pwr)</a></code> in your RMarkdown file.</p>
<p>The following functions are available.</p>
<table class="table">
<thead><tr class="header">
<th style="text-align: left;">Function</th>
<th style="text-align: left;">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>pwr.2p.test</code></td>
<td style="text-align: left;">Two proportions (equal n)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>pwr.2p2n.test</code></td>
<td style="text-align: left;">Two proportions (unequal n)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>pwr.anova.test</code></td>
<td style="text-align: left;">Balanced one-way ANOVA</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>pwr.chisq.test</code></td>
<td style="text-align: left;">Chi-square test</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>pwr.f2.test</code></td>
<td style="text-align: left;">General linear model</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>pwr.p.test</code></td>
<td style="text-align: left;">Proportion (one sample)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>pwr.r.test</code></td>
<td style="text-align: left;">Correlation</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>pwr.t.test</code></td>
<td style="text-align: left;">t-tests (one sample, two samples, paired)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>pwr.t2n.test</code></td>
<td style="text-align: left;">t-test (two samples with unequal n)</td>
</tr>
</tbody>
</table>
<p>For each function, you can specify three of four arguments (sample size, alpha, effect size, power) and the fourth argument will be calculated for you.</p>
<p>Of the four quantities, effect size is often the most difficult to specify. Calculating effect size typically requires some experience with the measures involved and knowledge of past research.</p>
<p>Typically, specifying effect size requires you to read published literature or past papers on your research topic, to see what effect sizes were found and what significant results were reported. Other times, this might come from previous collected data or subject-knowledge from your colleagues.</p>
<p>But what can you do if you have no clue what effect size to expect in a given study? Cohen (1988) provided guidelines for what a small, medium, or large effect typically is in the behavioral sciences.</p>
<table class="table">
<thead><tr class="header">
<th style="text-align: left;">Type of test</th>
<th style="text-align: center;">Small</th>
<th style="text-align: center;">Medium</th>
<th style="text-align: center;">Large</th>
<th style="text-align: center;"></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">t-test</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">0.80</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">ANOVA</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.40</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linear regression</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">0.15</td>
<td style="text-align: center;">0.35</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 6 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_06_power.html">S2 Week 6 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-11" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-11', 'opt-start-11')"> <span class="olab">Power for t-tests</span></span>
</div>
<div id="opt-body-11" class="optional-body" style="display: none;">
<p>We compare the mean of a response variable between two groups using a t-test. For example, if you are comparing the mean response between two groups, say treatment and control, the null and alternative hypotheses are: <span class="math display">\[
H_0 : \mu_t - \mu_c = 0
\]</span></p>
<p><span class="math display">\[
H_1 : \mu_t - \mu_c \neq 0  
\]</span></p>
<p>The effect size in this case is Cohen’s <span class="math inline">\(D\)</span>: <span class="math display">\[
D = \frac{(\bar x_t - \bar x_c) - 0}{s_p}  
\]</span> where</p>
<ul>
<li>
<span class="math inline">\(\bar x_t\)</span> and <span class="math inline">\(\bar x_c\)</span> are the sample means in the treatment and control groups, respectively</li>
<li>
<span class="math inline">\(s_p\)</span> is the “pooled” standard deviation</li>
</ul>
<p>Cohen’s <span class="math inline">\(D\)</span> measures the distance between (a) the observed difference in means from (b) the hypothesised value 0, and compares this to the variability in the data.</p>
<div class="blue">
<p>In <strong>R</strong> we use the function</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pwr.t.test</span><span class="op">(</span>n <span class="op">=</span> , d <span class="op">=</span> , sig.level <span class="op">=</span> , power <span class="op">=</span> , type <span class="op">=</span> , alternative <span class="op">=</span> <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>where</p>
<ul>
<li>
<code>n</code> = the sample size</li>
<li>
<code>d</code> = the effect size</li>
<li>
<code>sig.level</code> = the significance level <span class="math inline">\(\alpha\)</span> (the default is 0.05)</li>
<li>
<code>power</code> = the power level.</li>
<li>
<code>type</code> = the type of t-test to perform: either a two-sample t-test (“two.sample”), a one-sample t-test (“one.sample”), or a dependent sample t-test (“paired”). A two-sample test is the default.</li>
<li>
<code>alternative</code> = whether the alternative hypothesis is two-sided (“two.sided”) or one-sided (“less” or “greater”). A two-sided test is the default.</li>
</ul>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 6 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_06_power.html">S2 Week 6 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-12" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-12', 'opt-start-12')"> <span class="olab">Power for Linear Regression</span></span>
</div>
<div id="opt-body-12" class="optional-body" style="display: none;">
<p>In linear regression, the relevant function in <strong>R</strong> is:</p>
<div class="blue">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/heliosdrm/pwr">pwr</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.f2.test.html">pwr.f2.test</a></span><span class="op">(</span>u <span class="op">=</span> , v <span class="op">=</span> , f2 <span class="op">=</span> , sig.level <span class="op">=</span> , power <span class="op">=</span> <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>where - <code>u</code> = numerator degrees of freedom - <code>v</code> = denominator degrees of freedom - <code>f2</code> = effect size</p>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Goal 1. Test on all slopes</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Goal 2. Test on a subset of slopes</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Here you have one model,</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \dots + \beta_k x_k + \epsilon  
\]</span></p>
<p>and you wish to find the minimum sample size required to answer the following test of hypothesis with a given power:</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: \beta_1 = \beta_2 = \dots = \beta_k = 0 \\  
H_1 &amp;: \text{At least one } \beta_i \neq 0 \\  
\end{aligned}
\]</span></p>
<p>The appropriate formula for the effect size is:</p>
<p><span class="math display">\[
f^2 = \frac{R^2}{1 - R^2}  
\]</span></p>
<p>And the numerator degrees of freedom are <span class="math inline">\(\texttt u = k\)</span>, the number of predictors in the model.</p>
<p>The denominator degrees of freedom returned by the function will give you:</p>
<p><span class="math display">\[
\texttt v = n - (k + 1) = n - k - 1 \\    
\]</span></p>
<p>From which you can infer the sample size as</p>
<p><span class="math display">\[
n = \texttt v + k + 1 \\  
\]</span></p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>In this case you would have a smaller model <span class="math inline">\(m\)</span> with <span class="math inline">\(k\)</span> predictors and a larger model <span class="math inline">\(M\)</span> with <span class="math inline">\(K\)</span> predictors:</p>
<p><span class="math display">\[
\begin{aligned}
m &amp;: \quad y = \beta_0 + \beta_1 x_1 + \dots + \beta_{k} x_k + \epsilon \\  
M &amp;: \quad y = \beta_0 + \beta_1 x_1 + \dots + \beta_{k} x_k
+ \underbrace{\beta_{k + 1} x_{k+1} + \dots + \beta_{K} x_K}_{\text{extra predictors}}
+ \epsilon \\   
\end{aligned}
\]</span></p>
<p>This case is when you wish to find the minimum sample size required to answer the following test of hypothesis:</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: \beta_{k+1} = \beta_{k+2} = \dots = \beta_K = 0 \\  
H_1 &amp;: \text{At least one of the above } \beta \neq 0 \\  
\end{aligned}
\]</span></p>
<p>You need to use the R-squared from the larger model <span class="math inline">\(R^2_M\)</span> and the R-squared from the smaller model <span class="math inline">\(R^2_m\)</span>. The appropriate formula for the effect size is:</p>
<p><span class="math display">\[
f^2 = \frac{R^2_{M} - R^2_{m}}{1 - R^2_M}  
\]</span></p>
<p>Here, the numerator degrees of freedom are the extra predictors: <span class="math inline">\(\texttt u = K - k\)</span>.</p>
<p>The denominator degrees of freedom returned by the function will give you (here you use <span class="math inline">\(K\)</span> the number of all predictors in the larger model):</p>
<p><span class="math display">\[  
\text v = n - (K + 1) = n - K - 1  
\]</span></p>
<p>From which you can infer the sample size as</p>
<p><span class="math display">\[
n = \text v + K + 1  
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 6 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_06_power.html">S2 Week 6 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-13" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-13', 'opt-start-13')"> <span class="olab">Probability, Odds, Log-Odds</span></span>
</div>
<div id="opt-body-13" class="optional-body" style="display: none;">
<ul>
<li><p>The <strong>probability</strong> <span class="math inline">\(p\)</span> ranges from 0 to 1.</p></li>
<li><p>The <strong>odds</strong> <span class="math inline">\(\frac{p}{1-p}\)</span> ranges from 0 to <span class="math inline">\(\infty\)</span>.</p></li>
<li><p>The <strong>log-odds</strong> <span class="math inline">\(\log \left( \frac{p}{1-p} \right)\)</span> ranges from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>.</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the labs, we used “log” to denote log-odds. In the lectures, you will have seen this denoted as “ln”.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/glm/plo.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption class="figure-caption">Probability, Odds and Log-odds</figcaption></figure>
</div>
</div>
</div>
<p>In order to understand the connections among these concepts, lets work with an example where the <em>probability</em> of an event occurring is 0.2:</p>
<ul>
<li>Odds of event occurring:</li>
</ul>
<p><span class="math display">\[
\text{odds} = (\frac{0.2}{0.8}) = 0.25
\]</span></p>
<ul>
<li>Log-odds of the event occurring:</li>
</ul>
<p><span class="math display">\[
log(\frac{0.2}{0.8}) = -1.3863 \\ \ \\
\]</span></p>
<center>
OR
</center>
<p><span class="math display">\[
log(0.25) = -1.3863
\]</span></p>
<ul>
<li>Probability can be reconstructed as:</li>
</ul>
<span class="math display">\[
(\frac{odds}{1+odds}) = (\frac{0.25}{1+0.25}) = 0.2 \\ \ \\
\]</span>
<center>
OR
</center>
<p><span class="math display">\[
(\frac{exp(log(odds))}{1+exp(log(odds))}) = (\frac{exp(-1.3863)}{1+exp(-1.3683)}) = (\frac{0.25}{1.25}) = 0.2
\]</span></p>
<div class="blue">
<p>In <strong>R</strong>:</p>
<ul>
<li>
<p>obtain the odds</p>
<p><code>odds &lt;- 0.2 / (1 - 0.2)</code></p>
</li>
<li>
<p>obtain the log-odds for a given probability</p>
<p><code>log_odds &lt;- log(0.25)</code></p>
<p><strong>OR</strong></p>
<p><code>log_odds &lt;- qlogis(0.2)</code></p>
</li>
<li>
<p>obtain the probability from the odds</p>
<p><code>prob_O &lt;- odds / (1 + odds)</code></p>
</li>
<li>
<p>obtain the probability from the log-odds</p>
<p><code>prob_LO &lt;- exp(log_odds) / (1 + exp(log_odds))</code></p>
<p><strong>OR</strong></p>
<p><code>prob_LO &lt;- plogis(log_odds)</code></p>
</li>
</ul>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 7 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_07_glm1.html">S2 Week 7 Lab</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_08_glm2.html">S2 Week 8 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-14" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-14', 'opt-start-14')"> <span class="olab">Binary Logistic Regression</span></span>
</div>
<div id="opt-body-14" class="optional-body" style="display: none;">
<p>When a response (y) is binary coded (e.g., 0/1; failure/success; no/yes; fail/pass; unemployed/employed) we must use logistic regression. The predictors can either be continuous or categorical.</p>
<p><span class="math display">\[
{\log(\frac{p_i}{1-p_i})} = \beta_0 + \beta_1 \ x_{i1}
\]</span></p>
<div class="blue">
<p><strong>In R:</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x1</span> <span class="op">+</span> <span class="va">x2</span>, data <span class="op">=</span> <span class="va">data</span>, family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 7 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_07_glm1.html">S2 Week 7 Lab</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_08_glm2.html">S2 Week 8 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-15" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-15', 'opt-start-15')"> <span class="olab">Interpretation of Coefficients</span></span>
</div>
<div id="opt-body-15" class="optional-body" style="display: none;">
<p>To interpret the fitted coefficients, we first exponentiate the model: <span class="math display">\[
\begin{aligned}
\log \left( \frac{p_x}{1-p_x} \right) &amp;= \beta_0 + \beta_1 x \\
e^{ \log \left( \frac{p_x}{1-p_x} \right) } &amp;= e^{\beta_0 + \beta_1 x } \\
\frac{p_x}{1-p_x} &amp;= e^{\beta_0} \ e^{\beta_1 x}
\end{aligned}
\]</span></p>
<p>and recall that the probability of success divided by the probability of failure is the odds of success. <span class="math display">\[
\frac{p_x}{1-p_x} = \text{odds}
\]</span></p>
<p>Let’s apply this to an example where we are trying to determine whether the probability of having senility symptoms change as a function of Wechsler Adult Intelligence Scale (WAIS) score, where we fit the following model:</p>
<p><span class="math display">\[
\begin{aligned}
Model_{Senility}: \qquad \log \left( \frac{p}{1 - p}\right) = \beta_0 + \beta_1 \cdot \text{WAIS Score} + \epsilon
\end{aligned}
\]</span></p>
<p><strong>Intercept</strong></p>
<p><span class="math display">\[
\text{If }x = 0, \qquad \frac{p_0}{1-p_0} = e^{\beta_0} \ e^{\beta_1 x} = e^{\beta_0}
\]</span></p>
<p>That is, <span class="math inline">\(e^{\beta_0}\)</span> represents the odds of having symptoms of senility for individuals with a WAIS score of 0.</p>
<p>In other words, for those with a WAIS score of 0, the probability of having senility symptoms is <span class="math inline">\(e^{\beta_0}\)</span> times that of non having them.</p>
<p><strong>Slope</strong></p>
<p><span class="math display">\[
\text{If }x = 1, \qquad \frac{p_1}{1-p_1} = e^{\beta_0} \ e^{\beta_1 x} = e^{\beta_0} \ e^{\beta_1}
\]</span></p>
<p>Now consider taking the ratio of the odds of senility symptoms when <span class="math inline">\(x=1\)</span> to the odds of senility symptoms when <span class="math inline">\(x = 0\)</span>:</p>
<p><span class="math display">\[
\frac{\text{odds}_{x=1}}{\text{odds}_{x=0}} = \frac{p_1 / (1 - p_1)}{p_0 / (1 - p_0)}
= \frac{e^{\beta_0} \ e^{\beta_1}}{e^{\beta_0}}
= e^{\beta_1}
\]</span></p>
<p>So, <span class="math inline">\(e^{\beta_1}\)</span> represents the odds ratio for a 1 unit increase in WAIS score.</p>
<p>There are various ways of describing odds ratios:</p>
<ul>
<li>“for a 1 unit increase in <span class="math inline">\(x\)</span> the odds of <span class="math inline">\(y\)</span> change by <em>a ratio</em> of <code>exp(b)</code>”<br>
</li>
<li>“for a 1 unit increase in <span class="math inline">\(x\)</span> the odds of <span class="math inline">\(y\)</span> are multiplied by <code>exp(b)</code>”<br>
</li>
<li>“for a 1 unit increase in <span class="math inline">\(x\)</span> there are <code>exp(b)</code> increased/decreased odds of <span class="math inline">\(y\)</span>”</li>
</ul>
<p>Instead of thinking of a coefficient of 0 as indicating “no association”, in odds ratios this when the OR = 1.</p>
<ul>
<li>
<strong>OR = 1</strong> : equal odds (<span class="math inline">\(1 \times odds = odds \text{ don't change}\)</span>)<br>
</li>
<li>
<strong>OR &lt; 1</strong> : decreased odds (<span class="math inline">\(0.5 \times odds = odds \text{ are halved}\)</span>)<br>
</li>
<li>
<strong>OR &gt; 1</strong> : increased odds (<span class="math inline">\(2 \times odds = odds \text{ are doubled}\)</span>)</li>
</ul>
<p>So in our example, we could interpret by saying that for a one-unit increase in WAIS score the odds of senility symptoms increase by a factor of <span class="math inline">\(e^{\beta_1}\)</span>.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
OR are not “exp(b) times more likely”
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Often you will hear people interpreting odds ratios as “<span class="math inline">\(y\)</span> is <code>exp(b)</code> times as likely”.<br>
Although it is true that increased odds is an increased likelihood of <span class="math inline">\(y\)</span> occurring, double the odds does not mean you will see <em>twice</em> as many occurrences of <span class="math inline">\(y\)</span> - i.e.&nbsp;it does not translate to doubling the probability.</p>
<p>Here’s a little more step-by-step explanation to explain:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="qgbmeeorak" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#qgbmeeorak table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#qgbmeeorak thead, #qgbmeeorak tbody, #qgbmeeorak tfoot, #qgbmeeorak tr, #qgbmeeorak td, #qgbmeeorak th {
  border-style: none;
}

#qgbmeeorak p {
  margin: 0;
  padding: 0;
}

#qgbmeeorak .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#qgbmeeorak .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#qgbmeeorak .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#qgbmeeorak .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#qgbmeeorak .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qgbmeeorak .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qgbmeeorak .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qgbmeeorak .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#qgbmeeorak .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#qgbmeeorak .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#qgbmeeorak .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#qgbmeeorak .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#qgbmeeorak .gt_spanner_row {
  border-bottom-style: hidden;
}

#qgbmeeorak .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#qgbmeeorak .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#qgbmeeorak .gt_from_md > :first-child {
  margin-top: 0;
}

#qgbmeeorak .gt_from_md > :last-child {
  margin-bottom: 0;
}

#qgbmeeorak .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#qgbmeeorak .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#qgbmeeorak .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#qgbmeeorak .gt_row_group_first td {
  border-top-width: 2px;
}

#qgbmeeorak .gt_row_group_first th {
  border-top-width: 2px;
}

#qgbmeeorak .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qgbmeeorak .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#qgbmeeorak .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#qgbmeeorak .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qgbmeeorak .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qgbmeeorak .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#qgbmeeorak .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#qgbmeeorak .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#qgbmeeorak .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qgbmeeorak .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qgbmeeorak .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qgbmeeorak .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qgbmeeorak .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qgbmeeorak .gt_left {
  text-align: left;
}

#qgbmeeorak .gt_center {
  text-align: center;
}

#qgbmeeorak .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#qgbmeeorak .gt_font_normal {
  font-weight: normal;
}

#qgbmeeorak .gt_font_bold {
  font-weight: bold;
}

#qgbmeeorak .gt_font_italic {
  font-style: italic;
}

#qgbmeeorak .gt_super {
  font-size: 65%;
}

#qgbmeeorak .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#qgbmeeorak .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#qgbmeeorak .gt_indent_1 {
  text-indent: 5px;
}

#qgbmeeorak .gt_indent_2 {
  text-indent: 10px;
}

#qgbmeeorak .gt_indent_3 {
  text-indent: 15px;
}

#qgbmeeorak .gt_indent_4 {
  text-indent: 20px;
}

#qgbmeeorak .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="coefficient">coefficient</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="b">b</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="exp(b)">exp(b)</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="coefficient" class="gt_row gt_left">(Intercept)</td>
<td headers="b" class="gt_row gt_right">3.76</td>
<td headers="exp(b)" class="gt_row gt_right">43.13</td>
</tr>
<tr>
<td headers="coefficient" class="gt_row gt_left">age</td>
<td headers="b" class="gt_row gt_right">-0.62</td>
<td headers="exp(b)" class="gt_row gt_right">0.54</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ol type="1">
<li>For children aged 2 years old the log-odds of them taking the marshmallow are 3.76 + -0.62*2 = 2.52.<br>
</li>
<li>Translating this to odds, we exponentiate it, so the odds of them taking the marshmallow are <span class="math inline">\(e^{(3.76 + -0.62*2)} = e^{2.52} = 12.43\)</span>.<br>
(This is the same<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> as <span class="math inline">\(e^{3.76} \times e^{-0.62*2}\)</span>)<br>
</li>
<li>These odds of 12.43 means that (rounded to nearest whole number) if we take 13 children aged 2 years, we would expect 12 of them to take the marshmallow, and 1 to not take it.<br>
</li>
<li>If we consider how the odds change for every extra year of age (i.e.&nbsp;for 3 year old as opposed to 2 year old children):
<ul>
<li>the log-odds of taking the marshmallow decrease by -0.62.<br>
</li>
<li>the odds of taking the marshmallow are multiplied by 0.54.<br>
</li>
<li>so for a 3 year old child, the odds are <span class="math inline">\(12.43 \times 0.54 = 6.69\)</span>.<br>
(And we can also calculate this as <span class="math inline">\(e^{2.52 + -0.62}\)</span>)<br>
</li>
</ul>
</li>
<li>So we have gone from odds of 12.4-to-1 for 2 year olds, and 6.7-to-1 for 3 year olds. The odds have been multiplied by 0.54.<br>
But those odds, when converted to probability, these are 0.93 and 0.87. So <span class="math inline">\(0.54 \times odds\)</span> is not <span class="math inline">\(0.54 \times probability\)</span>.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
the intercept (but not slopes) can be converted to a probability
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because our intercept is at a single point (it’s not an <em>association</em>), we can actually convert this to a probability. Remember that <span class="math inline">\(odds = \frac{p}{1-p}\)</span>, which means that <span class="math inline">\(p = \frac{odds}{1 + odds}\)</span>. So the probability of taking the marshmallow for a child aged zero is <span class="math inline">\(\frac{43.13}{1 + 43.13} = 0.98\)</span>.</p>
<p>Unfortunately, we can’t do the same for any slope coefficients. This is because while the intercept is “odds”, the slopes are “odds ratios” (i.e.&nbsp;changes in odds), and changes in odds are different at different levels of probability.</p>
<p>Consider how when we multiply odds by 2, the increase in probability is not constant:</p>
<table class="table">
<thead><tr class="header">
<th>Odds</th>
<th>Probability</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>0.5</td>
<td><span class="math inline">\(\frac{1}{1+0.5} = 0.33\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\(\frac{1}{1+1} = 0.5\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\(\frac{2}{1+2} = 0.66\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td><span class="math inline">\(\frac{4}{1+4} = 0.8\)</span></td>
</tr>
<tr class="odd">
<td>8</td>
<td><span class="math inline">\(\frac{8}{1+8} = 0.88\)</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="blue">
<p><strong>In R:</strong></p>
<p>To translate log-odds to odds in order to aid interpretation, we can exponentiate (i.e., by using exp()) the coefficients from your model using R via the following command:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">modelname</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can also use <code>R</code> to extract predicted probabilities for us from our models.</p>
<ul>
<li>Calculate the predicted log-odds (probabilities on the logit scale): <code>predict(model, type="link")</code>
</li>
<li>Calculate the predicted probabilities: <code>predict(model, type="response")</code>
</li>
</ul>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 7 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_07_glm1.html">S2 Week 7 Lab</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_08_glm2.html">S2 Week 8 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-16" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-16', 'opt-start-16')"> <span class="olab">Generalized Linear Models</span></span>
</div>
<div id="opt-body-16" class="optional-body" style="display: none;">
<p>Generalized linear models can be fitted in R using the <code>glm</code> function, which is similar to the <code>lm</code> function for fitting linear models. However, we also need to specify the family (i.e., link) function. There are three key components to consider:</p>
<ul>
<li>Random component / probability distribution - The distribution of the response/outcome variable. Can be from any family of distributions as listed below.</li>
<li>Systematic component / linear predictor - the explanatory/predictor variable(s) (can be continuous or discrete).</li>
<li>Link function - specifies the link between a random and systematic components.</li>
</ul>
<p><strong>Formula:</strong></p>
<p><span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + + \beta_2 x_i + \epsilon_i\)</span></p>
<div class="blue">
<p><strong>In R:</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> data, <span class="at">family =</span> <span class="sc">&lt;</span>INSERT_FAMILY<span class="sc">&gt;</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>The family argument takes (the name of) a family function which specifies the link function and variance function (as well as a few other arguments not entirely relevant to the purpose of this course).</p>
<p>The exponential family functions available in <strong>R</strong> are:</p>
<ul>
<li>
<code>binomial</code> (link = “logit”)</li>
<li>
<code>gaussian</code> (link = “identity”)</li>
<li>
<code>poisson</code> (link = “log”)</li>
<li>
<code>Gamma</code> (link = “inverse”)</li>
<li>
<code>inverse.gaussian</code> (link = “1/mu2”)</li>
</ul>
<p>See <code><a href="https://rdrr.io/r/stats/glm.html">?glm</a></code> for other modeling options. See <code><a href="https://rdrr.io/r/stats/family.html">?family</a></code> for other allowable link functions for each family.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 7 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_07_glm1.html">S2 Week 7 Lab</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_08_glm2.html">S2 Week 8 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-17" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-17', 'opt-start-17')"> <span class="olab">Drop-in-Deviance Test to Compare Mested Models</span></span>
</div>
<div id="opt-body-17" class="optional-body" style="display: none;">
<p>When moving from linear regression to more advanced and flexible models, testing of goodness of fit is more often done by comparing a model of interest to a simpler one.</p>
<p>The only caveat is that the two models need to be <strong>nested</strong>, i.e.&nbsp;one model needs to be a simplification of the other, and all predictors of one model needs to be within the other.</p>
<p>We want to compare the model we previously fitted against a model where all slopes are 0, i.e.&nbsp;a baseline model:</p>
<p><span class="math display">\[
\begin{aligned}
M_1 : \qquad\log \left( \frac{p}{1 - p} \right) &amp;= \beta_0 \\
M_2 : \qquad \log \left( \frac{p}{1 - p} \right) &amp;= \beta_0 + \beta_1 x
\end{aligned}
\]</span></p>
<div class="blue">
<p><strong>In R:</strong> We do the comparison as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>mdl_reduced <span class="ot">&lt;-</span> <span class="fu">glm</span>(DV <span class="sc">~</span> <span class="dv">1</span>, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> dataset)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>mdl_main <span class="ot">&lt;-</span> <span class="fu">glm</span>(DV <span class="sc">~</span> IV1 <span class="sc">+</span> IV2 ... <span class="sc">+</span> IV4, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> dataset)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mdl_red, mdl_main, <span class="at">test =</span> <span class="st">'Chisq'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the output we can see the residual deviance of each model. Remember the deviance is the equivalent of residual sum of squares in linear regression.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 7 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_07_glm1.html">S2 Week 7 Lab</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_08_glm2.html">S2 Week 8 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-18" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-18', 'opt-start-18')"> <span class="olab">Akaike and Bayesian Information Criteria</span></span>
</div>
<div id="opt-body-18" class="optional-body" style="display: none;">
<p>Deviance measures lack of fit, and it can be reduced to zero by making the model more and more complex, effectively estimating the value at each single data point. However, this involves adding more and more predictors, which makes the model more complex (and less interpretable).</p>
<p>Typically, the simpler model should be preferred when it can still explain the data almost as well. This is why information criteria were devised, exactly to account for both the model misfit but also its complexity.</p>
<p><span class="math display">\[
\text{Information Criterion} = \text{Deviance} + \text{Penalty for model complexity}
\]</span></p>
<p>Depending on the chosen penalty, you get different criteria. Two common ones are the Akaike and Bayesian Information Criteria, AIC and BIC respectively:</p>
<p><span class="math display">\[
\begin{aligned}
\text{AIC} &amp;= \text{Deviance} + 2 p \\
\text{BIC} &amp;= \text{Deviance} + p \log(n)
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(n\)</span> is the sample size and <span class="math inline">\(p\)</span> is the number of regression coefficients in the model. <strong>Models that produce smaller values of these fit criteria should be preferred.</strong></p>
<p>AIC and BIC differ in their degrees of penalization for number of regression coefficients, with BIC usually favouring models with fewer terms.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 7 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_07_glm1.html">S2 Week 7 Lab</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_08_glm2.html">S2 Week 8 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-19" class="fa-solid fa-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-19', 'opt-start-19')"> <span class="olab">Comparing lm() and glm() summary output</span></span>
</div>
<div id="opt-body-19" class="optional-body" style="display: none;">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">lm summary, annotated</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">glm summary, annotated</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-summarylman" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/lmsummary.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3: lm summary, annotated (you may want to open the image in a new tab to zoom in)</figcaption></figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-summaryglman" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/glmsummary.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4: glm summary, annotated (you may want to open the image in a new tab to zoom in)</figcaption></figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See S2 Week 7 Lecture, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_07_glm1.html">S2 Week 7 Lab</a>, and <a href="https://uoepsy.github.io/dapr2/2324/labs/2_08_glm2.html">S2 Week 8 Lab</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>


</section><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1"><p><span class="math inline">\(e^{a+b} = e^a \times e^b\)</span>. For example: <span class="math inline">\(2^2 \times 2^3 = 4 \times 8 = 32 = 2^5 = 2^{2+3}\)</span><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2024 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>