<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Model Fit and Standardization</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR2</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intro-to-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Intro to Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intro-to-linear-models">
<li>
    <a class="dropdown-item" href="./1_01_function.html">
 <span class="dropdown-text">1/1: Functions and Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_slr.html">
 <span class="dropdown-text">1/2: Intro to Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_mlr.html">
 <span class="dropdown-text">1/3: Multiple Regression</span></a>
  </li>  
        <li class="dropdown-header">1/4: Model Fit and Standardization</li>
        <li class="dropdown-header">1/5: Recap &amp; Write Up</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">More Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more-linear-models">
<li class="dropdown-header">1/7: Interactions I: Num x Cat &amp; Num x Num</li>
        <li class="dropdown-header">1/8: Interactions II: Cat x Cat</li>
        <li class="dropdown-header">1/9: Assumptions &amp; Diagnostics</li>
        <li class="dropdown-header">1/10: Bootstrap &amp; Troubleshooting</li>
        <li class="dropdown-header">1/11: Recap &amp; Write Up</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysing-experimental-studies" role="button" data-bs-toggle="dropdown" aria-expanded="false">Analysing Experimental Studies</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysing-experimental-studies">
<li class="dropdown-header">2/1: Functions and Models</li>
        <li class="dropdown-header">2/2: Intro to Linear Regression</li>
        <li class="dropdown-header">2/3: More Linear Regression</li>
        <li class="dropdown-header">2/4: Multiple Predictors</li>
        <li class="dropdown-header">2/5: Recap &amp; Write Up</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-topics-for-lm" role="button" data-bs-toggle="dropdown" aria-expanded="false">Advanced Topics for LM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-topics-for-lm">
<li class="dropdown-header">2/6: Functions and Models</li>
        <li class="dropdown-header">2/7: Intro to Linear Regression</li>
        <li class="dropdown-header">2/8: More Linear Regression</li>
        <li class="dropdown-header">2/9: Multiple Predictors</li>
        <li class="dropdown-header">2/10: Recap &amp; Write Up</li>
    </ul>
</li>
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#study-overview" id="toc-study-overview" class="nav-link active" data-scroll-target="#study-overview">Study Overview</a>
  <ul class="collapse">
<li><a href="#data-recap" id="toc-data-recap" class="nav-link" data-scroll-target="#data-recap">Data Recap</a></li>
  </ul>
</li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li>
<a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
<li><a href="#standardization" id="toc-standardization" class="nav-link" data-scroll-target="#standardization">Standardization</a></li>
  </ul>
</li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Model Fit and Standardization</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand the calculation and interpretation of the coefficient of determination.</li>
<li>Understand the calculation and interpretation of the F-test of model utility.</li>
<li>Understand how to standardize model coefficients and when this is appropriate to do.</li>
<li>Understand the relationship between the correlation coefficient and the regression slope.</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed previous lab exercises from <a href="https://uoepsy.github.io/dapr2/2223/labs/1_01_function.html">Week 1</a>, <a href="https://uoepsy.github.io/dapr2/2223/labs/1_02_slr.html">Week 2</a>, and <a href="https://uoepsy.github.io/dapr2/2223/labs/1_03_mlr.html">Week 3</a>
</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>patchwork</strong></li>
<li><strong>kableExtra</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/wellbeing.csv">here</a> or read it in via this link https://uoepsy.github.io/data/wellbeing.csv. <strong>Note</strong>: this is the same data as Lab 3.</p>
</section>
</div>
<section id="study-overview" class="level1"><h1>Study Overview</h1>
<section id="data-recap" class="level2"><h2 class="anchored" data-anchor-id="data-recap">Data Recap</h2>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Wellbeing data codebook.</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>Researchers interviewed 32 participants, selected at random from the population of residents of Edinburgh &amp; Lothians. They used the Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.</p>
<p>The researchers also asked participants to estimate the average number of hours they spend outdoors each week, the average number of social interactions they have each week (whether on-line or in-person), and whether they believe that they stick to a routine throughout the week (Yes/No).</p>
<p>The data in <code>wellbeing.csv</code> contain five attributes collected from a random sample of <span class="math inline">\(n=32\)</span> hypothetical residents over Edinburgh &amp; Lothians, and include:</p>
<ul>
<li>
<code>wellbeing</code>: Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br>
</li>
<li>
<code>outdoor_time</code>: Self report estimated number of hours per week spent outdoors<br>
</li>
<li>
<code>social_int</code>: Self report estimated number of social interactions per week (both online and in-person)</li>
<li>
<code>routine</code>: Binary Yes/No response to the question “Do you follow a daily routine throughout the week?”</li>
<li>
<code>location</code>: Location of primary residence (City, Suburb, Rural)</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell">
<div class="cell-output-display">

<div id="ydgabwknrs" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ydgabwknrs .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ydgabwknrs .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ydgabwknrs .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ydgabwknrs .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ydgabwknrs .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ydgabwknrs .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ydgabwknrs .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ydgabwknrs .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ydgabwknrs .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ydgabwknrs .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ydgabwknrs .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ydgabwknrs .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ydgabwknrs .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ydgabwknrs .gt_from_md > :first-child {
  margin-top: 0;
}

#ydgabwknrs .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ydgabwknrs .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ydgabwknrs .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ydgabwknrs .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ydgabwknrs .gt_row_group_first td {
  border-top-width: 2px;
}

#ydgabwknrs .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ydgabwknrs .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ydgabwknrs .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ydgabwknrs .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ydgabwknrs .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ydgabwknrs .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ydgabwknrs .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ydgabwknrs .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ydgabwknrs .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ydgabwknrs .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ydgabwknrs .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ydgabwknrs .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ydgabwknrs .gt_left {
  text-align: left;
}

#ydgabwknrs .gt_center {
  text-align: center;
}

#ydgabwknrs .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ydgabwknrs .gt_font_normal {
  font-weight: normal;
}

#ydgabwknrs .gt_font_bold {
  font-weight: bold;
}

#ydgabwknrs .gt_font_italic {
  font-style: italic;
}

#ydgabwknrs .gt_super {
  font-size: 65%;
}

#ydgabwknrs .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#ydgabwknrs .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ydgabwknrs .gt_indent_1 {
  text-indent: 5px;
}

#ydgabwknrs .gt_indent_2 {
  text-indent: 10px;
}

#ydgabwknrs .gt_indent_3 {
  text-indent: 15px;
}

#ydgabwknrs .gt_indent_4 {
  text-indent: 20px;
}

#ydgabwknrs .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">wellbeing</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">outdoor_time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">social_int</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">location</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">routine</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_right">30</td>
<td class="gt_row gt_right">7</td>
<td class="gt_row gt_right">8</td>
<td class="gt_row gt_left">Suburb</td>
<td class="gt_row gt_left">Routine</td>
</tr>
<tr>
<td class="gt_row gt_right">21</td>
<td class="gt_row gt_right">9</td>
<td class="gt_row gt_right">8</td>
<td class="gt_row gt_left">City</td>
<td class="gt_row gt_left">No Routine</td>
</tr>
<tr>
<td class="gt_row gt_right">38</td>
<td class="gt_row gt_right">14</td>
<td class="gt_row gt_right">10</td>
<td class="gt_row gt_left">Suburb</td>
<td class="gt_row gt_left">Routine</td>
</tr>
<tr>
<td class="gt_row gt_right">27</td>
<td class="gt_row gt_right">16</td>
<td class="gt_row gt_right">10</td>
<td class="gt_row gt_left">City</td>
<td class="gt_row gt_left">No Routine</td>
</tr>
<tr>
<td class="gt_row gt_right">20</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">10</td>
<td class="gt_row gt_left">Rural</td>
<td class="gt_row gt_left">No Routine</td>
</tr>
<tr>
<td class="gt_row gt_right">37</td>
<td class="gt_row gt_right">11</td>
<td class="gt_row gt_right">12</td>
<td class="gt_row gt_left">Suburb</td>
<td class="gt_row gt_left">No Routine</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section></section><section id="setup" class="level1"><h1>Setup</h1>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the wellbeing dataset into R, assigning it to an object named <code>mwdata</code>
</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#Loading the required package(s)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Reading in data and storing to an object named 'mwdata'</span></span>
<span><span class="va">mwdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/wellbeing.csv"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 32 Columns: 5</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): location, routine
dbl (3): wellbeing, outdoor_time, social_int

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">riverview</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">'https://uoepsy.github.io/data/riverview.csv'</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 32 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): gender, party
dbl (4): education, income, seniority, male

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="exercises" class="level1"><h1>Exercises</h1>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Specify and fit a linear model to investigate how WEMWBS scores vary with time spent outdoors <em>after</em> controlling for the number of social interactions and whether the individual follows a daily routine. Next, check the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> output from the model.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>The model is:</p>
<p><span class="math display">\[
\widehat{Wellbeing} = \hat \beta_0 + \hat \beta_1 \cdot Social Interactions + \hat \beta_2 \cdot Routine + \hat \beta_3 \cdot Outdoor Time
\]</span></p>
<p>In <code>R</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#fit model</span></span>
<span><span class="va">mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wellbeing</span> <span class="op">~</span> <span class="va">social_int</span> <span class="op">+</span> <span class="va">routine</span> <span class="op">+</span> <span class="va">outdoor_time</span>, data <span class="op">=</span> <span class="va">mwdata</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#look at summary output from model</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ social_int + routine + outdoor_time, 
    data = mwdata)

Residuals:
   Min     1Q Median     3Q    Max 
-9.354 -3.840 -1.071  2.671  8.859 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      3.4097     3.5908   0.950 0.350463    
social_int       1.7859     0.2214   8.065 8.81e-09 ***
routineRoutine   6.9937     1.8152   3.853 0.000623 ***
outdoor_time     0.5371     0.1397   3.844 0.000638 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.058 on 28 degrees of freedom
Multiple R-squared:  0.8303,    Adjusted R-squared:  0.8121 
F-statistic: 45.67 on 3 and 28 DF,  p-value: 6.525e-11</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p>Recall the main formulas for obtaining a confidence interval and a test-statistic:</p>
<div class="statbox">
<p><strong>Test statistic</strong></p>
<p>A test statistic for the null hypothesis <span class="math inline">\(H_0: \beta_1 = 0\)</span> is</p>
<p><span class="math display">\[
t = \frac{\hat \beta_1 - 0}{SE(\hat \beta_1)}
\]</span></p>
<p>which follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.</p>
<p><strong>Confidence interval</strong></p>
<p>A confidence interval for the population slope is</p>
<p><span class="math display">\[
\hat \beta_1 \pm t^* \cdot SE(\hat \beta_1)
\]</span></p>
<p>where <span class="math inline">\(t^*\)</span> denotes the critical value chosen from t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom for a desired <span class="math inline">\(\alpha\)</span> level of confidence.</p>
</div>
<p><br></p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Test the hypothesis that the population slope is zero — that is, that there is no linear association between wellbeing and outdoor time (<em>after</em> controlling for the number of social interactions and whether the individual follows a daily routine) in the population.</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You can find all of the necessary information in the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> output of your model, or calculate manually.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Manually</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">R function</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>We calculate the test statistic</p>
<p><span class="math display">\[
t = \frac{\hat \beta_3 - 0}{SE(\hat \beta_3)} = \frac{0.5371 - 0}{0.1397} = 3.845
\]</span></p>
<p>and compare it with the 5% critical value from a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom, which is:</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">mwdata</span><span class="op">)</span></span>
<span><span class="va">tstar</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.975</span>, df <span class="op">=</span> <span class="va">n</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">tstar</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.042272</code></pre>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#tstar = 2.042272</span></span></code></pre></div>
</div>
<p>As <span class="math inline">\(|t|\)</span> (<span class="math inline">\(|t|\)</span> = 3.85) is much larger than <span class="math inline">\(t^*\)</span> (<span class="math inline">\(t^*\)</span> = 2.04), we reject then null hypothesis as we have strong evidence against it.</p>
<p>The <span class="math inline">\(p\)</span>-value, shown below, also confirms this conclusion.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fl">2</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span><span class="fl">3.845</span>, <span class="va">n</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0005835717</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Please note that the same information was already contained in the row corresponding to the variable “outdoor_time” in the output of <code>summary(mdl)</code>, which reported the <span class="math inline">\(t\)</span>-statistic under <code>t value</code> and the <span class="math inline">\(p\)</span>-value under <code>Pr(&gt;|t|)</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ social_int + routine + outdoor_time, 
    data = mwdata)

Residuals:
   Min     1Q Median     3Q    Max 
-9.354 -3.840 -1.071  2.671  8.859 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      3.4097     3.5908   0.950 0.350463    
social_int       1.7859     0.2214   8.065 8.81e-09 ***
routineRoutine   6.9937     1.8152   3.853 0.000623 ***
outdoor_time     0.5371     0.1397   3.844 0.000638 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.058 on 28 degrees of freedom
Multiple R-squared:  0.8303,    Adjusted R-squared:  0.8121 
F-statistic: 45.67 on 3 and 28 DF,  p-value: 6.525e-11</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Before we interpret the results, note that sometimes <span class="math inline">\(p\)</span>-values will be reported to <span class="math inline">\(e^X\)</span>. For example, look in the <code>Pr(&gt;|t|)</code> column for “social_int”. The value <span class="math inline">\(8.81e^-09^\)</span> simply means <span class="math inline">\(8.81 \times 10^{-9}\)</span>. This is a very small value (i.e., 0.00000000881), hence we will report it as &lt;.001 following the <a href="https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf">APA guidelines</a>.</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>We performed a <span class="math inline">\(t\)</span>-test against the null hypothesis that outdoor time was not associated with wellbeing scores. A significant association was found between level of outdoor time (in hours per week) and wellbeing (WEMWBS scores) <span class="math inline">\(t(28) = 3.84,\ p &lt; .001\)</span>, two-sided. Thus, we have evidence to reject the null hypothesis.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Compute a confidence interval for the regression slope for <span class="math display">\[\hat \beta_3\]</span>.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Manually</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">R function</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p>For 95% confidence we have <span class="math inline">\(t^* = 2.04\)</span>:</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">mwdata</span><span class="op">)</span></span>
<span><span class="va">tstar</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.975</span>, df <span class="op">=</span> <span class="va">n</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">tstar</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.042272</code></pre>
</div>
</div>
<p>The confidence interval is:</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">beta3_ci</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  lower <span class="op">=</span> <span class="fl">0.5371</span> <span class="op">-</span> <span class="va">tstar</span> <span class="op">*</span> <span class="fl">0.1397</span>,</span>
<span>  upper <span class="op">=</span> <span class="fl">0.5371</span> <span class="op">+</span> <span class="va">tstar</span> <span class="op">*</span> <span class="fl">0.1397</span>,</span>
<span>                  <span class="op">)</span></span>
<span><span class="va">beta3_ci</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower upper
  &lt;dbl&gt; &lt;dbl&gt;
1 0.252 0.822</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>We can easily obtain the confidence intervals for the regression coefficients using the command <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">mdl</span>, level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %     97.5 %
(Intercept)    -3.945790 10.7651807
social_int      1.332306  2.2395049
routineRoutine  3.275366 10.7119970
outdoor_time    0.250891  0.8233483</code></pre>
</div>
</div>
<p>The result is exactly the same (up to rounding errors) as calculating manually.</p>
</div>
</div>
</div>
<p>We typically report our uncertainty in a statistic by providing <span class="math inline">\(\text{estimate} \pm t^* \cdot \text{SE}\)</span>. Here we would say that because of sampling variation, we are 95% confident that the slope is between 0.252 and 0.822. Interpreting this, we might say,</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>For all Riverview city employees, each one-year difference in formal education was associated with a difference in income between $1,896 and $3,406, on average.</p>
</div>
</div>
</div>
<p>Similarly, we could express the uncertainty in the intercept <span class="math inline">\(\hat \beta_0\)</span> as:</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The average income for all Riverview city employees with zero years of education is between $-1184 and $23,827.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>What is the proportion of the total variability in wellbeing scores explained by the model?</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The question asks to compute the value of <span class="math inline">\(R^2\)</span>. Since the model has more than 2 predictors, you should report the Adjusted <span class="math inline">\(R^2\)</span>.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<p>The proportion of the total variability explained is given by R-squared.</p>
<p>The R-squared coefficient is defined as:</p>
<p><span class="math display">\[
R^2 = \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\]</span></p>
<p>The Adjusted R-squared coefficient is defined as:</p>
<p><span class="math display">\[
\hat R^2 = 1 - \frac{(1 - R^2)(n-1)}{n-k-1}
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; n = \text{sample size} \\
&amp; k = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Manually</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">summary()</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false">Manually: ANOVA</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p>In <code>R</code> we can write:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#R squared &amp; adjusted R squared</span></span>
<span></span>
<span><span class="va">wellbeing_fitted</span> <span class="op">&lt;-</span> <span class="va">mwdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    wellbeing_hat <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span>,</span>
<span>    resid <span class="op">=</span> <span class="va">wellbeing</span> <span class="op">-</span> <span class="va">wellbeing_hat</span></span>
<span>  <span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">wellbeing_fitted</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  wellbeing outdoor_time social_int location routine    wellbeing_hat resid
      &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt;
1        30            7          8 Suburb   Routine             28.5  1.55
2        21            9          8 City     No Routine          22.5 -1.53
3        38           14         10 Suburb   Routine             35.8  2.22
4        27           16         10 City     No Routine          29.9 -2.86
5        20            1         10 Rural    No Routine          21.8 -1.81
6        37           11         12 Suburb   No Routine          30.7  6.25</code></pre>
</div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">wellbeing_fitted</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>    SSModel <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span> <span class="op">(</span><span class="va">wellbeing_hat</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">wellbeing</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">)</span>,</span>
<span>    SSTotal <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span> <span class="op">(</span><span class="va">wellbeing</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">wellbeing</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>    RSquared <span class="op">=</span> <span class="va">SSModel</span> <span class="op">/</span> <span class="va">SSTotal</span>,</span>
<span>    AdjRSquared <span class="op">=</span> <span class="fl">1</span><span class="op">-</span><span class="op">(</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="op">(</span><span class="va">RSquared</span><span class="op">)</span><span class="op">)</span><span class="op">*</span><span class="op">(</span><span class="fl">32</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="fl">32</span><span class="op">-</span><span class="fl">3</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  RSquared AdjRSquared
     &lt;dbl&gt;       &lt;dbl&gt;
1    0.830       0.812</code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ social_int + routine + outdoor_time, 
    data = mwdata)

Residuals:
   Min     1Q Median     3Q    Max 
-9.354 -3.840 -1.071  2.671  8.859 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      3.4097     3.5908   0.950 0.350463    
social_int       1.7859     0.2214   8.065 8.81e-09 ***
routineRoutine   6.9937     1.8152   3.853 0.000623 ***
outdoor_time     0.5371     0.1397   3.844 0.000638 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.058 on 28 degrees of freedom
Multiple R-squared:  0.8303,    Adjusted R-squared:  0.8121 
F-statistic: 45.67 on 3 and 28 DF,  p-value: 6.525e-11</code></pre>
</div>
</div>
<p>The output of <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> displays the Adjusted <span class="math inline">\(R\)</span>-squared value in the following line:</p>
<pre><code>Adjusted R-squared:  0.8121 </code></pre>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<p>We can perform an <strong>AN</strong>alysis <strong>O</strong>f <strong>VA</strong>riance or, in short, ANOVA.</p>
<p>It simply means that we are examining/partitioning the total variability of a response variable.</p>
<p>The <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> function returns the sum of squares of interest in the column <code>Sum Sq</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl_anova</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span>
<span><span class="va">mdl_anova</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: wellbeing
             Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
social_int    1 2661.03 2661.03 104.001 6.231e-11 ***
routine       1  466.48  466.48  18.231 0.0002031 ***
outdoor_time  1  378.06  378.06  14.776 0.0006376 ***
Residuals    28  716.43   25.59                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Consider the column <code>Sum Sq</code>. The entry corresponding to <code>education</code> gives <span class="math inline">\(SS_{Model}\)</span> = 4147.3, as education is the explanatory variable. The entry corresponding to <code>Residuals</code> gives <span class="math inline">\(SS_{Residual}\)</span> = 2418.2.</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># Because the column name Sum Sq has a space, we need to wrap it with backticks</span></span>
<span><span class="va">SSModel</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">mdl_anova</span><span class="op">$</span><span class="va">`Sum Sq`</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span><span class="op">+</span><span class="op">(</span><span class="va">mdl_anova</span><span class="op">$</span><span class="va">`Sum Sq`</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">+</span><span class="op">(</span><span class="va">mdl_anova</span><span class="op">$</span><span class="va">`Sum Sq`</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="va">SSResidual</span> <span class="op">&lt;-</span> <span class="va">mdl_anova</span><span class="op">$</span><span class="va">`Sum Sq`</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span></span>
<span><span class="va">SSTotal</span> <span class="op">&lt;-</span> <span class="va">SSModel</span> <span class="op">+</span> <span class="va">SSResidual</span></span>
<span></span>
<span><span class="va">RSquared</span> <span class="op">&lt;-</span> <span class="va">SSModel</span> <span class="op">/</span> <span class="va">SSTotal</span></span>
<span><span class="va">RSquared</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8303108</code></pre>
</div>
</div>
<p>Now to calculate the Adjusted R Squared, simply sub the values into the formula given above:</p>
<p><span class="math display">\[
\hat R^2 = 1 - \frac{(1 - 0.83)(32-1)}{32-3-1}
\]</span></p>
<p>In R:</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#sub in values - pull from R as opposed to including rounded numbers to improve accuracy of estimation</span></span>
<span><span class="va">AdjRSquared</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="op">(</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="va">RSquared</span><span class="op">)</span><span class="op">*</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">mwdata</span><span class="op">)</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">mwdata</span><span class="op">)</span><span class="op">-</span><span class="fl">3</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">AdjRSquared</span> </span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8121298</code></pre>
</div>
</div>
</div>
</div>
</div>
<hr>
<p><strong>Interpretation</strong></p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Approximately 81% of the total variability in wellbeing scores is explained by associations with social interactions, routine, and outdoor time.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Perform a model utility test at the 5% significance level, by computing the F-statistic using its definition.</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The F-ratio is used to test the null hypothesis that all regression slopes are zero.<br>
It is called the F-ratio because it is the ratio of the how much of the variation is explained by the model (per paramater) versus how much of the variation is left unexplained in the residuals (per remaining degrees of freedom).</p>
<p><span class="math display">\[
F_{df_{model},df_{residual}} = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model}/df_{Model}}{SS_{Residual}/df_{Residual}} \\
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; df_{model} = k \\
&amp; df_{residual} = n-k-1 \\
&amp; n = \text{sample size} \\
&amp; k  = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="optional-begin">
<span id="opt-start-7" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-7', 'opt-start-7')"> <span class="olab">Optional: Another formula for the F-test.</span></span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<p>With some algebra we can also show that:</p>
<p><span class="math display">\[
F = \frac{R^2 / 1}{(1 - R^2) / (n - 2) } = \frac{R^2 / df_{Model}}{(1 - R^2) / df_{Residual} }
\]</span></p>
<p>Proof:</p>
<p><span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)}
= \frac{\frac{SS_{Model}}{SS_{Total}}}{\frac{SS_{Residual}}{SS_{Total}} \cdot \frac{1}{(n - 2)}}
= \frac{R^2 / 1}{(1 - R^2) / (n - 2)}
\end{aligned}
\]</span></p>
</div>
<p class="optional-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">df1</span> <span class="op">&lt;-</span> <span class="fl">1</span></span>
<span><span class="va">df2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">mwdata</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2</span></span>
<span><span class="va">f_star</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Fdist.html">qf</a></span><span class="op">(</span><span class="fl">0.95</span>, <span class="va">df1</span>, <span class="va">df2</span><span class="op">)</span></span>
<span><span class="va">f_star</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.170877</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">model_utility</span> <span class="op">&lt;-</span> <span class="va">wellbeing_fitted</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>    SSModel <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">wellbeing_hat</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">wellbeing</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">)</span>,</span>
<span>    SSResid <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span> <span class="va">resid</span><span class="op">^</span><span class="fl">2</span> <span class="op">)</span>,</span>
<span>    MSModel <span class="op">=</span> <span class="va">SSModel</span> <span class="op">/</span> <span class="fl">1</span>,</span>
<span>    MSResid <span class="op">=</span> <span class="va">SSResid</span> <span class="op">/</span> <span class="va">df2</span>,</span>
<span>    FObs <span class="op">=</span> <span class="va">MSModel</span> <span class="op">/</span> <span class="va">MSResid</span></span>
<span>  <span class="op">)</span></span>
<span><span class="va">model_utility</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  SSModel SSResid MSModel MSResid  FObs
    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1   3506.    716.   3506.    23.9  147.</code></pre>
</div>
</div>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>We performed an <span class="math inline">\(F\)</span>-test of model utility at the 5% significance level, where <span class="math inline">\(F(1,30) = 51.45\)</span>.</p>
<p>As the observed <span class="math inline">\(F = 51.45\)</span> is much larger than the critical value <span class="math inline">\(F^* = 4.17\)</span>, we have strong evidence to reject the null hypothesis that the model is ineffective.</p>
</div>
</div>
</div>
<p><br> Alternatively, we can compute the p-value: ::: {.cell}</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">pvalue</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Fdist.html">pf</a></span><span class="op">(</span><span class="va">model_utility</span><span class="op">$</span><span class="va">FObs</span>, <span class="va">df1</span>, <span class="va">df2</span><span class="op">)</span></span>
<span><span class="va">pvalue</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.387601e-13</code></pre>
</div>
<p>::: The value <code>5.562116e-08</code> simply means <span class="math inline">\(5.56 \times 10^{-8}\)</span>, so it’s a really small number.</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>We performed an <span class="math inline">\(F\)</span>-test of model utility at the 5% significance level, where <span class="math inline">\(F(1,30) = 51.45, p&lt;.001\)</span>.</p>
<p>The <span class="math inline">\(p\)</span>-value (&lt; .001) is much lower than the specified significance level, meaning that we have evidence against the null hypothesis.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Look at the output of <code>summary(mdl)</code> and <code>anova(mdl)</code>.</p>
<p>For each output, identify the relevant information to conduct an F-test against the null hypothesis that the model is ineffective at predicting income using education level.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">summary() output</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">anova() output</a></li>
</ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ social_int + routine + outdoor_time, 
    data = mwdata)

Residuals:
   Min     1Q Median     3Q    Max 
-9.354 -3.840 -1.071  2.671  8.859 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      3.4097     3.5908   0.950 0.350463    
social_int       1.7859     0.2214   8.065 8.81e-09 ***
routineRoutine   6.9937     1.8152   3.853 0.000623 ***
outdoor_time     0.5371     0.1397   3.844 0.000638 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.058 on 28 degrees of freedom
Multiple R-squared:  0.8303,    Adjusted R-squared:  0.8121 
F-statistic: 45.67 on 3 and 28 DF,  p-value: 6.525e-11</code></pre>
</div>
</div>
<p>The relevant row is the following:</p>
<pre><code>F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: wellbeing
             Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
social_int    1 2661.03 2661.03 104.001 6.231e-11 ***
routine       1  466.48  466.48  18.231 0.0002031 ***
outdoor_time  1  378.06  378.06  14.776 0.0006376 ***
Residuals    28  716.43   25.59                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>And the relevant entries are:</p>
<ul>
<li>the <code>Df</code> column, which contains the degrees of freedom;</li>
<li>
<code>F value = 51.452</code>, which is the F-statistic;</li>
<li>
<code>Pr(&gt;F) = 5.562e-08</code> = <span class="math inline">\(5.562 \times 10^{-8}\)</span>, which is the p-value.</li>
</ul>
</div>
</div>
</div>
<hr>
<p><strong>Interpretation</strong></p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>We performed an <span class="math inline">\(F\)</span>-test for the overall significance of the regression, <span class="math inline">\(F(1, 30) = 51.45, p &lt; .001\)</span>.</p>
<p>The large <span class="math inline">\(F\)</span>-statistic leads to a very small <span class="math inline">\(p\)</span>-value (<span class="math inline">\(&lt;.001\)</span>), meaning that we have very strong evidence against the null hypothesis that the model is ineffective.</p>
<p>In other words, the data provide strong evidence that education is an effective predictor of income.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Consider the <code>F value</code> output of <code>anova(mdl)</code> and the <code>t value</code> for education returned by <code>summary(mdl)</code></p>
<pre><code>F value = 51.452
t value = 7.173</code></pre>
<p>Do you notice any relationship between the F-statistic for overall model utility and the t-statistic for <span class="math inline">\(H_0: \beta_1 = 0\)</span>?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<p><strong>In simple linear regression only</strong>, the F-statistic for overall model significance is equal to the square of the t-statistic for <span class="math inline">\(H_0: \beta_1 = 0\)</span>.</p>
<p>You can check that the squared t-statistic is equal, up to rounding error, to the F-statistic:</p>
<p><span class="math display">\[
t^2 = F \\
7.173^2 = 51.452
\]</span></p>
<div class="optional-begin">
<span id="opt-start-11" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-11', 'opt-start-11')"> <span class="olab">Optional: Equivalence of t-test for the slope and model utility F-test in SLR.</span></span>
</div>
<div id="opt-body-11" class="optional-body" style="display: none;">
<p>Here we will show the equivalence of the F-test for model effectiveness and t-test for the slope.</p>
<p>Recall the formula of the sum of squares due to the model. We will rewrite it in an equivalent form below:</p>
<p><span class="math display">\[
\begin{aligned}
SS_{Model} &amp;= \sum_i (\hat y_i - \bar y)^2 \\
&amp;= \sum_i (\hat \beta_0 + \hat \beta_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\bar y - \hat \beta_1 \bar x + \hat \beta_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\hat \beta_1 (x_i - \bar x))^2 \\
&amp;= \hat \beta_1^2 \sum_i (x_i - \bar x)^2
\end{aligned}
\]</span></p>
<p>The <span class="math inline">\(F\)</span>-statistic is given by:</p>
<p><span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)}
= \frac{\hat \beta_1^2 \sum_i (x_i - \bar x)^2}{\hat \sigma^2}
= \frac{\hat \beta_1^2 }{\hat \sigma^2 / \sum_i (x_i - \bar x)^2}
\end{aligned}
\]</span></p>
<p>Now recall the formula of the <span class="math inline">\(t\)</span>-statistic,</p>
<p><span class="math display">\[
t = \frac{\hat \beta_1}{SE(\hat \beta_1)} = \frac{\hat \beta_1}{\hat \sigma / \sqrt{\sum_i (x_i - \bar x)^2}}
\]</span></p>
<p>It is evident that the latter is obtained as the square root of the former.</p>
</div>
<p class="optional-end">
</p>
</div>
<p class="solution-end">
</p>
<section id="standardization" class="level2"><h2 class="anchored" data-anchor-id="standardization">Standardization</h2>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Fit the regression model using the standardized response and explanatory variables.</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You can either:</p>
<ol type="1">
<li>Add to the “mwdata” dataset three variables called <code>z_wellbeing</code>, <code>z_social_int</code>, and <code>z_outdoor_time</code> representing the standardized welllbeing, social interactions and outdoor time variables, respectively. or</li>
<li>Use the <code><a href="https://rdrr.io/r/base/scale.html">scale()</a></code> function when specifying your <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> statement.</li>
</ol>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">Z-score</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">scale() function</a></li>
</ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mwdata</span> <span class="op">&lt;-</span> <span class="va">mwdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    z_wellbeing <span class="op">=</span> <span class="op">(</span><span class="va">wellbeing</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">wellbeing</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">wellbeing</span><span class="op">)</span>,</span>
<span>    z_social_int <span class="op">=</span> <span class="op">(</span><span class="va">social_int</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">social_int</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">social_int</span><span class="op">)</span>,</span>
<span>    z_outdoor_time <span class="op">=</span> <span class="op">(</span><span class="va">outdoor_time</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">outdoor_time</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">outdoor_time</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
</div>
<p>Check that they are standardized:</p>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mwdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>    M_z_wellbeing <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">z_wellbeing</span><span class="op">)</span>,<span class="fl">2</span><span class="op">)</span>, SD_z_wellbeing <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">z_wellbeing</span><span class="op">)</span>, </span>
<span>    M_z_social_int <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">z_social_int</span><span class="op">)</span>,<span class="fl">2</span><span class="op">)</span>, SD_z_social_int <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">z_social_int</span><span class="op">)</span>,</span>
<span>    M_z_outdoor_time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">z_outdoor_time</span><span class="op">)</span>,<span class="fl">2</span><span class="op">)</span>, SD_z_outdoor_time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">z_outdoor_time</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  M_z_wellbeing SD_z_wellbeing M_z_social_int SD_z_social_int M_z_outd…¹ SD_z_…²
          &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
1             0              1              0               1          0       1
# … with abbreviated variable names ¹​M_z_outdoor_time, ²​SD_z_outdoor_time</code></pre>
</div>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#mean of 0, SD of 1 - all good to go</span></span></code></pre></div>
</div>
<p>Run model:</p>
<div class="cell">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#with z scoring</span></span>
<span><span class="va">mdl_z</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">z_wellbeing</span> <span class="op">~</span> <span class="va">z_social_int</span> <span class="op">+</span> <span class="va">z_outdoor_time</span>, data <span class="op">=</span> <span class="va">mwdata</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_z</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = z_wellbeing ~ z_social_int + z_outdoor_time, data = mwdata)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.8347 -0.4212 -0.1075  0.4822  0.9371 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    1.327e-16  9.313e-02   0.000   1.0000    
z_social_int   6.742e-01  1.006e-01   6.702 2.37e-07 ***
z_outdoor_time 3.527e-01  1.006e-01   3.506   0.0015 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5268 on 29 degrees of freedom
Multiple R-squared:  0.7404,    Adjusted R-squared:  0.7224 
F-statistic: 41.34 on 2 and 29 DF,  p-value: 3.226e-09</code></pre>
</div>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_z</span><span class="op">)</span><span class="op">$</span><span class="va">coefficients</span>,<span class="fl">3</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)       0.000      0.093   0.000    1.000
z_social_int      0.674      0.101   6.702    0.000
z_outdoor_time    0.353      0.101   3.506    0.001</code></pre>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#use scale</span></span>
<span><span class="va">mdl_s</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">wellbeing</span><span class="op">)</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">social_int</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">outdoor_time</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">mwdata</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_s</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = scale(wellbeing) ~ scale(social_int) + scale(outdoor_time), 
    data = mwdata)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.8347 -0.4212 -0.1075  0.4822  0.9371 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         1.327e-16  9.313e-02   0.000   1.0000    
scale(social_int)   6.742e-01  1.006e-01   6.702 2.37e-07 ***
scale(outdoor_time) 3.527e-01  1.006e-01   3.506   0.0015 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5268 on 29 degrees of freedom
Multiple R-squared:  0.7404,    Adjusted R-squared:  0.7224 
F-statistic: 41.34 on 2 and 29 DF,  p-value: 3.226e-09</code></pre>
</div>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_s</span><span class="op">)</span><span class="op">$</span><span class="va">coefficients</span>,<span class="fl">3</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)            0.000      0.093   0.000    1.000
scale(social_int)      0.674      0.101   6.702    0.000
scale(outdoor_time)    0.353      0.101   3.506    0.001</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Interpret the slope of the standardized variables.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-13" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')"> Solution </span>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>For every standard deviation increase in education, income increases on average by 0.79 standard deviations.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section></section><section id="references" class="level1"><h1>References</h1>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
      <div class="nav-footer-center">© Copyright 2019-2022 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
  </div>
</footer>


</body></html>