<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Categorical Predictors &amp; Block 1 Recap</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR2</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intro-to-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Intro to Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intro-to-linear-models">
<li>
    <a class="dropdown-item" href="./1_01_function.html">
 <span class="dropdown-text">1/1: Functions and Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_slr.html">
 <span class="dropdown-text">1/2: Intro to Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_mlr.html">
 <span class="dropdown-text">1/3: Multiple Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_model_fit.html">
 <span class="dropdown-text">1/4: Model Fit and Standardization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_05_cat_recap.html">
 <span class="dropdown-text">1/5: Cat Predictors &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">More Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more-linear-models">
<li class="dropdown-header">1/7: Interactions I: Num x Cat</li>
        <li class="dropdown-header">1/8: Interactions II: Num x Num</li>
        <li class="dropdown-header">1/9: Interactions III: Cat x Cat</li>
        <li class="dropdown-header">1/10: Assumptions &amp; Diagnostics</li>
        <li class="dropdown-header">1/11: Recap &amp; Write Up</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysing-experimental-studies" role="button" data-bs-toggle="dropdown" aria-expanded="false">Analysing Experimental Studies</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysing-experimental-studies">
<li class="dropdown-header">2/1: Functions and Models</li>
        <li class="dropdown-header">2/2: Intro to Linear Regression</li>
        <li class="dropdown-header">2/3: More Linear Regression</li>
        <li class="dropdown-header">2/4: Multiple Predictors</li>
        <li class="dropdown-header">2/5: Recap &amp; Write Up</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-topics-for-lm" role="button" data-bs-toggle="dropdown" aria-expanded="false">Advanced Topics for LM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-topics-for-lm">
<li class="dropdown-header">2/6: Functions and Models</li>
        <li class="dropdown-header">2/7: Intro to Linear Regression</li>
        <li class="dropdown-header">2/8: More Linear Regression</li>
        <li class="dropdown-header">2/9: Multiple Predictors</li>
        <li class="dropdown-header">2/10: Recap &amp; Write Up</li>
    </ul>
</li>
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#section-a-numeric-categorical" id="toc-section-a-numeric-categorical" class="nav-link active" data-scroll-target="#section-a-numeric-categorical">Section A: Numeric + Categorical</a>
  <ul class="collapse">
<li><a href="#study-overview" id="toc-study-overview" class="nav-link" data-scroll-target="#study-overview">Study Overview</a></li>
  </ul>
</li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#section-b-weeks-1---4-recap" id="toc-section-b-weeks-1---4-recap" class="nav-link" data-scroll-target="#section-b-weeks-1---4-recap">Section B: Weeks 1 - 4 Recap</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Categorical Predictors &amp; Block 1 Recap</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand the meaning of (and how to interpret) a multiple regression model with a binary predictor</li>
<li>Understand how to specify a new baseline/reference level for categorical variables</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed Labs 1 - 4</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>patchwork</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/wellbeing.csv">here</a> or read it in via this link https://uoepsy.github.io/data/wellbeing.csv.</p>
<p><strong>Note</strong>: this is the same data as Lab 3 &amp; 4.</p>
</section>
</div>
<section id="section-a-numeric-categorical" class="level1"><h1>Section A: Numeric + Categorical</h1>
<section id="study-overview" class="level2"><h2 class="anchored" data-anchor-id="study-overview">Study Overview</h2>
<blockquote class="blockquote">
<p><strong>Research Question</strong></p>
<p>Is there an assocation between well-being and time spent outdoors <em>after</em> taking into account the assocation between well-being and <em>having a routine</em>?</p>
</blockquote>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Wellbeing data codebook.</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>Researchers interviewed 32 participants, selected at random from the population of residents of Edinburgh &amp; Lothians. They used the Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.</p>
<p>The researchers also asked participants to estimate the average number of hours they spend outdoors each week, the average number of social interactions they have each week (whether on-line or in-person), and whether they believe that they stick to a routine throughout the week (Yes/No).</p>
<p>The data in <code>wellbeing.csv</code> contain five attributes collected from a random sample of <span class="math inline">\(n=32\)</span> hypothetical residents over Edinburgh &amp; Lothians, and include:</p>
<ul>
<li>
<code>wellbeing</code>: Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br>
</li>
<li>
<code>outdoor_time</code>: Self report estimated number of hours per week spent outdoors<br>
</li>
<li>
<code>social_int</code>: Self report estimated number of social interactions per week (both online and in-person)</li>
<li>
<code>routine</code>: Binary Yes/No response to the question “Do you follow a daily routine throughout the week?”</li>
<li>
<code>location</code>: Location of primary residence (City, Suburb, Rural)</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell">
<div class="cell-output-display">

<div id="pqxkbfqhgj" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#pqxkbfqhgj .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#pqxkbfqhgj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#pqxkbfqhgj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#pqxkbfqhgj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#pqxkbfqhgj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#pqxkbfqhgj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#pqxkbfqhgj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#pqxkbfqhgj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#pqxkbfqhgj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#pqxkbfqhgj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#pqxkbfqhgj .gt_from_md > :first-child {
  margin-top: 0;
}

#pqxkbfqhgj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#pqxkbfqhgj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#pqxkbfqhgj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#pqxkbfqhgj .gt_row_group_first td {
  border-top-width: 2px;
}

#pqxkbfqhgj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#pqxkbfqhgj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#pqxkbfqhgj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#pqxkbfqhgj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#pqxkbfqhgj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_left {
  text-align: left;
}

#pqxkbfqhgj .gt_center {
  text-align: center;
}

#pqxkbfqhgj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#pqxkbfqhgj .gt_font_normal {
  font-weight: normal;
}

#pqxkbfqhgj .gt_font_bold {
  font-weight: bold;
}

#pqxkbfqhgj .gt_font_italic {
  font-style: italic;
}

#pqxkbfqhgj .gt_super {
  font-size: 65%;
}

#pqxkbfqhgj .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#pqxkbfqhgj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#pqxkbfqhgj .gt_indent_1 {
  text-indent: 5px;
}

#pqxkbfqhgj .gt_indent_2 {
  text-indent: 10px;
}

#pqxkbfqhgj .gt_indent_3 {
  text-indent: 15px;
}

#pqxkbfqhgj .gt_indent_4 {
  text-indent: 20px;
}

#pqxkbfqhgj .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">wellbeing</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">outdoor_time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">social_int</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">location</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">routine</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_right">30</td>
<td class="gt_row gt_right">7</td>
<td class="gt_row gt_right">8</td>
<td class="gt_row gt_left">Suburb</td>
<td class="gt_row gt_left">Routine</td>
</tr>
<tr>
<td class="gt_row gt_right">21</td>
<td class="gt_row gt_right">9</td>
<td class="gt_row gt_right">8</td>
<td class="gt_row gt_left">City</td>
<td class="gt_row gt_left">No Routine</td>
</tr>
<tr>
<td class="gt_row gt_right">38</td>
<td class="gt_row gt_right">14</td>
<td class="gt_row gt_right">10</td>
<td class="gt_row gt_left">Suburb</td>
<td class="gt_row gt_left">Routine</td>
</tr>
<tr>
<td class="gt_row gt_right">27</td>
<td class="gt_row gt_right">16</td>
<td class="gt_row gt_right">10</td>
<td class="gt_row gt_left">City</td>
<td class="gt_row gt_left">No Routine</td>
</tr>
<tr>
<td class="gt_row gt_right">20</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">10</td>
<td class="gt_row gt_left">Rural</td>
<td class="gt_row gt_left">No Routine</td>
</tr>
<tr>
<td class="gt_row gt_right">37</td>
<td class="gt_row gt_right">11</td>
<td class="gt_row gt_right">12</td>
<td class="gt_row gt_left">Suburb</td>
<td class="gt_row gt_left">No Routine</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section></section><section id="setup" class="level1"><h1>Setup</h1>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the wellbeing dataset into R, assigning it to an object named <code>mwdata</code>
</li>
<li>Check coding of variables (e.g., make sure that catgorical variables are coded as factors)</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#Loading the required package(s)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Reading in data and storing to an object named 'mwdata'</span></span>
<span><span class="va">mwdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/wellbeing.csv"</span><span class="op">)</span></span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#check coding of routine variable - should be a factor - check by running `is.factor()`</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">is.factor</a></span><span class="op">(</span><span class="va">mwdata</span><span class="op">$</span><span class="va">routine</span><span class="op">)</span> <span class="co">#result = false, so need to make routine a factor</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#designate routine as factor and check using above code if change has been applied by re-running line (should now be TRUE)</span></span>
<span><span class="va">mwdata</span><span class="op">$</span><span class="va">routine</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">mwdata</span><span class="op">$</span><span class="va">routine</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Produce visualisations of:</p>
<ol type="1">
<li>the distribution of the <code>routine</code> variable</li>
<li>the association between <code>routine</code> and <code>wellbeing</code>.</li>
</ol>
<p>Provide interpretation of these figures.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We cannot visualise the distribution of <code>routine</code> as a density curve or boxplot, because it is a <em>categorical</em> variable (observations can only take one of a set of discrete response values). Revise the <a href="https://uoepsy.github.io/dapr1/2122/labs/1_01_data_types.html#Types_of_data">DAPR1 materials</a> for a recap of data types.</p>
</div>
</div>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Consider using <code><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar()</a></code> and/or <code><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot()</a></code>. The <a href="https://uoepsy.github.io/dapr1/2122/labs/1_02_categorical.html">DAPR1 categorical data lab</a> might provide a useful starting point if needed.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p><code><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar()</a></code> will count the number of observations falling into each unique level of the routine variable:</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">mwdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">routine</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Routine"</span>, y <span class="op">=</span> <span class="st">"Frequency"</span><span class="op">)</span></span>
<span><span class="va">p1</span></span></code></pre></div>
<div class="cell-output-display">
<div id="fig-dist-routine" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_05_cat_recap_files/figure-html/fig-dist-routine-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 1: Marginal distribution plots of Routine (y/n)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We might plot the association between routine and wellbeing as two boxplots:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">p2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">mwdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">routine</span>, y <span class="op">=</span> <span class="va">wellbeing</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Routine"</span>, y <span class="op">=</span> <span class="st">"Wellbeing score (WEMWBS)"</span><span class="op">)</span></span>
<span><span class="va">p2</span></span></code></pre></div>
<div class="cell-output-display">
<div id="fig-relation-wboutine" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_05_cat_recap_files/figure-html/fig-relation-wboutine-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 2: Relationship between wellbeing and presence of routine</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#place plots adjacent to one another</span></span>
<span><span class="va">p1</span> <span class="op">|</span> <span class="va">p2</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="1_05_cat_recap_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From <a href="#fig-dist-routine">Figure&nbsp;1</a>, we can see that there are more individuals that do not have a routine than those who do.</p>
<p>From <a href="#fig-relation-wboutine">Figure&nbsp;2</a>, we can see that individuals with a routine tend to have higher wellbeing scores than those who do not.</p>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<ol type="1">
<li>Formally state:</li>
</ol>
<ul>
<li>your chosen significance level</li>
<li>the null and alternative hypotheses</li>
</ul>
<ol start="2" type="1">
<li>Fit the multiple regression model below using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, and assign it to an object named <code>mdl2</code>.</li>
</ol>
<p><span class="math display">\[
Wellbeing = \beta_0 + \beta_1 \cdot Routine + \beta_2 \cdot OutdoorTime + \epsilon
\]</span></p>
<p>Examine the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> output of the model.</p>
<p><span class="math inline">\(\hat \beta_0\)</span> (the intercept) is the estimated average wellbeing score associated with zero hours of weekly outdoor time and zero in the routine variable. What group is the intercept the estimated wellbeing score for when they have zero hours of outdoor time? Why (think about what zero in the routine variable means)?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>Effects will be considered statistically significant at <span class="math inline">\(\alpha=.05\)</span></p>
<p><span class="math inline">\(H_0: \beta_2 = 0\)</span></p>
<p>There is no association between well-being and time spent outdoors after taking into account the relationship between well-being and routine</p>
<p><span class="math inline">\(H_1: \beta_2 \neq 0\)</span></p>
<p>There is an association between well-being and time spent outdoors after taking into account the relationship between well-being and routine</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wellbeing</span> <span class="op">~</span>  <span class="va">routine</span> <span class="op">+</span> <span class="va">outdoor_time</span>, data <span class="op">=</span> <span class="va">mwdata</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl2</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ routine + outdoor_time, data = mwdata)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.3597  -5.7983   0.1047   7.2899  12.5957 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        33.5472     4.4263   7.579 2.35e-08 ***
routineNo Routine  -7.2947     3.2507  -2.244 0.032633 *  
outdoor_time        0.9152     0.2358   3.881 0.000552 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.06 on 29 degrees of freedom
Multiple R-squared:  0.4361,    Adjusted R-squared:  0.3972 
F-statistic: 11.21 on 2 and 29 DF,  p-value: 0.0002467</code></pre>
</div>
</div>
<p>As you can see in the output of the model, we have a coefficient called <code>routineNo Routine</code>. This is the parameter estimate for a dummy variable which has been inputted into the model. The <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function will automatically name the dummy variables (and therefore the coefficients) according to what level is identified by the 1. It names them <code>&lt;variable&gt;&lt;Level&gt;</code>, so we can tell that <code>routineNo Routine</code> is 1 for “No Routine” and 0 for “Routine”.</p>
<p>The intercept is therefore the estimated wellbeing score for those with a Routine and zero hours of outdoor time.</p>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>The researchers have decided that they would prefer ‘no routine’ to be considered the reference level for the “routine” variable instead of ‘routine’. Apply this change to the variable and re-run your model.</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You will need to use the <code><a href="https://rdrr.io/r/stats/relevel.html">relevel()</a></code> function here.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#re-order so that no routine is reference level</span></span>
<span><span class="va">mwdata</span><span class="op">$</span><span class="va">routine</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/relevel.html">relevel</a></span><span class="op">(</span><span class="va">mwdata</span><span class="op">$</span><span class="va">routine</span>, <span class="st">'No Routine'</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#re-run model and check summary</span></span>
<span><span class="va">mdl2_reorder</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wellbeing</span> <span class="op">~</span>  <span class="va">routine</span> <span class="op">+</span> <span class="va">outdoor_time</span>, data <span class="op">=</span> <span class="va">mwdata</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl2_reorder</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ routine + outdoor_time, data = mwdata)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.3597  -5.7983   0.1047   7.2899  12.5957 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     26.2525     3.9536   6.640  2.8e-07 ***
routineRoutine   7.2947     3.2507   2.244 0.032633 *  
outdoor_time     0.9152     0.2358   3.881 0.000552 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.06 on 29 degrees of freedom
Multiple R-squared:  0.4361,    Adjusted R-squared:  0.3972 
F-statistic: 11.21 on 2 and 29 DF,  p-value: 0.0002467</code></pre>
</div>
</div>
<p>You should now see that our routine variable is now showing <code>routineRoutine</code> instead of <code>routineNo Routine</code>. This means that 1 is now for “Routine” and 0 for “No Routine”.</p>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>We can visualise the model <span class="math inline">\(\widehat{Wellbeing} = \hat \beta_0 + \hat \beta_1 \cdot Routine + \hat \beta_2 \cdot OutdoorTime\)</span> as two lines.</p>
<p>Each line represents the model predicted values for wellbeing scores across the range of weekly outdoor time, with one line for those who report having “Routine” and one for those with “No Routine”.</p>
<p>Get a pen and paper, and sketch out the plot shown in <a href="#fig-annotate">Figure&nbsp;3</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-annotate" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_05_cat_recap_files/figure-html/fig-annotate-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 3: Multiple regression model: Wellbeing ~ Routine + Outdoor Time</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Annotate your plot with labels for each of parameter estimates from your model:</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 35%">
<col style="width: 36%">
</colgroup>
<thead><tr class="header">
<th>Parameter Estimate</th>
<th style="text-align: center;">Model Coefficient</th>
<th style="text-align: right;">Estimate</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\hat \beta_0\)</span></td>
<td style="text-align: center;"><code>(Intercept)</code></td>
<td style="text-align: right;">26.25</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\hat \beta_1\)</span></td>
<td style="text-align: center;"><code>routineRoutine</code></td>
<td style="text-align: right;">7.29</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat \beta_2\)</span></td>
<td style="text-align: center;"><code>outdoor_time</code></td>
<td style="text-align: right;">0.92</td>
</tr>
</tbody>
</table>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Below you can see where to add the labels, but we have not said which is which.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="1_05_cat_recap_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>A is the vertical distance between the red and blue lines (the lines are parallel, so this distance is the same wherever you cut it on the x-axis).<br>
</li>
<li>B is the point at which the blue line cuts the y-axis.<br>
</li>
<li>C is the vertical increase (increase on the y-axis) for the blue line associated with a 1 unit increase on the x-axis (the lines are parallel, so this is the same for the red line).</li>
</ul>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<ul>
<li>A = <span class="math inline">\(\hat \beta_2\)</span> = <code>routineRoutine</code> coefficient = 7.29</li>
<li>B = <span class="math inline">\(\hat \beta_0\)</span> = <code>(Intercept)</code> coefficient = 26.25</li>
<li>C = <span class="math inline">\(\hat \beta_1\)</span> = <code>outdoor_time</code> coefficient = 0.92</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="1_05_cat_recap_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Interpret your results in the context of the research question and report your model in full.</p>
<p>Provide key model results in a formatted table.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#create table for results</span></span>
<span><span class="fu">tab_model</span><span class="op">(</span><span class="va">mdl2_reorder</span>,</span>
<span>          dv.labels <span class="op">=</span> <span class="st">"Wellbeing (WEMWBS Scores)"</span>,</span>
<span>          pred.labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"routine"</span> <span class="op">=</span> <span class="st">"Routine"</span>,</span>
<span>                          <span class="st">"outdoor_time"</span> <span class="op">=</span> <span class="st">"Outdoor Time (hours per week)"</span><span class="op">)</span>,</span>
<span>          title <span class="op">=</span> <span class="st">"Regression Table for Wellbeing Model"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div id="tbl-modresults" class="anchored">

<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">Table 1:  Regression Table for Wellbeing Model </caption>
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">Wellbeing (WEMWBS Scores)</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">26.25</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">18.17&nbsp;–&nbsp;34.34</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">routineRoutine</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">7.29</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.65&nbsp;–&nbsp;13.94</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>0.033</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Outdoor Time (hours per<br>week)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.92</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.43&nbsp;–&nbsp;1.40</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">32</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.436 / 0.397</td>
</tr>
</tbody></table>
</div>
</div>
</div>
<p>And now lets write our results up:</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Full regression results including 95% Confidence Intervals are shown in <a href="#tbl-modresults">Table&nbsp;1</a>. The <span class="math inline">\(F\)</span>-test for model utility was significant <span class="math inline">\((F(2,29) = 11.21, p&lt;.001)\)</span>, and the model explained approximately 39.72% of the variability in wellbeing scores.</p>
<p>After controlling for routine, there was a significant association between wellbeing scores and outdoor time <span class="math inline">\((\beta = 0.92, SE = 0.24, p &lt; .001)\)</span>. This suggested that for every additional hour of outdoor time, wellbeing scores, on average, were higher by 0.92 points (<span class="math inline">\(CI_{95}[0.43 - 1.40]\)</span>). Therefore, we have evidence to reject the null hypothesis (that there was no association between well-being and time spent outdoors after taking into account the relationship between well-being and routine).</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="section-b-weeks-1---4-recap" class="level1"><h1>Section B: Weeks 1 - 4 Recap</h1>
<p>In the second part of the lab, there is no new content - the purpose of the recap section is for you to revisit and revise the concepts you have learned over the last 4 weeks.</p>
<div class="red">
<p>Before you expand each of the boxes below, think about how comfortable you feel with each concept.</p>
</div>
<div class="optional-begin">
<span id="opt-start-8" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-8', 'opt-start-8')"> <span class="olab">Types of Models: Deterministic vs Statistical</span></span>
</div>
<div id="opt-body-8" class="optional-body" style="display: none;">
<section id="deterministic-example-perimeter-side" class="level4"><h4 class="anchored" data-anchor-id="deterministic-example-perimeter-side"><strong>Deterministic (<em>Example: Perimeter &amp; Side</em>)</strong></h4>
<p>The mathematical model</p>
<p><span class="math display">\[
Perimeter = 4 * Side
\]</span></p>
<p>or, equivalently,</p>
<p><span class="math display">\[
y = 4 * x
\]</span></p>
<p>represents the relationship between side and perimeter of squares. This is an example of a <em>deterministic model</em> as it is a model of an <em>exact relationship</em> - there can be no deviation.</p>
</section><section id="statistical-example-height-handspan" class="level4"><h4 class="anchored" data-anchor-id="statistical-example-height-handspan"><strong>Statistical (<em>Example: Height &amp; Handspan</em>)</strong></h4>
<p>The relationship between height and handspan shows deviations from the ‘average pattern’. Hence, we need to create a model that allows for deviations from the linear relationship - we need a <em>statistical model</em>.</p>
<p>A statistical model includes <em>both</em> a deterministic function and a random error term:</p>
<p><span class="math display">\[
Handspan = \beta_0 + \beta_1 * Height + \epsilon
\]</span></p>
<p>or, in short,</p>
<p><span class="math display">\[
y = \underbrace{\beta_0 + \beta_1 * x}_{\text{function of }x} + \underbrace{\epsilon}_{\text{random error}}
\]</span></p>
<p>The deterministic function need not be linear if the scatterplot displays signs of nonlinearity.</p>
<p>In the equation above, the terms <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are numbers specifying where the line going through the data meets the y-axis and its slope (direction and gradient of line).</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2223/labs/1_01_function.html">Week 1 lab</a> and lectures for further details and to revise these concepts further.</p>
</div>
</div>
</section>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-9" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-9', 'opt-start-9')"> <span class="olab">Null &amp; Alternative Hypotheses</span></span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p>Recall that statistical hypotheses are testable mathematical statements.</p>
<p>We need to define a null (<span class="math inline">\(H_0\)</span>) and alternative (<span class="math inline">\(H_1\)</span>) hypothesis.</p>
<p>Points to note:</p>
<ul>
<li>We can only ever test the null (<span class="math inline">\(H_0\)</span>), so all statements must be made in reference to this</li>
<li>We can only ever reject or fail to reject the null (we can <strong>never</strong> accept a hypothesis)</li>
</ul>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-10" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-10', 'opt-start-10')"> <span class="olab">Simple Linear Regression</span></span>
</div>
<div id="opt-body-10" class="optional-body" style="display: none;">
<p><strong>Formula:</strong></p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]</span></p>
<p>In <strong>R</strong>:</p>
<div class="blue">
<p>There are basically two pieces of information that we need to pass to the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function:</p>
<ol type="1">
<li>The formula: The regression formula should be specified in the form <code>y ~ x</code> where <span class="math inline">\(y\)</span> is the dependent variable (DV) and <span class="math inline">\(x\)</span> the independent variable (IV).</li>
<li>The data: Specify which dataframe contains the variables specified in the formula.</li>
</ol>
<ul>
<li>run simple linear regression via <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">model_name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">DV</span> <span class="op">~</span> <span class="va">IV</span>, data <span class="op">=</span> <span class="va">data_name</span><span class="op">)</span></span></code></pre></div>
</div>
<p><strong>OR</strong></p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">model_name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">data_name</span><span class="op">$</span><span class="va">DV</span> <span class="op">~</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2223/labs/1_02_slr.html">Week 2 lab</a> and lectures for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-11" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-11', 'opt-start-11')"> <span class="olab">Multiple Linear Regression</span></span>
</div>
<div id="opt-body-11" class="optional-body" style="display: none;">
<p><strong>Formula:</strong></p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon_i
\]</span></p>
<p>In <strong>R</strong>:</p>
<div class="blue">
<p>Multiple and simple linear regression follow the same structure within the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function. You simply add (using the <code>+</code> sign) more independent variables.</p>
<ul>
<li>run multiple linear regression (example includes three independent variables) via <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">model_name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">DV</span> <span class="op">~</span> <span class="va">IV1</span> <span class="op">+</span> <span class="va">IV2</span> <span class="op">+</span> <span class="va">IV3</span>, data <span class="op">=</span> <span class="va">data_name</span><span class="op">)</span></span></code></pre></div>
</div>
<p><strong>OR</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>model_name <span class="ot">&lt;-</span> <span class="fu">lm</span>(data_name<span class="sc">$</span>DV <span class="sc">~</span> data_name<span class="sc">$</span>IV1 <span class="sc">+</span> data_name<span class="sc">$</span>IV2 <span class="sc">+</span> data_name<span class="sc">$</span>IV3</span></code></pre></div>
</div>
</div>
<p><strong>Interpretation of Multiple Regression Coefficients</strong></p>
<p>You’ll hear a lot of different ways that people explain multiple regression coefficients.</p>
<p>For the model <span class="math inline">\(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon\)</span>, the estimate <span class="math inline">\(\hat \beta_1\)</span> will often be reported as:</p>
<p>the increase in <span class="math inline">\(y\)</span> for a one unit increase in <span class="math inline">\(x_1\)</span> when…</p>
<ul>
<li>holding the effect of <span class="math inline">\(x_2\)</span> constant.</li>
<li>controlling for differences in <span class="math inline">\(x_2\)</span>.</li>
<li>partialling out the effects of <span class="math inline">\(x_2\)</span>.</li>
<li>holding <span class="math inline">\(x_2\)</span> equal.</li>
<li>accounting for effects of <span class="math inline">\(x_2\)</span>.</li>
</ul>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2223/labs/1_03_mlr.html">Week 3 lab</a> and lectures for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-12" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-12', 'opt-start-12')"> <span class="olab">Partitioning Variation: Sum of Squares</span></span>
</div>
<div id="opt-body-12" class="optional-body" style="display: none;">
<section id="sum-of-squares" class="level3"><h3 class="anchored" data-anchor-id="sum-of-squares"><strong>Sum of Squares</strong></h3>
<p>The sum of squares measures the deviation or variation of data points away from the mean (i.e., how spread out are the numbers in a given dataset). We are trying to find the equation/function that best fits our data by varying the least from our data points.</p>
<section id="total-sum-of-squares" class="level4"><h4 class="anchored" data-anchor-id="total-sum-of-squares"><strong>Total Sum of Squares</strong></h4>
<p><strong>Formula</strong>:</p>
<p><span class="math display">\[SS_{Total} = \sum_{i=1}^{n}(y_i - \bar{y})^2\]</span></p>
<p><strong>In words</strong>:</p>
<p>Squared distance of each data point from the mean of <span class="math inline">\(y\)</span>.</p>
<p><strong>Description</strong>:</p>
<p>How much variation there is in the DV.</p>
</section><section id="residual-sum-of-squares" class="level4"><h4 class="anchored" data-anchor-id="residual-sum-of-squares"><strong>Residual Sum of Squares</strong></h4>
<p><strong>Formula</strong>:</p>
<p><span class="math display">\[SS_{Residual} = \sum_{i=1}^{n}(y_i - \hat{y}_i)^2\]</span></p>
<p><strong>In words</strong>:</p>
<p>Squared distance of each point from the predicted value.</p>
<p><strong>Description</strong>:</p>
<p>How much of the variation in the DV the model did not explain - a measure that captures the unexplained variation in your regression model. Lower residual sum of squares suggests that your model fits the data well, and higher suggests that the model poorly explains the data (in other words, the lower the value, the better the regression model). If the value was zero here, it would suggest the model fits perfectly with no error.</p>
</section><section id="model-sum-of-squares" class="level4"><h4 class="anchored" data-anchor-id="model-sum-of-squares"><strong>Model Sum of Squares</strong></h4>
<p><strong>Formula</strong>:</p>
<p><span class="math display">\[SS_{Model} = \sum_{i=1}^{n}(\hat{y}_i - \bar{y})^2\]</span></p>
<p>Can also be derived from:</p>
<p><span class="math display">\[SS_{Model} = SS_{Total} - SS_{Residual}\]</span></p>
<p><strong>In words</strong>:</p>
<p>The deviance of the predicted scores from the mean of <span class="math inline">\(y\)</span>.</p>
<p><strong>Description</strong>:</p>
<p>How much of the variation in the DV your model explained - like a measure that captures how well the regression line fits your data.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2223/labs/1_03_mlr.html">Week 3 lab</a> &amp; <a href="https://uoepsy.github.io/dapr2/2223/labs/1_04_model_fit.html">Week 4 lab</a> and lectures for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</section></section>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-13" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-13', 'opt-start-13')"> <span class="olab">F-test &amp; F-ratio</span></span>
</div>
<div id="opt-body-13" class="optional-body" style="display: none;">
<p><strong>Formula</strong>:</p>
<p><span class="math display">\[
F_{df_{model},df_{residual}} = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model}/df_{Model}}{SS_{Residual}/df_{Residual}} \\
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; df_{model} = k \\
&amp; df_{residual} = n-k-1 \\
&amp; n = \text{sample size} \\
&amp; k  = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
<p><strong>Description</strong>:</p>
<p>To test the significance of an overall model, we can conduct an <span class="math inline">\(F\)</span>-test. The <span class="math inline">\(F\)</span>-test compares your model to a model containing zero predictor variables (i.e., the intercept only model), and tests whether your added predictor variables significantly improved the model.</p>
<p>The <span class="math inline">\(F\)</span>-test involves testing the statistical significance of the <span class="math inline">\(F\)</span>-ratio. Q: What does the <span class="math inline">\(F\)</span>-ratio test? A: The null hypothesis that all regression slopes in a model are zero (i.e., explain no variance in your outcome/DV).</p>
<p><em>Points to note</em>:</p>
<ul>
<li>The larger your <span class="math inline">\(F\)</span>-ratio, the better your model</li>
<li>The <span class="math inline">\(F\)</span>-ratio will be close to 1 when the null is true (i.e., that all slopes are zero)</li>
</ul>
<p><strong>Interpretation</strong>:</p>
<p>If your model predictors do explain some variance, the <span class="math inline">\(F\)</span>-ratio will be significant, and you would reject the null, as this would suggest that your predictor variables included in your model improved the model fit (in comparison to the intercept only model).</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2223/labs/1_04_model_fit.html">Week 4 lab</a> and lectures for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-14" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-14', 'opt-start-14')"> <span class="olab">R-squared and Adjusted R-squared</span></span>
</div>
<div id="opt-body-14" class="optional-body" style="display: none;">
<p><span class="math inline">\(R^2\)</span> represents the proportion of variance in <span class="math inline">\(Y\)</span> that is explained by the model.</p>
<p>The <span class="math inline">\(R\)</span>-squared coefficient is defined as:</p>
<p><span class="math display">\[
R^2 = \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\]</span></p>
<p>The Adjusted <span class="math inline">\(R\)</span>-squared coefficient is defined as:</p>
<p><span class="math display">\[
\hat R^2 = 1 - \frac{(1 - R^2)(n-1)}{n-k-1}
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; n = \text{sample size} \\
&amp; k = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
<p>We can see the Multiple and Adjusted <span class="math inline">\(R\)</span>-squared in the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> output of a model.</p>
<p>Points to note:</p>
<ul>
<li>Adjusted-<span class="math inline">\(R^2\)</span> adjusts for the number of terms in a model, and should be used when there are 2 or more predictors in the model</li>
<li>Adjusted-<span class="math inline">\(R^2\)</span> should always be less than or equal to <span class="math inline">\(R^2\)</span>
</li>
</ul>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2223/labs/1_04_model_fit.html">Week 4 lab</a> and lectures for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-15" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-15', 'opt-start-15')"> <span class="olab">Standardisation</span></span>
</div>
<div id="opt-body-15" class="optional-body" style="display: none;">
<p><strong><span class="math inline">\(z\)</span>-score Formula:</strong></p>
<p><span class="math display">\[
z_x = \frac{x - \bar{x}}{s_x}, \qquad z_y = \frac{y - \bar{y}}{s_y}
\]</span></p>
<p>Recall that a standardized variable has mean of 0 and standard deviation of 1.</p>
<p>In <strong>R</strong>:</p>
<div class="blue">
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#create z-scored variables</span></span>
<span><span class="va">dataframe</span> <span class="op">&lt;-</span> <span class="va">dataframe</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>   z_variable <span class="op">=</span> <span class="op">(</span><span class="va">variable</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">variable</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">variable</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span></code></pre></div>
</div>
<p><strong>OR</strong></p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#use scale function</span></span>
<span><span class="va">model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">DV</span><span class="op">)</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">IV</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">dataset</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2223/labs/1_04_model_fit.html">Week 4 lab</a> and lectures for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-16" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-16', 'opt-start-16')"> <span class="olab">Binary Variables</span></span>
</div>
<div id="opt-body-16" class="optional-body" style="display: none;">
<p><strong>Binary predictors in linear regression</strong></p>
<p>We can include categorical predictors in a linear regression, but the interpretation of the coefficients is very specific. Whereas we talked about coefficients being interpreted as “the change in <span class="math inline">\(y\)</span> associated with a 1-unit increase in <span class="math inline">\(x\)</span>”, for categorical explanatory variables, coefficients can be considered to examine differences in group means. However, they are actually doing exactly the same thing - the model is simply translating the levels (like “Yes”/“No”) in to 0s and 1s!</p>
<p>Our coefficients are just the same as before. The intercept is where our predictor equals zero, and the slope is the change in our outcome variable associated with a 1-unit change in our predictor.</p>
<p>However, “zero” for this predictor variable now corresponds to a whole level. This is known as the “reference level”. Accordingly, the 1-unit change in our predictor (the move from “zero” to “one”) corresponds to the difference between the two levels.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See <a href="https://uoepsy.github.io/dapr2/2223/labs/1_05_cat_recap.html">Week 5 lab</a> and lectures for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-17" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-17', 'opt-start-17')"> <span class="olab">Categorical Predictors with k levels</span></span>
</div>
<div id="opt-body-17" class="optional-body" style="display: none;">
<p>We saw that a <em>binary categorical</em> variable gets inputted into our model as a variable of 0s and 1s (these typically get called <strong>“dummy variables”</strong>).</p>
<div class="statbox">
<p><strong>Dummy variables</strong> are numeric variables that represent categorical data.</p>
</div>
<p>When we have a <em>categorical</em> explanatory variable with <strong>more than 2 levels</strong>, our model gets a bit more - it needs not just one, but <em>a number of</em> dummy variables. For a categorical variable with <span class="math inline">\(k\)</span> levels, we can express it in <span class="math inline">\(k-1\)</span> dummy variables.</p>
<p>For example, the “species” column below has three levels, and can be expressed by the two variables “species_dog” and “species_parrot”:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  species species_dog species_parrot
1     cat           0              0
2     cat           0              0
3     dog           1              0
4  parrot           0              1
5     dog           1              0
6     cat           0              0
7     ...         ...            ...</code></pre>
</div>
</div>
<ul>
<li>The “cat” level is expressed whenever both the “species_dog” and “species_parrot” variables are 0.</li>
<li>The “dog” level is expressed whenever the “species_dog” variable is 1 and the “species_parrot” variable is 0.</li>
<li>The “parrot” level is expressed whenever the “species_dog” variable is 0 and the “species_parrot” variable is 1.</li>
</ul>
<p><code>R</code> will do all of this re-expression for us. If we include in our model a categorical explanatory variable with 4 different levels, the model will estimate 3 parameters - one for each dummy variable. We can interpret the parameter estimates (the coefficients we obtain using <code><a href="https://rdrr.io/r/stats/coef.html">coefficients()</a></code>,<code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code> or <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>) as the estimated increase in the outcome variable associated with an increase of one in each dummy variable (holding all other variables equal).</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 27%">
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 16%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">&nbsp;</th>
<th style="text-align: center;">Estimate</th>
<th style="text-align: center;">Std. Error</th>
<th style="text-align: center;">t value</th>
<th style="text-align: center;">Pr(&gt;|t|)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>(Intercept)</strong></td>
<td style="text-align: center;">60.28</td>
<td style="text-align: center;">1.209</td>
<td style="text-align: center;">49.86</td>
<td style="text-align: center;">5.273e-39</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>speciesdog</strong></td>
<td style="text-align: center;">-11.47</td>
<td style="text-align: center;">1.71</td>
<td style="text-align: center;">-6.708</td>
<td style="text-align: center;">3.806e-08</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>speciesparrot</strong></td>
<td style="text-align: center;">-4.916</td>
<td style="text-align: center;">1.71</td>
<td style="text-align: center;">-2.875</td>
<td style="text-align: center;">0.006319</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Note that in the above example, an increase in 1 of “species_dog” is the difference between a “cat” and a “dog”. An increase in one of “species_parrot” is the difference between a “cat” and a “parrot”. We think of the “cat” category in this example as the <em>reference level</em> - it is the category against which other categories are compared against.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="1_05_cat_recap_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 5 lectures for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-18" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-18', 'opt-start-18')"> <span class="olab">Steps Involved in Modelling</span></span>
</div>
<div id="opt-body-18" class="optional-body" style="display: none;">
<p>You can think of the sequence of steps involved in statistical modeling as:</p>
<p><span class="math display">\[
\text{Choose} \rightarrow \text{Fit} \rightarrow \text{Assess} \rightarrow \text{Use}
\]</span></p>
<div class="frame">
<strong>A general rule</strong><br><br><center>
Do not use (draw inferences or predictions from) a model before you have <strong>assessed</strong> whether the model satisfies the underlying assumptions
</center>
</div>
<p><br> Throughout this block, we have completed the first three steps (<strong>Choose</strong>, <strong>Fit</strong>, and <strong>Use</strong>) in that we have:</p>
<ol type="1">
<li>Explored/visualised our data and specified our model</li>
<li>Fitted the model in <code>R</code><br>
</li>
<li>Interpreted our parameter estimates</li>
</ol>
<p>Please note that when conducting real analyses, it would be inappropriate to complete these steps without also <strong>assessing</strong> whether a regression model meets the assumptions. You will learn how to do this in Block 2 of Semester 1 for linear regression models.</p>
</div>
<p class="optional-end">
</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
      <div class="nav-footer-center">© Copyright 2019-2022 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
  </div>
</footer>


</body></html>