<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Interactions I: Num x Cat</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR2</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intro-to-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Intro to Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intro-to-linear-models">
<li>
    <a class="dropdown-item" href="./1_01_function.html">
 <span class="dropdown-text">1/1: Functions and Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_slr.html">
 <span class="dropdown-text">1/2: Intro to Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_mlr.html">
 <span class="dropdown-text">1/3: Multiple Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_model_fit.html">
 <span class="dropdown-text">1/4: Model Fit and Standardization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_05_cat_recap.html">
 <span class="dropdown-text">1/5: Cat Predictors &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">More Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more-linear-models">
<li class="dropdown-header">1/7: Interactions I: Num x Cat</li>
        <li class="dropdown-header">1/8: Interactions II: Num x Num</li>
        <li class="dropdown-header">1/9: Interactions III: Cat x Cat</li>
        <li class="dropdown-header">1/10: Assumptions &amp; Diagnostics</li>
        <li class="dropdown-header">1/11: Recap &amp; Write Up</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysing-experimental-studies" role="button" data-bs-toggle="dropdown" aria-expanded="false">Analysing Experimental Studies</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysing-experimental-studies">
<li class="dropdown-header">2/1: Functions and Models</li>
        <li class="dropdown-header">2/2: Intro to Linear Regression</li>
        <li class="dropdown-header">2/3: More Linear Regression</li>
        <li class="dropdown-header">2/4: Multiple Predictors</li>
        <li class="dropdown-header">2/5: Recap &amp; Write Up</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-topics-for-lm" role="button" data-bs-toggle="dropdown" aria-expanded="false">Advanced Topics for LM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-topics-for-lm">
<li class="dropdown-header">2/6: Functions and Models</li>
        <li class="dropdown-header">2/7: Intro to Linear Regression</li>
        <li class="dropdown-header">2/8: More Linear Regression</li>
        <li class="dropdown-header">2/9: Multiple Predictors</li>
        <li class="dropdown-header">2/10: Recap &amp; Write Up</li>
    </ul>
</li>
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#study-overview" id="toc-study-overview" class="nav-link active" data-scroll-target="#study-overview">Study Overview</a></li>
  <li>
<a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a>
  <ul class="collapse">
<li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Interactions I: Num x Cat</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand the concept of an interaction.</li>
<li>Be able to interpret the meaning of a numeric <span class="math inline">\(\times\)</span> categorical interaction.</li>
<li>Understand the principle of marginality and why this impacts modelling choices with interactions.</li>
<li>Visualize and probe interactions.</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed all labs from Block 1 Semester 1 (Weeks 1 - 5)</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>psych</strong></li>
<li><strong>sjPlot</strong></li>
<li><strong>patchwork</strong></li>
<li><strong>kableExtra</strong></li>
<li><strong>plotly</strong></li>
<li><strong>pander</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/wellbeing_rural.csv">here</a> or read it in via this link https://uoepsy.github.io/data/wellbeing_rural.csv.</p>
</section>
</div>
<section id="study-overview" class="level1"><h1>Study Overview</h1>
<blockquote class="blockquote">
<p><strong>Research Question</strong></p>
<p>Does the association between number of social interactions and wellbeing differ between rural and non-rural residents?</p>
</blockquote>
<p>Researchers were specifically interested in how the number of social interactions might influence mental health and wellbeing differently for those living in rural communities compared to those in cities and suburbs. They want to assess whether the effect of social interactions on wellbeing <em>is moderated by</em> (depends upon) whether or not a person lives in a rural area.</p>
<p>To investigate how the association between the number of social interactions and mental wellbeing might be different for those living in rural communities, the researchers conducted a study, where they collected data from 200 randomly selected residents of the Edinburgh &amp; Lothian postcodes.</p>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Wellbeing/Rurality data codebook.</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>From the Edinburgh &amp; Lothians, 100 city/suburb residences and 100 rural residences were chosen at random and contacted to participate in the study. The Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), was used to measure mental health and well-being.</p>
<p>Participants filled out a questionnaire including items concerning: estimated average number of hours spent outdoors each week, estimated average number of social interactions each week (whether on-line or in-person), whether a daily routine is followed (yes/no). For those respondents who had an activity tracker app or smart watch, they were asked to provide their average weekly number of steps.</p>
<p>The data in <code>wellbeing.csv</code> contain seven attributes collected from a random sample of <span class="math inline">\(n=200\)</span> hypothetical residents over Edinburgh &amp; Lothians, and include:</p>
<ul>
<li>
<code>wellbeing</code>: Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br>
</li>
<li>
<code>outdoor_time</code>: Self report estimated number of hours per week spent outdoors<br>
</li>
<li>
<code>social_int</code>: Self report estimated number of social interactions per week (both online and in-person)</li>
<li>
<code>routine</code>: Binary 1=Yes/0=No response to the question “Do you follow a daily routine throughout the week?”</li>
<li>
<code>location</code>: Location of primary residence (City, Suburb, Rural)</li>
<li>
<code>steps_k</code>: Average weekly number of steps in thousands (as given by activity tracker if available)</li>
<li>
<code>age</code>: Age in years of respondent</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 200 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): location
dbl (6): age, outdoor_time, social_int, routine, wellbeing, steps_k

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output-display">

<div id="xpqxkbfqhg" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#xpqxkbfqhg .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xpqxkbfqhg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xpqxkbfqhg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xpqxkbfqhg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xpqxkbfqhg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xpqxkbfqhg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xpqxkbfqhg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xpqxkbfqhg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xpqxkbfqhg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xpqxkbfqhg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xpqxkbfqhg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xpqxkbfqhg .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#xpqxkbfqhg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xpqxkbfqhg .gt_from_md > :first-child {
  margin-top: 0;
}

#xpqxkbfqhg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xpqxkbfqhg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xpqxkbfqhg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#xpqxkbfqhg .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#xpqxkbfqhg .gt_row_group_first td {
  border-top-width: 2px;
}

#xpqxkbfqhg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xpqxkbfqhg .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#xpqxkbfqhg .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#xpqxkbfqhg .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xpqxkbfqhg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xpqxkbfqhg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xpqxkbfqhg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xpqxkbfqhg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xpqxkbfqhg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xpqxkbfqhg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xpqxkbfqhg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xpqxkbfqhg .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xpqxkbfqhg .gt_left {
  text-align: left;
}

#xpqxkbfqhg .gt_center {
  text-align: center;
}

#xpqxkbfqhg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xpqxkbfqhg .gt_font_normal {
  font-weight: normal;
}

#xpqxkbfqhg .gt_font_bold {
  font-weight: bold;
}

#xpqxkbfqhg .gt_font_italic {
  font-style: italic;
}

#xpqxkbfqhg .gt_super {
  font-size: 65%;
}

#xpqxkbfqhg .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#xpqxkbfqhg .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#xpqxkbfqhg .gt_indent_1 {
  text-indent: 5px;
}

#xpqxkbfqhg .gt_indent_2 {
  text-indent: 10px;
}

#xpqxkbfqhg .gt_indent_3 {
  text-indent: 15px;
}

#xpqxkbfqhg .gt_indent_4 {
  text-indent: 20px;
}

#xpqxkbfqhg .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">age</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">outdoor_time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">social_int</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">routine</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">wellbeing</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">location</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">steps_k</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_right">28</td>
<td class="gt_row gt_right">12</td>
<td class="gt_row gt_right">13</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">36</td>
<td class="gt_row gt_left">rural</td>
<td class="gt_row gt_right">21.6</td>
</tr>
<tr>
<td class="gt_row gt_right">56</td>
<td class="gt_row gt_right">5</td>
<td class="gt_row gt_right">15</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">41</td>
<td class="gt_row gt_left">rural</td>
<td class="gt_row gt_right">12.3</td>
</tr>
<tr>
<td class="gt_row gt_right">25</td>
<td class="gt_row gt_right">19</td>
<td class="gt_row gt_right">11</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">35</td>
<td class="gt_row gt_left">rural</td>
<td class="gt_row gt_right">49.8</td>
</tr>
<tr>
<td class="gt_row gt_right">60</td>
<td class="gt_row gt_right">25</td>
<td class="gt_row gt_right">15</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">35</td>
<td class="gt_row gt_left">rural</td>
<td class="gt_row gt_right">NA</td>
</tr>
<tr>
<td class="gt_row gt_right">19</td>
<td class="gt_row gt_right">9</td>
<td class="gt_row gt_right">18</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">32</td>
<td class="gt_row gt_left">rural</td>
<td class="gt_row gt_right">48.1</td>
</tr>
<tr>
<td class="gt_row gt_right">34</td>
<td class="gt_row gt_right">18</td>
<td class="gt_row gt_right">13</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">34</td>
<td class="gt_row gt_left">rural</td>
<td class="gt_row gt_right">67.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section><section id="setup" class="level1"><h1>Setup</h1>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the wellbeing_rural dataset into R, assigning it to an object named <code>wrdata</code>
</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#Loading the required package(s)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://personality-project.org/r/psych/">psych</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://strengejacke.github.io/sjPlot/">sjPlot</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span> </span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://plotly-r.com">plotly</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://rapporter.github.io/pander/">pander</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co">#Reading in data and storing in object named 'wrdata'</span></span>
<span><span class="va">wrdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/wellbeing_rural.csv"</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<section id="exercises" class="level2"><h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Formally state:</p>
<ul>
<li>a linear model to investigate if the association between wellbeing and social interactions differs among rural and non-rural residents</li>
<li>your chosen significance level</li>
<li>the null and alternative hypotheses</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="quote">
<p>“Except in special circumstances, a model including a product term for interaction between two explanatory variables should also include terms with each of the explanatory variables individually, even though their coefficients may not be significantly different from zero. Following this rule avoids the logical inconsistency of saying that the effect of <span class="math inline">\(X_1\)</span> depends on the level of <span class="math inline">\(X_2\)</span> but that there is no effect of <span class="math inline">\(X_1\)</span>.”<br>
— <span class="citation" data-cites="Ramsey2012">Ramsey and Schafer (<a href="#ref-Ramsey2012" role="doc-biblioref">2012</a>)</span></p>
</div>
<div class="solution-begin">
<span id="sol-start-3" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>To address the research question, we are going to fit the following model, where <span class="math inline">\(y\)</span> = wellbeing; <span class="math inline">\(x_1\)</span> = social interactions; and <span class="math inline">\(x_2\)</span> = whether or not the respondent lives in a rural location.</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1  x_1 + \beta_2  x_2 + \beta_3 (x_1 \cdot x_2) + \epsilon \\
\quad \\ \text{where} \quad \epsilon \sim N(0, \sigma) \quad \text{independently}
\]</span></p>
<p>or</p>
<p><span class="math display">\[
\widehat{Wellbeing} = \hat \beta_0 + \hat \beta_1 \cdot Social Interactions + \hat \beta_2 \cdot Location  + \hat \beta_3 \cdot (Social Interactions \cdot Location)  
\]</span></p>
<p>Effects will be considered statistically significant at <span class="math inline">\(\alpha=.05\)</span></p>
<p>Our hypotheses are:</p>
<p><span class="math inline">\(H_0: \beta_3 = 0\)</span></p>
<p>The association between wellbeing and social interactions is not moderated by whether or not a person lives in a rural area.</p>
<p><span class="math inline">\(H_1: \beta_3 \neq 0\)</span></p>
<p>The association between wellbeing and social interactions is moderated by whether or not a person lives in a rural area.</p>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Check coding of variables (e.g., that categorical variables are coded as factors).</p>
<p>Note that the “location” variable currently has three levels (Rural/Suburb/City), but we only want two (Rural/Not Rural) in order to address our research question, so you’ll need to fix this. One way to do this would be to use <code><a href="https://rdrr.io/r/base/ifelse.html">ifelse()</a></code> to define a variable which takes one value (“Rural”) if the observation meets from some condition, or another value (“Not Rural”) if it does not.</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Type <code><a href="https://rdrr.io/r/base/ifelse.html">?ifelse</a></code> in the <em>console</em> if you want to see the help function. You can use it to add a new variable either inside <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>, or using <code>data$new_variable_name &lt;- ifelse(test, x, y)</code> syntax.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>Create a new variable for Rural/Not Rural:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">wrdata</span> <span class="op">&lt;-</span> <span class="va">wrdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    isRural <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">location</span> <span class="op">==</span> <span class="st">"rural"</span>, <span class="st">"rural"</span>, <span class="st">"not rural"</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
</div>
<p>Check coding of variables within <code>wrdata</code> and ensure <code>isRural</code> is a factor with two levels, ‘rural’ and ‘not rural’:</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">wrdata</span><span class="op">)</span> <span class="co">#overall 'structure of data. Or could run is.factor()</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [200 × 8] (S3: tbl_df/tbl/data.frame)
 $ age         : num [1:200] 28 56 25 60 19 34 41 41 35 53 ...
 $ outdoor_time: num [1:200] 12 5 19 25 9 18 17 11 12 13 ...
 $ social_int  : num [1:200] 13 15 11 15 18 13 19 12 13 15 ...
 $ routine     : num [1:200] 1 1 1 0 1 1 1 1 0 1 ...
 $ wellbeing   : num [1:200] 36 41 35 35 32 34 39 43 35 37 ...
 $ location    : chr [1:200] "rural" "rural" "rural" "rural" ...
 $ steps_k     : num [1:200] 21.6 12.3 49.8 NA 48.1 67.3 1.9 50.9 NA 35.5 ...
 $ isRural     : chr [1:200] "rural" "rural" "rural" "rural" ...</code></pre>
</div>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">wrdata</span><span class="op">$</span><span class="va">isRural</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">wrdata</span><span class="op">$</span><span class="va">isRural</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Visualise your data.</p>
<p>In particular:</p>
<ol type="1">
<li>Explore the associations among the variables included in your analysis</li>
<li>Produce a visualisation of the association between weekly number of social interactions and well-being, with separate <em>facets</em> for rural vs non-rural respondents</li>
</ol>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>The <code><a href="https://rdrr.io/pkg/psych/man/pairs.panels.html">pairs.panels()</a></code> function from the <code>psych</code> package will plot all variables in a dataset against one another. This will save you the time you would have spent creating individual plots.</p></li>
<li><p>Within your <code>ggplot</code> argument, you will need to specify <code>+ facet_wrap()</code></p></li>
</ol>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>Let’s first plot the variables included within our model (note that we could use this for the whole dataset, but we don’t want to include irrelevant variables):</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">wrdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">wellbeing</span>, <span class="va">social_int</span>, <span class="va">isRural</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/psych/man/pairs.panels.html">pairs.panels</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="1_07_int1_nc_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Next, lets produce our plots with a facet for rural vs non-rural residents:</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">wrdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">social_int</span>, y <span class="op">=</span> <span class="va">wellbeing</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span><span class="va">isRural</span><span class="op">)</span> </span></code></pre></div>
<div class="cell-output-display">
<p><img src="1_07_int1_nc_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Fit your model using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, and assign it as an object with the name “rural_mod”.</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>When fitting a regression model in <code>R</code> with two explanatory variables A and B, and their interaction, these two are equivalent:</p>
<ul>
<li>y ~ A + B + A:B</li>
<li>y ~ A*B</li>
</ul>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#fit model including interaction between social_int and isRural</span></span>
<span><span class="va">rural_mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wellbeing</span> <span class="op">~</span>  <span class="va">social_int</span> <span class="op">*</span> <span class="va">isRural</span>, data <span class="op">=</span> <span class="va">wrdata</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#check model output</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">rural_mod</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wellbeing ~ social_int * isRural, data = wrdata)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.4845  -2.7975   0.0155   2.4539  15.6743 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  32.3851     1.4719  22.003  &lt; 2e-16 ***
social_int                    0.1312     0.1123   1.168  0.24416    
isRuralnot rural             -1.3866     2.0510  -0.676  0.49981    
social_int:isRuralnot rural   0.5176     0.1615   3.206  0.00157 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.558 on 196 degrees of freedom
Multiple R-squared:  0.2962,    Adjusted R-squared:  0.2854 
F-statistic: 27.49 on 3 and 196 DF,  p-value: 6.97e-15</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="statbox">
<p><strong>Interpreting coefficients for A and B in the presence of an interaction A:B</strong></p>
<p>When you include an interaction between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> in a regression model, you are estimating the extent to which the effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> is different across the values of <span class="math inline">\(x_2\)</span>.</p>
<p>What this means is that the effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> <em>depends on/is conditional upon</em> the value of <span class="math inline">\(x_2\)</span>.<br>
(and vice versa, the effect of <span class="math inline">\(x_2\)</span> on <span class="math inline">\(y\)</span> is different across the values of <span class="math inline">\(x_1\)</span>).<br>
This means that we can no longer talk about the “effect of <span class="math inline">\(x_1\)</span> <em>holding <span class="math inline">\(x_2\)</span> constant</em>”. Instead we can talk about a <em>marginal effect</em> of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> at a specific value of <span class="math inline">\(x_2\)</span>.</p>
<div class="frame">
<p>When we fit the model <span class="math inline">\(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 (x_1 \cdot x_2) + \epsilon\)</span> using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>:</p>
<ul>
<li>the parameter estimate <span class="math inline">\(\hat \beta_1\)</span> is the <em>marginal effect</em> of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> where <span class="math inline">\(x_2 = 0\)</span><br>
</li>
<li>the parameter estimate <span class="math inline">\(\hat \beta_2\)</span> is the <em>marginal effect</em> of <span class="math inline">\(x_2\)</span> on <span class="math inline">\(y\)</span> where <span class="math inline">\(x_1 = 0\)</span><br>
</li>
</ul>
</div>
<div style="margin-left: 15px">
<p><small> <strong>N.B.</strong> Regardless of whether or not there is an interaction term in our model, all parameter estimates in multiple regression are “conditional” in the sense that they are dependent upon the inclusion of other variables in the model. For instance, in <span class="math inline">\(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon\)</span> the coefficient <span class="math inline">\(\hat \beta_1\)</span> is conditional upon holding <span class="math inline">\(x_2\)</span> constant. </small></p>
</div>
</div>
<div class="statbox">
<p><strong>Interpreting the interaction term A:B</strong></p>
<p>The coefficient for an interaction term can be thought of as providing an <em>adjustment to the slope.</em></p>
<p>In the model below, we have a numeric*categorical interaction:</p>
<p><span class="math display">\[
\begin{align}
\text{wellbeing} \ = \ &amp;\beta_0 + \beta_1 \text{social_interactions} + \beta_2 \text{isRural} + \\
&amp;\beta_3 (\text{social_interactions} \cdot \text{isRural}) + \epsilon
\end{align}
\]</span></p>
<p>The estimate <span class="math inline">\(\hat \beta_3\)</span> is the adjustment to the slope <span class="math inline">\(\hat \beta_1\)</span> to be made for the individuals in the <span class="math inline">\(\text{isRural}=1\)</span> group.</p>
</div>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Look at the parameter estimates from your model, and write a description of what each one corresponds to on the plot shown in <a href="#fig-annotate-int">Figure&nbsp;1</a> (it may help to sketch out the plot yourself and annotate it).</p>
<div class="quote">
<p>“The best method of communicating findings about the presence of significant interaction may be to present a table of graph of the estimated means at various combinations of the interacting variables.”<br>
— <span class="citation" data-cites="Ramsey2012">Ramsey and Schafer (<a href="#ref-Ramsey2012" role="doc-biblioref">2012</a>)</span></p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-annotate-int" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_07_int1_nc_files/figure-html/fig-annotate-int-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 1: Multiple regression model: Wellbeing ~ Social Interactions * is Rural</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-7" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-7', 'opt-start-7')"> <span class="olab">Hints.</span></span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<p>Here are some options to choose from:</p>
<ul>
<li>The point at which the blue line cuts the y-axis (where social_int = 0)</li>
<li>The point at which the red line cuts the y-axis (where social_int = 0)</li>
<li>The average vertical distance between the red and blue lines.</li>
<li>The vertical distance from the blue to the red line <em>at the y-axis</em> (where social_int = 0)</li>
<li>The vertical distance from the red to the blue line <em>at the y-axis</em> (where social_int = 0)</li>
<li>The vertical distance from the blue to the red line <em>at the center of the plot</em>
</li>
<li>The vertical distance from the red to the blue line <em>at the center of the plot</em>
</li>
<li>The slope (vertical increase on the y-axis associated with a 1 unit increase on the x-axis) of the blue line</li>
<li>The slope of the red line</li>
<li>How the slope of the line changes when you move from the blue to the red line</li>
<li>How the slope of the line changes when you move from the red to the blue line</li>
</ul>
</div>
<p class="optional-end">
</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>We can obtain our parameter estimates using various functions such as <code>summary(rural_mod)</code>,<code>coef(rural_mod)</code>, <code>coefficients(rural_mod)</code> etc.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coefficients</a></span><span class="op">(</span><span class="va">rural_mod</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                (Intercept)                  social_int 
                 32.3851376                   0.1312089 
           isRuralnot rural social_int:isRuralnot rural 
                 -1.3865688                   0.5175856 </code></pre>
</div>
</div>
<ul>
<li>
<span class="math inline">\(\hat \beta_0\)</span> = <code>(Intercept)</code> = 32.39: The point at which the blue line cuts the y-axis (where social_int = 0).<br>
</li>
<li>
<span class="math inline">\(\hat \beta_1\)</span> = <code>social_int</code> = 0.13: The slope (vertical increase on the y-axis associated with a 1 unit increase on the x-axis) of the blue line.</li>
<li>
<span class="math inline">\(\hat \beta_2\)</span> = <code>isRuralrural</code> = -1.39: The vertical distance from the blue to the red line <em>at the y-axis</em> (where social_int = 0).<br>
</li>
<li>
<span class="math inline">\(\hat \beta_3\)</span> = <code>social_int:isRuralrural</code> = 0.52: How the slope of the line changes when you move from the blue to the red line.</li>
</ul>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Using <code><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model()</a></code>, visualize the interaction between social interactions and rural.</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Try to create a plot like <a href="#fig-annotate-int">Figure&nbsp;1</a>, which shows the two lines.</p>
<p>Think about what you need to specify in the <code>type =</code> argument - what types of models are these questions all about?</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">rural_mod</span>, </span>
<span>           type<span class="op">=</span><span class="st">"int"</span>, </span>
<span>           axis.title <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Social Interactions (number per week)"</span>, <span class="st">"Wellbeing (WEMWBS Scores)"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="1_07_int1_nc_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Interpret your results in the context of the research question and report your model in full.</p>
<p>Provide key model results in a formatted table.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#create table for results</span></span>
<span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">rural_mod</span>,</span>
<span>          dv.labels <span class="op">=</span> <span class="st">"Wellbeing (WEMWBS Scores)"</span>,</span>
<span>          pred.labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"social_int"</span> <span class="op">=</span> <span class="st">"Social Interactions (number per week)"</span>,</span>
<span>                          <span class="st">"isRural"</span> <span class="op">=</span> <span class="st">"Location"</span><span class="op">)</span>,</span>
<span>          title <span class="op">=</span> <span class="st">"Regression Table for Wellbeing Model"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div id="tbl-rural-modresults" class="anchored">

<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">Table 1:  Regression Table for Wellbeing Model </caption>
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">Wellbeing (WEMWBS Scores)</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">32.39</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">29.48&nbsp;–&nbsp;35.29</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Social Interactions<br>(number per week)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.13</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.09&nbsp;–&nbsp;0.35</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.244</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">isRuralnot rural</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.39</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-5.43&nbsp;–&nbsp;2.66</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.500</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">social_int:isRuralnot rural</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.52</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.20&nbsp;–&nbsp;0.84</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>0.002</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">200</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.296 / 0.285</td>
</tr>
</tbody></table>
</div>
</div>
</div>
<p>And now lets write our results up:</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Full regression results including 95% Confidence Intervals are shown in <a href="#tbl-rural-modresults">Table&nbsp;1</a>. The <span class="math inline">\(F\)</span>-test for model utility was significant <span class="math inline">\((F(3, 196) = 27.49, p&lt;.001)\)</span>, and the model explained approximately 28.54% of the variability in wellbeing scores.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="statbox">
<p><strong>Mean Centering</strong></p>
<p>Mean centering a variable involves subtracting the mean of that variable from every individual value. When working with models that contain interaction terms (like our <code>rural_mod</code>), it is generally a good idea to center your continuous predictor variables. This is because:</p>
<ul>
<li>centering helps to address issues of multicollinearity (you’ll learn more about this later in the course)</li>
<li>centering makes the model coefficients easier to interpret</li>
</ul>
</div>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Mean center the continuous IV, and re-run your model.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<p>Create mean centred variable for ‘social_int’:</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#wrdata &lt;-</span></span>
<span> <span class="co"># wrdata %&gt;%</span></span>
<span>  <span class="co">#mutate(</span></span>
<span>   <span class="co"># mc_social_int = scs - mean(social_int)</span></span>
<span>    <span class="co">#)</span></span></code></pre></div>
</div>
<p>Re-run model:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#fit model including interaction between social_int and isRural</span></span>
<span><span class="co">#rural_mod1 &lt;- lm(wellbeing ~  mc_social_int * isRural, data = wrdata)</span></span>
<span></span>
<span><span class="co">#check model output</span></span>
<span><span class="co">#summary(rural_mod1)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>



</section></section><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-Ramsey2012" class="csl-entry" role="doc-biblioentry">
Ramsey, Fred, and Daniel Schafer. 2012. <em>The Statistical Sleuth: A Course in Methods of Data Analysis</em>. Cengage Learning.
</div>
</div></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
      <div class="nav-footer-center">© Copyright 2019-2022 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
  </div>
</footer>


</body></html>