<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Write Up Example &amp; Block 2 Recap</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR2</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intro-to-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Intro to Linear Models</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intro-to-linear-models">
<li>
    <a class="dropdown-item" href="./1_01_function.html">
 <span class="dropdown-text">1/1: Functions and Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_slr.html">
 <span class="dropdown-text">1/2: Intro to Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_mlr.html">
 <span class="dropdown-text">1/3: Multiple Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_model_fit.html">
 <span class="dropdown-text">1/4: Model Fit and Standardization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_05_cat_recap.html">
 <span class="dropdown-text">1/5: Cat Predictors &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">More Linear Models</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more-linear-models">
<li>
    <a class="dropdown-item" href="./1_07_int1_nc.html">
 <span class="dropdown-text">1/7: Interactions I: Num x Cat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_08_int2_nn.html">
 <span class="dropdown-text">1/8: Interactions II: Num x Num</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_09_int3_cc.html">
 <span class="dropdown-text">1/9: Interactions III: Cat x Cat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_10_assump_diag.html">
 <span class="dropdown-text">1/10: Assumptions &amp; Diagnostics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_11_writeup_recap.html">
 <span class="dropdown-text">1/11: Write Up &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysing-experimental-studies" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Analysing Experimental Studies</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysing-experimental-studies">
<li>
    <a class="dropdown-item" href="./2_01_model_comps.html">
 <span class="dropdown-text">2/1: Model Comparison</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_02_effects.html">
 <span class="dropdown-text">2/2: Effects Coding</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_03_contrasts.html">
 <span class="dropdown-text">2/3: Contrasts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_04_emmeans.html">
 <span class="dropdown-text">2/4: Simple Effects &amp; Pairwise Comparisons</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_05_writeup_recap.html">
 <span class="dropdown-text">2/5: Write Up &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-topics-for-lm" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Advanced Topics for LM</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-topics-for-lm">
<li>
    <a class="dropdown-item" href="./2_06_glm1.html">
 <span class="dropdown-text">2/6: Binary Logistic Regression</span></a>
  </li>  
        <li class="dropdown-header">2/7: More Logistic Regression</li>
        <li class="dropdown-header">2/8: Sample Size &amp; Power Analysis</li>
        <li class="dropdown-header">2/9: Write Up &amp; Recap</li>
        <li class="dropdown-header">2/10: Mock Exam</li>
    </ul>
</li>
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#section-a-write-up" id="toc-section-a-write-up" class="nav-link active" data-scroll-target="#section-a-write-up">Section A: Write-Up</a>
  <ul class="collapse">
<li>
<a href="#study-overview" id="toc-study-overview" class="nav-link" data-scroll-target="#study-overview">Study Overview</a>
  <ul class="collapse">
<li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#the-3-act-structure" id="toc-the-3-act-structure" class="nav-link" data-scroll-target="#the-3-act-structure">The 3-Act Structure</a></li>
  </ul>
</li>
  </ul>
</li>
  <li><a href="#section-b-weeks-6---11-recap" id="toc-section-b-weeks-6---11-recap" class="nav-link" data-scroll-target="#section-b-weeks-6---11-recap">Section B: Weeks 6 - 11 Recap</a></li>
  <li><a href="#section-c-mock-exam-questions" id="toc-section-c-mock-exam-questions" class="nav-link" data-scroll-target="#section-c-mock-exam-questions">Section C: Mock Exam Questions</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Write Up Example &amp; Block 2 Recap</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand how to write-up and provide interpretation of a linear model with multiple predictors.</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed Labs 7-10</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>patchwork</strong></li>
<li><strong>sjPlot</strong></li>
<li><strong>sandwich</strong></li>
<li><strong>interactions</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/scs_study.csv">here</a> or read it in via this link https://uoepsy.github.io/data/scs_study.csv.</p>
<p><strong>Note</strong>: This is the same data as <a href="https://uoepsy.github.io/dapr2/2223/labs/1_08_int2_nn.html">Lab 8</a>.</p>
</section>
</div>
<section id="section-a-write-up" class="level1"><h1>Section A: Write-Up</h1>
<p>In this lab you will be presented with the output from a statistical analysis, and your job will be to write-up and present the results. We’re going to use an example analysis using one of the datasets we have worked with on a number of exercises in previous labs concerning personality traits, social comparison, depression, and anxiety.</p>
<p>The aim in writing should be that a reader is able to more or less replicate your analyses <strong>without</strong> referring to your R code. This requires detailing all of the steps you took in conducting the analysis.<br>
The point of using RMarkdown is that you can pull your results <strong>directly</strong> from the code. If your analysis changes, so does your report!</p>
<p>Make sure that your final report doesn’t show any R functions or code. Remember you are interpreting and reporting your results in text, tables, or plots, targeting a generic reader who may use different software or may not know R at all. If you need a reminder on how to hide code, format tables, etc., make sure to review the <a href="https://uoepsy.github.io//rmd-bootcamp/">rmd bootcamp</a>.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important - Write-Up Examples &amp; Plagiarism
</div>
</div>
<div class="callout-body-container callout-body">
<p>The example write-up sections included below are not <strong>perfect</strong> - they instead should give you a good example of what information you should include within each section, and how to structure this. For example, some information is missing (e.g., interpretation of descriptive statistics, what type of interaction is present), some information could be presented more clearly (e.g., variable names in tables, table/figure titles/captions, and rationales for choices), and writing could be more concise in places (e.g., discussion section is quite long).</p>
<p>Further, <strong>you must not copy any of the write-up included below for future reports</strong> - if you do, you will be committing plagiarism, and this type of academic misconduct is taken very seriously by the University. You can find out more <a href="https://www.ed.ac.uk/academic-services/students/conduct/academic-misconduct">here</a>.</p>
</div>
</div>
<section id="study-overview" class="level2"><h2 class="anchored" data-anchor-id="study-overview">Study Overview</h2>
<blockquote class="blockquote">
<p><strong>Research Question</strong></p>
<p>Controlling for other personality traits, does neuroticism moderate effects of social comparison on symptoms of depression, anxiety and stress?</p>
</blockquote>
<p>Previous research has identified an association between an individual’s perception of their social rank and symptoms of depression, anxiety and stress. We are interested in the individual differences in this association.</p>
<p>To investigate whether the effect of social comparison on symptoms of depression, anxiety and stress varies depending on level of Neuroticism, we will need to fit a multiple regression model with an interaction term and control for other personality traits.</p>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Social Comparison Study data codebook</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>Data from 656 participants containing information on scores on each trait of a Big 5 personality measure, their perception of their own social rank, and their scores on a measure of depression.</p>
<p>The data in <code>scs_study.csv</code> contain seven attributes collected from a random sample of <span class="math inline">\(n=656\)</span> participants:</p>
<ul>
<li>
<code>zo</code>: Openness (Z-scored), measured on the Big-5 Aspects Scale (BFAS)</li>
<li>
<code>zc</code>: Conscientiousness (Z-scored), measured on the Big-5 Aspects Scale (BFAS)</li>
<li>
<code>ze</code>: Extraversion (Z-scored), measured on the Big-5 Aspects Scale (BFAS)</li>
<li>
<code>za</code>: Agreeableness (Z-scored), measured on the Big-5 Aspects Scale (BFAS)</li>
<li>
<code>zn</code>: Neuroticism (Z-scored), measured on the Big-5 Aspects Scale (BFAS)</li>
<li>
<code>scs</code>: Social Comparison Scale - An 11-item scale that measures an individual’s perception of their social rank, attractiveness and belonging relative to others. The scale is scored as a sum of the 11 items (each measured on a 5-point scale), with higher scores indicating more favourable perceptions of social rank.</li>
<li>
<code>dass</code>: Depression Anxiety and Stress Scale - The DASS-21 includes 21 items, each measured on a 4-point scale. The score is derived from the sum of all 21 items, with higher scores indicating higher a severity of symptoms.</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell">
<div class="cell-output-display">

<div id="pqxkbfqhgj" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

:where(#pqxkbfqhgj) .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

:where(#pqxkbfqhgj) .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#pqxkbfqhgj) .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

:where(#pqxkbfqhgj) .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

:where(#pqxkbfqhgj) .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

:where(#pqxkbfqhgj) .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#pqxkbfqhgj) .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#pqxkbfqhgj) .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

:where(#pqxkbfqhgj) .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

:where(#pqxkbfqhgj) .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

:where(#pqxkbfqhgj) .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

:where(#pqxkbfqhgj) .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

:where(#pqxkbfqhgj) .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

:where(#pqxkbfqhgj) .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

:where(#pqxkbfqhgj) .gt_from_md > :first-child {
  margin-top: 0;
}

:where(#pqxkbfqhgj) .gt_from_md > :last-child {
  margin-bottom: 0;
}

:where(#pqxkbfqhgj) .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

:where(#pqxkbfqhgj) .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#pqxkbfqhgj) .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

:where(#pqxkbfqhgj) .gt_row_group_first td {
  border-top-width: 2px;
}

:where(#pqxkbfqhgj) .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#pqxkbfqhgj) .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

:where(#pqxkbfqhgj) .gt_first_summary_row.thick {
  border-top-width: 2px;
}

:where(#pqxkbfqhgj) .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#pqxkbfqhgj) .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#pqxkbfqhgj) .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

:where(#pqxkbfqhgj) .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

:where(#pqxkbfqhgj) .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#pqxkbfqhgj) .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#pqxkbfqhgj) .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#pqxkbfqhgj) .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#pqxkbfqhgj) .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#pqxkbfqhgj) .gt_left {
  text-align: left;
}

:where(#pqxkbfqhgj) .gt_center {
  text-align: center;
}

:where(#pqxkbfqhgj) .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

:where(#pqxkbfqhgj) .gt_font_normal {
  font-weight: normal;
}

:where(#pqxkbfqhgj) .gt_font_bold {
  font-weight: bold;
}

:where(#pqxkbfqhgj) .gt_font_italic {
  font-style: italic;
}

:where(#pqxkbfqhgj) .gt_super {
  font-size: 65%;
}

:where(#pqxkbfqhgj) .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

:where(#pqxkbfqhgj) .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

:where(#pqxkbfqhgj) .gt_indent_1 {
  text-indent: 5px;
}

:where(#pqxkbfqhgj) .gt_indent_2 {
  text-indent: 10px;
}

:where(#pqxkbfqhgj) .gt_indent_3 {
  text-indent: 15px;
}

:where(#pqxkbfqhgj) .gt_indent_4 {
  text-indent: 20px;
}

:where(#pqxkbfqhgj) .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="zo">zo</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="zc">zc</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="ze">ze</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="za">za</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="zn">zn</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="scs">scs</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="dass">dass</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="zo" class="gt_row gt_right">0.76</td>
<td headers="zc" class="gt_row gt_right">1.58</td>
<td headers="ze" class="gt_row gt_right">-0.79</td>
<td headers="za" class="gt_row gt_right">-0.09</td>
<td headers="zn" class="gt_row gt_right">1.32</td>
<td headers="scs" class="gt_row gt_right">30</td>
<td headers="dass" class="gt_row gt_right">56</td>
</tr>
<tr>
<td headers="zo" class="gt_row gt_right">0.30</td>
<td headers="zc" class="gt_row gt_right">-0.27</td>
<td headers="ze" class="gt_row gt_right">-0.09</td>
<td headers="za" class="gt_row gt_right">0.09</td>
<td headers="zn" class="gt_row gt_right">-0.40</td>
<td headers="scs" class="gt_row gt_right">30</td>
<td headers="dass" class="gt_row gt_right">48</td>
</tr>
<tr>
<td headers="zo" class="gt_row gt_right">-0.13</td>
<td headers="zc" class="gt_row gt_right">0.66</td>
<td headers="ze" class="gt_row gt_right">-0.80</td>
<td headers="za" class="gt_row gt_right">-0.95</td>
<td headers="zn" class="gt_row gt_right">0.93</td>
<td headers="scs" class="gt_row gt_right">35</td>
<td headers="dass" class="gt_row gt_right">48</td>
</tr>
<tr>
<td headers="zo" class="gt_row gt_right">1.06</td>
<td headers="zc" class="gt_row gt_right">-1.02</td>
<td headers="ze" class="gt_row gt_right">-0.16</td>
<td headers="za" class="gt_row gt_right">-0.50</td>
<td headers="zn" class="gt_row gt_right">-0.02</td>
<td headers="scs" class="gt_row gt_right">29</td>
<td headers="dass" class="gt_row gt_right">48</td>
</tr>
<tr>
<td headers="zo" class="gt_row gt_right">1.74</td>
<td headers="zc" class="gt_row gt_right">-0.78</td>
<td headers="ze" class="gt_row gt_right">-1.55</td>
<td headers="za" class="gt_row gt_right">-2.86</td>
<td headers="zn" class="gt_row gt_right">-1.14</td>
<td headers="scs" class="gt_row gt_right">41</td>
<td headers="dass" class="gt_row gt_right">43</td>
</tr>
<tr>
<td headers="zo" class="gt_row gt_right">0.22</td>
<td headers="zc" class="gt_row gt_right">-0.41</td>
<td headers="ze" class="gt_row gt_right">0.78</td>
<td headers="za" class="gt_row gt_right">0.90</td>
<td headers="zn" class="gt_row gt_right">-0.25</td>
<td headers="scs" class="gt_row gt_right">37</td>
<td headers="dass" class="gt_row gt_right">60</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-2" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-2', 'opt-start-2')"> <span class="olab">Provided Analysis Code</span></span>
</div>
<div id="opt-body-2" class="optional-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span> <span class="co"># for all things!</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://personality-project.org/r/psych/">psych</a></span><span class="op">)</span> <span class="co"># good for descriptive stats</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span> <span class="co"># useful for creating nice tables</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">car</a></span><span class="op">)</span> <span class="co"># for assumption tests</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://sandwich.R-Forge.R-project.org/">sandwich</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://interactions.jacob-long.com">interactions</a></span><span class="op">)</span> <span class="co"># for plotting models</span></span>
<span></span>
<span><span class="va">scs_study</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/scs_study.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># standardise scs score</span></span>
<span><span class="va">scs_study</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">scs_study</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>      zscs <span class="op">=</span> <span class="op">(</span><span class="va">scs</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">scs</span><span class="op">)</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">scs</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span><span class="co">#alternatively, you could do zscs = scale(scs, center = TRUE, scale = TRUE)</span></span>
<span></span>
<span><span class="co"># the describe() function is from the psych package, and kable() from kableExtra which is used to make a nice table where the values are rounded to 2 decimal places using digits = 2. </span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.html">describe</a></span><span class="op">(</span><span class="va">scs_study</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>        <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">dass</span>, <span class="va">scs</span>, <span class="va">zn</span><span class="op">)</span><span class="op">)</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span><span class="op">:</span><span class="fl">4</span>,<span class="fl">8</span><span class="op">:</span><span class="fl">9</span><span class="op">)</span><span class="op">]</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>        <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">.</span>, caption <span class="op">=</span> <span class="st">"DASS-21, SCS, and Neuroticism Descriptive Statistics"</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>        <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>DASS-21, SCS, and Neuroticism Descriptive Statistics</caption>
 <thead><tr>
<th style="text-align:left;">   </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> mean </th>
   <th style="text-align:right;"> sd </th>
   <th style="text-align:right;"> min </th>
   <th style="text-align:right;"> max </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:left;"> dass </td>
   <td style="text-align:right;"> 656 </td>
   <td style="text-align:right;"> 44.72 </td>
   <td style="text-align:right;"> 6.76 </td>
   <td style="text-align:right;"> 23.00 </td>
   <td style="text-align:right;"> 68.00 </td>
  </tr>
<tr>
<td style="text-align:left;"> scs </td>
   <td style="text-align:right;"> 656 </td>
   <td style="text-align:right;"> 35.77 </td>
   <td style="text-align:right;"> 3.53 </td>
   <td style="text-align:right;"> 27.00 </td>
   <td style="text-align:right;"> 54.00 </td>
  </tr>
<tr>
<td style="text-align:left;"> zn </td>
   <td style="text-align:right;"> 656 </td>
   <td style="text-align:right;"> 0.00 </td>
   <td style="text-align:right;"> 1.00 </td>
   <td style="text-align:right;"> -1.45 </td>
   <td style="text-align:right;"> 3.35 </td>
  </tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># scatterplot matrix of dataset without the zscs variable</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/pairs.panels.html">pairs.panels</a></span><span class="op">(</span><span class="va">scs_study</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">zscs</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="1_11_writeup_recap_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">dass_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">dass</span> <span class="op">~</span> <span class="va">zscs</span><span class="op">*</span><span class="va">zn</span> <span class="op">+</span> <span class="va">zo</span> <span class="op">+</span> <span class="va">zc</span> <span class="op">+</span> <span class="va">ze</span> <span class="op">+</span> <span class="va">za</span>, data <span class="op">=</span> <span class="va">scs_study</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">dass_mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="1_11_writeup_recap_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" style="width:90.0%"></p>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># 35 seems to be a very influential point, lets remove it and re-run the model</span></span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">dass_mdl2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">dass</span> <span class="op">~</span> <span class="va">zscs</span><span class="op">*</span><span class="va">zn</span> <span class="op">+</span> <span class="va">zo</span> <span class="op">+</span> <span class="va">zc</span> <span class="op">+</span> <span class="va">ze</span> <span class="op">+</span> <span class="va">za</span>, data <span class="op">=</span> <span class="va">scs_study</span><span class="op">[</span><span class="op">-</span><span class="fl">35</span>, <span class="op">]</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># check assumptions for updated model</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">dass_mdl2</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="1_11_writeup_recap_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" style="width:90.0%"></p>
</div>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># N.B. we cannot use crPlots for interactions</span></span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># Additional diagnostic plots for independence and homoscedasticity</span></span>
<span></span>
<span><span class="co"># checking for independence</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">dass_mdl2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="1_11_writeup_recap_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" style="width:90.0%"></p>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># alternative check for equal variances (Homoscedasticity) - </span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/residualPlots.html">residualPlots</a></span><span class="op">(</span><span class="va">dass_mdl2</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="1_11_writeup_recap_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid" style="width:90.0%"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>           Test stat Pr(&gt;|Test stat|)  
zscs          1.8141          0.07013 .
zn           -0.5911          0.55467  
zo            1.7801          0.07553 .
zc           -0.2403          0.81018  
ze           -0.9951          0.32004  
za            0.0725          0.94219  
Tukey test   -1.6406          0.10089  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># multicollinearity</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/vif.html">vif</a></span><span class="op">(</span><span class="va">dass_mdl2</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    zscs       zn       zo       zc       ze       za  zscs:zn 
1.015133 1.015736 1.013310 1.008235 2.332486 2.342220 1.012475 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># model output</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">dass_mdl2</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = dass ~ zscs * zn + zo + zc + ze + za, data = scs_study[-35, 
    ])

Residuals:
     Min       1Q   Median       3Q      Max 
-17.1455  -3.8155  -0.0066   3.6905  18.1483 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 44.97703    0.22635 198.708  &lt; 2e-16 ***
zscs        -1.93818    0.23042  -8.412 2.58e-16 ***
zn           1.41639    0.22661   6.250 7.44e-10 ***
zo          -0.31435    0.22056  -1.425    0.155    
zc           0.09134    0.22515   0.406    0.685    
ze           0.52695    0.34233   1.539    0.124    
za           0.33847    0.34281   0.987    0.324    
zscs:zn     -2.76609    0.24097 -11.479  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.733 on 647 degrees of freedom
Multiple R-squared:  0.279, Adjusted R-squared:  0.2712 
F-statistic: 35.76 on 7 and 647 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#create table for results</span></span>
<span><span class="fu">tab_model</span><span class="op">(</span><span class="va">dass_mdl2</span>,</span>
<span>          dv.labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"DASS-21 Scores"</span><span class="op">)</span>,</span>
<span>          pred.labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"zscs"</span><span class="op">=</span><span class="st">"Social Comparison Scale (Z-scored)"</span>, </span>
<span>                          <span class="st">"zn"</span><span class="op">=</span><span class="st">"Neuroticism (Z-scored)"</span>, </span>
<span>                          <span class="st">"zo"</span><span class="op">=</span><span class="st">"Openness (Z-scored)"</span>, </span>
<span>                          <span class="st">"zc"</span><span class="op">=</span><span class="st">"Conscientiousness (Z-scored)"</span>,</span>
<span>                          <span class="st">"ze"</span><span class="op">=</span><span class="st">"Extraversion (Z-scored)"</span>,</span>
<span>                          <span class="st">"za"</span><span class="op">=</span><span class="st">"Agreeableness (Z-scored)"</span>,</span>
<span>                          <span class="st">"zscs:zn"</span><span class="op">=</span><span class="st">"Social Comparison Scale (Z-scored): Neutoricism (Z-scored)"</span><span class="op">)</span>,</span>
<span>          title <span class="op">=</span> <span class="st">"Regression table for DASS-21 model"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">Regression table for DASS-21 model</caption>
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">DASS-21 Scores</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">44.98</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">44.53&nbsp;–&nbsp;45.42</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Social Comparison Scale<br>(Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.94</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-2.39&nbsp;–&nbsp;-1.49</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Neuroticism (Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">1.42</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.97&nbsp;–&nbsp;1.86</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Openness (Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.31</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.75&nbsp;–&nbsp;0.12</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.155</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Conscientiousness<br>(Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.09</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.35&nbsp;–&nbsp;0.53</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.685</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Extraversion (Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.53</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.15&nbsp;–&nbsp;1.20</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.124</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Agreeableness (Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.34</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.33&nbsp;–&nbsp;1.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.324</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Social Comparison Scale<br>(Z-scored): Neutoricism<br>(Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-2.77</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-3.24&nbsp;–&nbsp;-2.29</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">655</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.279 / 0.271</td>
</tr>
</tbody></table>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#interaction plot and simple slopes:</span></span>
<span><span class="va">plt_scs_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://interactions.jacob-long.com/reference/probe_interaction.html">probe_interaction</a></span><span class="op">(</span>model <span class="op">=</span> <span class="va">dass_mdl2</span>, </span>
<span>                  pred <span class="op">=</span> <span class="va">zscs</span>, </span>
<span>                  modx <span class="op">=</span> <span class="va">zn</span>, </span>
<span>                  cond.int <span class="op">=</span> <span class="cn">T</span>,</span>
<span>                  interval <span class="op">=</span> <span class="cn">T</span>, </span>
<span>                  jnplot <span class="op">=</span> <span class="cn">T</span>,</span>
<span>                  main.title <span class="op">=</span> <span class="st">"Neuroticism moderating the effect of\nsocial comparison on depression and anxiety"</span>,</span>
<span>                  x.label <span class="op">=</span> <span class="st">"Social Comparison Scale (Z-scored)"</span>,</span>
<span>                  y.label <span class="op">=</span> <span class="st">"DASS-21 Scores"</span>,</span>
<span>                  legend.main <span class="op">=</span> <span class="st">"Neuroticism (Z-scored)"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">plt_scs_mdl</span><span class="op">$</span><span class="va">interactplot</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="1_11_writeup_recap_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">plt_scs_mdl</span><span class="op">$</span><span class="va">simslopes</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>JOHNSON-NEYMAN INTERVAL 

When zn is OUTSIDE the interval [-0.93, -0.52], the slope of zscs is p &lt;
.05.

Note: The range of observed values of zn is [-1.45, 3.35]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="1_11_writeup_recap_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>SIMPLE SLOPES ANALYSIS 

When zn = -1.000344918 (- 1 SD): 

                               Est.   S.E.   t val.      p
--------------------------- ------- ------ -------- ------
Slope of zscs                  0.83   0.33     2.49   0.01
Conditional intercept         43.53   0.32   136.42   0.00

When zn = -0.003414067 (Mean): 

                               Est.   S.E.   t val.      p
--------------------------- ------- ------ -------- ------
Slope of zscs                 -1.93   0.23    -8.37   0.00
Conditional intercept         44.96   0.23   199.64   0.00

When zn =  0.993516784 (+ 1 SD): 

                               Est.   S.E.   t val.      p
--------------------------- ------- ------ -------- ------
Slope of zscs                 -4.69   0.33   -14.05   0.00
Conditional intercept         46.39   0.32   145.48   0.00</code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
<section id="setup" class="level3"><h3 class="anchored" data-anchor-id="setup">Setup</h3>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the scs dataset into R, assigning it to an object named <code>scs</code>
</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://personality-project.org/r/psych/">psych</a></span><span class="op">)</span> </span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">car</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://strengejacke.github.io/sjPlot/">sjPlot</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">scs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/scs_study.csv"</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="the-3-act-structure" class="level3"><h3 class="anchored" data-anchor-id="the-3-act-structure">The 3-Act Structure</h3>
<p>We need to present our report in three clear sections - think of your sections like the 3 key parts of a play or story - we need to (1) provide some background and scene setting for the reader, (2) present our results in the context of the research question, and (3) present a resolution to our story - relate our findings back to the question we were asked and provide our answer.</p>
<section id="act-i-analysis-strategy" class="level4"><h4 class="anchored" data-anchor-id="act-i-analysis-strategy">Act I: Analysis Strategy</h4>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Attempt to draft a discussion section based on the above research question and analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Analysis Strategy - What to Include
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Your analysis strategy will contain a number of different elements detailing plans and changes to your plan. Remember, your analysis strategy should <strong>not</strong> contain any results. You may wish to include the following sections:</p>
<ul>
<li>Very brief data and design description:
<ul>
<li>Give the reader some background on the context of your write-up. For example, you may wish to describe the data source, data collection strategy, study design, number of observational units.</li>
<li>Specify the variables of interest in relation to the research question, including their unit of measurement, the allowed range (for Likert scales), how they are scored, and if they are factors make sure to list the order of the levels.</li>
</ul>
</li>
<li>Data management:
<ul>
<li>Describe any data cleaning and/or recoding.</li>
<li>Are there any observations that have been excluded based on pre-defined criteria? How/why, and how many?</li>
<li>* Describe any transformations performed to aid your interpretation (i.e., log transformation, mean centering, standardisation, etc.)</li>
</ul>
</li>
<li>Model specification:
<ul>
<li>Clearly state your hypotheses and specify your chosen significance level.</li>
<li>What type of statistical analysis do you plan to use to answer the research question? (e.g., t-test, simple linear regression, multiple linear regression, etc.)</li>
<li>In some cases, you may wish to include some visualisations and descriptive tables to motivate your model specification.</li>
<li>Specify the model(s) to be fitted to answer your given research question and analysis structure. Clearly specify the response and explanatory variables included in your model(s) and remember to describe the coding of categorical variables (i.e., factors) so the reader is aware of any reference levels.</li>
<li>Detail the steps that you will undertake to ensure that your model(s) do not violate the appropriate assumptions.</li>
<li>If applicable, detail any required changes/modifications to the model specification to satisfy assumptions. Consider the following: Was there anything you had to do differently than planned during the analysis? Did the modelling highlight issues in your data? Did you have to do anything (e.g., transform any variables, exclude any observations) in order to meet assumptions?</li>
</ul>
</li>
</ul>
<div class="frame">
<p>Note that the * used on occasion in the above indicates that you may/should in some cases repeat these steps if you decide to make any modifications to your data (e.g., removing outliers, etc.).</p>
</div>
<p>As noted and encouraged throughout the course, one of the main benefits of using RMarkdown is the ability to include inline R code in your document. Try to incorporate this in your write up so you can automatically pull the specified values from your code. If you need a reminder on how to do this, see <a href="https://uoepsy.github.io//rmd-bootcamp/">Lesson 4 of the Rmd Bootcamp</a>.</p>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-4" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-4', 'opt-start-4')"> <span class="olab">Example Write-Up of Analysis Strategy Section</span></span>
</div>
<div id="opt-body-4" class="optional-body" style="display: none;">
<p>The dataset contained information on 656 participants, including <span class="math inline">\(Z\)</span>-scores on 5 personality traits assessed by the Big-Five Aspects Scale (BFAS; Openness, Conscientiousness, Extraversion, Agreeableness and Neuroticism). Participants were also assessed on the Social Comparison Scale (SCS), which is an 11-item scale measuring self-perception (relative to others) of social rank, attractiveness and belonging, and the Depression Anxiety and Stress Scale (DASS-21) - a 21 item measure with higher scores indicating higher severity of symptoms. For both of these measures, only total scores were available. Items in the SCS were measured on a 5-point scale, giving minimum and maximum possible scores of 11 and 55 respectively. Items in the DASS-21 were measured on a 4-point scale, meaning that scores could range from 21 to 84.</p>
<p>All participant data was complete (no missing values), with scores on the SCS and the DASS-21 all within possible ranges.</p>
<p>To investigate whether, when controlling for other personality traits, Neuroticism moderated the effect of social comparison on symptoms of depression, anxiety and stress, total scores on the DASS-21 were modeled using multiple linear regression. The <span class="math inline">\(Z\)</span>-scored measures on each of the big-five personality traits were included as predictors, along with scores on the SCS (<span class="math inline">\(Z\)</span>-scored) and its interaction with the measure of Neuroticism. Effects were considered statistically significant at <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p>The following model specification was used: <span class="math display">\[
\begin{aligned}
\text{DASS-21}
= \beta_0 + \beta_1 \text{O} + \beta_2 \text{C} + \beta_3 \text{E} + \beta_4 \text{A}
+ \beta_5 \text{N} + \beta_6 \text{SCS} + \beta_7 (\text{SCS} \cdot \text{N})
+ \epsilon  \\
\end{aligned}
\]</span></p>
<p><span class="math display">\[
\begin{aligned}
\text{where } \\
\\
&amp; \text{O = Openness, z-scored} \\
&amp; \text{C = Conscientiousness, z-scored} \\
&amp; \text{E = Extraversion, z-scored} \\
&amp; \text{A = Agreeableness, z-scored} \\
&amp; \text{N = Neuroticism, z-scored} \\
&amp; \text{SCS = Social Comparison Scale, z-scored} \\
\end{aligned}
\]</span></p>
<p>To address the research question of whether Neuroticism moderated the effect of social comparison on depression and anxiety, we tested whether the interaction between SCS and Neuroticism was significant. Formally, this corresponded to testing whether the interaction coefficient was equal to zero:</p>
<p><span class="math display">\[
\begin{aligned}
H_0: \beta_7 = 0  \\  
H_1: \beta_7 \neq 0  \\
\end{aligned}
\]</span></p>
<p>The following assumptions were assessed visually using diagnostic plots: linearity (via plot of residuals vs fitted values; red line should be approximately horizontal, with residual values randomly scattered around zero and thus showing no pattern in relation to fitted values), independence (with the previous plot and a plot of residuals vs index; no dependence should be indicated), equal variances (via a scale-location plot; residuals should be evenly spread across the range of fitted values, where the spread should be constant across the range of fitted values), and normality (via a qqplot of the residuals; points should follow along the diagonal line). We also checked if there was any evidence of multicollinearity by checking VIF values, where values &gt; 5 were considered to indicate moderate multicollinearity, and values &gt; 10 severe. Outliers were assessed via Cooks Distance, where values &gt;2 indicated influential points.</p>
</div>
<p class="optional-end">
</p>
</section><section id="act-ii-results" class="level4"><h4 class="anchored" data-anchor-id="act-ii-results">Act II: Results</h4>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Attempt to draft a results section based on your detailed analysis strategy and the analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Results - What To Include
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The results section should follow from your analysis strategy. This is where you would present the evidence and results that will be used to answer the research questions and can support your conclusions. Make sure that you address all aspects of the approach you outlined in the analysis strategy.</p>
<p>In this section, it is useful to include tables and plots to clearly present your findings to your reader. It is important, however, to carefully select what is the key information that should be presented. You don’t want to overload the reader with unnecessary information, and you also want to save space in case there is a page limit. Make use of figures with multiple panels where you can.</p>
<p>As a broad guideline, you want to start with the results of an exploratory data analysis, presenting tables of summary statistics and exploratory plots. You may also want to visualise relationships between variables and report covariances or correlations. Then, you should move on to the results from your model. Remember that in the main part of the report you should only interpret and report for models that <strong>do not violate</strong> the assumptions. You should also interpret all of the results presented, and remember to make reference to and comment on your assumption and diagnostic checks for key models.</p>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-5" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-5', 'opt-start-5')"> <span class="olab">Example Write-Up of Results Section</span></span>
</div>
<div id="opt-body-5" class="optional-body" style="display: none;">
<p>Descriptive statistics are displayed in <a href="#tbl-scsdasstab">Table&nbsp;1</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-scsdasstab" class="anchored">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Table&nbsp;1:  Regression table for DASS-21 model </caption>
 <thead><tr>
<th style="text-align:left;">   </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> mean </th>
   <th style="text-align:right;"> sd </th>
   <th style="text-align:right;"> min </th>
   <th style="text-align:right;"> max </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:left;"> dass </td>
   <td style="text-align:right;"> 656 </td>
   <td style="text-align:right;"> 44.72 </td>
   <td style="text-align:right;"> 6.76 </td>
   <td style="text-align:right;"> 23.00 </td>
   <td style="text-align:right;"> 68.00 </td>
  </tr>
<tr>
<td style="text-align:left;"> scs </td>
   <td style="text-align:right;"> 656 </td>
   <td style="text-align:right;"> 35.77 </td>
   <td style="text-align:right;"> 3.53 </td>
   <td style="text-align:right;"> 27.00 </td>
   <td style="text-align:right;"> 54.00 </td>
  </tr>
<tr>
<td style="text-align:left;"> zn </td>
   <td style="text-align:right;"> 656 </td>
   <td style="text-align:right;"> 0.00 </td>
   <td style="text-align:right;"> 1.00 </td>
   <td style="text-align:right;"> -1.45 </td>
   <td style="text-align:right;"> 3.35 </td>
  </tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Bivariate correlations showed a moderate negative association between DASS-21 and SCS scores; a moderate positive association between DASS-21 and Neuroticism, and a weak positive correlation between SCS and Neuroticism (see <a href="#fig-splom">Figure&nbsp;1</a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-splom" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_11_writeup_recap_files/figure-html/fig-splom-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Bivariate scatter plots (below diagonal), histograms (diagonal), and Pearson correlation coefficient (above diagonal) for DASS-21 scores, SCS, and Big 5 Personality variables</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>One observation (unit 35) was judged to be too influential on the model (Cook’s Distance = 2.66) and as such was excluded from the final analysis, leaving 655 observations.</p>
<p>The final model met assumptions of linearity and independence (see top left panel of <a href="#fig-diagplots">Figure&nbsp;2</a>; residuals were randomly scattered with a mean of zero and there was no clear dependence), homoscedasticity (see bottom left panel of <a href="#fig-diagplots">Figure&nbsp;2</a>; there was a constant spread of residuals), and normality (see top right panel of <a href="#fig-diagplots">Figure&nbsp;2</a>; the QQplot showed very little deviation from the diagonal line). All VIF values were &lt;5, and hence there was no evidence of multicollinearity.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-diagplots" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_11_writeup_recap_files/figure-html/fig-diagplots-1.png" class="img-fluid figure-img" style="width:90.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Diagnostic Plots</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">

</div>
<p>Full regression results including 95% Confidence Intervals are shown in <a href="#tbl-dass-modresults">Table&nbsp;2</a>. The <span class="math inline">\(F\)</span>-test for model utility was significant (<span class="math inline">\(F(7,647) = 35.76, p&lt;.001\)</span>), and the model explained approximately 27.12% of the variability in DASS-21 Scores.</p>
<br><center>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-dass-modresults" class="anchored">

<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">Table&nbsp;2:  Regression table for DASS-21 model </caption>
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">DASS-21 Scores</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">44.98</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">44.53&nbsp;–&nbsp;45.42</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Social Comparison Scale<br>(Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.94</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-2.39&nbsp;–&nbsp;-1.49</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Neuroticism (Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">1.42</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.97&nbsp;–&nbsp;1.86</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Openness (Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.31</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.75&nbsp;–&nbsp;0.12</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.155</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Conscientiousness<br>(Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.09</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.35&nbsp;–&nbsp;0.53</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.685</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Extraversion (Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.53</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.15&nbsp;–&nbsp;1.20</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.124</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Agreeableness (Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.34</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.33&nbsp;–&nbsp;1.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.324</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Social Comparison Scale<br>(Z-scored): Neutoricism<br>(Z-scored)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-2.77</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-3.24&nbsp;–&nbsp;-2.29</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">655</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.279 / 0.271</td>
</tr>
</tbody></table>
</div>
</div>
</div>
</center>
<p><br></p>
<p>Results showed a significant conditional association between SCS scores (<span class="math inline">\(Z\)</span>-scored) and DASS-21 Scores (<span class="math inline">\(\beta\)</span> = -1.94, <span class="math inline">\(SE\)</span> = 0.23, <span class="math inline">\(p\)</span> &lt;.001), which suggested that for those at the mean level of Neuroticism, scores on the DASS-21 decreased by 1.94 for every 1 standard deviation increase in SCS scores. A significant conditional association was also evident between Neuroticism (Z-scored) and DASS-21 Scores (<span class="math inline">\(\beta\)</span> = 1.42, <span class="math inline">\(SE\)</span> = 0.23, <span class="math inline">\(p\)</span> &lt;.001), which suggested that for those with average scores on the SCS, scores on the DASS-21 increased by 1.42 for every 1 standard deviation increase in Neuroticism.</p>
<p>Crucially, the association between social comparison and symptoms of depression and anxiety was found to be dependent upon the level of Neuroticism, with a greater negative association between the two for those with high levels of Neuroticism (<span class="math inline">\(\beta\)</span> = -2.77, <span class="math inline">\(SE\)</span> = 0.24, <span class="math inline">\(p\)</span> &lt;.001). This interaction is visually presented in <a href="#fig-intplot">Figure&nbsp;3</a>.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-intplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_11_writeup_recap_files/figure-html/fig-intplot-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3: Interaction Plot</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The results presented here indicated that the association between social comparison and depression and anxiety did depend upon individuals’ levels of Neuroticism, with perceived social rank perhaps leading to more symptoms of depression and anxiety for highly neurotic individuals. The Johnson-Neyman technique (see <a href="#fig-simpslope">Figure&nbsp;4</a>) indicated that the association between DASS-21 scores and SCS was significant when Neuroticism scores were less than 0.93 standard deviations below the mean or more than -0.52 standard deviations above the mean.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-simpslope" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_11_writeup_recap_files/figure-html/fig-simpslope-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;4: Simple Slopes</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section><section id="act-iii-discussion" class="level4"><h4 class="anchored" data-anchor-id="act-iii-discussion">Act III: Discussion</h4>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Attempt to draft a discussion section based on your results and the analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Discussion - What To Include
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In the discussion section, you should summarise the key findings from the results section and provide the reader with take-home sentences drawing the analysis together and relating it back to the original question.</p>
<p>The discussion should be relatively brief, and should not include any statistical analysis - instead think of the discussion as a conclusion, providing an answer to the research question(s).</p>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-6" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-6', 'opt-start-6')"> <span class="olab">Example Write-Up of Discussion Section</span></span>
</div>
<div id="opt-body-6" class="optional-body" style="display: none;">
<p>Previous research had identified an association between an individual’s perception of their social rank and symptoms of depression, anxiety and stress. We investigated if Neuroticism moderated effects of social comparison on symptoms of depression, anxiety, and stress after controlling for other personality traits.</p>
<p>Our results led us to reject the null hypothesis that the interaction coefficient was equal to zero, as the results indicated that the association between social comparison and depression and anxiety did depend upon individuals’ levels of Neuroticism, with perceived social rank perhaps leading to more symptoms of depression and anxiety for highly neurotic individuals. However, it is important to note that we can make no claims on the directions of these associations from these data based on significance alone - it may be that social comparison leads to more depression and anxiety in neurotic individuals, but also consistent is the view that - for these individuals - higher levels of depression leads to a greater reduction in perceived social rank.</p>
</div>
<p class="optional-end">
</p>
</section></section></section></section><section id="section-b-weeks-6---11-recap" class="level1"><h1>Section B: Weeks 6 - 11 Recap</h1>
<p>In the second part of the lab, there is no new content - the purpose of the recap section is for you to revisit and revise the concepts you have learned over the last 4/5 weeks.</p>
<div class="red">
<p>Before you expand each of the boxes below, think about how comfortable you feel with each concept.</p>
</div>
<div class="optional-begin">
<span id="opt-start-7" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-7', 'opt-start-7')"> <span class="olab">Specifying Interaction Models</span></span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<p><strong>Formula:</strong></p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 (x_1 \cdot x_2) + \epsilon
\]</span> In <strong>R</strong>:</p>
<div class="blue">
<p>There are basically two pieces of information that we need to pass to the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function:</p>
<ol type="1">
<li><p>The formula: The regression formula should be specified in the form <code>y ~ x</code> where <span class="math inline">\(y\)</span> is the dependent variable (DV), <span class="math inline">\(x_1\)</span> the first independent variable (IV1), and <span class="math inline">\(x_2\)</span> the second independent variable (IV2).</p></li>
<li><p>The data: Specify which dataframe contains the variables specified in the formula.</p></li>
</ol>
<ul>
<li>run interaction model via <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">model_name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">DV</span> <span class="op">~</span> <span class="va">IV1</span><span class="op">*</span><span class="va">IV2</span>, data <span class="op">=</span> <span class="va">data_name</span><span class="op">)</span></span></code></pre></div>
</div>
<p><strong>OR</strong></p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">model_name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">data_name</span><span class="op">$</span><span class="va">DV</span> <span class="op">~</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV1</span> <span class="op">+</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV2</span> <span class="op">+</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV1</span><span class="op">:</span><span class="va">data_name</span><span class="op">$</span><span class="va">IV2</span><span class="op">)</span></span></code></pre></div>
</div>
<p><strong>OR</strong></p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">model_name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">data_name</span><span class="op">$</span><span class="va">DV</span> <span class="op">~</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV1</span> <span class="op">+</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV2</span> <span class="op">+</span> <span class="va">data_name</span><span class="op">$</span><span class="va">IV1</span><span class="op">*</span><span class="va">data_name</span><span class="op">$</span><span class="va">IV2</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 7 <a href="https://uoepsy.github.io/dapr2/2223/labs/1_07_int1_nc.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_06_interactions1#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-8" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-8', 'opt-start-8')"> <span class="olab">Interpreting Coefficients</span></span>
</div>
<div id="opt-body-8" class="optional-body" style="display: none;">
<p><strong>Interpreting coefficients for A and B in the presence of an interaction A:B</strong></p>
<p>When you include an interaction between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> in a regression model, you are estimating the extent to which the effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> is different across the values of <span class="math inline">\(x_2\)</span>.</p>
<p>What this means is that the effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> <em>depends on/is conditional upon</em> the value of <span class="math inline">\(x_2\)</span>.<br>
(and vice versa, the effect of <span class="math inline">\(x_2\)</span> on <span class="math inline">\(y\)</span> is different across the values of <span class="math inline">\(x_1\)</span>).<br>
This means that we can no longer talk about the “effect of <span class="math inline">\(x_1\)</span> <em>holding <span class="math inline">\(x_2\)</span> constant</em>”. Instead we can talk about a <em>marginal effect</em> of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> at a specific value of <span class="math inline">\(x_2\)</span>.</p>
<div class="frame">
<p>When we fit the model <span class="math inline">\(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 (x_1 \cdot x_2) + \epsilon\)</span> using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>:</p>
<ul>
<li>the parameter estimate <span class="math inline">\(\hat \beta_1\)</span> is the <em>marginal effect</em> of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> where <span class="math inline">\(x_2 = 0\)</span><br>
</li>
<li>the parameter estimate <span class="math inline">\(\hat \beta_2\)</span> is the <em>marginal effect</em> of <span class="math inline">\(x_2\)</span> on <span class="math inline">\(y\)</span> where <span class="math inline">\(x_1 = 0\)</span><br>
</li>
</ul>
</div>
<div style="margin-left: 15px">
<p><small> <strong>N.B.</strong> Regardless of whether or not there is an interaction term in our model, all parameter estimates in multiple regression are “conditional” in the sense that they are dependent upon the inclusion of other variables in the model. For instance, in <span class="math inline">\(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon\)</span> the coefficient <span class="math inline">\(\hat \beta_1\)</span> is conditional upon holding <span class="math inline">\(x_2\)</span> constant. </small></p>
</div>
<p><strong>Interpreting the interaction term A:B</strong></p>
<p>The coefficient for an interaction term can be thought of as providing an <em>adjustment to the slope.</em></p>
<p>For example, in the model below, we have a numeric*categorical interaction:</p>
<p><span class="math display">\[
\begin{split}
\text{Wellbeing} \ = \beta_0 + \beta_1 \cdot Social Interactions + \beta_2 \cdot Location_{Rural} \\ + \beta_3 \cdot (Social Interactions \cdot Location_{Rural}) + \epsilon  
\end{split}
\]</span></p>
<p>The estimate <span class="math inline">\(\hat \beta_3\)</span> is the adjustment to the slope <span class="math inline">\(\hat \beta_1\)</span> to be made for the individuals in the <span class="math inline">\(\text{isRural}=1\)</span> group.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 7 <a href="https://uoepsy.github.io/dapr2/2223/labs/1_07_int1_nc.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_06_interactions1#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-9" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-9', 'opt-start-9')"> <span class="olab">Mean Centering</span></span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p>Mean centering a variable involves subtracting the mean of that variable from every individual value. When working with models that contain interaction terms (like our <code>rural_mod</code>), it is generally a good idea to center your continuous predictor variables. This is because:</p>
<ul>
<li>centering helps to address issues of multicollinearity</li>
<li>centering makes the model coefficients easier to interpret</li>
</ul>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 7 <a href="https://uoepsy.github.io/dapr2/2223/labs/1_07_int1_nc.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_06_interactions1#1">lectures</a>, and Week 8 <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_07_interactions2#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-10" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-10', 'opt-start-10')"> <span class="olab">Assumptions: Linearity</span></span>
</div>
<div id="opt-body-10" class="optional-body" style="display: none;">
<section id="simple-linear-regression" class="level3"><h3 class="anchored" data-anchor-id="simple-linear-regression">Simple Linear Regression</h3>
<p>In simple linear regression (SLR) with only one explanatory variable, we could assess linearity through a simple scatterplot of the outcome variable against the explanatory. This would allow us to check if the errors have a mean of zero. If this assumption was met, the residuals would appear to be randomly scattered around zero.<br>
The rationale for this is that, once you remove from the data the linear trend, what’s left over in the residuals should not have any trend, i.e.&nbsp;have a mean of zero.</p>
</section><section id="multiple-regression" class="level3"><h3 class="anchored" data-anchor-id="multiple-regression">Multiple Regression</h3>
<p>In multiple regression, however, it becomes more necessary to rely on diagnostic plots of the model residuals. This is because we need to know whether the relations are linear between the outcome and each predictor <em>after accounting for the other predictors in the model.</em></p>
<p>In order to assess this, we use <strong>partial-residual plots</strong> (also known as ‘component-residual plots’). This is a plot with each explanatory variable <span class="math inline">\(x_j\)</span> on the x-axis, and <strong>partial residuals</strong> on the y-axis.</p>
<p>Partial residuals for a predictor <span class="math inline">\(x_j\)</span> are calculated as: <span class="math display">\[
\hat \epsilon + \hat \beta_j x_j
\]</span></p>
<div class="blue">
<p>In <strong>R</strong>, we can easily create these plots for all predictors in the model by using the <code><a href="https://rdrr.io/pkg/car/man/crPlots.html">crPlots()</a></code> function from the <code>car</code> package.</p>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 10 <a href="https://uoepsy.github.io/dapr2/2223/labs/1_10_assump_diag.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_09_assumptions_diagnostics#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</section>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-11" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-11', 'opt-start-11')"> <span class="olab">Assumptions: Equal Variances (Homoscedasticity)</span></span>
</div>
<div id="opt-body-11" class="optional-body" style="display: none;">
<p>The equal variances assumption is that the error variance <span class="math inline">\(\sigma^2\)</span> is constant across values of the predictor(s) <span class="math inline">\(x_1, \dots, x_k\)</span>, and across values of the fitted values <span class="math inline">\(\hat y\)</span>. This sometimes gets termed “Constant” vs “Non-constant” variance. This is presented visually in <a href="#fig-ncv-violate">Figure&nbsp;5</a> and <a href="#fig-ncv-noviolate">Figure&nbsp;6</a>.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ncv-violate" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_11_writeup_recap_files/figure-html/fig-ncv-violate-1.png" class="img-fluid figure-img" style="width:90.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;5: Non-constant variance for numeric and categorical X</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ncv-noviolate" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1_11_writeup_recap_files/figure-html/fig-ncv-noviolate-1.png" class="img-fluid figure-img" style="width:90.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;6: Constant variance for numeric and categorical X</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="blue">
<p>In <strong>R</strong>, we can create plots of the <em>Pearson residuals</em> against the predicted values <span class="math inline">\(\hat y\)</span> and against the predictors <span class="math inline">\(x_1\)</span>, … <span class="math inline">\(x_k\)</span> by using the <code><a href="https://rdrr.io/pkg/car/man/residualPlots.html">residualPlots()</a></code> function from the <code>car</code> package. This function also provides the results of a lack-of-fit test for each of these relationships (note when it is the fitted values <span class="math inline">\(\hat y\)</span> it gets called “Tukey’s test”).</p>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 10 <a href="https://uoepsy.github.io/dapr2/2223/labs/1_10_assump_diag.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_09_assumptions_diagnostics#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-12" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-12', 'opt-start-12')"> <span class="olab">Assumptions: Independence (of errors)</span></span>
</div>
<div id="opt-body-12" class="optional-body" style="display: none;">
<p>The ‘independence of errors’ assumption is the condition that the errors do not have some underlying relationship which is causing them to influence one another. <br></p>
<p>There are many sources of possible dependence, and often these are issues of study design. For example, we may have groups of observations in our data which we would expect to be related (e.g., multiple trials from the same participant). Our modelling strategy would need to take this into account. <br></p>
<p>One form of dependence is <strong>autocorrelation</strong> - this is when observations influence those adjacent to them. It is common in data for which <em>time</em> is a variable of interest (e.g, the humidity today is dependent upon the rainfall yesterday).</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 10 <a href="https://uoepsy.github.io/dapr2/2223/labs/1_10_assump_diag.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_09_assumptions_diagnostics#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-13" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-13', 'opt-start-13')"> <span class="olab">Assumptions: Normality (of errors)</span></span>
</div>
<div id="opt-body-13" class="optional-body" style="display: none;">
<p>The normality assumption is the condition that the errors <span class="math inline">\(\epsilon\)</span> are normally distributed in the population.</p>
<p>We can visually assess this condition through histograms, density plots, and quantile-quantile plots (QQplots) of our residuals <span class="math inline">\(\hat \epsilon\)</span>.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 10 <a href="https://uoepsy.github.io/dapr2/2223/labs/1_10_assump_diag.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_09_assumptions_diagnostics#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-14" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-14', 'opt-start-14')"> <span class="olab">Assumptions: Interactions</span></span>
</div>
<div id="opt-body-14" class="optional-body" style="display: none;">
<p>A few points to note when assessing the assumptions of an interaction model:</p>
<ul>
<li>When there is an interaction in the model, assessing linearity becomes difficult. In fact, <code><a href="https://rdrr.io/pkg/car/man/crPlots.html">crPlots()</a></code> will not work. To assess, you can create a residuals-vs-fitted plot like we saw in the guided exercises above.<br>
</li>
<li>Interaction terms often result in multicollinearity, because these terms are made up of the product of some ‘main effects’. Mean-centering the variables like we have here will reduce this source of structural multicollinearity (“structural” here refers to the fact that multicollinearity is due to our model specification, rather than the data itself).</li>
</ul>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 10 <a href="https://uoepsy.github.io/dapr2/2223/labs/1_10_assump_diag.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_09_assumptions_diagnostics#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-15" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-15', 'opt-start-15')"> <span class="olab">Multicollinearity</span></span>
</div>
<div id="opt-body-15" class="optional-body" style="display: none;">
<p>For the linear model with <strong>multiple</strong> explanatory variables, we need to also think about <strong>multicollinearity</strong> - this is when two (or more) of the predictors in our regression model are moderately or highly correlated.</p>
<p>We can assess multicollinearity using the <strong>variance inflation factor (VIF)</strong>, which for a given predictor <span class="math inline">\(x_j\)</span> is calculated as:<br><span class="math display">\[
VIF_j = \frac{1}{1-R_j^2} \\
\]</span> Suggested cut-offs for VIF are varied. Some suggest 10, others 5. Define what you will consider an acceptable value <em>prior</em> to calculating it. You could loosely interpret VIF values &gt;5 as moderate multicollinearity and values &gt;10 as severe multicollinearity.</p>
<div class="blue">
<p>In <strong>R</strong>, the <code><a href="https://rdrr.io/pkg/car/man/vif.html">vif()</a></code> function from the <code>car</code> package will provide VIF values for each predictor in your model.</p>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 10 <a href="https://uoepsy.github.io/dapr2/2223/labs/1_10_assump_diag.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_09_assumptions_diagnostics#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-16" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-16', 'opt-start-16')"> <span class="olab">Individual Case Diagnostics</span></span>
</div>
<div id="opt-body-16" class="optional-body" style="display: none;">
<p>We have seen in the case of the simple linear regression that individual cases in our data can influence our model more than others. We know about:</p>
<ul>
<li>
<strong>Regression outliers:</strong> A large residual <span class="math inline">\(\hat \epsilon_i\)</span> - i.e., a big discrepancy between their predicted y-value and their observed y-value.
<ul>
<li>
<strong>Standardised residuals:</strong> For residual <span class="math inline">\(\hat \epsilon_i\)</span>, divide by the estimate of the standard deviation of the residuals. In R, the <code><a href="https://rdrr.io/r/stats/influence.measures.html">rstandard()</a></code> function will give you these</li>
<li>
<strong>Studentised residuals:</strong> For residual <span class="math inline">\(\hat \epsilon_i\)</span>, divide by the estimate of the standard deviation of the residuals excluding case <span class="math inline">\(i\)</span>. In R, the <code><a href="https://rdrr.io/r/stats/influence.measures.html">rstudent()</a></code> function will give you these.</li>
</ul>
</li>
<li>
<strong>High leverage cases:</strong> These are cases which have considerable <em>potential</em> to influence the regression model (e.g., cases with an unusual combination of predictor values).
<ul>
<li>
<strong>Hat values:</strong> are used to assess leverage. In R, The <code><a href="https://rdrr.io/r/stats/influence.measures.html">hatvalues()</a></code> function will retrieve these.</li>
</ul>
</li>
<li>
<strong>High influence cases:</strong> When a case has high leverage <em>and</em> is an outlier, it will have a large influence on the regression model.
<ul>
<li>
<strong>Cook’s Distance:</strong> combines <em>leverage</em> (hatvalues) with <em>outlying-ness</em> to capture influence: <span class="math inline">\(D_i = \text{Outlyingness} \times \text{Leverage}\)</span>. Cook’s distance refers to the average distance the <span class="math inline">\(\hat{y}\)</span> values will move if a given case is removed. In <code>R</code>, the <code><a href="https://rdrr.io/r/stats/influence.measures.html">cooks.distance()</a></code> function will provide these values. Alongside Cook’s Distance, we can examine the extent to which model estimates and predictions are affected when an entire case is dropped from the dataset and the model is refitted.<br>
</li>
</ul>
</li>
<li>
<strong>DFFit:</strong> the change in the predicted value at the <span class="math inline">\(i^{th}\)</span> observation with and without the <span class="math inline">\(i^{th}\)</span> observation is included in the regression.<br>
</li>
<li>
<strong>DFbeta:</strong> the change in a specific coefficient with and without the <span class="math inline">\(i^{th}\)</span> observation is included in the regression.<br>
</li>
<li>
<strong>DFbetas:</strong> the change in a specific coefficient divided by the standard error, with and without the <span class="math inline">\(i^{th}\)</span> observation is included in the regression.<br>
</li>
<li>
<strong>COVRATIO:</strong> measures the effect of an observation on the covariance matrix of the parameter estimates. In simpler terms, it captures an observation’s influence on standard errors.</li>
</ul>
<div class="blue">
<p>In <strong>R</strong>, we can get lots of these measures with the <code><a href="https://rdrr.io/r/stats/influence.measures.html">influence.measures()</a></code> function:</p>
<ul>
<li>
<code>influence.measures(my_model)</code> will give you out a dataframe of the various measures.</li>
<li>
<code>summary(influence.measures(my_model))</code> will provide a nice summary of what R deems to be the influential points.</li>
</ul>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 10 <a href="https://uoepsy.github.io/dapr2/2223/labs/1_10_assump_diag.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_09_assumptions_diagnostics#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section><section id="section-c-mock-exam-questions" class="level1"><h1>Section C: Mock Exam Questions</h1>
<p>In the exam, there will be 3 sections containing different types of questions, as outlined below:</p>
<ul>
<li>Section A: You will answer multiple choice questions (see Question 1 for an example)</li>
<li>Section B: You will solve by-hand calculation problems (see Question 2 for an example)</li>
<li>Section C: You will be asked questions about basic <code>R</code>-code and to interpret results of analyses (see Question 3 for an example)</li>
</ul>
<p>Below there is a mock question from each section described above - note that solutions are <strong>not</strong> provided. These are just to give you an example of the types of questions you will be presented with. If you have questions about these, ask your tutor or come to office hours to discuss.</p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Which assumption is being checked in the following line of code:</p>
<p><code>residualPlots(model1)</code></p>
<ul>
<li>A: Linearity</li>
<li>B: Normality</li>
<li>C: Independence</li>
<li>D: Equal variances / Homoscedasticity</li>
</ul>
</div>
<p class="question-end">
</p>
<p><br></p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Using the values below, calculate <span class="math inline">\(R^2\)</span>.</p>
<ul>
<li>SS<sub>Model</sub> = 70</li>
<li>SS<sub>Residual</sub> = 56</li>
<li>SS<sub>Total</sub> = 126</li>
</ul>
</div>
<p class="question-end">
</p>
<p><br></p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Researchers have a sample of 100 people, and they have measured their resting heart rate (<code>rhr</code>) and their caffeine consumption (<code>caffeine</code>). They were interested in estimating how caffeine consumption was associated with differences in resting heart rate, after controlling for age (<code>age</code>; since heart rate increases with advancing age and because they thought that older people tend to drink less caffeine).</p>
<p>From the following output (see <a href="#fig-mock_q3">Figure&nbsp;7</a>), write out and interpret the regression equation for the model following APA guidelines.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mock_q3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/mock_q3-new.png" class="img-fluid figure-img" style="width:90.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;7: Caffeinated Heart Rates</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
      <div class="nav-footer-center">© Copyright 2019-2022 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
  </div>
</footer>


</body></html>