<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Effects Coding</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR2</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intro-to-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Intro to Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intro-to-linear-models">
<li>
    <a class="dropdown-item" href="./1_01_function.html">
 <span class="dropdown-text">1/1: Functions and Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_slr.html">
 <span class="dropdown-text">1/2: Intro to Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_mlr.html">
 <span class="dropdown-text">1/3: Multiple Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_model_fit.html">
 <span class="dropdown-text">1/4: Model Fit and Standardization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_05_cat_recap.html">
 <span class="dropdown-text">1/5: Cat Predictors &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">More Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more-linear-models">
<li>
    <a class="dropdown-item" href="./1_07_int1_nc.html">
 <span class="dropdown-text">1/7: Interactions I: Num x Cat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_08_int2_nn.html">
 <span class="dropdown-text">1/8: Interactions II: Num x Num</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_09_int3_cc.html">
 <span class="dropdown-text">1/9: Interactions III: Cat x Cat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_10_assump_diag.html">
 <span class="dropdown-text">1/10: Assumptions &amp; Diagnostics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_11_writeup_recap.html">
 <span class="dropdown-text">1/11: Write Up &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysing-experimental-studies" role="button" data-bs-toggle="dropdown" aria-expanded="false">Analysing Experimental Studies</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysing-experimental-studies">
<li class="dropdown-header">2/1: Model Comparison</li>
        <li>
    <a class="dropdown-item" href="./2_02_effects.html">
 <span class="dropdown-text">2/2: Effects Coding</span></a>
  </li>  
        <li class="dropdown-header">2/3: Contrasts</li>
        <li class="dropdown-header">2/4: Simple Effects &amp; Pairwise Comparisons</li>
        <li class="dropdown-header">2/5: Write Up &amp; Recap</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-topics-for-lm" role="button" data-bs-toggle="dropdown" aria-expanded="false">Advanced Topics for LM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-topics-for-lm">
<li class="dropdown-header">2/6: Binary Logistic Regression</li>
        <li class="dropdown-header">2/7: More Logistic Regression</li>
        <li class="dropdown-header">2/8: Sample Size &amp; Power Analysis</li>
        <li class="dropdown-header">2/9: Write Up &amp; Recap</li>
        <li class="dropdown-header">2/10: Mock Exam</li>
    </ul>
</li>
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#study-overview" id="toc-study-overview" class="nav-link active" data-scroll-target="#study-overview">Study Overview</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li>
<a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
<li>
<a href="#levels-of-variable-side-constraints" id="toc-levels-of-variable-side-constraints" class="nav-link" data-scroll-target="#levels-of-variable-side-constraints">Levels of Variable &amp; Side Constraints</a>
  <ul class="collapse">
<li><a href="#levels-of-variable" id="toc-levels-of-variable" class="nav-link" data-scroll-target="#levels-of-variable">Levels of variable</a></li>
  </ul>
</li>
  </ul>
</li>
  <li><a href="#anova-f-test" id="toc-anova-f-test" class="nav-link" data-scroll-target="#anova-f-test">ANOVA F-test</a></li>
  <li><a href="#reference-group-dummy-constraint" id="toc-reference-group-dummy-constraint" class="nav-link" data-scroll-target="#reference-group-dummy-constraint">Reference group (dummy) constraint</a></li>
  <li><a href="#sum-to-zero-effects-constraint" id="toc-sum-to-zero-effects-constraint" class="nav-link" data-scroll-target="#sum-to-zero-effects-constraint">Sum-to-zero (effects) constraint</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Effects Coding</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand how to specify dummy and effects coding</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed previous lab exercises from <a href="https://uoepsy.github.io/dapr2/2223/labs/2_01_model_comps.html">Week 1</a>
</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>psych</strong></li>
<li><strong>kableExtra</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/RestaurantSpending.csv">here</a> or read it in via this link https://uoepsy.github.io/data/RestaurantSpending.csv</p>
</section>
</div>
<section id="study-overview" class="level1"><h1>Study Overview</h1>
<blockquote class="blockquote">
<p><strong>Research Question</strong></p>
<p>Does the type of background music playing in a restaurant influence the amount of money that diners spend on their meal?</p>
</blockquote>
<p>A group of researchers wanted to test the claims reported in <span class="citation" data-cites="North2003">(<a href="#ref-North2003" role="doc-biblioref">North, Shilcock, and Hargreaves 2003</a>)</span> on whether the type of background music playing in a restaurant influences the average amount of money spent by diners on their meal.</p>
<p>The group researchers got in touch with a restaurant and asked to alternate silence, popular music, and classical music on successive nights over 18 days. On those nights they recorded the mean spend per head for each table.</p>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Restaurant Spending Codebook</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>The following variables were collected:</p>
<ul>
<li>
<code>id</code>: Identifier for each diner</li>
<li>
<code>type</code>: type of music played (“Classical Music”, “Pop Music”, “No Music”)</li>
<li>
<code>amount</code>: restaurant spending per person (in pounds - £)</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first ten rows of the data are:</p>
<div class="cell">
<div class="cell-output-display">

<div id="lgdzhkhtjw" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#lgdzhkhtjw .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#lgdzhkhtjw .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lgdzhkhtjw .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#lgdzhkhtjw .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#lgdzhkhtjw .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lgdzhkhtjw .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lgdzhkhtjw .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#lgdzhkhtjw .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#lgdzhkhtjw .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#lgdzhkhtjw .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#lgdzhkhtjw .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#lgdzhkhtjw .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#lgdzhkhtjw .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#lgdzhkhtjw .gt_from_md > :first-child {
  margin-top: 0;
}

#lgdzhkhtjw .gt_from_md > :last-child {
  margin-bottom: 0;
}

#lgdzhkhtjw .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#lgdzhkhtjw .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#lgdzhkhtjw .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#lgdzhkhtjw .gt_row_group_first td {
  border-top-width: 2px;
}

#lgdzhkhtjw .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lgdzhkhtjw .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#lgdzhkhtjw .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#lgdzhkhtjw .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lgdzhkhtjw .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lgdzhkhtjw .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#lgdzhkhtjw .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#lgdzhkhtjw .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lgdzhkhtjw .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lgdzhkhtjw .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#lgdzhkhtjw .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lgdzhkhtjw .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#lgdzhkhtjw .gt_left {
  text-align: left;
}

#lgdzhkhtjw .gt_center {
  text-align: center;
}

#lgdzhkhtjw .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#lgdzhkhtjw .gt_font_normal {
  font-weight: normal;
}

#lgdzhkhtjw .gt_font_bold {
  font-weight: bold;
}

#lgdzhkhtjw .gt_font_italic {
  font-style: italic;
}

#lgdzhkhtjw .gt_super {
  font-size: 65%;
}

#lgdzhkhtjw .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#lgdzhkhtjw .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#lgdzhkhtjw .gt_indent_1 {
  text-indent: 5px;
}

#lgdzhkhtjw .gt_indent_2 {
  text-indent: 10px;
}

#lgdzhkhtjw .gt_indent_3 {
  text-indent: 15px;
}

#lgdzhkhtjw .gt_indent_4 {
  text-indent: 20px;
}

#lgdzhkhtjw .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">id</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">type</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">amount</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_left">No Music</td>
<td class="gt_row gt_right">23.14891</td>
</tr>
<tr>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_left">Pop Music</td>
<td class="gt_row gt_right">20.59492</td>
</tr>
<tr>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_left">Pop Music</td>
<td class="gt_row gt_right">19.18172</td>
</tr>
<tr>
<td class="gt_row gt_right">4</td>
<td class="gt_row gt_left">Pop Music</td>
<td class="gt_row gt_right">16.70237</td>
</tr>
<tr>
<td class="gt_row gt_right">5</td>
<td class="gt_row gt_left">Classical Music</td>
<td class="gt_row gt_right">25.91041</td>
</tr>
<tr>
<td class="gt_row gt_right">6</td>
<td class="gt_row gt_left">Pop Music</td>
<td class="gt_row gt_right">19.27888</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section><section id="setup" class="level1"><h1>Setup</h1>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the Restaurant Spending dataset into R, assigning it to an object named <code>rest_spend</code>
</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#Loading the required package(s)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://personality-project.org/r/psych/">psych</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co">#Reading in data and storing in object named 'rest_spend'</span></span>
<span><span class="va">rest_spend</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">'https://uoepsy.github.io/data/RestaurantSpending.csv'</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="exercises" class="level1"><h1>Exercises</h1>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Examine the dataset, and perform any necessary and appropriate data management steps.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>Let’s have a look at the data to see what we’re working with:</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#first look at dataset structure</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spec_tbl_df [360 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ id    : num [1:360] 1 2 3 4 5 6 7 8 9 10 ...
 $ type  : chr [1:360] "No Music" "Pop Music" "Pop Music" "Pop Music" ...
 $ amount: num [1:360] 23.1 20.6 19.2 16.7 25.9 ...
 - attr(*, "spec")=
  .. cols(
  ..   id = col_double(),
  ..   type = col_character(),
  ..   amount = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#now lets look at top 6 rows (or the head) of the dataset</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
     id type            amount
  &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
1     1 No Music          23.1
2     2 Pop Music         20.6
3     3 Pop Music         19.2
4     4 Pop Music         16.7
5     5 Classical Music   25.9
6     6 Pop Music         19.3</code></pre>
</div>
</div>
<p>Music type is a categorical variable but it is encoded as a character (<code>&lt;chr&gt;</code>) variable rather than a factor (<code>&lt;fctr&gt;</code>). Let’s fix this, and rename ‘type’ to ‘music’ and the levels of the factor to avoid repetition whilst we’re at it:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">rest_spend</span> <span class="op">&lt;-</span> <span class="va">rest_spend</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>        type <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">type</span>, </span>
<span>                           levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"No Music"</span>, <span class="st">"Pop Music"</span>, <span class="st">"Classical Music"</span><span class="op">)</span>,</span>
<span>                           labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"None"</span>, <span class="st">"Pop"</span>, <span class="st">"Classical"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>        <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>music <span class="op">=</span> <span class="va">type</span><span class="op">)</span></span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#re-examine the top 6 rows of the dataset</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
     id music     amount
  &lt;dbl&gt; &lt;fct&gt;      &lt;dbl&gt;
1     1 None        23.1
2     2 Pop         20.6
3     3 Pop         19.2
4     4 Pop         16.7
5     5 Classical   25.9
6     6 Pop         19.3</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Formally state:</p>
<ul>
<li>a linear model to investigate whether there are differences in types of memory deficits for those experiencing different cognitive impairment(s)</li>
<li>your chosen significance level</li>
<li>the null and alternative hypotheses</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">

</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Provide a table of descriptive statistics and visualise your data (remember to interpret your plot in the context of the research question).</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>For your table of descriptive statistics, both the <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> functions will come in handy here.</p></li>
<li><p>When visualising the data, consider using <code><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot()</a></code> to visually explore the association between restaurant spending and music type.</p></li>
<li><p>Make sure to comment on any observed differences among the sample means of the three background music types.</p></li>
</ol>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>First, lets look at our descriptive statistics and present in a well formatted table:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">music_desc</span> <span class="op">&lt;-</span> <span class="va">rest_spend</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>            <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">music</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>            <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>                      Mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">amount</span><span class="op">)</span>,</span>
<span>                      SD <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">amount</span><span class="op">)</span>,</span>
<span>                      Min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">amount</span><span class="op">)</span>,</span>
<span>                      Max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">amount</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>            <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span>caption <span class="op">=</span> <span class="st">"Descriptive Statistics"</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>            <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">music_desc</span></span></code></pre></div>
<div class="cell-output-display">
<div id="tbl-music-descript" class="anchored">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Table 1:  Descriptive Statistics </caption>
 <thead><tr>
<th style="text-align:left;"> music </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> Mean </th>
   <th style="text-align:right;"> SD </th>
   <th style="text-align:right;"> Min </th>
   <th style="text-align:right;"> Max </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:left;"> None </td>
   <td style="text-align:right;"> 120 </td>
   <td style="text-align:right;"> 22.14 </td>
   <td style="text-align:right;"> 3.44 </td>
   <td style="text-align:right;"> 13.71 </td>
   <td style="text-align:right;"> 33.43 </td>
  </tr>
<tr>
<td style="text-align:left;"> Pop </td>
   <td style="text-align:right;"> 120 </td>
   <td style="text-align:right;"> 21.90 </td>
   <td style="text-align:right;"> 2.97 </td>
   <td style="text-align:right;"> 15.60 </td>
   <td style="text-align:right;"> 28.94 </td>
  </tr>
<tr>
<td style="text-align:left;"> Classical </td>
   <td style="text-align:right;"> 120 </td>
   <td style="text-align:right;"> 24.17 </td>
   <td style="text-align:right;"> 1.89 </td>
   <td style="text-align:right;"> 19.05 </td>
   <td style="text-align:right;"> 28.02 </td>
  </tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Now, lets visualise the association between restaurant spending and music type using a boxplot:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">rest_spend</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">music</span>, y <span class="op">=</span> <span class="va">amount</span>, fill <span class="op">=</span> <span class="va">music</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">'Background music type'</span>, y <span class="op">=</span> <span class="st">'Restaurant spending (in GBP)'</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p1</span> </span></code></pre></div>
<div class="cell-output-display">
<div id="fig-music-desc" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_02_effects_files/figure-html/fig-music-desc-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 1: Associations among Spending and Music Type</figcaption><p></p>
</figure>
</div>
</div>
</div>
<ul>
<li>There are three types of music groups (<span class="math inline">\(g = 3\)</span>), where there is one group for each music type: “Classical,” “None,” “Pop”. Each group has 120 observations.</li>
<li>It seems that customers without background music or pop music had a similar average restaurant spending</li>
<li>The average restaurant spending seems to be higher for those who had a classical music background compared to the customers either without music or with a pop music background.</li>
</ul>
</div>
<p class="solution-end">
</p>
<p><br></p>
<section id="levels-of-variable-side-constraints" class="level2"><h2 class="anchored" data-anchor-id="levels-of-variable-side-constraints">Levels of Variable &amp; Side Constraints</h2>
<section id="levels-of-variable" class="level3"><h3 class="anchored" data-anchor-id="levels-of-variable">Levels of variable</h3>
<p><code>R</code> by default orders the levels of a categorical variable in alphabetical order:</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "None"      "Pop"       "Classical"</code></pre>
</div>
</div>
<p>If we follow the same approach and order the groups by alphabetical ordering, we can represent the data as follows:</p>
<table class="table">
<colgroup>
<col style="width: 23%">
<col style="width: 21%">
<col style="width: 30%">
<col style="width: 23%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Population Name</th>
<th style="text-align: center;">Population ID</th>
<th style="text-align: center;">Sample observations</th>
<th style="text-align: center;">Population mean</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Classical</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(y_{1,1}, y_{1,2}, ..., y_{1,n}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{1}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">None</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(y_{2,1}, y_{2,2}, ..., y_{2,n}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{2}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Pop</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;"><span class="math inline">\(y_{3,1}, y_{3,2}, ..., y_{3,n}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{3}\)</span></td>
</tr>
</tbody>
</table>
<section id="sum-to-zero-constraint---effects-coding" class="level4 frame"><h4 class="anchored" data-anchor-id="sum-to-zero-constraint---effects-coding">Sum to zero constraint - effects coding</h4>
<p>Under the constraint <span class="math inline">\(\beta_1 + \beta_2 + \beta_3 = 0\)</span>, the model coefficients are interpreted as follows:</p>
<ul>
<li>
<span class="math inline">\(\beta_0 = \mu\)</span> is interpreted as the overall or global mean — that is, the population mean when all the groups are combined;</li>
<li>
<span class="math inline">\(\beta_i = \mu_i - \mu\)</span> is interpreted as the effect of group <span class="math inline">\(i\)</span> — that is, the difference between the population mean for group <span class="math inline">\(i\)</span>, <span class="math inline">\(\mu_i\)</span>, and the global population mean, <span class="math inline">\(\mu\)</span>.</li>
</ul>
<p>We can fit the linear regression model:</p>
<p><span class="math display">\[
y
= b_0
+ b_1 \ \text{EffectLevel1}
+ b_2 \ \text{EffectLevel2}
+ \epsilon
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\text{EffectLevel1} = \begin{cases}
1  &amp; \text{if observation is from category 1} \\
0  &amp; \text{if observation is from category 2} \\
-1 &amp; \text{otherwise}
\end{cases}
\\
\text{EffectLevel2} = \begin{cases}
0  &amp; \text{if observation is from category 1} \\
1  &amp; \text{if observation is from category 2} \\
-1 &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>Schematically,</p>
<p><span class="math display">\[
\begin{matrix}
\textbf{Level}  &amp; \textbf{EffectLevel1} &amp; \textbf{EffectLevel2} \\
\hline
\text{Classical}       &amp; 1   &amp; 0    \\
\text{None}            &amp; 0   &amp; 1    \\
\text{Pop}             &amp; -1  &amp; -1
\end{matrix}
\]</span></p>
<div class="blue">
<p>In <strong>R</strong> this is simply done by saying:</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.sum"</span></span>
<span><span class="va">mdl_sum</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">amount</span> <span class="op">~</span> <span class="va">music</span>, data <span class="op">=</span> <span class="va">rest_spend</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">mdl_sum</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      music1      music2 
 22.7381560  -0.5967688  -0.8392158 </code></pre>
</div>
</div>
<p>where <code>music</code> is a factor. In such case <code>R</code> will automatically create the two variables <code>EffectLevel1</code> and <code>EffectLevel2</code> for you!</p>
<p>The <code>summary(mdl)</code> will return 3 estimated coefficients:</p>
<ul>
<li>
<span class="math inline">\(b_0 = 22.74\)</span> is estimated overall mean</li>
<li>
<span class="math inline">\(b_1 = 1.44\)</span> is the effect of Classical Music</li>
<li>
<span class="math inline">\(b_2 = -0.6\)</span> is the effect of No Music</li>
<li>
<strong>NOTE</strong>: The effect of Pop Music is not shown by <code>summary</code> as it is found via the side-constraint as <span class="math inline">\(b_3 = -(b_1 + b_2) = -0.84\)</span>!</li>
</ul>
</div>
</section><section id="reference-group-constraint---dummy-coding" class="level4 frame"><h4 class="anchored" data-anchor-id="reference-group-constraint---dummy-coding">Reference group constraint - dummy coding</h4>
<p>Under the constraint <span class="math inline">\(\beta_1 = 0\)</span>, meaning that the first factor level is the reference group,</p>
<ul>
<li>
<span class="math inline">\(\beta_0\)</span> is interpreted as <span class="math inline">\(\mu_1\)</span>, the mean response for the reference group (group 1);</li>
<li>
<span class="math inline">\(\beta_i\)</span> is interpreted as the difference between the mean response for group <span class="math inline">\(i\)</span> and the reference group.</li>
</ul>
<p>We can fit the linear regression model:</p>
<p><span class="math display">\[
y
= b_0
+ b_1 \ \text{IsTypeNoMusic}
+ b_2 \ \text{IsTypePopMusic}
+\epsilon
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\text{IsTypeNoMusic} = \begin{cases}
1 &amp; \text{if observation is from the No Music category} \\
0 &amp; \text{otherwise}
\end{cases}
\\
\text{IsTypePopMusic} = \begin{cases}
1 &amp; \text{if observation is from the Pop Music category} \\
0 &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>Schematically,</p>
<p><span class="math display">\[
\begin{matrix}
\textbf{Level}  &amp; \textbf{IsTypeNoMusic} &amp; \textbf{IsTypePopMusic} \\
\hline
\text{Classical}       &amp; 0   &amp; 0   \\
\text{None}            &amp; 1   &amp; 0   \\
\text{Pop}             &amp; 0   &amp; 1
\end{matrix}
\]</span></p>
<div class="blue">
<p>In <strong>R</strong> this is simply done by saying:</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.treatment"</span></span>
<span><span class="va">mdl_trt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">amount</span> <span class="op">~</span> <span class="va">music</span>, data <span class="op">=</span> <span class="va">rest_spend</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">mdl_trt</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept)       musicPop musicClassical 
    22.1413872     -0.2424471      2.0327533 </code></pre>
</div>
</div>
<p>where <code>music</code> is a factor. In such case R will automatically create the two dummy variables <code>IsMusicNone</code> and <code>IsMusicPop</code> for you!</p>
<p>The <code>summary(mdl)</code> will return 3 estimated coefficients:</p>
<ul>
<li>
<span class="math inline">\(b_0 = 24.17\)</span> is the mean of the base level (level 1)</li>
<li>
<span class="math inline">\(b_1 = -2.03\)</span> is the effect of None</li>
<li>
<span class="math inline">\(b_2 = -2.28\)</span> is the effect of Pop</li>
<li>
<strong>NOTE</strong>: The effect of Classical is not shown as it is equal to zero by the constraint!</li>
</ul>
</div>
</section></section></section></section><section id="anova-f-test" class="level1"><h1>ANOVA F-test</h1>
<p>Since <code>R</code> uses the reference group constraint, in this section and the next one, we will not specify any side-constraints, meaning that <span class="math inline">\(\beta_1 = 0\)</span>.</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Fit a linear model to the data, having <code>amount</code> as response variable and the factor <code>music</code> as predictor. Call the fitted model <code>mdl_rg</code> (for reference group constraint)</p>
<p>Identify the relevant pieces of information from the commands <code>anova(mdl_rg)</code> and <code>summary(mdl_rg)</code> that can be used to conduct an ANOVA <span class="math inline">\(F\)</span>-test against the null hypothesis that all population means are equal.</p>
<p>Interpret the <span class="math inline">\(F\)</span>-test results in the context of the ANOVA null hypothesis.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl_rg</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">amount</span> <span class="op">~</span> <span class="va">music</span>, data <span class="op">=</span> <span class="va">rest_spend</span><span class="op">)</span></span>
<span><span class="va">mdl_rg</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = amount ~ music, data = rest_spend)

Coefficients:
   (Intercept)        musicPop  musicClassical  
       22.1414         -0.2424          2.0328  </code></pre>
</div>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_rg</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = amount ~ music, data = rest_spend)

Residuals:
   Min     1Q Median     3Q    Max 
-8.433 -1.886  0.127  1.755 11.285 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     22.1414     0.2593  85.373  &lt; 2e-16 ***
musicPop        -0.2424     0.3668  -0.661    0.509    
musicClassical   2.0328     0.3668   5.542 5.81e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.841 on 357 degrees of freedom
Multiple R-squared:  0.1151,    Adjusted R-squared:  0.1101 
F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
</div>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl_rg</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: amount
           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
music       2  374.7 187.348  23.211 3.335e-10 ***
Residuals 357 2881.5   8.071                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The model summary returns the <span class="math inline">\(F\)</span>-test of model utility which, in this case, corresponds to the ANOVA <span class="math inline">\(F\)</span>-test against the null hypothesis of equal population means.</p>
<p>The relevant line from <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> is:</p>
<pre><code>F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<p>The relevant parts from <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> are:</p>
<ul>
<li>
<code>F value</code> of <code>23.211</code>
</li>
<li>The <code>Df</code> column giving <code>2</code> and <code>357</code> degrees of freedom</li>
<li>The p-value of the test, reported under <code>Pr(&gt;F)</code> as <code>3.335e-10 ***</code>.</li>
</ul>
<p>We can write this up as follows:</p>
<div class="int">
<p>We performed an analysis of variance against the null hypothesis of equal population mean spending across three types of background music, <span class="math inline">\(F(2, 357) = 23.21\)</span>, <span class="math inline">\(p &lt; .001\)</span>.</p>
<p>The large observed <span class="math inline">\(F\)</span>-statistic led to a very small <em>p</em>-value, meaning that such a large observed variability among the mean restaurant spending across the different music types, compared to the variability in the residuals, is very unlikely to happen by chance alone if the population means where all the same.</p>
<p>For this reason, at the 5% significance level, we reject the null hypothesis as there is strong evidence that at least two population means differ.</p>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="reference-group-dummy-constraint" class="level1"><h1>Reference group (dummy) constraint</h1>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Examine and investigate the meaning of the coefficients in the output of <code>summary(mdl_rg)</code>. Next, obtain the estimated (or predicted) group means for the “Classical”, “None”, and “Pop” groups by using the <code>predict(mdl_rg, newdata = ...)</code> function.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>Let’s recall the model summary:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_rg</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = amount ~ music, data = rest_spend)

Residuals:
   Min     1Q Median     3Q    Max 
-8.433 -1.886  0.127  1.755 11.285 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     22.1414     0.2593  85.373  &lt; 2e-16 ***
musicPop        -0.2424     0.3668  -0.661    0.509    
musicClassical   2.0328     0.3668   5.542 5.81e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.841 on 357 degrees of freedom
Multiple R-squared:  0.1151,    Adjusted R-squared:  0.1101 
F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
</div>
</div>
<p>The interpretation is as follows</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Coefficient</th>
<th style="text-align: center;">Estimate</th>
<th style="text-align: center;">Corresponds to</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">(Intercept)</td>
<td style="text-align: center;">24.1741</td>
<td style="text-align: center;"><span class="math inline">\(\hat \beta_0 = \hat \mu_1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">musicNone</td>
<td style="text-align: center;">-2.0328</td>
<td style="text-align: center;"><span class="math inline">\(\hat \beta_2 = \hat \mu_2 - \hat \beta_0 = \hat \mu_2 - \hat \mu_1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">musicPop</td>
<td style="text-align: center;">-2.2752</td>
<td style="text-align: center;"><span class="math inline">\(\hat \beta_3 = \hat \mu_3 - \hat \beta_0 = \hat \mu_3 - \hat \mu_1\)</span></td>
</tr>
</tbody>
</table>
<p>The estimate corresponding to (Intercept) contains <span class="math inline">\(\hat \beta_0 = \hat \mu_1 = 24.17\)</span>. The estimated average spending for those having a classical music background is approximately £24.2.</p>
<p>The next estimate corresponds to <code>musicNone</code> and is <span class="math inline">\(\hat \beta_2 = -2.033\)</span>. The difference in mean spending between <code>None</code> and <code>Classical</code> is estimated to be <span class="math inline">\(-2.033\)</span>. In other words, people with a silent background seem to spend approximately £2 less than those having a classical music background.</p>
<p>The estimate corresponding to <code>musicPop</code> is <span class="math inline">\(\hat \beta_3 = -2.275\)</span>. This is the estimated difference in mean spending between <code>Pop</code> and <code>Classical</code>. People with a pop music background seem to spend approximately £2.3 less than those with a classical music background.</p>
<p>Hence, for all levels except the reference group we see differences to the reference group while the estimate of the reference level can be found next to <code>(Intercept)</code>.</p>
<p>It is also important to notice how the coefficients names are written. They are a combination of <code>factor name</code> and <code>level name</code>, such as <code>musicNone</code>. The only coefficient that is missing is <code>musicClassical</code>, the one corresponding to the reference category <code>Classical</code>.</p>
<p>To use <code>preditct</code>, you first need to define a data frame with a column having the same name as the factor in the fitted model. Then, specify all the groups (= levels) for which you would like the predicted mean.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">query_groups</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>music <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Classical"</span>, <span class="st">"None"</span>, <span class="st">"Pop"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">query_groups</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 1
  music    
  &lt;chr&gt;    
1 Classical
2 None     
3 Pop      </code></pre>
</div>
</div>
<p>Pass the data frame to the predict function using the <code>newdata =</code> argument. The predict function will match the column named <code>music</code> with the predictor called <code>music</code> in the fitted model <code>mdl_rg</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mdl_rg</span>, newdata <span class="op">=</span> <span class="va">query_groups</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3 
24.17414 22.14139 21.89894 </code></pre>
</div>
</div>
<p>Or:</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">query_groups</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pred <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mdl_rg</span>, newdata <span class="op">=</span> <span class="va">.</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  music      pred
  &lt;chr&gt;     &lt;dbl&gt;
1 Classical  24.2
2 None       22.1
3 Pop        21.9</code></pre>
</div>
</div>
<p>Hence,</p>
<ul>
<li><span class="math inline">\(\hat \mu_\text{Classical} = \hat \mu_1 = 24.17\)</span></li>
<li><span class="math inline">\(\hat \mu_\text{None} = \hat \mu_2 = 22.14\)</span></li>
<li><span class="math inline">\(\hat \mu_\text{Pop} = \hat \mu_3 = 21.90\)</span></li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>It actually makes more sense to have “None” as reference group for music.</p>
<p>Open the help page of the function <code><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel()</a></code>, and look at the examples.</p>
<p>Within the <code>rest_sped</code> data, reorder the levels of the factor <code>music</code> so that your reference group is “None”.</p>
<div class="yellow">
<p><strong>NOTE</strong></p>
<p>Because you reordered the levels, now</p>
<ul>
<li>
<span class="math inline">\(\mu_1\)</span> = mean of no music group</li>
<li>
<span class="math inline">\(\mu_2\)</span> = mean of classical music group</li>
<li>
<span class="math inline">\(\mu_3\)</span> = mean of pop music group</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>Check the help page:</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="op">?</span><span class="va">fct_relevel</span></span></code></pre></div>
</div>
<p>Select “None” to be the first level:</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span>, <span class="st">"None"</span><span class="op">)</span></span></code></pre></div>
</div>
<p>Check that the factor levels are now in the correct order:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "None"      "Pop"       "Classical"</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Refit the linear model, and inspect the model summary once more.</p>
<p>Do you notice any change in the estimated coefficients? Do you notice any change in the F-test for model utility?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl_rg</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">amount</span> <span class="op">~</span> <span class="va">music</span>, data <span class="op">=</span> <span class="va">rest_spend</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_rg</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = amount ~ music, data = rest_spend)

Residuals:
   Min     1Q Median     3Q    Max 
-8.433 -1.886  0.127  1.755 11.285 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     22.1414     0.2593  85.373  &lt; 2e-16 ***
musicPop        -0.2424     0.3668  -0.661    0.509    
musicClassical   2.0328     0.3668   5.542 5.81e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.841 on 357 degrees of freedom
Multiple R-squared:  0.1151,    Adjusted R-squared:  0.1101 
F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
</div>
</div>
<p>The displayed coefficients have changed as now the (Intercept) represents the new reference group, which is “None”.</p>
<p>However, by checking the calculations, this model is equivalent to the previous one as the predicted group means are the same.</p>
<ul>
<li>Predicted mean of “None” <span class="math inline">\(\hat \mu_\text{None}\)</span> = 22.1414</li>
<li>Predicted mean of “Classical” <span class="math inline">\(\hat \mu_\text{Classical}\)</span> = 22.1414 + 2.0328 = 24.1742</li>
<li>Predicted mean of “Pop” = <span class="math inline">\(\hat \mu_\text{Pop}\)</span> = 22.1414 - 0.2424 = 21.899</li>
</ul>
<p>The <code>predict</code> function returns the same output:</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">query_groups</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>music <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">query_groups</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 1
  music    
  &lt;chr&gt;    
1 None     
2 Pop      
3 Classical</code></pre>
</div>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">query_groups</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pred <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mdl_rg</span>, newdata <span class="op">=</span> <span class="va">.</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  music      pred
  &lt;chr&gt;     &lt;dbl&gt;
1 None       22.1
2 Pop        21.9
3 Classical  24.2</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="sum-to-zero-effects-constraint" class="level1"><h1>Sum-to-zero (effects) constraint</h1>
<p>Let’s now change the side-constraint from the <code>R</code> default (the reference group or <code>contr.treatment</code> constraint) to the sum-to-zero constraint using <code>contr.sum</code>.</p>
<p>Recall that under this constraint the interpretation of the coefficients becomes:</p>
<ul>
<li>
<span class="math inline">\(\beta_0\)</span> represents the global mean</li>
<li>
<span class="math inline">\(\beta_i\)</span> the effect due to group <span class="math inline">\(i\)</span> — that is, the mean response in group <span class="math inline">\(i\)</span> minus the global mean</li>
</ul>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Set the sum to zero constraint for the factor <code>music</code> of background music.</p>
<p>Fit again the linear model using <code>amount</code> as response variable and <code>music</code> as predictor. Call the fitted model using the sum to zero constraint <code>mdl_stz</code> (for sum to zero).</p>
<p>Examine the output of the <code>summary(mdl_stz)</code> function:</p>
<ul>
<li>Do the displayed coefficients change? What do they represent now?</li>
<li>Do the predicted group means change?</li>
<li>Is the model utility F-test still the same? Why do you think it’s the case?</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<p>Set the sum to zero contrast to the <code>music</code> factor:</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.sum"</span></span></code></pre></div>
</div>
<p>Re-fit the model and inspect the summary output:</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl_stz</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">amount</span> <span class="op">~</span> <span class="va">music</span>, data <span class="op">=</span> <span class="va">rest_spend</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_stz</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = amount ~ music, data = rest_spend)

Residuals:
   Min     1Q Median     3Q    Max 
-8.433 -1.886  0.127  1.755 11.285 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  22.7382     0.1497 151.856  &lt; 2e-16 ***
music1       -0.5968     0.2118  -2.818   0.0051 ** 
music2       -0.8392     0.2118  -3.963 8.94e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.841 on 357 degrees of freedom
Multiple R-squared:  0.1151,    Adjusted R-squared:  0.1101 
F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
</div>
</div>
<p>With the new side-constraint, we get different values for the model coefficients because the meaning of the parameters has changed. If we closely inspect the output, we can also notice that a slightly different naming has been used.</p>
<p>Instead of <code>factor name</code> and <code>level name</code> (such as <code>musicNone</code>), we get <code>factor name</code> and <code>level number</code> (e.g.&nbsp;<code>music1</code>). Here, <code>music1</code> simply means the first level of the factor <code>music</code>, while <code>music2</code> means the second level of the factor <code>music</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "None"      "Pop"       "Classical"</code></pre>
</div>
</div>
<p>The first level is “No Music”, while the second level is “Classical Music”.</p>
<ul>
<li>The estimate for <code>(Intercept)</code> is now the <em>global mean</em> of the data.</li>
<li>The estimate for <code>music1</code> is now the difference of the first group (“None”) to the global mean</li>
<li>The estimate for <code>music2</code> is now the difference of the second group (“Classical”) to the global mean</li>
</ul>
<p>The estimate for <code>music3</code>, representing the difference of “Pop” to the global mean is not shown. Because of the side-constraint, we know it must be <span class="math inline">\(\beta_3 = - (\beta_1 + \beta_2) = - (-0.5968 + 1.4360) = -0.8392\)</span>.</p>
<p>Underneath we see the group effects that need to be added to the global mean to obtain the predicted group means.</p>
<p>Compute the predicted group means:</p>
<div class="cell">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">query_groups</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pred <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mdl_stz</span>, newdata <span class="op">=</span> <span class="va">.</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  music      pred
  &lt;chr&gt;     &lt;dbl&gt;
1 None       22.1
2 Pop        21.9
3 Classical  24.2</code></pre>
</div>
</div>
<p>We notice that we get the same predicted group means independently of the side-constraint.</p>
<p>The predicted means do <em>not</em> depend on the side-constraint that we apply. However, the side-constraint influences the meaning of the parameters in the model.</p>
</div>
<p class="solution-end">
</p>
<div class="blue">
<p><strong>In <strong>R</strong>, we can switch back to the default reference group constraint by either of these</strong></p>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># Option 1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span><span class="co"># Option 2</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.treatment"</span></span></code></pre></div>
</div>
</div>



</section><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-North2003" class="csl-entry" role="doc-biblioentry">
North, A., A. Shilcock, and D. Hargreaves. 2003. <span>“The Effect of Musical Style on Restaurant Customers’ Spending.”</span> <em>Environment and Behavior</em> 35: 712–18.
</div>
</div></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
      <div class="nav-footer-center">© Copyright 2019-2022 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
  </div>
</footer>


</body></html>