<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Contrasts</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR2</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intro-to-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Intro to Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intro-to-linear-models">
<li>
    <a class="dropdown-item" href="./1_01_function.html">
 <span class="dropdown-text">1/1: Functions and Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_slr.html">
 <span class="dropdown-text">1/2: Intro to Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_mlr.html">
 <span class="dropdown-text">1/3: Multiple Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_model_fit.html">
 <span class="dropdown-text">1/4: Model Fit and Standardization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_05_cat_recap.html">
 <span class="dropdown-text">1/5: Cat Predictors &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">More Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more-linear-models">
<li>
    <a class="dropdown-item" href="./1_07_int1_nc.html">
 <span class="dropdown-text">1/7: Interactions I: Num x Cat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_08_int2_nn.html">
 <span class="dropdown-text">1/8: Interactions II: Num x Num</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_09_int3_cc.html">
 <span class="dropdown-text">1/9: Interactions III: Cat x Cat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_10_assump_diag.html">
 <span class="dropdown-text">1/10: Assumptions &amp; Diagnostics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_11_writeup_recap.html">
 <span class="dropdown-text">1/11: Write Up &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysing-experimental-studies" role="button" data-bs-toggle="dropdown" aria-expanded="false">Analysing Experimental Studies</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysing-experimental-studies">
<li class="dropdown-header">2/1: Model Comparison</li>
        <li class="dropdown-header">2/2: Effects Coding</li>
        <li>
    <a class="dropdown-item" href="./2_03_contrasts.html">
 <span class="dropdown-text">2/3: Contrasts</span></a>
  </li>  
        <li class="dropdown-header">2/4: Simple Effects &amp; Pairwise Comparisons</li>
        <li class="dropdown-header">2/5: Write Up &amp; Recap</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-topics-for-lm" role="button" data-bs-toggle="dropdown" aria-expanded="false">Advanced Topics for LM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-topics-for-lm">
<li class="dropdown-header">2/6: Binary Logistic Regression</li>
        <li class="dropdown-header">2/7: More Logistic Regression</li>
        <li class="dropdown-header">2/8: Sample Size &amp; Power Analysis</li>
        <li class="dropdown-header">2/9: Write Up &amp; Recap</li>
        <li class="dropdown-header">2/10: Mock Exam</li>
    </ul>
</li>
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#study-overview" id="toc-study-overview" class="nav-link active" data-scroll-target="#study-overview">Study Overview</a></li>
  <li>
<a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a>
  <ul class="collapse">
<li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design">Study Design</a></li>
  <li><a href="#factorial-anova" id="toc-factorial-anova" class="nav-link" data-scroll-target="#factorial-anova">Factorial ANOVA</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Contrasts</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand how to specify contracts to test specific effects.</li>
<li>Understand different types of study design.</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed previous lab exercises from <a href="https://uoepsy.github.io/dapr2/2223/labs/2_01_model_comps.html">Week 1</a> and <a href="https://uoepsy.github.io/dapr2/2223/labs/2_02_effects.html">Week 2</a>
</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>psych</strong></li>
<li><strong>kableExtra</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/caffeinedrink.csv">here</a> or read it in via this link https://uoepsy.github.io/data/caffeinedrink.csv</p>
</section>
</div>
<section id="study-overview" class="level1"><h1>Study Overview</h1>
<blockquote class="blockquote">
<p><strong>Research Question</strong></p>
<p>Does WPM differ by caffeine treatment condition?</p>
</blockquote>
<p>To investigate if the number of words typed per minute (WPM) differs among caffeine treatment conditions, the researchers conducted an experiment where participants were randomly allocated to one of four treatment conditions. Two of these conditions included non-caffeinated drinks - control (water) and mint tea, and the other two caffeinated drinks - coffee and red bull.</p>
<table class="table">
<thead><tr class="header">
<th style="text-align: center;">Drink</th>
<th style="text-align: center;">Caffeine</th>
<th style="text-align: center;">Temp</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Control (Water)</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Cold</td>
</tr>
<tr class="even">
<td style="text-align: center;">Red Bull</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Cold</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Coffee</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Hot</td>
</tr>
<tr class="even">
<td style="text-align: center;">Mint Tea</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Hot</td>
</tr>
</tbody>
</table>
<p>The researchers were specifically interested in the following comparisons:</p>
<ul>
<li>Whether having some kind of caffeine (i.e., red bull / coffee), rather than no caffeine (i.e., control - water / mint tea), resulted in a difference in average WPM</li>
<li>Whether there was a difference in average WPM between those with hot drinks (i.e., mint tea / coffee) in comparison to those with cold drinks (control - water / red bull)</li>
</ul>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Caffeine data codebook</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>Data from 40 participants containing information on words typed per minute (WPM) and the caffeine treatment condition was collected.</p>
<p>The data in <code>caffeinedrink.csv</code> contained two attributes collected from <span class="math inline">\(n=40\)</span> participants:</p>
<ul>
<li>
<code>treatment</code>: Which one of four treatment conditions the participant was assigned - control, coffee, mint_tea, or red_bull</li>
<li>
<code>wpm</code>: average number of words typed per minute</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell">
<div class="cell-output-display">

<div id="ezlgdzhkht" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ezlgdzhkht .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ezlgdzhkht .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ezlgdzhkht .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ezlgdzhkht .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ezlgdzhkht .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ezlgdzhkht .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ezlgdzhkht .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ezlgdzhkht .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ezlgdzhkht .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ezlgdzhkht .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ezlgdzhkht .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ezlgdzhkht .gt_from_md > :first-child {
  margin-top: 0;
}

#ezlgdzhkht .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ezlgdzhkht .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ezlgdzhkht .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ezlgdzhkht .gt_row_group_first td {
  border-top-width: 2px;
}

#ezlgdzhkht .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ezlgdzhkht .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ezlgdzhkht .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ezlgdzhkht .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ezlgdzhkht .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ezlgdzhkht .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ezlgdzhkht .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_left {
  text-align: left;
}

#ezlgdzhkht .gt_center {
  text-align: center;
}

#ezlgdzhkht .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ezlgdzhkht .gt_font_normal {
  font-weight: normal;
}

#ezlgdzhkht .gt_font_bold {
  font-weight: bold;
}

#ezlgdzhkht .gt_font_italic {
  font-style: italic;
}

#ezlgdzhkht .gt_super {
  font-size: 65%;
}

#ezlgdzhkht .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#ezlgdzhkht .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ezlgdzhkht .gt_indent_1 {
  text-indent: 5px;
}

#ezlgdzhkht .gt_indent_2 {
  text-indent: 10px;
}

#ezlgdzhkht .gt_indent_3 {
  text-indent: 15px;
}

#ezlgdzhkht .gt_indent_4 {
  text-indent: 20px;
}

#ezlgdzhkht .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">treatment</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">wpm</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left">control</td>
<td class="gt_row gt_right">109.43</td>
</tr>
<tr>
<td class="gt_row gt_left">control</td>
<td class="gt_row gt_right">113.83</td>
</tr>
<tr>
<td class="gt_row gt_left">control</td>
<td class="gt_row gt_right">113.22</td>
</tr>
<tr>
<td class="gt_row gt_left">control</td>
<td class="gt_row gt_right">110.46</td>
</tr>
<tr>
<td class="gt_row gt_left">control</td>
<td class="gt_row gt_right">116.23</td>
</tr>
<tr>
<td class="gt_row gt_left">control</td>
<td class="gt_row gt_right">113.12</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section><section id="setup" class="level1"><h1>Setup</h1>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the caffeinedrink dataset into R, assigning it to an object named <code>caffeine</code>
</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="va">caffeine</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/caffeinedrink.csv"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 40 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): treatment
dbl (1): wpm

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Check for the correct coding of all variables (i.e., categorical variables should be factors and numeric variables should be numeric).</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>Treatment is a categorical variable but it is coded as a character (<code>&lt;chr&gt;</code>), so we need to correct this:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">caffeine</span> <span class="op">&lt;-</span> <span class="va">caffeine</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>treatment <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">treatment</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Numerically and visually summarise the <code>caffeine</code> dataset. Comment on any observed differences among treatment groups.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">caffeine</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">treatment</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>, </span>
<span>            M <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">wpm</span><span class="op">)</span>, </span>
<span>            SD <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">wpm</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  treatment     n     M    SD
  &lt;fct&gt;     &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1 coffee       10  114.  1.82
2 control      10  112.  1.98
3 mint_tea     10  111.  2.13
4 red_bull     10  117.  2.15</code></pre>
</div>
</div>
<p>We have a continuous outcome and a categorical predictor - a boxplot would be most appropriate for visualisations:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">caffeine</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">treatment</span>, y <span class="op">=</span> <span class="va">wpm</span>, color <span class="op">=</span> <span class="va">treatment</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">'Treatment Condition'</span>, y <span class="op">=</span> <span class="st">'WPM'</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_03_contrasts_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="int">
<p>From the boxplots, it seems that those in the Red Bull condition, on average, typed the most WPM, whilst those in the Mint Tea condition the fewest.</p>
<p>Overall, the average WPM appears to be lower for those in the non-caffeine conditions (i.e., control - water / mint tea) in comparison to those in the caffeine drinks condition (red bull / coffee).</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Set an appropriate reference group based on the research question.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>It would make most sense to have the ‘Control’ caffeine treatment condition as our reference group.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">caffeine</span><span class="op">$</span><span class="va">treatment</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">caffeine</span><span class="op">$</span><span class="va">treatment</span>, <span class="st">"control"</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Fit the following model, and assign it the name “caf_mdl1”.</p>
<p>Examine and describe the coefficients in the output of <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> before interpreting the F-test results from <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> in the context of the ANOVA null hypothesis.</p>
<p><span class="math inline">\(\text{WPM} = \beta_0 + \beta_1 \cdot \text{Treatment (Category)} + \epsilon\)</span></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">caf_mdl1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wpm</span> <span class="op">~</span> <span class="va">treatment</span>, data<span class="op">=</span><span class="va">caffeine</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">caf_mdl1</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wpm ~ treatment, data = caffeine)

Residuals:
   Min     1Q Median     3Q    Max 
-3.652 -1.362 -0.151  1.125  4.729 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       112.1460     0.6402 175.179  &lt; 2e-16 ***
treatmentcoffee     2.3350     0.9053   2.579   0.0141 *  
treatmentmint_tea  -1.0550     0.9053  -1.165   0.2516    
treatmentred_bull   4.5060     0.9053   4.977 1.61e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.024 on 36 degrees of freedom
Multiple R-squared:  0.5563,    Adjusted R-squared:  0.5194 
F-statistic: 15.05 on 3 and 36 DF,  p-value: 1.651e-06</code></pre>
</div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">caf_mdl1</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: wpm
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
treatment  3 185.00  61.666  15.047 1.651e-06 ***
Residuals 36 147.54   4.098                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="int">
<p>The estimate corresponding to (Intercept) contains <span class="math inline">\(\hat \beta_0 = \hat \mu_1 = 112.1460\)</span>. The estimated average WPM for those in the control condition (water) is approximately 112.15.</p>
<p>The next estimate corresponds to <code>treatmentcoffee</code> and is <span class="math inline">\(\hat \beta_2 = 2.3350\)</span>. The difference in mean WPM between <code>Control</code> and <code>Coffee</code> is estimated to be <span class="math inline">\(2.3350\)</span>. In other words, people who have had a coffee type approximately 2.3 words per minute more than those who have had water.</p>
<p>The estimate corresponding to <code>treatmentmint_tea</code> is <span class="math inline">\(\hat \beta_3 = -1.0550\)</span>. This is the estimated difference in mean WPM between <code>Control</code> and <code>Mint Tea</code> is estimated to be <span class="math inline">\(-1.0550\)</span>. In other words, people who have had a mint tea type approximately 1.1 words per minute less than those who have had water.</p>
<p>The estimate corresponding to <code>treatmentred_bull</code> is <span class="math inline">\(\hat \beta_4 = 4.5060\)</span>. This is the estimated difference in mean WPM between <code>Control</code> and <code>Red Bull</code> is estimated to be <span class="math inline">\(4.5060\)</span>. In other words, people who have had a red bull type approximately 4.5 words per minute more than those who have had water.</p>
<p>We performed an analysis of variance against the null hypothesis of equal population mean spending across four types of treatment condition. At the 5% significance level, we reject the null hypothesis as there is strong evidence that at least a pair of means differ from each other <span class="math inline">\(F(3, 36) = 15.05\)</span>, <span class="math inline">\(p &lt; .001\)</span>.</p>
<p>As an example, suppose you are testing whether <span class="math inline">\(H_0: \mu_{A} = \mu_{B} = \mu_{C} = \mu_{D}\)</span>. If a pair of those differs, e.g.&nbsp;<span class="math inline">\(\mu_{C} \neq \mu_{D}\)</span>, then the claim doesn’t hold.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>The two planned comparisons that the researchers were interested in can be translated into the following research hypotheses:</p>
$$
<span class="math display">\[\begin{aligned}
1. \quad H_0 &amp;: \mu_\text{No Caffeine} = \mu_\text{Caffeine} \\

    \quad H_0 &amp;: \frac{1}{2} (\mu_\text{Control} + \mu_\text{Mint Tea}) = \frac{1}{2} (\mu_\text{Coffee} + \mu_\text{Red Bull}) \\



2. \quad H_0 &amp;: \mu_\text{Hot Drink} = \mu_\text{Cold Drink} \\
    \quad H_0 &amp;: \frac{1}{2} (\mu_\text{Coffee} + \mu_\text{Mint Tea}) = \frac{1}{2} (\mu_\text{Control} + \mu_\text{Red Bull})

\end{aligned}\]</span>
<p>$$</p>
<p>After checking the levels of the factor <code>treatment</code>, use <code>emmeans</code> to obtain the estimated treatment means and uncertainties for your factor. <em>Hint</em> use plot() to visualise this.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">caffeine</span><span class="op">$</span><span class="va">treatment</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "control"  "coffee"   "mint_tea" "red_bull"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/rvlenth/emmeans">emmeans</a></span><span class="op">)</span></span>
<span><span class="va">emm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">caf_mdl1</span>, <span class="op">~</span> <span class="va">treatment</span><span class="op">)</span></span>
<span><span class="va">emm</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> treatment emmean   SE df lower.CL upper.CL
 control      112 0.64 36      111      113
 coffee       114 0.64 36      113      116
 mint_tea     111 0.64 36      110      112
 red_bull     117 0.64 36      115      118

Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">emm</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_03_contrasts_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Specify the coefficients of the comparisons and run the contrast analysis. Obtain 95% confidence intervals, and then interpret your results in relation to the researchers hypotheses.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">comp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"No Caffeine - Caffeine"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="fl">2</span>, <span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">2</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">2</span>, <span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span>,</span>
<span>             <span class="st">"Hot Drink - Cold Drink"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">2</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">2</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">2</span>, <span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span></span>
<span>             <span class="op">)</span></span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">comp_res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">emm</span>, method <span class="op">=</span> <span class="va">comp</span><span class="op">)</span></span>
<span><span class="va">comp_res</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast               estimate   SE df t.ratio p.value
 No Caffeine - Caffeine    -3.95 0.64 36  -6.167  &lt;.0001
 Hot Drink - Cold Drink    -1.61 0.64 36  -2.520  0.0163</code></pre>
</div>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">comp_res</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast               estimate   SE df lower.CL upper.CL
 No Caffeine - Caffeine    -3.95 0.64 36    -5.25   -2.650
 Hot Drink - Cold Drink    -1.61 0.64 36    -2.91   -0.315

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>The hypothesis test for the first contrast could be reported as follows:</p>
<div class="int">
<p>We performed a test against <span class="math inline">\(H_0: \frac{1}{2}(\mu_1 + \mu_3) - \frac{1}{2}(\mu_2 + \mu_4) = 0\)</span>. At the 5% significance level, there was evidence that the mean WPM for those who were in the no caffeine condition was significantly different from those in a caffeine condition <span class="math inline">\(t(36) = -6.17, p = &lt; .001\)</span> (two-sided). We are 95% confident that those who consumed no caffeine typed, on average, between 2.7 and 5.3 words less per minute than those who consumed some form of caffeine <span class="math inline">\(CI_{95}[-5.25, -2.65]\)</span>.</p>
</div>
<p>The hypothesis test for the second contrast could be reported as follows:</p>
<div class="int">
<p>We performed a test against <span class="math inline">\(H_0: \frac{1}{2}(\mu_2 + \mu_3) - \frac{1}{2}(\mu_1 + \mu_4) = 0\)</span>. At the 5% significance level, there was evidence that the average WPM for those in the hot drink condition significantly differed from those in the cold drink condition <span class="math inline">\(t(36) = -2.52, p = .02\)</span> (two-sided). We are 95% confident that those who consumed a hot drink typed, on average, between 0.3 and 2.9 words less per minute than those who consumed a cold drink <span class="math inline">\(CI_{95}[-2.91, -0.32]\)</span>.</p>
</div>
</div>
<p class="solution-end">
</p>
<section id="study-design" class="level2"><h2 class="anchored" data-anchor-id="study-design">Study Design</h2>
<p>For each of the below experiment descriptions, note (1) the design, (2) number of variables of interest, (3) levels of categorical variables, (4) what you think the reference group should be and why.</p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>A group of researchers were interested in whether sleep deprivation influenced reaction time. They hypothesised that sleep deprived individuals would have slower reaction times than non-sleep deprived individuals.</p>
<p>To test this, they recruited 60 participants who were matched on a number of demographic variables including age and sex. One member of each pair (e.g., female aged 18) was placed into a different sleep condition - ‘Sleep Deprived’ (4 hours per night) or ‘Non-Sleep Deprived’ (8 hours per night).</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<ol type="1">
<li>Design = Between-person: Matched pairs</li>
<li>No of variables of interest = 2 - Sleep Condition and Reaction Time</li>
<li>Levels of variables = Sleep Condition has 2 levels - Sleep Deprived and Non-Sleep Deprived; Reaction Time is a continuous measure, so has no associated levels</li>
<li>Reference Groups = Sleep Condition - Non-Sleep Deprived because the RQ stated that the researchers were interested in how the sleep deprived group <em>differed from</em> the non-sleep deprived group.</li>
</ol>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>A group of researchers were interested in replicating an experiment testing the Stroop Effect.</p>
<p>They recruited 50 participants who took part in Task A (word colour and meaning are congruent) and Task B (word colour and meaning are incongruent) where they were asked to name the color of the ink instead of reading the word. The order of presentation was counterbalanced across participants. The researchers hypothesised that participants would take significantly more time (‘response time’ measured in seconds) to complete Task B than Task A.</p>
<p>You can test yourself here for fun: <a href="https://www.psytoolkit.org/lessons/experiment_stroop.html">Stroop Task</a></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<ol type="1">
<li>Design = Within-person: repeated measures</li>
<li>No of variables of interest = 2 - Task and Response Time</li>
<li>Levels of variables = Task has 2 levels - A and B; Response Time is a continuous measure, so has no associated levels</li>
<li>Reference Groups = Task - A because the RQ stated that the researchers were interested in how response time in Task B <em>differed from</em> the response time in Task A.</li>
</ol>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>A group of researchers wanted to test a hypothesised theory according to which patients with amnesia will have a deficit in explicit memory but not implicit memory. Huntingtons patients, on the other hand, will display the opposite: they will have no deficit in explicit memory, but will have a deficit in implicit memory.</p>
<p>To test this, researchers designed a study that included two variables: ‘Diagnosis’ (Amnesic, Huntingtons, Control) and ‘Task’ (Grammar, Classification, Recognition) where participants were randomly assigned to a Task condition. The first two tasks (Grammar and Classification) are known to reflect implicit memory processes, whereas the Recognition task is known to reflect explicit memory processes.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<ol type="1">
<li>Design = Between-person: 3×3 factorial design</li>
<li>No of variables of interest = 2 - Diagnosis and Task</li>
<li>Levels of variables = Diagnosis has 3 levels - Amnesic, Huntingtons, and Control; Task has 3 levels - Grammar, Classification, and Recognition</li>
<li>Reference Groups = Diagnosis - Control; Task - Recognition. We have chosen Control since the other two groups have some form of cognitive impairment; and the Recognition task since it measures explicit memory whilst the other two task types implicit.</li>
</ol>
</div>
<p class="solution-end">
</p>
</section><section id="factorial-anova" class="level2"><h2 class="anchored" data-anchor-id="factorial-anova">Factorial ANOVA</h2>
<p>Next week, the lab will focus on Experiment 3 described above. You have already worked with <em>some</em> of this data before - see <a href="https://uoepsy.github.io/dapr2/labs/1_08_int_cc.html">semester 1 week 8 lab</a>, but we now have a third task condition - Classification.</p>
<p><strong>Data download link:</strong> https://uoepsy.github.io/data/cognitive_experiment.csv</p>
<p>We have data from the 45 participants (15 amnesiacs, 15 Huntington individuals, and 15 controls). Recall that study involves two factors, now with three levels each. For each combination of factor levels we have 5 observations:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 45 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (3): Diagnosis, Task, Y

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Attaching package: 'kableExtra'


The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Values from `Y` are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = {summary_fun}` to summarise duplicates.
* Use the following dplyr code to identify duplicates.
  {data} %&gt;%
    dplyr::group_by(Diagnosis, Task) %&gt;%
    dplyr::summarise(n = dplyr::n(), .groups = "drop") %&gt;%
    dplyr::filter(n &gt; 1L)</code></pre>
</div>
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1"></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Task</div></th>
</tr>
<tr>
<th style="text-align:left;"> Diagnosis </th>
   <th style="text-align:left;"> grammar </th>
   <th style="text-align:left;"> classification </th>
   <th style="text-align:left;"> recognition </th>
  </tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;"> amnesic </td>
   <td style="text-align:left;"> 44, 63, 76, 72, 45 </td>
   <td style="text-align:left;"> 72, 66, 55, 82, 75 </td>
   <td style="text-align:left;"> 70, 51, 82, 66, 56 </td>
  </tr>
<tr>
<td style="text-align:left;"> huntingtons </td>
   <td style="text-align:left;"> 24, 30, 51, 55, 40 </td>
   <td style="text-align:left;"> 53, 59, 33, 37, 43 </td>
   <td style="text-align:left;"> 107, 80, 98, 82, 108 </td>
  </tr>
<tr>
<td style="text-align:left;"> control </td>
   <td style="text-align:left;"> 76, 98, 71, 70, 85 </td>
   <td style="text-align:left;"> 92, 65, 86, 67, 90 </td>
   <td style="text-align:left;"> 107, 80, 101, 82, 105 </td>
  </tr>
</tbody>
</table>
</div>
</div>
<p>The five observations are assumed to come from a population having a specific mean. The population means corresponding to each combination of factor levels can be schematically written as:</p>
<p><span class="math display">\[
\begin{matrix}
                   &amp;         &amp;         &amp; \textbf{Task} &amp; \\
                   &amp;         &amp; (j=1)\text{ grammar} &amp; (j=2)\text{ classification} &amp; (j=3)\text{ recognition} \\
                   &amp; (i=1)\text{ control} &amp; \mu_{1,1} &amp; \mu_{1,2} &amp; \mu_{1,3} \\
\textbf{Diagnosis} &amp; (i=2)\text{ amnesic} &amp; \mu_{2,1} &amp; \mu_{2,2} &amp; \mu_{2,3} \\
                   &amp; (i=3)\text{ huntingtons} &amp; \mu_{3,1} &amp; \mu_{3,2} &amp; \mu_{3,3}
\end{matrix}
\]</span></p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Repeat the steps outlined in the Semester 1 Week 8 lab, but using the new dataset.</p>
<ul>
<li>Read the cognitive experiment data into R.</li>
<li>Convert categorical variables into factors, and assign more informative labels to the factor levels according to the data description provided above.</li>
<li>Relevel the <code>Diagnosis</code> factor to have ‘Control’ as the reference group.</li>
<li>Relevel the <code>Task</code> factor to have ‘Recognition’ as the reference group.</li>
<li>Rename the response variable from <code>Y</code> to <code>Score</code>.</li>
<li>Describe the data.</li>
<li>Visualise the interaction between Diagnosis and Task.</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<p>Load the tidyverse library and read the data into R:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">'https://uoepsy.github.io/data/cognitive_experiment.csv'</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 45 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (3): Diagnosis, Task, Y

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">cog</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Diagnosis  Task     Y
      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1         1     1    44
2         1     1    63
3         1     1    76
4         1     1    72
5         1     1    45
6         1     2    72</code></pre>
</div>
</div>
<p>We will now convert <code>Diagnosis</code> and <code>Task</code> into factors, making the labels of each factor level more meaningful.</p>
<p>According to the data description, the encoding of the factor <code>Diagnosis</code> is: 1 = amnesic patients, 2 = Huntingtons patients, and 3 are control patients.The encoding for the factor <code>Task</code> is: 1 = grammar task, 2 = classification task, and 3 = recognition task.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span>, </span>
<span>                        labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"amnesic"</span>, <span class="st">"huntingtons"</span>, <span class="st">"control"</span><span class="op">)</span>, </span>
<span>                        ordered <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span>, </span>
<span>                   labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"grammar"</span>, <span class="st">"classification"</span>, <span class="st">"recognition"</span><span class="op">)</span>, </span>
<span>                   ordered <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
</div>
<p>Relevel the <code>Diagnosis</code> factor so that the reference group is “Control”:</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span>, <span class="st">"control"</span><span class="op">)</span></span>
<span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span>, <span class="st">"recognition"</span><span class="op">)</span></span></code></pre></div>
</div>
<p>Rename the response:</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog</span> <span class="op">&lt;-</span> <span class="va">cog</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>Score <span class="op">=</span> <span class="va">Y</span><span class="op">)</span></span></code></pre></div>
</div>
<p>Look at the data:</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">cog</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Diagnosis Task           Score
  &lt;fct&gt;     &lt;fct&gt;          &lt;dbl&gt;
1 amnesic   grammar           44
2 amnesic   grammar           63
3 amnesic   grammar           76
4 amnesic   grammar           72
5 amnesic   grammar           45
6 amnesic   classification    72</code></pre>
</div>
</div>
<p>Describe data:</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog_stats</span> <span class="op">&lt;-</span> <span class="va">cog</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">Diagnosis</span>, <span class="va">Task</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>        Avg_Score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Score</span><span class="op">)</span>, </span>
<span>        SD <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Score</span><span class="op">)</span>,</span>
<span>        SE <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Score</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span>        <span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Diagnosis'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog_stats</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 5
# Groups:   Diagnosis [3]
  Diagnosis   Task           Avg_Score    SD    SE
  &lt;fct&gt;       &lt;fct&gt;              &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 control     recognition           95  13.0  5.81
2 control     grammar               80  11.7  5.22
3 control     classification        80  13.0  5.81
4 amnesic     recognition           65  12.2  5.44
5 amnesic     grammar               60  14.9  6.67
6 amnesic     classification        70  10.2  4.55
7 huntingtons recognition           95  13.4  5.98
8 huntingtons grammar               40  13.2  5.92
9 huntingtons classification        45  10.9  4.86</code></pre>
</div>
</div>
<p>Since we have not yet fitted our model, we cannot use the <code>emmip</code> function from <code>emmeans</code> or <code>plot_model</code> from <code>sjPlot</code>. We can however use a simple <code>ggplot</code> and use our summary scores from above:</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">cog_stats</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Task</span>, y <span class="op">=</span> <span class="va">Avg_Score</span>, color <span class="op">=</span> <span class="va">Diagnosis</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">Task</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_03_contrasts_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="int">
<p>Control patients consistently perform best across all tasks. They don’t seem to differ substantially in their scores between grammar and classification tasks, but they clearly perform better in the recognition task than the grammar and classification ones.</p>
<p>Amnesic patients appear to perform better than Huntingtons patients in grammar an classification tasks (reflecting intrinsic memory processes) and perform worse than Huntingtons patients in the recognition task (reflecting extrinsic memory processes).</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>The model with interaction is:</p>
<p><span class="math display">\[
\begin{aligned}
Score &amp;= \beta_0 \\
      &amp;+ \beta_1 D_\text{Control} + \beta_2 D_\text{Amnesic}   \\
      &amp;+ \beta_3 T_\text{Recognition}  + \beta_4 D_\text{Grammar} \\
      &amp;+ \beta_5 (D_\text{Control} * T_\text{Recognition}) + \beta_6 (D_\text{Amnesic} * T_\text{Recognition})  \\
      &amp;+ \beta_7 (D_\text{Control} * T_\text{Grammar}) + \beta_8 (D_\text{Amnesic} * T_\text{Grammar})  \\
      &amp;+ \epsilon
\end{aligned}
\]</span></p>
<p>Fit the above model, and set the the sum to zero constraint for <code>Diagnosis</code> of ‘Control’ and <code>Task</code> of ‘Recognition’.</p>
<p>Applying the sum to zero constraint, we would have:</p>
<p><span class="math display">\[
\begin{aligned}
\text{Intercept (global mean)} &amp;= \beta_0 \frac{\mu_{1,1} + \mu_{1,2} + \cdots + \mu_{3,3}}{9} \\
\beta_{Huntingtons} &amp;= -(\beta_1 + \beta_2) \\
\beta_{Classification} &amp;= -(\beta_3 + \beta_4) \\
\beta_{Huntingtons:Classification} &amp;= -(\beta_5 + \beta_6 + \beta_7 + \beta_8)
\end{aligned}
\]</span></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-13" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')"> Solution </span>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<p>The fitted model should be:</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.sum"</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.sum"</span></span>
<span><span class="va">mdl_int1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Score</span> <span class="op">~</span> <span class="va">Diagnosis</span> <span class="op">*</span> <span class="va">Task</span>, data <span class="op">=</span> <span class="va">cog</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_int1</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Score ~ Diagnosis * Task, data = cog)

Residuals:
   Min     1Q Median     3Q    Max 
   -16    -12      2     11     18 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        70.000      1.872  37.384  &lt; 2e-16 ***
Diagnosis1         15.000      2.648   5.664 1.95e-06 ***
Diagnosis2         -5.000      2.648  -1.888 0.067085 .  
Task1              15.000      2.648   5.664 1.95e-06 ***
Task2             -10.000      2.648  -3.776 0.000576 ***
Diagnosis1:Task1   -5.000      3.745  -1.335 0.190216    
Diagnosis2:Task1  -15.000      3.745  -4.005 0.000297 ***
Diagnosis1:Task2    5.000      3.745   1.335 0.190216    
Diagnosis2:Task2    5.000      3.745   1.335 0.190216    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.56 on 36 degrees of freedom
Multiple R-squared:  0.7318,    Adjusted R-squared:  0.6722 
F-statistic: 12.28 on 8 and 36 DF,  p-value: 2.844e-08</code></pre>
</div>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl_int1</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Score
               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Diagnosis       2   5250 2625.00 16.6373  7.64e-06 ***
Task            2   5250 2625.00 16.6373  7.64e-06 ***
Diagnosis:Task  4   5000 1250.00  7.9225 0.0001092 ***
Residuals      36   5680  157.78                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Next week, we will explore the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> and <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> output in detail. If you have time, note down what you think these estimates might be telling us. Remember, the interpretation of the estimates is now <em>different</em> from what you had in Semester 1 Week 8 - now each beta coefficient is the difference between a group mean and the <strong>overall</strong> mean.</p>
</div>
<p class="solution-end">
</p>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
      <div class="nav-footer-center">© Copyright 2019-2022 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
  </div>
</footer>


</body></html>