<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Simple Effects, Pairwise Comparisons, Corrections</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR2</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intro-to-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Intro to Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intro-to-linear-models">
<li>
    <a class="dropdown-item" href="./1_01_function.html">
 <span class="dropdown-text">1/1: Functions and Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_slr.html">
 <span class="dropdown-text">1/2: Intro to Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_mlr.html">
 <span class="dropdown-text">1/3: Multiple Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_model_fit.html">
 <span class="dropdown-text">1/4: Model Fit and Standardization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_05_cat_recap.html">
 <span class="dropdown-text">1/5: Cat Predictors &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">More Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more-linear-models">
<li>
    <a class="dropdown-item" href="./1_07_int1_nc.html">
 <span class="dropdown-text">1/7: Interactions I: Num x Cat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_08_int2_nn.html">
 <span class="dropdown-text">1/8: Interactions II: Num x Num</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_09_int3_cc.html">
 <span class="dropdown-text">1/9: Interactions III: Cat x Cat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_10_assump_diag.html">
 <span class="dropdown-text">1/10: Assumptions &amp; Diagnostics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_11_writeup_recap.html">
 <span class="dropdown-text">1/11: Write Up &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysing-experimental-studies" role="button" data-bs-toggle="dropdown" aria-expanded="false">Analysing Experimental Studies</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysing-experimental-studies">
<li>
    <a class="dropdown-item" href="./2_01_model_comps.html">
 <span class="dropdown-text">2/1: Model Comparison</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_02_effects.html">
 <span class="dropdown-text">2/2: Effects Coding</span></a>
  </li>  
        <li class="dropdown-header">2/3: Contrasts</li>
        <li class="dropdown-header">2/4: Simple Effects &amp; Pairwise Comparisons</li>
        <li class="dropdown-header">2/5: Write Up &amp; Recap</li>
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-topics-for-lm" role="button" data-bs-toggle="dropdown" aria-expanded="false">Advanced Topics for LM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-topics-for-lm">
<li class="dropdown-header">2/6: Binary Logistic Regression</li>
        <li class="dropdown-header">2/7: More Logistic Regression</li>
        <li class="dropdown-header">2/8: Sample Size &amp; Power Analysis</li>
        <li class="dropdown-header">2/9: Write Up &amp; Recap</li>
        <li class="dropdown-header">2/10: Mock Exam</li>
    </ul>
</li>
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#study-overview" id="toc-study-overview" class="nav-link active" data-scroll-target="#study-overview">Study Overview</a>
  <ul class="collapse">
<li><a href="#factorial-anova" id="toc-factorial-anova" class="nav-link" data-scroll-target="#factorial-anova">Factorial ANOVA</a></li>
  </ul>
</li>
  <li>
<a href="#recap" id="toc-recap" class="nav-link" data-scroll-target="#recap">Recap</a>
  <ul class="collapse">
<li><a href="#research-question-and-data" id="toc-research-question-and-data" class="nav-link" data-scroll-target="#research-question-and-data">Research question and data</a></li>
  </ul>
</li>
  <li><a href="#interaction-model" id="toc-interaction-model" class="nav-link" data-scroll-target="#interaction-model">Interaction Model</a></li>
  <li><a href="#contrast-analysis" id="toc-contrast-analysis" class="nav-link" data-scroll-target="#contrast-analysis">Contrast analysis</a></li>
  <li><a href="#simple-effects" id="toc-simple-effects" class="nav-link" data-scroll-target="#simple-effects">Simple Effects</a></li>
  <li><a href="#pairwise-comparisons" id="toc-pairwise-comparisons" class="nav-link" data-scroll-target="#pairwise-comparisons">Pairwise Comparisons</a></li>
  <li>
<a href="#multiple-comparisons" id="toc-multiple-comparisons" class="nav-link" data-scroll-target="#multiple-comparisons">Multiple Comparisons</a>
  <ul class="collapse">
<li><a href="#why-does-the-number-of-tests-matter" id="toc-why-does-the-number-of-tests-matter" class="nav-link" data-scroll-target="#why-does-the-number-of-tests-matter">Why does the number of tests matter?</a></li>
  </ul>
</li>
  <li>
<a href="#corrections" id="toc-corrections" class="nav-link" data-scroll-target="#corrections">Corrections</a>
  <ul class="collapse">
<li><a href="#bonferroni" id="toc-bonferroni" class="nav-link" data-scroll-target="#bonferroni">Bonferroni</a></li>
  <li><a href="#%C5%A1%C3%ADd%C3%A1k" id="toc-šídák" class="nav-link" data-scroll-target="#%C5%A1%C3%ADd%C3%A1k">Šídák</a></li>
  <li><a href="#tukey" id="toc-tukey" class="nav-link" data-scroll-target="#tukey">Tukey</a></li>
  <li><a href="#scheffe" id="toc-scheffe" class="nav-link" data-scroll-target="#scheffe">Scheffe</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Simple Effects, Pairwise Comparisons, Corrections</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand how to interpret simple effects for experimental designs</li>
<li>Understand how to conduct pairwise comparisons</li>
<li>Understand how to apply corrections available for multiple comparisons</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed previous lab exercises from Semester 1</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>psych</strong></li>
<li><strong>kableExtra</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/cognitive_experiment.csv">here</a> or read it in via this link https://uoepsy.github.io/data/cognitive_experiment.csv. Note, you have already worked with <em>some</em> of this data before - see <a href="https://uoepsy.github.io/dapr2/labs/1_08_int_cc.html">Semester 1 week 8 lab</a>, but we now have a third Task condition - Classification.</p>
</section>
</div>
<section id="study-overview" class="level1"><h1>Study Overview</h1>
<blockquote class="blockquote">
<p><strong>Research Question</strong></p>
<p>Are there differences in types of memory deficits for those experiencing different cognitive impairment(s)?</p>
</blockquote>
<p>In this week’s exercises, we will further explore questions such as:</p>
<ul>
<li>Does level <span class="math inline">\(i\)</span> of the first factor have an effect on the response?</li>
<li>Does level <span class="math inline">\(j\)</span> of the second factor have an effect on the response?</li>
<li>Is there a combined effect of level <span class="math inline">\(i\)</span> of the first factor and level <span class="math inline">\(j\)</span> of the second factor on the response? In other words, is there interaction of the two factors so that the combined effect is not simply the additive effect of level <span class="math inline">\(i\)</span> of the first factor plus the effect of level <span class="math inline">\(j\)</span> of the second factor?</li>
</ul>
<section id="factorial-anova" class="level2"><h2 class="anchored" data-anchor-id="factorial-anova">Factorial ANOVA</h2>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Cognitive Exp 3x3 Codebook</span></span>
</div>
<div class="optional-body" id="opt-body-1" style="display: none;">



<p><strong>Description</strong></p>
<p>The researchers designed a study yielding a 3 by 2 factorial design to test this theory. The first factor, “Diagnosis”, classifies the three types of individuals:</p>
<ul>
<li>1 denotes amnesic patients;</li>
<li>2 denotes Huntingtons patients; and</li>
<li>3 denotes a control group of individuals with no known neurological disorder.</li>
</ul>
<p>The second factor, “Task”, tells us to which of two tasks each study participant was randomly assigned to:</p>
<ul>
<li>1 = grammar task, which consists of classifying letter sequences as either following or not following grammatical rules; and</li>
<li>2 = recognition task, which consists of recognising particular stimuli as stimuli that have previously been presented during the task.</li>
<li>3 = classification task, which consists of</li>
</ul>
<p>The tasks chosen by the researchers have been picked to map onto the theoretical differences between the three types of research participants. The first task (grammar) is known to reflect implicit memory processes, whereas the recognition task is known to reflect explicit memory processes. If the theory is correct, we would expect the difference in scores between the recognition and grammar tasks to be relatively similar for the control and amnesiac groups, but relatively larger for the Huntingtons group compared to controls.</p>
<p><strong>Preview</strong></p>
<p>We have data from the 45 participants (15 amnesiacs, 15 Huntington individuals, and 15 controls). Recall that study involves two factors, now with three levels each. For each combination of factor levels we have 5 observations:</p>
<p>The first ten rows of the data are:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 45 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (3): Diagnosis, Task, Y

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Attaching package: 'kableExtra'


The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Values from `Y` are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = {summary_fun}` to summarise duplicates.
* Use the following dplyr code to identify duplicates.
  {data} %&gt;%
    dplyr::group_by(Diagnosis, Task) %&gt;%
    dplyr::summarise(n = dplyr::n(), .groups = "drop") %&gt;%
    dplyr::filter(n &gt; 1L)</code></pre>
</div>
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1"></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Task</div></th>
</tr>
<tr>
<th style="text-align:left;"> Diagnosis </th>
   <th style="text-align:left;"> grammar </th>
   <th style="text-align:left;"> classification </th>
   <th style="text-align:left;"> recognition </th>
  </tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;"> amnesic </td>
   <td style="text-align:left;"> 44, 63, 76, 72, 45 </td>
   <td style="text-align:left;"> 72, 66, 55, 82, 75 </td>
   <td style="text-align:left;"> 70, 51, 82, 66, 56 </td>
  </tr>
<tr>
<td style="text-align:left;"> huntingtons </td>
   <td style="text-align:left;"> 24, 30, 51, 55, 40 </td>
   <td style="text-align:left;"> 53, 59, 33, 37, 43 </td>
   <td style="text-align:left;"> 107, 80, 98, 82, 108 </td>
  </tr>
<tr>
<td style="text-align:left;"> control </td>
   <td style="text-align:left;"> 76, 98, 71, 70, 85 </td>
   <td style="text-align:left;"> 92, 65, 86, 67, 90 </td>
   <td style="text-align:left;"> 107, 80, 101, 82, 105 </td>
  </tr>
</tbody>
</table>
</div>
</div>
<p>The five observations are assumed to come from a population having a specific mean. The population means corresponding to each combination of factor levels can be schematically written as:</p>
<p><span class="math display">\[
\begin{matrix}
                   &amp;         &amp;         &amp; \textbf{Task} &amp; \\
                   &amp;         &amp; (j=1)\text{ grammar} &amp; (j=2)\text{ classification} &amp; (j=3)\text{ recognition} \\
                   &amp; (i=1)\text{ control} &amp; \mu_{1,1} &amp; \mu_{1,2} &amp; \mu_{1,3} \\
\textbf{Diagnosis} &amp; (i=2)\text{ amnesic} &amp; \mu_{2,1} &amp; \mu_{2,2} &amp; \mu_{2,3} \\
                   &amp; (i=3)\text{ huntingtons} &amp; \mu_{3,1} &amp; \mu_{3,2} &amp; \mu_{3,3}
\end{matrix}
\]</span></p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Repeat the steps outlined in the Semester 1 Week 8 lab, but using the new dataset.</p>
<ul>
<li>Read the cognitive experiment data into R.</li>
<li>Convert categorical variables into factors, and assign more informative labels to the factor levels according to the data description provided above.</li>
<li>Relevel the <code>Diagnosis</code> factor to have ‘Control’ as the reference group.</li>
<li>Relevel the <code>Task</code> factor to have ‘Recognition’ as the reference group.</li>
<li>Rename the response variable from <code>Y</code> to <code>Score</code>.</li>
<li>Describe the data.</li>
<li>Visualise the interaction between Diagnosis and Task.</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<p>Load the tidyverse library and read the data into R:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">'https://uoepsy.github.io/data/cognitive_experiment.csv'</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 45 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (3): Diagnosis, Task, Y

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">cog</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Diagnosis  Task     Y
      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1         1     1    44
2         1     1    63
3         1     1    76
4         1     1    72
5         1     1    45
6         1     2    72</code></pre>
</div>
</div>
<p>We will now convert <code>Diagnosis</code> and <code>Task</code> into factors, making the labels of each factor level more meaningful.</p>
<p>According to the data description, the encoding of the factor <code>Diagnosis</code> is: 1 = amnesic patients, 2 = Huntingtons patients, and 3 are control patients.The encoding for the factor <code>Task</code> is: 1 = grammar task, 2 = classification task, and 3 = recognition task.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span>, </span>
<span>                        labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"amnesic"</span>, <span class="st">"huntingtons"</span>, <span class="st">"control"</span><span class="op">)</span>, </span>
<span>                        ordered <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span>, </span>
<span>                   labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"grammar"</span>, <span class="st">"classification"</span>, <span class="st">"recognition"</span><span class="op">)</span>, </span>
<span>                   ordered <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
</div>
<p>Relevel the <code>Diagnosis</code> factor so that the reference group is “Control”:</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span> <span class="op">&lt;-</span> <span class="fu">fct_relevel</span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span>, <span class="st">"control"</span><span class="op">)</span></span>
<span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span> <span class="op">&lt;-</span> <span class="fu">fct_relevel</span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span>, <span class="st">"recognition"</span><span class="op">)</span></span></code></pre></div>
</div>
<p>Rename the response:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog</span> <span class="op">&lt;-</span> <span class="va">cog</span> <span class="op">%&gt;%</span></span>
<span>    <span class="fu">rename</span><span class="op">(</span>Score <span class="op">=</span> <span class="va">Y</span><span class="op">)</span></span></code></pre></div>
</div>
<p>Look at the data:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">cog</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Diagnosis Task           Score
  &lt;fct&gt;     &lt;fct&gt;          &lt;dbl&gt;
1 amnesic   grammar           44
2 amnesic   grammar           63
3 amnesic   grammar           76
4 amnesic   grammar           72
5 amnesic   grammar           45
6 amnesic   classification    72</code></pre>
</div>
</div>
<p>Describe data:</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog_stats</span> <span class="op">&lt;-</span> <span class="va">cog</span> <span class="op">%&gt;%</span> </span>
<span>    <span class="fu">group_by</span><span class="op">(</span><span class="va">Diagnosis</span>, <span class="va">Task</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>    <span class="fu">summarise</span><span class="op">(</span></span>
<span>        Avg_Score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Score</span><span class="op">)</span>, </span>
<span>        SD <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Score</span><span class="op">)</span>,</span>
<span>        SE <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Score</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu">n</span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span>        <span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Diagnosis'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog_stats</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 5
# Groups:   Diagnosis [3]
  Diagnosis   Task           Avg_Score    SD    SE
  &lt;fct&gt;       &lt;fct&gt;              &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 control     recognition           95  13.0  5.81
2 control     grammar               80  11.7  5.22
3 control     classification        80  13.0  5.81
4 amnesic     recognition           65  12.2  5.44
5 amnesic     grammar               60  14.9  6.67
6 amnesic     classification        70  10.2  4.55
7 huntingtons recognition           95  13.4  5.98
8 huntingtons grammar               40  13.2  5.92
9 huntingtons classification        45  10.9  4.86</code></pre>
</div>
</div>
<p>Since we have not yet fitted our model, we cannot use the <code>emmip</code> function from <code>emmeans</code> or <code>plot_model</code> from <code>sjPlot</code>. We can however use a simple <code>ggplot</code> and use our summary scores from above:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">cog_stats</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">Task</span>, y <span class="op">=</span> <span class="va">Avg_Score</span>, color <span class="op">=</span> <span class="va">Diagnosis</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_point</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">Task</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_04_emmeans_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="int">
<p>Control patients consistently perform best across all tasks. They don’t seem to differ substantially in their scores between grammar and classification tasks, but they clearly perform better in the recognition task than the grammar and classification ones.</p>
<p>Amnesic patients appear to perform better than Huntingtons patients in grammar an classification tasks (reflecting intrinsic memory processes) and perform worse than Huntingtons patients in the recognition task (reflecting extrinsic memory processes).</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>The model with interaction is:</p>
<p><span class="math display">\[
\begin{aligned}
Score &amp;= \beta_0 \\
      &amp;+ \beta_1 D_\text{Control} + \beta_2 D_\text{Amnesic}   \\
      &amp;+ \beta_3 T_\text{Recognition}  + \beta_4 D_\text{Grammar} \\
      &amp;+ \beta_5 (D_\text{Control} * T_\text{Recognition}) + \beta_6 (D_\text{Amnesic} * T_\text{Recognition})  \\
      &amp;+ \beta_7 (D_\text{Control} * T_\text{Grammar}) + \beta_8 (D_\text{Amnesic} * T_\text{Grammar})  \\
      &amp;+ \epsilon
\end{aligned}
\]</span></p>
<p>Fit the above model, and set the the sum to zero constraint for <code>Diagnosis</code> of ‘Control’ and <code>Task</code> of ‘Recognition’.</p>
<p>Applying the sum to zero constraint, we would have:</p>
<p><span class="math display">\[
\begin{aligned}
\text{Intercept (global mean)} &amp;= \beta_0 \frac{\mu_{1,1} + \mu_{1,2} + \cdots + \mu_{3,3}}{9} \\
\beta_{Huntingtons} &amp;= -(\beta_1 + \beta_2) \\
\beta_{Classification} &amp;= -(\beta_3 + \beta_4) \\
\beta_{Huntingtons:Classification} &amp;= -(\beta_5 + \beta_6 + \beta_7 + \beta_8)
\end{aligned}
\]</span></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>The fitted model should be:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.sum"</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.sum"</span></span>
<span><span class="va">mdl_int1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Score</span> <span class="op">~</span> <span class="va">Diagnosis</span> <span class="op">*</span> <span class="va">Task</span>, data <span class="op">=</span> <span class="va">cog</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_int1</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Score ~ Diagnosis * Task, data = cog)

Residuals:
   Min     1Q Median     3Q    Max 
   -16    -12      2     11     18 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        70.000      1.872  37.384  &lt; 2e-16 ***
Diagnosis1         15.000      2.648   5.664 1.95e-06 ***
Diagnosis2         -5.000      2.648  -1.888 0.067085 .  
Task1              15.000      2.648   5.664 1.95e-06 ***
Task2             -10.000      2.648  -3.776 0.000576 ***
Diagnosis1:Task1   -5.000      3.745  -1.335 0.190216    
Diagnosis2:Task1  -15.000      3.745  -4.005 0.000297 ***
Diagnosis1:Task2    5.000      3.745   1.335 0.190216    
Diagnosis2:Task2    5.000      3.745   1.335 0.190216    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.56 on 36 degrees of freedom
Multiple R-squared:  0.7318,    Adjusted R-squared:  0.6722 
F-statistic: 12.28 on 8 and 36 DF,  p-value: 2.844e-08</code></pre>
</div>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl_int1</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Score
               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Diagnosis       2   5250 2625.00 16.6373  7.64e-06 ***
Task            2   5250 2625.00 16.6373  7.64e-06 ***
Diagnosis:Task  4   5000 1250.00  7.9225 0.0001092 ***
Residuals      36   5680  157.78                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Next week, we will explore the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> and <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> output in detail. If you have time, note down what you think these estimates might be telling us. Remember, the interpretation of the estimates is now <em>different</em> from what you had in Semester 1 Week 8 - now each beta coefficient is the difference between a group mean and the <strong>overall</strong> mean.</p>
</div>
<p class="solution-end">
</p>


<section id="recap" class="level1"><h1>Recap</h1>
<p>You have (hopefully) already made a head start on this weeks exercises if you completed the Factorial ANOVA section of <a href="https://uoepsy.github.io/dapr2/labs/2_03_cont_design_factanova.html#Factorial_ANOVA">last week’s lab</a>. If you haven’t yet completed these two questions, do so before reading any further.</p>
<section id="research-question-and-data" class="level2"><h2 class="anchored" data-anchor-id="research-question-and-data">Research question and data</h2>
<p>As a reminder, we are working with data from a study yielding a <span class="math inline">\(3 \times 3\)</span> factorial design to test whether there are differences in types of memory deficits for those experiencing different cognitive impairment(s).</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 45 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (3): Diagnosis, Task, Y

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Values from `Score` are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = {summary_fun}` to summarise duplicates.
* Use the following dplyr code to identify duplicates.
  {data} %&gt;%
    dplyr::group_by(Diagnosis, Task) %&gt;%
    dplyr::summarise(n = dplyr::n(), .groups = "drop") %&gt;%
    dplyr::filter(n &gt; 1L)</code></pre>
</div>
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1"></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Task</div></th>
</tr>
<tr>
<th style="text-align:left;"> Diagnosis </th>
   <th style="text-align:left;"> grammar </th>
   <th style="text-align:left;"> classification </th>
   <th style="text-align:left;"> recognition </th>
  </tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;"> amnesic </td>
   <td style="text-align:left;"> 44, 63, 76, 72, 45 </td>
   <td style="text-align:left;"> 72, 66, 55, 82, 75 </td>
   <td style="text-align:left;"> 70, 51, 82, 66, 56 </td>
  </tr>
<tr>
<td style="text-align:left;"> huntingtons </td>
   <td style="text-align:left;"> 24, 30, 51, 55, 40 </td>
   <td style="text-align:left;"> 53, 59, 33, 37, 43 </td>
   <td style="text-align:left;"> 107, 80, 98, 82, 108 </td>
  </tr>
<tr>
<td style="text-align:left;"> control </td>
   <td style="text-align:left;"> 76, 98, 71, 70, 85 </td>
   <td style="text-align:left;"> 92, 65, 86, 67, 90 </td>
   <td style="text-align:left;"> 107, 80, 101, 82, 105 </td>
  </tr>
</tbody>
</table>
</div>
</div>
</section></section><section id="interaction-model" class="level1"><h1>Interaction Model</h1>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Let’s look at the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> and <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> output in detail from the model you should have previously fitted with the sum to zero constraint. As a reminder, the model with interaction is:</p>
<p><span class="math display">\[
\begin{aligned}
Score &amp;= \beta_0 \\
      &amp;+ \beta_1 D_\text{Control} + \beta_2 D_\text{Amnesic}   \\
      &amp;+ \beta_3 T_\text{Recognition}  + \beta_4 T_\text{Grammar} \\
      &amp;+ \beta_5 (D_\text{Control} * T_\text{Recognition}) + \beta_6 (D_\text{Amnesic} * T_\text{Recognition})  \\
      &amp;+ \beta_7 (D_\text{Control} * T_\text{Grammar}) + \beta_8 (D_\text{Amnesic} * T_\text{Grammar})  \\
      &amp;+ \epsilon
\end{aligned}
\]</span></p>
<p>Applying the sum to zero constraint (for <code>Diagnosis</code> of ‘Control’ and <code>Task</code> of ‘Recognition’), we would have:</p>
<p><span class="math display">\[
\begin{aligned}
\text{Intercept (global mean)} &amp;= \beta_0 \frac{\mu_{1,1} + \mu_{1,2} + \cdots + \mu_{3,3}}{9} \\
\beta_{Huntingtons} &amp;= -(\beta_1 + \beta_2) \\
\beta_{Classification} &amp;= -(\beta_3 + \beta_4) \\
\beta_{Huntingtons:Classification} &amp;= -(\beta_5 + \beta_6 + \beta_7 + \beta_8)
\end{aligned}
\]</span></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>Let’s look at the <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> and <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> output:</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.sum"</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.sum"</span></span>
<span><span class="va">mdl_int</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Score</span> <span class="op">~</span> <span class="va">Diagnosis</span> <span class="op">*</span> <span class="va">Task</span>, data <span class="op">=</span> <span class="va">cog</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl_int</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Score
               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Diagnosis       2   5250 2625.00 16.6373  7.64e-06 ***
Task            2   5250 2625.00 16.6373  7.64e-06 ***
Diagnosis:Task  4   5000 1250.00  7.9225 0.0001092 ***
Residuals      36   5680  157.78                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="int">
<p>Scores significantly differed by both Diagnosis (<span class="math inline">\(F(2, 36)=16.63, p &lt; .001\)</span>) and by Task (<span class="math inline">\(F(2, 36)=16.63, p &lt; .001\)</span>). The interaction between Diagnosis and Task was significant (<span class="math inline">\(F(4, 36)=7.92, p &lt; 0.001\)</span>). This provides evidence against the null hypothesis that effect of Task is constant across the different levels of Diagnosis.</p>
</div>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mdl_int</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Score ~ Diagnosis * Task, data = cog)

Residuals:
   Min     1Q Median     3Q    Max 
   -16    -12      2     11     18 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        70.000      1.872  37.384  &lt; 2e-16 ***
Diagnosis1         15.000      2.648   5.664 1.95e-06 ***
Diagnosis2         -5.000      2.648  -1.888 0.067085 .  
Task1              15.000      2.648   5.664 1.95e-06 ***
Task2             -10.000      2.648  -3.776 0.000576 ***
Diagnosis1:Task1   -5.000      3.745  -1.335 0.190216    
Diagnosis2:Task1  -15.000      3.745  -4.005 0.000297 ***
Diagnosis1:Task2    5.000      3.745   1.335 0.190216    
Diagnosis2:Task2    5.000      3.745   1.335 0.190216    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.56 on 36 degrees of freedom
Multiple R-squared:  0.7318,    Adjusted R-squared:  0.6722 
F-statistic: 12.28 on 8 and 36 DF,  p-value: 2.844e-08</code></pre>
</div>
</div>
<div class="int">
<p>The F-test for model utility is again significant at the 5% level: <span class="math inline">\(F(8,36) = 12.28, p &lt; .001\)</span>. An F-statistic this large or larger occurring by chance only is very small. In the presence of a significant interaction we <strong>do not</strong> interpret the main effects as their interpretation changes with the level of the other factor.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Based on previous plotting, it does seem that there is a clear interaction between diagnosis and task (as well as from our output above). However, we have not statistically compared our interaction model to an additive model (same model but without the interaction). Until we do so, we cannot confidently progress on the <em>assumption</em> that the interaction model is the most suitable for answering the research question.</p>
<p>We also want to consider the best coding constraint to apply in order to best answer the research question - are we interested in whether group X (e.g., Amnesic) differed from group Y (e.g., Huntingtons), or whether group X (e.g., Amnesic) differed from the overall group mean?</p>
<p>Since we are interested in comparing groups, we should reset to dummy coding, and thus should re-run our interaction model. Next, we need to perform a model comparison between the additive model and the interaction model using the <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> function.</p>
<p>After re-running your model with dummy coding, interpret the result of the model comparison.</p>
<p><span class="math display">\[
\begin{aligned}
Additive Model: Score &amp;= \beta_0 \\
      &amp;+ \beta_1 D_\text{Amnseic} + \beta_2 D_\text{Huntingtons}   \\
      &amp;+ \beta_3 T_\text{Grammar}  + \beta_4 T_\text{Classification} \\
      &amp;+ \epsilon
\end{aligned}
\]</span></p>
<p><span class="math display">\[
\begin{aligned}
Interaction Model: Score &amp;= \beta_0 \\
      &amp;+ \beta_1 D_\text{Amnseic} + \beta_2 D_\text{Huntingtons}   \\
      &amp;+ \beta_3 T_\text{Grammar}  + \beta_4 T_\text{Classification} \\
      &amp;+ \beta_5 (D_\text{Amnseic} * T_\text{Grammar}) + \beta_6 (D_\text{Huntingtons} * T_\text{Grammar})  \\
      &amp;+ \beta_7 (D_\text{Amnseic} * T_\text{Classification}) + \beta_8 (D_\text{Huntingtons} * T_\text{Classification})  \\
      &amp;+ \epsilon
\end{aligned}
\]</span></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>Switch back to dummy coding:</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.treatment"</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.treatment"</span></span></code></pre></div>
</div>
<p>Build additive model and re-run interaction model:</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl_add</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Score</span> <span class="op">~</span> <span class="va">Diagnosis</span> <span class="op">+</span> <span class="va">Task</span>, data <span class="op">=</span> <span class="va">cog</span><span class="op">)</span></span>
<span><span class="va">mdl_int</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Score</span> <span class="op">~</span> <span class="va">Diagnosis</span> <span class="op">*</span> <span class="va">Task</span>, data <span class="op">=</span> <span class="va">cog</span><span class="op">)</span></span></code></pre></div>
</div>
<p>The relevant function is <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> with the two models as inputs to conduct a model comparison:</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl_add</span>, <span class="va">mdl_int</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Score ~ Diagnosis + Task
Model 2: Score ~ Diagnosis * Task
  Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
1     40 10680                                  
2     36  5680  4      5000 7.9225 0.0001092 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="int">
<p>We performed an F-test to compare two nested models: an additive two-factor ANOVA against a two-factor model with interaction. The test results are <span class="math inline">\(F(4, 36) = 7.92, p &lt; .001\)</span>.</p>
<p>At the 5% significance level, the probability of obtaining an F-statistic as large as 7.92 or larger is &lt;.001.</p>
<p>Hence, the comparison of nested models provides evidence against the additive effects model, suggesting that we should use the interaction model as each factor has a different effect on the response depending the level of the other factor.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Using <code><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model()</a></code> (note that this function is from <code>sjPlot</code> package - make sure that you load this), generate a plot showing the predicted mean scores for each combination of levels of the diagnosis and task factors.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<p>To visualize the interaction between Diagnosis and Task, we will use <code><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model()</a></code>, and ask for a plot of predicted values by specifying <code>type = "pred"</code>. Because the interaction involves the two variables, we need to specify a list of the <code>terms</code> (or names) from the model that should be plotted.</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://strengejacke.github.io/sjPlot/">sjPlot</a></span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'parameters':
  method                      from       
  plot.check_clusterstructure performance</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Install package "strengejacke" from GitHub (`devtools::install_github("strengejacke/strengejacke")`) to load all sj-packages at once!</code></pre>
</div>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">mdl_int</span>, type <span class="op">=</span> <span class="st">"pred"</span>, terms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Diagnosis"</span>, <span class="st">"Task"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_04_emmeans_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="contrast-analysis" class="level1"><h1>Contrast analysis</h1>
<p>We will begin by looking at each factor separately.</p>
<p>In terms of the diagnostic groups, recall that we want to compare the amnesiacs to the Huntington individuals. This corresponds to a contrast with coefficients of 0, 1, and −1, for control, amnesic, and Huntingtons, respectively.</p>
<p>Similarly, in terms of the tasks, we want to compare the average of the two implicit memory tasks with the explicit memory task. This corresponds to a contrast with coefficients of 0.5, 0.5, and −1 for the three tasks.</p>
<p>When we are in presence of a significant interaction, the coefficients for a contrast between the means are found by multiplying each row coefficient with all column coefficients as shown below:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="images/contr_interaction.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<p>This can be done in R using:</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">diag_coef</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'control'</span> <span class="op">=</span> <span class="fl">0</span>, <span class="st">'amnesic'</span> <span class="op">=</span> <span class="fl">1</span>, <span class="st">'huntingtons'</span> <span class="op">=</span> <span class="op">-</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">task_coef</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'grammar'</span> <span class="op">=</span> <span class="fl">0.5</span>, <span class="st">'classification'</span> <span class="op">=</span> <span class="fl">0.5</span>, <span class="st">'recognition'</span> <span class="op">=</span> <span class="op">-</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">contr_coef</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/outer.html">outer</a></span><span class="op">(</span><span class="va">diag_coef</span>, <span class="va">task_coef</span><span class="op">)</span>   <span class="co"># or: diag_coef %o% task_coef</span></span>
<span><span class="va">contr_coef</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            grammar classification recognition
control         0.0            0.0           0
amnesic         0.5            0.5          -1
huntingtons    -0.5           -0.5           1</code></pre>
</div>
</div>
<p>The above coefficients correspond to testing the null hypothesis</p>
<p><span class="math display">\[
H_0 : \frac{\mu_{2,1} + \mu_{2,2}}{2} - \mu_{2,3} - \left( \frac{\mu_{3,1} + \mu_{3,2}}{2} - \mu_{3,3} \right) = 0
\]</span></p>
<p>or, equivalently,</p>
<p><span class="math display">\[
H_0 : \frac{\mu_{2,1} + \mu_{2,2}}{2} - \mu_{2,3} = \frac{\mu_{3,1} + \mu_{3,2}}{2} - \mu_{3,3}
\]</span></p>
<p>which says that, in the population, the difference between the mean implicit memory and the explicit memory score is the same for amnesic patients and Huntingtons individuals. Note that the scores for the grammar and classification tasks have been averaged to obtain a single measure of ‘implicit memory’ score.</p>
<p>Now that we have the coefficients, let’s call the <code>emmeans</code> function (this is helpful to look at the ordering of the groups):</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/rvlenth/emmeans">emmeans</a></span><span class="op">)</span></span>
<span><span class="va">emm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="op">~</span> <span class="va">Diagnosis</span><span class="op">*</span><span class="va">Task</span><span class="op">)</span></span>
<span><span class="va">emm</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Diagnosis   Task           emmean   SE df lower.CL upper.CL
 control     recognition        95 5.62 36     83.6    106.4
 amnesic     recognition        65 5.62 36     53.6     76.4
 huntingtons recognition        95 5.62 36     83.6    106.4
 control     grammar            80 5.62 36     68.6     91.4
 amnesic     grammar            60 5.62 36     48.6     71.4
 huntingtons grammar            40 5.62 36     28.6     51.4
 control     classification     80 5.62 36     68.6     91.4
 amnesic     classification     70 5.62 36     58.6     81.4
 huntingtons classification     45 5.62 36     33.6     56.4

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>Next, from <code>contr_coef</code>, insert the coefficients following the order specified by the rows of <code>emm</code> above. That is, the first one should be for <code>control</code> <code>recognition</code> and have a value of 0, the second for <code>amnesic</code> <code>recognition</code> with a value of -1, and so on…</p>
<p>We also give a name to this contrast, such as ‘Research Hyp’.</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">comp_res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">emm</span>, method <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">'Research Hyp'</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">0.5</span>, <span class="op">-</span><span class="fl">0.5</span>, <span class="fl">0</span>, <span class="fl">0.5</span>, <span class="op">-</span><span class="fl">0.5</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">comp_res</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast     estimate   SE df t.ratio p.value
 Research Hyp     52.5 9.73 36   5.396  &lt;.0001</code></pre>
</div>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">comp_res</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast     estimate   SE df lower.CL upper.CL
 Research Hyp     52.5 9.73 36     32.8     72.2

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>or:</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">comp_res</span>, infer <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast     estimate   SE df lower.CL upper.CL t.ratio p.value
 Research Hyp     52.5 9.73 36     32.8     72.2   5.396  &lt;.0001

Confidence level used: 0.95 </code></pre>
</div>
</div>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Interpret the results of the contrast analysis.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>The contrast analysis yielded a <span class="math inline">\(t\)</span>-value of 5.4 and a corresponding <span class="math inline">\(p\)</span>-value &lt; .001. Thus, there is evidence that the contrast is not zero in the population. In other words, Amnesics and Huntingtons patients differ in the difference between implicit and explicit recognition memory tasks.</p>
<p>The contrast analysis shows that the 95% confidence interval for our contrast stretches from 32.8 to 72.2. This interval does not contain zero. Thus, we can be 95% confident that the task difference is not the same for amnesiacs as for Huntingtons, which is why we can reject the null hypothesis that the difference in differences is zero.</p>
</div>
<p class="solution-end">
</p>
</section><section id="simple-effects" class="level1"><h1>Simple Effects</h1>
<p>By considering the simple effects, we can identify at which levels of the interacting condition we see different effects.</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Since we have a significant interaction, we should also look at the simple main effects. Simple effects are the effect of one factor (e.g., Task) at each level of another factor (e.g., Diagnosis - Control, Huntingtons, and Amnesic).</p>
<p>Examine the simple effects for Task at each level of Diagnosis; and then the simple effects for Diagnosis at each level of Task.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl_int_simple1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="va">emm</span>, simple <span class="op">=</span> <span class="st">"Task"</span><span class="op">)</span></span>
<span><span class="va">mdl_int_simple1</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Diagnosis = control:
 contrast                     estimate   SE df t.ratio p.value
 recognition - grammar              15 7.94 36   1.888  0.1567
 recognition - classification       15 7.94 36   1.888  0.1567
 grammar - classification            0 7.94 36   0.000  1.0000

Diagnosis = amnesic:
 contrast                     estimate   SE df t.ratio p.value
 recognition - grammar               5 7.94 36   0.629  0.8050
 recognition - classification       -5 7.94 36  -0.629  0.8050
 grammar - classification          -10 7.94 36  -1.259  0.4273

Diagnosis = huntingtons:
 contrast                     estimate   SE df t.ratio p.value
 recognition - grammar              55 7.94 36   6.923  &lt;.0001
 recognition - classification       50 7.94 36   6.294  &lt;.0001
 grammar - classification           -5 7.94 36  -0.629  0.8050

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl_int_simple2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="va">emm</span>, simple <span class="op">=</span> <span class="st">"Diagnosis"</span><span class="op">)</span></span>
<span><span class="va">mdl_int_simple2</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Task = recognition:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           30 7.94 36   3.776  0.0016
 control - huntingtons        0 7.94 36   0.000  1.0000
 amnesic - huntingtons      -30 7.94 36  -3.776  0.0016

Task = grammar:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           20 7.94 36   2.518  0.0424
 control - huntingtons       40 7.94 36   5.035  &lt;.0001
 amnesic - huntingtons       20 7.94 36   2.518  0.0424

Task = classification:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           10 7.94 36   1.259  0.4273
 control - huntingtons       35 7.94 36   4.406  0.0003
 amnesic - huntingtons       25 7.94 36   3.147  0.0091

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>From <code>mdl_int_simple1</code> we can see the differences between between tasks for each diagnosis group, and from <code>mdl_int_simple2</code> the differences between diagnoses for each task group.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>There are various ways we can create an interaction plot, for instance, try this code:</p>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmip.html">emmip</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="va">Diagnosis</span> <span class="op">~</span> <span class="va">Task</span>, CIs <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
</div>
<p>Considering the simple effects that we just saw in Question 5, identify the significant effects and match them to the parts of an interaction plot.</p>
<div class="optional-begin">
<span id="opt-start-9" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-9', 'opt-start-9')"> <span class="olab">Optional: You can change what is plotted on the x-axis</span></span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p>We can switch what is on the x-axis pretty easily:</p>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span> <span class="co">#loading this package so that I can display plots in a grid</span></span>
<span><span class="va">plt_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmip.html">emmip</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="va">Diagnosis</span> <span class="op">~</span> <span class="va">Task</span>, CIs <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">plt_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmip.html">emmip</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="va">Task</span> <span class="op">~</span> <span class="va">Diagnosis</span>, CIs <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">plt_1</span> <span class="op">/</span> <span class="va">plt_2</span></span></code></pre></div>
</div>
</div>
<p class="optional-end">
</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div class="solution-body" id="sol-body-10" style="display: none;">


<p>For the simple effects of Task, the significant differences (those for which <span class="math inline">\(p&lt;.05\)</span>) are only seen in the Huntingtons group, between recognition &amp; grammar and recognition &amp; classification tasks.<br>
In the plot below, we can see this is the left-most blue point compared to the middle blue point, and then compared to the right-most blue point.</p>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmip.html">emmip</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="va">Diagnosis</span> <span class="op">~</span> <span class="va">Task</span>, CIs <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_04_emmeans_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p>For the simple effects of Diagnosis, we saw significant differences</p>
<ul>
<li>in the recognition task, between control &amp; amnesic<br>
(in the plot below: left-most red point to middle red-point)<br>
</li>
<li>in the recognition task, between amnesic &amp; huntingtons<br>
(in the plot below: middle red-point to right-most red point)<br>
</li>
<li>in the grammar task, between control &amp; huntingtons<br>
(in the plot below: left-most green point to right-most green point)</li>
<li>in the classification task, between control &amp; huntingtons<br>
(in the plot below: left-most blue point to right-most blue point)</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmip.html">emmip</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="va">Task</span> <span class="op">~</span> <span class="va">Diagnosis</span>, CIs <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_04_emmeans_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="pairwise-comparisons" class="level1"><h1>Pairwise Comparisons</h1>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Conduct exploratory pairwise comparisons to compare all levels of Diagnosis with all levels of Task.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">pairs_res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="va">emm</span><span class="op">)</span></span>
<span><span class="va">pairs_res</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                             estimate   SE df t.ratio
 control recognition - amnesic recognition                  30 7.94 36   3.776
 control recognition - huntingtons recognition               0 7.94 36   0.000
 control recognition - control grammar                      15 7.94 36   1.888
 control recognition - amnesic grammar                      35 7.94 36   4.406
 control recognition - huntingtons grammar                  55 7.94 36   6.923
 control recognition - control classification               15 7.94 36   1.888
 control recognition - amnesic classification               25 7.94 36   3.147
 control recognition - huntingtons classification           50 7.94 36   6.294
 amnesic recognition - huntingtons recognition             -30 7.94 36  -3.776
 amnesic recognition - control grammar                     -15 7.94 36  -1.888
 amnesic recognition - amnesic grammar                       5 7.94 36   0.629
 amnesic recognition - huntingtons grammar                  25 7.94 36   3.147
 amnesic recognition - control classification              -15 7.94 36  -1.888
 amnesic recognition - amnesic classification               -5 7.94 36  -0.629
 amnesic recognition - huntingtons classification           20 7.94 36   2.518
 huntingtons recognition - control grammar                  15 7.94 36   1.888
 huntingtons recognition - amnesic grammar                  35 7.94 36   4.406
 huntingtons recognition - huntingtons grammar              55 7.94 36   6.923
 huntingtons recognition - control classification           15 7.94 36   1.888
 huntingtons recognition - amnesic classification           25 7.94 36   3.147
 huntingtons recognition - huntingtons classification       50 7.94 36   6.294
 control grammar - amnesic grammar                          20 7.94 36   2.518
 control grammar - huntingtons grammar                      40 7.94 36   5.035
 control grammar - control classification                    0 7.94 36   0.000
 control grammar - amnesic classification                   10 7.94 36   1.259
 control grammar - huntingtons classification               35 7.94 36   4.406
 amnesic grammar - huntingtons grammar                      20 7.94 36   2.518
 amnesic grammar - control classification                  -20 7.94 36  -2.518
 amnesic grammar - amnesic classification                  -10 7.94 36  -1.259
 amnesic grammar - huntingtons classification               15 7.94 36   1.888
 huntingtons grammar - control classification              -40 7.94 36  -5.035
 huntingtons grammar - amnesic classification              -30 7.94 36  -3.776
 huntingtons grammar - huntingtons classification           -5 7.94 36  -0.629
 control classification - amnesic classification            10 7.94 36   1.259
 control classification - huntingtons classification        35 7.94 36   4.406
 amnesic classification - huntingtons classification        25 7.94 36   3.147
 p.value
  0.0149
  1.0000
  0.6257
  0.0026
  &lt;.0001
  0.6257
  0.0711
  &lt;.0001
  0.0149
  0.6257
  0.9993
  0.0711
  0.6257
  0.9993
  0.2575
  0.6257
  0.0026
  &lt;.0001
  0.6257
  0.0711
  &lt;.0001
  0.2575
  0.0004
  1.0000
  0.9367
  0.0026
  0.2575
  0.2575
  0.9367
  0.6257
  0.0004
  0.0149
  0.9993
  0.9367
  0.0026
  0.0711

P value adjustment: tukey method for comparing a family of 9 estimates </code></pre>
</div>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#can also plot if you'd like:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">pairs_res</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_04_emmeans_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the above, we can see comparisons for all different possible pairs of diagnosis-task combinations. As well as recapping assumption checks, next week we will also explore how we can adjust our pairwise comparisons (<em>think</em> about how many comparisons were conducted above - without adjusting our <span class="math inline">\(\alpha\)</span> (or <span class="math inline">\(p\)</span>-value), why might any inferences drawn be problematic?)</p>
</div>
<p class="solution-end">
</p>
</section><section id="multiple-comparisons" class="level1"><h1>Multiple Comparisons</h1>
<p>In last week’s exercises we began to look at how we compare different groups, by using contrast analysis to conduct tests of specific comparisons between groups. We also saw how we might conduct <em>pairwise comparisons</em>, where we test all possible pairs of group means within a given set.</p>
<p>For instance, we can compare the means of the different diagnosis groups for each task:</p>
<div class="cell">
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">emm_task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="op">~</span> <span class="va">Diagnosis</span> <span class="op">|</span> <span class="va">Task</span><span class="op">)</span></span>
<span><span class="va">contr_task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">emm_task</span>, method <span class="op">=</span> <span class="st">'pairwise'</span><span class="op">)</span></span>
<span><span class="va">contr_task</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Task = recognition:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           30 7.94 36   3.776  0.0016
 control - huntingtons        0 7.94 36   0.000  1.0000
 amnesic - huntingtons      -30 7.94 36  -3.776  0.0016

Task = grammar:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           20 7.94 36   2.518  0.0424
 control - huntingtons       40 7.94 36   5.035  &lt;.0001
 amnesic - huntingtons       20 7.94 36   2.518  0.0424

Task = classification:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           10 7.94 36   1.259  0.4273
 control - huntingtons       35 7.94 36   4.406  0.0003
 amnesic - huntingtons       25 7.94 36   3.147  0.0091

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>or we can test all different combinations of task and diagnosis group (if that was something we were theoretically interested in, which is unlikely!) which would equate to conducting 36 comparisons!</p>
<div class="cell">
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">emm_task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="op">~</span> <span class="va">Diagnosis</span> <span class="op">*</span> <span class="va">Task</span><span class="op">)</span></span>
<span><span class="va">contr_task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">emm_task</span>, method <span class="op">=</span> <span class="st">'pairwise'</span><span class="op">)</span></span>
<span><span class="va">contr_task</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                             estimate   SE df t.ratio
 control recognition - amnesic recognition                  30 7.94 36   3.776
 control recognition - huntingtons recognition               0 7.94 36   0.000
 control recognition - control grammar                      15 7.94 36   1.888
 control recognition - amnesic grammar                      35 7.94 36   4.406
 control recognition - huntingtons grammar                  55 7.94 36   6.923
 control recognition - control classification               15 7.94 36   1.888
 control recognition - amnesic classification               25 7.94 36   3.147
 control recognition - huntingtons classification           50 7.94 36   6.294
 amnesic recognition - huntingtons recognition             -30 7.94 36  -3.776
 amnesic recognition - control grammar                     -15 7.94 36  -1.888
 amnesic recognition - amnesic grammar                       5 7.94 36   0.629
 amnesic recognition - huntingtons grammar                  25 7.94 36   3.147
 amnesic recognition - control classification              -15 7.94 36  -1.888
 amnesic recognition - amnesic classification               -5 7.94 36  -0.629
 amnesic recognition - huntingtons classification           20 7.94 36   2.518
 huntingtons recognition - control grammar                  15 7.94 36   1.888
 huntingtons recognition - amnesic grammar                  35 7.94 36   4.406
 huntingtons recognition - huntingtons grammar              55 7.94 36   6.923
 huntingtons recognition - control classification           15 7.94 36   1.888
 huntingtons recognition - amnesic classification           25 7.94 36   3.147
 huntingtons recognition - huntingtons classification       50 7.94 36   6.294
 control grammar - amnesic grammar                          20 7.94 36   2.518
 control grammar - huntingtons grammar                      40 7.94 36   5.035
 control grammar - control classification                    0 7.94 36   0.000
 control grammar - amnesic classification                   10 7.94 36   1.259
 control grammar - huntingtons classification               35 7.94 36   4.406
 amnesic grammar - huntingtons grammar                      20 7.94 36   2.518
 amnesic grammar - control classification                  -20 7.94 36  -2.518
 amnesic grammar - amnesic classification                  -10 7.94 36  -1.259
 amnesic grammar - huntingtons classification               15 7.94 36   1.888
 huntingtons grammar - control classification              -40 7.94 36  -5.035
 huntingtons grammar - amnesic classification              -30 7.94 36  -3.776
 huntingtons grammar - huntingtons classification           -5 7.94 36  -0.629
 control classification - amnesic classification            10 7.94 36   1.259
 control classification - huntingtons classification        35 7.94 36   4.406
 amnesic classification - huntingtons classification        25 7.94 36   3.147
 p.value
  0.0149
  1.0000
  0.6257
  0.0026
  &lt;.0001
  0.6257
  0.0711
  &lt;.0001
  0.0149
  0.6257
  0.9993
  0.0711
  0.6257
  0.9993
  0.2575
  0.6257
  0.0026
  &lt;.0001
  0.6257
  0.0711
  &lt;.0001
  0.2575
  0.0004
  1.0000
  0.9367
  0.0026
  0.2575
  0.2575
  0.9367
  0.6257
  0.0004
  0.0149
  0.9993
  0.9367
  0.0026
  0.0711

P value adjustment: tukey method for comparing a family of 9 estimates </code></pre>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-12" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-12', 'opt-start-12')"> <span class="olab">36? how do we know there are 36?</span></span>
</div>
<div id="opt-body-12" class="optional-body" style="display: none;">
<p>There are 3 diagnosis groups, and 3 tasks, meaning there are 9 different group means. All possible pairwise comparisons would is all different possible combinations of 2 from a set of 9. We can work this out using the rule:</p>
<p><span class="math display">\[
_nC_r = \frac{n!}{r!(n-r)!} \\
\begin{align} \\
&amp; \text{Where:} \\
&amp; n = \text{total number in the set} \\
&amp; r = \text{number chosen} \\
&amp; _nC_r = \text{number of combinations of r from n} \\
\end{align}
\]</span></p>
<p>In <strong>R</strong>:</p>
<div class="cell">
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Special.html">factorial</a></span><span class="op">(</span><span class="fl">9</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Special.html">factorial</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span><span class="op">*</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Special.html">factorial</a></span><span class="op">(</span><span class="fl">9</span><span class="op">-</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 36</code></pre>
</div>
</div>
<p>Or, easier still:</p>
<div class="cell">
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/combn.html">combn</a></span><span class="op">(</span><span class="fl">9</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2 36</code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
<section id="why-does-the-number-of-tests-matter" class="level2"><h2 class="anchored" data-anchor-id="why-does-the-number-of-tests-matter">Why does the number of tests matter?</h2>
<div class="optional-begin">
<span id="opt-start-13" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-13', 'opt-start-13')"> <span class="olab">refresher on making errors in hypothesis tests</span></span>
</div>
<div id="opt-body-13" class="optional-body" style="display: none;">
<p>Think back to <a href="https://uoe-psychology.github.io/uoe_psystats/dapr1/book/chap-typeerror.html">“Type 1 errors” from DAPR1</a> - when we conduct an hypothesis test, and we set <span class="math inline">\(\alpha=0.05\)</span>, we will reject the null hypothesis <span class="math inline">\(H_0\)</span> when we find a <span class="math inline">\(p &lt; .05\)</span>. Now remember what a <span class="math inline">\(p\)</span>-value represents - it is the chance of observing a statistic at least as extreme as the one we do have, assuming the null hypothesis to be true. This means that <em>if</em> <span class="math inline">\(H_0\)</span> <strong>is</strong> true, then we will still observe a <span class="math inline">\(p &lt; .05\)</span> 5% of the time. So our chance of making this error = the threshold (<span class="math inline">\(\alpha\)</span>) at which below a p-value results in us rejecting <span class="math inline">\(H_0\)</span>.</p>
</div>
<p class="optional-end">
</p>
<p>But this error-rate applies to each statistical hypothesis we test. So if we conduct an experiment in which we plan on conducting lots of tests of different comparisons, the chance of an error being made increases substantially. Across the family of tests performed that chance will be much higher than 5%.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>Each test conducted at <span class="math inline">\(\alpha = 0.05\)</span> has a 0.05 (or 5%) probability of Type I error (wrongly rejecting the null hypothesis). If we do 9 tests, that experimentwise error rate is <span class="math inline">\(\alpha_{ew} \leq 9 \times 0.05\)</span>, where 9 is the number of comparisons made as part of the experiment.</p>
<p>Thus, if nine <strong>independent</strong> comparisons were made at the <span class="math inline">\(\alpha = 0.05\)</span> level, the experimentwise Type I error rate <span class="math inline">\(\alpha_{ew}\)</span> would be at most <span class="math inline">\(9 \times 0.05 = 0.45\)</span>. That is, we could wrongly reject the null hypothesis on average 45 times out of 100. To make this more confusing, many of the tests in a family are not <strong>independent</strong> (see the lecture slides for the calculation of error rate for dependent tests).</p>
<p>Here, we go through some of the different options available to us to control, or ‘correct’ for this problem.</p>
</section></section><section id="corrections" class="level1"><h1>Corrections</h1>
<section id="bonferroni" class="level2"><h2 class="anchored" data-anchor-id="bonferroni">Bonferroni</h2>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Load the data from last week, and re-acquaint yourself with it.</p>
<p>Provide a plot of the Diagnosis*Task group mean scores.</p>
<p>The data is at https://uoepsy.github.io/data/cognitive_experiment.csv.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-14" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-14', 'sol-start-14')"> Solution </span>
</div>
<div id="sol-body-14" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb64"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">cog</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">'https://uoepsy.github.io/data/cognitive_experiment.csv'</span><span class="op">)</span></span>
<span><span class="co"># head(df)</span></span>
<span></span>
<span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span>, </span>
<span>                       labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"amnesic"</span>, <span class="st">"huntingtons"</span>, <span class="st">"control"</span><span class="op">)</span>,</span>
<span>                       ordered <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span>, </span>
<span>                  labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"grammar"</span>, <span class="st">"classification"</span>, <span class="st">"recognition"</span><span class="op">)</span>, </span>
<span>                  ordered <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span> <span class="op">&lt;-</span> <span class="fu">fct_relevel</span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Diagnosis</span>, <span class="st">"control"</span><span class="op">)</span></span>
<span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span> <span class="op">&lt;-</span> <span class="fu">fct_relevel</span><span class="op">(</span><span class="va">cog</span><span class="op">$</span><span class="va">Task</span>, <span class="st">"recognition"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">cog</span> <span class="op">&lt;-</span> <span class="va">cog</span> <span class="op">%&gt;%</span></span>
<span>    <span class="fu">rename</span><span class="op">(</span>Score <span class="op">=</span> <span class="va">Y</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Fit the interaction model, using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>. Pass your model to the <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> function, to remind yourself that there is a significant interaction present.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-15" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-15', 'sol-start-15')"> Solution </span>
</div>
<div id="sol-body-15" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mdl_int</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Score</span> <span class="op">~</span> <span class="va">Task</span><span class="op">*</span><span class="va">Diagnosis</span>, data <span class="op">=</span> <span class="va">cog</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl_int</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Score
               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Task            2   5250 2625.00 16.6373  7.64e-06 ***
Diagnosis       2   5250 2625.00 16.6373  7.64e-06 ***
Task:Diagnosis  4   5000 1250.00  7.9225 0.0001092 ***
Residuals      36   5680  157.78                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>There are various ways to make nice tables in RMarkdown.<br>
Some of the most well known are:</p>
<ul>
<li>The <strong>knitr</strong> package has <code><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable()</a></code><br>
</li>
<li>The <strong>pander</strong> package has <code><a href="https://rdrr.io/pkg/pander/man/pander.html">pander()</a></code>
</li>
</ul>
<p>Pick one (or find go googling and find a package you like the look of), install the package (if you don’t already have it), then try to create a nice pretty ANOVA table rather than the one given by <code>anova(model)</code>.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-16" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-16', 'sol-start-16')"> Solution </span>
</div>
<div id="sol-body-16" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://yihui.org/knitr/">knitr</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl_int</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">

<table>
<thead><tr>
<th style="text-align:left;">   </th>
   <th style="text-align:right;"> Df </th>
   <th style="text-align:right;"> Sum Sq </th>
   <th style="text-align:right;"> Mean Sq </th>
   <th style="text-align:right;"> F value </th>
   <th style="text-align:right;"> Pr(&gt;F) </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:left;"> Task </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 5250 </td>
   <td style="text-align:right;"> 2625.0000 </td>
   <td style="text-align:right;"> 16.637324 </td>
   <td style="text-align:right;"> 0.0000076 </td>
  </tr>
<tr>
<td style="text-align:left;"> Diagnosis </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 5250 </td>
   <td style="text-align:right;"> 2625.0000 </td>
   <td style="text-align:right;"> 16.637324 </td>
   <td style="text-align:right;"> 0.0000076 </td>
  </tr>
<tr>
<td style="text-align:left;"> Task:Diagnosis </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 5000 </td>
   <td style="text-align:right;"> 1250.0000 </td>
   <td style="text-align:right;"> 7.922535 </td>
   <td style="text-align:right;"> 0.0001092 </td>
  </tr>
<tr>
<td style="text-align:left;"> Residuals </td>
   <td style="text-align:right;"> 36 </td>
   <td style="text-align:right;"> 5680 </td>
   <td style="text-align:right;"> 157.7778 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:right;"> NA </td>
  </tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb68"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://rapporter.github.io/pander/">pander</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/pander/man/pander.html">pander</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mdl_int</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Analysis of Variance Table</caption>
<colgroup>
<col style="width: 29%">
<col style="width: 6%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 16%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">&nbsp;</th>
<th style="text-align: center;">Df</th>
<th style="text-align: center;">Sum Sq</th>
<th style="text-align: center;">Mean Sq</th>
<th style="text-align: center;">F value</th>
<th style="text-align: center;">Pr(&gt;F)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Task</strong></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">5250</td>
<td style="text-align: center;">2625</td>
<td style="text-align: center;">16.64</td>
<td style="text-align: center;">7.64e-06</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Diagnosis</strong></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">5250</td>
<td style="text-align: center;">2625</td>
<td style="text-align: center;">16.64</td>
<td style="text-align: center;">7.64e-06</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Task:Diagnosis</strong></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5000</td>
<td style="text-align: center;">1250</td>
<td style="text-align: center;">7.923</td>
<td style="text-align: center;">0.0001092</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Residuals</strong></td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">5680</td>
<td style="text-align: center;">157.8</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>As in the previous week’s exercises, let us suppose that we are specifically interested in comparisons of the mean score <em>across the different diagnosis groups for a given task</em>.</p>
<p>Edit the code below to obtain the pairwise comparisons of diagnosis groups for each task. Use the Bonferroni method to adjust for multiple comparisons, and then obtain confidence intervals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>emm_task <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mdl_int, ? )</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>contr_task <span class="ot">&lt;-</span> <span class="fu">contrast</span>(emm_task, <span class="at">method =</span> ?, <span class="at">adjust =</span> ? )</span></code></pre></div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-17" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-17', 'sol-start-17')"> Solution </span>
</div>
<div id="sol-body-17" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb70"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">emm_task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="op">~</span> <span class="va">Diagnosis</span> <span class="op">|</span> <span class="va">Task</span><span class="op">)</span></span>
<span><span class="va">contr_task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">emm_task</span>, method <span class="op">=</span> <span class="st">"pairwise"</span>, adjust<span class="op">=</span><span class="st">"bonferroni"</span><span class="op">)</span></span>
<span><span class="va">contr_task</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Task = recognition:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           30 7.94 36   3.776  0.0017
 control - huntingtons        0 7.94 36   0.000  1.0000
 amnesic - huntingtons      -30 7.94 36  -3.776  0.0017

Task = grammar:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           20 7.94 36   2.518  0.0492
 control - huntingtons       40 7.94 36   5.035  &lt;.0001
 amnesic - huntingtons       20 7.94 36   2.518  0.0492

Task = classification:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           10 7.94 36   1.259  0.6486
 control - huntingtons       35 7.94 36   4.406  0.0003
 amnesic - huntingtons       25 7.94 36   3.147  0.0099

P value adjustment: bonferroni method for 3 tests </code></pre>
</div>
<div class="sourceCode" id="cb72"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">contr_task</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Task = recognition:
 contrast              estimate   SE df lower.CL upper.CL
 control - amnesic           30 7.94 36  10.0517     49.9
 control - huntingtons        0 7.94 36 -19.9483     19.9
 amnesic - huntingtons      -30 7.94 36 -49.9483    -10.1

Task = grammar:
 contrast              estimate   SE df lower.CL upper.CL
 control - amnesic           20 7.94 36   0.0517     39.9
 control - huntingtons       40 7.94 36  20.0517     59.9
 amnesic - huntingtons       20 7.94 36   0.0517     39.9

Task = classification:
 contrast              estimate   SE df lower.CL upper.CL
 control - amnesic           10 7.94 36  -9.9483     29.9
 control - huntingtons       35 7.94 36  15.0517     54.9
 amnesic - huntingtons       25 7.94 36   5.0517     44.9

Confidence level used: 0.95 
Conf-level adjustment: bonferroni method for 3 estimates </code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="frame">
<p><strong>adjusting <span class="math inline">\(\alpha\)</span>, adjusting p</strong></p>
<p>In the lecture we talked about adjusting the <span class="math inline">\(\alpha\)</span> level (i.e., instead of determining significance at <span class="math inline">\(p &lt; .05\)</span>, we might adjust and determine a result to be statistically significant if <span class="math inline">\(p &lt; .005\)</span>, depending on how many tests are in our family of tests).</p>
<p>Note what the functions in R do is adjust the <span class="math inline">\(p\)</span>-value, rather than the <span class="math inline">\(\alpha\)</span>. The Bonferroni method simply multiplies the ‘raw’ p-value by the number of the tests.</p>
</div>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>In question 4 above, there are 9 tests being performed, but there are 3 in each ‘family’ (each <code>Task</code>).</p>
<p>Try changing your answer to question 4 to use <code>adjust = "none"</code>, rather than <code>"bonferroni"</code>, and confirm that the p-values are 1/3 of the size.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-18" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-18', 'sol-start-18')"> Solution </span>
</div>
<div id="sol-body-18" class="solution-body" style="display: none;">
<p>The first Bonferroni adjusted p-value is 0.0492.</p>
<div class="cell">
<div class="sourceCode" id="cb74"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fl">0.0492</span><span class="op">/</span><span class="fl">3</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0164</code></pre>
</div>
</div>
<p>Let’s check that this is the raw p-value:</p>
<div class="cell">
<div class="sourceCode" id="cb76"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">emm_task</span>, method <span class="op">=</span> <span class="st">"pairwise"</span>, adjust<span class="op">=</span><span class="st">"none"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Task = recognition:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           30 7.94 36   3.776  0.0006
 control - huntingtons        0 7.94 36   0.000  1.0000
 amnesic - huntingtons      -30 7.94 36  -3.776  0.0006

Task = grammar:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           20 7.94 36   2.518  0.0164
 control - huntingtons       40 7.94 36   5.035  &lt;.0001
 amnesic - huntingtons       20 7.94 36   2.518  0.0164

Task = classification:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           10 7.94 36   1.259  0.2162
 control - huntingtons       35 7.94 36   4.406  0.0001
 amnesic - huntingtons       25 7.94 36   3.147  0.0033</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="šídák" class="level2"><h2 class="anchored" data-anchor-id="šídák">Šídák</h2>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>The Sidak approach is slightly less conservative than the Bonferroni adjustment. Doing this with the <strong>emmeans</strong> package is easy, can you figure out how?</p>
<p><strong>Hint:</strong> you just have to change the <code>adjust</code> argument in <code><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast()</a></code> function.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-19" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-19', 'sol-start-19')"> Solution </span>
</div>
<div id="sol-body-19" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb78"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">emm_task</span>, method <span class="op">=</span> <span class="st">"pairwise"</span>, adjust <span class="op">=</span> <span class="st">"sidak"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Task = recognition:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           30 7.94 36   3.776  0.0017
 control - huntingtons        0 7.94 36   0.000  1.0000
 amnesic - huntingtons      -30 7.94 36  -3.776  0.0017

Task = grammar:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           20 7.94 36   2.518  0.0484
 control - huntingtons       40 7.94 36   5.035  &lt;.0001
 amnesic - huntingtons       20 7.94 36   2.518  0.0484

Task = classification:
 contrast              estimate   SE df t.ratio p.value
 control - amnesic           10 7.94 36   1.259  0.5185
 control - huntingtons       35 7.94 36   4.406  0.0003
 amnesic - huntingtons       25 7.94 36   3.147  0.0099

P value adjustment: sidak method for 3 tests </code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="tukey" class="level2"><h2 class="anchored" data-anchor-id="tukey">Tukey</h2>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Like with Šídák, in R we can easily change to Tukey. Conduct pairwise comparisons of the scores of different Diagnosis groups on different Task types (i.e., the interaction), and use the Tukey adjustment.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-20" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-20', 'sol-start-20')"> Solution </span>
</div>
<div id="sol-body-20" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb80"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">emm_task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="op">~</span> <span class="va">Diagnosis</span><span class="op">*</span><span class="va">Task</span><span class="op">)</span></span>
<span><span class="va">contr_task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">emm_task</span>, method <span class="op">=</span> <span class="st">"pairwise"</span>, adjust<span class="op">=</span><span class="st">"tukey"</span><span class="op">)</span></span>
<span><span class="va">contr_task</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                             estimate   SE df t.ratio
 control recognition - amnesic recognition                  30 7.94 36   3.776
 control recognition - huntingtons recognition               0 7.94 36   0.000
 control recognition - control grammar                      15 7.94 36   1.888
 control recognition - amnesic grammar                      35 7.94 36   4.406
 control recognition - huntingtons grammar                  55 7.94 36   6.923
 control recognition - control classification               15 7.94 36   1.888
 control recognition - amnesic classification               25 7.94 36   3.147
 control recognition - huntingtons classification           50 7.94 36   6.294
 amnesic recognition - huntingtons recognition             -30 7.94 36  -3.776
 amnesic recognition - control grammar                     -15 7.94 36  -1.888
 amnesic recognition - amnesic grammar                       5 7.94 36   0.629
 amnesic recognition - huntingtons grammar                  25 7.94 36   3.147
 amnesic recognition - control classification              -15 7.94 36  -1.888
 amnesic recognition - amnesic classification               -5 7.94 36  -0.629
 amnesic recognition - huntingtons classification           20 7.94 36   2.518
 huntingtons recognition - control grammar                  15 7.94 36   1.888
 huntingtons recognition - amnesic grammar                  35 7.94 36   4.406
 huntingtons recognition - huntingtons grammar              55 7.94 36   6.923
 huntingtons recognition - control classification           15 7.94 36   1.888
 huntingtons recognition - amnesic classification           25 7.94 36   3.147
 huntingtons recognition - huntingtons classification       50 7.94 36   6.294
 control grammar - amnesic grammar                          20 7.94 36   2.518
 control grammar - huntingtons grammar                      40 7.94 36   5.035
 control grammar - control classification                    0 7.94 36   0.000
 control grammar - amnesic classification                   10 7.94 36   1.259
 control grammar - huntingtons classification               35 7.94 36   4.406
 amnesic grammar - huntingtons grammar                      20 7.94 36   2.518
 amnesic grammar - control classification                  -20 7.94 36  -2.518
 amnesic grammar - amnesic classification                  -10 7.94 36  -1.259
 amnesic grammar - huntingtons classification               15 7.94 36   1.888
 huntingtons grammar - control classification              -40 7.94 36  -5.035
 huntingtons grammar - amnesic classification              -30 7.94 36  -3.776
 huntingtons grammar - huntingtons classification           -5 7.94 36  -0.629
 control classification - amnesic classification            10 7.94 36   1.259
 control classification - huntingtons classification        35 7.94 36   4.406
 amnesic classification - huntingtons classification        25 7.94 36   3.147
 p.value
  0.0149
  1.0000
  0.6257
  0.0026
  &lt;.0001
  0.6257
  0.0711
  &lt;.0001
  0.0149
  0.6257
  0.9993
  0.0711
  0.6257
  0.9993
  0.2575
  0.6257
  0.0026
  &lt;.0001
  0.6257
  0.0711
  &lt;.0001
  0.2575
  0.0004
  1.0000
  0.9367
  0.0026
  0.2575
  0.2575
  0.9367
  0.6257
  0.0004
  0.0149
  0.9993
  0.9367
  0.0026
  0.0711

P value adjustment: tukey method for comparing a family of 9 estimates </code></pre>
</div>
</div>
<p>We can also use the following, which doesn’t require the <strong>emmeans</strong> package. You might see this when you look online for resources. The <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> function is fitting an ANOVA model, and then <code><a href="https://rdrr.io/r/stats/TukeyHSD.html">TukeyHSD()</a></code> compares between Diagnosis group; between Task type; and between Diagnosis*Task.</p>
<p>Run the code below yourself to see the output.</p>
<div class="cell">
<div class="sourceCode" id="cb82"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/TukeyHSD.html">TukeyHSD</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">Score</span> <span class="op">~</span> <span class="va">Diagnosis</span> <span class="op">*</span> <span class="va">Task</span>, data <span class="op">=</span> <span class="va">cog</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="scheffe" class="level2"><h2 class="anchored" data-anchor-id="scheffe">Scheffe</h2>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Run the same pairwise comparison as above, but this time with the Scheffe adjustment.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-21" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-21', 'sol-start-21')"> Solution </span>
</div>
<div id="sol-body-21" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb83"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">emm_task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">mdl_int</span>, <span class="op">~</span> <span class="va">Diagnosis</span> <span class="op">*</span> <span class="va">Task</span><span class="op">)</span></span>
<span><span class="va">contr_task</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">emm_task</span>, method <span class="op">=</span> <span class="st">"pairwise"</span>, adjust<span class="op">=</span><span class="st">"scheffe"</span><span class="op">)</span></span>
<span><span class="va">contr_task</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                             estimate   SE df t.ratio
 control recognition - amnesic recognition                  30 7.94 36   3.776
 control recognition - huntingtons recognition               0 7.94 36   0.000
 control recognition - control grammar                      15 7.94 36   1.888
 control recognition - amnesic grammar                      35 7.94 36   4.406
 control recognition - huntingtons grammar                  55 7.94 36   6.923
 control recognition - control classification               15 7.94 36   1.888
 control recognition - amnesic classification               25 7.94 36   3.147
 control recognition - huntingtons classification           50 7.94 36   6.294
 amnesic recognition - huntingtons recognition             -30 7.94 36  -3.776
 amnesic recognition - control grammar                     -15 7.94 36  -1.888
 amnesic recognition - amnesic grammar                       5 7.94 36   0.629
 amnesic recognition - huntingtons grammar                  25 7.94 36   3.147
 amnesic recognition - control classification              -15 7.94 36  -1.888
 amnesic recognition - amnesic classification               -5 7.94 36  -0.629
 amnesic recognition - huntingtons classification           20 7.94 36   2.518
 huntingtons recognition - control grammar                  15 7.94 36   1.888
 huntingtons recognition - amnesic grammar                  35 7.94 36   4.406
 huntingtons recognition - huntingtons grammar              55 7.94 36   6.923
 huntingtons recognition - control classification           15 7.94 36   1.888
 huntingtons recognition - amnesic classification           25 7.94 36   3.147
 huntingtons recognition - huntingtons classification       50 7.94 36   6.294
 control grammar - amnesic grammar                          20 7.94 36   2.518
 control grammar - huntingtons grammar                      40 7.94 36   5.035
 control grammar - control classification                    0 7.94 36   0.000
 control grammar - amnesic classification                   10 7.94 36   1.259
 control grammar - huntingtons classification               35 7.94 36   4.406
 amnesic grammar - huntingtons grammar                      20 7.94 36   2.518
 amnesic grammar - control classification                  -20 7.94 36  -2.518
 amnesic grammar - amnesic classification                  -10 7.94 36  -1.259
 amnesic grammar - huntingtons classification               15 7.94 36   1.888
 huntingtons grammar - control classification              -40 7.94 36  -5.035
 huntingtons grammar - amnesic classification              -30 7.94 36  -3.776
 huntingtons grammar - huntingtons classification           -5 7.94 36  -0.629
 control classification - amnesic classification            10 7.94 36   1.259
 control classification - huntingtons classification        35 7.94 36   4.406
 amnesic classification - huntingtons classification        25 7.94 36   3.147
 p.value
  0.1131
  1.0000
  0.8852
  0.0329
  0.0001
  0.8852
  0.3060
  0.0003
  0.1131
  0.8852
  0.9999
  0.3060
  0.8852
  0.9999
  0.6128
  0.8852
  0.0329
  0.0001
  0.8852
  0.3060
  0.0003
  0.6128
  0.0080
  1.0000
  0.9894
  0.0329
  0.6128
  0.6128
  0.9894
  0.8852
  0.0080
  0.1131
  0.9999
  0.9894
  0.0329
  0.3060

P value adjustment: scheffe method with rank 8 </code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>


</section></section><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
      <div class="nav-footer-center">© Copyright 2019-2022 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
  </div>
</footer></section></section><div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1" role="doc-endnote"><p>what defines a ‘family’ of tests is debateable.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main>
</div>


</body></html>