<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR2 - Write Up Example &amp; Block 3 Recap</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR2</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intro-to-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Intro to Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intro-to-linear-models">
<li>
    <a class="dropdown-item" href="./1_01_function.html">
 <span class="dropdown-text">1/1: Functions and Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_slr.html">
 <span class="dropdown-text">1/2: Intro to Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_mlr.html">
 <span class="dropdown-text">1/3: Multiple Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_model_fit.html">
 <span class="dropdown-text">1/4: Model Fit and Standardization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_05_cat_recap.html">
 <span class="dropdown-text">1/5: Cat Predictors &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">More Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more-linear-models">
<li>
    <a class="dropdown-item" href="./1_07_int1_nc.html">
 <span class="dropdown-text">1/7: Interactions I: Num x Cat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_08_int2_nn.html">
 <span class="dropdown-text">1/8: Interactions II: Num x Num</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_09_int3_cc.html">
 <span class="dropdown-text">1/9: Interactions III: Cat x Cat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_10_assump_diag.html">
 <span class="dropdown-text">1/10: Assumptions &amp; Diagnostics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_11_writeup_recap.html">
 <span class="dropdown-text">1/11: Write Up &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysing-experimental-studies" role="button" data-bs-toggle="dropdown" aria-expanded="false">Analysing Experimental Studies</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysing-experimental-studies">
<li>
    <a class="dropdown-item" href="./2_01_model_comps.html">
 <span class="dropdown-text">2/1: Model Comparison</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_02_effects.html">
 <span class="dropdown-text">2/2: Effects Coding</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_03_contrasts.html">
 <span class="dropdown-text">2/3: Contrasts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_04_emmeans.html">
 <span class="dropdown-text">2/4: Simple Effects &amp; Pairwise Comparisons</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_05_writeup_recap.html">
 <span class="dropdown-text">2/5: Write Up &amp; Recap</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-topics-for-lm" role="button" data-bs-toggle="dropdown" aria-expanded="false">Advanced Topics for LM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-topics-for-lm">
<li class="dropdown-header">2/6: Binary Logistic Regression</li>
        <li class="dropdown-header">2/7: More Logistic Regression</li>
        <li class="dropdown-header">2/8: Sample Size &amp; Power Analysis</li>
        <li class="dropdown-header">2/9: Write Up &amp; Recap</li>
        <li class="dropdown-header">2/10: Mock Exam</li>
    </ul>
</li>
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#section-a-write-up" id="toc-section-a-write-up" class="nav-link active" data-scroll-target="#section-a-write-up">Section A: Write-Up</a>
  <ul class="collapse">
<li>
<a href="#study-overview" id="toc-study-overview" class="nav-link" data-scroll-target="#study-overview">Study Overview</a>
  <ul class="collapse">
<li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#analysis-code" id="toc-analysis-code" class="nav-link" data-scroll-target="#analysis-code">Analysis Code</a></li>
  <li><a href="#the-3-act-structure-analysis-strategy-results-discussion" id="toc-the-3-act-structure-analysis-strategy-results-discussion" class="nav-link" data-scroll-target="#the-3-act-structure-analysis-strategy-results-discussion">The 3-Act Structure: Analysis Strategy, Results, &amp; Discussion</a></li>
  </ul>
</li>
  </ul>
</li>
  <li><a href="#section-b-weeks-1-5-recap" id="toc-section-b-weeks-1-5-recap" class="nav-link" data-scroll-target="#section-b-weeks-1-5-recap">Section B: Weeks 1-5 Recap</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Write Up Example &amp; Block 3 Recap</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="lo">
<section id="learning-objectives" class="level3"><h3 class="anchored" data-anchor-id="learning-objectives">
<i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Understand how to write-up and provide interpretation of a 2x2 factorial ANOVA</li>
</ol></section><section id="what-you-need" class="level3"><h3 class="anchored" data-anchor-id="what-you-need">
<i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed Labs 1-4</li>
</ol></section><section id="required-r-packages" class="level3"><h3 class="anchored" data-anchor-id="required-r-packages">
<i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
<li><strong>psych</strong></li>
<li><strong>kableExtra</strong></li>
<li><strong>emmeans</strong></li>
</ul></section><section id="lab-data" class="level3"><h3 class="anchored" data-anchor-id="lab-data">
<i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/lietraining.csv">here</a> or read it in via this link https://uoepsy.github.io/data/lietraining.csv.</p>
</section>
</div>
<section id="section-a-write-up" class="level1"><h1>Section A: Write-Up</h1>
<p>In this section of the lab you will be be presented with a research question, and tasked with writing up and presenting your analyses.</p>
<p>The aim in writing should be that a reader is able to more or less replicate your analyses <strong>without</strong> referring to your R code. This requires detailing all of the steps you took in conducting the analysis. The point of using RMarkdown is that you can pull your results <strong>directly</strong> from the code. If your analysis changes, so does your report!</p>
<p>Make sure that your final report doesn’t show any R functions or code. Remember you are interpreting and reporting your results in text, tables, or plots, targeting a generic reader who may use different software or may not know R at all. If you need a reminder on how to hide code, format tables, etc., make sure to review the <a href="https://uoepsy.github.io//rmd-bootcamp/">rmd bootcamp</a>.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important - Write-Up Examples &amp; Plagiarism
</div>
</div>
<div class="callout-body-container callout-body">
<p>The example write-up sections included below are not <strong>perfect</strong> - they instead should give you a good example of what information you should include within each section, and how to structure this. For example, some information is missing (e.g., interpretation of descriptive statistics, what type of interaction is present), some information could be presented more clearly (e.g., variable names in tables, table/figure titles/captions, and rationales for choices), and writing could be more concise in places (e.g., discussion section is quite long).</p>
<p>Further, <strong>you must not copy any of the write-up included below for future reports</strong> - if you do, you will be committing plagiarism, and this type of academic misconduct is taken very seriously by the University. You can find out more <a href="https://www.ed.ac.uk/academic-services/students/conduct/academic-misconduct">here</a>.</p>
</div>
</div>
<section id="study-overview" class="level2"><h2 class="anchored" data-anchor-id="study-overview">Study Overview</h2>
<blockquote class="blockquote">
<p><strong>Research Question</strong></p>
<p>Do Police training materials and the mode of communication influence the accuracy of veracity judgements?</p>
</blockquote>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Lie detectors: Data Codebook</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>A total of 120 participants took part in a study in which they were presented with 100 recordings, and were tasked with guessing whether the speaker in each recording was lying or whether they were telling the truth.</p>
<p>Participants scored points every time they correctly identified a truth or a lie, and lost points whenever they mistook a lie for a truth (or vice versa). The maximum possible points to be scored was 100.</p>
<p>Half of the participants (<span class="math inline">\(n\)</span> = 60) were shown recordings in audio and video, the other half were presented with only the audio track.</p>
<p>Prior to taking part in the experiment, participants were given material to read for 10 minutes. Half of the participants in each condition (30 in the audio-only condition, and 30 in the audiovideo condition) were given instructional material used by the Police Force to train detectives to pick up on dishonesty during interrogations via various verbal and non-verbal cues. The remaining 30 participants in each condition were given a series of <a href="https://external-preview.redd.it/OY7xRuBBRkx8JFrjYoh3PswM2VMBDHBv4oXbpIEcB3Q.jpg?auto=webp&amp;s=1a12316259fdfd314d4060f44f30260735741da5">cartoon strips to read</a>.</p>
<p>The data in <code>lietraining.csv</code> contain seven attributes collected from a sample of <span class="math inline">\(n=120\)</span> participants:</p>
<ul>
<li>
<code>pid</code>: Participant ID</li>
<li>
<code>age</code>: Age (in years) of participant</li>
<li>
<code>trained</code>: Whether participants were given instructional material used by the Police Force to train detectives to pick up on dishonesty during interrogations via various verbal and non-verbal cues (yes = <code>y</code> / no = <code>n</code>)</li>
<li>
<code>audiovideo</code>: Audio-Video recording condition - either <code>audio+video</code> for those participants shown recordings in audio and video, or <code>ausio-only</code> for those participants presented with only the audio track</li>
<li>
<code>points</code>: Points scored for identifying a truth or a lie (range: 0-100)</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell">
<div class="cell-output-display">

<div id="pqxkbfqhgj" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#pqxkbfqhgj .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#pqxkbfqhgj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#pqxkbfqhgj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#pqxkbfqhgj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#pqxkbfqhgj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#pqxkbfqhgj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#pqxkbfqhgj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#pqxkbfqhgj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#pqxkbfqhgj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#pqxkbfqhgj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#pqxkbfqhgj .gt_from_md > :first-child {
  margin-top: 0;
}

#pqxkbfqhgj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#pqxkbfqhgj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#pqxkbfqhgj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#pqxkbfqhgj .gt_row_group_first td {
  border-top-width: 2px;
}

#pqxkbfqhgj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#pqxkbfqhgj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#pqxkbfqhgj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#pqxkbfqhgj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#pqxkbfqhgj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pqxkbfqhgj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pqxkbfqhgj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pqxkbfqhgj .gt_left {
  text-align: left;
}

#pqxkbfqhgj .gt_center {
  text-align: center;
}

#pqxkbfqhgj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#pqxkbfqhgj .gt_font_normal {
  font-weight: normal;
}

#pqxkbfqhgj .gt_font_bold {
  font-weight: bold;
}

#pqxkbfqhgj .gt_font_italic {
  font-style: italic;
}

#pqxkbfqhgj .gt_super {
  font-size: 65%;
}

#pqxkbfqhgj .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#pqxkbfqhgj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#pqxkbfqhgj .gt_indent_1 {
  text-indent: 5px;
}

#pqxkbfqhgj .gt_indent_2 {
  text-indent: 10px;
}

#pqxkbfqhgj .gt_indent_3 {
  text-indent: 15px;
}

#pqxkbfqhgj .gt_indent_4 {
  text-indent: 20px;
}

#pqxkbfqhgj .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">pid</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">age</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">trained</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">audiovideo</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">points</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left">ppt_1</td>
<td class="gt_row gt_right">26</td>
<td class="gt_row gt_left">y</td>
<td class="gt_row gt_left">audio+video</td>
<td class="gt_row gt_right">36.23952</td>
</tr>
<tr>
<td class="gt_row gt_left">ppt_2</td>
<td class="gt_row gt_right">22</td>
<td class="gt_row gt_left">y</td>
<td class="gt_row gt_left">audio+video</td>
<td class="gt_row gt_right">38.46473</td>
</tr>
<tr>
<td class="gt_row gt_left">ppt_3</td>
<td class="gt_row gt_right">18</td>
<td class="gt_row gt_left">y</td>
<td class="gt_row gt_left">audio+video</td>
<td class="gt_row gt_right">34.19058</td>
</tr>
<tr>
<td class="gt_row gt_left">ppt_4</td>
<td class="gt_row gt_right">22</td>
<td class="gt_row gt_left">y</td>
<td class="gt_row gt_left">audio+video</td>
<td class="gt_row gt_right">52.62804</td>
</tr>
<tr>
<td class="gt_row gt_left">ppt_5</td>
<td class="gt_row gt_right">21</td>
<td class="gt_row gt_left">y</td>
<td class="gt_row gt_left">audio+video</td>
<td class="gt_row gt_right">38.89564</td>
</tr>
<tr>
<td class="gt_row gt_left">ppt_6</td>
<td class="gt_row gt_right">27</td>
<td class="gt_row gt_left">y</td>
<td class="gt_row gt_left">audio+video</td>
<td class="gt_row gt_right">37.46595</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<section id="setup" class="level3"><h3 class="anchored" data-anchor-id="setup">Setup</h3>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the lietraining dataset into R, assigning it to an object named <code>liedat</code>
</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://personality-project.org/r/psych/">psych</a></span><span class="op">)</span> </span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/rvlenth/emmeans">emmeans</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co">#read in data</span></span>
<span><span class="va">liedat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/lietraining.csv"</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
</section><section id="analysis-code" class="level3"><h3 class="anchored" data-anchor-id="analysis-code">Analysis Code</h3>
<p>Try to answer the research question above without referring to the provided analysis code below, and then check how your script matches up - is there anything you missed or done differently? If so, discuss the differences with a tutor - there are lots of ways to code to the same solution!</p>
<div class="optional-begin">
<span id="opt-start-3" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-3', 'opt-start-3')"> <span class="olab">Provided Analysis Code</span></span>
</div>
<div id="opt-body-3" class="optional-body" style="display: none;">
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">######Step 1 is always to read in the data, then to explore, check, describe, and visualise it.</span></span>
<span></span>
<span><span class="co">#check coding of variables - are they coded as they should be?</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">liedat</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spec_tbl_df [120 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ pid       : chr [1:120] "ppt_1" "ppt_2" "ppt_3" "ppt_4" ...
 $ age       : num [1:120] 26 22 18 22 21 27 27 26 25 22 ...
 $ trained   : chr [1:120] "y" "y" "y" "y" ...
 $ audiovideo: chr [1:120] "audio+video" "audio+video" "audio+video" "audio+video" ...
 $ points    : num [1:120] 36.2 38.5 34.2 52.6 38.9 ...
 - attr(*, "spec")=
  .. cols(
  ..   pid = col_character(),
  ..   age = col_double(),
  ..   trained = col_character(),
  ..   audiovideo = col_character(),
  ..   points = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">liedat</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  pid     age trained audiovideo  points
  &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt;
1 ppt_1    26 y       audio+video   36.2
2 ppt_2    22 y       audio+video   38.5
3 ppt_3    18 y       audio+video   34.2
4 ppt_4    22 y       audio+video   52.6
5 ppt_5    21 y       audio+video   38.9
6 ppt_6    27 y       audio+video   37.5</code></pre>
</div>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#make variables factors &amp; label</span></span>
<span><span class="va">liedat</span><span class="op">$</span><span class="va">audiovideo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">liedat</span><span class="op">$</span><span class="va">audiovideo</span>, labels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"audio"</span>,<span class="st">"audio+video"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">liedat</span><span class="op">$</span><span class="va">trained</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">liedat</span><span class="op">$</span><span class="va">trained</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"untrained"</span>,<span class="st">"trained"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#create descriptives table</span></span>
<span><span class="va">descript</span> <span class="op">&lt;-</span> <span class="va">liedat</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">audiovideo</span>, <span class="va">trained</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>   <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>       meanpoints <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">points</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>       se <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">points</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'audiovideo'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">descript</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   audiovideo [2]
  audiovideo  trained   meanpoints    se
  &lt;fct&gt;       &lt;fct&gt;          &lt;dbl&gt; &lt;dbl&gt;
1 audio       untrained       52.8  1.27
2 audio       trained         53.7  1.55
3 audio+video untrained       49.9  1.01
4 audio+video trained         40.4  1.12</code></pre>
</div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#boxplot</span></span>
<span><span class="va">p0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">liedat</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">audiovideo</span>, y <span class="op">=</span> <span class="va">points</span>, color <span class="op">=</span> <span class="va">trained</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/lims.html">ylim</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">100</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Communication Condition"</span>, y <span class="op">=</span> <span class="st">"Accuracy Score"</span><span class="op">)</span></span>
<span><span class="va">p0</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_05_writeup_recap_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#plot showing the mean points for each condition</span></span>
<span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">descript</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">audiovideo</span>, y <span class="op">=</span> <span class="va">meanpoints</span>, color <span class="op">=</span> <span class="va">trained</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_linerange</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">meanpoints</span> <span class="op">-</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">se</span>, ymax <span class="op">=</span> <span class="va">meanpoints</span> <span class="op">+</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">se</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">audiovideo</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">p1</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_05_writeup_recap_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">######Step 2 is to run your model(s) of interest to answer your research question, and make sure that the data meet the assumptions of your chosen test</span></span>
<span></span>
<span><span class="co">#build model</span></span>
<span><span class="va">lie_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">points</span> <span class="op">~</span> <span class="va">audiovideo</span> <span class="op">*</span> <span class="va">trained</span>, data <span class="op">=</span> <span class="va">liedat</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#check assumptions</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">lie_mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_05_writeup_recap_files/figure-html/unnamed-chunk-3-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># look at model output - summary() and anova()</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lie_mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = points ~ audiovideo * trained, data = liedat)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.1947  -4.2134  -0.7559   4.5235  21.1755 

Coefficients:
                                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                           52.7591     1.2576  41.953  &lt; 2e-16 ***
audiovideoaudio+video                 -2.8367     1.7785  -1.595    0.113    
trainedtrained                         0.9759     1.7785   0.549    0.584    
audiovideoaudio+video:trainedtrained -10.4830     2.5152  -4.168 5.95e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.888 on 116 degrees of freedom
Multiple R-squared:  0.3768,    Adjusted R-squared:  0.3607 
F-statistic: 23.38 on 3 and 116 DF,  p-value: 6.591e-12</code></pre>
</div>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">lie_mdl</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: points
                    Df Sum Sq Mean Sq F value    Pr(&gt;F)    
audiovideo           1 1957.7 1957.71  41.263 3.046e-09 ***
trained              1  545.8  545.85  11.505   0.00095 ***
audiovideo:trained   1  824.2  824.20  17.372 5.949e-05 ***
Residuals          116 5503.6   47.45                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#int model plot</span></span>
<span><span class="va">plt_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmip.html">emmip</a></span><span class="op">(</span><span class="va">lie_mdl</span>, <span class="va">trained</span><span class="op">~</span><span class="va">audiovideo</span>,</span>
<span>                     CIs <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>                     xlab <span class="op">=</span> <span class="st">"Mode of Communication"</span>,</span>
<span>                     ylab <span class="op">=</span> <span class="st">"Predicted Accuracy Scores"</span>,</span>
<span>                     title <span class="op">=</span> <span class="st">"Interaction Model"</span><span class="op">)</span> </span>
<span><span class="va">plt_mdl</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_05_writeup_recap_files/figure-html/unnamed-chunk-3-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#####Step 3 somewhat depends on the outcomes of step 2. Here, you may need to consider conducting further analyses before writing up / describing your results in relation to the research question. </span></span>
<span></span>
<span><span class="co">#Perform a pairwise comparison of the mean accuracy (as measured by points accrued) across the 2×2 factorial design, making sure to adjust for multiple comparisons. </span></span>
<span></span>
<span><span class="va">emms_lie</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">lie_mdl</span>, <span class="op">~</span> <span class="va">audiovideo</span> <span class="op">*</span> <span class="va">trained</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lie_con</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">emms_lie</span>, method <span class="op">=</span> <span class="st">"pairwise"</span>, adjust<span class="op">=</span><span class="st">"tukey"</span><span class="op">)</span></span>
<span><span class="va">lie_con</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                        estimate   SE  df t.ratio
 audio untrained - (audio+video untrained)          2.837 1.78 116   1.595
 audio untrained - audio trained                   -0.976 1.78 116  -0.549
 audio untrained - (audio+video trained)           12.344 1.78 116   6.941
 (audio+video untrained) - audio trained           -3.813 1.78 116  -2.144
 (audio+video untrained) - (audio+video trained)    9.507 1.78 116   5.346
 audio trained - (audio+video trained)             13.320 1.78 116   7.489
 p.value
  0.3855
  0.9467
  &lt;.0001
  0.1456
  &lt;.0001
  &lt;.0001

P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># confidence intervals</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">lie_con</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                        estimate   SE  df lower.CL
 audio untrained - (audio+video untrained)          2.837 1.78 116    -1.80
 audio untrained - audio trained                   -0.976 1.78 116    -5.61
 audio untrained - (audio+video trained)           12.344 1.78 116     7.71
 (audio+video untrained) - audio trained           -3.813 1.78 116    -8.45
 (audio+video untrained) - (audio+video trained)    9.507 1.78 116     4.87
 audio trained - (audio+video trained)             13.320 1.78 116     8.68
 upper.CL
    7.473
    3.660
   16.980
    0.823
   14.143
   17.956

Confidence level used: 0.95 
Conf-level adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co">#plot</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">lie_con</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<p><img src="2_05_writeup_recap_files/figure-html/unnamed-chunk-3-5.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section><section id="the-3-act-structure-analysis-strategy-results-discussion" class="level3"><h3 class="anchored" data-anchor-id="the-3-act-structure-analysis-strategy-results-discussion">The 3-Act Structure: Analysis Strategy, Results, &amp; Discussion</h3>
<p>Recall that we need to present our report in three clear sections - think of your sections like the 3 key parts of a play or story - we need to (1) provide some background and scene setting for the reader, (2) present our results in the context of the research question, and (3) present a resolution to our story - relate our findings back to the question we were asked and provide our answer.</p>
<p>If you need a reminder of what to include within each section, refer to <a href="https://uoepsy.github.io/dapr2/2223/labs/1_11_writeup_recap.html">Semester 1 Lab 11</a>, and read through the ‘what to include’ sections for Analysis Strategy, Results, and Discussion.</p>
<section id="act-i-analysis-strategy" class="level4"><h4 class="anchored" data-anchor-id="act-i-analysis-strategy">Act I: Analysis Strategy</h4>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Attempt to draft a discussion section based on the above research question and analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="optional-begin">
<span id="opt-start-4" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-4', 'opt-start-4')"> <span class="olab">Example Write-Up of Analysis Strategy Section</span></span>
</div>
<div id="opt-body-4" class="optional-body" style="display: none;">
<p>The <code>lietraining</code> dataset contained information on 120 participants who took part in a study concerning lie detection. Participants were each presented with 100 recordings (half were shown recordings in audio and video, and the other half audio only), and were tasked with judging whether the speaker in each recording was lying or whether they were telling the truth. Participants scored 1 point each time they correctly identified a truth or a lie, and lost 1 point whenever they mistook a lie for a truth (or vice versa). The maximum score was 100, where higher scores reflected higher levels of accuracy. Prior to taking part in the experiment participants were given materials to read. Half of the participants in each condition were given instructional material used by the Police Force (used to train detectives to pick up on dishonesty during interrogations via various verbal and non-verbal cues) and the remaining 30 participants in each condition were given a series of <a href="https://external-preview.redd.it/OY7xRuBBRkx8JFrjYoh3PswM2VMBDHBv4oXbpIEcB3Q.jpg?auto=webp&amp;s=1a12316259fdfd314d4060f44f30260735741da5">cartoon strips to read</a>.</p>
<p>All participant data was complete, and accuracy scores (points) within range i.e., 0-100. Categorical variables were coded as factors, where audio was designated as the reference level for mode of communication, and untrained as the reference level for training materials.</p>
<p>To investigate whether police training materials (trained vs untrained) and the mode of communication (audio vs audiovideo) interacted to influence the accuracy of veracity judgements, a two-way ANOVA model was used. Effects were considered statistically significant at <span class="math inline">\(\alpha = 0.05\)</span>. Using dummy coding, the following model specification was used:</p>
<p><span class="math display">\[
\begin{aligned}
\text{Accuracy Scores} &amp;= \beta_0 \\
&amp;+ \beta_1 A_\text{AudioVideo} + \beta_2 T_\text{Trained} \\
&amp;+ \beta_3 (A_\text{AudioVideo} * T_\text{Trained}) \\
&amp;+ \epsilon
\end{aligned}
\]</span></p>
<p>To address the research question of whether the interaction between training materials and mode of communication was statistically significant, this formally corresponded to testing whether the interaction coefficient was equal to zero:</p>
<p><span class="math display">\[
H_0: \beta_3 = 0
\]</span></p>
<p><span class="math display">\[
H_1: \beta_3 \neq 0
\]</span></p>
<p>The following assumptions were assessed visually using diagnostic plots: independence (with the previous plot and a plot of residuals vs index; no dependence should be indicated), equal variances (via a scale-location plot; residuals should be evenly spread across the range of fitted values, where the spread should be constant across the range of fitted values), and normality (via a qqplot of the residuals; points should follow along the diagonal line). We also checked if there was any evidence of multicollinearity by checking VIF values, where values &gt; 5 were considered to indicate moderate multicollinearity, and values &gt; 10 severe. Outliers were assessed via Cooks Distance, where values &gt;2 indicated influential points.</p>
</div>
<p class="optional-end">
</p>
</section><section id="act-ii-results" class="level4"><h4 class="anchored" data-anchor-id="act-ii-results">Act II: Results</h4>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Attempt to draft a results section based on your detailed analysis strategy and the analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="optional-begin">
<span id="opt-start-5" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-5', 'opt-start-5')"> <span class="olab">Example Write-Up of Results Section</span></span>
</div>
<div id="opt-body-5" class="optional-body" style="display: none;">
<p>Descriptive statistics are displayed in <a href="#tbl-descript">Table&nbsp;1</a>.</p>
<div class="cell" data-caption="Descriptives Table">
<div class="cell-output-display">
<div id="tbl-descript" class="anchored">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Table 1:  Descriptive Statistics </caption>
 <thead><tr>
<th style="text-align:left;"> audiovideo </th>
   <th style="text-align:left;"> trained </th>
   <th style="text-align:right;"> mean_points </th>
   <th style="text-align:right;"> se </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:left;"> audio </td>
   <td style="text-align:left;"> untrained </td>
   <td style="text-align:right;"> 52.76 </td>
   <td style="text-align:right;"> 1.27 </td>
  </tr>
<tr>
<td style="text-align:left;"> audio </td>
   <td style="text-align:left;"> trained </td>
   <td style="text-align:right;"> 53.74 </td>
   <td style="text-align:right;"> 1.55 </td>
  </tr>
<tr>
<td style="text-align:left;"> audio+video </td>
   <td style="text-align:left;"> untrained </td>
   <td style="text-align:right;"> 49.92 </td>
   <td style="text-align:right;"> 1.01 </td>
  </tr>
<tr>
<td style="text-align:left;"> audio+video </td>
   <td style="text-align:left;"> trained </td>
   <td style="text-align:right;"> 40.42 </td>
   <td style="text-align:right;"> 1.12 </td>
  </tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In the audio condition, there did not appear to be a difference between trained and non-trained scores. However, untrained scored higher than trained in the audio+video condition. This suggested that there may be an interaction (see <a href="#fig-lieplot">Figure&nbsp;1</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lieplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_05_writeup_recap_files/figure-html/fig-lieplot-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 1: Association between Score and Communication / Training Conditions</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Accuracy of veracity judgements (measured by points scored in lie-detecting game) were analysed with a 2 (audio vs audiovideo) <span class="math inline">\(\times\)</span> 2 (untrained vs trained) between-subjects ANOVA.</p>
<p>The model met assumptions of linearity and independence (see top left panel of <a href="#fig-assumpt">Figure&nbsp;2</a>; residuals were randomly scattered with a mean of zero and there was no clear dependence), homoscedasticity (see bottom left panel of <a href="#fig-assumpt">Figure&nbsp;2</a>; there was a constant spread of residuals), and normality (see top right panel of <a href="#fig-assumpt">Figure&nbsp;2</a>; the QQplot showed very little deviation from the diagonal line).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-assumpt" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_05_writeup_recap_files/figure-html/fig-assumpt-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 2: Diagnostic Plots</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>There was a significant interaction between presentation mode and whether or not participants had received training for detecting lies <span class="math inline">\(F(1, 116) = 17.37, p &lt;. 001\)</span> (see <a href="#tbl-aovout">Table&nbsp;2</a>).</p>
<div class="cell" data-caption="ANOVA Output">
<div class="cell-output-display">
<div id="tbl-aovout" class="anchored">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Table 2:  Model Results </caption>
 <thead><tr>
<th style="text-align:left;">   </th>
   <th style="text-align:right;"> Df </th>
   <th style="text-align:right;"> Sum Sq </th>
   <th style="text-align:right;"> Mean Sq </th>
   <th style="text-align:right;"> F value </th>
   <th style="text-align:right;"> Pr(&gt;F) </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:left;"> audiovideo </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1957.71 </td>
   <td style="text-align:right;"> 1957.71 </td>
   <td style="text-align:right;"> 41.26 </td>
   <td style="text-align:right;"> 0.00e+00 </td>
  </tr>
<tr>
<td style="text-align:left;"> trained </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 545.85 </td>
   <td style="text-align:right;"> 545.85 </td>
   <td style="text-align:right;"> 11.50 </td>
   <td style="text-align:right;"> 9.50e-04 </td>
  </tr>
<tr>
<td style="text-align:left;"> audiovideo:trained </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 824.20 </td>
   <td style="text-align:right;"> 824.20 </td>
   <td style="text-align:right;"> 17.37 </td>
   <td style="text-align:right;"> 5.95e-05 </td>
  </tr>
<tr>
<td style="text-align:left;"> Residuals </td>
   <td style="text-align:right;"> 116 </td>
   <td style="text-align:right;"> 5503.63 </td>
   <td style="text-align:right;"> 47.45 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:right;"> NA </td>
  </tr>
</tbody>
</table>
</div>
</div>
</div>
<p>As displayed in <a href="#fig-intplot">Figure&nbsp;3</a>, results suggested that the difference in points did not differ significantly in the audio condition regardless of training, but that there were significant differences in the audio-video condition where untrained participants had higher accuracy scores than trained.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-intplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_05_writeup_recap_files/figure-html/fig-intplot-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 3: Interaction Plot</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>To explore the interaction further, pairwise comparisons were conducted. Tukey’s Honestly Significant Difference comparisons (see <a href="#fig-contrastplot">Figure&nbsp;4</a>) indicated that, contrary to what one might expect, participants who were presented with audiovisual recordings scored on average 9.5 points lower when they had read the police training materials compared to when they had received no training (95% CI [4.87 — 14.14]). The presentation mode (audio vs audio-video) was not found to result in a significantly different average score for those who were untrained (95% CI [-1.80 — 7.47]), and nor did training appear to have any effect on detecting lies in the audio-only condition (95% CI [-5.61 — 3.66]).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-contrastplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="2_05_writeup_recap_files/figure-html/fig-contrastplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 4: Tukey HSD Pairwise Comparisons</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</section><section id="act-iii-discussion" class="level4"><h4 class="anchored" data-anchor-id="act-iii-discussion">Act III: Discussion</h4>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Attempt to draft a discussion section based on your results and the analysis provided.</p>
</div>
<p class="question-end">
</p>
<div class="optional-begin">
<span id="opt-start-6" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-6', 'opt-start-6')"> <span class="olab">Example Write-Up of Discussion Section</span></span>
</div>
<div id="opt-body-6" class="optional-body" style="display: none;">
<p>The findings indicated that, in general, people were inaccurate when trying to distinguish between a lie and the truth, as the overall mean score was 49.21 out of 100 (SD = 8.61), where a series of completely random guesses expected to score 50/100. Our results led us to reject the null hypothesis that the interaction coefficient was equal to zero, as the results indicated that the association between police training materials and mode of communication did interact to influence the accuracy of veracity judgements. The direction of this association was surprising - trained participants performed more poorly (compared to untrained) in the audio-visual condition. This may indicate that the training materials focus too heavily on visual cues (since there was no difference in police training conditions in the audio-only communication condition), which perhaps are not actually associated with dishonesty in the appropriate way.</p>
</div>
<p class="optional-end">
</p>
</section></section></section></section><section id="section-b-weeks-1-5-recap" class="level1"><h1>Section B: Weeks 1-5 Recap</h1>
<p>In the second part of the lab, there is no new content - the purpose of the recap section is for you to revisit and revise the concepts you have learned over the last 4/5 weeks.</p>
<div class="red">
<p>Before you expand each of the boxes below, think about how comfortable you feel with each concept.</p>
</div>
<div class="optional-begin">
<span id="opt-start-7" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-7', 'opt-start-7')"> <span class="olab">F-Ratio</span></span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<p>As in simple linear regression, the <span class="math inline">\(F\)</span>-ratio is used to test the null hypothesis that all regression slopes are zero.</p>
<p>It is called the <span class="math inline">\(F\)</span>-ratio because it is the ratio of the how much of the variation is explained by the model (per paramater) versus how much of the variation is unexplained (per remaining degrees of freedom).</p>
<p><span class="math display">\[
F_{df_{model},df_{residual}} = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model}/df_{Model}}{SS_{Residual}/df_{Residual}} \\
\quad \\
\]</span></p>
<p><span class="math display">\[
\begin{align}
&amp; \text{Where:} \\
&amp; df_{model} = k \\
&amp; df_{error} = n-k-1 \\
&amp; n = \text{sample size} \\
&amp; k  = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
<hr>
<div class="blue">
<p>In <strong>R</strong>, at the bottom of the output of <code>summary(&lt;modelname&gt;)</code>,:</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure"><p><img src="images/mlroutputf.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Multiple regression output in R, summary.lm(). F statistic highlighted</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<p>The <span class="math inline">\(F\)</span>-ratio you see at the bottom of <code>summary(model)</code> is actually a comparison between two models: your model (with some explanatory variables in predicting <span class="math inline">\(y\)</span>) and the <em>null model</em>.</p>
<p>In regression, the null model can be thought of as the model in which all explanatory variables have zero regression coefficients. It is also referred to as the <strong>intercept-only model</strong>, because if all predictor variable coefficients are zero, then the only we are only estimating <span class="math inline">\(y\)</span> via an intercept (which will be the mean - <span class="math inline">\(\bar y\)</span>).</p>
<p>Alongside viewing the <span class="math inline">\(F\)</span>-ratio, you can see the results from testing the null hypothesis that all of the coefficients are <span class="math inline">\(0\)</span> (the alternative hypothesis is that at least one coefficient is <span class="math inline">\(\neq 0\)</span>. Under the null hypothesis that all coefficients = 0, the ratio of explained:unexplained variance should be approximately 1)</p>
<p>:::</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 1 <a href="https://uoepsy.github.io/dapr2/2223/labs/2_01_model_comps.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_11_modelcomparison#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-8" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-8', 'opt-start-8')"> <span class="olab">Nested vs Non-Nested Models</span></span>
</div>
<div id="opt-body-8" class="optional-body" style="display: none;">
<p><strong>Nested Models</strong></p>
<p>Consider that you have two regression models where Model 1 contains a subset of the predictors contained in the other Model 2 and is fitted to the same data. More simply, Model 2 contains all of the predictors included in Model 1, <strong>plus</strong> additional predictor(s). This means that Model 1 is <em>nested</em> within Model 2, or that Model 1 is a <em>submodel</em> of Model 2. These two terms, at least in this setting, are interchangeable - it might be easier to think of Model 1 as your null and Model 2 as your alternative.</p>
<p><strong>Non-Nested Models</strong></p>
<p>Consider that you have two regression models where Model 1 contains different variables to those contained in Model 2, where both models are fitted to the same data. More simply, Model 1 and Model 2 contain unique variables that are not shared. This means that Model 1 and Model 2 are <strong>not</strong> nested.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 1 <a href="https://uoepsy.github.io/dapr2/2223/labs/2_01_model_comps.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_11_modelcomparison#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-9" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-9', 'opt-start-9')"> <span class="olab">Incremental F-test</span></span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p>If (<em>and only if</em>) two models are <strong>nested</strong>, can we compare them using an <strong>incremental F-test</strong>.</p>
<p>This is a formal test of whether the additional predictors provide a better fitting model.<br>
Formally this is the test of:</p>
<ul>
<li>
<span class="math inline">\(H_0:\)</span> coefficients for the added/omitted variables are all zero.</li>
<li>
<span class="math inline">\(H_1:\)</span> at least one of the added/omitted variables has a coefficient that is not zero.</li>
</ul>
<p>The <span class="math inline">\(F\)</span>-ratio for comparing the residual sums of squares between two models can be calculated as:</p>
<p><span class="math display">\[
F_{(df_R-df_F),df_F} = \frac{(SSR_R-SSR_F)/(df_R-df_F)}{SSR_F / df_F} \\
\quad \\
\]</span></p>
<p><span class="math display">\[
\begin{align}
&amp; \text{Where:} \\
\\
&amp; SSR_R = \text{residual sums of squares for the restricted model} \\
&amp; SSR_F = \text{residual sums of squares for the full model} \\
&amp; df_R = \text{residual degrees of freedom from the restricted model} \\
&amp; df_F = \text{residual degrees of freedom from the full model} \\
\end{align}
\]</span></p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 1 <a href="https://uoepsy.github.io/dapr2/2223/labs/2_01_model_comps.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_11_modelcomparison#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-10" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-10', 'opt-start-10')"> <span class="olab">Comparing regression models with anova()</span></span>
</div>
<div id="opt-body-10" class="optional-body" style="display: none;">
<p>Remember that you want your models to be <em>parsimonious</em>, or in other words, only as complex as they need to be in order to describe the data well. This means that you need to be able to justify your model choice, and one way to do so is by comparing models via <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code>. If your model with multiple IVs does not provide a significantly better fit to your data than a more simplistic model with less IVs, then the more simplistic model should be preferred.</p>
<div class="blue">
<p>In <strong>R</strong>, we can conduct an incremental <span class="math inline">\(F\)</span>-test by constructing two linear regression models, and passing them to the <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> function:</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">model1</span>, <span class="va">model2</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<p>If the <span class="math inline">\(p\)</span>-value is sufficiently low (i.e., below your predetermined significance level - usually .05), then you would conclude that model 2 is significantly better fitting than model 1. If <span class="math inline">\(p\)</span> is not &lt; .05, then you should favor the more simplistic model.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 1 <a href="https://uoepsy.github.io/dapr2/2223/labs/2_01_model_comps.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_11_modelcomparison#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-11" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-11', 'opt-start-11')"> <span class="olab">AIC &amp; BIC</span></span>
</div>
<div id="opt-body-11" class="optional-body" style="display: none;">
<p>AIC (Akaike Information Criterion) and BIC (Bayesian Information Criterion) combine information about the sample size, the number of model parameters, and the residual sums of squares (<span class="math inline">\(SS_{residual}\)</span>). Models do not <em>need</em> to be nested to be compared via AIC and BIC, <strong>but</strong> they need to have been fit to the same dataset.</p>
<p>For both of these fit indices, lower values are better, and both include a penalty for the number of predictors in the model (although BIC’s penalty is harsher):</p>
<p><span class="math display">\[
AIC = n\,\text{ln}\left( \frac{SS_{residual}}{n} \right) + 2k \\
\quad \\
BIC = n\,\text{ln}\left( \frac{SS_{residual}}{n} \right) + k\,\text{ln}(n) \\
\quad \\
\]</span></p>
<p><span class="math display">\[
\begin{align}
&amp; \text{Where:} \\
&amp; SS_{residual} = \text{sum of squares residuals} \\
&amp; n = \text{sample size} \\
&amp; k = \text{number of explanatory variables} \\
&amp; \text{ln} = \text{natural log function}
\end{align}
\]</span></p>
<div class="blue">
<p>In <strong>R</strong>, we can calculate AIC and BIC by using the <code><a href="https://rdrr.io/r/stats/AIC.html">AIC()</a></code> and <code><a href="https://rdrr.io/r/stats/AIC.html">BIC()</a></code> functions respectively.</p>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 1 <a href="https://uoepsy.github.io/dapr2/2223/labs/2_01_model_comps.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_11_modelcomparison#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-12" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-12', 'opt-start-12')"> <span class="olab">Side Contraints</span></span>
</div>
<div id="opt-body-12" class="optional-body" style="display: none;">
<p>Possible side-constraints on the parameters are:</p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 30%">
<col style="width: 38%">
<col style="width: 16%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Name</th>
<th style="text-align: center;">Constraint</th>
<th style="text-align: center;">Meaning of <span class="math inline">\(\beta_0\)</span>
</th>
<th style="text-align: center;">R</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Sum to zero (Effects Coding)</td>
<td style="text-align: center;"><span class="math inline">\(\beta_1 + \beta_2 + \beta_3 = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\beta_0 = \mu\)</span></td>
<td style="text-align: center;"><code>contr.sum</code></td>
</tr>
<tr class="even">
<td style="text-align: center;">Reference group (Dummy Coding)</td>
<td style="text-align: center;"><span class="math inline">\(\beta_1 = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\beta_0 = \mu_1\)</span></td>
<td style="text-align: center;"><code>contr.treatment</code></td>
</tr>
</tbody>
</table>
<div class="blue">
<p><strong>IMPORTANT</strong></p>
<ul>
<li><p>By default <code>R</code> uses the reference group constraint. If your factor has <span class="math inline">\(g\)</span> levels, your regression model will have <span class="math inline">\(g-1\)</span> dummy variables (<code>R</code> creates them for you)</p></li>
<li><p>We can switch back to the default reference group constraint by applying either of these:</p></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="co"># Option 1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span><span class="co"># Option 2</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">rest_spend</span><span class="op">$</span><span class="va">music</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"contr.treatment"</span></span></code></pre></div>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 2 <a href="https://uoepsy.github.io/dapr2/2223/labs/2_02_effects.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_12_effectscoding.html#2">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-13" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-13', 'opt-start-13')"> <span class="olab">Contrasts: Rules for Assigning Weights</span></span>
</div>
<div id="opt-body-13" class="optional-body" style="display: none;">
<ul>
<li>
<strong>Rule 1</strong>: Weights are -1 <span class="math inline">\(\geq\)</span> x <span class="math inline">\(\leq\)</span> 1</li>
<li>
<strong>Rule 2</strong>: The group(s) in one chunk are given negative weights, the group(s) in the other get positive weights</li>
<li>
<strong>Rule 3</strong>: The sum of the weights of the comparison must be 0</li>
<li>
<strong>Rule 4</strong>: If a group is not involved in the comparison, weight is 0</li>
<li>
<strong>Rule 5</strong>: For a given comparison, weights assigned to group(s) are equal to 1 divided by the number of groups in that chunk.</li>
<li>
<strong>Rule 6</strong>: Restrict yourself to running <span class="math inline">\(k\)</span> - 1 comparisons (where <span class="math inline">\(k\)</span> = number of groups)</li>
<li>
<strong>Rule 7</strong>: Each contrast can only compare 2 chunks of variance</li>
<li>
<strong>Rule 8</strong>: Once a group singled out, it can not enter other contrasts</li>
</ul>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 3 <a href="https://uoepsy.github.io/dapr2/2223/labs/2_03_contrasts.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_13_onewaycontrasts.html#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-14" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-14', 'opt-start-14')"> <span class="olab">Multiple Comparisons: Why does the Number of Tests Matter?</span></span>
</div>
<div id="opt-body-14" class="optional-body" style="display: none;">
<p>If we are conducting all possible pairwise comparisons, we can calculate how many tests are being conducted via the following rule:</p>
<p><span class="math display">\[
_nC_r = \frac{n!}{r!(n-r)!} \\
\]</span></p>
<p><span class="math display">\[
\begin{align} \\
&amp; \text{Where:} \\
&amp; n = \text{total number in the set} \\
&amp; r = \text{number chosen} \\
&amp; _nC_r = \text{number of combinations of r from n} \\
\end{align}
\]</span></p>
<p>So, why does the number of tests matter? First, think back to <a href="https://uoepsy.github.io/dapr1/2122/lectures/dapr1_2_05_errorspower.pdf">“Type 1 errors” from DAPR1</a> - when we conduct an hypothesis test, and we set <span class="math inline">\(\alpha = .05\)</span>, we will reject the null hypothesis <span class="math inline">\(H_0\)</span> when we find a <span class="math inline">\(p &lt; .05\)</span>. Now remember what a <span class="math inline">\(p\)</span>-value represents - it is the chance of observing a statistic at least as extreme as the one we do have, assuming the null hypothesis to be true. This means that <em>if</em> <span class="math inline">\(H_0\)</span> <strong>is</strong> true, then we will still observe a <span class="math inline">\(p &lt; .05\)</span> 5% of the time. So our chance of making this error = the threshold (<span class="math inline">\(\alpha\)</span>) at which below a p-value results in us rejecting <span class="math inline">\(H_0\)</span>.</p>
<p>But this error-rate applies to each statistical hypothesis we test. So if we conduct an experiment in which we plan on conducting lots of tests of different comparisons, the chance of an error being made increases substantially. Across the family of tests performed that chance will be much higher than 5%.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>Each test conducted at <span class="math inline">\(\alpha = .05\)</span> has a .05 (or 5%) probability of Type I error (wrongly rejecting the null hypothesis). If we do 9 tests, that experimentwise error rate is <span class="math inline">\(\alpha_{ew} \leq 9 \times .05\)</span>, where 9 is the number of comparisons made as part of the experiment.</p>
<p>Thus, if nine <strong>independent</strong> comparisons were made at the <span class="math inline">\(\alpha = 0.05\)</span> level, the experimentwise Type I error rate <span class="math inline">\(\alpha_{ew}\)</span> would be at most <span class="math inline">\(9 \times 0.05 = 0.45\)</span>. That is, we could wrongly reject the null hypothesis on average 45 times out of 100. To make this more confusing, many of the tests in a family are not <strong>independent</strong> (see the lecture slides for the calculation of error rate for dependent tests).</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 4 <a href="https://uoepsy.github.io/dapr2/2223/labs/2_04_emmeans.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_14_experimentaleffects.html#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-15" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-15', 'opt-start-15')"> <span class="olab">Multiple Comparisons: When to use Which Correction</span></span>
</div>
<div id="opt-body-15" class="optional-body" style="display: none;">
<p><strong>Bonferroni</strong></p>
<ul>
<li>Use Bonferroni’s method when you are interested in a small number of planned contrasts (or pairwise comparisons).</li>
<li>Bonferroni’s method is to divide alpha by the number of tests/confidence intervals.</li>
<li>Assumes that all comparisons are independent of one another.<br>
</li>
<li>It sacrifices slightly more power than Tukey’s method (discussed below), but it can be applied to any set of contrasts or linear combinations (i.e., it is useful in more situations than Tukey).</li>
<li>It is usually better than Tukey if we want to do a small number of planned comparisons.</li>
</ul>
<p><strong>Šídák</strong></p>
<ul>
<li>(A bit) more powerful than the Bonferroni method.</li>
<li>Assumes that all comparisons are independent of one another.</li>
<li>Less common than Bonferroni method, largely because it is more difficult to calculate (not a problem now we have computers).</li>
</ul>
<p><strong>Tukey</strong></p>
<ul>
<li>It specifies an exact family significance level for comparing all pairs of treatment means.<br>
</li>
<li>Use Tukey’s method when you are interested in all (or most) pairwise comparisons of means.</li>
</ul>
<p><strong>Scheffe</strong></p>
<ul>
<li>It is the most conservative (least powerful) of all tests.</li>
<li>It controls the family alpha level for testing all possible contrasts.</li>
<li>It should be used if you have not planned contrasts in advance.</li>
<li>For testing pairs of treatment means it is too conservative (you should use Bonferroni or Šídák).</li>
</ul>
<div class="blue">
<p>In <strong>R</strong>, you can easily change which correction you are using via the <code>adjust =</code> argument.</p>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 4 <a href="https://uoepsy.github.io/dapr2/2223/labs/2_04_emmeans.html">lab</a> and <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_14_experimentaleffects.html#1">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-16" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-16', 'opt-start-16')"> <span class="olab">Bootstrap: Terminology</span></span>
</div>
<div id="opt-body-16" class="optional-body" style="display: none;">
<ul>
<li>A <em>parameter</em> is a numerical summary for the population, e.g.&nbsp;the population slope <span class="math inline">\(\beta_1\)</span>
</li>
<li>A <em>statistic</em> is a numerical summary calculated from the sample data, e.g.&nbsp;the estimated slope in the sample <span class="math inline">\(\widehat \beta_1\)</span>. We use the sample statistic as a best guess, or estimate, for the unknown population parameter.</li>
<li>A <em>bootstrap sample</em> is chosen with replacement from an existing sample, using the same sample size.</li>
<li>A <em>bootstrap statistic</em> is a statistic computed for each bootstrap sample.</li>
<li>A <em>bootstrap distribution</em> collects bootstrap statistics for many bootstrap samples.</li>
</ul>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 5 <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_15_BootstrapLM">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-17" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-17', 'opt-start-17')"> <span class="olab">Bootstrap</span></span>
</div>
<div id="opt-body-17" class="optional-body" style="display: none;">
<p>The <em>bootstrap</em> is a general approach to assessing whether the sample results are statistically significant or not, and allows us to draw inferences to the population from a regression model. This method is assumption-free and does not rely on conditions such as normality of the residuals.</p>
<p>It is based on sampling repeatedly with replacement (to avoid always getting the original sample exactly) from the data at hand, and then computing the regression coefficients from each re-sample. We will equivalently use the word “bootstrap sample” or “resample” (for <strong>sample</strong> with <strong>re</strong>placement).</p>
<div class="frame">
<p>The basic principle is:</p>
<center>
<p><strong>The population is to the original sample</strong></p>
<p><strong>as</strong></p>
<p><strong>the original sample is to the bootstrap samples.</strong></p>
</center>
</div>
<p>Because we only have one sample of size <span class="math inline">\(n\)</span>, and we do not have access to the data for the entire population, we consider our original sample as our best approximation to the population.</p>
<p>To be more precise, we assume that the population is made up of many, many copies of our original sample. Then, we take multiple samples each of size <span class="math inline">\(n\)</span> from this assumed population. This is equivalent to sampling <em>with replacement</em> from the original sample.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="images/reg-boot.png" class="img-fluid" style="width:90.0%"></p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 5 <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_15_BootstrapLM">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-18" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-18', 'opt-start-18')"> <span class="olab">Bootstrap: In R</span></span>
</div>
<div id="opt-body-18" class="optional-body" style="display: none;">
<p>Follow these steps:</p>
<ul>
<li>1: Load the <code>car</code> library</li>
<li>2: Use the <code><a href="https://rdrr.io/pkg/car/man/Boot.html">Boot()</a></code> function (do not forget the uppercase B!) which takes as arguments:
<ul>
<li>the fitted model</li>
<li>
<code>f</code>, saying which bootstrap statistics to compute on each bootstrap sample. By default <code>f = coef</code>, returning the regression coefficients.</li>
<li>
<code>R</code>, saying how many bootstrap samples to compute. By default <code>R = 999</code> but this could be any number. To experiment we recommend 1000, when you want to produce results for journals, it is typical to go with 10,000 or more.</li>
<li>
<code>ncores</code>, saying if to perform the calculations in parallel (and more efficiently). However, this will depend on your PC, and you need to find how many cores you have by running <code><a href="https://rdrr.io/r/parallel/detectCores.html">parallel::detectCores()</a></code> on your PC. By default the function uses <code>ncores = 1</code>.</li>
</ul>
</li>
<li>3: Run the code. However, please remember that the <code><a href="https://rdrr.io/pkg/car/man/Boot.html">Boot()</a></code> function does <strong>not</strong> want a model which was fitted using data with <code>NAs</code>. To remove, for example, you could use <code>na.omit</code>.</li>
<li>4: Look at the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> of the bootstrap results. When doing so the output will show, for each regression coefficient, the value in the original sample in the column <code>original</code>, and in the <code>bootSE</code> column, the estimate of the variability of the coefficient from bootstrap sample to bootstrap sample. The <code>bootSE</code> provides us the bootstrap standard error, or bootstrap SE in short. We can use this to answer the key question of how accurate our estimate is.</li>
<li>5: Compute confidence intervals. Use your preferred confidence level (usually, and by default, 95%)</li>
<li>6: Provide interpretation in the context of your research question and report results in APA format.</li>
</ul>
<div class="blue">
<p>In <strong>R</strong>, for example:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r"><code class="sourceCode R"><span><span class="va">mymodel</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x1</span> <span class="op">+</span> <span class="va">x2</span>, data <span class="op">=</span> <span class="va">mydata</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">car</a></span><span class="op">)</span></span>
<span><span class="va">bootmymodel</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/Boot.html">Boot</a></span><span class="op">(</span><span class="va">mymodel</span>, R <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>See Week 5 <a href="https://uoepsy.github.io/dapr2/2223/lectures/dapr2_15_BootstrapLM">lectures</a> for further details, examples, and to revise these concepts further.</p>
</div>
</div>
</div>
<p class="optional-end">
</p>


</section><div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1" role="doc-endnote"><p>what defines a ‘family’ of tests is debatable.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
      <div class="nav-footer-center">© Copyright 2019-2022 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
  </div>
</footer>


</body></html>