---
title: "Specifying hypotheses"
params: 
    TOGGLE: TRUE
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```


We need to specify our hypotheses when testing a model as this not only defines what we are testing, but also sets the direction for statistical inference. By specifying a null hypothesis (typically stating no effect or no association) and an alternative hypothesis (indicating the presence of an association), we create a structured approach for determining the statistical significance of model parameters. Without specifying hypotheses, the interpretation of results would lack focus, making it difficult to assess the validity and relevance of the model's findings.

In regression analysis, hypothesis testing for beta coefficients is used to assess whether (each) predictor variable significantly contributes to the model. 

The way we specify hypotheses is similar across simple and multiple regression models.

For each regression coefficient $\beta_j$ (for predictor $X_j$):

+ Null hypothesis ($H_0$) = $\beta_j = 0$: The predictor variable ($X_j$) is not associated with the DV  
+ Alternative hypothesis ($H_1$) = $\beta_j \neq 0$: The predictor variable ($X_j$) is associated with the DV  
  
  
Based on the $p$-value or comparison of the $t$-statistic with the critical value, you can conclude whether the predictor variable is significant or not (see the simple & multiple regression Models - extracting information > model coefficients flashcard below):

+ Reject $H_0$ if $|t_j|$ > critical value or $p$-value $< \alpha$ 
+ Fail to reject $H_0$ if $|t_j|$ $\leq$ critical value or $p$-value $\geq \alpha$ 