---
title: "Marginal distributions vs. bivariate associations"
params: 
    TOGGLE: TRUE
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

<table cellspacing="3">
<tr style="border-bottom: 1px solid"><th></th><th style="border-right: 1px solid">Marginal Distributions</th><th>Bivariate Associations</th></tr>
<tr style="border-bottom: 1px solid">
<td style="vertical-align:top">**Description**</td>
<td style="vertical-align:top;border-right: 1px solid">The distribution of each variable individually (i.e., *without* reference to the values of the other variables).</td>
<td style="vertical-align:top">Describing the association between two numeric variables.</td>
</tr>
<tr style="border-bottom: 1px solid">
<td style="vertical-align:top">**Visually**</td>
<td style="vertical-align:top;border-right: 1px solid">Plot each variable individually.<br><br>You could use, for example, `geom_density()` for a density plot, `geom_boxplot()` for a boxplot or `geom_histogram()` for a histogram to comment on and/or examine:<br><ul><li> The *shape* of the distribution. Look at the shape, centre and spread of the distribution. Is it symmetric or skewed? Is it unimodal or bimodal? </li><li> Identify any *unusual observations*. Do you notice any extreme observations (i.e., outliers)? </li></ul></td>
<td style="vertical-align:top">Plot associations among two variables.<br><br>You could use, for example, `geom_point()` for a scatterplot  to comment on and/or examine:<br><ul><li>The *direction* of the association indicates whether there is a positive or negative association</li><li>The *form* of association refers to whether the relationship between the variables can be summarized well with a straight line or some more complicated pattern </li><li>The *strength* of association entails how closely the points fall to a recognizable pattern such as a line  </li><li>*Unusual observations* that do not fit the pattern of the rest of the observations and which are worth examining in more detail </li></ul></td>
</tr>
<tr style="border-bottom: 1px solid">
<td style="vertical-align:top">**Numerically**&nbsp;&nbsp;&nbsp;</td>
<td style="vertical-align:top;border-right: 1px solid">Compute and report summary statistics e.g., mean, standard deviation, median, min, max, etc.<br><br>You could, for example, calculate summary statistics such as the mean (`mean()`) and standard deviation (`sd()`), etc. within `summarize()`</td>
<td style="vertical-align:top">Compute and report the correlation coefficient.<br><br>You can use the `cor()` function to calculate this</td>
</tr>
</table>
