---
title: "Common terminology"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```


| Term           | Definition       |
|----------------|------------------|
| Observation, observational unit | The individual entities on which data are collected (often the rows in a data frame) |  
| Variable | Any characteristic recorded on the observational units (often the columns in a data frame) |  
| Numeric variable | A variable that records a numeric quantity for each case. For such variables standard arithmetic operations make sense. For example: height, IQ, and weight |  
| Categorical variable | A categorical variable places units into one of several groups. For example: country of birth, dominant hand, eye colour |  
| Binary variable | A special case of categorical variable with only two possible levels. For example: dominant hand (left or right), smoking status (smoker or non-smoker), answered question correctly (yes or no) |  
| Outcome variable, dependent variable (DV), response variable | Variable which measures the outcome of interest in a study |  
| Predictor, independent variable (IV), explanatory variable | Variable which is used to explain differences/changes in the response variable |  
| Observational study | An observational study is a study in which the researcher does not manipulate any of the variables involved in the study, but merely records the values as they naturally exist | 
| Experimental study | An experiment is a study in which the researcher imposes the values of the explanatory variable on the units before measuring the response variable |  
