---
title: "Binary outcomes"
params: 
    TOGGLE: TRUE
---

```{r setup, include=FALSE}
source('../assets/setup.R')
library(tidyverse)
library(sjPlot)
```

Binary outcomes are outcome variables with only two possible values, e.g.:

- Failure or success
- No or yes
- Fail or pass
- Employed or unemployed
- Depressed or not depressed

To represent the binary outcome numerically, we must represent one level as 0 and the other as 1.
**The level that we represent as 1 is the level that we want the logistic regression model to estimate the probability/log-odds of.**

For example:

- Failure or success
  - Failure = 0
  - Success = 1
  - The model will estimate the log-odds of success
  
- No or yes
  - No = 0
  - Yes = 1
  - The model will estimate the log-odds of a "Yes" response
  
- Fail or pass
  - Fail = 0
  - Pass = 1
  - The model will estimate the log-odds of a pass
  
- Employed or unemployed
  - Employed = 0
  - Unemployed = 1
  - The model will estimate the log-odds of being unemployed

- Depressed or not depressed
  - Depressed = 0
  - Not depressed = 1
  - The model will estimate the log-odds of not being depressed


Note: although both use 0s and 1s, binary outcomes are **not** the same thing as a treatment-coded predictor, and binary outcomes have no reference level.