---
title: "Link function"
params: 
    TOGGLE: TRUE
---

```{r setup, include=FALSE}
source('../assets/setup.R')
library(tidyverse)
library(sjPlot)
```


A "link function" is what generalised linear models (GLMs) use to transform some outcome variable that's not continuous numeric into a version that *is* continuous numeric, so that we can model it using a straight line.

In all the linear regression models we've seen in the first three blocks of DAPR2, we haven't needed to transform the outcomes at all.
You might see this written as "link function = identity".

**For logistic regression, the link function is the logit link, which transforms probabilities (bounded between 0 and 1) to log-odds (continuous numeric).**

For lots of examples, see the [Probabilities and log-odds](prob-logodds.html){target="_blank"} flash card.


::: {.callout-caution collapse="true"}
## Common GLM families and their link functions

- For modelling binary outcomes: **the binomial family and the logit link (logistic function) or the probit link (Gaussian function).**
- For modelling count outcomes (i.e., integers only, like number of panic attacks in a week): **the Poisson family with the log link.**
- For modelling positive-only numeric outcomes (e.g., reaction times): **the Gamma family with the inverse link.**

See `?glm` for other modelling options. 
See `?family` for other allowable link functions for each family.

:::
