---
title: "Assessing logistic regression model fit"
params: 
    TOGGLE: TRUE
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```


## Deviance

Deviance is a measure of deviation/discrepancy/mismatch between the data and the model. You can think of it as a generalisation of the terms making up the residual sum of squares in simple linear regression, in that it measures the misfit, or badness of fit.   

**Null Deviance**
  
+ The deviance of a model with no predictors, just the intercept  
+ It acts as a baseline, and measures how well the null model fits the data  

**Residual Deviance**
  
+ The deviance of the model with the predictors included  
+ Shows how well the model with those predictors fits the data compared to the null model  

**Interpretation**
  
+ By comparing the null deviance with the residual deviance, you can assess the improvement provided by the predictors  
+ Lower deviance values indicate a better fit. If you wanted to know whether the difference in deviance was *significantly* different, you would need to *statistically* compare your models (see [model comparisons - logistic models](https://uoepsy.github.io/dapr2/2526/labs/1_b4_reading.html#logistic-models-2)). 
