{
  "hash": "2fcf75bbd64f5010dc031b6a21cebe45",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Effect coding and manual post-hoc contrasts\"\nauthor: \"Elizabeth Pankratz (elizabeth.pankratz@ed.ac.uk)\"\neditor_options: \n  chunk_output_type: console\nformat:\n  revealjs:\n    smaller: true\n---\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n# Course Overview {.smaller}\n\n<br>\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n<table style=\"border: 1px solid black;>\n  <tr style=\"padding: 0 1em 0 1em;\">\n    <td rowspan=\"5\" style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1;text-align:center;vertical-align: middle\">\n        <b>Introduction to Linear Models</b></td>\n    <td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        Intro to Linear Regression</td>\n  </tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        Interpreting Linear Models</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        Testing Individual Predictors</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        Model Testing & Comparison</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        Linear Model Analysis</td></tr>\n\n  <tr style=\"padding: 0 1em 0 1em;\">\n    <td rowspan=\"5\" style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1;text-align:center;vertical-align: middle\">\n        <b>Analysing Experimental Studies</b></td>\n    <td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        Categorical Predictors & Dummy Coding</td>\n  </tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        <b>\tEffects Coding & Coding Specific Contrasts</b></td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Assumptions & Diagnostics</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Bootstrapping</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        \tCategorical Predictor Analysis</td></tr>\n</table>\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n<table style=\"border: 1px solid black;>\n  <tr style=\"padding: 0 1em 0 1em;\">\n    <td rowspan=\"5\" style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4;text-align:center;vertical-align: middle\">\n        <b>Interactions</b></td>\n    <td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Interactions I</td>\n  </tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Interactions II</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Interactions III</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Analysing Experiments</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Interaction Analysis</td></tr>\n\n  <tr style=\"padding: 0 1em 0 1em;\">\n    <td rowspan=\"5\" style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4;text-align:center;vertical-align: middle\">\n        <b>Advanced Topics</b></td>\n    <td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Power Analysis</td>\n  </tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Binary Logistic Regression I</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Binary Logistic Regression II</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Logistic Regression Analysis</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        \tExam Prep and Course Q&A</td></tr>\n</table>\n\n\n:::\n\n::::\n\n\n## {{< iconify icon-park-twotone brain >}} Retrieval practice: Coefficients and <br> null hypotheses (H0s) in dummy coding\n\n<br>\n\nAnswer the questions in this table as thoroughly as you can **FROM MEMORY,** without checking your notes from last week.\n\nIt's extremely OK and normal to not remember everything.\n\n\n|  | Intercept $\\beta_0$ |  | Slope $\\beta_j$ |  |\n|---|---|---|---|---|\n|  | **Meaning** | **H0** | **Meaning** | **H0** |\n| Dummy coding /<br> Treatment coding | *What does the intercept mean?* | *What null hypothesis is tested for the intercept?* | *What does a slope coefficient mean?* | *What hypothesis is tested for a slope coefficient?* |\n|  |  |  |  |  |\n<!-- | Dummy coding / Treatment coding | Mean outcome of reference level | Mean outcome of ref. level = 0 | Difference between non-ref. level and ref. level | This difference = 0 | -->\n<!-- | Effects coding / Sum to zero coding | Mean of all group means (aka grand mean) | Grand mean = 0 | Difference between grand mean and the mean of group j | Diff = 0 | -->\n\nOnce you've written down everything you can remember, look at your notes and fill in the gaps.\n\n<br>\n\n:::{.dapr2callout}\nTo practice retrieving information from memory is a good study strategy, according to [Brown et al. (2014)](https://www.hup.harvard.edu/file/feeds/PDF/9780674729018_sample.pdf).\nIf you test your memory first, and only afterward look up the information, you'll end up remembering the information much better than if you immediately look up the information without testing yourself first.\n:::\n\n\n\n## This week's learning objectives\n\n<br>\n\n\n::: {style=\"font-size: 125%;\"}\n\n<!-- ::: {.fragment} -->\n::: {.dapr2callout}\nDummy coding is one common scheme for *a priori* contrast coding. What's another common scheme, and how is it different?\n:::\n<!-- ::: -->\n\n<!-- ::: {.fragment} -->\n::: {.dapr2callout}\nWhen we code predictors using this other coding scheme, how do we interpret the linear model's coefficients?\n:::\n<!-- ::: -->\n\n<!-- ::: {.fragment} -->\n::: {.dapr2callout}\nIn this other coding scheme, what hypotheses are tested for each coefficient?\n:::\n<!-- ::: -->\n\n<!-- ::: {.fragment} -->\n::: {.dapr2callout}\nHow can we test hypotheses other than the ones tested by *a priori* coding schemes?\n:::\n<!-- ::: -->\n\n:::\n\n<!-- ======================================== -->\n\n\n\n\n\n\n## Coefficients and null hypotheses (H0s)\n\n\n|  | Intercept $\\beta_0$ |  | Slope $\\beta_j$ |  |\n|---|---|---|---|---|\n|  | **Meaning** | **H0** | **Meaning** | **H0** |\n| Dummy coding / <br> Treatment coding | Mean outcome of reference level | Mean outcome of ref. level = 0 | Difference between non-ref. level and ref. level | Difference between non-ref. level and ref. level = 0 |\n| Effect(s) coding / sum(-to-zero) coding |  |  |  |  |\n|  |  |  |  |  |\n\n<!-- | Effects coding / Sum to zero coding | Mean of all group means (aka grand mean) | Grand mean = 0 | Difference between grand mean and the mean of group j | Diff = 0 | -->\n\n\n# Effect coding\n\n\n## Another way of representing categorical predictors as numbers\n\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Dummy coding/treatment coding:**\n\n![](figs/TODO-trtmt.jpeg){fig-align=\"center\"}\n\nHere, `alone` is coded as 0, `others` is coded as 1.\n\n:::\n::: {.column width=\"50%\"}\n\n**Effect(s) coding / sum-to-zero coding:**\n\n![](figs/TODO-sum.jpeg){fig-align=\"center\"}\n\nHere, `alone` is coded as 1, `others` is coded as –1.\n\n:::\n::::\n\n## The data: Two study patterns\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_07_effects_manual_files/figure-revealjs/unnamed-chunk-4-1.svg){fig-align='center'}\n:::\n:::\n\n\n\n## Same data represented as different numbers\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\nDummy coding uses 0 and 1.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_07_effects_manual_files/figure-revealjs/plot xy study dummy-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n::: {.column width=\"50%\"}\n\nEffect coding uses 1 and –1.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_07_effects_manual_files/figure-revealjs/plot xy study effect-1.svg){fig-align='center'}\n:::\n:::\n\n\n\n:::\n::::\n:::{.dapr2callout}\n\n- In effect coding, what does the **intercept** represent?\n- In effect coding, what does the **slope** represent?\n\n:::\n\n**{{< iconify material-symbols person-rounded size=1em >}} Predict individually:**\nWrite down your guesses about each question.\n\n**{{< iconify material-symbols group-outline-rounded size=1em >}} Explain to a partner:**\nWhy do you think your guesses are likely to be correct?\n\n\n\n## Define effect coding in R\n\nR uses dummy coding by default.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(score_data$study)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       others\nalone       0\nothers      1\n```\n\n\n:::\n:::\n\n\n\n<br>\n\nTo make sure that our predictor is effect-coded, we use the function `contr.sum()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(score_data$study) <- contr.sum(2)  # 2 because there are 2 levels\ncontrasts(score_data$study)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       [,1]\nalone     1\nothers   -1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Model `score ~ study`\n\n$$\nscore_i = \\beta_0 + (\\beta_1 \\times study) + \\epsilon_i\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(score ~ study, data = score_data)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = score ~ study, data = score_data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-22.79  -4.79   0.21   5.48  18.21 \n\nCoefficients:\n            Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)   25.157      0.505   49.85   < 2e-16 ***\nstudy1        -2.367      0.505   -4.69 0.0000045 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.9 on 248 degrees of freedom\nMultiple R-squared:  0.0815,\tAdjusted R-squared:  0.0777 \nF-statistic:   22 on 1 and 248 DF,  p-value: 0.00000453\n```\n\n\n:::\n:::\n\n\n\n\n\n<br> \n\nDoes your guess about the **intercept** make sense, given the estimate of 25.157?\n\nDoes your guess about the **slope** make sense, given the estimate of -2.367?\n\n\n## What does each coefficient mean?\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_07_effects_manual_files/figure-revealjs/unnamed-chunk-10-1.svg){fig-align='center'}\n:::\n:::\n\n:::\n::: {.column width=\"50%\" style='font-size:85%;'}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value  Pr(>|t|)\n(Intercept)    25.16      0.505   49.85 3.12e-131\nstudy1         -2.37      0.505   -4.69  4.53e-06\n```\n\n\n:::\n:::\n\n\n:::\n::::\n\n\n## What does each coefficient mean?\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_07_effects_manual_files/figure-revealjs/unnamed-chunk-12-1.svg){fig-align='center'}\n:::\n:::\n\n:::\n::: {.column width=\"50%\" style='font-size:85%;'}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value  Pr(>|t|)\n(Intercept)    25.16      0.505   49.85 3.12e-131\nstudy1         -2.37      0.505   -4.69  4.53e-06\n```\n\n\n:::\n:::\n\n\n<br>\n\n:::\n::::\n\n\n\n## What does each coefficient mean?\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_07_effects_manual_files/figure-revealjs/unnamed-chunk-14-1.svg){fig-align='center'}\n:::\n:::\n\n:::\n::: {.column width=\"50%\" style='font-size:85%;'}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value  Pr(>|t|)\n(Intercept)    25.16      0.505   49.85 3.12e-131\nstudy1         -2.37      0.505   -4.69  4.53e-06\n```\n\n\n:::\n:::\n\n\n<br>\n\n**`(Intercept)` aka $\\beta_0$:**\n\n- 25.157 is the **grand mean**: the mean of the group means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m1_grand_mean <- mean(\n  c(mean_others, mean_alone))\n )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25.2\n```\n\n\n:::\n:::\n\n\n\n\n<br>\n\n**`study1` aka $\\beta_1$:**\n\n- -2.367 is the difference between the level coded as 1, `alone`, and the grand mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_alone - m1_grand_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2.37\n```\n\n\n:::\n:::\n\n\n\n:::\n::::\n\n\n**{{< iconify material-symbols person-rounded size=1.5em >}} Observe**: Did your guesses match the results?\n\n**{{< iconify material-symbols group-outline-rounded size=1.5em >}} Explain**: Why are the results the way they are?\n\n\n<!-- TODO: add beta annotations into overlays of this slide -->\n\n\n## Coefficients and null hypotheses (H0s)\n\n|  | Intercept $\\beta_0$ |  | Slope $\\beta_j$ |  |\n|---|---|---|---|---|\n|  | **Meaning** | **H0** | **Meaning** | **H0** |\n| Dummy coding / <br> Treatment coding | Mean outcome of reference level | Mean outcome of ref. level = 0 | Difference between non-ref. level and ref. level | Difference between non-ref. level and ref. level = 0 |\n| Effect(s) coding / sum(-to-zero) coding | Grand mean (mean of all group mean outcomes) |  | Difference between mean of level coded as 1 and grand mean |  |\n|  |  |  |  |  |\n\n<!-- | Effects coding / Sum to zero coding | Mean of all group means (aka grand mean) | Grand mean = 0 | Difference between grand mean and mean of level coded as 1 | Diff = 0 | -->\n\n\n\n## What hypotheses does effect coding test?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value  Pr(>|t|)    \n (Intercept)   25.157      0.505   49.85   < 2e-16 ***\n study1        -2.367      0.505   -4.69 0.0000045 ***\n```\n\n\n:::\n:::\n\n\n\n<br>\n\n**`(Intercept)` aka $\\beta_0$:**\n\n- Null hypothesis: The grand mean is equal to zero.\n- $p$-value: the probability of observing a grand mean of 25.157, assuming that the true grand mean is zero.\n\n\n**`study1` aka $\\beta_1$:**\n\n- Null hypothesis: The difference between the mean score of `alone` and the grand mean is equal to zero.\n- $p$-value: the probability of observing a difference of -2.367, assuming that the true difference is zero.\n\n\n**Can we reject each of these null hypotheses?** {{< iconify codicon thumbsup-filled size=1em >}} {{< iconify codicon thumbsdown-filled size=1em >}}\n\n\n## Coefficients and null hypotheses (H0s)\n\n|  | Intercept $\\beta_0$ |  | Slope $\\beta_j$ |  |\n|---|---|---|---|---|\n|  | **Meaning** | **H0** | **Meaning** | **H0** |\n| Dummy coding / <br> Treatment coding | Mean outcome of reference level | Mean outcome of ref. level = 0 | Difference between non-ref. level and ref. level | Difference between non-ref. level and ref. level = 0 |\n| Effect(s) coding / sum(-to-zero) coding | Grand mean (mean of all group mean outcomes) | Grand mean = 0 | Difference between  mean of level coded as 1 and grand mean | Difference between mean of level coded as 1 and grand mean = 0 |\n|  |  |  |  |  |\n\n\n\n<!-- ======================================== -->\n\n# Effect coding for >2 levels\n\n## The data: Three study methods\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_07_effects_manual_files/figure-revealjs/unnamed-chunk-19-1.svg){fig-align='center'}\n:::\n:::\n\n\n\n## {{< iconify icon-park-outline muscle >}} Challenge: Guess the coefficient values\n\n:::{.dapr2callout}\nIn effect coding:\n\n- Intercept = Grand mean (mean of all group mean outcomes)\n- Slope = Difference between  mean of level coded as 1 and grand mean (i.e., group mean – grand mean) \n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n:::{.dapr2callout}\nMean of `read` group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_read\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23.4\n```\n\n\n:::\n:::\n\n\n\nMean of `self-test` group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_self\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27.6\n```\n\n\n:::\n:::\n\n\n\nMean of `summarise` group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_summ\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.2\n```\n\n\n:::\n:::\n\n:::\n:::\n::: {.column width=\"70%\"}\n\n:::{.dapr2callout}\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(score_data$method) <- contr.sum(3)\ncontrasts(score_data$method)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1] [,2]\nread         1    0\nself-test    0    1\nsummarise   -1   -1\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.dapr2callout style=\"background: #FDEDEF;\"}\n**Imagine fitting a model `score ~ method`. This slide has all the information you need to guess the coefficient values.**\n\n- What's the value of the intercept?\n- There'll be a predictor called `method1`. What is its value?\n- There'll also be a predictor called `method2`. What is its value?\n:::\n:::\n::::\n\n## {{< iconify icon-park-outline muscle >}} Challenge: Guess the coefficient values\n\n:::{.dapr2callout}\nIn effect coding:\n\n- Intercept = Grand mean (mean of all group mean outcomes)\n- Slope = Difference between  mean of level coded as 1 and grand mean (i.e., group mean – grand mean) \n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n:::{.dapr2callout}\nMean of `read` group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_read\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23.4\n```\n\n\n:::\n:::\n\n\n\nMean of `self-test` group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_self\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27.6\n```\n\n\n:::\n:::\n\n\n\nMean of `summarise` group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_summ\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.2\n```\n\n\n:::\n:::\n\n:::\n:::\n::: {.column width=\"70%\"}\n\n:::{.dapr2callout}\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(score_data$method) <- contr.sum(3)\ncontrasts(score_data$method)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1] [,2]\nread         1    0\nself-test    0    1\nsummarise   -1   -1\n```\n\n\n:::\n:::\n\n\n:::\n\n\n::: {.dapr2callout style=\"background: #FDEDEF;\"}\n- Intercept: grand mean, so\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m2_grand_mean <- (mean_read + mean_self + mean_summ)/3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25.1\n```\n\n\n:::\n:::\n\n\n- `method1`: in first column of contrast matrix, `read` = 1, so\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_read - m2_grand_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.65\n```\n\n\n:::\n:::\n\n\n\n- `method2`: in second column of contrast matrix, `self-test` = 1, so\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_self - m2_grand_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.51\n```\n\n\n:::\n:::\n\n\n:::\n:::\n::::\n\n\n## Model `score ~ method`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- lm(score ~ method, data = score_data)\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = score ~ method, data = score_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-23.414  -5.359  -0.196   5.750  17.804 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   25.062      0.518   48.41   <2e-16 ***\nmethod1       -1.648      0.720   -2.29   0.0229 *  \nmethod2        2.514      0.773    3.25   0.0013 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.08 on 247 degrees of freedom\nMultiple R-squared:  0.0422,\tAdjusted R-squared:  0.0345 \nF-statistic: 5.45 on 2 and 247 DF,  p-value: 0.00484\n```\n\n\n:::\n:::\n\n\n\n\n\n## What hypotheses are being tested?\n\n|  | Intercept $\\beta_0$ |  | Slope $\\beta_j$ |  |\n|---|---|---|---|---|\n|  | **Meaning** | **H0** | **Meaning** | **H0** |\n| Dummy coding / <br> Treatment coding | Mean outcome of reference level | Mean outcome of ref. level = 0 | Difference between non-ref. level and ref. level | Difference between non-ref. level and ref. level = 0 |\n| Effect(s) coding / sum(-to-zero) coding | Grand mean (mean of all group mean outcomes) | Grand mean = 0 | Difference between  mean of level coded as 1 and grand mean | Difference between mean of level coded as 1 and grand mean = 0 |\n|  |  |  |  |  |\n\n<br>\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value Pr(>|t|)    \n (Intercept)   25.062      0.518   48.41   <2e-16 ***\n method1       -1.648      0.720   -2.29   0.0229 *  \n method2        2.514      0.773    3.25   0.0013 ** \n```\n\n\n:::\n:::\n\n\n<br>\n\n**Can we reject each of these null hypotheses?**\n\n\n<!-- ======================================== -->\n\n# Creating your own post-hoc contrasts\n\n\n## Terminology: *A priori* contrasts? Post-hoc contrasts?\n\n\n:::: {.columns}\n::: {.column width=\"45%\"}\n\n***A priori* contrasts** are chosen *prior* to (before) fitting the model.\n\nEvery categorical variable must be coded with some kind of *a priori* contrast.\n\nYour toolkit now includes:\n\n1. **dummy coding** = treatment coding\n2. **effect coding** = effects coding = sum-to-zero coding = sum coding \n\n:::\n::: {.column width=\"10%\"}\n:::\n::: {.column width=\"45%\"}\n\n**Post-hoc contrasts** are tested *post* (after) fitting the model.\n\nWe can optionally use estimated marginal means to test hypotheses beyond the ones from our *a priori* contrasts.\n\nWe tested our first post-hoc contrasts last week, when we looked at the difference between the two non-reference levels of `method`.\n\n**This session, we'll learn how to define any contrasts we want.**\n\n:::\n::::\n\n\n\n## The data: Subjective well-being and partnership\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_07_effects_manual_files/figure-revealjs/unnamed-chunk-34-1.svg){fig-align='center'}\n:::\n:::\n\n\n\n\n## Research questions\n\n<br>\n\n\n1. **Is there a difference in subjective well-being between (1) people who are currently married or in a civil partnership and (2) people who were previously married or in a civil partnership?**\n\n$\\rightarrow$ We'll create the contrasts to address this question together.\n\n<br>\n\n\n2. **Is there a difference in subjective well-being between (1) people who are currently OR were previously married or in a civil partnership and (2) people who were never married or in a civil partnership?**\n\n$\\rightarrow$ You'll create the contrasts for this question in pairs/small groups.\n\n\n## Fit model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- lm(swb ~ status, wb_data)\nsummary(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = swb ~ status, data = wb_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-11.337  -2.078  -0.002   2.053  11.473 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        11.438      0.333   34.35  < 2e-16 ***\nstatusDivorced     -2.064      0.577   -3.58  0.00038 ***\nstatusMarried/CP   -0.812      0.389   -2.09  0.03721 *  \nstatusSingle       -3.377      0.577   -5.86  8.7e-09 ***\nstatusWidowed      -5.433      0.745   -7.30  1.2e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.33 on 495 degrees of freedom\nMultiple R-squared:  0.142,\tAdjusted R-squared:  0.135 \nF-statistic: 20.4 on 4 and 495 DF,  p-value: 1.38e-15\n```\n\n\n:::\n:::\n\n\n<br>\n\n**These contrasts don't address our research questions!**\n\n\n## Defining manual contrasts step by step\n\n**Is there a difference in subjective well-being between (1) people who are currently married or in a civil partnership and (2) people who were previously married or in a civil partnership?**\n\n:::: {.columns}\n::: {.column width=\"30%\"}\n:::{.hcenter}\n\n| `group`      | `current` |\n| ------------ | --------- |\n| `Cohab`      |           |\n| `Divorced`   |           |\n| `Married/CP` |           |\n| `Single`     |           |\n| `Widowed`    |           |\n|||\n\n:::\n:::\n::: {.column width=\"70%\"}\n\n:::{.dapr2callout}\n**Step 1:** \"Chunk\" together the two group(s) that the research question is comparing.\n\n- Chunk 1: People who are currently married or in a civil partnership: `Married/CP`.\n- Chunk 2: People who were previously married or in a civil partnership: `Divorced`, `Widowed`.\n:::\n\n:::\n::::\n\n## Defining manual contrasts step by step\n\n**Is there a difference in subjective well-being between (1) people who are currently married or in a civil partnership and (2) people who were previously married or in a civil partnership?**\n\n:::: {.columns}\n::: {.column width=\"30%\"}\n:::{.hcenter}\n\n| `group`      | `current` |\n| ------------ | --------- |\n| `Cohab`      | 0         |\n| `Divorced`   |           |\n| `Married/CP` |           |\n| `Single`     | 0         |\n| `Widowed`    |           |\n|||\n\n:::\n:::\n::: {.column width=\"70%\"}\n\n:::{.dapr2callout}\n**Step 1:** \"Chunk\" together the two group(s) that the research question is comparing.\n\n- Chunk 1: People who are currently married or in a civil partnership: `Married/CP`.\n- Chunk 2: People who were previously married or in a civil partnership: `Divorced`, `Widowed`.\n:::\n\n:::{.dapr2callout}\n**Step 2:** Assign a 0 to any group(s) that aren't in one of the chunks from Step 1.\n\n- `Cohab`, `Single`\n:::\n\n:::\n::::\n\n\n## Defining manual contrasts step by step\n\n**Is there a difference in subjective well-being between (1) people who are currently married or in a civil partnership and (2) people who were previously married or in a civil partnership?**\n\n:::: {.columns}\n::: {.column width=\"30%\"}\n:::{.hcenter}\n\n| `group`      | `current` |\n| ------------ | --------- |\n| `Cohab`      | 0         |\n| `Divorced`   | –         |\n| `Married/CP` | +         |\n| `Single`     | 0         |\n| `Widowed`    | –         |\n|||\n\n:::\n:::\n::: {.column width=\"70%\"}\n\n\n:::{.dapr2callout}\n**Step 1:** \"Chunk\" together the two group(s) that the research question is comparing.\n\n- Chunk 1: People who are currently married or in a civil partnership: `Married/CP`.\n- Chunk 2: People who were previously married or in a civil partnership: `Divorced`, `Widowed`.\n:::\n\n\n:::{.dapr2callout}\n**Step 2:** Assign a 0 to any group(s) that aren't in one of the chunks from Step 1.\n\n- `Cohab`, `Single`\n:::\n\n\n:::{.dapr2callout}\n**Step 3:** Assign a plus sign to every group in Chunk 1, and a minus sign to every group in Chunk 2.\n:::\n\n\n:::\n::::\n\n\n\n## Defining manual contrasts step by step\n\n**Is there a difference in subjective well-being between (1) people who are currently married or in a civil partnership and (2) people who were previously married or in a civil partnership?**\n\n:::: {.columns}\n::: {.column width=\"30%\"}\n:::{.hcenter}\n\n| `group`      | `current` |\n| ------------ | --------- |\n| `Cohab`      | 0         |\n| `Divorced`   | –         |\n| `Married/CP` | +         |\n| `Single`     | 0         |\n| `Widowed`    | –         |\n|||\n\n:::\n:::\n::: {.column width=\"70%\"}\n\n:::{.dapr2callout}\n**Step 4:** Count the plus signs and minus signs.\n\n- Plus: $n_{plus}$ = 1\n- Minus: $n_{minus}$ = 2\n:::\n\n:::{.dapr2callout .fragment}\n**Step 5:** To figure out the actual values for each cell, start with 1 and –1.\nDivide 1 by $n_{plus}$, and divide –1 by $n_{minus}$.\n\n- Plus: 1 divided by 1 = 1\n- Minus: –1 divided by 2 = –1/2\n:::\n\n:::\n::::\n\n\n\n## Defining manual contrasts step by step\n\n**Is there a difference in subjective well-being between (1) people who are currently married or in a civil partnership and (2) people who were previously married or in a civil partnership?**\n\n:::: {.columns}\n::: {.column width=\"30%\"}\n:::{.hcenter}\n\n| `group`      | `current` |\n| ------------ | --------- |\n| `Cohab`      | 0         |\n| `Divorced`   | –1/2      |\n| `Married/CP` | 1         |\n| `Single`     | 0         |\n| `Widowed`    | –1/2      |\n|||\n\n:::\n:::\n::: {.column width=\"70%\"}\n\n:::{.dapr2callout}\n**Step 4:** Count the plus signs and minus signs.\n\n- Plus: $n_{plus}$ = 1\n- Minus: $n_{minus}$ = 2\n:::\n\n:::{.dapr2callout}\n**Step 5:** To figure out the actual values for each cell, start with 1 and –1.\nDivide 1 by $n_{plus}$, and divide –1 by $n_{minus}$.\n\n- Plus: 1 divided by 1 = 1\n- Minus: –1 divided by 2 = –1/2\n:::\n\n:::{.dapr2callout}\n**Step 6:** In the coding matrix, replace the plus signs with the positive coding value from Step 5, and replace the minus signs with the negative coding value from Step 5. **Done!**\n:::\n\n:::\n::::\n\n\n## Manual contrasts FAQ\n\n- **Can I compare more than two chunks in a single contrast?** No. This is because we're dealing with the slope of lines between two groups. If you want to compare more than two things, then you need more than one contrast.\n\n- **How many contrasts can I have?** If you have $k$ groups, you can have up to $k-1$ contrasts. So since we have five groups, we can have up to four contrasts.\n\n- **Can I use the exact same chunk in more than one contrast?** No. Using the exact same chunk in more than one contrast is the categorical predictor equivalent of collinearity/non-independence of predictors.\n\n\n\n## `emmeans` and manual contrasts in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3_emm <- emmeans(m3, ~status)\n```\n:::\n\n\nLike we saw last time, we can use `emmeans`' `contrast()` function to test our manual contrasts.\n\nFirst, verify the order of levels with `levels()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(wb_data$status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Cohab\"      \"Divorced\"   \"Married/CP\" \"Single\"     \"Widowed\"   \n```\n\n\n:::\n:::\n\n\n<br>\n\n:::: {.columns}\n::: {.column width=\"30%\"}\n:::{.hcenter}\n\n| `group`      | `current` |\n| ------------ | --------- |\n| `Cohab`      | 0         |\n| `Divorced`   | –1/2      |\n| `Married/CP` | 1         |\n| `Single`     | 0         |\n| `Widowed`    | –1/2      |\n|||\n\n:::\n:::\n::: {.column width=\"70%\"}\n\n\nThen make sure the order of coding values matches the order of levels from `levels()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3_comparison1 <- list(\n  \"current\" = c(\n    0,     # Cohab\n    -1/2,  # Divorced\n    1,     # Married/CP \n    0,     # Single\n    -1/2   # Widowed\n  )\n)\n```\n:::\n\n\n\n:::\n::::\n\n\n## Testing manual contrasts\n\nTest the contrast (i.e., test the H0 that the estimate is different from 0):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m3_contrast1 <- contrast(m3_emm, m3_comparison1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast estimate    SE  df t.ratio p.value\n current      2.94 0.455 495   6.460  <.0001\n```\n\n\n:::\n:::\n\n\n<br>\n\nGet the associated 95% CIs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m3_confint1 <- confint(m3_contrast1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast estimate    SE  df lower.CL upper.CL\n current      2.94 0.455 495     2.04     3.83\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n<br>\n\nWhere does this number for `estimate` come from?\n\nIt's the grand mean of the positive chunk, minus the grand mean of the negative chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_married - mean(c(mean_divorced, mean_widowed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.94\n```\n\n\n:::\n:::\n\n\n<br>\n\n**Can we reject the null hypothesis that there's no difference in subjective well-being between people who are currently married and people who were previously married?**\n\n\n\n## {{< iconify material-symbols group-outline-rounded >}} Your turn: Research question 2\n\n**Is there a difference in subjective well-being between (1) people who are currently OR were previously married or in a civil partnership and (2) people who were never married or in a civil partnership?**\n\n:::: {.columns}\n::: {.column width=\"35%\"}\n:::{.hcenter}\n\n| `group`      | `evermarried` |\n| ------------ | ------------- |\n| `Cohab`      |               |\n| `Divorced`   |               |\n| `Married/CP` |               |\n| `Single`     |               |\n| `Widowed`    |               |\n|||\n\n:::\n:::\n::: {.column width=\"65%\"}\n\n:::{.dapr2callout}\n**Step 1:** \"Chunk\" together the two group(s) that the research question is comparing.\n\n- Chunk 1: `Divorced`, `Married/CP`, `Widowed`.\n- Chunk 2: `Cohab`, `Single`.\n:::\n\n:::{.dapr2callout}\n**Step 2:** Assign a 0 to any group(s) that aren't in one of the chunks from Step 1.\n:::\n\n\n:::{.dapr2callout}\n**Step 3:** Assign a plus sign to every group in Chunk 1, and a minus sign to every group in Chunk 2.\n:::\n\n:::{.dapr2callout}\n**Step 4:** Count the plus signs and minus signs.\n:::\n\n:::{.dapr2callout}\n**Step 5:** To figure out the actual values for each cell, start with 1 and –1.\nDivide 1 by $n_{plus}$, and divide –1 by $n_{minus}$.\n:::\n\n:::{.dapr2callout}\n**Step 6:** In the coding matrix, replace the plus signs with the positive coding value from Step 5, and replace the minus signs with the negative coding value from Step 5. **Done!**\n:::\n\n:::\n\n::::\n\n## If you finish early\n\n- Can you work out what `emmeans`' estimate for the `evermarried` coefficient will be?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## Switch to R ...\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(wb_data$status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Cohab\"      \"Divorced\"   \"Married/CP\" \"Single\"     \"Widowed\"   \n```\n\n\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3_comparison2 <- list(\n  \"evermarried\" = c(\n    ?,  # Cohab\n    ?,  # Divorced\n    ?,  # Married/CP \n    ?,  # Single\n    ?   # Widowed\n  )\n)\n```\n:::\n\n\n<!-- - let someone come up to the computer and type in what they've got? -->\n<!-- - run analysis live? that's kinda fun -->\n\n## The results we should expect\n\n\n\n\n\n\nTest the contrast (i.e., test the H0 that the estimate is different from 0):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m3_contrast2 <- contrast(m3_emm, m3_comparison2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    estimate    SE  df t.ratio p.value\n evermarried    -1.08 0.402 495  -2.690  0.0074\n```\n\n\n:::\n:::\n\n\n<br>\n\nGet the associated 95% CIs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m3_confint2 <- confint(m3_contrast2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    estimate    SE  df lower.CL upper.CL\n evermarried    -1.08 0.402 495    -1.87   -0.291\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n<br>\n\nThe `estimate` is the grand mean of the positive chunk, minus the grand mean of the negative chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npos_chunk_mean <- mean(c( mean_divorced, mean_married, mean_widowed ))\nneg_chunk_mean <- mean(c( mean_cohab, mean_single ))\n\npos_chunk_mean - neg_chunk_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.08\n```\n\n\n:::\n:::\n\n\n\n\n\n<!-- ======================================== -->\n\n## Building an analysis workflow\n\n<br> \n\n::: {.r-stack}\n![](figs/block2-flowchart-07-0.svg){.fragment height=\"550\" }\n\n![](figs/block2-flowchart-07-1.svg){.fragment height=\"550\" }\n\n:::\n\n\n\n\n\n## Revisiting this week's learning objectives\n\n::: {style=\"font-size: 125%;\"}\n\n:::{}\n::: {.dapr2callout}\n**Dummy coding is one common scheme for *a priori* contrast coding. What's another common scheme, and how is it different?**\n\n::: {style=\"font-size: 80%;\"}\n- Effects coding, also called sum-to-zero coding (or just \"sum coding\").\n- Dummy coding uses 0/1, and one level of the predictor (the one coded as 0) is the reference level.\n- Effects coding uses –1/1, and there is no reference level.\n:::\n\n:::\n:::\n\n::: {}\n::: {.dapr2callout}\n**When we code predictors using this other coding scheme, how do we interpret the linear model's coefficients?**\n\n::: {style=\"font-size: 80%;\"}\n- Intercept (also written as $\\beta_0$): The grand mean of the outcome (grand mean = the mean of every group's mean).\n- Slope (also written as $\\beta_1$, $\\beta_2$, etc., or for short, $\\beta_j$): The difference between (1) the mean of a group and (2) the grand mean, when all other predictors are at zero.\n:::\n\n:::\n:::\n\n:::\n\n## Revisiting this week's learning objectives\n\n\n::: {style=\"font-size: 125%;\"}\n\n::: {}\n::: {.dapr2callout}\n**In this other coding scheme, what hypotheses are tested for each coefficient?**\n\n::: {style=\"font-size: 80%;\"}\n- The intercept's hypothesis test: The grand mean of the outcome is different from zero.\n- The slopes' hypothesis tests: The difference between (1) the mean of each individual group and (2) the grand mean is different from zero.\n:::\n\n:::\n:::\n\n::: {}\n::: {.dapr2callout}\n**How can we test hypotheses other than the ones tested by *a priori* coding schemes?**\n\n::: {style=\"font-size: 80%;\"}\n- Use a linear model to generate the expected outcome values for every level of our predictors (= the expected marginal means).\n- We can compare expected marginal means of any combination of groups we want by manually creating our own contrasts.\n- There is a step-by-step process we can follow to create any contrasts we want.\n:::\n\n:::\n:::\n\n:::\n\n\n\n\n## This week {}\n\n<br>\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n### Tasks\n\n<br>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figs/labs.svg){width=15%}\n:::\n:::\n\n\n**Attend your lab and work together on the exercises** \n\n:::\n::: {.column width=\"50%\"}\n\n### Support\n\n<br>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figs/forum.svg){width=15%}\n:::\n:::\n\n\n**Help each other on the Piazza forum**\n\n:::\n::::\n\n<br>\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figs/exam.svg){width=15%}\n:::\n:::\n\n\n**Complete the weekly quiz**\n\n:::\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figs/oh.png){width=15%}\n:::\n:::\n\n\n**Attend office hours (see Learn page for details)**\n\n:::\n::::\n\n\n# Appendix {.appendix}\n\n## Solution to manual contrast exercise\n\n<br>\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n| `group`      | `evermarried` |\n| ------------ | ------------- |\n| `Cohab`      | –1/2          |\n| `Divorced`   |  1/3          |\n| `Married/CP` |  1/3          |\n| `Single`     | –1/2          |\n| `Widowed`    |  1/3          |\n|||\n:::\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nm3_comparison2 <- list(\n  \"evermarried\" = c(\n    -1/2,  # Cohab\n     1/3,  # Divorced\n     1/3,  # Married/CP \n    -1/2,  # Single\n     1/3   # Widowed\n  )\n)\n```\n:::\n\n:::\n::::\n\n\n\n\n\n\n## Grand mean vs. overall mean of the data\n\nThe grand mean is the mean of the group means.\n\n**The grand mean is sometimes, but not always, the overall mean of the observed data.**\n\n- When the groups are all exactly the same size, then the grand mean = the overall mean of observed data.\n- But when the groups are different sizes (like with the subjective well-being data), then the grand mean $\\neq$ the overall mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_data |>\n  group_by(status) |>\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n# Groups:   status [5]\n  status         n\n  <fct>      <int>\n1 Cohab        100\n2 Divorced      50\n3 Married/CP   275\n4 Single        50\n5 Widowed       25\n```\n\n\n:::\n:::\n\n\n<br>\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nThe mean of all `swb` values (*not* the grand mean):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_data$swb |> mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.2\n```\n\n\n:::\n:::\n\n\n:::\n::: {.column width=\"50%\"}\n\nThe grand mean (*not* the mean of all `swb` values):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(c(mean_cohab, mean_divorced, mean_married, mean_single, mean_widowed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.1\n```\n\n\n:::\n:::\n\n:::\n::::\n\n\n\n\n\n\n## Visualise effect coding with >2 levels\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(score_data$method)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1] [,2]\nread         1    0\nself-test    0    1\nsummarise   -1   -1\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_07_effects_manual_files/figure-revealjs/unnamed-chunk-58-1.svg)\n:::\n:::\n\n\nThe $\\times$ shows the grand mean = the model's intercept.\n\n**Once effect coding uses >2 levels, the line between group means does not give us the correct intercept or slope.**\n\n<!-- :::: {.columns} -->\n<!-- ::: {.column width=\"50%\"} -->\n<!-- a -->\n<!-- ::: -->\n<!-- ::: {.column width=\"50%\"} -->\n<!-- b -->\n<!-- ::: -->\n<!-- :::: -->\n\n<!-- style=\"font-size: 70%;\" -->",
    "supporting": [
      "dapr2_07_effects_manual_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}