---
title: "Categorical predictors: Study brief"
author: "Emma Waterston, Elizabeth Pankratz"
format: 
  html:
    toc: true
    number_sections: false
    toc-location: left
editor_options: 
  chunk_output_type: console
---


## Research question

RQ: Do people with greater conscientiousness and more advanced years of study attend university courses more?


## Study background

The data are available at: <https://uoepsy.github.io/data/DapR2_S1B2_PracticalPart1.csv>

The data used for this write-up exercise are simulated, drawing on a meta-analysis that explores the association between student characteristics and grades.
The simulated data are loosely based on the findings of this work, and they expand on the methods and results reported in the paper:

Credé, M., Roch, S. G., & Kieszczynka, U. M. (2010). Class attendance in college: A meta-analytic review of the relationship of class attendance with grades and student characteristics. *Review of Educational Research, 80*(2), 272-295. [https://doi.org/10.3102/0034654310362998](https://doi.org/10.3102/0034654310362998)

*NOTE: You are not expected to write an introduction, so you do not have to read this article.*


## Study procedure

Researchers were interested in what might predict attendance in university courses.
They collected information from 397 students across all years of study (`Year`; i.e., UG (Y1–Y4), MSc, and PhD), and recorded their class attendance across the academic year (`Attendance`), their level of Conscientiousness (`Conscientiousness` categorized as Low, Moderate, or High), the frequency of which they accessed online course materials (`OnlineAccess` categorized as Rarely, Sometimes, or Often), and the timing of class (`Time` categorized as 9AM, 10AM, 11AM, 12PM 1PM, 2PM, 3PM, 4PM).


## Data dictionary

The data in `DapR2_S1B2_PracticalPart1.csv` contain six attributes collected from a simulated sample of $n=397$ hypothetical individuals.
It includes: 

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
data1 <- read_csv("https://uoepsy.github.io/data/DapR2_S1B2_PracticalPart1.csv")
tibble(
Variable = names(data1),
Description = c("Participant ID number", "Total attendance (in days)", "Conscientiousness (Levels: Low, Moderate, High)", "Time of class (Levels: 9AM, 10AM, 11AM, 12PM, 1PM, 2PM, 3PM, 4PM)", "Frequency of access to online course materials (Levels: Rarely, Sometimes, Often)", "Year of study in university (Levels: Y1, Y2, Y3, Y4, MSc, PhD)")
) %>% gt::gt()
```
 