project:
  render: 
    - "*.qmd"
    - "!todo/*"
  ## change to the appropriate place in main repo/docs/
  # output-dir: ../../docs/2526/lectures/
  output-dir: ./wipdocs/

subtitle: "<br>Data Analysis for Psychology in R 2"
author: "DAPR2 Team"  # the default if lecturer doesn't include own name in YAML header
institute: "<br>Department of Psychology<br>University of Edinburgh<br>2025–2026"
format:
  revealjs:
    theme: [default, _theme/mystyle.scss]
    width: 1294
    height: 1000
    slide-number: true
    preview-links: auto
    include-after-body: _theme/clean_title_page.html
    callout-appearance: simple
    code-line-numbers: false
    code-overflow: wrap
    code-annotations: hover
    code-copy: hover
    classoption: fleqn
    chalkboard: true
revealjs-plugins:
  - attribution
filters: 
  - "_theme/inverse_part.lua"  # comment in for inverted-colour section header slides
  - line-highlight
highlight-style: breeze
title-slide-attributes:
  data-background-color: "#BF1932"
execute:
  warning: false
  echo: true
  message: false
  fig-format: svg
include-in-header: _theme/highlighter.js
