---
title: 'dapR2 (week 13 Lect2): Activity2'
author: "Department of Psychology<br>University of Edinburgh"
date: "AY 2020-2021"
output:
  html_document:
    theme: flatly
---

# Question 1

Install the **emmeans** package. Download the hospital.csv data (if you haven't already). Run the analyses that we did in the lecture using dummy coding and effects coding. Look at a summary of the output of the dummy code model. Check all the betas and use them to fill in the group means and marginal of the design matrix. This exercise will help you a great deal in understanding what the betas correspond to in a dummy coded model. 
  
Remember, you can find the data at https://uoepsy.github.io/data/hospital.csv  
<br>
<br>

---  

*Scroll down for answers*  
  
---

<div style="margin-bottom:750px;">

</div>




# Answers

In the dummy code model, the intercept is the mean of treatA in hosp1. You can fill out that cell of the design matrix directly. You can fill in the mean of treatB in hosp1 by adding beta1 to beta0. You can fill in the mean of treatC in hosp1 by adding beta2 and beta0. You can fill in the mean of treatA in hosp2 by adding beta3 and beta0. If you add beta4 to beta1 you have the difference between A and B in hosp2. Add (beta4+beta1) to the mean of treatA in hosp2 to get mean of treatB in hosp2. If you add beta5 to beta1 you have the difference between A and C in hosp2. Add (beta5+beta1) to the mean of treatA in hosp2 to get mean of treatC in hosp2. 



