---
title: "<b>Week 10: Evaluating Papers & Writing Up </b>"
subtitle: "Data Analysis for Psychology in R 2<br><br> "
author: "TOM BOOTH"
institute: "Department of Psychology<br>The University of Edinburgh"
date: "AY 2020-2021"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
style_mono_accent(
  #base_color = "#0F4C81", # DAPR1
   base_color = "#BF1932", # DAPR2
  # base_color = "#88B04B", # DAPR3 
  # base_color = "#FCBB06", # USMR
  # base_color = "#a41ae4", # MSMR
  header_color = "#000000",
  header_font_google = google_font("Source Sans Pro"),
  header_font_weight = 400,
  text_font_google = google_font("Source Sans Pro", "400", "400i", "600", "600i"),
  code_font_google = google_font("Source Code Pro")
)
```

---
# Weeks Learning Objectives
1. Construct a linear model from information in published paper. 
2. Evaluate a published analysis with respect to the thoroughness of information presented. 
3. Write-up  and provide interpretation of a linear model analysis with multiple predictors.

---
# Topics for today


---
# Summary of today


---
# Next tasks

