---
title: "Week 11: Practical Example"
author: "Monica Truelove-Hill"
date: "2023-11-14"
output: html_document
---

# Overview of the Week

This week, we'll be reviewing what we've learned in weeks 7-10 and applying it to a practical example. 


Our example is based on the paper *** CHANGE ALL OF THIS **** [Individual differences in Fear of Missing Out (FoMO): Age, and the Big Five personality trait domains, facets, and items](https://www.sciencedirect.com/science/article/pii/S0191886920307376#ec0005). This paper looks at how fear of missing out (FOMO) is related to the Big Five personality traits, age, and gender. Although the data we will be using in these analysis are simulated, they are based on the data found in the paper. Because we haven't yet covered linear modeling using categorical variables, the gender variable is replaced with a continuous variable that measures the number of followers participants have on Instagram.

We're going to use these data to review multiple linear regression with categorical variables, dummy and effects coding, checking model assumptions and diagnostics, and performing bootstrapping. 