---
title: "<b>Functions Quiz</b>"
subtitle: "Data Analysis for Psychology in R 2<br><br> "
author: "TOM BOOTH & ALEX DOUMAS"
institute: "Department of Psychology<br>The University of Edinburgh"
date: "AY 2020-2021"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
options(htmltools.dir.version = FALSE)
```


```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
style_mono_accent(
  #base_color = "#0F4C81", # DAPR1
   base_color = "#BF1932", # DAPR2
  # base_color = "#88B04B", # DAPR3 
  # base_color = "#FCBB06", # USMR
  # base_color = "#a41ae4", # MSMR
  header_color = "#000000",
  header_font_google = google_font("Source Sans Pro"),
  header_font_weight = 400,
  text_font_google = google_font("Source Sans Pro", "400", "400i", "600", "600i"),
  code_font_google = google_font("Source Code Pro")
)

library(tidyverse)
```

# Function 1

```{r, echo=FALSE}
df <- tibble(
  x = 0:10
  ) %>%
  mutate(
    f1 = x + 2*x,
    f2 = x -5,
    f3 = 5 + (x-1)^2
  )
 
ggplot(df, aes(x=x, y = f1)) +
  geom_line() 
```


---

# Function 2

```{r, echo=FALSE}

ggplot(df, aes(x=x, y = f2)) +
  geom_line() 
```


---
# Function 3

```{r, echo=FALSE}

ggplot(df, aes(x=x, y = f3)) +
  geom_line() 
```