---
title: 'dapR2 Live : Semester 2 week 3'
author: "dapR2 Team"
date: "31/01/2022"
output: html_document
---

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(emmeans)
library(kableExtra)
```

# Data

```{r, echo=FALSE}
n <- round(500*(c(.55, .2, .1, .05, .1)),0)
set.seed(7284)
wb_tib <- tibble(
  swb = c(rnorm(n[1], 11, 3.6),
          rnorm(n[2], 12, 4.2),
          rnorm(n[3], 8, 2.2),
          rnorm(n[4], 6, 1.1),
          rnorm(n[5], 9.5, 2.5)),
  status = factor(c(rep("Married/CP", n[1]),
             rep("Cohab", n[2]),
             rep("Single", n[3]),
             rep("Widowed", n[4]),
             rep("Divorced", n[5])))
)
```

```{r}
wb_tib %>%
  group_by(status) %>%
  summarise(
    n = n(),
    mean = round(mean(swb),2),
    sd = round(sd(swb),2)
  ) %>%
  kable(.)%>%
  kable_styling(., full_width = F)
```

# Run model
```{r}
m1 <- lm(swb ~ status, wb_tib)
summary(m1)
```

```{r}
contrasts(wb_tib$status)
```


# Specific contrasts
1. Those who are currently or previously married or in a civil partnership vs not.
2. Those who are currently married or in a civil partnership vs those who have previously been.

```{r}
comp <- list("Married/CP vs Not" = c(-1/2, 1/3, 1/3, -1/2, 1/3),
             "Current vs Previous" = c(0, -0.5, 1, 0, -0.5),
              "Reverse" = c(0, 0.5, -1, 0, 0.5)
             )
```

2. Those who are currently married or in a civil partnership vs those who have previously been.

$$
1. \quad H_0: \mu_\text{Current} = \mu_\text{Previous} \\

  \quad H_0: \mu_\text{Married/CP} = \frac{1}{2} (\mu_\text{Divorced} + \mu_\text{Widowed}) \\
$$

Get the means:

```{r}
wb_means <- emmeans(m1, ~status)
wb_means
```

Apply the contrasts
```{r}
m1_con <- contrast(wb_means, method = comp)
m1_con
```


```{r}
confint(m1_con)
```

