---
title: "<b>Best Lines Quiz</b>"
subtitle: "Data Analysis for Psychology in R 2<br><br> "
author: "TOM BOOTH & ALEX DOUMAS"
institute: "Department of Psychology<br>The University of Edinburgh"
date: "AY 2020-2021"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
options(htmltools.dir.version = FALSE)
```


```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
style_mono_accent(
  #base_color = "#0F4C81", # DAPR1
   base_color = "#BF1932", # DAPR2
  # base_color = "#88B04B", # DAPR3 
  # base_color = "#FCBB06", # USMR
  # base_color = "#a41ae4", # MSMR
  header_color = "#000000",
  header_font_google = google_font("Source Sans Pro"),
  header_font_weight = 400,
  text_font_google = google_font("Source Sans Pro", "400", "400i", "600", "600i"),
  code_font_google = google_font("Source Code Pro")
)

```

```{r, echo=FALSE, warning=FALSE}
library(MASS)
mu <- c(0,0)
Sigma <- matrix(c(1.0, 0.6,
                  0.6, 1.0), byrow = T, ncol = 2)

rawvars <- mvrnorm(n=10000, mu=mu, Sigma=Sigma)

df <- rawvars[sample(nrow(rawvars), 150),]


Sigma2 <- matrix(c(1.0, -0.4,
                  -0.4, 1.0), byrow = T, ncol = 2)

rawvars2 <- mvrnorm(n=10000, mu=mu, Sigma=Sigma2)

df2 <- rawvars2[sample(nrow(rawvars2), 150),]


Sigma3 <- matrix(c(1.0, 0,
                  0, 1.0), byrow = T, ncol = 2)

rawvars3 <- mvrnorm(n=10000, mu=mu, Sigma=Sigma3)

df3 <- rawvars3[sample(nrow(rawvars3), 150),]


res <- data.frame(df, df2, df3)
colnames(res) <- c("x1", "y1","x2", "y2","x3", "y3")
```




# Q1

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
ggplot(res, aes(x = x1, y = y1)) +
  geom_point() +
  geom_abline(slope = -0.64, intercept = -0.11) +
  geom_abline(slope = 0.4, intercept = 1.5, col = "red") +
  geom_abline(slope = 0.64, intercept = -0.11, col = "blue") + #correct
  geom_abline(slope = 0.3, intercept = 0.1, col = "green")
```


---

# Q2

```{r, echo=FALSE}
ggplot(res, aes(x = x2, y = y2)) +
  geom_point() +
  geom_abline(slope = -0.5, intercept = 1.5) +
  geom_abline(slope = -0.31, intercept = -0.07, col = "red") + #correct
  geom_abline(slope = -.1, intercept = 1, col = "blue") +
  geom_abline(slope = 0.3, intercept = 0.1, col = "green")
```



---
# Q3

```{r, echo=FALSE}
ggplot(res, aes(x = x3, y = y3)) +
  geom_point() +
  geom_abline(slope = 0.7, intercept = .1) +
  geom_abline(slope = 0.08, intercept = -2, col = "red") +
  geom_abline(slope = 0.08, intercept = 3, col = "blue") +
  geom_abline(slope = 0.08, intercept = -0.08, col = "green") #correct
```