<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DAPR2 - Intro to Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR2</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intro-to-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Intro to Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intro-to-linear-models">    
        <li>
    <a class="dropdown-item" href="./1_01_function.html">
 <span class="dropdown-text">1/1: Functions and Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_slr.html">
 <span class="dropdown-text">1/2: Intro to Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_mlr.html">
 <span class="dropdown-text">1/3: Multiple Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_model_fit.html">
 <span class="dropdown-text">1/4: Model Fit and Standardization</span></a>
  </li>  
        <li class="dropdown-header">1/5: Recap &amp; Write Up</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more-linear-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">More Linear Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more-linear-models">    
        <li class="dropdown-header">1/7: Interactions I: Num x Cat &amp; Num x Num</li>
        <li class="dropdown-header">1/8: Interactions II: Cat x Cat</li>
        <li class="dropdown-header">1/9: Assumptions &amp; Diagnostics</li>
        <li class="dropdown-header">1/10: Bootstrap &amp; Troubleshooting</li>
        <li class="dropdown-header">1/11: Recap &amp; Write Up</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysing-experimental-studies" role="button" data-bs-toggle="dropdown" aria-expanded="false">Analysing Experimental Studies</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysing-experimental-studies">    
        <li class="dropdown-header">2/1: Functions and Models</li>
        <li class="dropdown-header">2/2: Intro to Linear Regression</li>
        <li class="dropdown-header">2/3: More Linear Regression</li>
        <li class="dropdown-header">2/4: Multiple Predictors</li>
        <li class="dropdown-header">2/5: Recap &amp; Write Up</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-topics-for-lm" role="button" data-bs-toggle="dropdown" aria-expanded="false">Advanced Topics for LM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-topics-for-lm">    
        <li class="dropdown-header">2/6: Functions and Models</li>
        <li class="dropdown-header">2/7: Intro to Linear Regression</li>
        <li class="dropdown-header">2/8: More Linear Regression</li>
        <li class="dropdown-header">2/9: Multiple Predictors</li>
        <li class="dropdown-header">2/10: Recap &amp; Write Up</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#study-overview" id="toc-study-overview" class="nav-link active" data-scroll-target="#study-overview">Study Overview</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration">Data Exploration</a>
  <ul class="collapse">
  <li><a href="#marginal-distributions" id="toc-marginal-distributions" class="nav-link" data-scroll-target="#marginal-distributions">Marginal Distributions</a></li>
  <li><a href="#associations-among-variables" id="toc-associations-among-variables" class="nav-link" data-scroll-target="#associations-among-variables">Associations among Variables</a></li>
  </ul></li>
  <li><a href="#model-specification-and-fitting" id="toc-model-specification-and-fitting" class="nav-link" data-scroll-target="#model-specification-and-fitting">Model Specification and Fitting</a></li>
  <li><a href="#inference-for-regression-coefficients" id="toc-inference-for-regression-coefficients" class="nav-link" data-scroll-target="#inference-for-regression-coefficients">Inference for Regression Coefficients</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Intro to Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="lo">
<section id="learning-objectives" class="level3">
<h3 class="anchored" data-anchor-id="learning-objectives"><i class="fa fa-graduation-cap"></i> Learning Objectives</h3>
<p>At the end of this lab, you will:</p>
<ol type="1">
<li>Be able to specify a simple linear model.</li>
<li>Understand what fitted values and residuals are.</li>
<li>Be able to interpret the coefficients of a fitted model.</li>
<li>Be able to test hypotheses and construct confidence intervals for the regression coefficients.</li>
</ol>
</section>
<section id="what-you-need" class="level3">
<h3 class="anchored" data-anchor-id="what-you-need"><i class="fa fa-check-square-o fa-2"></i> What You Need</h3>
<ol type="1">
<li>Be up to date with lectures</li>
<li>Have completed previous lab exercises</li>
</ol>
</section>
<section id="required-r-packages" class="level3">
<h3 class="anchored" data-anchor-id="required-r-packages"><i class="fab fa-r-project"></i> Required R Packages</h3>
<p>Remember to load all packages within a code chunk at the start of your RMarkdown file using <code>library()</code>. If you do not have a package and need to install, do so within the console using <code>install.packages(" ")</code>. For further guidance on installing/updating packages, see Section C <a href="https://uoepsy.github.io/files/install-update-r#update-pkgs">here</a>.</p>
<p>For this lab, you will need to load the following package(s):</p>
<ul>
<li><strong>tidyverse</strong></li>
</ul>
</section>
<section id="lab-data" class="level3">
<h3 class="anchored" data-anchor-id="lab-data"><i class="fa fa-file"></i> Lab Data</h3>
<p>You can download the data required for this lab <a href="https://uoepsy.github.io/data/riverview.csv">here</a> or read it in via this link https://uoepsy.github.io/data/riverview.csv.</p>
</section>
</div>
<section id="study-overview" class="level1">
<h1>Study Overview</h1>
<blockquote class="blockquote">
<p><strong>Research Question</strong></p>
<p>Is there an association between income and education level in the city of Riverview?</p>
</blockquote>
<p>Let’s imagine a study into income disparity for workers in a local authority. We might carry out interviews and find that there is an association between the level of education and an employee’s income. Those with more formal education seem to be better paid.</p>
<p>In this lab, we will use the riverview data (see below) to examine whether education level is related to income among the employees working for the city of Riverview, a hypothetical midwestern city in the US.</p>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Riverview data codebook.</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><strong>Description</strong></p>
<p>The riverview data come from <span class="citation" data-cites="Lewis-Beck2015">Lewis-Beck and Lewis-Beck (<a href="#ref-Lewis-Beck2015" role="doc-biblioref">2015</a>)</span> and contain five attributes collected from a random sample of <span class="math inline">\(n=32\)</span> employees working in the hypothetical city of Riverview. The attributes include:</p>
<ul>
<li><code>education</code>: Years of formal education</li>
<li><code>income</code>: Annual income (in thousands of U.S. dollars)</li>
<li><code>seniority</code>: Years of seniority</li>
<li><code>gender</code>: Employee’s gender</li>
<li><code>male</code>: Dummy coded gender variable (0 = Female, 1 = Male)</li>
<li><code>party</code>: Political party affiliation</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div class="cell">
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:center;"> education </th>
   <th style="text-align:center;"> income </th>
   <th style="text-align:center;"> seniority </th>
   <th style="text-align:center;"> gender </th>
   <th style="text-align:center;"> male </th>
   <th style="text-align:center;"> party </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 37.449 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> male </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> Democrat </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 26.430 </td>
   <td style="text-align:center;"> 9 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Independent </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 47.034 </td>
   <td style="text-align:center;"> 14 </td>
   <td style="text-align:center;"> male </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> Democrat </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 34.182 </td>
   <td style="text-align:center;"> 16 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Independent </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 25.479 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Republican </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 12 </td>
   <td style="text-align:center;"> 46.488 </td>
   <td style="text-align:center;"> 11 </td>
   <td style="text-align:center;"> female </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> Democrat </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p class="optional-end">
</p>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="question-begin">
Setup
</div>
<div class="question-body">
<ol type="1">
<li>Create a new RMarkdown file</li>
<li>Load the required package(s)</li>
<li>Read the riverview dataset into R, assigning it to an object named <code>riverview</code></li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Loading the required package(s)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Reading in riverview data and storing in object named 'riverview'</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>riverview <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/riverview.csv"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#check first six rows</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(riverview)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  education income seniority gender  male party      
      &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;      
1         8   37.4         7 male       1 Democrat   
2         8   26.4         9 female     0 Independent
3        10   47.0        14 male       1 Democrat   
4        10   34.2        16 female     0 Independent
5        10   25.5         1 female     0 Republican 
6        12   46.5        11 female     0 Democrat   </code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="exercises" class="level1">
<h1>Exercises</h1>
<section id="data-exploration" class="level2">
<h2 class="anchored" data-anchor-id="data-exploration">Data Exploration</h2>
<p>The common first port of call for almost any statistical analysis is to explore the data, and we can do this visually and/or numerically.</p>
<table class="table">
<colgroup>
<col style="width: 4%">
<col style="width: 46%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Marginal Distributions</th>
<th>Bivariate Associations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Description</td>
<td>The distribution of each variable (e.g., employee incomes and education levels) <em>without</em> reference to the values of the other variables</td>
<td>Describing the relationship between two numeric variables</td>
</tr>
<tr class="even">
<td><p><strong>Visually</strong> <br> <br></p>
<p><br> <br></p></td>
<td>Plot each variable individually. <br> <br> You could use, for example, <code>geom_density()</code> for a density plot or <code>geom_histogram()</code> for a histogram to comment on and/or examine: <br> <br> - The <em>shape</em> of the distribution. Look at the shape, centre and spread of the distribution. Is it symmetric or skewed? Is it unimodal or bimodal? - Identify any <em>unusual observations</em>. Do you notice any extreme observations (i.e., outliers)?</td>
<td>Plot associations among two variables. <br> <br> You could use, for example, a scatterplot to comment on and/or examine: <br> <br> - The <em>direction</em> of the association indicates whether there is a positive or negative association - The <em>form</em> of association refers to whether the relationship between the variables can be summarized well with a straight line or some more complicated pattern - The <em>strength</em> of association entails how closely the points fall to a recognizable pattern such as a line - <em>Unusual observations</em> that do not fit the pattern of the rest of the observations and which are worth examining in more detail</td>
</tr>
<tr class="odd">
<td><strong>Numerically</strong> <br> <br></td>
<td>Compute and report summary statistics e.g., mean, standard deviation, median, min, max, etc. <br> <br> You could, for example, calculate summary statistics such as the mean (<code>mean()</code>) and standard deviation (<code>sd()</code>), etc. within <code>summarize()</code></td>
<td>Compute and report the correlation coefficient. <br> <br> <br> You can use the <code>cor()</code> function to calculate this</td>
</tr>
</tbody>
</table>
<section id="marginal-distributions" class="level3">
<h3 class="anchored" data-anchor-id="marginal-distributions">Marginal Distributions</h3>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Visualise and describe the marginal distribution of (a) employee incomes, and (b) education level.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>We can plot the marginal distributions of employee incomes and education level as density curves, and add a boxplot underneath to check for the presence of outliers.</p>
<section id="employee-incomes" class="level4">
<h4 class="anchored" data-anchor-id="employee-incomes">Employee Incomes</h4>
<p>Visualisation of distribution:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> riverview, <span class="fu">aes</span>(<span class="at">x =</span> income)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">300</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Income (in thousands of U.S. dollars)"</span>, </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probability density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-densbox-income" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="1_02_slr_files/figure-html/fig-densbox-income-1.png" class="img-fluid figure-img" alt="Density and boxplot of employee incomes. Unimodal distribution, with most incomes around $45,000-70,000. No outliers suggested based on boxplot." width="672"></p>
<p></p><figcaption class="figure-caption">Figure 1: Density plot and boxplot of employee incomes</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The plot suggested that the distribution of employee incomes was unimodal, and most of the incomes were between roughly $45,000 and $70,000. The lowest income in the sample was approximately $25,000 and the highest over $80,000. This suggested there was a fair high degree of variation in the data. Furthermore, the boxplot did not highlight any outliers in the data.</p>
<p>To further summarize the distribution, it is typical to compute and report numerical summary statistics such as the mean and standard deviation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>desc_income <span class="ot">&lt;-</span> riverview <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">M =</span> <span class="fu">mean</span>(income), </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD =</span> <span class="fu">sd</span>(income)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>desc_income</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
      M    SD
  &lt;dbl&gt; &lt;dbl&gt;
1  53.7  14.6</code></pre>
</div>
</div>
<p>Following the exploration above, we can describe the income variable as follows:</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The marginal distribution of income was unimodal with a mean of approximately $53,700. There was variation in employees’ salaries (SD = $14,553).</p>
</div>
</div>
</div>
</section>
<section id="education-level" class="level4">
<h4 class="anchored" data-anchor-id="education-level">Education Level</h4>
<p>Visualisation of distribution:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> riverview, <span class="fu">aes</span>(<span class="at">x =</span> education)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">100</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Education (in years)"</span>, </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probability density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-densbox-education" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="1_02_slr_files/figure-html/fig-densbox-education-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 2: Density plot and boxplot of employee education levels</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Summary statistics for the employees’ level of education:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>desc_education <span class="ot">&lt;-</span> riverview <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">M =</span> <span class="fu">mean</span>(education),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD =</span> <span class="fu">sd</span>(education)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>desc_education</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
      M    SD
  &lt;dbl&gt; &lt;dbl&gt;
1    16  4.36</code></pre>
</div>
</div>
<p><br></p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The marginal distribution of education was unimodal with an average of of 16 years. There was variation in employees’ level of education (SD = 4.4 years).</p>
</div>
</div>
</div>
<p><br></p>
</section>
</div>
<p class="solution-end">
</p>
</section>
<section id="associations-among-variables" class="level3">
<h3 class="anchored" data-anchor-id="associations-among-variables">Associations among Variables</h3>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Create a scatterplot of income and education level before calculating the correlation between the income and education level. Making reference to both the plot and correlation coefficient, describe the relationship between income and level of education among the employees in the sample.</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We are trying to investigate how income varies when varying years of formal education. Hence, income is the dependent variable (on the y-axis), and education is the independent variable (on the x-axis).</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>Let’s produce a scatterplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> riverview, <span class="fu">aes</span>(<span class="at">x =</span> education, <span class="at">y =</span> income)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Education (in years)"</span>, </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Income (in thousands of U.S. dollars)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-riverview-scatterplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="1_02_slr_files/figure-html/fig-riverview-scatterplot-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 3: The relationship between employees’ education level and income</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>To comment on the strength of the linear association we compute the correlation coefficient:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>corr <span class="ot">&lt;-</span> riverview <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(education, income) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>corr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          education    income
education 1.0000000 0.7947847
income    0.7947847 1.0000000</code></pre>
</div>
</div>
<p>that is,</p>
<p><span class="math display">\[
r_{\text{education, income}} = 0.79
\]</span></p>
<p><br></p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>There was a strong positive linear association between education level and income for the employees in the sample. High incomes tended to be observed, on average, with more years of formal education (<span class="math inline">\(r\)</span> = .79).</p>
<p>The scatterplot did not highlight any outliers.</p>
</div>
</div>
</div>
<p><br></p>
</div>
<p class="solution-end">
</p>
</section>
</section>
<section id="model-specification-and-fitting" class="level2">
<h2 class="anchored" data-anchor-id="model-specification-and-fitting">Model Specification and Fitting</h2>
<p>The scatterplot highlighted a linear relationship, where the data points were scattered around an underlying linear pattern with a roughly-constant spread as x varied.</p>
<p>Hence, we will try to fit a simple (i.e., one x variable only) linear regression model:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x + \epsilon
\\
\quad \text{where} \quad \epsilon \sim N(0, \sigma) \text{ independently}
\]</span></p>
<p>where “<span class="math inline">\(\epsilon \sim N(0, \sigma) \text{ independently}\)</span>” means that the errors around the line have mean zero and constant spread as x varies.</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Using the <code>lm()</code> function, fit a simple linear model to predict income (DV) by Education (IV), naming the output <code>mdl</code>.</p>
<p>Write down the equation of the fitted line.</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>The syntax of the <code>lm()</code> function is:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>[model name] <span class="ot">&lt;-</span> <span class="fu">lm</span>([response variable i.e., dependent variable] <span class="sc">~</span> [explanatory variable i.e., independent variable], <span class="at">data =</span> [dataframe])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>The fitted model can be written as</p>
<p><span class="math display">\[
\widehat{Income} = \hat \beta_0 + \hat \beta_1 \ Education
\]</span></p>
<p>or</p>
<p><span class="math display">\[
\widehat{Income} = \hat \beta_0 \cdot 1 + \hat \beta_1 \cdot Education
\]</span></p>
<p>When we specify the linear model in R, we include after the tilde sign, <code>~</code>, the variables that appear to the right of the <span class="math inline">\(\hat \beta\)</span>s. That’s why the 1 is included.</p>
<p>As the variables are in the <code>riverview</code> dataframe, we would write:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(income <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education, <span class="at">data =</span> riverview)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>mdl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ 1 + education, data = riverview)

Coefficients:
(Intercept)    education  
     11.321        2.651  </code></pre>
</div>
</div>
<p>Note that by calling the name of the fitted model, <code>mdl</code>, you can see the estimated regression coefficients <span class="math inline">\(\hat \beta_0\)</span> and <span class="math inline">\(\hat \beta_1\)</span>. The fitted line is</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><span class="math display">\[
\widehat{Income} = 11.32 + 2.65 \ Education \\
\]</span></p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Explore the following equivalent ways to obtain the estimated regression coefficients — that is, <span class="math inline">\(\hat \beta_0\)</span> and <span class="math inline">\(\hat \beta_1\)</span> — from the fitted model:</p>
<ul>
<li><code>mdl</code></li>
<li><code>mdl$coefficients</code></li>
<li><code>coef(mdl)</code></li>
<li><code>coefficients(mdl)</code></li>
<li><code>summary(mdl)</code></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<p>The estimated parameters returned by the below methods are all equivalent. However, <code>summary()</code> returns more information.</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">mdl()</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">mdl$coefficients</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">coef(mdl)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">coefficients(mdl)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false">summary(mdl)</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Simply invoke the name of the fitted model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mdl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ 1 + education, data = riverview)

Coefficients:
(Intercept)    education  
     11.321        2.651  </code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mdl<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   education 
  11.321379    2.651297 </code></pre>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   education 
  11.321379    2.651297 </code></pre>
</div>
</div>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   education 
  11.321379    2.651297 </code></pre>
</div>
</div>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<p>Look under the “Estimate” column:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ 1 + education, data = riverview)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.809  -5.783   2.088   5.127  18.379 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  11.3214     6.1232   1.849   0.0743 .  
education     2.6513     0.3696   7.173 5.56e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.978 on 30 degrees of freedom
Multiple R-squared:  0.6317,    Adjusted R-squared:  0.6194 
F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The estimated intercept is <span class="math inline">\(\hat \beta_0 = 11.32\)</span> and the estimated slope is <span class="math inline">\(\hat \beta_1 = 2.65\)</span>.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Explore the following equivalent ways to obtain the estimated standard deviation of the errors — that is, <span class="math inline">\(\hat \sigma\)</span> — from the fitted model <code>mdl</code>:</p>
<ul>
<li><code>sigma(mdl)</code></li>
<li><code>summary(mdl)</code></li>
</ul>
<div class="optional-begin">
<span id="opt-start-7" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-7', 'opt-start-7')"> <span class="olab">Huh? What is <span class="math inline">\(\sigma\)</span>?</span></span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<p>The standard deviation of the errors, denoted by <span class="math inline">\(\sigma\)</span> is an important quantity to estimate because it measures how much individual data points tend to deviate above and below the regression line.</p>
<p>A small <span class="math inline">\(\sigma\)</span> indicates that the points hug the line closely and we should expect fairly accurate predictions, while a large <span class="math inline">\(\sigma\)</span> suggests that, even if we estimate the line perfectly, we can expect individual values to deviate from it by substantial amounts.</p>
<p>The <em>estimated</em> standard deviation of the errors is (surprisingly) denoted <span class="math inline">\(\hat \sigma\)</span> and is equal to</p>
<p><span class="math display">\[
\hat \sigma = \sqrt{\frac{SS_{Residual}}{n - 2}}
\]</span></p>
</div>
<p class="optional-end">
</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>The estimated standard deviation of the errors can be equivalently obtained by the below methods. However, <code>summary()</code> returns more information.</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">sigma(mdl)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">summary(mdl)</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sigma</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.978116</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>Look at the “Residual standard error” entry of the <code>summary(mdl)</code> output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ 1 + education, data = riverview)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.809  -5.783   2.088   5.127  18.379 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  11.3214     6.1232   1.849   0.0743 .  
education     2.6513     0.3696   7.173 5.56e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.978 on 30 degrees of freedom
Multiple R-squared:  0.6317,    Adjusted R-squared:  0.6194 
F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The term “Residual standard error” is a misnomer, as the help page for <code>sigma</code> says (check <code>?sigma</code>). However, it’s hard to get rid of this bad name as it has been used in too many books showing R output.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The estimated standard deviation of the errors is <span class="math inline">\(\hat \sigma = 8.98\)</span>.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Interpret the estimated intercept and slope, as well as the estimated standard deviation of the errors in the context of the research question.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<p>We can interpret the estimated intercept as follows,</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The estimated average income associated to zero years of formal education is $11,321.</p>
</div>
</div>
</div>
<p>For the estimated slope we might write,</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The estimated increase in average income associated to a one year increase in education is $2,651.</p>
</div>
</div>
</div>
<p>To interpret the estimated standard deviation of the errors we can use the fact that about 95% of values from a normal distribution fall within two standard deviations of the centre.</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>For any particular level of education, employee incomes should be distributed above and below the regression line with standard deviation estimated to be <span class="math inline">\(\hat \sigma = 8.98\)</span>. Since <span class="math inline">\(2 \hat \sigma = 2 (8.98) = 17.96\)</span>, we expect most (about 95%) of the employee incomes to be within about $18,000 from the regression line.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Plot the data and the fitted regression line. To do so:</p>
<ul>
<li>Extract the estimated regression coefficients e.g., via <code>betas &lt;- coef(mdl)</code></li>
<li>Extract the first entry of <code>betas</code> (i.e., the intercept) via <code>betas[1]</code></li>
<li>Extract the second entry of <code>betas</code> (i.e., the slope) via <code>betas[2]</code></li>
<li>Provide the intercept and slope to the function</li>
</ul>
<pre><code>geom_abline(intercept = &lt;intercept&gt;, slope = &lt;slope&gt;)</code></pre>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<p>The function <code>coef(mdl)</code> returns a <em>vector</em>: that is, a sequence of numbers all of the same type. To get the first element of the sequence you append <code>[1]</code>, and <code>[2]</code> for the second.</p>
<p>We can plot the model as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>betas <span class="ot">&lt;-</span> <span class="fu">coef</span>(mdl)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>intercept <span class="ot">&lt;-</span> betas[<span class="dv">1</span>]</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>slope <span class="ot">&lt;-</span> betas[<span class="dv">2</span>]</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> riverview, <span class="fu">aes</span>(<span class="at">x =</span> education, <span class="at">y =</span> income)) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> intercept, <span class="at">slope =</span> slope, </span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">'blue'</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Education (in years)"</span>, </span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Income (in thousands of U.S. dollars)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="1_02_slr_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<div class="statbox">
<section id="fitted-and-predicted-values" class="level2">
<h2 class="anchored" data-anchor-id="fitted-and-predicted-values">Fitted and Predicted Values</h2>
<p>To compute the model-predicted values for the data in the sample, we can use various funcitons:</p>
<ul>
<li><code>predict(&lt;fitted model&gt;)</code></li>
<li><code>fitted(&lt;fitted model&gt;)</code></li>
<li><code>fitted.values(&lt;fitted model&gt;)</code></li>
<li><code>mdl$fitted.values</code></li>
</ul>
<p>For example, this will give us the estimated income (point on our regression line) for each observed value of education level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7        8 
32.53175 32.53175 37.83435 37.83435 37.83435 43.13694 43.13694 43.13694 
       9       10       11       12       13       14       15       16 
43.13694 48.43953 48.43953 48.43953 51.09083 53.74212 53.74212 53.74212 
      17       18       19       20       21       22       23       24 
53.74212 53.74212 56.39342 59.04472 59.04472 61.69601 61.69601 64.34731 
      25       26       27       28       29       30       31       32 
64.34731 64.34731 64.34731 66.99861 66.99861 69.64990 69.64990 74.95250 </code></pre>
</div>
</div>
<p>We can also compute model-predicted values for other (unobserved) data:</p>
<ul>
<li><code>predict(&lt;fitted model&gt;, newdata = &lt;dataframe&gt;)</code></li>
</ul>
<p>We first need to remember that the model predicts <code>income</code> using the independent variable <code>education</code>. Hence, if we want predictions for new data, we first need to create a tibble with a column called <code>education</code> containing the years of education for which we want the prediction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">education =</span> <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">23</span>))</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>newdata</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 1
  education
      &lt;dbl&gt;
1        11
2        23</code></pre>
</div>
</div>
<p>Then we take <code>newdata</code> and add a new column called <code>income_hat</code>, computed as the prediction from the fitted <code>mdl</code> using the <code>newdata</code> above:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> newdata <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">income_hat =</span> <span class="fu">predict</span>(mdl, <span class="at">newdata =</span> newdata)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>newdata</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  education income_hat
      &lt;dbl&gt;      &lt;dbl&gt;
1        11       40.5
2        23       72.3</code></pre>
</div>
</div>
</section>
<section id="residuals" class="level2">
<h2 class="anchored" data-anchor-id="residuals">Residuals</h2>
<p>The residuals represent the deviations between the actual responses and the predicted responses and can be obtained either as</p>
<ul>
<li><code>mdl$residuals</code>;</li>
<li><code>resid(mdl)</code>;</li>
<li><code>residuals(mdl)</code>;</li>
<li>computing them as the difference between the response and the predicted response.</li>
</ul>
</section>
</div>
<p><br></p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Use <code>predict(mdl)</code> to compute the fitted values and residuals. Mutate the <code>riverview</code> dataframe to include the fitted values and residuals as extra columns.</p>
<p>Assign to the following symbols the corresponding numerical values:</p>
<ul>
<li><span class="math inline">\(y_{3}\)</span> = response variable for unit <span class="math inline">\(i = 3\)</span> in the sample data</li>
<li><span class="math inline">\(\hat y_{3}\)</span> = fitted value for the third unit</li>
<li><span class="math inline">\(\hat \epsilon_{5} = y_{5} - \hat y_{5}\)</span> = the residual corresponding to the 5th unit.</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>riverview_fitted <span class="ot">&lt;-</span> riverview <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">income_hat =</span> <span class="fu">predict</span>(mdl),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">resid =</span> income <span class="sc">-</span> income_hat</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(riverview_fitted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  education income seniority gender  male party       income_hat  resid
      &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt;
1         8   37.4         7 male       1 Democrat          32.5   4.92
2         8   26.4         9 female     0 Independent       32.5  -6.10
3        10   47.0        14 male       1 Democrat          37.8   9.20
4        10   34.2        16 female     0 Independent       37.8  -3.65
5        10   25.5         1 female     0 Republican        37.8 -12.4 
6        12   46.5        11 female     0 Democrat          43.1   3.35</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(y_{3}\)</span> = 47.03</li>
<li><span class="math inline">\(\hat y_{3}\)</span> = 37.83</li>
<li><span class="math inline">\(\hat \epsilon_{5} = y_{5} - \hat y_{5}\)</span> = -12.36</li>
</ul>
</div>
<p class="solution-end">
</p>
<p><br></p>
<section id="inference-for-regression-coefficients" class="level2 statbox">
<h2 class="anchored" data-anchor-id="inference-for-regression-coefficients">Inference for Regression Coefficients</h2>
<p>We have fitted a linear model, and we now know how we interpret our coefficients. But this is only part of the story. Consider again the output of the <code>summary()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ 1 + education, data = riverview)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.809  -5.783   2.088   5.127  18.379 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  11.3214     6.1232   1.849   0.0743 .  
education     2.6513     0.3696   7.173 5.56e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.978 on 30 degrees of freedom
Multiple R-squared:  0.6317,    Adjusted R-squared:  0.6194 
F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
</div>
</div>
<p>To quantify the amount of uncertainty in each estimated coefficient that is due to sampling variability, we use the standard error (SE) of the coefficient. <em>Recall that a standard error gives a numerical answer to the question of how variable a statistic will be because of random sampling.</em></p>
<p>The standard errors are found in the column “Std. Error”. That is, the SE of the intercept is 6.1232, and the SE of the slope corresponding to the education variable is 0.3696.</p>
<p>In this example the slope, 2.651, has a standard error of 0.37. One way to envision this is as a distribution. Our best guess (mean) for the slope parameter is 2.651. The standard deviation of this distribution is 0.37, which indicates the precision (uncertainty) of our estimate.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="1_02_slr_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Sampling distribution of the slope coefficient. The distribution is approximately bell-shaped with a mean of 2.651 and a standard error of 0.37.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>It shouldn’t surprise you that the reference distribution in this case is a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom, where <span class="math inline">\(n\)</span> is the sample size.</p>
</section>
<p><br></p>
<div class="sticky">
<p>Recall the main formulas for obtaining a confidence interval and a test-statistic:</p>
<p><strong>Test statistic</strong></p>
<p>A test statistic for the null hypothesis <span class="math inline">\(H_0: \beta_1 = 0\)</span> is</p>
<p><span class="math display">\[
t = \frac{\hat \beta_1 - 0}{SE(\hat \beta_1)}
\]</span></p>
<p>which follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.</p>
<p><strong>Confidence interval</strong></p>
<p>A confidence interval for the population slope is</p>
<p><span class="math display">\[
\hat \beta_1 \pm t^* \cdot SE(\hat \beta_1)
\]</span></p>
<p>where <span class="math inline">\(t^*\)</span> denotes the critical value chosen from t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom for a desired <span class="math inline">\(\alpha\)</span> level of confidence.</p>
</div>
<p><br></p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Test the hypothesis that the population slope is zero — that is, that there is no linear association between income and education level in the population.</p>
<div class="callout-tip callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You can find all of the necessary information in the <code>summary()</code> output of your model, or calculate manually.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Manually</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">R function</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p>We calculate the test statistic</p>
<p><span class="math display">\[
t = \frac{\hat \beta_1 - 0}{SE(\hat \beta_1)} = \frac{ 2.6513 - 0 }{0.3696} = 7.173
\]</span></p>
<p>and compare it with the 5% critical value from a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom, which is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(riverview)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>tstar <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>tstar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.042272</code></pre>
</div>
</div>
<p>As <span class="math inline">\(|t|\)</span> is much larger than <span class="math inline">\(t^*\)</span>, we reject then null hypothesis as have strong evidence against it.</p>
<p>The p-value, shown below, also confirms the conclusion.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fl">7.173</span>, n <span class="sc">-</span> <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.561692e-08</code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<p>Please note that the same information was already contained in the row corresponding to the variable “education” in the output of <code>summary(mdl)</code>, which reported the <span class="math inline">\(t\)</span>-statistic under <code>t value</code> and the <span class="math inline">\(p\)</span>-value under <code>Pr(&gt;|t|)</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ 1 + education, data = riverview)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.809  -5.783   2.088   5.127  18.379 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  11.3214     6.1232   1.849   0.0743 .  
education     2.6513     0.3696   7.173 5.56e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.978 on 30 degrees of freedom
Multiple R-squared:  0.6317,    Adjusted R-squared:  0.6194 
F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Before we interpret the results, recall that the p-value <code>5.56e-08</code> in the <code>Pr(&gt;|t|)</code> column simply means <span class="math inline">\(5.56 \times 10^{-8}\)</span>. This is a very small value (i.e., 0.0000000556), hence we will report it as &lt;.001 following the APA guidelines.</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>We performed a <span class="math inline">\(t\)</span>-test against the null hypothesis that education was not associated with income. A significant association was found between level of education (in years) and income <span class="math inline">\(t(30) = 7.173,\ p &lt; .001\)</span>, two-sided. Thus, we have evidence against the null hypothesis.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Compute a confidence interval for the regression slope</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-13" class="fa-solid fa-circle-arrow-right solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')"> Solution </span>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">Manually</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">R function</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<p>In the riverview example, for 95% confidence we have <span class="math inline">\(t^* = 2.04\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(riverview)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>tstar <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>tstar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.042272</code></pre>
</div>
</div>
<p>The confidence interval is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>beta1_ci <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> <span class="fl">2.6513</span> <span class="sc">-</span> tstar <span class="sc">*</span> <span class="fl">0.3696</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">upper =</span> <span class="fl">2.6513</span> <span class="sc">+</span> tstar <span class="sc">*</span> <span class="fl">0.3696</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>beta1_ci</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower upper
  &lt;dbl&gt; &lt;dbl&gt;
1  1.90  3.41</code></pre>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<p>We can easily obtain the confidence intervals for the regression coefficients using the command <code>confint()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mdl, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) -1.183935 23.826693
education    1.896425  3.406168</code></pre>
</div>
</div>
<p>The result is exactly the same (up to rounding errors) as calculating manually.</p>
</div>
</div>
</div>
<p>We typically report our uncertainty in a statistic by providing <span class="math inline">\(\text{estimate} \pm t^* \cdot \text{SE}\)</span>. Here we would say that because of sampling variation, we are 95% confident that the slope is between 1.896 and 3.406. Interpreting this, we might say,</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>For all Riverview city employees, each one-year difference in formal education was associated with a difference in income between $1,896 and $3,406, on average.</p>
</div>
</div>
</div>
<p>Similarly, we could express the uncertainty in the intercept <span class="math inline">\(\hat \beta_0\)</span> as:</p>
<div class="callout-important callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The average income for all Riverview city employees with zero years of education is between $-1184 and $23,827.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-Lewis-Beck2015" class="csl-entry" role="doc-biblioentry">
Lewis-Beck, Colin, and Michael Lewis-Beck. 2015. <em>Applied Regression: An Introduction</em>. Vol. 22. Sage publications.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
      <div class="nav-footer-center">© Copyright 2019-2022 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
  </div>
</footer>



</body></html>