{
  "hash": "11a7b794d2bb44e2246b909c93b5087d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bootstrapping\"\nlink-citations: TRUE\nparams: \n    SHOW_SOLS: TRUE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n:::lo\n\n### <i class=\"fa fa-graduation-cap\"></i> Learning Objectives\nAt the end of this lab, you will:\n\n1. Understand the principles of bootstrapping\n2. Understand how to apply the bootstrap confidence interval to inference in linear models\n\n### <i class=\"fa fa-check-square-o fa-2\"></i> What You Need\n\n1. Be up to date with lectures\n2. Have completed previous lab exercises from [Week 2](https://uoepsy.github.io/dapr2/2425/labs/1_02_mlr.html) and [Week 9](https://uoepsy.github.io/dapr2/2425/labs/1_08_assump_diag.html)\n\n### <i class=\"fab fa-r-project\"></i> Required R Packages\nRemember to load all packages within a code chunk at the start of your RMarkdown file using `library()`. If you do not have a package and need to install, do so within the console using `install.packages(\" \")`. For further guidance on installing/updating packages, see Section C [here](https://uoepsy.github.io/files/install-update-r#update-pkgs). \n\nFor this lab, you will need to load the following package(s):\n\n* **tidyverse** \n* **psych**\n* **patchwork**\n* **sjPlot**\n* **kableExtra**\n* **car**\n\n### <i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i> Presenting Results\nAll results should be presented following [APA guidelines](https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf).If you need a reminder on how to hide code, format tables/plots, etc., make sure to review the [rmd bootcamp](https://uoepsy.github.io/scs/rmd-bootcamp/).\n\nThe example write-up sections included as part of the solutions are **not perfect** - they instead should give you a good example of what information you should include and how to structure this. Note that you must **not** copy any of the write-ups included below for future reports - if you do, you will be committing plagiarism, and this type of academic misconduct is taken very seriously by the University. You can find out more [here](https://www.ed.ac.uk/academic-services/students/conduct/academic-misconduct).\n\n### <i class=\"fa fa-file\"></i> Lab Data\nYou can download the data required for this lab [here](https://uoepsy.github.io/data/science-faith-attitude.csv) or read it in via this link https://uoepsy.github.io/data/science-faith-attitude.csv \n\n:::\n\n# Study Overview\n\n> **Research Question**\n>\n> Is there an association between peoples' attitudes towards science and faith and their scientific knowledge after accounting for their age?\n\n\n\n<div class=\"optional-begin\"><span id='opt-start-1' class=\"fa-solid fa-circle-right optional-icon clickable\" onclick=\"toggle_visibility('opt-body-1', 'opt-start-1')\"> <span class=\"olab\">Attitudes Codebook</span></span></div><div class=\"optional-body\" id = \"opt-body-1\" style=\"display: none;\">\n\n \n\n__Description__\n\nUsing Eurobarometer measures, researchers were interested in understanding opinions about science, technology, social values, and services of\ngeneral interest. Specifically, researchers wanted to explore whether peoples' attitudes towards science and faith was associated with their scientific knowledge after accounting for their age. To examine these associations, we will use a subset of data from the [2005 Eurobarometer 63.1 survey](https://www.gesis.org/en/eurobarometer-data-service/survey-series/standard-special-eb/study-overview/eurobarometer-631-za-4233-jan-feb-2005). \n\n__Data Dictionary__\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ezlgdzhkht\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ezlgdzhkht table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ezlgdzhkht thead, #ezlgdzhkht tbody, #ezlgdzhkht tfoot, #ezlgdzhkht tr, #ezlgdzhkht td, #ezlgdzhkht th {\n  border-style: none;\n}\n\n#ezlgdzhkht p {\n  margin: 0;\n  padding: 0;\n}\n\n#ezlgdzhkht .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ezlgdzhkht .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ezlgdzhkht .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ezlgdzhkht .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ezlgdzhkht .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ezlgdzhkht .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ezlgdzhkht .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ezlgdzhkht .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ezlgdzhkht .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ezlgdzhkht .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ezlgdzhkht .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ezlgdzhkht .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ezlgdzhkht .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ezlgdzhkht .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ezlgdzhkht .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ezlgdzhkht .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ezlgdzhkht .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ezlgdzhkht .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ezlgdzhkht .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ezlgdzhkht .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ezlgdzhkht .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ezlgdzhkht .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ezlgdzhkht .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ezlgdzhkht .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ezlgdzhkht .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ezlgdzhkht .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ezlgdzhkht .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ezlgdzhkht .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ezlgdzhkht .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ezlgdzhkht .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ezlgdzhkht .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ezlgdzhkht .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ezlgdzhkht .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ezlgdzhkht .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ezlgdzhkht .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ezlgdzhkht .gt_left {\n  text-align: left;\n}\n\n#ezlgdzhkht .gt_center {\n  text-align: center;\n}\n\n#ezlgdzhkht .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ezlgdzhkht .gt_font_normal {\n  font-weight: normal;\n}\n\n#ezlgdzhkht .gt_font_bold {\n  font-weight: bold;\n}\n\n#ezlgdzhkht .gt_font_italic {\n  font-style: italic;\n}\n\n#ezlgdzhkht .gt_super {\n  font-size: 65%;\n}\n\n#ezlgdzhkht .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ezlgdzhkht .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ezlgdzhkht .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ezlgdzhkht .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ezlgdzhkht .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ezlgdzhkht .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ezlgdzhkht .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ezlgdzhkht .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ezlgdzhkht div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">v5</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant ID</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">v6</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Nation ID:  1 = France, 2 = Belgium, 3 = The Netherlands, 4 = Germany West, 5 = Italy, 6 = Luxembourg, 7 = Denmark, 8 = Ireland, 9 = Great Britain, 10 = Northern Ireland, 11 = Greece, 12 = Spain, 13 = Portugal, 14 = Germany East, 15 = Norway, 16 = Finland, 17 = Sweden, 18 = Austria, 19 = Cyprus (Republic), 20 = Czech Republic, 21 = Estonia, 22 = Hungary, 23 = Latvia, 24 = Lithuania, 25 = Malta, 26 = Poland, 27 = Slovakia, 28 = Slovenia, 29 = Bulgaria, 30 = Romania, 31 = Turkey, 32 = Croatia, 33 Cyprus (TCC; not included), 34 = Iceland, 35 = Switzerland</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">kstot</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Score on a science quiz composed of 13 true/false items. Scores can range 0-13.</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Individual's age (in years)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">male</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Whether participant idenitfied as male (1) or female (0)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">toomuchscience</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Attitude to science and faith. Response to the question - We rely too much on science and not enough on faith. Responses were recorded on a 5-point scale from strongly disagree (0) to strongly agree (4)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">solveprob</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of explicitly mentioned target phrases in response to the question - Please tell me, in your own words, what it means to study something scientifically?</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n__Preview__\n\nThe first six rows of the data are:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jwhphheblm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jwhphheblm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jwhphheblm thead, #jwhphheblm tbody, #jwhphheblm tfoot, #jwhphheblm tr, #jwhphheblm td, #jwhphheblm th {\n  border-style: none;\n}\n\n#jwhphheblm p {\n  margin: 0;\n  padding: 0;\n}\n\n#jwhphheblm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jwhphheblm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jwhphheblm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jwhphheblm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jwhphheblm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jwhphheblm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jwhphheblm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jwhphheblm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jwhphheblm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jwhphheblm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jwhphheblm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jwhphheblm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jwhphheblm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jwhphheblm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jwhphheblm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jwhphheblm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jwhphheblm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jwhphheblm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jwhphheblm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jwhphheblm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jwhphheblm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jwhphheblm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jwhphheblm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jwhphheblm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jwhphheblm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jwhphheblm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jwhphheblm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jwhphheblm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jwhphheblm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jwhphheblm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jwhphheblm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jwhphheblm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jwhphheblm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jwhphheblm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jwhphheblm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jwhphheblm .gt_left {\n  text-align: left;\n}\n\n#jwhphheblm .gt_center {\n  text-align: center;\n}\n\n#jwhphheblm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jwhphheblm .gt_font_normal {\n  font-weight: normal;\n}\n\n#jwhphheblm .gt_font_bold {\n  font-weight: bold;\n}\n\n#jwhphheblm .gt_font_italic {\n  font-style: italic;\n}\n\n#jwhphheblm .gt_super {\n  font-size: 65%;\n}\n\n#jwhphheblm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jwhphheblm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jwhphheblm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jwhphheblm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jwhphheblm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jwhphheblm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jwhphheblm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jwhphheblm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jwhphheblm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"v5\">v5</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"v6\">v6</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"kstot\">kstot</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age\">age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"male\">male</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"toomuchscience\">toomuchscience</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"solveprob\">solveprob</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"v5\" class=\"gt_row gt_right\">1</td>\n<td headers=\"v6\" class=\"gt_row gt_right\">2</td>\n<td headers=\"kstot\" class=\"gt_row gt_right\">12</td>\n<td headers=\"age\" class=\"gt_row gt_right\">35</td>\n<td headers=\"male\" class=\"gt_row gt_right\">1</td>\n<td headers=\"toomuchscience\" class=\"gt_row gt_right\">2</td>\n<td headers=\"solveprob\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"v5\" class=\"gt_row gt_right\">2</td>\n<td headers=\"v6\" class=\"gt_row gt_right\">2</td>\n<td headers=\"kstot\" class=\"gt_row gt_right\">11</td>\n<td headers=\"age\" class=\"gt_row gt_right\">34</td>\n<td headers=\"male\" class=\"gt_row gt_right\">0</td>\n<td headers=\"toomuchscience\" class=\"gt_row gt_right\">1</td>\n<td headers=\"solveprob\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"v5\" class=\"gt_row gt_right\">3</td>\n<td headers=\"v6\" class=\"gt_row gt_right\">2</td>\n<td headers=\"kstot\" class=\"gt_row gt_right\">7</td>\n<td headers=\"age\" class=\"gt_row gt_right\">40</td>\n<td headers=\"male\" class=\"gt_row gt_right\">0</td>\n<td headers=\"toomuchscience\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"solveprob\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"v5\" class=\"gt_row gt_right\">4</td>\n<td headers=\"v6\" class=\"gt_row gt_right\">2</td>\n<td headers=\"kstot\" class=\"gt_row gt_right\">9</td>\n<td headers=\"age\" class=\"gt_row gt_right\">32</td>\n<td headers=\"male\" class=\"gt_row gt_right\">0</td>\n<td headers=\"toomuchscience\" class=\"gt_row gt_right\">3</td>\n<td headers=\"solveprob\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"v5\" class=\"gt_row gt_right\">5</td>\n<td headers=\"v6\" class=\"gt_row gt_right\">2</td>\n<td headers=\"kstot\" class=\"gt_row gt_right\">6</td>\n<td headers=\"age\" class=\"gt_row gt_right\">35</td>\n<td headers=\"male\" class=\"gt_row gt_right\">0</td>\n<td headers=\"toomuchscience\" class=\"gt_row gt_right\">3</td>\n<td headers=\"solveprob\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"v5\" class=\"gt_row gt_right\">6</td>\n<td headers=\"v6\" class=\"gt_row gt_right\">2</td>\n<td headers=\"kstot\" class=\"gt_row gt_right\">11</td>\n<td headers=\"age\" class=\"gt_row gt_right\">67</td>\n<td headers=\"male\" class=\"gt_row gt_right\">1</td>\n<td headers=\"toomuchscience\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"solveprob\" class=\"gt_row gt_right\">NA</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n</div><p class=\"optional-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Setup\n\n\n\n<div class='question-begin'>Setup</div><div class='question-body'>\n\n  \n\n1. Create a new RMarkdown file\n2. Load the required package(s)\n3. Read in the science-faith-attitude dataset into R, assigning it to an object named `ebsurvey` \n \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-2' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#load packages\nlibrary(tidyverse) \nlibrary(psych)\nlibrary(patchwork)\nlibrary(sjPlot)\nlibrary(kableExtra)\nlibrary(car)\n\n#read in data\nebsurvey <- read_csv(\"https://uoepsy.github.io/data/science-faith-attitude.csv\")\n```\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Exercises \n\n## Study Overview & Data Management\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\n\nExamine the dataset, and perform any necessary and appropriate data management steps.\n\nNote, to address the research question, we only need to refer to the `kstot`, `age`, and `toomuchscience` variables. Subset the data to only have those 3 columns.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n- To subset the data to only include the 3 variables of interest, we can use the `select()` function  \n- Check that the dataset is complete (i.e., are there any `NA` values?). We can check this using `is.na()`  \n    - There are numerous ways to deal with this. Two common commands are `na.omit()` and `drop_na()`. The former will remove all rows from a dataset that contain `NA` values in any column. In the latter, we can specify which columns we want to identify `NA` values in, and remove only rows containing `NA` values for those specific columns. In other words, the latter can help to preserve more data  \n- If needed, provide better variable names\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-3' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Inspect top 6 rows\nhead(ebsurvey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n     v5    v6 kstot   age  male toomuchscience solveprob\n  <dbl> <dbl> <dbl> <dbl> <dbl>          <dbl>     <dbl>\n1     1     2    12    35     1              2         0\n2     2     2    11    34     0              1         1\n3     3     2     7    40     0             NA        NA\n4     4     2     9    32     0              3         0\n5     5     2     6    35     0              3         1\n6     6     2    11    67     1             NA        NA\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check data dimensions\ndim(ebsurvey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21886     7\n```\n\n\n:::\n:::\n\n\n\nThere are 21886 observations on 7 variables.\n\nHowever, today we will be only using the `kstot`, `age`, and `toomuchscience` variables, and so we subset the data to only include these:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nebsurvey <- ebsurvey %>%\n    select(kstot, age, toomuchscience)\n```\n:::\n\n\n\nAre there any `NA` values in the data?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#check for NAs\nanyNA(ebsurvey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\n#how many NAs?\ntable(is.na(ebsurvey))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n54268 11390 \n```\n\n\n:::\n\n```{.r .cell-code}\n#11390 NAs in data set \n\n#Omit the NAs - we are interested in all three columns so do not need to specify within drop_na()\nebsurvey <- ebsurvey %>%\n    drop_na()\n\n# Check new data dimensions\ndim(ebsurvey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10503     3\n```\n\n\n:::\n:::\n\n\n\nGive the variables more meaningful names. Rename `kstot` to `science_knowledge` and rename `toomuchscience` to `attitude`:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nebsurvey <- ebsurvey %>%\n    rename(science_knowledge = kstot,\n           attitude = toomuchscience)\nhead(ebsurvey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  science_knowledge   age attitude\n              <dbl> <dbl>    <dbl>\n1                12    35        2\n2                11    34        1\n3                 9    32        3\n4                 6    35        3\n5                 9    37        1\n6                 5    63        2\n```\n\n\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\n\nProvide a brief overview of the study design and data, before detailing your analysis plan to address the research question.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\n- Give the reader some background on the context of the study\n- State what type of analysis you will conduct in order to address the research question\n- Specify the model to be fitted to address the research question (note that you will need to specify the reference level of any categorical variable(s))\n- Specify your chosen significance ($\\alpha$) level\n- State your hypotheses\n\nMuch of the information required can be found in the [Study Overview] codebook. The [statistical models](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#statistical-models) flashcards may also be useful to refer to. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-4' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\n\nThe `ebsurvey` dataset, excluding missing values, included 10,503 individual respondents who were measured on 3 different attributes of interest: (1) score on a science \"quiz\" composed of 13 true/false items; (2) attitudes towards science and faith (question phrasing: \"We rely too much on science and not enough on faith\" with responses recorded on a 5-point scale from strongly disagree to strongly agree); and (3) their age (in years).\n\nHistograms will be used to visualise the marginal distributions of attitudes towards science and faith, scientific knowledge, and age. To understand the strength of association among the variables, we will estimate the the correlation coefficients. To address the research question of whether there is an association between people’s scientific knowledge and their attitudes towards science and faith after accounting for their age, we are going to fit the following multiple linear regression model:\n\n$$\n \\text{Attitude} = \\beta_0  + \\beta_1 \\cdot \\text{Science Knowledge} + \\beta_2 \\cdot \\text{Age} + \\epsilon\n$$\nEffects will be considered statistically significant at $\\alpha = .05$.\n\nOur hypotheses are:\n\n$H_0: \\beta_1 = 0$: There is no association between people’s scientific knowledge and their attitudes towards science and faith after accounting for their age\n\n$H_1: \\beta_1 \\neq 0$: There is an association between people’s scientific knowledge and their attitudes towards science and faith after accounting for their age\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Descriptive Statistics & Visualisations\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\n\nAlongside descriptive statistics, visualise the marginal distributions of the `attitude`, `science_knowledge`, and `age` variables. \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nReview the many ways to numerically and visually explore your data by reading over the [data exploration flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#data-exploration).\n\nFor examples, see flashcards on [descriptives statistics tables](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#data-exploration) and [data visualisation - marginal](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#visual-exploration).\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-5' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\n::: {.panel-tabset}\n\n## Numeric\n\n\n\n::: {#tbl-w9-desc .cell layout-align=\"center\" tbl-cap='Attitude, Scientfic Knowledge, and Age Descriptive Statistics'}\n\n```{.r .cell-code}\n# drop columns 5, 6, 7 and 13 from describe output\nebsurvey %>% \n    describe() %>%\n    select(-c(5:7, 13)) %>%\n    kable(caption = \"Attitude, Scientfic Knowledge, and Age Descriptive Statistics\", align = \"c\", digits = 2) %>%\n    kable_styling(full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Attitude, Scientfic Knowledge, and Age Descriptive Statistics</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">  </th>\n   <th style=\"text-align:center;\"> vars </th>\n   <th style=\"text-align:center;\"> n </th>\n   <th style=\"text-align:center;\"> mean </th>\n   <th style=\"text-align:center;\"> sd </th>\n   <th style=\"text-align:center;\"> min </th>\n   <th style=\"text-align:center;\"> max </th>\n   <th style=\"text-align:center;\"> range </th>\n   <th style=\"text-align:center;\"> skew </th>\n   <th style=\"text-align:center;\"> kurtosis </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> science_knowledge </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 10503 </td>\n   <td style=\"text-align:center;\"> 8.68 </td>\n   <td style=\"text-align:center;\"> 2.61 </td>\n   <td style=\"text-align:center;\"> 0 </td>\n   <td style=\"text-align:center;\"> 13 </td>\n   <td style=\"text-align:center;\"> 13 </td>\n   <td style=\"text-align:center;\"> -0.42 </td>\n   <td style=\"text-align:center;\"> -0.38 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> age </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 10503 </td>\n   <td style=\"text-align:center;\"> 44.93 </td>\n   <td style=\"text-align:center;\"> 17.32 </td>\n   <td style=\"text-align:center;\"> 15 </td>\n   <td style=\"text-align:center;\"> 93 </td>\n   <td style=\"text-align:center;\"> 78 </td>\n   <td style=\"text-align:center;\"> 0.18 </td>\n   <td style=\"text-align:center;\"> -0.88 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> attitude </td>\n   <td style=\"text-align:center;\"> 3 </td>\n   <td style=\"text-align:center;\"> 10503 </td>\n   <td style=\"text-align:center;\"> 2.20 </td>\n   <td style=\"text-align:center;\"> 1.22 </td>\n   <td style=\"text-align:center;\"> 0 </td>\n   <td style=\"text-align:center;\"> 4 </td>\n   <td style=\"text-align:center;\"> 4 </td>\n   <td style=\"text-align:center;\"> -0.25 </td>\n   <td style=\"text-align:center;\"> -0.87 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n## Visual\n\n::: {.panel-tabset}\n\n### Attitude Towards Science & Faith\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(ebsurvey, aes(x = attitude)) +\n    geom_bar() +\n    labs(x = 'We Rely too Much on Science and not Enough on Faith', \n         y = 'Frequency')\n```\n\n::: {.cell-output-display}\n![Bar Chart of Attitude Scores](1_09_bootstrapGRAPE_files/figure-html/fig-w9-attitude-1.png){#fig-w9-attitude fig-align='center' width=80%}\n:::\n:::\n\n\n\n:::{.callout-important icon=false appearance=\"minimal\"}\n\nThe mean score on the science and faith attitude variable is just over 2. There are only 5 discrete values possible in the distribution, based on the response options available, but the distribution looks approximately normal, with a slight negative skew (see @fig-w9-attitude).\n\n:::\n\n### Science Knowledge\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(ebsurvey, aes(x = science_knowledge)) +\n    geom_histogram() +\n    labs(x = 'Science Knowledge Quiz Scores', \n         y = 'Frequency')\n```\n\n::: {.cell-output-display}\n![Histogram of Scientific Knowledge Scores](1_09_bootstrapGRAPE_files/figure-html/fig-w9-sciknow-1.png){#fig-w9-sciknow fig-align='center' width=80%}\n:::\n:::\n\n\n\n:::{.callout-important icon=false appearance=\"minimal\"}\n\n@fig-w9-sciknow shows that the majority of values on the science knowledge quiz score cluster between about 5 and 11. There is a slight negative skew to the distribution. Overall there is little reason for concern as to the appropriateness of the variable for inclusion.\n\n:::\n\n### Age\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(ebsurvey, aes(x = age)) +\n    geom_histogram() +\n    labs(x = 'Age (years)', \n         y = 'Frequency')\n```\n\n::: {.cell-output-display}\n![Histogram of Age](1_09_bootstrapGRAPE_files/figure-html/fig-w9-age-1.png){#fig-w9-age fig-align='center' width=80%}\n:::\n:::\n\n\n\n:::{.callout-important icon=false appearance=\"minimal\"}\n\nThe mean age in the sample is about 45 years with a standard deviation of just over 17 years. The distribution looks approximately normal, with a slight positive skew (see @fig-w9-age).\n\n:::\n\n:::\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\n\nProduce plots of the associations between the outcome variable and each of the explanatory variables.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \nReview how to visually explore bivariate associations via the [data visualisation flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#visual-exploration). For specifically visualising associations between variables, see the [bivariate examples flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#visual-exploration).  \n\nNote that using `geom_point()` here might not be the best idea - all we would see from the plot is all combinations of Attitude towards Science and Faith and a) Age and b) Science Knowledge that were observed in the data, and this is not very informative:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Scatterplots displaying the associations between Attitude towards Science and Faith and a) Age, and b) Science Knowledge](1_09_bootstrapGRAPE_files/figure-html/fig-biv-relationship-demo-1.png){#fig-biv-relationship-demo fig-align='center' width=80%}\n:::\n:::\n\n\n\nInstead, you may want to consider using `geom_jitter()` to add a little bit of noise (or jitter)  to the plot. Within the `geom_jitter()` argument, take some time to experiment with the `size = ` and `alpha = ` arguments to find optimal values to aid interpretation. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-6' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np1 <- ggplot(data = ebsurvey, aes(x = age, y = attitude)) +\n    geom_jitter(size = .5, alpha = .3) +\n    labs(x = 'Age (in years)', y = \"Attitude towards Science and Faith\")\n\np2 <- ggplot(data = ebsurvey, aes(x = science_knowledge, y = attitude)) +\n    geom_jitter(size = .5, alpha = .3)  +\n    labs(x = \"Science Knowledge Quiz Scores\", y = \"Attitude towards Science and Faith\")\n\np1 | p2 \n```\n\n::: {.cell-output-display}\n![Scatterplots displaying the associations between Attitude towards Science and Faith and a) Age, and b) Science Knowledge](1_09_bootstrapGRAPE_files/figure-html/fig-biv-relationship-1.png){#fig-biv-relationship fig-align='center' width=80%}\n:::\n:::\n\n\n\n:::{.callout-important icon=false appearance=\"minimal\"}\n\nIt does not seem like there is a strong linear dependence of attitude to science and faith on a person's age or their scientific knowledge. We can make some rough observations:\n\n+ The majority of respondents scored 2 or 3 (i.e., responded as neutral or agree) on the attitudes towards science and faith question\n+ Very few people strongly disagreed with the attitudes towards science and faith question, but this appeared to be slightly more common in younger respondents\n+ Very few people had scientific knowledge quiz scores <5. Lower scientific knowledge quiz scores appeared to be associated with responses of 3 or 4 (i.e., responded as agree or strongly agree) on the attitudes towards science and faith question. \n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\n\nProduce a correlation matrix of the variables which are to be used in the analysis, and write a short paragraph describing the associations. \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nReview the [correlation flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#correlation), and remember to interpret in the context of the research question. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-7' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\n\nRecall that we can either index the dataframe or select the variables of interest:\n\n::: {.panel-tabset}\n\n## Index dataframe (`[]`)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# correlation matrix of the three columns of interest (check which columns we need - in this case, 1,2,3)\nround(cor(ebsurvey[,c(1:3)]), digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  science_knowledge   age attitude\nscience_knowledge              1.00 -0.12    -0.18\nage                           -0.12  1.00     0.05\nattitude                      -0.18  0.05     1.00\n```\n\n\n:::\n:::\n\n\n\n## Variable selection (`select()`)\n\n\n\n::: {#tbl-w9-cors .cell layout-align=\"center\" tbl-cap='Correlation Matrix'}\n\n```{.r .cell-code}\n# select only the columns we want by variable name, and pass this to cor()\nebsurvey %>% \n  select(attitude, science_knowledge, age) %>%\n  cor() %>%\n    kable(digits = 2, caption = \"Correlation Matrix\") %>%\n    kable_styling(full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Correlation Matrix</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">  </th>\n   <th style=\"text-align:right;\"> attitude </th>\n   <th style=\"text-align:right;\"> science_knowledge </th>\n   <th style=\"text-align:right;\"> age </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> attitude </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> -0.18 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> science_knowledge </td>\n   <td style=\"text-align:right;\"> -0.18 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> -0.12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> age </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> -0.12 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n:::\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\n+ There was a weak, positive, linear association between attitude towards science and faith and age for the participants in the sample $(r = .05)$\n+ There was a weak, negative, linear association between attitude towards science and faith and scientific knowledge for the participants in the sample $(r = -.18)$\n+ There was a weak, negative, linear association between scientific knowledge and age for the participants in the sample $(r = -.12)$. The correlation is relatively small in absolute terms, and we therefore have little concern about multicollinearity influencing this regression analysis\n+ Overall, there were very weak linear associations among the variables of interest\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Model Fitting & Interpretation \n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\n\nFit the specified model, and assign it the name \"att_mdl\".  \n\n$$\n \\text{Attitude} = \\beta_0  + \\beta_1 \\cdot \\text{Science Knowledge} + \\beta_2 \\cdot \\text{Age} + \\epsilon\n$$\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nFor a recap, see the [multiple linear regression model flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#numeric-outcomes-predictors). \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-8' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-8', 'sol-start-8')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-8\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\natt_mdl <- lm(attitude ~ science_knowledge + age, data = ebsurvey)\n```\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\n\nCheck the assumptions of your model. Note any violations of the model assumptions.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nReview the [assumptions flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions) and consider the most efficient way to do this (might be a good idea to review the *useful assumption plots*).  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-9' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-9', 'sol-start-9')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-9\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(2,2)) # set 2 by 2 panels\nplot(att_mdl)\npar(mfrow = c(1,1)) # go back to 1 by 1 panels\n```\n\n::: {.cell-output-display}\n![Assumption Plots for Attitudes Model](1_09_bootstrapGRAPE_files/figure-html/fig-assumpt-w9-1.png){#fig-assumpt-w9 fig-align='center' width=95%}\n:::\n:::\n\n\n\nBased on the visual inspection of the plots, the assumptions appear to be violated.\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\n\nBootstrap your model, computing 1000 bootstrap samples. \n\nProvide key model results in a formatted table, and interpret your coefficients in the context of the research question.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nReview the [bootstrap flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#bootstrap). \n\nYou can't use `tab_model()` here, but instead will need to use `kable()` and `kable_styling()`. Check over the [tables flashcard](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#tables), and in particular review the RMD bootcamp lesson which is signposted to. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-10' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-10', 'sol-start-10')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-10\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#Run model\nboot_mdl <- Boot(att_mdl, R = 1000)\n```\n:::\n\n::: {#tbl-w9-modresults .cell layout-align=\"center\" tbl-cap='Bootstrap Regression Results for Attitudes Model'}\n\n```{.r .cell-code}\nsummary(boot_mdl) %>%\n    kable(digits = 3, caption = 'Bootstrap Regression Results for Attitudes Model') %>%\n    kable_styling(full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Bootstrap Regression Results for Attitudes Model</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">  </th>\n   <th style=\"text-align:right;\"> R </th>\n   <th style=\"text-align:right;\"> original </th>\n   <th style=\"text-align:right;\"> bootBias </th>\n   <th style=\"text-align:right;\"> bootSE </th>\n   <th style=\"text-align:right;\"> bootMed </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 1000 </td>\n   <td style=\"text-align:right;\"> 2.788 </td>\n   <td style=\"text-align:right;\"> 0.002 </td>\n   <td style=\"text-align:right;\"> 0.053 </td>\n   <td style=\"text-align:right;\"> 2.790 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> science_knowledge </td>\n   <td style=\"text-align:right;\"> 1000 </td>\n   <td style=\"text-align:right;\"> -0.080 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 0.004 </td>\n   <td style=\"text-align:right;\"> -0.080 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> age </td>\n   <td style=\"text-align:right;\"> 1000 </td>\n   <td style=\"text-align:right;\"> 0.002 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 0.001 </td>\n   <td style=\"text-align:right;\"> 0.002 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.panel-tabset}\n\n## Intercept\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint - Interpretation \n\nThe intercept of a multiple regression model can be interpreted as the average expected value of the dependent variable when all of the independent variables equal zero.\n\n:::\n\n+ As presented in @tbl-w9-modresults, the estimated intercept was approximately 2.79. This represents the expected attitude towards science and faith score when all other variables were zero. \n+ In this case, only a handful of respondents had a scientific knowledge quiz score of zero, and nobody was aged zero. Hence, in this example, the intercept itself isn't very informative. \n    + A way to improve the model here to aid interpretation would be to mean centre age, and then refit the model with the mean centred age variable!\n\n## Scientific knowledge\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint - Interpretation \n\nThis represents the average marginal effect of $X1$ on $Y$, and can be interpreted as the expected change in $Y$ for a one-unit increase in $X1$ controlling for $X2$. See [Semester 1 Week 5 Lab](https://uoepsy.github.io/dapr2/2324/labs/1_05_writeup_recap.html#section-b-block-1-weeks-1---4-recap) for a recap on interpretation. \n\n:::\n\n+ As presented in @tbl-w9-modresults, the estimated value for the scientific knowledge slope was estimated to be approximately -0.08\n+ Results suggested that, holding age constant, for every one point increase in scientific knowledge quiz scores, attitude scores decreased by 0.08 points.\n+ Keeping in mind the valence of the question wording, this means that those who were more knowledgeable of science tended to be more favorable towards science – i.e. disagreeing with the statement.\n\n## Age\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint - Interpretation \n\nThis represents the average marginal effect of $X2$ on $Y$, and can be interpreted as the expected change in $Y$ for a one-unit increase in $X2$ controlling for $X1$. See [Semester 1 Week 5 Lab](https://uoepsy.github.io/dapr2/2324/labs/1_05_writeup_recap.html#section-b-block-1-weeks-1---4-recap) for a recap on interpretation. \n\n:::\n\n+ As presented in @tbl-w9-modresults, the estimated value for the age slope was estimated to be approximately 0.002\n+ Results suggested that, holding science knowledge constant, for every one year increase in age, attitude scores increased by 0.002 points.\n+ Keeping in mind the valence of the question wording, this means that older people tend to be less favorable towards science – i.e. agreeing with the statement.\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\n\nObtain 95% confidence intervals for your bootstrapped model estimates.  \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nReview the [bootstrap flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#bootstrap). \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-11' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-11', 'sol-start-11')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-11\" style=\"display: none;\">\n\n\n\nYou can use your preferred confidence level here, but by default this is 95%:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nConfint(boot_mdl, level = 0.95, type = \"perc\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap percent confidence intervals\n\n                      Estimate         2.5 %       97.5 %\n(Intercept)        2.788248712  2.6877669516  2.888953606\nscience_knowledge -0.080276256 -0.0887889092 -0.071671501\nage                0.002379446  0.0009551896  0.003710649\n```\n\n\n:::\n:::\n\n\n\nIf you want to make it into a nice table, we can use `kable()`:\n\n\n\n::: {#tbl-w9-confint .cell layout-align=\"center\" tbl-cap='Bootstrap 95% CIs'}\n\n```{.r .cell-code}\nConfint(boot_mdl, type = \"perc\") %>%\n    kable(digits = 3, caption = 'Bootstrap 95% CIs') %>%\n    kable_styling(full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Bootstrap 95% CIs</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">  </th>\n   <th style=\"text-align:right;\"> Estimate </th>\n   <th style=\"text-align:right;\"> 2.5 % </th>\n   <th style=\"text-align:right;\"> 97.5 % </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 2.788 </td>\n   <td style=\"text-align:right;\"> 2.688 </td>\n   <td style=\"text-align:right;\"> 2.889 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> science_knowledge </td>\n   <td style=\"text-align:right;\"> -0.080 </td>\n   <td style=\"text-align:right;\"> -0.089 </td>\n   <td style=\"text-align:right;\"> -0.072 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> age </td>\n   <td style=\"text-align:right;\"> 0.002 </td>\n   <td style=\"text-align:right;\"> 0.001 </td>\n   <td style=\"text-align:right;\"> 0.004 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\n+ We are 95% confident that the population intercept is between 2.68 and 2.90  \n+ We are 95% confident that the population slope for science knowledge is between -0.09 and -0.07  \n+ We are 95% confident that the population slope for age is between 0.001 and 0.004  \n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Writing Up & Presenting Results\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\n\nInterpret the results from your bootstrapped model in the context of the research question.\n\nMake reference to your key result table(s) and plot(s).\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nMake sure to include a decision in relation to your null hypothesis - based on the evidence, should you reject or fail to reject the null?  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-12' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-12', 'sol-start-12')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-12\" style=\"display: none;\">\n\n\n\nWe used a subset of data from the [2005 Eurobarometer 63.1 survey](https://www.gesis.org/en/eurobarometer-data-service/survey-series/standard-special-eb/study-overview/eurobarometer-631-za-4233-jan-feb-2005) to investigate whether there was an association between people’s scientific knowledge and their attitudes towards science and faith after accounting for their age. \n\nTo answer the research hypothesis, we fitted the following regression model:\n$$\n\\text{Attitude} = \\beta_0 + \\beta_1 \\cdot \\text{Science Knowledge} + \\beta_2 \\cdot \\text{Age} + \\epsilon\n$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nWhich resulted in the following estimated regression coefficients for the original sample:\n\n$$\n\\widehat{\\text{Attitude}} = 2.8 -0.08 \\cdot \\text{Science Knowledge} + 0.0024 \\cdot \\text{Age}\n$$\n\nThe model did not satisfy the regression assumptions (see @fig-assumpt-w9) and for this reason we assessed statistical significance using the bootstrap approach with $R = 1000$ resamples.\n\nThe 95% bootstrap confidence intervals are provided in @tbl-w9-confint. Results suggested that there was a negative and statistically significant association between attitudes towards science and faith and scientific knowledge after controlling for age $(\\beta = -0.08, CI_{95}[-0.09, -0.07])$. Since the 95% CI did not contain zero, we rejected the null hypothesis as there was evidence of an association between peoples' attitudes towards science and faith and their scientific knowledge after accounting for their age. Specifically, results suggested that for every additional quiz question people got correct, we expected their attitude score to be lower by about 0.08 points, holding age constant. In other words, respondents with greater scientific knowledge tended to be more favorable towards it, regardless of their age. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Compile Report\n\n\n\n<div class='question-begin'>Compile Report</div><div class='question-body'>\n\n  \n\nKnit your report to PDF, and check over your work. To do so, you should make sure:\n\n- Only the output you want your reader to see is visible (e.g., do you want to hide your code?)\n- Check that the **tinytex** package is installed\n- Ensure that the ‘yaml’ (bit at the very top of your document) looks something like this:\n\n```{}\n---\ntitle: \"this is my report title\"\nauthor: \"B1234506\"\ndate: \"07/09/2024\"\noutput: bookdown::pdf_document2\n---\n```\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n# What to do if you cannot knit to PDF\nIf you are having issues knitting directly to PDF, try the following:  \n\n- Knit to HTML file  \n- Open your HTML in a web-browser (e.g. Chrome, Firefox)  \n- Print to PDF (Ctrl+P, then choose to save to PDF)  \n- Open file to check formatting\n:::\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n# Hiding Code and/or Output\n\nReview [Lesson 5 of the rmd bootcamp](https://uoepsy.github.io/scs/rmd-bootcamp/05-echoeval.html) for a detailed description/worked examples.\n\n:::{.panel-tabset}\n## Hiding R Code\n\nTo not show the code of an R code chunk, and only show the output, write:\n\n````\n```{{r, echo=FALSE}}\n# code goes here\n```\n````\n\n## Hiding R Output\n\nTo show the code of an R code chunk, but hide the output, write:\n\n````\n```{{r, results='hide'}}\n# code goes here\n```\n````\n\n## Hiding R Code and Output\n\nTo hide both code and output of an R code chunk, write:\n\n````\n```{{r, include=FALSE}}\n# code goes here\n```\n````\n:::\n\n:::\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Tinytex\nYou must make sure you have **tinytex** installed in R so that you can “Knit” your Rmd document to a PDF file:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninstall.packages(\"tinytex\")\ntinytex::install_tinytex()\n```\n:::\n\n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-13' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-13', 'sol-start-13')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-13\" style=\"display: none;\">\n\n\n\nYou should end up with a PDF file. If you have followed the above instructions and still have issues with knitting, speak with a Tutor. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n",
    "supporting": [
      "1_09_bootstrapGRAPE_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}