{
  "hash": "f15869b03fe2fe364cb70f7787fb22f0",
  "result": {
    "markdown": "---\ntitle: \"Model Fit and Comparisons\"\nlink-citations: TRUE\nparams: \n    SHOW_SOLS: TRUE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n:::lo\n### <i class=\"fa fa-graduation-cap\"></i> Learning Objectives\nAt the end of this lab, you will:\n\n1. Understand how to calculate the interpret $R^2$ and adjusted-$R^2$ as a measure of model quality.\n1. Understand the calculation and interpretation of the $F$-test of model utility.\n1. Understand measures of model fit using $F$.  \n1. Understand the principles of model selection and how to compare models via $F$ tests, $AIC$, and $BIC$.\n\n### <i class=\"fa fa-check-square-o fa-2\"></i> What You Need\n\n1. Be up to date with lectures\n2. Have completed [Week 1](https://uoepsy.github.io/dapr2/2526/labs/1_01_slr.html) and [Week 2](https://uoepsy.github.io/dapr2/2526/labs/1_02_mlr.html), and [Week 3](https://uoepsy.github.io/dapr2/2526/labs/1_03_mlr_stz.html) lab exercises\n\n### <i class=\"fab fa-r-project\"></i> Required R Packages\nRemember to load all packages within a code chunk at the start of your RMarkdown file using `library()`. If you do not have a package and need to install, do so within the console using `install.packages(\" \")`. For further guidance on installing/updating packages, see Section C [here](https://uoepsy.github.io/files/install-update-r#update-pkgs). \n\nFor this lab, you will need to load the following package(s):\n\n* **tidyverse**\n* **sjPlot**\n* **kableExtra**\n\n### <i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i> Presenting Results\nAll results should be presented following [APA guidelines](https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf).If you need a reminder on how to hide code, format tables/plots, etc., make sure to review the [rmd bootcamp](https://uoepsy.github.io/scs/rmd-bootcamp/).\n\nThe example write-up sections included as part of the solutions are **not perfect** - they instead should give you a good example of what information you should include and how to structure this. Note that you must **not** copy any of the write-ups included below for future reports - if you do, you will be committing plagiarism, and this type of academic misconduct is taken very seriously by the University. You can find out more [here](https://www.ed.ac.uk/academic-services/students/conduct/academic-misconduct).\n\n### <i class=\"fa fa-file\"></i> Lab Data\nYou can download the data required for this lab [here](https://uoepsy.github.io/data/wellbeing_rural.csv) or read it in via this link https://uoepsy.github.io/data/wellbeing_rural.csv \n\n:::\n\n# Study Overview \n\n> **Research Question(s)** \n>\n> *Section I*\n>\n> + Is there an association between wellbeing and time spent outdoors after taking into account the association between wellbeing and social interactions? \n>\n> *Section II* \n>\n> + RQ1: Is the number of weekly social interactions a useful predictor of wellbeing scores?\n> + RQ2: Does weekly outdoor time explain a significant amount of variance in wellbeing scores over and above social interactions?\n\n\n\n<div class=\"optional-begin\"><span id='opt-start-1' class=\"fa-solid fa-circle-right optional-icon clickable\" onclick=\"toggle_visibility('opt-body-1', 'opt-start-1')\"> <span class=\"olab\">Wellbeing/Rurality data codebook</span></span></div><div class=\"optional-body\" id = \"opt-body-1\" style=\"display: none;\">\n\n  \n\n__Description__\n\nFrom the Edinburgh & Lothians, 100 city/suburb residences and 100 rural residences were chosen at random and contacted to participate in the study. The Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS) was used to measure mental health and well-being. \n\nParticipants filled out a questionnaire including items concerning: estimated average number of hours spent outdoors each week, estimated average number of social interactions each week (whether on-line or in-person), whether a daily routine is followed (yes/no). For those respondents who had an activity tracker app or smart watch, they were asked to provide their average weekly number of steps.  \n  \n  \n__Data Dictionary__\n\nThe data in `wellbeing_rural.csv` contain seven attributes collected from a random sample of $n=200$ hypothetical residents over Edinburgh & Lothians, and include: \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"ydgabwknrs\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ydgabwknrs table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ydgabwknrs thead, #ydgabwknrs tbody, #ydgabwknrs tfoot, #ydgabwknrs tr, #ydgabwknrs td, #ydgabwknrs th {\n  border-style: none;\n}\n\n#ydgabwknrs p {\n  margin: 0;\n  padding: 0;\n}\n\n#ydgabwknrs .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ydgabwknrs .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ydgabwknrs .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ydgabwknrs .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ydgabwknrs .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ydgabwknrs .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ydgabwknrs .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ydgabwknrs .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ydgabwknrs .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ydgabwknrs .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ydgabwknrs .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ydgabwknrs .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ydgabwknrs .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ydgabwknrs .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ydgabwknrs .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ydgabwknrs .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ydgabwknrs .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ydgabwknrs .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ydgabwknrs .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ydgabwknrs .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ydgabwknrs .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ydgabwknrs .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ydgabwknrs .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ydgabwknrs .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ydgabwknrs .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ydgabwknrs .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ydgabwknrs .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ydgabwknrs .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ydgabwknrs .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ydgabwknrs .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ydgabwknrs .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ydgabwknrs .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ydgabwknrs .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ydgabwknrs .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ydgabwknrs .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ydgabwknrs .gt_left {\n  text-align: left;\n}\n\n#ydgabwknrs .gt_center {\n  text-align: center;\n}\n\n#ydgabwknrs .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ydgabwknrs .gt_font_normal {\n  font-weight: normal;\n}\n\n#ydgabwknrs .gt_font_bold {\n  font-weight: bold;\n}\n\n#ydgabwknrs .gt_font_italic {\n  font-style: italic;\n}\n\n#ydgabwknrs .gt_super {\n  font-size: 65%;\n}\n\n#ydgabwknrs .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ydgabwknrs .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ydgabwknrs .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ydgabwknrs .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ydgabwknrs .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ydgabwknrs .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ydgabwknrs .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Age in years of respondent</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">outdoor_time</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Self report estimated number of hours per week spent outdoors </td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">social_int</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Self report estimated number of social interactions per week (both online and in-person)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">routine</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Binary 1=Yes/0=No response to the question 'Do you follow a daily routine throughout the week?'</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">wellbeing</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">location</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Location of primary residence (City, Suburb, Rural)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">steps_k</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Average weekly number of steps in thousands (as given by activity tracker if available)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n  \n  \n__Preview__\n\nThe first six rows of the data are:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"auujvnjgio\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#auujvnjgio table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#auujvnjgio thead, #auujvnjgio tbody, #auujvnjgio tfoot, #auujvnjgio tr, #auujvnjgio td, #auujvnjgio th {\n  border-style: none;\n}\n\n#auujvnjgio p {\n  margin: 0;\n  padding: 0;\n}\n\n#auujvnjgio .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#auujvnjgio .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#auujvnjgio .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#auujvnjgio .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#auujvnjgio .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#auujvnjgio .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#auujvnjgio .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#auujvnjgio .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#auujvnjgio .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#auujvnjgio .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#auujvnjgio .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#auujvnjgio .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#auujvnjgio .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#auujvnjgio .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#auujvnjgio .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#auujvnjgio .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#auujvnjgio .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#auujvnjgio .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#auujvnjgio .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#auujvnjgio .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#auujvnjgio .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#auujvnjgio .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#auujvnjgio .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#auujvnjgio .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#auujvnjgio .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#auujvnjgio .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#auujvnjgio .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#auujvnjgio .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#auujvnjgio .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#auujvnjgio .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#auujvnjgio .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#auujvnjgio .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#auujvnjgio .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#auujvnjgio .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#auujvnjgio .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#auujvnjgio .gt_left {\n  text-align: left;\n}\n\n#auujvnjgio .gt_center {\n  text-align: center;\n}\n\n#auujvnjgio .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#auujvnjgio .gt_font_normal {\n  font-weight: normal;\n}\n\n#auujvnjgio .gt_font_bold {\n  font-weight: bold;\n}\n\n#auujvnjgio .gt_font_italic {\n  font-style: italic;\n}\n\n#auujvnjgio .gt_super {\n  font-size: 65%;\n}\n\n#auujvnjgio .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#auujvnjgio .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#auujvnjgio .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#auujvnjgio .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#auujvnjgio .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#auujvnjgio .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#auujvnjgio .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age\">age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"outdoor_time\">outdoor_time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"social_int\">social_int</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"routine\">routine</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wellbeing\">wellbeing</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"location\">location</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"steps_k\">steps_k</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">28</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">12</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">13</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">36</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">21.6</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">56</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">5</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">15</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">41</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">12.3</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">25</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">19</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">11</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">35</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">49.8</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">60</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">25</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">15</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">0</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">35</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">19</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">9</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">18</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">32</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">48.1</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">34</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">18</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">13</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">34</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">67.3</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n  \n\n\n</div><p class=\"optional-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Setup\n\n\n\n<div class='question-begin'>Setup</div><div class='question-body'>\n\n  \n\n1. Create a new RMarkdown file\n2. Load the required package(s)\n3. Read the wellbeing dataset into R, assigning it to an object named `mwdata`\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-2' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#Loading the required package(s)\nlibrary(tidyverse)\nlibrary(sjPlot)\nlibrary(kableExtra)\n\n# Reading in data and storing to an object named 'mwdata'\nmwdata <- read_csv(\"https://uoepsy.github.io/data/wellbeing_rural.csv\")\n```\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Exercises \n\n## Section I: Model Fit\n\nIn the first section of this lab, you will focus on the statistics contained within the highlighted sections of the `summary()` output below. You will be both calculating these by hand and deriving via `R` before interpreting these values in the context of the research question.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/mdl_output_model.PNG){fig-align='center' width=85%}\n:::\n:::\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\n\nFit the following multiple linear regression model, and assign the output to an object called `mdl`.\n\n$$\n\\text{Wellbeing} = \\beta_0 + \\beta_1 \\cdot \\text{Social Interactions} + \\beta_2 \\cdot \\text{Outdoor Time} + \\epsilon \n$$\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nThis is the same model that you have fitted in the previous couple of weeks. \n\nSee the [statistical models flashcards](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#statistical-models), specifically the [numeric outcomes & numeric predictors > multiple linear regression models flashcards](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#multiple-linear-regression-models) for a reminder on how to specify models, as well as an example. \n\nThe `summary()` function will be useful to examine the model output. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-3' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmdl <- lm(wellbeing ~ social_int + outdoor_time, data = mwdata)\nsummary(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = wellbeing ~ social_int + outdoor_time, data = mwdata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.7611  -3.1308  -0.4213   3.3126  18.8406 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  28.62018    1.48786  19.236  < 2e-16 ***\nsocial_int    0.33488    0.08929   3.751 0.000232 ***\noutdoor_time  0.19909    0.05060   3.935 0.000115 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.065 on 197 degrees of freedom\nMultiple R-squared:  0.1265,\tAdjusted R-squared:  0.1176 \nF-statistic: 14.26 on 2 and 197 DF,  p-value: 1.644e-06\n```\n:::\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\n\nWhat is the proportion of the total variability in wellbeing scores explained by the model?\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nTo review how to calculate, extract, and interpret $R^2$ and $\\text{Adjusted-}R^2$ values, see the [model fit > linear models > R-squared and Adjusted R-squared flashcard](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#linear-models).\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-4' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\n\n::: {.panel-tabset}\n\n## Manually\n\nIn `R` we can write:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#Define n & k\nn <- nrow(mwdata)\nk <- 2\n\n#Predicted scores\nwellbeing_fitted <- mwdata |>\n  mutate(\n    wellbeing_pred = predict(mdl),\n    wellbeing_resid = wellbeing - wellbeing_pred)\n\n# Sums of Squares, and R / Adjusted R Squared\nwellbeing_fitted |>\n  summarise(\n    SSModel = sum((wellbeing_pred - mean(wellbeing))^2),\n    SSTotal = sum((wellbeing - mean(wellbeing))^2),\n    SSResid = sum(wellbeing_resid^2)\n  ) |> \n  summarise(\n    RSquared = SSModel / SSTotal,\n    AdjRSquared = 1-((1-(RSquared))*(n-1)/(n-k-1))\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  RSquared AdjRSquared\n     <dbl>       <dbl>\n1    0.126       0.118\n```\n:::\n:::\n\n\nThe output displays the Adjusted $R^2$ value in the following column:\n\n```\nAdjRSquared\n <dbl>\n 0.118\n```\n\n## R Function\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#look in second bottom row - Multiple R Squared and Adjusted R Squared both reported here\nsummary(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = wellbeing ~ social_int + outdoor_time, data = mwdata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.7611  -3.1308  -0.4213   3.3126  18.8406 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  28.62018    1.48786  19.236  < 2e-16 ***\nsocial_int    0.33488    0.08929   3.751 0.000232 ***\noutdoor_time  0.19909    0.05060   3.935 0.000115 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.065 on 197 degrees of freedom\nMultiple R-squared:  0.1265,\tAdjusted R-squared:  0.1176 \nF-statistic: 14.26 on 2 and 197 DF,  p-value: 1.644e-06\n```\n:::\n:::\n\n\nThe output of `summary()` displays the Adjusted $R^2$ value in the following line:\n\n```\nAdjusted R-squared:  0.1176 \n```\n:::\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nApproximately 12\\% of the total variability in wellbeing scores is accounted for by social interactions and outdoor time.\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\n\nWhat do you notice about the unadjusted and adjusted $R^2$ values?\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nAre they similar or quite different? Why might this be? It might be useful to think about how each is calculated.\n\nTo review how to calculate, extract, and interpret $R^2$ and $\\text{Adjusted-}R^2$ values, see the [model fit > linear models > R-squared and Adjusted R-squared flashcard](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#linear-models).\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-5' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\nThe values of the unadjusted (0.1265) and adjusted $R^2$ (0.1176) values are quite similar. This is because the sample size is quite large $(n = 200)$, and the number of predictors $(k = 2)$ is small. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\n\nPerform a model utility test at the 5\\% significance level and report your results. \n\nIn other words, conduct an $F$-test against the null hypothesis that the model is ineffective at predicting wellbeing scores using social interactions and outdoor time by computing the $F$-statistic using its definition.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nTo review how to calculate, extract, and interpret $F-ratio$ estimates, see the [model fit > linear models > F-ratio flashcard](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#linear-models).\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-6' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n\n\n::: {.panel-tabset}\n\n## Manually\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#df(model) = k \ndf1 <- 2\n\n#df(residual) = n - k - 1\ndf2 <- nrow(mwdata) - 2 - 1\n\nf_star <- qf(0.95, df1, df2)\n\n#check value\nf_star\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.041753\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel_utility <- wellbeing_fitted |>\n  summarise(\n    SSModel = sum((wellbeing_pred - mean(wellbeing))^2),\n    SSResid = sum(wellbeing_resid^2),\n    MSModel = SSModel / df1,\n    MSResid = SSResid / df2,\n    FObs = MSModel / MSResid\n  )\nmodel_utility\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 5\n  SSModel SSResid MSModel MSResid  FObs\n    <dbl>   <dbl>   <dbl>   <dbl> <dbl>\n1    732.   5054.    366.    25.7  14.3\n```\n:::\n:::\n\n\nWe can also compute the p-value:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npvalue <- 1 - pf(model_utility$FObs, df1, df2)\npvalue\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.643779e-06\n```\n:::\n:::\n\n\nThe value `1.643779e-06` simply means $1.6 \\times 10^{-6}$, so it's a really small number (i.e., 0.000001643779).\n\n## R Function\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#look in bottom row\nsummary(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = wellbeing ~ social_int + outdoor_time, data = mwdata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.7611  -3.1308  -0.4213   3.3126  18.8406 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  28.62018    1.48786  19.236  < 2e-16 ***\nsocial_int    0.33488    0.08929   3.751 0.000232 ***\noutdoor_time  0.19909    0.05060   3.935 0.000115 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.065 on 197 degrees of freedom\nMultiple R-squared:  0.1265,\tAdjusted R-squared:  0.1176 \nF-statistic: 14.26 on 2 and 197 DF,  p-value: 1.644e-06\n```\n:::\n:::\n\n\nThe relevant row is the following:\n\n```\n\nF-statistic: 14.26 on 2 and 197 DF,  p-value: 1.644e-06\n\n```\n\n:::\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nWe performed an $F$-test of model utility at the 5\\% significance level, where $F(2,197) = 14.26, p <.001$.\n\nThe large $F$-statistic and small $p$-value $(p <.001)$ suggested that we have very strong evidence against the null hypothesis.\n\nIn other words, the data provide strong evidence that the number of social interactions and outdoor time are predictors of wellbeing scores.\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Section II: Model Comparisons\n\nIn the second section of this lab, you will focus on model comparison where you will formally test a number of research questions:\n\n> + RQ1: Is the number of weekly social interactions a useful predictor of wellbeing scores?\n> + RQ2: Does weekly outdoor time explain a significant amount of variance in wellbeing scores over and above the number of weekly social interactions?\n\n<br>\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\n\nFit the below 3 models required to address the 2 research questions stated above. Note down which model(s) will be used to address each research question, and examine the results of each model. \n\nName the models as follows: \"wb_mdl0\", \"wb_mdl1\", \"wb_mdl2\"\n\n<br>\n$$\n\\text{Wellbeing} = \\beta_0  + \\epsilon\n$$\n\n<br>\n\n$$\n\\text{Wellbeing} = \\beta_0  + \\beta_1 \\cdot \\text{Social Interactions} + \\epsilon\n$$\n\n<br>\n\n$$\n\\text{Wellbeing} = \\beta_0  + \\beta_1 \\cdot \\text{Social Interactions} + \\beta_2 \\cdot \\text{Outdoor Time} + \\epsilon\n$$\n<br>\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nSee the [statistical models flashcards](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#statistical-models), specifically the [numeric outcomes & numeric predictors > multiple linear regression models flashcards](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#multiple-linear-regression-models) for a reminder on how to specify models, as well as an example. \n\nThe `summary()` function will be useful to examine the model output. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-7' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\n\n::: {.panel-tabset}\n\n## wb_mdl0\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#null/intercept only model\nwb_mdl0 <- lm(wellbeing ~ 1, data = mwdata)\nsummary(wb_mdl0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = wellbeing ~ 1, data = mwdata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-14.295  -3.295  -1.295   3.705  22.705 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  36.2950     0.3813   95.19   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.392 on 199 degrees of freedom\n```\n:::\n:::\n\n\n## wb_mdl1\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#model with social interactions\nwb_mdl1 <- lm(wellbeing ~ social_int, data = mwdata)\nsummary(wb_mdl1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = wellbeing ~ social_int, data = mwdata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.5628  -3.2741  -0.7908   3.3703  20.4706 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 32.40771    1.17532  27.573  < 2e-16 ***\nsocial_int   0.32220    0.09243   3.486 0.000605 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.247 on 198 degrees of freedom\nMultiple R-squared:  0.05781,\tAdjusted R-squared:  0.05306 \nF-statistic: 12.15 on 1 and 198 DF,  p-value: 0.0006045\n```\n:::\n:::\n\n\n## wb_mdl2\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#model with social interactions and outdoor time\nwb_mdl2 <- lm(wellbeing ~ social_int + outdoor_time, data = mwdata)\nsummary(wb_mdl2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = wellbeing ~ social_int + outdoor_time, data = mwdata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.7611  -3.1308  -0.4213   3.3126  18.8406 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  28.62018    1.48786  19.236  < 2e-16 ***\nsocial_int    0.33488    0.08929   3.751 0.000232 ***\noutdoor_time  0.19909    0.05060   3.935 0.000115 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.065 on 197 degrees of freedom\nMultiple R-squared:  0.1265,\tAdjusted R-squared:  0.1176 \nF-statistic: 14.26 on 2 and 197 DF,  p-value: 1.644e-06\n```\n:::\n:::\n\n\n:::\n\nThe models required to address each research question (RQ) are:\n\n+ RQ1: Models wb_mdl0 and wb_mdl1 \n+ RQ2: Models wb_mdl1 and wb_mdl2\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\n\nRQ1: Is the number of weekly social interactions a useful predictor of wellbeing scores? \n\nCheck that the $F$-statistic and the $p$-value are the same from the model comparison as that which are given at the bottom of `summary(wb_mdl1)`. \n\nProvide the key model results from the two models in a single formatted table.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nRemember that the null model tests the null hypothesis that all beta coefficients are zero. By comparing *wb_mdl0* to *wb_mdl1*, we can test whether we should include the IV of 'social_int'.   \n\nWhen considering what method(s) you can use to compare the models, remember to determine whether the models are [nested or non-nested](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#linear-models-1).\n\nMake sure to present your model comparison results in a well formatted table. For a quick guide, review the [tables flashcard](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#tables).\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-8' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-8', 'sol-start-8')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-8\" style=\"display: none;\">\n\n\n\n::: {.panel-tabset}\n\n## Model Comparison\n\nRun model comparison via `anova()`, and present results in well formatted table:\n\n\n::: {#tbl-wb0-wb1-comp-results .cell layout-align=\"center\" tbl-cap='Model Comparison - wb_mdl0 vs wb_mdl1'}\n\n```{.r .cell-code}\nanova(wb_mdl0, wb_mdl1) |>\n    kable(caption = \"Model Comparison - wb_mdl0 vs wb_mdl1\", align = \"c\", digits = c(2,2,2,2,2,4)) |>\n    kable_styling(full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Model Comparison - wb_mdl0 vs wb_mdl1</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Res.Df </th>\n   <th style=\"text-align:center;\"> RSS </th>\n   <th style=\"text-align:center;\"> Df </th>\n   <th style=\"text-align:center;\"> Sum of Sq </th>\n   <th style=\"text-align:center;\"> F </th>\n   <th style=\"text-align:center;\"> Pr(&gt;F) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> 199 </td>\n   <td style=\"text-align:center;\"> 5785.6 </td>\n   <td style=\"text-align:center;\"> NA </td>\n   <td style=\"text-align:center;\"> NA </td>\n   <td style=\"text-align:center;\"> NA </td>\n   <td style=\"text-align:center;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 198 </td>\n   <td style=\"text-align:center;\"> 5451.1 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 334.49 </td>\n   <td style=\"text-align:center;\"> 12.15 </td>\n   <td style=\"text-align:center;\"> 6e-04 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Comparing `summary()` and `anova()` Outputs\n\nThe output of `anova(wb_mdl0, wb_mdl1)` displays the $F$-statistic and the $p$-value in the following line:\n\n```\n  Res.Df    RSS Df Sum of Sq     F    Pr(>F)  \n2    198 5451.1  1    334.49 12.15 0.0006045 ***\n```\n\nWe can check that the $F$-statistic and the $p$-value are the the same as that which is given at the bottom of `summary(wb_mdl1)`:\n\n```\nF-statistic: 12.15 on 1 and 198 DF,  p-value: 0.0006045\n```\n\nThe $F$-statistic and the $p$-value from `anova(wb_mdl0, wb_mdl1)` and `summary(wb_mdl1)` both match! This is because the $F$-test from a model with a single predictor (i.e, 'wb_mdl1') is really just a comparison against the null model (i.e, 'wb_mdl0').\n\n\n\n\n\n## Table of Model Results \n\n\n::: {#tbl-wb0-wb1-results .cell layout-align=\"center\" tbl-cap='Regression Table for Wellbeing Models wb0 and wb1'}\n\n```{.r .cell-code}\ntab_model(wb_mdl0, wb_mdl1,\n          dv.labels = c(\"Wellbeing (WEMWBS Scores)\", \"Wellbeing (WEMWBS Scores)\"),\n          pred.labels = c(\"social_int\" = \"Social Interactions (number per week)\"),\n          title = \"Regression Table for Wellbeing Models wb0 and wb1\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<caption style=\"font-weight: bold; text-align:left;\">Regression Table for Wellbeing Models wb0 and wb1</caption>\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Wellbeing (WEMWBS Scores)</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Wellbeing (WEMWBS Scores)</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7\">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">36.29</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">35.54&nbsp;&ndash;&nbsp;37.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">32.41</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">30.09&nbsp;&ndash;&nbsp;34.73</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Social Interactions<br>(number per week)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.32</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.14&nbsp;&ndash;&nbsp;0.50</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\"><strong>0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">200</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">200</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.000 / 0.000</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.058 / 0.053</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nThe number of social interactions was found to explain a significant amount of variance in wellbeing scores $(F(1 ,198) = 12.15, p<.001)$. The model with social interactions was significantly better fitting than the intercept-only model, and thus social interactions is a useful predictor of wellbeing scores. Full regression results are presented in @tbl-wb0-wb1-results. \n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\n\nLook at the amount of variation in wellbeing scores explained by models \"wb_mdl1\" and \"wb_mdl2\". \n\nFrom this, can we answer the second research question of whether weekly outdoor time explains a significant amount of variance in wellbeing scores over and above social interactions?  \n\nProvide justification/rationale for your answer. \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nYou will need to review the $R^2$ and Adjusted $R^2$ values.\n\nConsider whether comparing these numeric values would constitute a *statistical* comparison. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-9' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-9', 'sol-start-9')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-9\" style=\"display: none;\">\n\n\n\nLet's look at the amount of variance explained by each model:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(wb_mdl1)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.0578147\n```\n:::\n\n```{.r .cell-code}\nsummary(wb_mdl2)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1176021\n```\n:::\n:::\n\n\nThe model *with* weekly outdoor time as a predictor explains 12\\% of the variance, and the model *without* explains 6\\%. But, from only looking at the proportion of variance accounted for in each model, we cannot determine which model is statistically a better fit.  \n\nTo answer the question 'Does including weekly outdoor time as a predictor provide a significantly better fit of the data?' we need to **statistically compare** wb_mdl1 to wb_mdl2. \n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br> \n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\n\nDoes weekly outdoor time explain a significant amount of variance in wellbeing scores over and above social interactions?\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nTo address RQ2, you need to statistically compare \"wb_mdl1\" and \"wb_mdl2\".  \n\nWhen considering what method(s) you can use to compare the models, remember to determine whether the models are [nested or non-nested](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#linear-models-1).\n\nMake sure to present your model comparison results in a well formatted table. For a quick guide, review the [tables flashcard](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#tables).\n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-10' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-10', 'sol-start-10')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-10\" style=\"display: none;\">\n\n\n\n::: {.panel-tabset}\n\n## Model Comparison\n\nTo statistically compare models, we could use an incremental $F$-test to compare the models since the models are nested and from the same dataset:\n\n\n::: {#tbl-wb1-wb2-comp-results .cell layout-align=\"center\" tbl-cap='Model Comparison - wb_mdl1 vs wb_mdl2'}\n\n```{.r .cell-code}\nanova(wb_mdl1, wb_mdl2) |>\n    kable(caption = \"Model Comparison - wb_mdl1 vs wb_mdl2\", align = \"c\", digits = c(2,2,2,2,2,4)) |>\n    kable_styling(full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Model Comparison - wb_mdl1 vs wb_mdl2</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Res.Df </th>\n   <th style=\"text-align:center;\"> RSS </th>\n   <th style=\"text-align:center;\"> Df </th>\n   <th style=\"text-align:center;\"> Sum of Sq </th>\n   <th style=\"text-align:center;\"> F </th>\n   <th style=\"text-align:center;\"> Pr(&gt;F) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> 198 </td>\n   <td style=\"text-align:center;\"> 5451.10 </td>\n   <td style=\"text-align:center;\"> NA </td>\n   <td style=\"text-align:center;\"> NA </td>\n   <td style=\"text-align:center;\"> NA </td>\n   <td style=\"text-align:center;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 197 </td>\n   <td style=\"text-align:center;\"> 5053.89 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 397.21 </td>\n   <td style=\"text-align:center;\"> 15.48 </td>\n   <td style=\"text-align:center;\"> 1e-04 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Table of Model Results \n\nPresent results from both models:\n\n\n::: {#tbl-wb1-wb2-results .cell layout-align=\"center\" tbl-cap='Regression Table for Wellbeing Models wb1 and wb2'}\n\n```{.r .cell-code}\ntab_model(wb_mdl1, wb_mdl2,\n          dv.labels = c(\"Wellbeing (WEMWBS Scores)\", \"Wellbeing (WEMWBS Scores)\"),\n          pred.labels = c(\"social_int\" = \"Social Interactions (number per week)\",\n                          \"outdoor_time\" = \"Outdoor Time (hours per week)\"),\n          title = \"Regression Table for Wellbeing Models wb1 and wb2\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<caption style=\"font-weight: bold; text-align:left;\">Regression Table for Wellbeing Models wb1 and wb2</caption>\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Wellbeing (WEMWBS Scores)</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Wellbeing (WEMWBS Scores)</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7\">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">32.41</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">30.09&nbsp;&ndash;&nbsp;34.73</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">28.62</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">25.69&nbsp;&ndash;&nbsp;31.55</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Social Interactions<br>(number per week)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.32</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.14&nbsp;&ndash;&nbsp;0.50</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.33</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.16&nbsp;&ndash;&nbsp;0.51</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Outdoor Time (hours per<br>week)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.20</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.10&nbsp;&ndash;&nbsp;0.30</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">200</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">200</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.058 / 0.053</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.126 / 0.118</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n\n\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nAs presented in @tbl-wb1-wb2-comp-results, weekly outdoor time was found to explain a significant amount of variance in wellbeing scores over and above weekly social interactions $(F(1 ,197) = 15.48, p<.001)$.\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\n\nA fellow researcher has suggested to examine the role of age in wellbeing scores. Based on their recommendation, compare the two following models, each looking at the associations of Wellbeing scores and different predictor variables. \n\n$\\text{Wellbeing} = \\beta_0 + \\beta_1 \\cdot \\text{Social Interactions} + \\beta_2 \\cdot \\text{Age} + \\epsilon$  \n\n$\\text{Wellbeing} = \\beta_0 + \\beta_1 \\cdot \\text{Outdoor Time} + \\epsilon$ \n\nReport which model you think best fits the data, and justify your answer. \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\nAre the models are [nested or non-nested](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#linear-models-1)? This will impact what method(s) you can use to compare the models.  \n  \nThink about whether you can quantify or use a verbal label to describe the difference in models (i.e., are there any thresholds you can refer to?).  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-11' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-11', 'sol-start-11')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-11\" style=\"display: none;\">\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#fit models\nwb_socint_age <- lm(wellbeing ~ social_int + age, data = mwdata)\nwb_outdoor <- lm(wellbeing ~ outdoor_time, data = mwdata)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#AIC values\nAIC(wb_socint_age, wb_outdoor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              df      AIC\nwb_socint_age  4 1236.575\nwb_outdoor     3 1233.289\n```\n:::\n\n```{.r .cell-code}\n#BIC values\nBIC(wb_socint_age, wb_outdoor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              df      BIC\nwb_socint_age  4 1249.769\nwb_outdoor     3 1243.184\n```\n:::\n:::\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nWe used $AIC$ and $BIC$ model selection to distinguish between two possible models describing the association between several personal factors and wellbeing scores. The model with outdoor time included as a single predictor was better fitting $(AIC = 1233.29)$ than the alternative model with weekly number of social interactions and age $(AIC = 1236.58)$ included. Based on the BIC value of the former model $(BIC = 1243.18)$, we concluded that there was strong evidence that it was better fitting than the alternative, latter model $(BIC = 1249.77)$. \n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\n\nThe code below fits 6 different models based on our `mwdata`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel1 <- lm(wellbeing ~ social_int, data = mwdata)\nmodel2 <- lm(wellbeing ~ social_int + outdoor_time, data = mwdata)\nmodel3 <- lm(wellbeing ~ social_int + age, data = mwdata)\nmodel4 <- lm(wellbeing ~ social_int + outdoor_time + age, data = mwdata)\nmodel5 <- lm(wellbeing ~ social_int + outdoor_time + age + steps_k, data = mwdata)\nmodel6 <- lm(wellbeing ~ social_int + outdoor_time, data = wb_data)\n```\n:::\n\n\nFor each of the below pairs of models, what methods are/are not available for us to use for comparison and why?  \n\n+ `model1` vs `model2`\n+ `model2` vs `model3`\n+ `model1` vs `model4`\n+ `model3` vs `model5`\n+ `model2` vs `model6`\n\n\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint \n\n[This flowchart](https://uoepsy.github.io/dapr2/2526/labs/1_b1_reading.html#linear-models-1) might help you to reach your decision.  \n  \nYou may need to examine the dataset. It is especially important to check for completeness (e.g., are there any missing values?).   \n  \nRemember that not all models *can* be compared!  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-12' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-12', 'sol-start-12')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-12\" style=\"display: none;\">\n\n\n\n::: {.panel-tabset}\n\n## `model1` vs `model2`\n\n+ These models are nested - `model2` contains all the variables of `model1` and they are fitted on the same dataset.  \n+ We can therefore use an $F$-test or AIC and BIC.  \n    \n## `model2` vs `model3`\n\n+ These models are __not__ nested, but they are fitted on the same dataset.  \n+ We can therefore use AIC or BIC, but we cannot use an $F$-test.  \n    \n## `model1` vs `model4`\n\n+ These models are nested - `model4` contains all the variables of `model1` and they are fitted on the same dataset.  \n+ We can therefore use an $F$-test or AIC and BIC.  \n    \n## `model3` vs `model5`\n\n+ These models are __not__ nested, and they are __not__ fitted on the same dataset. The \"steps_k\" variable contains missing values (over 30% of the data is missing for this variable), and so these whole rows are excluded from `model5` (but they are included in `model3`). \n+ We cannot compare these models.   \n  \n## `model2` vs `model6`  \n\n+ These models are nested, but they are __not__ fitted on the same dataset: `model2` uses the 'mwdata' dataset, whilst `model6` uses the 'wb_data' dataset.\n+ We cannot compare these models.   \n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Compile Report\n\n\n\n<div class='question-begin'>Compile Report</div><div class='question-body'>\n\n  \n\nKnit your report to PDF, and check over your work. To do so, you should make sure:\n\n- Only the output you want your reader to see is visible (e.g., do you want to hide your code?)\n- Check that the **tinytex** package is installed\n- Ensure that the ‘yaml’ (bit at the very top of your document) looks something like this:\n\n```{}\n---\ntitle: \"this is my report title\"\nauthor: \"B1234506\"\ndate: \"07/09/2024\"\noutput: bookdown::pdf_document2\n---\n```\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n# What to do if you cannot knit to PDF\nIf you are having issues knitting directly to PDF, try the following:  \n\n- Knit to HTML file  \n- Open your HTML in a web-browser (e.g. Chrome, Firefox)  \n- Print to PDF (Ctrl+P, then choose to save to PDF)  \n- Open file to check formatting\n:::\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n# Hiding Code and/or Output\n\n:::{.panel-tabset}\n## Hiding R Code\n\nTo not show the code of an R code chunk, and only show the output, write:\n\n````\n```{{r, echo=FALSE}}\n# code goes here\n```\n````\n\n## Hiding R Output\n\nTo show the code of an R code chunk, but hide the output, write:\n\n````\n```{{r, results='hide'}}\n# code goes here\n```\n````\n\n## Hiding R Code and Output\n\nTo hide both code and output of an R code chunk, write:\n\n````\n```{{r, include=FALSE}}\n# code goes here\n```\n````\n:::\n\n:::\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Tinytex\nYou must make sure you have **tinytex** installed in R so that you can “Knit” your Rmd document to a PDF file:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninstall.packages(\"tinytex\")\ntinytex::install_tinytex()\n```\n:::\n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-13' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-13', 'sol-start-13')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-13\" style=\"display: none;\">\n\n\n\nYou should end up with a PDF file. If you have followed the above instructions and still have issues with knitting, speak with a Tutor. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n",
    "supporting": [
      "1_04_model_fit_comp_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\r\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}