<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Simple linear regression</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Simple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_models.html">Lab 1: Functions and models</a>
    </li>
    <li>
      <a href="02_slr.html">Lab 2: Simple linear regression</a>
    </li>
    <li class="dropdown-header">Lab 3: Model Fit, Standardized Coefficients</li>
    <li class="dropdown-header">Lab 4: Assumptions &amp; Diagnostics</li>
    <li class="dropdown-header">Lab 5: Writing-up</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multiple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="06_mlr.html">Lab 6: Basics</a>
    </li>
    <li>
      <a href="07_mlr_int.html">Lab 7: Interactions</a>
    </li>
    <li>
      <a href="08_mlr_assumpt.html">Lab 8: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="09_mlr_select.html">Lab 9: Model Fit, Model Comparison, Model Selection</a>
    </li>
    <li>
      <a href="10_mlr_report.html">Lab 10: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Experimental Data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lab 11: ANOVA</li>
    <li class="dropdown-header">Lab 12: Sum-to-zero contrasts</li>
    <li class="dropdown-header">Lab 13: 2x2 ANOVA</li>
    <li class="dropdown-header">Lab 14: Multiple Comparisons</li>
    <li class="dropdown-header">Lab 15: Write-up</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lab 16: Logistic Regression</li>
    <li class="dropdown-header">Lab 17: Bootstrap</li>
    <li class="dropdown-header">Lab 18: Power</li>
    <li class="dropdown-header">Lab 19: Common tests as LM</li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="00_intro.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Simple linear regression</h1>

</div>


<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Be able to specify a simple linear model.</li>
<li>Understand what fitted values and residuals are.</li>
<li>Be able to interpret the coefficients of a fitted model.</li>
<li>Be able to test hypotheses and construct confidence intervals for the regression coefficients.</li>
</ol>
</div>
<div id="introduction-and-research-question" class="section level1">
<h1>Introduction and research question</h1>
<blockquote>
<p>Suppose a group of researchers was studying income differences among local government employees in Riverview, a hypothetical medium-size Midwestern city in the US. Exploratory interviews suggest a relationship between income and education. Specifically, those employees with more formal training appear to receive better pay. In an attempt to verify whether this is so, they gathered relevant data.
The researchers did not have the time or money to interview the entire population: all 320 employees on the city payroll. Therefore, they decided to interview a simple random sample of 32, selected from the personnel list that the city clerk kindly provided.</p>
<p>— <span class="citation">Lewis-Beck and Lewis-Beck (<a href="#ref-Lewis-Beck2015" role="doc-biblioref">2015</a>)</span></p>
</blockquote>
<p>In this lab we will use the <a href="#dc-riverview">riverview.csv</a> data to examine whether education level is related to income.
Please take a look at the <a href="#dc-riverview">data codebook</a> for a preview of the data and a link to download the file.</p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Load the required libraries and import the riverview data into R.
Assign the data to a variable called <code>riverview</code>.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-16" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-16&#39;, &#39;sol-start-16&#39;)"></span>
</div>
<div id="sol-body-16" class="solution-body" style="display: none;">
<pre class="r"><code>library(tidyverse)

riverview &lt;- read_csv(file = &quot;https://uoepsy.github.io/data/riverview.csv&quot;)
head(riverview)</code></pre>
<pre><code>## # A tibble: 6 x 6
##   education income seniority gender  male party      
##       &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;      
## 1         8   37.4         7 male       1 Democrat   
## 2         8   26.4         9 female     0 Independent
## 3        10   47.0        14 male       1 Democrat   
## 4        10   34.2        16 female     0 Independent
## 5        10   25.5         1 female     0 Republican 
## 6        12   46.5        11 female     0 Democrat</code></pre>
</div>
<p class="solution-end">
</p>
</div>
<div id="data-exploration" class="section level1">
<h1>Data exploration</h1>
<div id="marginal-distributions" class="section level2 unnumbered">
<h2>Marginal distributions</h2>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Investigate the marginal distribution of employee incomes.</p>
<div class="optional-begin">
Give me more guidance<span id="opt-start-17" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-17&#39;, &#39;opt-start-17&#39;)"></span>
</div>
<div id="opt-body-17" class="optional-body" style="display: none;">
<p>Typical steps when examining the marginal distribution of a quantitative variable are:</p>
<ol style="list-style-type: decimal">
<li><p><em>Plot the variable</em>.
Display the distribution of the variable. You could use, for example, <code>geom_density()</code> for a density plot or <code>geom_histogram()</code> for a histogram.</p></li>
<li><p><em>Comment on the shape of the distribution</em>.
Look at the shape, centre and spread of the distribution.
Is it symmetric or skewed? Is it unimodal or bimodal?</p></li>
<li><p><em>Identify any unusual observations</em>.
Is there evidence of observations that falls outside the overall pattern of the graph?</p></li>
</ol>
</div>
<p class="optional-end">
</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-18" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-18&#39;, &#39;sol-start-18&#39;)"></span>
</div>
<div id="sol-body-18" class="solution-body" style="display: none;">
<p>We can plot the marginal distribution of employee incomes as a density curve, and add a boxplot underneath to check for the presence of outliers.</p>
<pre class="r"><code>ggplot(data = riverview, aes(x = income)) +
  geom_density() +
  geom_boxplot(width = 1/300) +
  labs(x = &quot;Income (in thousands of U.S. dollars)&quot;, y = &quot;Probability density&quot;)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-2"></span>
<img src="02_slr_files/figure-html/unnamed-chunk-2-1.png" alt="Density plot and boxplot of employee incomes." width="60%" />
<p class="caption">
Figure 1: Density plot and boxplot of employee incomes.
</p>
</div>
<p>The plot suggests that the distribution of employee incomes is unimodal and most of the incomes are between roughly $45,000 and $70,000. The smallest income in the sample is about $25,000 and the largest income is over $80,000. (We could find the exact values using the <code>summary()</code> function.) This suggests there is a fair amount of variation in the data.
Furthermore, the boxplot does not highlight any outliers in the data.</p>
<p>To further summarize the distribution, it is typical to compute and report numerical summary statistics such as the mean and standard deviation. One way to compute these values is to use the <code>summary()</code>function from the <code>tidyverse</code> library:</p>
<pre class="r"><code>riverview %&gt;% 
  summarize(
    M = mean(income), 
    SD = sd(income)
    )</code></pre>
<pre><code>## # A tibble: 1 x 2
##       M    SD
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  53.7  14.6</code></pre>
<p>Following the exploration above, we can describe this variable as follows:</p>
<div class="int">
<p>The marginal distribution of income is unimodal with a mean of approximately $53,700. There is variation in employees’ salaries (SD = $14,553).</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Examine the marginal distribution of the education level variable.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-19" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-19&#39;, &#39;sol-start-19&#39;)"></span>
</div>
<div id="sol-body-19" class="solution-body" style="display: none;">
<p>We can visualise the marginal distribution of the education level variable using a density curve, and add a boxplot underneath to check for the presence of outliers.</p>
<pre class="r"><code>ggplot(data = riverview, aes(x = education)) +
  geom_density() +
  geom_boxplot(width = 1/100) +
  labs(x = &quot;Education (in years)&quot;, y = &quot;Probability density&quot;)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-4"></span>
<img src="02_slr_files/figure-html/unnamed-chunk-4-1.png" alt="Density plot and boxplot of employee education levels." width="60%" />
<p class="caption">
Figure 2: Density plot and boxplot of employee education levels.
</p>
</div>
<p>Below are the summary statistics for the employees’ level of education:</p>
<pre class="r"><code>riverview %&gt;%
  summarize(
    M = mean(education),
    SD = sd(education)
    )</code></pre>
<pre><code>## # A tibble: 1 x 2
##       M    SD
##   &lt;dbl&gt; &lt;dbl&gt;
## 1    16  4.36</code></pre>
<p>Again, we might write:</p>
<div class="int">
<p>The marginal distribution of education is unimodal with a mean of 16 years. There is variation in employees’ level of education (SD = 4.4 years).</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="relationship-between-variables" class="section level2 unnumbered">
<h2>Relationship between variables</h2>
<p>After examining the marginal distributions of the variables of interest in the analysis, we typically move on to examining relationships between the variables.</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Create a scatterplot to investigate the relationship between income and education level.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-20" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-20&#39;, &#39;sol-start-20&#39;)"></span>
</div>
<div id="sol-body-20" class="solution-body" style="display: none;">
<pre class="r"><code>ggplot(data = riverview, aes(x = education, y = income)) +
  geom_point(alpha = 0.5) +
  labs(x = &quot;Education (in years)&quot;, y = &quot;Income (in thousands of U.S. dollars)&quot;)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:riverview-scatterplot"></span>
<img src="02_slr_files/figure-html/riverview-scatterplot-1.png" alt="Scatterplot displaying the relationship between employee education levels and incomes." width="60%" />
<p class="caption">
Figure 3: Scatterplot displaying the relationship between employee education levels and incomes.
</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Using the scatterplot from the previous question, describe the relationship between income and level of education among the employees in the sample.</p>
<div class="optional-begin">
Give me more guidance<span id="opt-start-21" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-21&#39;, &#39;opt-start-21&#39;)"></span>
</div>
<div id="opt-body-21" class="optional-body" style="display: none;">
<p>Describing the relationship between two quantitative variables involves looking at their scatterplot and commenting on four characteristics of the relationship:</p>
<ol style="list-style-type: decimal">
<li>The <em>direction</em> of the association indicates whether large values of one variable tend to go with large values of the other (positive association) or with small values of the other (negative association).</li>
<li>The <em>form</em> of association refers to whether the relationship between the variables can be summarized well with a straight line or some more complicated pattern.</li>
<li>The <em>strength</em> of association entails how closely the points fall to a recognizable pattern such as a line.</li>
<li><em>Unusual observations</em> that do not fit the pattern of the rest of the observations and which are worth examining in more detail.</li>
</ol>
</div>
<p class="optional-end">
</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-22" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-22&#39;, &#39;sol-start-22&#39;)"></span>
</div>
<div id="sol-body-22" class="solution-body" style="display: none;">
<ol style="list-style-type: decimal">
<li>Direction: positive</li>
<li>Form: approximately linear</li>
<li>Strength: we compute the strength of a linear association using the correlation coefficient.
The closer the correlation coefficient to −1 or 1, the stronger the linear association between the variables.
The closer the correlation coefficient to 0, the weaker the linear association between the variables.</li>
<li>Unusual observations: no evidence of outliers</li>
</ol>
<p>Correlation coefficient:</p>
<pre class="r"><code>riverview %&gt;%
  select(education, income) %&gt;%
  cor()</code></pre>
<pre><code>##           education    income
## education 1.0000000 0.7947847
## income    0.7947847 1.0000000</code></pre>
<p>that is,
<span class="math display">\[
r_{\text{education, income}} = 0.79
\]</span></p>
<p>We might write:</p>
<div class="int">
<p>There is a strong, positive, linear relationship between education level and income for the employees in the sample.
Employee incomes tend to be higher, on average, as the years of formal education increases.
There appears to be some variation around the linear trend, so we will investigate the strength of the relationship in more detail later on.
It appears that there are no extreme observations, i.e. points that do not fit with the rest of the data.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="model-specification" class="section level2 unnumbered">
<h2>Model specification</h2>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Looking back at the data exploration, specify a model for the relationship between income and education level <em>in the population</em>.</p>
<p>Pick a model from one of the following:</p>
<ol style="list-style-type: upper-alpha">
<li><span class="math inline">\(y = \beta_0 + \epsilon\)</span></li>
<li><span class="math inline">\(y = \beta_0 + \beta_1 x + \epsilon\)</span></li>
<li><span class="math inline">\(y = \beta_1 x^2 + \epsilon\)</span></li>
<li><span class="math inline">\(y = e^{\beta_1 \cdot x} \cdot \epsilon\)</span></li>
</ol>
<p>where <span class="math inline">\(\epsilon \sim N(0, \sigma) \text{ independently}\)</span>.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-23" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-23&#39;, &#39;sol-start-23&#39;)"></span>
</div>
<div id="sol-body-23" class="solution-body" style="display: none;">
<p>The relationship appears to be linear, and the points appear to be scattered around an underlying linear pattern with a spread that seems to be pretty much constant as x varies.</p>
<p>We will try and fit a linear model (option B)
<span class="math display">\[
y = \beta_0 + \beta_1 x + \epsilon \quad \text{where} \quad \epsilon \sim N(0, \sigma) \text{ independently}
\]</span></p>
</div>
<p class="solution-end">
</p>
</div>
</div>
<div id="fit" class="section level1">
<h1>Fit</h1>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Fit the line to the data using the <code>lm()</code> function and assign the output to an object called <code>mdl</code>.</p>
<p>The syntax is:</p>
<pre><code>lm(&lt;response variable&gt; ~ 1 + &lt;explanatory variable&gt;, data = &lt;dataframe&gt;)</code></pre>
<p>Finally, write down the equation of the fitted line.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-24" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-24&#39;, &#39;sol-start-24&#39;)"></span>
</div>
<div id="sol-body-24" class="solution-body" style="display: none;">
<p>The fitted model in our example can be written as
<span class="math display">\[
\widehat{Income} = \hat \beta_0 + \hat \beta_1 \ Education
\]</span>
or
<span class="math display">\[
\widehat{Income} = \hat \beta_0 \cdot 1 + \hat \beta_1 \cdot Education
\]</span></p>
<p>When we specify the linear model in R, we include after the tilde <code>~</code> the variables that appear to the right of the <span class="math inline">\(\hat \beta\)</span>s, that’s why the 1 is included.</p>
<p>As the variables are in the <code>riverview</code> dataframe, we would write:</p>
<pre class="r"><code>mdl &lt;- lm(income ~ 1 + education, data = riverview)
mdl</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Coefficients:
## (Intercept)    education  
##      11.321        2.651</code></pre>
<p>Note that by calling the name of the fitted model, <code>mdl</code>, you can see the estimated regression coefficients <span class="math inline">\(\hat \beta_0\)</span> and <span class="math inline">\(\hat \beta_1\)</span>. The fitted line is:
<span class="math display">\[
\widehat{Income} = 11.32 + 2.65 \ Education \\
\]</span></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Explore the following equivalent ways to obtain the estimated regression coefficients (i.e., the intercept and slope) from the fitted model <code>mdl</code>:</p>
<p><code>mdl</code>, <code>mdl$coefficients</code>, <code>coef(mdl)</code>, <code>coefficients(mdl)</code>, <code>summary(mdl)</code></p>
<p>Explore the following equivalent ways to obtain the estimated standard deviation of the errors <span class="math inline">\(\hat \sigma\)</span> from the fitted model <code>mdl</code>:</p>
<p><code>sigma(mdl)</code>, <code>summary(mdl)</code></p>
<div class="optional-begin">
Huh? What is <span class="math inline">\(\sigma\)</span>?<span id="opt-start-25" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-25&#39;, &#39;opt-start-25&#39;)"></span>
</div>
<div id="opt-body-25" class="optional-body" style="display: none;">
<p>The standard deviation of the errors, denoted by <span class="math inline">\(\sigma\)</span> is an important quantity to estimate because it measures how much individual data points tend to deviate above and below the regression line.</p>
<p>A small <span class="math inline">\(\sigma\)</span> indicates that the points hug the line closely and we should expect fairly accurate predictions, while a large <span class="math inline">\(\sigma\)</span> suggests that, even if we estimate the line perfectly, we can expect individual values to deviate from it by substantial amounts.</p>
<p>The <em>estimated</em> standard deviation of the errors is denoted (surprise) <span class="math inline">\(\hat \sigma\)</span>.</p>
</div>
<p class="optional-end">
</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-26" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-26&#39;, &#39;sol-start-26&#39;)"></span>
</div>
<div id="sol-body-26" class="solution-body" style="display: none;">
<p>To obtain the estimated coefficients you can either:</p>
<ul>
<li>type <code>mdl</code>, i.e. simply invoke the name of the fitted model;</li>
<li>type <code>mdl$coefficients</code>;</li>
<li>use the <code>coef(mdl)</code> function;</li>
<li>use the <code>coefficients(mdl)</code> function;</li>
<li>use the <code>summary(mdl)</code> function and look under the “Estimate” column.</li>
</ul>
<p>The estimated parameters returned by the above methods are all equivalent. However, <code>summary()</code> returns more information and you need to look under the column “Estimate”.</p>
<pre class="r"><code>mdl</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Coefficients:
## (Intercept)    education  
##      11.321        2.651</code></pre>
<pre class="r"><code>mdl$coefficients</code></pre>
<pre><code>## (Intercept)   education 
##   11.321379    2.651297</code></pre>
<pre class="r"><code>coef(mdl)</code></pre>
<pre><code>## (Intercept)   education 
##   11.321379    2.651297</code></pre>
<pre class="r"><code>coefficients(mdl)</code></pre>
<pre><code>## (Intercept)   education 
##   11.321379    2.651297</code></pre>
<pre class="r"><code>summary(mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.809  -5.783   2.088   5.127  18.379 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.3214     6.1232   1.849   0.0743 .  
## education     2.6513     0.3696   7.173 5.56e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.978 on 30 degrees of freedom
## Multiple R-squared:  0.6317, Adjusted R-squared:  0.6194 
## F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p>The estimated intercept is <span class="math inline">\(\hat \beta_0 = 11.32\)</span> and the estimated slope is <span class="math inline">\(\hat \beta_1 = 2.65\)</span>.</p>
<hr />
<p>The estimated standard deviation of the errors can be equivalently obtained by:</p>
<ul>
<li>typing <code>sigma(mdl)</code>;</li>
<li>looking at the “Residual standard error” entry of the <code>summary(mdl)</code> output.</li>
</ul>
<p><em><strong>Note:</strong> As <code>help(sigma)</code> says, the term “Residual standard error” is a misnomer but it’s hard to get rid of this bad practice as it has been used in too many books which show R output.</em></p>
<pre class="r"><code>sigma(mdl)</code></pre>
<pre><code>## [1] 8.978116</code></pre>
<pre class="r"><code>summary(mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.809  -5.783   2.088   5.127  18.379 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.3214     6.1232   1.849   0.0743 .  
## education     2.6513     0.3696   7.173 5.56e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.978 on 30 degrees of freedom
## Multiple R-squared:  0.6317, Adjusted R-squared:  0.6194 
## F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p>The estimated standard deviation of the errors is <span class="math inline">\(\hat \sigma = 8.98\)</span>.</p>
<hr />
<p>We can interpret the estimated intercept as follows,</p>
<div class="int">
<p>The estimated average income associated to zero years of formal education is $11,321.</p>
</div>
<p>For the estimated slope we might write,</p>
<div class="int">
<p>The estimated increase in average income associated to a one year increase in education is $2,651.</p>
</div>
<p>And finally, to interpret the estimated standard deviation of the errors we can use the fact that about 95% of values from a normal distribution fall within two standard deviations of the centre to interpret what the value <span class="math inline">\(\hat \sigma = 8.98\)</span> says about employee incomes:</p>
<div class="int">
<p>For any particular level of education, employee incomes should be distributed above and below the regression line with standard deviation estimated to be <span class="math inline">\(\hat \sigma = 8.98\)</span>.
Since <span class="math inline">\(2 \hat \sigma = 2 (8.98) = 17.96\)</span>, we expect most (about 95%) of the employee incomes to be within about $18,000 from the regression line.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Plot the data and the fitted regression line.</p>
<div class="optional-begin">
Give me more guidance<span id="opt-start-27" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-27&#39;, &#39;opt-start-27&#39;)"></span>
</div>
<div id="opt-body-27" class="optional-body" style="display: none;">
<ol style="list-style-type: decimal">
<li>Extract the intercept using the function <code>coef(mdl)[1]</code>;</li>
<li>Extract the slope using the function <code>coef(mdl)[2]</code>;</li>
<li>Provide the intercept and slope to the function <code>geom_abline(intercept = &lt;intercept&gt;, slope = &lt;slope&gt;)</code>.</li>
</ol>
</div>
<p class="optional-end">
</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-28" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-28&#39;, &#39;sol-start-28&#39;)"></span>
</div>
<div id="sol-body-28" class="solution-body" style="display: none;">
<p>The function <code>coef(mdl)</code> returns a <em>vector</em>: that is, a sequence of numbers all of the same type.
To get the first element of the sequence you simply use <code>[1]</code>, and <code>[2]</code> for the second.</p>
<p>We can plot the model as follows:</p>
<pre class="r"><code>intercept &lt;- coef(mdl)[1]
slope &lt;- coef(mdl)[2]

ggplot(data = riverview, aes(x = education, y = income)) +
  geom_point(alpha = 0.5) +
  geom_abline(intercept = intercept, slope = slope, color = &#39;blue&#39;, size = 1) + 
  labs(x = &quot;Education (in years)&quot;, y = &quot;Income (in thousands of U.S. dollars)&quot;)</code></pre>
<p><img src="02_slr_files/figure-html/unnamed-chunk-10-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<p>A predicted value is the estimate made from the model</p>
<!-- The model-predicted values are obtained using the function `predict()`, which takes as first input the fitted regression model. -->
<p>The model-predicted values represent the estimated average response, and are obtained using the fitted line. R provides different functions according to what your goal is.</p>
<ol style="list-style-type: decimal">
<li>To obtain the predicted values for the observed <span class="math inline">\(x\)</span> values in the sample:</li>
</ol>
<ul>
<li><code>predict(&lt;FITTED MODEL&gt;)</code></li>
<li><code>fitted(&lt;FITTED MODEL&gt;)</code></li>
<li><code>fitted.values(&lt;FITTED MODEL&gt;)</code></li>
<li><code>mdl$fitted.values</code></li>
</ul>
<pre class="r"><code># Fitted values
predict(mdl)</code></pre>
<pre><code>##        1        2        3        4        5        6        7        8 
## 32.53175 32.53175 37.83435 37.83435 37.83435 43.13694 43.13694 43.13694 
##        9       10       11       12       13       14       15       16 
## 43.13694 48.43953 48.43953 48.43953 51.09083 53.74212 53.74212 53.74212 
##       17       18       19       20       21       22       23       24 
## 53.74212 53.74212 56.39342 59.04472 59.04472 61.69601 61.69601 64.34731 
##       25       26       27       28       29       30       31       32 
## 64.34731 64.34731 64.34731 66.99861 66.99861 69.64990 69.64990 74.95250</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>To obtain predicted values for new <span class="math inline">\(x\)</span> values provided via <code>&lt;NEW DATA&gt;</code>:</li>
</ol>
<ul>
<li><code>predict(&lt;FITTED MODEL&gt;, newdata = &lt;NEW DATA&gt;)</code></li>
</ul>
<pre class="r"><code># Predictions for values not in the sample
education_query &lt;- tibble(education = c(0, 20.5))
predict(mdl, newdata = education_query)</code></pre>
<pre><code>##        1        2 
## 11.32138 65.67296</code></pre>
<div id="residuals" class="section level2 unnumbered">
<h2>Residuals</h2>
<p>The residuals represent the deviations between the actual responses and the predicted responses and can be obtained either as</p>
<ul>
<li><code>mdl$residuals</code>;</li>
<li><code>resid(mdl)</code>;</li>
<li><code>residuals(mdl)</code>;</li>
<li>computing them as the difference between the response and the predicted response.</li>
</ul>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Use <code>predict(mdl)</code> to compute the fitted values and residuals. Mutate the <code>riverview</code> dataframe to include the fitted values and residuals as extra columns.</p>
<p>Assign to the following symbols the corresponding numerical values:</p>
<ul>
<li><span class="math inline">\(y_{3}\)</span> = response variable for unit <span class="math inline">\(i = 3\)</span> in the sample data</li>
<li><span class="math inline">\(\hat y_{3}\)</span> = fitted value for the third unit</li>
<li><span class="math inline">\(\hat \epsilon_{5} = y_{5} - \hat y_{5}\)</span> = the residual corresponding to the 5th unit.</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-29" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-29&#39;, &#39;sol-start-29&#39;)"></span>
</div>
<div id="sol-body-29" class="solution-body" style="display: none;">
<pre class="r"><code>riverview_fitted &lt;- riverview %&gt;%
  mutate(
    income_hat = predict(mdl),
    resid = income - income_hat
  )

head(riverview_fitted)</code></pre>
<pre><code>## # A tibble: 6 x 8
##   education income seniority gender  male party       income_hat  resid
##       &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt;
## 1         8   37.4         7 male       1 Democrat          32.5   4.92
## 2         8   26.4         9 female     0 Independent       32.5  -6.10
## 3        10   47.0        14 male       1 Democrat          37.8   9.20
## 4        10   34.2        16 female     0 Independent       37.8  -3.65
## 5        10   25.5         1 female     0 Republican        37.8 -12.4 
## 6        12   46.5        11 female     0 Democrat          43.1   3.35</code></pre>
<ul>
<li><span class="math inline">\(y_{3}\)</span> = 47.03</li>
<li><span class="math inline">\(\hat y_{3}\)</span> = 37.83</li>
<li><span class="math inline">\(\hat \epsilon_{5} = y_{5} - \hat y_{5}\)</span> = -12.36</li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Plot the original income vs education data points as black dots, along with the regression line in blue, the residuals as vertical red lines, and fitted values as blue dots.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-30" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-30&#39;, &#39;sol-start-30&#39;)"></span>
</div>
<div id="sol-body-30" class="solution-body" style="display: none;">
<pre class="r"><code>ggplot(riverview_fitted) +
  geom_point(aes(x = education, y = income), color = &#39;black&#39;, size = 2, alpha = 0.5) +
  geom_abline(intercept = intercept, slope = slope, color = &#39;blue&#39;) +
  geom_segment(aes(x = education, y = income_hat, xend = education, yend = income), 
               color = &#39;tomato1&#39;, alpha = 0.5) +
  geom_point(aes(x = education, y = income_hat), color = &#39;blue&#39;, size = 3)</code></pre>
<p><img src="02_slr_files/figure-html/unnamed-chunk-14-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
</div>
<div id="understanding-the-fit" class="section level1">
<h1>Understanding the fit</h1>
<div id="tests-and-confidence-intervals-for-slope-and-intercept" class="section level2 unnumbered">
<h2>Tests and confidence intervals for slope and intercept</h2>
<p>Consider again the output of the <code>summary()</code> function, which takes as input the fitted regression object:</p>
<pre class="r"><code>summary(mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.809  -5.783   2.088   5.127  18.379 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.3214     6.1232   1.849   0.0743 .  
## education     2.6513     0.3696   7.173 5.56e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.978 on 30 degrees of freedom
## Multiple R-squared:  0.6317, Adjusted R-squared:  0.6194 
## F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p>We already saw that the “Estimate” column returns the estimated regression coefficients.</p>
<p>To quantify the amount of uncertainty in each estimated coefficient that is due to sampling variability, we use the standard error (SE) of the coefficient.
<em>Recall that a standard error gives a numerical answer to the question of how variable a statistic will be because of random sampling.</em></p>
<p>The standard errors are found in the column “Std. Error”. That is, the SE of the intercept is 6.1232, and the SE of the slope corresponding to the education variable is 0.3696.</p>
<p>In this example the slope, 2.651, has a standard error of 0.37. One way to envision this is as a distribution. Our best guess (mean) for the slope parameter is 2.651. The standard deviation of this distribution is 0.37, which indicates the precision (uncertainty) of our estimate.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-16"></span>
<img src="02_slr_files/figure-html/unnamed-chunk-16-1.png" alt="Sampling distribution of the slope coefficient. The distribution is approximately bell-shaped with a mean of 2.651 and a standard error of 0.37." width="60%" />
<p class="caption">
Figure 4: Sampling distribution of the slope coefficient. The distribution is approximately bell-shaped with a mean of 2.651 and a standard error of 0.37.
</p>
</div>
<p>It shouldn’t surprise you that the reference distribution in this case is a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom, where <span class="math inline">\(n\)</span> is the sample size.
Recall the main formulas for obtaining a confidence interval and a test-statistic:</p>
<div class="frame">
<p><strong>Confidence interval</strong>: A confidence interval for the population slope is
<span class="math display">\[
\hat \beta_1 \pm t^* \cdot SE
\]</span>
where <span class="math inline">\(t^*\)</span> denotes the critical value chosen from t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom for a desired <span class="math inline">\(\alpha\)</span> level of confidence.</p>
<p><strong>Test statistic</strong>: A test statistic for <span class="math inline">\(H_0: \beta_1 = 0\)</span> is
<span class="math display">\[
t = \frac{\hat \beta_1 - 0}{SE}
\]</span>
which follows a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.</p>
</div>
<p>In the riverview example, for 95% confidence we have <span class="math inline">\(t^* = 2.04\)</span>. The confidence interval is:</p>
<pre class="r"><code>n &lt;- nrow(riverview)
tstar &lt;- qt(0.975, df = n - 2)
tstar</code></pre>
<pre><code>## [1] 2.042272</code></pre>
<pre class="r"><code>beta1_ci &lt;- tibble(
  lower = 2.6513 - tstar * 0.3696,
  upper = 2.6513 + tstar * 0.3696,
)
beta1_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower upper
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  1.90  3.41</code></pre>
<p>In R it is easy to obtain the confidence intervals for the regression coefficients using the command <code>confint()</code>:</p>
<pre class="r"><code>confint(mdl, level = 0.95)</code></pre>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) -1.183935 23.826693
## education    1.896425  3.406168</code></pre>
<p>The result is exactly the same (up to rounding errors) as the previous one.</p>
<p>We typically report our uncertainty in a statistic by providing <span class="math inline">\(\text{estimate} \pm t^* \cdot \text{SE}\)</span>. Here we would say that because of sampling variation, we are 95% confident that the slope is between 1.896 and 3.406. Interpreting this, we might say,</p>
<div class="int">
<p>For all Riverview city employees, each one-year difference in formal education is associated with a difference in income between $1,896 and $3,406, on average.</p>
</div>
<p>Similarly, we could express the uncertainty in the intercept <span class="math inline">\(\hat \beta_0\)</span> as:</p>
<div class="int">
<p>The average income for all Riverview city employees with zero years of education is between $-1184 and $23,827.</p>
</div>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Test the hypothesis that the population slope is zero.
That is, that there is no linear association between income and education level in the population.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-31" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-31&#39;, &#39;sol-start-31&#39;)"></span>
</div>
<div id="sol-body-31" class="solution-body" style="display: none;">
<p>We calculate the test statistic
<span class="math display">\[
t = \frac{\hat \beta_1 - 0}{SE} = \frac{ 2.6513 - 0 }{0.3696} = 7.173
\]</span>
and compare it with the 5% critical value from a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom, which is:</p>
<pre class="r"><code>n &lt;- nrow(riverview)
tstar &lt;- qt(0.975, df = n - 2)
tstar</code></pre>
<pre><code>## [1] 2.042272</code></pre>
<p>As <span class="math inline">\(|t| &gt;&gt; t^*\)</span>, we reject then null hypothesis as have strong evidence against it.</p>
<p>The p-value, shown below, also confirms the conclusion.</p>
<pre class="r"><code>2 * (1 - pt(7.173, n - 2))</code></pre>
<pre><code>## [1] 5.561692e-08</code></pre>
<p>Please note that the same information was already contained in the row corresponding to the variable “education” in the output of <code>summary(mdl)</code>, which reported the t-statistic under <code>t value</code> and the p-value under <code>Pr(&gt;|t|)</code>:</p>
<pre class="r"><code>summary(mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.809  -5.783   2.088   5.127  18.379 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.3214     6.1232   1.849   0.0743 .  
## education     2.6513     0.3696   7.173 5.56e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.978 on 30 degrees of freedom
## Multiple R-squared:  0.6317, Adjusted R-squared:  0.6194 
## F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p>Before we interpret the results, recall that the p-value <code>5.56e-08</code> in the <code>Pr(&gt;|t|)</code> column simply means <span class="math inline">\(5.56 \times 10^{-8}\)</span>. This is a very small value, hence we will report it as &lt;.001 following the APA guidelines.</p>
<div class="int">
<p>We performed a t-test against the null hypothesis that education is not a significant predictor of income: <span class="math inline">\(t(30) = 7.173,\ p &lt; .001\)</span>, two-sided.
The large t-statistic leads to a very small p-value, meaning that we have strong evidence against the null hypothesis.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="anova-for-regression" class="section level2 unnumbered">
<h2>ANOVA for regression</h2>
<p>The term ANOVA is an acronym for <strong>AN</strong>alysis <strong>O</strong>f <strong>VA</strong>riance. In a nutshell it means that we are examining/partitioning the total variability of a response variable.</p>
<p>To assess how well the model is capturing the variability of the response, we can split the total variability in the response <span class="math inline">\(y\)</span> as the sum of the variability explained by the model (the fitted regression line) plus the variability that is left unexplained in the residuals.</p>
<p><span class="math display">\[
\text{total variability in response = variability explained by model + unexplained variability in residuals}
\]</span></p>
<p>Each of these part is measured by a sum of squares:</p>
<p><span class="math display">\[
\begin{aligned}
SS_{Total} &amp;= SS_{Model} + SS_{Residual} \\
\sum_i (y_i - \bar y)^2 &amp;= \sum_i (\hat y_i - \bar y)^2 + \sum_i (y_i - \hat y_i)^2 
\end{aligned}
\]</span></p>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<p>What is the proportion of the total variability in incomes explained by the linear relationship with education level?</p>
<p><em><strong>Hint:</strong> The question asks what is the value of <span class="math inline">\(R^2 = SS_{Model} / SS_{Total}\)</span> for this model?</em></p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-32" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-32&#39;, &#39;sol-start-32&#39;)"></span>
</div>
<div id="sol-body-32" class="solution-body" style="display: none;">
<p>The proportion of the total variability in incomes explained by the linear relationship with education level is given by R-squared.</p>
<p><strong>Option 1</strong></p>
<pre class="r"><code>summary(mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.809  -5.783   2.088   5.127  18.379 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.3214     6.1232   1.849   0.0743 .  
## education     2.6513     0.3696   7.173 5.56e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.978 on 30 degrees of freedom
## Multiple R-squared:  0.6317, Adjusted R-squared:  0.6194 
## F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p>The output of <code>summary()</code> displays the R-squared value in the following line:</p>
<pre><code>Multiple R-squared:  0.6317</code></pre>
<p>For the moment, ignore “Adjusted R-squared”. We will come back to this later in the course.</p>
<p><strong>Option 2</strong></p>
<p>The R-squared can also be obtained as:
<span class="math display">\[
R^2 = \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\]</span></p>
<p>We can compute it using R as follows:</p>
<pre class="r"><code>head(riverview_fitted)</code></pre>
<pre><code>## # A tibble: 6 x 8
##   education income seniority gender  male party       income_hat  resid
##       &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt;
## 1         8   37.4         7 male       1 Democrat          32.5   4.92
## 2         8   26.4         9 female     0 Independent       32.5  -6.10
## 3        10   47.0        14 male       1 Democrat          37.8   9.20
## 4        10   34.2        16 female     0 Independent       37.8  -3.65
## 5        10   25.5         1 female     0 Republican        37.8 -12.4 
## 6        12   46.5        11 female     0 Democrat          43.1   3.35</code></pre>
<pre class="r"><code>riverview_fitted %&gt;%
  summarise(
    SSModel = sum( (income_hat - mean(income))^2 ),
    SSTotal = sum( (income - mean(income))^2 )
  ) %&gt;%
  summarise(
    RSquared = SSModel / SSTotal
  )</code></pre>
<pre><code>## # A tibble: 1 x 1
##   RSquared
##      &lt;dbl&gt;
## 1    0.632</code></pre>
<p><strong>Option 3</strong></p>
<p>The <code>anova</code> function returns the sum of squares of interest:</p>
<pre class="r"><code>mdl_anova &lt;- anova(mdl)
mdl_anova</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: income
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## education  1 4147.3  4147.3  51.452 5.562e-08 ***
## Residuals 30 2418.2    80.6                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Consider the column <code>Sum Sq</code>.
The entry corresponding to <code>education</code> gives <span class="math inline">\(SS_{Model}\)</span> = 4147.3, as education is the explanatory variable. T
he entry corresponding to <code>Residuals</code> gives <span class="math inline">\(SS_{Residual}\)</span> = 2418.2.</p>
<pre class="r"><code>SSModel &lt;- mdl_anova$`Sum Sq`[1]
SSResidual &lt;- mdl_anova$`Sum Sq`[2]
SSTotal &lt;- SSModel + SSResidual

RSquared &lt;- SSModel / SSTotal
RSquared</code></pre>
<pre><code>## [1] 0.6316828</code></pre>
<div class="int">
<p>Approximately 63% of the total variability in employee incomes is explained by the linear association with education level.</p>
</div>
</div>
<p class="solution-end">
</p>
<p>Recall that the <span class="math inline">\(R^2\)</span> is computed on the available sample, hence it is a sample statistic and it will vary from sample to sample. How do we check if the model explains a significant amount of the variability of the responses <em>in the population</em>, or if the explained variability is due to chance alone?
To assess if the sample results could have happened by random chance alone we resort to a formal F-test. In simple linear regression the hypotheses being tested are:</p>
<p><span class="math inline">\(H_0: \text{the model is ineffective, } \beta_1 = 0\)</span></p>
<p><span class="math inline">\(H_1: \text{the model is effective, } \beta_1 \neq 0\)</span></p>
<p>The relevant test-statistic compares the amount of variation in the response explained by the model to the amount of variation which left unexplained in the residuals.</p>
<p>The model utility test uses the F-statistic:</p>
<p><span class="math display">\[
\begin{split}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n-2)} = \frac{MS_{Model}}{MS_{Residual}}
\end{split}
\]</span></p>
<p>The sample F-statistic is compared to an F-distribution with <span class="math inline">\(df_{Model} = 1\)</span> and <span class="math inline">\(df_{Residual} = n - 2\)</span> degrees of freedom.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<div class="optional-begin">
Optional: Another formula for the F-test<span id="opt-start-33" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-33&#39;, &#39;opt-start-33&#39;)"></span>
</div>
<div id="opt-body-33" class="optional-body" style="display: none;">
<p>Recall the following relationships:
<span class="math display">\[
\begin{split}
SS_{Total} &amp;= SS_{Model} + SS_{Residual} \\
\\
R^2 &amp;= \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\end{split}
\]</span></p>
<p>With some algebra we can also show that:
<span class="math display">\[
F = \frac{R^2 / 1}{(1 - R^2) / (n - 2) }
\]</span></p>
<p>Proof:</p>
<p><span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)} 
= \frac{\frac{SS_{Model}}{SS_{Total}}}{\frac{SS_{Residual}}{SS_{Total}} \cdot \frac{1}{(n - 2)}} 
= \frac{R^2 / 1}{(1 - R^2) / (n - 2)}
\end{aligned}
\]</span></p>
</div>
<p class="optional-end">
</p>
<div class="question-begin">
Question 13
</div>
<div class="question-body">
<p>Look at the output of <code>summary(mdl)</code> and <code>anova(mdl)</code>.</p>
<p>For each output, identify the relevant information to conduct an F-test against the null hypothesis that the model is ineffective at predicting income using education level.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-34" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-34&#39;, &#39;sol-start-34&#39;)"></span>
</div>
<div id="sol-body-34" class="solution-body" style="display: none;">
<pre class="r"><code>summary(mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.809  -5.783   2.088   5.127  18.379 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.3214     6.1232   1.849   0.0743 .  
## education     2.6513     0.3696   7.173 5.56e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.978 on 30 degrees of freedom
## Multiple R-squared:  0.6317, Adjusted R-squared:  0.6194 
## F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p>The relevant row is the following:</p>
<pre><code>F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p><br /></p>
<p>Instead, the <code>anova()</code> output is:</p>
<pre class="r"><code>anova(mdl)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: income
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## education  1 4147.3  4147.3  51.452 5.562e-08 ***
## Residuals 30 2418.2    80.6                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>And the relevant entries are:</p>
<ul>
<li>the <code>Df</code> column, which contains the degrees of freedom;</li>
<li><code>F value = 51.452</code>, which is the F-statistic;</li>
<li><code>Pr(&gt;F) = 5.562e-08</code> = <span class="math inline">\(5.562 \times 10^{-8}\)</span>, which is the p-value.</li>
</ul>
<p><br /></p>
<p>We might write up the test results as,</p>
<div class="int">
<p>We performed an F-test for the overall significance of the regression, <span class="math inline">\(F(1, 30) = 51.45, p &lt; .001\)</span>.
The large F-statistic leads to a very small p-value (&lt;.001), meaning that we have very strong evidence against the null hypothesis that the model is ineffective.
The data provide strong evidence that education is an effective predictor of income.</p>
</div>
</div>
<p class="solution-end">
</p>
<p>Please note that in simple linear regression, the F-statistic for overall model significance is equal to the square of the t-statistic for <span class="math inline">\(H_0: \beta_1 = 0\)</span>.</p>
<p>Let’s check that. Consider the <code>F value</code> output of <code>anova(mdl)</code> and the <code>t value</code> for education returned by <code>summary(mdl)</code></p>
<pre><code>F value = 51.452
t value = 7.173</code></pre>
<p>You can check that the squared t-statistic is equal, up to rounding error, to the F-statistic:
<span class="math display">\[
t^2 = F \\
7.173^2 = 51.452
\]</span></p>
<div class="optional-begin">
Optional: Equivalence of t-test for the slope and model utility F-test in SLR<span id="opt-start-35" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-35&#39;, &#39;opt-start-35&#39;)"></span>
</div>
<div id="opt-body-35" class="optional-body" style="display: none;">
<p>Here we will show the equivalence of the F-test for model effectiveness and t-test for the slope.</p>
<p>Recall the formula of the sum of squares due to the model. We will rewrite it in an equivalent form below:
<span class="math display">\[
\begin{aligned}
SS_{Model} &amp;= \sum_i (\hat y_i - \bar y)^2 \\
&amp;= \sum_i (\hat \beta_0 + \hat \beta_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\bar y - \hat \beta_1 \bar x + \hat \beta_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\hat \beta_1 (x_i - \bar x))^2 \\
&amp;= \hat \beta_1^2 \sum_i (x_i - \bar x)^2
\end{aligned}
\]</span></p>
<p>The F-statistic is given by:
<span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)} 
= \frac{\hat \beta_1^2 \sum_i (x_i - \bar x)^2}{\hat \sigma^2} 
= \frac{\hat \beta_1^2 }{\hat \sigma^2 / \sum_i (x_i - \bar x)^2}
\end{aligned}
\]</span></p>
<p>Now recall the formula of the t-statistic,
<span class="math display">\[
t = \frac{\hat \beta_1}{SE} = \frac{\hat \beta_1}{\hat \sigma / \sqrt{\sum_i (x_i - \bar x)^2}}
\]</span></p>
<p>It is evident that the latter is obtained as the square root of the former.</p>
</div>
<p class="optional-end">
</p>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-Lewis-Beck2015">
<p>Lewis-Beck, Colin, and Michael Lewis-Beck. 2015. <em>Applied Regression: An Introduction</em>. Vol. 22. Sage publications.</p>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>
<span class="math inline">\(SS_{Residual}\)</span> has <span class="math inline">\(n - 2\)</span> degrees of freedom. There are <span class="math inline">\(n\)</span> residuals, but two degrees of freedom are lost in estimating the slope and intercept of the line used to obtain the <span class="math inline">\(\hat y_i\)</span>s.
<span class="math inline">\(SS_{Model}\)</span> has 1 degrees of freedom. Even though there are <span class="math inline">\(n\)</span> deviations <span class="math inline">\(\hat y_i - \bar y\)</span>, they are all computed from the same fitted model, which has two degrees of freedoms associated to it: the intercept and the slope. One degree of freedom is lost as the deviations <span class="math inline">\(\hat y_i - \bar y\)</span> are subject to a constraint: they must sum to zero.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
