<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Categorical predictors and assumptions</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Simple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_models.html">Lab 1: Functions and models</a>
    </li>
    <li>
      <a href="02_slr.html">Lab 2: Simple linear regression</a>
    </li>
    <li>
      <a href="03_slr_model_fit.html">Lab 3: Model fit and standardization</a>
    </li>
    <li class="dropdown-header">Lab 4: Assumptions &amp; Diagnostics</li>
    <li class="dropdown-header">Lab 5: Writing-up</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multiple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="06_mlr.html">Lab 6: Basics</a>
    </li>
    <li>
      <a href="07_mlr_int.html">Lab 7: Interactions</a>
    </li>
    <li>
      <a href="08_mlr_assumpt.html">Lab 8: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="09_mlr_select.html">Lab 9: Model Fit, Model Comparison, Model Selection</a>
    </li>
    <li>
      <a href="10_mlr_report.html">Lab 10: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Experimental Data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lab 11: ANOVA</li>
    <li class="dropdown-header">Lab 12: Sum-to-zero contrasts</li>
    <li class="dropdown-header">Lab 13: 2x2 ANOVA</li>
    <li class="dropdown-header">Lab 14: Multiple Comparisons</li>
    <li class="dropdown-header">Lab 15: Write-up</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lab 16: Logistic Regression</li>
    <li class="dropdown-header">Lab 17: Bootstrap</li>
    <li class="dropdown-header">Lab 18: Power</li>
    <li class="dropdown-header">Lab 19: Common tests as LM</li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="00_intro.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Categorical predictors and assumptions</h1>

</div>


<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand the meaning of model coefficients in the case of a binary predictor.</li>
<li>Be able to state the assumptions underlying a linear model.</li>
<li>Understand how to assess if a fitted model satisfies the linear model assumptions.</li>
<li>Understand how to use transformations when the model violates assumptions.</li>
</ol>
</div>
<div id="research-question" class="section level1">
<h1>Research question</h1>
<p><em>Do distracting colours influence reaction times?</em></p>
<p>A group of students wanted to answer the above research question. To do so, they designed a standard computerized game and a second version with distracting colours. Time to completion and game type was recorded for each study participant. See the data description below.</p>
<div class="optional-begin">
Data: perfection.csv
</div>
<div class="optional-body">


<p><strong>Download link</strong></p>
<p><a href="https://uoepsy.github.io/data/perfection.csv">Download the data here</a></p>
<p><strong>Description</strong></p>
<p>A group of students wanted to investigate the impact of colour distracters on game-completion time.
They hypothesized a slower completion time for those playing a game with distracting colours, as a consequence of the widely known <em>Stroop effect</em> <span class="citation">(Stroop <a href="#ref-Stroop1935" role="doc-biblioref">1935</a>)</span>.</p>
<p>Students created two computer versions of the Perfection game.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>
In one version of the computerised game, the “standard” game type, all pegs and shapes would be of the same colour.
In the other version of the game, the “colour” game type, pegs and shapes did not have matching colours, hence there was a colour distracter effect.
The task was to click and drag each peg to the space with the matching shape.</p>
<p>They randomly recruited 40 students from the university. Half were randomly assigned to the standard game and the other half to the colour distracter version.
All participants would play in similar conditions: same location and similar background noise to control for possible distractions.</p>
<div class="figure" style="text-align: center"><span id="fig:dc-perfection-image"></span>
<img src="images/perfection.png" alt="Electronic Perfection game with and without colour distracters. The instructions for the game were to click and drag each peg to the space with the matching shape." width="60%" />
<p class="caption">
Figure 1: Electronic Perfection game with and without colour distracters. The instructions for the game were to click and drag each peg to the space with the matching shape.
</p>
</div>
<p>The following variables were collected:</p>
<ul>
<li><code>student_id</code>: Identifier for each student</li>
<li><code>type</code>: game type: Standard or Colour</li>
<li><code>time</code>: time (in seconds) from the start of the game to completion</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data, provided by <span class="citation">Kuiper and Sklar (<a href="#ref-Kuiper2012" role="doc-biblioref">2012</a>)</span>, are:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
student_id
</th>
<th style="text-align:center;">
type
</th>
<th style="text-align:center;">
time
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
Standard
</td>
<td style="text-align:center;">
38
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
Colour
</td>
<td style="text-align:center;">
36
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
Colour
</td>
<td style="text-align:center;">
42
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
Standard
</td>
<td style="text-align:center;">
35
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
Standard
</td>
<td style="text-align:center;">
32
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
Colour
</td>
<td style="text-align:center;">
37
</td>
</tr>
</tbody>
</table>
</div>
<p class="optional-end">
</p>
</div>
<div id="data-exploration" class="section level1">
<h1>Data exploration</h1>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Read the perfection data into R and name the data frame <code>perfection</code>.</p>
<p>Check for the correct encoding of all variables — that is, categorical variables should be factors and numeric variables should be numeric.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<pre class="r"><code>library(tidyverse)

perfection &lt;- read_csv(&#39;https://uoepsy.github.io/data/perfection.csv&#39;)
head(perfection)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   student_id type      time
##        &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;
## 1          1 Standard    38
## 2          2 Colour      36
## 3          3 Colour      42
## 4          4 Standard    35
## 5          5 Standard    32
## 6          6 Colour      37</code></pre>
<p>Game type is a categorical variable but is encoded as a character (<code>&lt;chr&gt;</code>) variable rather than a factor.
Let’s fix it:</p>
<pre class="r"><code>perfection &lt;- perfection %&gt;%
  mutate(type = as.factor(type))

head(perfection)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   student_id type      time
##        &lt;dbl&gt; &lt;fct&gt;    &lt;dbl&gt;
## 1          1 Standard    38
## 2          2 Colour      36
## 3          3 Colour      42
## 4          4 Standard    35
## 5          5 Standard    32
## 6          6 Colour      37</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Identify the units, the population to which conclusions can be generalised to, the explanatory variable and the response variable. Also classify the variables according to their type.</p>
<p>Is this study an experiment or an observational study?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<p>Units: each student.</p>
<p>Population: set of all students at this university who would be willing to be part of the study.</p>
<p>Explanatory variable: type of game (standard or with a colour distracter). Type: categorical.</p>
<p>Response variable: the completion time (in seconds). Type: quantitative.</p>
<p>This study is an experiment, since students were randomly allocated to one of the two types of games.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Display and describe the marginal distribution of game type.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<p>Type of game played is a categorical variable, hence we visualise it, for example, with a bar plot:</p>
<pre class="r"><code>ggplot(perfection, aes(x = type)) +
  geom_bar()</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-4-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>perfection %&gt;%
  group_by(type) %&gt;%
  summarise(n = n())</code></pre>
<pre><code>## # A tibble: 2 x 2
##   type         n
##   &lt;fct&gt;    &lt;int&gt;
## 1 Colour      20
## 2 Standard    20</code></pre>
<div class="int">
<p>The forty students were evenly split at random into either a colour distracter or standard game.
Each group consisted of 20 students.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Display and describe the marginal distribution of completion times.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<pre class="r"><code>ggplot(perfection, aes(x = time)) +
  geom_density() +
  geom_boxplot(width = 1/100)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-5-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>perfection %&gt;%
  summarise(M = mean(time),
            SD = sd(time))</code></pre>
<pre><code>## # A tibble: 1 x 2
##       M    SD
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  36.8  3.71</code></pre>
<div class="int">
<p>The distribution completion times appears to be unimodal, centred at approximately 37 seconds, with a SD of roughly 4 seconds.</p>
<p>The boxplot does not highlight any outliers.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Display and describe the relationship between game type and completion times.</p>
<p>Does it look like the groups have equal mean or spread? Are there any extreme observations?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<p>There are many correct way to investigate the distribution of completion times by group.</p>
<p><strong>Option 1: Boxplots by group</strong></p>
<pre class="r"><code>ggplot(perfection, aes(x = type, y = time)) +
  geom_boxplot()</code></pre>
<div class="figure" style="text-align: center"><span id="fig:perfection-boxplots"></span>
<img src="04_slr_assumptions_files/figure-html/perfection-boxplots-1.png" alt="Boxplots of competion times by game type." width="60%" />
<p class="caption">
Figure 2: Boxplots of competion times by game type.
</p>
</div>
<p><strong>Option 2: Dotplots by group</strong></p>
<pre class="r"><code>ggplot(perfection, aes(x = type, y = time)) +
  geom_dotplot(binaxis = &#39;y&#39;)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:perfection-dotplots"></span>
<img src="04_slr_assumptions_files/figure-html/perfection-dotplots-1.png" alt="Dotplots of competion times by game type." width="60%" />
<p class="caption">
Figure 3: Dotplots of competion times by game type.
</p>
</div>
<p><strong>Option 3: Histograms by group</strong></p>
<pre class="r"><code>ggplot(perfection, aes(x = time)) +
  geom_histogram(binwidth = 1, color = &#39;white&#39;) +
  facet_grid(rows = vars(type))</code></pre>
<div class="figure" style="text-align: center"><span id="fig:perfection-histograms"></span>
<img src="04_slr_assumptions_files/figure-html/perfection-histograms-1.png" alt="Histograms of competion times for each game type." width="60%" />
<p class="caption">
Figure 4: Histograms of competion times for each game type.
</p>
</div>
<p><strong>And many other options…</strong></p>
<p>The summary statistics by group can be computed as follows:</p>
<pre class="r"><code>stats_time &lt;- perfection %&gt;%
  group_by(type) %&gt;%
  summarise(n = n(),
            mean_time = mean(time), 
            sd_time = sd(time))

stats_time</code></pre>
<pre><code>## # A tibble: 2 x 4
##   type         n mean_time sd_time
##   &lt;fct&gt;    &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 Colour      20      38.1    3.65
## 2 Standard    20      35.6    3.39</code></pre>
<p>The summary statistics of completion time by group are as follows:</p>
<ul>
<li>Colour distracter group: <span class="math inline">\(n_1 = 20\)</span>, <span class="math inline">\(\bar y_1 = 38.10\)</span>, <span class="math inline">\(s_1 = 3.65\)</span></li>
<li>Standard group: <span class="math inline">\(n_2 = 20\)</span>, <span class="math inline">\(\bar y_2 = 35.55\)</span>, <span class="math inline">\(s_2 = 3.39\)</span></li>
</ul>
<p>We can write up these results as follows:</p>
<div class="int">
<p>The dotplots of completion time by type of game played (Figure <a href="#fig:perfection-dotplots">3</a>) show that the response distribution is fairly symmetric and bell-shaped in both groups.
Furthermore, the spread (standard deviation) of the two distributions appears to be similar.</p>
<p>The boxplots in Figure <a href="#fig:perfection-boxplots">2</a> do not highlight any outliers. They suggest a higher mean completion time in the colour distracter group (<span class="math inline">\(\bar y_1 = 38.10\)</span>s) than the standard group (<span class="math inline">\(\bar y_2 = 35.55\)</span>s). The standard deviation of completion time in the colour distracter group (<span class="math inline">\(s_1 = 3.65\)</span>s) is similar to that in the standard group (<span class="math inline">\(s_2 = 3.39\)</span>s).</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="model-specification-and-fitting" class="section level1">
<h1>Model specification and fitting</h1>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>The researchers hope to determine if distracting colours could impact response times when playing a computerised version of the Perfection game.</p>
<p>Write out in words and in symbols appropriate null and alternative hypothesis for the research question of interest.</p>
<p>Use a two-sided alternative.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<p>Let <span class="math inline">\(\mu_1\)</span> represent the true mean response time of the colour group and <span class="math inline">\(\mu_2\)</span> the true mean response time of the standard group.</p>
<ul>
<li><p>Null hypothesis: <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> (the mean completion time for the colour distracter game is equal to the mean completion time for the standard game).</p></li>
<li><p>Alternative hypothesis: <span class="math inline">\(H_0: \mu_1 \neq \mu_2\)</span> (the mean completion time for the colour distracter game is not equal to the mean completion time for the standard game).</p></li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Using the <code>t.test()</code> function, compute a statistical test against the null hypothesis specified above.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<pre class="r"><code>var.test(time ~ type, data = perfection)</code></pre>
<pre><code>## 
##  F test to compare two variances
## 
## data:  time by type
## F = 1.1592, num df = 19, denom df = 19, p-value = 0.7508
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.4588131 2.9285830
## sample estimates:
## ratio of variances 
##           1.159169</code></pre>
<pre class="r"><code>t_res &lt;- t.test(time ~ type, data = perfection, var.equal = TRUE)
t_res</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  time by type
## t = 2.2862, df = 38, p-value = 0.02791
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.2920254 4.8079746
## sample estimates:
##   mean in group Colour mean in group Standard 
##                  38.10                  35.55</code></pre>
<div class="int">
<p>We performed a two-sample t-test against the null hypothesis of equal mean completion time for the colour distracter and standard games.</p>
<p>At the 5% significance level, the observed difference in mean completion time between the colour distracter and standard game is significantly different from 0 (<span class="math inline">\(t(38) = 2.29\)</span>, <span class="math inline">\(p = 0.028\)</span>, two-sided).</p>
<p>The sample data provide strong evidence that, on average, the time taken to complete the game with distracting colour is different from the standard game.</p>
</div>
<p>To comment on the magnitude of this observed difference in the population means we must resort to the confidence interval: <span class="math inline">\([0.29, 4.81]\)</span>.</p>
<div class="int">
<p>We are 95% confident that participants taking the colour distracter game take between 0.29 and 4.81 seconds longer to complete the game, on average, than those taking the standard game.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Using the linear model function, <code>lm()</code>, fit the following linear model to the perfection data:
<span class="math display">\[
Time = \beta_0 + \beta_1 \ Type + \epsilon
\]</span></p>
<p>Write down the equation of the fitted line.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<pre class="r"><code>mdl_perf &lt;- lm(time ~ 1 + type, data = perfection)
summary(mdl_perf)</code></pre>
<pre><code>## 
## Call:
## lm(formula = time ~ 1 + type, data = perfection)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -7.100 -2.550  0.175  2.038  7.900 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   38.1000     0.7887  48.308   &lt;2e-16 ***
## typeStandard  -2.5500     1.1154  -2.286   0.0279 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.527 on 38 degrees of freedom
## Multiple R-squared:  0.1209, Adjusted R-squared:  0.09778 
## F-statistic: 5.227 on 1 and 38 DF,  p-value: 0.02791</code></pre>
<p>The fitted model is:
<span class="math display">\[
\widehat{Time} = 38.1 - 2.55 \ Type
\]</span></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>At the 5% significance level, are the regression coefficients significantly different from zero?</p>
<p>Is the model useful in explaining variability of completion times?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<p>At the 5% significance level, both intercept and slope are significantly different from zero.</p>
<p>The F-statistic for model utility, in the case of simple linear regression, is simply the square t-statistic for the slope.
The model involving game type as a predictor explains a significant amount of the variability in the response. That is, type of game played is a significant predictor of game completion time.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Do you notice any similarities between the t-test and the coefficients of the fitted linear model?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<p>Consider the again the <code>t.test()</code> output and the <code>lm()</code> output:</p>
<pre class="r"><code>t_res</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  time by type
## t = 2.2862, df = 38, p-value = 0.02791
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.2920254 4.8079746
## sample estimates:
##   mean in group Colour mean in group Standard 
##                  38.10                  35.55</code></pre>
<pre class="r"><code>summary(mdl_perf)</code></pre>
<pre><code>## 
## Call:
## lm(formula = time ~ 1 + type, data = perfection)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -7.100 -2.550  0.175  2.038  7.900 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   38.1000     0.7887  48.308   &lt;2e-16 ***
## typeStandard  -2.5500     1.1154  -2.286   0.0279 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.527 on 38 degrees of freedom
## Multiple R-squared:  0.1209, Adjusted R-squared:  0.09778 
## F-statistic: 5.227 on 1 and 38 DF,  p-value: 0.02791</code></pre>
<p>In the t-test, <code>mean in group Colour</code> = 38.10 corresponds to the estimate intercept of the linear model, <span class="math inline">\(\hat \beta_0 = 38.10\)</span>.</p>
<p>In the t-test, <code>mean in group Standard</code> = 35.55 corresponds to the estimated intercept plus slope in the linear model:
<span class="math display">\[
\begin{matrix}
35.55 &amp;=&amp; 38.10 &amp;-&amp;2.55 \\
\bar y_2 &amp;=&amp; \hat \beta_0 &amp;+&amp; \hat \beta_1 \\
\bar y_2 &amp;=&amp; \bar y_1 &amp;+&amp; \hat \beta_1
\end{matrix}
\]</span></p>
<p>This means that <span class="math inline">\(x = 1\)</span> for the standard group (group 2) and <span class="math inline">\(x = 0\)</span> for the colour distracter group.</p>
<div class="yellow">
<p>When dealing with a factor, R selects <strong>the first level in alphabetical order</strong> to be the <strong>reference level</strong> and <span class="math inline">\(\hat \beta_0\)</span> predicts the group mean of the reference level.</p>
<p>To do so, R internally denotes the two groups by a binary indicator variable <span class="math inline">\(x\)</span>. It can take only two possible values: zero or one. When <span class="math inline">\(x=0\)</span>, we are dealing with the reference group, while when <span class="math inline">\(x = 1\)</span> we are dealing with the other group.</p>
<p>The estimated slope <span class="math inline">\(\hat \beta_1\)</span> represents the predicted difference in the means between the other group and the reference group.</p>
<p>Hence, testing if <span class="math inline">\(\mu_2 - \mu_1 = 0\)</span> is equivalent to testing if <span class="math inline">\(\beta_1 = 0\)</span>.</p>
</div>
<p>This is clearer when exploring the predictions from the fitted model <span class="math inline">\(\hat y = \hat \beta_0 + \hat \beta_1 x\)</span> for the possible values of <span class="math inline">\(x\)</span>:
<span class="math display">\[
\begin{aligned}
x = 0: \qquad &amp;\hat y = \hat \beta_0 + \hat \beta_1 \cdot 0 = \hat \beta_0\\
x = 1: \qquad &amp;\hat y = \hat \beta_0 + \hat \beta_1 \cdot 1 = \hat \beta_0 + \hat \beta_1 
\end{aligned}
\]</span></p>
<p>The <code>t-test</code> statistic, and the <code>lm()</code> t-statistic are equivalent in absolute value.
The p-value is identical.
Furthermore, the <code>lm()</code> F-statistic, 5.227, is the square of t-statistic, and the p-value is also identical.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Interpret the intercept and slope of the fitted regression model.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<p>Intercept</p>
<div class="int">
<p>The estimated average completion time for those taking the colour distracter game is 38.10 seconds.</p>
</div>
<p>Slope</p>
<div class="int">
<p>The estimated difference in average completion times between those taking the standard game and the colour distracter one is -2.55 seconds. As the difference is negative, the colour distracter group is has a higher estimated average completion time.</p>
<p>Equivalently, those taking the standard game will take on average 2.55 seconds less than those taking the colour distracter game.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="assumptions-check" class="section level1">
<h1>Assumptions check</h1>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Check if the fitted model satisfies the linearity assumption.</p>
<p><em><strong>Hint:</strong> An equivalent way to assess this is to check that the errors have a mean of zero. That is, there is no residual pattern and the systematic trend has entirely been captured by the linear model.</em></p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<pre class="r"><code>plot(mdl_perf, 1)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-11-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>perfection_check &lt;- perfection %&gt;%
  mutate(
    time_hat = predict(mdl_perf),
    resid = time - time_hat,
  )
ggplot(perfection_check, aes(x = type, y = resid)) +
  geom_violin(width = 0.5, draw_quantiles = TRUE)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-12-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Check if the fitted model satisfies the independent errors assumption.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<pre class="r"><code>car::durbinWatsonTest(mdl_perf)</code></pre>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1      0.05821787      1.805711   0.522
##  Alternative hypothesis: rho != 0</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Check if the fitted model satisfies the normality of the errors assumption.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<pre class="r"><code>hist(residuals(mdl_perf), breaks = 15)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-14-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>plot(mdl_perf, which = 2)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-14-2.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Check if the fitted model satisfies the equal variance assumption.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<pre class="r"><code>car::ncvTest(mdl_perf)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 0.1086857, Df = 1, p = 0.74165</code></pre>
<pre class="r"><code>plot(mdl_perf, which = 3)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-15-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-Kuiper2012">
<p>Kuiper, Shonda, and Jeff Sklar. 2012. <em>Practicing Statistics: Guided Investigations for the Second Course</em>. Pearson Higher Ed.</p>
</div>
<div id="ref-Stroop1935">
<p>Stroop, J Ridley. 1935. “Studies of Interference in Serial Verbal Reactions.” <em>Journal of Experimental Psychology</em> 18 (6): 643–62.</p>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>
Perfection is a popular game in which a person is expected to place an assortment of shaped pegs into the matching spaces.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
