<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Writing-up</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Simple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_models.html">Lab 1: Functions and models</a>
    </li>
    <li class="dropdown-header">Lab 2: Simple linear regression</li>
    <li class="dropdown-header">Lab 3: Model Fit, Standardized Coefficients</li>
    <li class="dropdown-header">Lab 4: Assumptions &amp; Diagnostics</li>
    <li class="dropdown-header">Lab 5: Writing-up</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multiple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lab 6: Basics</li>
    <li class="dropdown-header">Lab 7: Interactions</li>
    <li class="dropdown-header">Lab 8: Assumptions &amp; Diagnostics</li>
    <li class="dropdown-header">Lab 9: Model Fit, Model Comparison, Model Selection</li>
    <li class="dropdown-header">Lab 10: Writing-up</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Experimental Data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lab 11: ANOVA</li>
    <li class="dropdown-header">Lab 12: Sum-to-zero contrasts</li>
    <li class="dropdown-header">Lab 13: 2x2 ANOVA</li>
    <li class="dropdown-header">Lab 14: Multiple Comparisons</li>
    <li class="dropdown-header">Lab 15: Write-up</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lab 16: Logistic Regression</li>
    <li class="dropdown-header">Lab 17: Bootstrap</li>
    <li class="dropdown-header">Lab 18: Power</li>
    <li class="dropdown-header">Lab 19: Common tests as LM</li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="00_intro.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Writing-up</h1>

</div>


<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand the difference between outliers and influential points.</li>
<li>Understand and apply methods to detect outliers and influential points.</li>
<li>Comment on the issues of correlation vs causation and generalisability of the sample results.</li>
<li>Run a full simple regression analysis from start to finish and to correctly interpret the results.</li>
</ol>
</div>
<div id="data-and-research-question" class="section level1">
<h1>Data and research question</h1>
<p>A school is interested in investigating how children’ performance is affected by anxiety.</p>
<p>Consider the following data on anxiety and academic performance for a sample of 100 children.</p>
<div class="optional-begin">
Data: anx_perf.csv<span id="opt-start-11" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-11&#39;, &#39;opt-start-11&#39;)"></span>
</div>
<div class="optional-body" id = "opt-body-11" style="display: none;">


<p><strong>Download link</strong></p>
<p><a href="https://uoepsy.github.io/data/anx_perf.csv">Download the data here</a></p>
<p><strong>Description</strong></p>
<p>Level of anxiety and academic performance were measured for one hundred children randomly selected from Green Tree primary school, a hypothetical school.</p>
<p>The measured variables were:</p>
<ul>
<li><code>anxiety</code>: pupils’ anxiety score</li>
<li><code>performance</code>: pupils’ academic performance score</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
anxiety
</th>
<th style="text-align:center;">
performance
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;width: 10em; ">
17.0
</td>
<td style="text-align:center;width: 10em; ">
19.97
</td>
</tr>
<tr>
<td style="text-align:center;width: 10em; ">
10.2
</td>
<td style="text-align:center;width: 10em; ">
10.27
</td>
</tr>
<tr>
<td style="text-align:center;width: 10em; ">
26.4
</td>
<td style="text-align:center;width: 10em; ">
43.99
</td>
</tr>
<tr>
<td style="text-align:center;width: 10em; ">
25.4
</td>
<td style="text-align:center;width: 10em; ">
38.58
</td>
</tr>
<tr>
<td style="text-align:center;width: 10em; ">
16.4
</td>
<td style="text-align:center;width: 10em; ">
22.78
</td>
</tr>
<tr>
<td style="text-align:center;width: 10em; ">
12.2
</td>
<td style="text-align:center;width: 10em; ">
12.67
</td>
</tr>
</tbody>
</table>
</div>
<p class="optional-end">
</p>
</div>
<div id="analysis" class="section level1">
<h1>Analysis</h1>
<p>In today’s lab the analysis will be provided, the task will be for you to correctly report what has been done.</p>
<p>Read the data:</p>
<pre class="r"><code>library(tidyverse)
library(car)

anxperf &lt;- read_csv(file = &#39;https://uoepsy.github.io/data/anx_perf.csv&#39;)
head(anxperf)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   anxiety performance
##     &lt;dbl&gt;       &lt;dbl&gt;
## 1    17          20.0
## 2    10.2        10.3
## 3    26.4        44.0
## 4    25.4        38.6
## 5    16.4        22.8
## 6    12.2        12.7</code></pre>
<p>Investigate the marginal distributions of each variable and the relationship between the two variables.</p>
<p><strong>Note:</strong> The patchwork library is used to combine ggplots into a single figure made up of multiple panels. You can add them using <code>+</code> or <code>|</code>, and put plots underneath with the <code>/</code> operator.</p>
<pre class="r"><code>library(patchwork)

plt_anx &lt;- ggplot(anxperf, aes(x = anxiety)) +
  geom_density() +
  geom_boxplot(width = 0.01)

plt_perf &lt;- ggplot(anxperf, aes(x = performance)) +
  geom_density() +
  geom_boxplot(width = 0.01)

plt_joint &lt;- ggplot(anxperf, aes(x = anxiety, y = performance)) +
  geom_point() +
  labs(x = &#39;Anxiety score&#39;, y = &#39;Performance score&#39;)

plt_anx | plt_perf | plt_joint</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-3-1.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>anxperf %&gt;%
  summarise(M_anx = mean(anxiety), 
            SD_anx = sd(anxiety),
            MED_anx = median(anxiety), 
            IQR_anx = IQR(anxiety),
            M_perf = mean(performance), 
            SD_perf = sd(performance),
            MED_perf = median(performance), 
            IQR_perf = IQR(performance))</code></pre>
<pre><code>## # A tibble: 1 x 8
##   M_anx SD_anx MED_anx IQR_anx M_perf SD_perf MED_perf IQR_perf
##   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1  20.4   5.49    19.6    9.15   32.4    17.4     28.5     24.0</code></pre>
<p>Correlation between the variables:</p>
<pre class="r"><code>cor(anxperf)</code></pre>
<pre><code>##               anxiety performance
## anxiety     1.0000000   0.8098636
## performance 0.8098636   1.0000000</code></pre>
<p>Linear model:</p>
<pre class="r"><code>mdl1 &lt;- lm(performance ~ 1 + anxiety, data = anxperf)
summary(mdl1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = performance ~ 1 + anxiety, data = anxperf)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -56.754  -4.594  -1.003   3.251  33.005 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -19.8039     3.9512  -5.012 2.39e-06 ***
## anxiety       2.5624     0.1875  13.667  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.24 on 98 degrees of freedom
## Multiple R-squared:  0.6559, Adjusted R-squared:  0.6524 
## F-statistic: 186.8 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="green">
<p><strong>TIP</strong></p>
<p>When you call <code>plot()</code> on a fitted model to show the diagnostic plots, you can display all four plots at once by telling R</p>
<pre class="r"><code>par(mfrow = c(2,2))</code></pre>
<p>This means that each figure should be made of 2 by 2 plots.</p>
<p>To go back to one figure made by a single plot, just type&quot;</p>
<pre class="r"><code>par(mfrow = c(1,1))</code></pre>
<p><strong>Note that this will not work with ggplot.</strong></p>
</div>
<p>Diagnostics:</p>
<pre class="r"><code>par(mfrow = c(2,2))
plot(mdl1)</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-9-1.png" width="90%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>im &lt;- influence.measures(mdl1)
summary(im)</code></pre>
<pre><code>## Potentially influential observations of
##   lm(formula = performance ~ 1 + anxiety, data = anxperf) :
## 
##    dfb.1_  dfb.anxt dffit   cov.r   cook.d  hat    
## 2   0.08   -0.07     0.08    1.06_*  0.00    0.04  
## 8  -0.37    0.48     0.59_*  0.84_*  0.16    0.03  
## 19 -0.17    0.24     0.35    0.92_*  0.06    0.02  
## 41  1.43_* -1.67_*  -1.82_*  0.48_*  1.11_*  0.06_*
## 52  0.04   -0.04     0.04    1.07_*  0.00    0.04  
## 63  0.41   -0.33     0.47_*  0.84_*  0.10    0.02  
## 87 -0.50    0.61     0.71_*  0.84_*  0.22    0.04</code></pre>
<p>Focus on Cook’s distance for now:</p>
<pre class="r"><code>anxperf &lt;- anxperf %&gt;%
    slice(-41)</code></pre>
<p>Re-fit the model and check assumptions:</p>
<pre class="r"><code>mdl2 &lt;- lm(performance ~ 1 + anxiety, data = anxperf)
summary(mdl2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = performance ~ 1 + anxiety, data = anxperf)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.873  -4.902  -1.587   2.984  33.137 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -24.4249     3.3066  -7.387 5.26e-11 ***
## anxiety       2.8192     0.1581  17.836  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.398 on 97 degrees of freedom
## Multiple R-squared:  0.7663, Adjusted R-squared:  0.7639 
## F-statistic: 318.1 on 1 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>par(mfrow = c(2,2))
plot(mdl2)</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-13-1.png" width="90%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ncvTest(mdl2)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 12.37983, Df = 1, p = 0.000434</code></pre>
<p>Try transforming the response:</p>
<pre class="r"><code>anxperf &lt;- anxperf %&gt;%
    mutate(log_performance = log(performance))

mdl3 &lt;- lm(log_performance ~ 1 + anxiety, data = anxperf)
summary(mdl3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log_performance ~ 1 + anxiety, data = anxperf)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.38616 -0.12918 -0.02290  0.09671  1.07349 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1.464804   0.084408   17.35   &lt;2e-16 ***
## anxiety     0.092902   0.004035   23.02   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2144 on 97 degrees of freedom
## Multiple R-squared:  0.8453, Adjusted R-squared:  0.8437 
## F-statistic: 530.1 on 1 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>par(mfrow = c(2,2))
plot(mdl3)</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-16-1.png" width="90%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(mdl3$residuals)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  mdl3$residuals
## W = 0.9134, p-value = 7.033e-06</code></pre>
<p>Try removing outlier:</p>
<pre class="r"><code>anxperf &lt;- anxperf %&gt;%
    slice(-62)</code></pre>
<pre class="r"><code>mdl4 &lt;- lm(log_performance ~ 1 + anxiety, data = anxperf)
summary(mdl4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log_performance ~ 1 + anxiety, data = anxperf)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.3795 -0.1141 -0.0205  0.1008  0.5020 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1.412733   0.073345   19.26   &lt;2e-16 ***
## anxiety     0.094929   0.003497   27.14   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1849 on 96 degrees of freedom
## Multiple R-squared:  0.8847, Adjusted R-squared:  0.8835 
## F-statistic: 736.7 on 1 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>par(mfrow = c(2,2))
plot(mdl4)</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-18-1.png" width="90%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(mdl4$residuals)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  mdl4$residuals
## W = 0.97992, p-value = 0.1395</code></pre>
<pre class="r"><code>ncvTest(mdl4)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 0.1958679, Df = 1, p = 0.65808</code></pre>
<p>Go back to figures with only one plot:</p>
<pre class="r"><code>par(mfrow = c(1,1))</code></pre>
<p>Table for reporting:</p>
<pre class="r"><code>library(sjPlot)
tab_model(mdl4)</code></pre>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
log performance
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.41
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.27 – 1.56
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
anxiety
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.09
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.09 – 0.10
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
98
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.885 / 0.884
</td>
</tr>
</table>
<p>Plot of the final model:</p>
<pre class="r"><code>betas &lt;- coef(mdl4)

ggplot(anxperf, aes(x = anxiety, y = log_performance)) +
  geom_point() +
  geom_abline(intercept = betas[1], slope = betas[2], color = &#39;blue&#39;) +
  labs(x = &#39;Anxiety score&#39;, y = &#39;Performance score (in log-scale)&#39;)</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-21-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<div id="reporting" class="section level1">
<h1>Reporting</h1>
<p>A good data analysis report should follow three steps: <em>Think, Show, and Tell.</em></p>
<p>For a detailed explanation of each step, check this <a href="https://uoepsy.github.io/files/writeup_guide.pdf" target="_blank">document.</a></p>
<div id="think" class="section level2">
<h2>Think</h2>
<div class="yellow">
<p>What do you know? What do you hope to learn? What did you learn during the exploratory analysis?</p>
</div>
<div class="question-begin">
1: Describe design
</div>
<div class="question-body">
<p>Describe the study design, the data collection strategy, etc.</p>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<p>The data consist of measurements of anxiety and academic performance scores for a random sample of 100 children from Green Tree primary school.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
2: Describe the data
</div>
<div class="question-body">
<ul>
<li>How many observational units? (If not mentioned above.)</li>
<li>Are there any observations that have been excluded based on pre-defined criteria? How/why, and how many?</li>
<li>Describe and visualise the variables of interest. How are they scored? have they been transformed at all?</li>
<li>Describe and visualise relationships between variables. Report covariances/correlations.</li>
</ul>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<div class="figure" style="text-align: center"><span id="fig:marg-distrib"></span>
<img src="05_slr_writeup_files/figure-html/marg-distrib-1.png" alt="Marginal and joint distributions." width="100%" />
<p class="caption">
Figure 1: Marginal and joint distributions.
</p>
</div>
<p>The distribution of anxiety scores appears to be roughly symmetric around the mean anxiety score of 20.4, with standard deviation 5.49.
The boxplot in Figure <a href="#fig:marg-distrib">1</a>(a) does not highlight any evident outliers.</p>
<p>The distribution of performance scores appears to be right skewed, with median performance score 28.5, and interquartile range 24.
A boxplot of the distribution, Figure <a href="#fig:marg-distrib">1</a>(b), flags two potential outliers which are worth keeping an eye on, but have not been removed from the dataset.</p>
<p>Finally, the scatterplot in Figure <a href="#fig:marg-distrib">1</a>(c) displays the relationship between anxiety and performance score. There appears to be a strong (<span class="math inline">\(r_{Anxiety, Performance} = 0.81\)</span>), positive linear relationship between the two variables.
The scatterplot also highlights a couple of points which do not fit with the rest of the data. One has a high anxiety score but an unusually low performance score, and another point having an anxiety score of approximately 15 and a performance score of approximately 50, which is 25 scores above the rest of the points.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
3: Describe the analytical approach
</div>
<div class="question-body">
<ul>
<li>What type of statistical analysis do you use to answer the research question? (e.g., t-test, simple linear regression,
multiple linear regression)</li>
<li>Describe the model/analysis structure</li>
<li>What is your outcome variable? What is its type?</li>
<li>What are your predictors? What are their types?</li>
<li>Any other specifics?</li>
</ul>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<p>We want to investigate whether children’ performance is affected by anxiety and what is the intensity of that relationship.</p>
<p>To do so, we will use a simple linear regression model involving two numeric variables: anxiety (the predictor) and performance (the response).</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
4: Planned analysis vs actual analysis
</div>
<div class="question-body">
<ul>
<li>Was there anything you had to do differently than planned during the analysis? Did the modelling highlight issues in your data?</li>
<li>Did you have to do anything (e.g., transform any variables, exclude any observations) in order to meet assumptions?</li>
</ul>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<p>Such model, however, highlighted one influential observation (namely, case 41) having a Cook’s distance of 1.11.
Careful inspection of case 41 showed a high anxiety score (33), far from the average anxiety score (20.4) — hence, the point has high leverage. Furthermore, the point was an outlier as the actual performance score was 8, which was roughly 57 points lower than the model-predicted value.</p>
<p>After removing such observation from the dataframe and re-fitting the linear model, the diagnostic plots raised concerns about the normality and equal variance assumptions not being satisfied.</p>
<p>The Normal quantile plot showed that the distribution of the residuals was skewed to the right, and the Scale-Location plot displayed a thickening pattern (that is, a fan-shape) rather than a roughly constant vertical spread.</p>
<p>To mitigate the violation of the equal variance assumption, we log transformed the response variable.</p>
<p>After refitting the model, the diagnostic plots only raised concern about a single point (case 62) not fitting the linear pattern in the Normal quantile plot, and also being particularly unusual in the Residuals vs Fitted values plot.</p>
<p>The Shapiro-Wilk test for normality of the errors showed a significant p-value, indicating violation of the normality assumption.</p>
<p>After careful inspection, and because the point was not unusual in x-value, we decided to remove case 62 from the dataset and re-fit the linear model.</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="show" class="section level2">
<h2>Show</h2>
<div class="yellow">
<p>Show the mechanics and visualisations which will support your conclusions</p>
</div>
<div class="question-begin">
5: Present and describe the final model
</div>
<div class="question-body">
<p>Present and describe the model or test which you deemed best to answer your question.</p>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<p>The final model which was chosen to answer the research question of interest was:
<span class="math display">\[
\widehat{\log (Performance)} = 1.41 + 0.0949 \ Anxiety
\]</span></p>
<p>and was fitted excluding cases 41 and 62. The former was found to be an influential point, while the latter an outlier affecting normality.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
6: Are the assumptions and conditions of your final test or model satisfied?
</div>
<div class="question-body">
<p>Are the assumptions and conditions of your final test or model satisfied?
<em>For the final model (the one you report results from), were all assumptions met? (Hopefully yes, or there is more work to do…). Include evidence (tests or plots).</em></p>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-22-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>The final model was found to not violate the regression assumptions. A plot of the residuals vs fitted values shows randomly scattered points with no pattern and a horizontal direction.</p>
<p>The Normal quantile plot (qq-plot) shows a roughly linear trend in the standardized residuals vs the normal quantiles.
We performed a Shapiro-Wilk test, at the 5% significance level, against the null hypothesis that the residuals came from a normal distribution (<span class="math inline">\(W = 0.98\)</span>, <span class="math inline">\(p = 0.14\)</span>).
The large <span class="math inline">\(W\)</span>-statistic leads to a p-value (0.14) larger than the 0.05 threshold.
Hence, the sample results do not provide sufficient evidence to reject the null hypothesis that the errors follow a normal distribution.</p>
<p>The Residuals vs Fitted plot and the Scale-Location plot show that the vertical spread of the residuals is roughly the same everywhere.</p>
<p>Hence, we see no violation of the constant variance assumption.
At the 5% significance level, we also performed a Breusch-Pagan test against the null hypothesis of homoscedasticity (<span class="math inline">\(\chi^2(1) = 0.196, p = 0.658\)</span>). The large p-value indicates that the sample results do not provide sufficient evidence to reject the null hypothesis of equal variance.</p>
<p>Finally, a plot of residuals vs leverage does not highlight any influential observations.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
7: Report your test or model results
</div>
<div class="question-body">
<ul>
<li>Provide a table of results if applicable (for regression tables, try <code>tab_model()</code> from the <strong>sjPlot</strong> package).</li>
<li>Provide plots if applicable.</li>
</ul>
<p class="question-end">
</p>
</div>
<div style="display:none;">
The table below displays the estimated regression coefficients along with the corresponding test of significance:
<center>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
log performance
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.41
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.27 – 1.56
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
anxiety
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.09
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.09 – 0.10
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
98
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.885 / 0.884
</td>
</tr>
</table>
</center>
<p><br>
The fitted model is displayed below:
<img src="05_slr_writeup_files/figure-html/unnamed-chunk-24-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
<div id="tell" class="section level2">
<h2>Tell</h2>
<div class="yellow">
<p>Communicate your findings</p>
</div>
<div class="question-begin">
8: Interpret your results in the context of your research question.
</div>
<div class="question-body">
<ul>
<li>What do your results suggest about your research question?</li>
<li>Make direct links from hypotheses to models (which bit is testing hypothesis)</li>
<li>Be specific - which statistic did you use/what did the statistical test say? Comment on effect sizes.</li>
<li>Make sure to include measurement units where applicable.</li>
</ul>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<p>The fitted model predicts log performance for a given anxiety score.
Both intercept (<span class="math inline">\(t(96) = 19.26, p &lt; .001\)</span>, two-sided) and slope (<span class="math inline">\(t(96) = 27.14, p &lt; .001\)</span>, two-sided) are significantly different from zero.</p>
<p>As an anxiety score of zero is meaningless and far from the allowed range of scores, the estimated intercept <span class="math inline">\(\hat \beta_0 = 1.41\)</span> has no meaning if not a practical one of where the line meets the y-axis.</p>
<p>The estimated slope, <span class="math inline">\(\hat \beta_1 = 0.0949\)</span>, indicates that, each unit increase in anxiety score is associated, on average, to a 0.0949 units increase in log performance.</p>
<p>That is, there is a positive/increasing linear relationship between anxiety and log performance. However, the magnitude of the rate of increase, even if significant, is small and in the order of 0.1.</p>
<p>The F-test for model utility is also significant (<span class="math inline">\(F(1,96) = 736.7, p &lt; .001\)</span>). At the 5% significance level, anxiety is a significant predictor of log performance.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<p>Approximately 88.5% of the variability in log performance scores is explained by the linear association with anxiety scores.</p>
</div>
<p class="solution-end">
</p>
</div>
</div>
<div id="put-everything-together" class="section level1">
<h1>Put everything together</h1>
<p>If you followed the steps above, it is just a matter of taking all answers to the above questions and combining them, in order to have a reasonable draft of a statistical report.</p>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>
This information, however, is equivalent to the t-test for the significance of the slope as the F-statistic is the square t-statistic.<a href="#fnref1" class="footnote-back">↩</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
