<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Model Fit, Comparison, and Selection</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">DAPR2</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Simple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lab 1: Functions and Models</li>
    <li class="dropdown-header">Lab 2: Simple Regression Basics</li>
    <li class="dropdown-header">Lab 3: Model Fit, Standardized Coefficients</li>
    <li class="dropdown-header">Lab 4: Assumptions &amp; Diagnostics</li>
    <li class="dropdown-header">Lab 5: Writing-up</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multiple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="06-mlr.html">Lab 6: Basics</a>
    </li>
    <li>
      <a href="07-mlr-int.html">Lab 7: Interactions</a>
    </li>
    <li>
      <a href="08-mlr-assumpt.html">Lab 8: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="09-mlr-select.html">Lab 9: Model Fit, Model Comparison, Model Selection</a>
    </li>
    <li>
      <a href="10-mlr-report.html">Lab 10: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Experimental Data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lab 11: ANOVA</li>
    <li class="dropdown-header">Lab 12: Sum-to-zero contrasts</li>
    <li class="dropdown-header">Lab 13: 2x2 ANOVA</li>
    <li class="dropdown-header">Lab 14: Multiple Comparisons</li>
    <li class="dropdown-header">Lab 15: Write-up</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lab 16: Logistic Regression</li>
    <li class="dropdown-header">Lab 17: Bootstrap</li>
    <li class="dropdown-header">Lab 18: Power</li>
    <li class="dropdown-header">Lab 19: Common tests as LM</li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    About
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="about.html">About the course</a>
    </li>
    <li>
      <a href="00-intro.html">Intro to R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Model Fit, Comparison, and Selection</h1>

</div>


<div class="red">
<p><strong>PRE-LAB ACTIVITIES</strong></p>
<p>Before attempting the lab please read ?.</p>
</div>
<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand measures of model fit using <span class="math inline">\(R^2\)</span> and F.<br />
</li>
<li>Understand the principles of model selection and how to compare models via <span class="math inline">\(R^2\)</span> and F tests.</li>
<li>Understand AIC and BIC.</li>
<li>Understand the basics of Backward elimination, Forward selection and stepwise regression.</li>
</ol>
</div>
<div id="model-fit" class="section level1">
<h1>Model Fit</h1>
<div class="frame">
<h2 id="adjusted-r2">Adjusted <span class="math inline">\(R^2\)</span></h2>
<p>We know from our work on simple linear regression that the R-squared can be obtained as:
<span class="math display">\[
R^2 = \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\]</span></p>
<p>However, when we add more and more predictors into a multiple regression model, <span class="math inline">\(SS_{Residual}\)</span> cannot increase, and may decrease by pure chance alone, even if the predictors are unrelated to the outcome variable. Because <span class="math inline">\(SS_{Total}\)</span> is constant, the calculation <span class="math inline">\(1-\frac{SS_{Residual}}{SS_{Total}}\)</span> will increase by chance alone.</p>
<p>An alternative, the Adjusted-<span class="math inline">\(R^2\)</span>, does not necessarily increase with the addition of more explanatory variables, by including a penalty according to the number of explanatory variables in the model. It is not by itself meaningful, but can be useful in determining what predictors to include in a model.
<span class="math display">\[
Adjusted{-}R^2=1-\frac{(1-R^2)(n-1)}{n-k-1} \\
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; n = \text{sample size} \\
&amp; k = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
<hr />
<p><strong>In R,</strong> you can view the mutiple and adjusted <span class="math inline">\(R^2\)</span> at the bottom of the output of <code>summary(&lt;modelname&gt;)</code>:</p>
<div class="figure" style="text-align: left"><span id="fig:mlroutputrsq"></span>
<img src="images/mlroutputrsq.png" alt="Multiple regression output in R, summary.lm(). R-squared highlighted" width="60%" />
<p class="caption">
Figure 1: Multiple regression output in R, summary.lm(). R-squared highlighted
</p>
</div>
</div>
<div class="frame">
<h2 id="f-ratio">F-ratio</h2>
<p>As in simple linear regression, the F-ratio is used to test the null hypothesis that all regression slopes are zero.</p>
<p>It is called the F-ratio because it is the ratio of the how much of the variation is explained by the model (per paramater) versus how much of the variation is unexplained (per remaining degrees of freedom).</p>
<p><span class="math display">\[
F_{df_{model},df_{residual}} = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model}/df_{Model}}{SS_{Residual}/df_{Residual}} \\
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; df_{model} = k \\
&amp; df_{error} = n-k-1 \\
&amp; n = \text{sample size} \\
&amp; k  = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
<hr />
<p><strong>In R,</strong> at the bottom of the output of <code>summary(&lt;modelname&gt;)</code>, you can view the F ratio, along with an hypothesis test against the alternative hypothesis that the at least one of the coefficients <span class="math inline">\(\neq 0\)</span> (under the null hypothesis that all coefficients = 0, the ratio of explained:unexplained variance should be approximately 1):</p>
<div class="figure" style="text-align: left"><span id="fig:mlroutputrf"></span>
<img src="images/mlroutputf.png" alt="Multiple regression output in R, summary.lm(). F statistic highlighted" width="60%" />
<p class="caption">
Figure 2: Multiple regression output in R, summary.lm(). F statistic highlighted
</p>
</div>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Run the code below. It reads in the wellbeing/rurality study data, and creates a new binary variable which specifies whether or not each participant lives in a rural location.</p>
<pre class="r"><code>library(tidyverse)
mwdata2&lt;-read_csv(&quot;data/wellbeing_rural.csv&quot;)
mwdata2 &lt;- 
  mwdata2 %&gt;% mutate(
  isRural = ifelse(location==&quot;rural&quot;,&quot;rural&quot;,&quot;notrural&quot;)
)
head(mwdata2)</code></pre>
<pre><code>## # A tibble: 6 x 8
##     age outdoor_time social_int routine wellbeing location steps_k isRural
##   &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;  
## 1    28           12         13       1        36 rural       21.6 rural  
## 2    56            5         15       1        41 rural       12.3 rural  
## 3    25           19         11       1        35 rural       49.8 rural  
## 4    60           25         15       0        35 rural       NA   rural  
## 5    19            9         18       1        32 rural       48.1 rural  
## 6    34           18         13       1        34 rural       67.3 rural</code></pre>
<p>Fits the following model, and assign it the name “wb_mdl1”.</p>
<ul>
<li><span class="math inline">\(\text{Wellbeing} = \beta_0 + \beta_1 \cdot \text{Social Interactions} + \beta_2 \cdot \text{IsRural} + \epsilon\)</span></li>
</ul>
<p>Does the model provide a better fit to the data than a model with no explanatory variables? (i.e., test against the alternative hypothesis that at least one of the explanatory variables significantly predicts wellbeing scores).</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-1" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-1&#39;, &#39;sol-start-1&#39;)"></span>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<pre class="r"><code>wb_mdl1 &lt;- lm(wellbeing ~ social_int + isRural, data=mwdata2)
summary(wb_mdl1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = wellbeing ~ social_int + isRural, data = mwdata2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.3711  -3.1794   0.1097   2.5407  17.6324 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  34.11591    1.07052  31.868  &lt; 2e-16 ***
## social_int    0.38167    0.08257   4.622 6.85e-06 ***
## isRuralrural -4.85152    0.66283  -7.319 6.18e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.664 on 197 degrees of freedom
## Multiple R-squared:  0.2593, Adjusted R-squared:  0.2517 
## F-statistic: 34.47 on 2 and 197 DF,  p-value: 1.453e-13</code></pre>
<div class="int">
<p>Weekly social interactions and location (rural vs not rural) explained 25.2% of the variance (adjusted <span class="math inline">\(R^2\)</span> =0.252, <span class="math inline">\(F\)</span>(2,197)=34.5, p&lt;.001)</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="model-comparison" class="section level1">
<h1>Model Comparison</h1>
<div class="frame">
<h2 id="incremental-f-test">Incremental F-test</h2>
<div class="yellow">
<p>If (<em>and only if</em>) two models are <strong>nested</strong> (one model contains all the predictors of the other and is fitted to the same data), we can compare them using an <strong>incremental F-test.</strong></p>
<p>This is a formal test of whether the additional predictors provide a better fitting model.<br />
Formally this is the test of:</p>
<ul>
<li><span class="math inline">\(H_0:\)</span> coefficients for the added/ommitted variables are all zero.</li>
<li><span class="math inline">\(H_1:\)</span> at least one of the added/ommitted variables has a coefficient that is not zero.</li>
</ul>
</div>
<p>The F-ratio for comparing the residual sums of squares between two models can be calculated as:</p>
<p><span class="math display">\[
F_{(df_R-df_F),df_F} = \frac{(SSR_R-SSR_F)/(df_R-df_F)}{SSR_F / df_F} \\
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; SSR_R = \text{residual sums of squares for the restricted model} \\
&amp; SSR_F = \text{residual sums of squares for the full model} \\
&amp; df_R = \text{residual degrees of freedom from the restricted model} \\
&amp; df_F = \text{residual degrees of freedom from the full model} \\
\end{align}
\]</span></p>
<hr />
<p><strong>In R,</strong> we can conduct an incremental F-test by constructing two models, and passing them to the <code>anova()</code> function: <code>anova(model1, model2)</code>.</p>
</div>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>The F-ratio you see at the bottom of <code>summary(model)</code> is actually a comparison between two models: your model (with some explanatory variables in predicting <span class="math inline">\(y\)</span>) and <strong>the null model.</strong> In regression, the null model can be thought of as the model in which all explanatory variables have zero regression coefficients. It is also referred to as the <strong>intercept-only model</strong>, because if all predictor variable coefficients are zero, then the only we are only estimating <span class="math inline">\(y\)</span> via an intercept (which will be the mean - <span class="math inline">\(\bar y\)</span>).</p>
<p>Use the code below to fit the null model.<br />
Then, use the <code>anova()</code> function to perform a model comparison between your earlier model (<strong>wb_mdl1</strong>) and the null model.<br />
Check that the F statistic is the same as that which is given at the bottom of <code>summary(wb_mdl1)</code>.</p>
<pre class="r"><code>null_model &lt;- lm(wellbeing ~ 1, data = mwdata2)</code></pre>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-2" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-2&#39;, &#39;sol-start-2&#39;)"></span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<pre class="r"><code># fit the null model
null_model &lt;- lm(wellbeing ~ 1, data = mwdata2)

# model comparison null vs wb_mdl1
anova(null_model, wb_mdl1)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Model 1: wellbeing ~ 1
## Model 2: wellbeing ~ social_int + isRural
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    199 5785.6                                  
## 2    197 4285.6  2      1500 34.475 1.453e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code># extract f statistic from summary of wb_mdl1
summary(wb_mdl1)$fstatistic</code></pre>
<pre><code>##     value     numdf     dendf 
##  34.47463   2.00000 197.00000</code></pre>
<pre class="r"><code># we can retrieve the p-value:
fstat = summary(wb_mdl1)$fstatistic[1]
df_1 = summary(wb_mdl1)$fstatistic[2]
df_2 = summary(wb_mdl1)$fstatistic[3]
pf(fstat, df_1, df_2, lower.tail = FALSE)</code></pre>
<pre><code>##        value 
## 1.452925e-13</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Does weekly outdoor time explain a significant amount of variance in wellbeing scores over and above weekly social interactions and location (rural vs not-rural)?</p>
<p>Provide an answer to this question by fitting and comparing two models (one of them you may already have fitted in an earlier question).</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-3" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-3&#39;, &#39;sol-start-3&#39;)"></span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>We can compare the following models which predict wellbeing scores from weekly social interactions and location, with and without weekly outdoor time.</p>
<ul>
<li><span class="math inline">\(\text{Wellbeing} = \beta_0 + \beta_1 \cdot \text{Social Interactions} + \beta_2 \cdot \text{IsRural} + \epsilon\)</span></li>
<li><span class="math inline">\(\text{Wellbeing} = \beta_0 + \beta_1 \cdot \text{Social Interactions} + \beta_2 \cdot \text{IsRural} + \beta_3 \cdot \text{Outdoor time} + \epsilon\)</span></li>
</ul>
<p>We have already fitted the first model and assigned it the name <code>wb_mdl1</code>.<br />
We need to fit the second:</p>
<pre class="r"><code>wb_mdl2 &lt;- lm(wellbeing ~ 1 + social_int + isRural + outdoor_time, data=mwdata2)</code></pre>
<p>Let’s look at the amount of variation in wellbeing scores explained by each model:</p>
<pre class="r"><code>summary(wb_mdl1)$adj.r.squared</code></pre>
<pre><code>## [1] 0.251737</code></pre>
<pre class="r"><code>summary(wb_mdl2)$adj.r.squared</code></pre>
<pre><code>## [1] 0.3037301</code></pre>
<p>The model <em>with</em> weekly outdoor time as a predictor explains 30% of the variance, and the model <em>without</em> explains 25%.<br />
Does including weekly outdoor time as a predictor provide a significantly better fit of the data (<strong>wb_mdl2</strong> compared to <strong>wb_mdl1</strong>)?</p>
<pre class="r"><code>anova(wb_mdl1, wb_mdl2)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Model 1: wellbeing ~ social_int + isRural
## Model 2: wellbeing ~ 1 + social_int + isRural + outdoor_time
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    197 4285.6                                  
## 2    196 3967.6  1    318.03 15.711 0.0001033 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="int">
<p>Weekly outdoor time was found to explain a significant amount of variance in wellbeing scores over and above weekly social interactions and location (rural vs not-rural)<br />
<span class="math inline">\(F\)</span>(1 )=NA, 15.71, p&lt;.001.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="frame">
<h1 id="incremental-validity---a-caution">Incremental validity - A caution</h1>
<p>A common goal for researchers is to determine which variables matter (and which do not) in contributing to some outcome variable. A common approach to answer such questions is to consider whether some variable <span class="math inline">\(X\)</span>’s contribution remains significant <em>after</em> controlling for variables <span class="math inline">\(Z\)</span>.</p>
<p>The reasoning:</p>
<ul>
<li>If our measure of <span class="math inline">\(X\)</span> correlates significantly with outcome <span class="math inline">\(Y\)</span> even when controlling for our measure of <span class="math inline">\(Z\)</span>, then <span class="math inline">\(X\)</span> contributes to <span class="math inline">\(y\)</span> <em>over and above</em> the contribution of <span class="math inline">\(Z\)</span>.</li>
</ul>
<p>In multiple regression, we might fit the model <span class="math inline">\(Y = \beta_0 + \beta_1 \cdot X + \beta_2 \cdot Z + \epsilon\)</span> and conclude that <span class="math inline">\(X\)</span> is a useful predictor of <span class="math inline">\(Y\)</span> <em>over and above</em> <span class="math inline">\(Z\)</span> based on the estimate <span class="math inline">\(\hat \beta_1\)</span>, or via model comparison between that model and the model without <span class="math inline">\(Z\)</span> as a predictor (<span class="math inline">\(Y = \beta_0 + \beta_1 \cdot X + \epsilon\)</span>).</p>
<p><strong>A Toy Example</strong></p>
<p>Suppose we have monthly data over a seven year period which captures the number of shark attacks on swimmers each month, and the number of ice-creams sold by beach vendors each month.<br />
Consider the relationship between the two:<br />
<img src="09-mlr-select_files/figure-html/unnamed-chunk-10-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>We can fit the linear model and see a significant relationship between ice cream sales and shark attacks:</p>
<pre class="r"><code>sharkdata &lt;- read_csv(&quot;data/sharks.csv&quot;)
shark_mdl &lt;- lm(shark_attacks ~ ice_cream_sales, data = sharkdata)
summary(shark_mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = shark_attacks ~ ice_cream_sales, data = sharkdata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -17.3945  -4.9268   0.5087   4.8152  15.7023 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      5.58835    5.19063   1.077    0.285    
## ice_cream_sales  0.32258    0.05809   5.553 3.46e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.245 on 81 degrees of freedom
## Multiple R-squared:  0.2757, Adjusted R-squared:  0.2668 
## F-statistic: 30.84 on 1 and 81 DF,  p-value: 3.461e-07</code></pre>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Does the relationship between ice cream sales and shark attacks make sense? What might be missing from our model?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<p>You might quite rightly suggest that this relationship is actually being driven by temperature - when it is hotter, there are more ice cream sales <em>and</em> there are more people swimming (hence more shark attacks).</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Is <span class="math inline">\(X\)</span> (the number of ice-cream sales) a useful predictor of <span class="math inline">\(Y\)</span> (numbers of shark attacks) over and above <span class="math inline">\(Z\)</span> (temperature)?<br />
<br>
We might answer this with a multiple regression model including both temperature and ice cream sales as predictors of shark attacks:</p>
<pre class="r"><code>shark_mdl2 &lt;- lm(shark_attacks ~ ice_cream_sales + temperature, data = sharkdata)
summary(shark_mdl2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = shark_attacks ~ ice_cream_sales + temperature, data = sharkdata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -15.5359  -3.1353   0.1088   3.1064  17.2566 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      1.73422    4.27917   0.405    0.686    
## ice_cream_sales  0.08588    0.05997   1.432    0.156    
## temperature      1.31868    0.20457   6.446 8.04e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.914 on 80 degrees of freedom
## Multiple R-squared:  0.5233, Adjusted R-squared:  0.5114 
## F-statistic: 43.91 on 2 and 80 DF,  p-value: 1.345e-13</code></pre>
<p><br>
What do you conclude?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution
</div>
<div class="solution-body">
<p>It appears that numbers of ice cream sales is <em>not</em> a significant predictor of sharks attack numbers over and above the temperature.</p>
</div>
<p class="solution-end">
</p>
<p><strong>However…</strong>
In psychology, we can rarely observe and directly measure the constructs which we are interested in (for example, personality traits, intelligence, emotional states etc.). We rely instead on measurements of, e.g. behavioural tendencies, as a proxy for personality traits.</p>
<p>Let’s suppose that instead of including temperature in degrees celsius, we asked a set of people to self-report on a scale of 1 to 7 how hot it was that day. This measure should hopefully correlate well with the <em>actual</em> temperature, however, there will likely be some variation:
<img src="09-mlr-select_files/figure-html/unnamed-chunk-13-1.png" width="60%" style="display: block; margin: auto;" /></p>
<div class="question-begin">
Question
</div>
<div class="question-body">
<p>Is <span class="math inline">\(X\)</span> (the number of ice-cream sales) a useful predictor of <span class="math inline">\(Y\)</span> (numbers of shark attacks) over and above <span class="math inline">\(Z\)</span> (temperature - measured on our self-reported heat scale)?<br />
<br></p>
<pre class="r"><code>shark_mdl2a &lt;- lm(shark_attacks ~ ice_cream_sales + sr_heat, data = sharkdata)
summary(shark_mdl2a)</code></pre>
<pre><code>## 
## Call:
## lm(formula = shark_attacks ~ ice_cream_sales + sr_heat, data = sharkdata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -12.4576  -3.7818  -0.0553   3.6712  15.2155 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      8.96066    4.37145   2.050  0.04366 *  
## ice_cream_sales  0.14943    0.05643   2.648  0.00974 ** 
## sr_heat          2.96130    0.49276   6.010 5.24e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.051 on 80 degrees of freedom
## Multiple R-squared:  0.501,  Adjusted R-squared:  0.4885 
## F-statistic: 40.16 on 2 and 80 DF,  p-value: 8.394e-13</code></pre>
<p><br>
What do you conclude?</p>
<p class="question-end">
</p>
</div>
<p>Moral of the story: be considerate of what exactly it is that you are measuring.
<br>
This example was adapted from <a href="https://onlinelibrary.wiley.com/doi/full/10.1111/pere.12309">Westfall and Yarkoni, 2020</a> which provides a much more extensive discussion of incremental validity and type 1 error rates.</p>
</div>
<div class="frame">
<h2 id="aic-bic">AIC &amp; BIC</h2>
<p>We can also compare models using information criterion statistics, such as AIC and BIC. These combine information about the sample size, the number of model parameters and the residual sums of squares (<span class="math inline">\(SS_{residual}\)</span>). Models do not need to be nested to be compared via AIC and BIC, but they need to have been fit to the same dataset.<br />
For both of these fit indices, lower values are better, and both include a penalty for the number of predictors in the model, although BIC’s penalty is harsher:</p>
<p><span class="math display">\[
AIC = n\,\text{ln}\left( \frac{SS_{residual}}{n} \right) + 2k \\
\quad \\
BIC = n\,\text{ln}\left( \frac{SS_{residual}}{n} \right) + k\,\text{ln}(n) \\
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; SS_{residual} = \text{sum of squares residuals} \\
&amp; n = \text{sample size} \\
&amp; k = \text{number of explanatory variables} \\
&amp; \text{ln} = \text{natural log function} 
\end{align}
\]</span></p>
<hr />
<p><strong>In R,</strong> we can calculate AIC and BIC by using the <code>AIC()</code> and <code>BIC()</code> functions.</p>
</div>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>The code below fits 5 different models:</p>
<pre class="r"><code>model1 &lt;- lm(wellbeing ~ social_int + outdoor_time, data = mwdata2)
model2 &lt;- lm(wellbeing ~ social_int + outdoor_time + age, data = mwdata2)
model3 &lt;- lm(wellbeing ~ social_int + outdoor_time + routine, data = mwdata2)
model4 &lt;- lm(wellbeing ~ social_int + outdoor_time + routine + age, data = mwdata2)
model5 &lt;- lm(wellbeing ~ social_int + outdoor_time + routine + steps_k, data = mwdata2)</code></pre>
<p>For each of the below pairs of models, what methods are/are not available for us to use for comparison and why?</p>
<ul>
<li><code>model1</code> vs <code>model2</code></li>
<li><code>model2</code> vs <code>model3</code></li>
<li><code>model1</code> vs <code>model4</code></li>
<li><code>model3</code> vs <code>model5</code></li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-6" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-6&#39;, &#39;sol-start-6&#39;)"></span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<ul>
<li><p><code>model1</code> vs <code>model2</code><br />
These models are nested - <code>model2</code> contains all the variables of <code>model1</code> and they are fitted on the same dataset.<br />
We can therefore use an F-test, AIC or BIC.</p></li>
<li><p><code>model2</code> vs <code>model3</code><br />
These models are <strong>not</strong> nested, but they are fitted on the same dataset.<br />
We can therefore use AIC or BIC, but we cannot use an F-test.</p></li>
<li><p><code>model1</code> vs <code>model4</code>
These models are nested - <code>model4</code> contains all the variables of <code>model1</code> and they are fitted on the same dataset.<br />
We can therefore use an F-test, AIC or BIC.</p></li>
<li><p><code>model3</code> vs <code>model5</code><br />
These models are <strong>not</strong> nested, and they are <strong>not</strong> fitted on the same dataset. the “steps_k” variable contains missing values, and so these whole rows are excluded from <code>model5</code> (but they are included in <code>model3</code>). We cannot compare these models.</p></li>
</ul>
</div>
<p class="solution-end">
</p>
</div>
<div id="model-selection" class="section level1">
<h1>Model Selection</h1>
<p><a href="https://link.springer.com/article/10.1007/s10463-009-0234-4" class="uri">https://link.springer.com/article/10.1007/s10463-009-0234-4</a></p>
<p>step/drop1
<a href="http://joshualoftus.com/post/model-selection-bias-invalidates-significance-tests/" class="uri">http://joshualoftus.com/post/model-selection-bias-invalidates-significance-tests/</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
