<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>More About Logistic Regression</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Simple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="02_slr.html">1/2: Simple linear regression</a>
    </li>
    <li>
      <a href="03_slr_model_fit.html">1/3: Model Fit, Standardized Coefficients</a>
    </li>
    <li>
      <a href="04_slr_assumptions.html">1/4: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="05_slr_writeup.html">1/5: Writing-up</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multiple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="06_mlr.html">1/7: Basics</a>
    </li>
    <li>
      <a href="07_mlr_int.html">1/8: Interactions</a>
    </li>
    <li>
      <a href="08_mlr_assumpt.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="09_mlr_select.html">1/10: Model Fit, Model Comparison, Model Selection</a>
    </li>
    <li>
      <a href="10_mlr_report.html">1/11: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Experimental Data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="11_anova.html">2/1: ANOVA</a>
    </li>
    <li>
      <a href="11_anova.html">2/2: ANOVA (again)</a>
    </li>
    <li>
      <a href="12_factorial_anova.html">2/3: 2x2 ANOVA</a>
    </li>
    <li>
      <a href="13_multiplecomp.html">2/4: Multiple Comparisons</a>
    </li>
    <li class="dropdown-header">2/5: No exercises</li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="14_bootstrap_reg.html">2/7: Bootstrap</a>
    </li>
    <li>
      <a href="15_binary_logistic.html">2/8: Binary Logistic Regression</a>
    </li>
    <li class="dropdown-header">2/9: More About Logistic Regression</li>
    <li class="dropdown-header">2/10: Common tests as LM</li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">More About Logistic Regression</h1>

</div>


<div class="yellow">
<p><strong>PREREQUISITES</strong></p>
<p>Let <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> be two positive numbers:</p>
<p><span class="math display">\[
\begin{aligned}
e^{A + B} &amp;= e^A \times e^B \\
e^{\log(A)} &amp;= A \\
\log \left( \frac{A}{B} \right) &amp;= \log(A) - \log(B) \\
\log (A \times B) &amp;= \log(A) + \log(B)
\end{aligned}
\]</span></p>
</div>
<div id="senility-and-wais" class="section level1">
<h1>Senility and WAIS</h1>
<p>A sample of elderly people was given a psychiatric examination to determine symptoms of senility were present. Other measurements taken at the same time included the score on a subset of the Wechsler Adult Intelligent Scale (WAIS).</p>
<p>The data represent symptoms of senility (<code>senility</code> = 1 if symptoms are present and <code>senility</code>= 0 otherwise) and WAIS scores (<code>wais</code>) for <span class="math inline">\(n = 54\)</span> people.
You can download the data at following link: <a href="https://uoepsy.github.io/data/SenilityWAIS.csv" class="uri">https://uoepsy.github.io/data/SenilityWAIS.csv</a></p>
<pre class="r"><code>library(tidyverse)

sen &lt;- read_csv(file = &#39;https://uoepsy.github.io/data/SenilityWAIS.csv&#39;)
head(sen)</code></pre>
<pre><code>## # A tibble: 6 x 2
##    wais senility
##   &lt;dbl&gt;    &lt;dbl&gt;
## 1     9        1
## 2    13        1
## 3     6        1
## 4     8        1
## 5    10        1
## 6     4        1</code></pre>
<p>First, we should plot the data to understand what’s going on. We use <code>geom_jitter</code> rather than <code>geom_point</code> otherwise we will have multiple points on top of each other as there are multiple individuals with the same wais’ values:</p>
<pre class="r"><code>ggplot(sen, aes(wais, senility)) +
  geom_jitter(width = 0, height = 0.05) +
  labs(x = &quot;x, WAIS score&quot;, 
       y = &quot;y, Has senility symptoms?&quot;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-2-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Since we are interested in understanding how the probability of having senility symptoms changes as a function of the WAIS score, the response variable is <span class="math inline">\(y\)</span> = <code>senility</code> and the predictor is <span class="math inline">\(x\)</span> = <code>wais</code>.</p>
<p>We will fit the following logistic regression model:
<span class="math display">\[
\log \left( \frac{p}{1-p} \right) = \beta_0 + \beta_1 \ x
\]</span>
where <span class="math inline">\(p = P(y = 1)\)</span> is the probability that <span class="math inline">\(y = 1\)</span> for an individual with WAIS score equal to <span class="math inline">\(x\)</span>.</p>
<pre class="r"><code>mdl1 = glm(senility ~ wais, family = binomial, data = sen)
summary(mdl1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = senility ~ wais, family = binomial, data = sen)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.6702  -0.7402  -0.4749   0.5200   2.1157  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)   2.4040     1.1918   2.017  0.04369 * 
## wais         -0.3235     0.1140  -2.838  0.00453 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 61.806  on 53  degrees of freedom
## Residual deviance: 51.017  on 52  degrees of freedom
## AIC: 55.017
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div id="interpretation-of-coefficients" class="section level1">
<h1>Interpretation of coefficients</h1>
<p>To interpret the fitted coefficients, we first exponentiate the model:
<span class="math display">\[
\begin{aligned}
\log \left( \frac{p}{1-p} \right) &amp;= \beta_0 + \beta_1 x \\
e^{ \log \left( \frac{p}{1-p} \right) } &amp;= e^{\beta_0 + \beta_1 x } \\
\frac{p}{1-p} &amp;= e^{\beta_0} \ e^{\beta_1 x}
\end{aligned}
\]</span></p>
<p>and recall that the probability of success divided by the probability of failure is the odds of success:
<span class="math display">\[
\frac{p}{1-p} = \text{odds}(y = 1)
\]</span></p>
<p><strong>Intercept</strong></p>
<p>If <span class="math inline">\(x = 0\)</span>:
<span class="math display">\[
\frac{p_0}{1-p_0} = e^{\beta_0} \ e^{\beta_1 x} = e^{\beta_0}
\]</span></p>
<p>That is, <span class="math inline">\(e^{\beta_0}\)</span> represents the odds of having symptoms of senility for individuals with a WAIS score of 0.</p>
<p>In other words, for those with a WAIS score of 0, the probability of having senility symptoms is <span class="math inline">\(e^{\beta_0}\)</span> times that of non having them.</p>
<p><strong>Slope</strong></p>
<p>If <span class="math inline">\(x = 1\)</span>:
<span class="math display">\[
\frac{p_1}{1-p_1} = e^{\beta_0} \ e^{\beta_1 x} = e^{\beta_0} \ e^{\beta_1}
\]</span></p>
<p>Now consider taking the ratio of the odds of senility symptoms when <span class="math inline">\(x=1\)</span> to the odds of senility symptoms when <span class="math inline">\(x = 0\)</span>:
<span class="math display">\[
\frac{p_1 / (1 - p_1)}{p_0 / (1 - p_0)} 
= \frac{e^{\beta_0} \ e^{\beta_1}}{e^{\beta_0}}
= e^{\beta_1}
\]</span></p>
<p>So, <span class="math inline">\(e^{\beta_1}\)</span> represents the odds ratio for a 1 unit increase in WAIS score.</p>
<p>It is typically interpreted by saying that for a one-unit increase in WAIS score the odds of senility symptoms increase by a factor of <span class="math inline">\(e^{\beta_1}\)</span>.</p>
<p><strong>In our model</strong></p>
<pre class="r"><code>exp(coef(mdl1))</code></pre>
<pre><code>## (Intercept)        wais 
##    11.06784     0.72359</code></pre>
<p>The odds of senility symptoms for individuals scoring 0 on the WAIS test is 11:1. Or, the probability of having senility symptoms for those scoring 0 on the WAIS test is 11 times the probability of not having senility symptoms.</p>
<p>For every unit increase in WAIS score, the odds of senility symptoms reduces by a factor of 0.72</p>
<p><br></p>
<div class="optional-begin">
Optional Distinct covariate values (grouped data)<span id="opt-start-209" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-209&#39;, &#39;opt-start-209&#39;)"></span>
</div>
<div id="opt-body-209" class="optional-body" style="display: none;">
<p>If you explore the full data, you will see that even though there are <span class="math inline">\(n = `nrow(sen)`\)</span> individuals, there are only 17 distinct values of the covariate <span class="math inline">\(x\)</span> (representing the WAIS scores), as some people have the same WAIS scores but different <span class="math inline">\(y\)</span> values.</p>
<p>Let’s summarise the original data by computing for each covariate, the total number of people who showed senility symptoms (<span class="math inline">\(y\)</span>) and the total number of people with that distinct covariate value <span class="math inline">\(n\)</span>. This is the “grouped data”:</p>
<pre class="r"><code>sen_grp &lt;- sen %&gt;%
  group_by(wais) %&gt;%
  summarise(num_1s = sum(senility), total = n())

sen_grp</code></pre>
<pre><code>## # A tibble: 17 x 3
##     wais num_1s total
##  * &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;
##  1     4      1     2
##  2     5      1     1
##  3     6      1     2
##  4     7      2     3
##  5     8      2     2
##  6     9      2     6
##  7    10      1     6
##  8    11      1     6
##  9    12      0     2
## 10    13      1     6
## 11    14      2     7
## 12    15      0     3
## 13    16      0     4
## 14    17      0     1
## 15    18      0     1
## 16    19      0     1
## 17    20      0     1</code></pre>
<p>You can fit a logistic regression model to grouped data as follows. This is <strong>completely equivalent</strong> to the one we fitted above.</p>
<ol style="list-style-type: decimal">
<li>Provide two columns, one giving the number of successes (s = 1) and the other giving the number of failures (s = 0) which is just <span class="math inline">\(n - y\)</span>:</li>
</ol>
<pre class="r"><code>mdl1a &lt;- glm(cbind(num_1s, total - num_1s) ~ wais, data = sen_grp, family = binomial)
summary(mdl1a)</code></pre>
<pre><code>## 
## Call:
## glm(formula = cbind(num_1s, total - num_1s) ~ wais, family = binomial, 
##     data = sen_grp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.9064  -0.6965  -0.2538   0.1719   1.7771  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)   2.4040     1.1918   2.017  0.04369 * 
## wais         -0.3235     0.1140  -2.838  0.00453 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 20.208  on 16  degrees of freedom
## Residual deviance:  9.419  on 15  degrees of freedom
## AIC: 27.792
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Provide the proportion of successes and the number of people with that distinct covariate in weights:</li>
</ol>
<pre class="r"><code>sen_grp &lt;- sen_grp %&gt;%
  mutate(prop_1s = num_1s / total)

head(sen_grp)</code></pre>
<pre><code>## # A tibble: 6 x 4
##    wais num_1s total prop_1s
##   &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
## 1     4      1     2   0.5  
## 2     5      1     1   1    
## 3     6      1     2   0.5  
## 4     7      2     3   0.667
## 5     8      2     2   1    
## 6     9      2     6   0.333</code></pre>
<pre class="r"><code>mdl1b &lt;- glm(prop_1s ~ wais, weights = total, data = sen_grp, family = binomial)
summary(mdl1b)</code></pre>
<pre><code>## 
## Call:
## glm(formula = prop_1s ~ wais, family = binomial, data = sen_grp, 
##     weights = total)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.9064  -0.6965  -0.2538   0.1719   1.7771  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)   2.4040     1.1918   2.017  0.04369 * 
## wais         -0.3235     0.1140  -2.838  0.00453 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 20.208  on 16  degrees of freedom
## Residual deviance:  9.419  on 15  degrees of freedom
## AIC: 27.792
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</div>
<p class="optional-end">
</p>
</div>
<div id="diagnosing-model-fit-residuals" class="section level1">
<h1>Diagnosing model fit: Residuals</h1>
<p>Unlike linear regression, logistic regression has 2 main types of residuals.</p>
<ol style="list-style-type: decimal">
<li>Pearson residuals</li>
<li>Deviance residuals</li>
</ol>
<p>We will now discuss each in turn.</p>
<p>In addition, just like in linear regression, each of the above can be standardized or studentized if you wish to. We won’t discuss how to standardize each of those as the formula is difficult, but the idea is to standardize them to make them have a mean of zero and standard deviation = 1.</p>
<p>Remember the difference?</p>
<ul>
<li><span class="math inline">\(i\)</span>th standardized residual = residual / SD(residual)</li>
<li><span class="math inline">\(i\)</span>th studentized residual = residual / SD(residual from model fitted without observation <span class="math inline">\(i\)</span>)</li>
</ul>
<div id="pearson-residuals" class="section level2">
<h2>Pearson residuals</h2>
<p>Pearson residuals are similar to the Pearson residuals you might remember from the chi-squared test in DAPR1.
<span class="math display">\[
Pres_i = \frac{Observed - Expected}{\sqrt{Expected}}
\]</span></p>
<p>In logistic regression, this is
<span class="math display">\[
Pres_i = \frac{y_i - \hat p_i}{\sqrt{\hat p_i (1 - \hat p_i)}}
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(y_i\)</span> is the observed response for unit <span class="math inline">\(i\)</span>, either 0 (failure) or 1 (success)</li>
<li><span class="math inline">\(\hat p_i\)</span> is the model-predicted probability of success</li>
</ul>
<p>There is one residual per each case (row) in the dataset:</p>
<pre class="r"><code>Pres &lt;- residuals(mdl1, type = &#39;pearson&#39;)</code></pre>
<p>The standardized Pearson residuals (zero mean and unit standard deviation) are obtained as follows:</p>
<pre class="r"><code>SPres &lt;- rstandard(mdl1, type = &#39;pearson&#39;)</code></pre>
<p>The standardized Pearson residuals (also zero mean and unit standard deviation) are obtained as follows:</p>
<pre class="r"><code>StuPres &lt;- rstudent(mdl1, type = &#39;pearson&#39;)</code></pre>
<p><strong>In the following, I will use the Studentized residuals for the plots, but if you wish to, you can use the standardized ones.</strong></p>
<p>First, we plot the Studentized Pearson Residuals against their index, and we check whether there are any values larger than 2 in absolute value (that is larger than 2 or smaller than -2). Some people prefer to be strict and deem as outlier those greater than 3 in absolute value as most values should be within -3 and 3.</p>
<pre class="r"><code>plot(StuPres, ylab = &quot;Studentized Pearson Residuals&quot;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-12-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Yes, there appear to be 3 residuals with a value slightly larger than 2 in absolute value. We will keep these in mind and check later if they are also influential points.</p>
<p><br></p>
<p>Plotting the (Studentized) Pearson residuals against the fitted values or the predictor is not very informative in logistic regression as you can see below:</p>
<pre class="r"><code>plot(fitted(mdl1), StuPres, 
     xlab = &#39;Prob. of Success&#39;, ylab = &#39;Studentized Pearson Residuals&#39;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-13-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>plot(sen$wais, StuPres, 
     xlab = &#39;Prob. of Success&#39;, ylab = &#39;Studentized Pearson Residuals&#39;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-14-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Sometimes a <strong>binned plot</strong><a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> can be more informative, but not always! It works by combining together all responses for people having the same covariate <span class="math inline">\(x_i\)</span> value, and taking the average Studentized Pearson residual for those.</p>
<p>Before using this function, make sure you have installed the <strong>arm</strong> package!</p>
<pre class="r"><code>arm::binnedplot(fitted(mdl1), StuPres, 
                xlab = &#39;Prob. of Success&#39;, ylab = &#39;Studentized Pearson Residuals&#39;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-15-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>There doesn’t appear to be any extreme values.</p>
</div>
<div id="deviance-residuals" class="section level2">
<h2>Deviance residuals</h2>
<p>What does <em>deviance</em> mean? In logistic regression, deviance is a measure of deviation, discrepancy, mismatch between the data and the model. You can think of it as a generalisation of the terms making up the residual sum of squares in simple linear regression.</p>
<pre class="r"><code>Dres &lt;- residuals(mdl1, type = &#39;deviance&#39;)</code></pre>
<p>The standardized deviance residuals (zero mean and unit standard deviation) are obtaiend with</p>
<pre class="r"><code>SDres &lt;- rstandard(mdl1, type = &#39;deviance&#39;)</code></pre>
<p>And the Studentized deviance residuals (also zero mean and unit standard deviation) are found via:</p>
<pre class="r"><code>StuDres &lt;- rstudent(mdl1, type = &#39;deviance&#39;)</code></pre>
<p>Again, we check whether any residuals are larger than 2 or 3 in absolute value:</p>
<pre class="r"><code>plot(StuDres, ylab = &#39;Studentized Deviance Residuals&#39;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-19-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>All fine!</p>
<p>Again, a plot against the fitted values or the predictors isn’t that useful in logistic regression…</p>
<pre class="r"><code>plot(fitted(mdl1), StuDres, 
     xlab = &#39;Prob. of Success&#39;, ylab = &#39;Studentized Deviance Residuals&#39;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-20-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>plot(sen$wais, StuDres, 
     xlab = &#39;Prob. of Success&#39;, ylab = &#39;Studentized Deviance Residuals&#39;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-21-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>So we will check against a binned plot:</p>
<pre class="r"><code>arm::binnedplot(fitted(mdl1), StuDres, 
                xlab = &#39;Prob. of Success&#39;, ylab = &#39;Studentized Deviance Residuals&#39;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-22-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Again, it seems like everything is fine, no extremely high values.</p>
</div>
<div id="which-residuals-should-i-use" class="section level2">
<h2>Which residuals should I use???</h2>
<p>Both! Compute both, and for visual exploration most of the time it’s fine to use the <strong>deviance</strong> residuals.</p>
<!-- You will get away with it -->
<p>If you use standardized or studentized ones it’s easier to explore extreme values as we expect most residuals to be within -2, 2 or -3, 3.</p>
<p>If you do not provide the <code>type = ...</code> argument to the function <code>residuals()</code>, then it will use the Deviance residuals by default, and so will the function <code>rstandard()</code> and <code>rstudent()</code>!</p>
</div>
</div>
<div id="influential-values" class="section level1">
<h1>Influential values</h1>
<p>In logistic regression we typically check for influential observations by checking if there are any of the 54 cases in the dataset that have a Cook’s distance greater than 0.5 (moderately influential) or 1 (highly influential):</p>
<pre class="r"><code>plot(cooks.distance(mdl1), ylab = &quot;Cook&#39;s distance&quot;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-23-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>None of the units in the dataset appears to have a Cook’s distance value greater than 0.5, hence there does not seem to be issues with influential points.</p>
</div>
<div id="diagnosing-model-fit-goodness-of-fit-statistics" class="section level1">
<h1>Diagnosing model fit: Goodness of fit statistics</h1>
<p>In logistic regression there are two measures of goodness of fit. These are an extension of the ANOVA F-test in linear regression which test whether all slopes were 0 or at least one was not.</p>
<p>We test whether
<span class="math display">\[
\begin{aligned}
H_0 &amp;: \beta_1 = ... = 0 \\
H_1 &amp;: \text{at least one }\beta \neq 0
\end{aligned}
\]</span></p>
<p>using either:</p>
<ul>
<li>Pearson chi-squared statistic</li>
<li>Hosmer–Lemeshow statistic</li>
</ul>
<p>We are super lucky, as we already saved both Pearson residuals and the Deviance residuals, <strong>not the standardized</strong> and <strong>not the studentized</strong> ones, we just need to do respectively:</p>
<p><span class="math display">\[
X^2 = \sum Pres_i^2
\]</span></p>
<p><span class="math display">\[
D = \sum Dres_i^2
\]</span></p>
<div id="pearson-chi-squared-statistic" class="section level2">
<h2>Pearson chi-squared statistic</h2>
<p>The Pearson chi-squared statistic is computed as
<span class="math display">\[
X^2 = \sum Pres_i^2
\]</span></p>
<p>where <span class="math inline">\(Pres_i\)</span> is the <span class="math inline">\(i\)</span>th Pearson residual from <code>residuals(&lt;fitted model&gt;, type = 'pearson')</code>.</p>
<p>The test-statistic follows a chi-squared distribution with <span class="math inline">\(m - p\)</span> degrees of freedom where</p>
<ul>
<li><span class="math inline">\(m\)</span> = number of distinct covariate combinations</li>
<li><span class="math inline">\(p\)</span> = number of estimated parameters</li>
</ul>
<p>We are so lucky, because we already did compute the required residuals.</p>
<pre class="r"><code>m &lt;- length(unique(sen$wais))
m</code></pre>
<pre><code>## [1] 17</code></pre>
<pre class="r"><code>p &lt;- length(coef(mdl1))
p</code></pre>
<pre><code>## [1] 2</code></pre>
<pre class="r"><code>X2 &lt;- sum(Pres^2)
X2</code></pre>
<pre><code>## [1] 51.60331</code></pre>
<pre class="r"><code>1 - pchisq(X2, df = m - p)</code></pre>
<pre><code>## [1] 6.568158e-06</code></pre>
<div class="red">
<p><strong>WARNING</strong></p>
<p>This Pearson chi-squared goodness-of-fit test works reasonably well when the number of distinct covariate combinations is neither too small nor too large.
If the number of patterns is too small, the test for goodness of fit is too coarse, whereas if the number of patterns is too large, the predicted number of successes for many of the patterns in the independent variables will be too small (i.e., the data are “thin” with less than five successes for many patterns), and so the distribution of the computed chi-squared is not reasonably described by the theoretical chi-squared distribution.</p>
<p>This situation is particularly likely to occur when one or more of the independent variables are continuous or in clinical studies when the total sample size is relatively small (below 100 patients).</p>
<p>Do not despair though! There is the Hosmer-Lemeshow goodness-of-fit test…</p>
</div>
</div>
</div>
<div id="hosmer-lemeshow-goodness-of-fit-test" class="section level1">
<h1>Hosmer-Lemeshow goodness-of-fit test</h1>
<p>The Hosmer-Lemeshow goodness-of-fit test can be implemented via the <code>performance</code> package. Don’t forget to install it first with <code>install.packages("performance")</code>!</p>
<p>It divides the fitted probabilities into 10 bins by default, specified into <code>n_bins = 10</code>. Sometimes when we have small datasets, this might be too much, and we need to reduce it. It is good practice to try different values and see how much the p-value changes. If it is fairly consistent and above the significance level, you should be safe to accept goodness of fit!</p>
<pre class="r"><code># performance::performance_hosmer(mdl1, 10)   # returns an error!
# performance::performance_hosmer(mdl1, 9)    # returns an error!
performance::performance_hosmer(mdl1, 8)</code></pre>
<pre><code>## # Hosmer-Lemeshow Goodness-of-Fit Test
## 
##   Chi-squared: 4.533
##            df: 6    
##       p-value: 0.605</code></pre>
<pre class="r"><code>performance::performance_hosmer(mdl1, 7)</code></pre>
<pre><code>## # Hosmer-Lemeshow Goodness-of-Fit Test
## 
##   Chi-squared: 2.922
##            df: 5    
##       p-value: 0.712</code></pre>
<pre class="r"><code>performance::performance_hosmer(mdl1, 6)</code></pre>
<pre><code>## # Hosmer-Lemeshow Goodness-of-Fit Test
## 
##   Chi-squared: 4.077
##            df: 4    
##       p-value: 0.396</code></pre>
<pre class="r"><code>performance::performance_hosmer(mdl1, 5)</code></pre>
<pre><code>## # Hosmer-Lemeshow Goodness-of-Fit Test
## 
##   Chi-squared: 3.399
##            df: 3    
##       p-value: 0.334</code></pre>
<p>At the 5% significance level, the p-values are non-significant. Hence, the sample results do not provide sufficient evidence to reject the null hypothesis that the model fits the data well.</p>
<div id="comparison-of-nested-models" class="section level2">
<h2>Comparison of nested models</h2>
<p>When moving from linear regression to more advanced and flexible models, testing of goodness of fit is more often done by comparing a wanted model to a simpler one.
The only caveat is that the two models need to be nested, i.e. all predictors of one model needs to be within the other.</p>
<p>We want to compare the model we previously fitted against a model where all slopes are 0, i.e. a baseline model:
<span class="math display">\[
\begin{aligned}
M_1 : \qquad\log \left( \frac{p}{1 - p} \right) &amp;= \beta_0 \\
M_2 : \qquad \log \left( \frac{p}{1 - p} \right) &amp;= \beta_0 + \beta_1 x
\end{aligned}
\]</span></p>
<p>The null hypothesis will be that the simpler model is a good fit, while the alternative is that the more complex model is needed.</p>
<p>In R we do the comparison as follows:</p>
<pre class="r"><code>mdl_red &lt;- glm(senility ~ 1, family = binomial, data = sen)

anova(mdl_red, mdl1, test = &#39;Chisq&#39;)</code></pre>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: senility ~ 1
## Model 2: senility ~ wais
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)   
## 1        53     61.806                        
## 2        52     51.017  1   10.789 0.001021 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The above code shows the two fitted models</p>
<pre><code>Model 1: senility ~ 1
Model 2: senility ~ wais</code></pre>
<p>And then reports the <em>Residual Deviance</em> of each model, 61.806 and 51.017 respectively. Remember the deviance is the equivalent of residual sum of squares in linear regression.</p>
<p>So, by adding the predictor <span class="math inline">\(x\)</span> = wais to the model, we reduce our deviance from 61.806 to 51.017, i.e. we reduce it by 10.789.
Is this reduction sufficient to be attributed solely to the contribution of the predictor, or could it just be due to random sampling variation? This is what the chi-squared test tells us!</p>
<div class="int">
<p>The reduced model (<span class="math inline">\(M_1\)</span>) has the slope set to zero <span class="math inline">\(\beta_1 = 0\)</span>. Its deviance is obtained by fitting a logistic regression model without any explanatory variables (but including a constant term). This deviance is found to be 61.806, with 53 degrees of freedom.
The deviance statistic from a fit of the model with <span class="math inline">\(x\)</span> = wais included is 51.017, with 52 degrees of freedom. The deviance dropped by 10.789, with a drop of one degree of freedom. The associated p-value from a chi-squared distribution with 1df is <span class="math inline">\(p = .001\)</span>.</p>
<p>There is strong evidence of an association between senility symptoms and scores on the Wechsler Adult Intelligent Scale.</p>
</div>
<!-- Above was Drop-in-deviance GOF test -->
<!-- # Deviance GOF test -->
<!-- mdl_sat = glm(senility ~ factor(1:nrow(sen)), family = binomial, data = sen) -->
<!-- anova(mdl1, mdl_sat, test = 'Chisq') -->
</div>
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<p>Kalkhoran et al. (2015)<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> investigated predictors of dual use of cigarettes and smokeless tobacco products. Although their original sample size was large (<span class="math inline">\(n\)</span> = 1324), they were interested in running separate logistic regression analyses within subgroups. Most of the sample used only cigarettes. One of the smaller subgroups contained subjects who used both cigarettes and smokeless tobacco products (<span class="math inline">\(n\)</span>=61). For this problem we focus on this smaller subgroup of dual cigarette and smokeless tobacco users. The dependent variable, Q, is whether the subject made an attempt to quit using tobacco products (0 = no attempt to quit; 1 = attempted to quit). There is one multi-category independent variable, intention to quit, I, with four levels: never intend to quit, may intend to quit but not in the next 6 months, intend to quit in the next 6 months, intend to quit in the next 30 days.</p>
<p>The data can be found at the following link: <a href="https://uoepsy.github.io/data/QuitAttempts.csv" class="uri">https://uoepsy.github.io/data/QuitAttempts.csv</a></p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-27">Table 1: </span>Quit Attempts and Intentions Among Dual Users of Cigarettes and Smokeless Tobacco Products
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
Description
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:left;">
Subject
</td>
</tr>
<tr>
<td style="text-align:left;">
Q
</td>
<td style="text-align:left;">
Quitting (0 = No attempt to quit; 1 = Attempted to quit)
</td>
</tr>
<tr>
<td style="text-align:left;">
I
</td>
<td style="text-align:left;">
Intentions to Quit (1 = Never intend to quit; 2 = May intend to quit but not in the next 6 months; 3 = Intend to quit in the next 6 months; 4 = Intend to quit in the next 30 days)
</td>
</tr>
</tbody>
</table>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Read the data into R.</p>
<p>Perform a preliminary exploratory analysis of the data by computing summary statistics and visualising the distribution of the variables.</p>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<pre class="r"><code>qa &lt;- read_csv(&#39;https://uoepsy.github.io/data/QuitAttempts.csv&#39;)
qa</code></pre>
<pre><code>## # A tibble: 61 x 3
##        S     Q     I
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1     1     0     1
##  2     2     1     3
##  3     3     1     2
##  4     4     0     1
##  5     5     1     2
##  6     6     1     2
##  7     7     1     3
##  8     8     0     3
##  9     9     1     3
## 10    10     0     2
## # … with 51 more rows</code></pre>
<pre class="r"><code>qa %&gt;%
  group_by(I) %&gt;%
  count(Q)</code></pre>
<pre><code>## # A tibble: 7 x 3
## # Groups:   I [4]
##       I     Q     n
##   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1     1     0     7
## 2     1     1     1
## 3     2     0     9
## 4     2     1    17
## 5     3     0     5
## 6     3     1    18
## 7     4     1     4</code></pre>
<pre class="r"><code>ggplot(qa, aes(I, fill = factor(Q))) +
  geom_bar() +
  labs(fill = &#39;Attempted quitting?&#39;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-30-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Fit a logistic regression of Q on I using ordinary logistic regression.</p>
<p>Be sure to treat the independent variable I as categorical rather than as continuous in these analyses (hint: you will need to make sure R will create for you dummy variables for each level of I).</p>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<p>First, we must make sure <code>I</code> is a factor otherwise R won’t create the dummy variables for us:</p>
<pre class="r"><code>qa$I &lt;- as.factor(qa$I)</code></pre>
<pre class="r"><code>qa_fit1 = glm(Q ~ I, data = qa, family = binomial)
summary(qa_fit1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Q ~ I, family = binomial, data = qa)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.7470  -0.5168   0.7002   0.9218   2.0393  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)   -1.946      1.069  -1.820  0.06872 . 
## I2             2.582      1.146   2.253  0.02423 * 
## I3             3.227      1.183   2.729  0.00636 **
## I4            19.512   1978.090   0.010  0.99213   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 78.546  on 60  degrees of freedom
## Residual deviance: 63.655  on 57  degrees of freedom
## AIC: 71.655
## 
## Number of Fisher Scoring iterations: 16</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>What do you observe from the results?</p>
<p>Interpret the coefficients in the context of the study.</p>
<p class="question-end">
</p>
</div>
<div style="display:none;">

</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Investigate whether or not the studentized deviance residuals raise any concerns about outliers.</p>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<pre class="r"><code>plot(residuals(qa_fit1), ylab = &quot;Studentized Deviance Residuals&quot;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-33-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>plot(fitted(qa_fit1), residuals(qa_fit1),
     xlab = &quot;Fitted values&quot;, ylab = &quot;Studentized Deviance Residuals&quot;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-33-2.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>arm::binnedplot(fitted(qa_fit1), residuals(qa_fit1),
                ylab = &quot;Average Studentized Deviance Residuals&quot;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-33-3.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Investigate whether or not there are influential observations.</p>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<pre class="r"><code>plot(cooks.distance(qa_fit1), ylab = &quot;Cook&#39;s Distance&quot;)</code></pre>
<p><img src="16_more_about_logistic_files/figure-html/unnamed-chunk-34-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Compute the Pearson goodness-of-fit statistic and report its p-value.</p>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<pre class="r"><code>m &lt;- length(unique(qa$I))
m</code></pre>
<pre><code>## [1] 4</code></pre>
<pre class="r"><code>p &lt;- length(coef(qa_fit1))
p</code></pre>
<pre><code>## [1] 4</code></pre>
<pre class="r"><code>X2 &lt;- sum(residuals(qa_fit1, type = &#39;pearson&#39;)^2)
X2</code></pre>
<pre><code>## [1] 57</code></pre>
<pre class="r"><code>1 - pchisq(X2, m - p)</code></pre>
<pre><code>## [1] 0</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Compute the Hosmer-Lemeshow goodness-of-fit statistic and report its p-value.</p>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<pre class="r"><code>D &lt;- sum(residuals(qa_fit1, type = &#39;deviance&#39;)^2)
D</code></pre>
<pre><code>## [1] 63.65502</code></pre>
<pre class="r"><code>deviance(qa_fit1)</code></pre>
<pre><code>## [1] 63.65502</code></pre>
<pre class="r"><code>1 - pchisq(D, m - p)</code></pre>
<pre><code>## [1] 0</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Perform a Deviance goodness-of-fit test by compare the following nested models:</p>
<p><span class="math display">\[
\begin{aligned}
M_1 &amp;: \qquad \log \left( \frac{p}{1 - p}\right) = \beta_0 \\
M_2 &amp;: \qquad \log \left( \frac{p}{1 - p}\right) = \beta_0 + \beta_1 I2 + \beta_2 I3 + \beta_3 I4
\end{aligned}
\]</span></p>
<p class="question-end">
</p>
</div>
<div style="display:none;">
<pre class="r"><code>qa_null &lt;- glm(Q ~ 1, data = qa, family = binomial)
summary(qa_null)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Q ~ 1, family = binomial, data = qa)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.4604  -1.4604   0.9187   0.9187   0.9187  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)   0.6444     0.2695   2.391   0.0168 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 78.546  on 60  degrees of freedom
## Residual deviance: 78.546  on 60  degrees of freedom
## AIC: 80.546
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>anova(qa_null, qa_fit1, test = &#39;Chisq&#39;)</code></pre>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: Q ~ 1
## Model 2: Q ~ I
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)   
## 1        60     78.546                        
## 2        57     63.655  3   14.891 0.001912 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<p class="solution-end">
</p>
<!-- Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Gelman, A., &amp; Hill, J. (2006). Data Analysis Using Regression and Multilevel/Hierarchical Models (Analytical Methods for Social Research). Cambridge: Cambridge University Press. <a href="doi:10.1017/CBO9780511790942" class="uri">doi:10.1017/CBO9780511790942</a><a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Kalkhoran S, Grana RA, Neilands TB, and Ling PM. Dual use of smokeless tobacco or e-cigarettes with cigarettes and cessation. <em>Am J Health Behav.</em> 2015;39:277–284.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
