<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Multiple linear regression basics</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Intro to Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="1_02_slr.html">1/2: Intro to Linear Regression</a>
    </li>
    <li>
      <a href="1_03_slr_model_fit.html">1/3: More Linear Regression</a>
    </li>
    <li>
      <a href="1_04_mlr.html">1/4: Multiple Predictors</a>
    </li>
    <li>
      <a href="1_05_int_nc.html">1/5: Interactions: Num * Cat</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    More Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_07_int_nn.html">1/7: Interactions: Num * Num</a>
    </li>
    <li>
      <a href="1_08_int_cc.html">1/8: Interactions: Cat * Cat</a>
    </li>
    <li>
      <a href="1_09_assumptions.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li class="dropdown-header">1/10: Bootstrap &amp; Troubleshooting</li>
    <li class="dropdown-header">1/11: Writing-up</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Analyzing Experimental Studies
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">2/1: </li>
    <li class="dropdown-header">2/2: </li>
    <li class="dropdown-header">2/3: </li>
    <li class="dropdown-header">2/4: </li>
    <li class="dropdown-header">2/5: </li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">2/7: </li>
    <li class="dropdown-header">2/8: </li>
    <li class="dropdown-header">2/9: </li>
    <li class="dropdown-header">2/10: </li>
    <li class="dropdown-header">2/11: </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Multiple linear regression basics</h1>

</div>


<div class="green">
<p><strong>Information about solutions</strong></p>
<p>Solutions for these exercises are available immediately below each question.<br />
We would like to emphasise that much evidence suggests that testing enhances learning, and we <strong>strongly</strong> encourage you to make a concerted attempt at answering each question <em>before</em> looking at the solutions. Immediately looking at the solutions and then copying the code into your work will lead to poorer learning.<br />
We would also like to note that there are always many different ways to achieve the same thing in R, and the solutions provided are simply <em>one</em> approach.</p>
<p>Be sure to check the <a href="1_03_slr_model_fit.html"><strong>solutions to last week’s exercises</strong></a>.<br />
You can still ask any questions about previous weeks’ materials if things aren’t clear!</p>
</div>
<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Extend the ideas of SLR to consider regression models with two or more predictors.</li>
<li>Understand and interpret the coefficients in multiple linear regression models</li>
<li>(Categorical pred.) Understand the meaning of a MLR model with categorical predictors (no interaction case). For example, two parallel regression lines, one for each of two groups.</li>
</ol>
</div>
<p>In this block of exercises, we move from the simple linear regression model (one outcome variable, one explanatory variable) to the <em>multiple regression model</em> (one outcome variable, multiple explanatory variables). Everything we just learned about simple linear regression can be extended (with minor modification) to the multiple regresion model. The key conceptual difference is that for simple linear regression we think of the distribution of errors at some fixed value of the explanatory variable, and for multiple linear regression, we think about the distribution of errors at fixed set of values for all our explanatory variables.</p>
<div id="numeric-numeric" class="section level1">
<h1>~ Numeric + Numeric</h1>
<blockquote>
<p><strong>Research question</strong><br />
Reseachers are interested in the relationship between psychological wellbeing and time spent outdoors.<br />
The researchers know that other aspects of peoples’ lifestyles such as how much social interaction they have can influence their mental well-being. They would like to study whether there is a relationship between well-being and time spent outdoors <em>after</em> taking into account the relationship between well-being and social interactions.</p>
</blockquote>
<!-- We previously used simple linear regression to examine whether score on the WMBWS was related to the amount of time spent outdoors (self-reported as the average number of hours per week). We will now extend this and build a multiple regression model which we can use to predict WEMWBS score based on both outdoor time *and* number of social interactions.   -->
<div class="optional-begin">
<span id="opt-start-45" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-45&#39;, &#39;opt-start-45&#39;)"> Wellbeing data codebook.</span>
</div>
<div id="opt-body-45" class="optional-body" style="display: none;">
<p><strong>Download link</strong></p>
<p>The data is available at <a href="https://uoepsy.github.io/data/wellbeing.csv" class="uri">https://uoepsy.github.io/data/wellbeing.csv</a>.</p>
<p><strong>Description</strong></p>
<p>Researchers interviewed 32 participants, selected at random from the population of residents of Edinburgh &amp; Lothians. They used the Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br />
The researchers also asked participants to estimate the average number of hours they spend outdoors each week, the average number of social interactions they have each week (whether on-line or in-person), and whether they believe that they stick to a routine throughout the week (Yes/No).</p>
<p>The data in <code>wellbeing.csv</code> contain five attributes collected from a random sample of <span class="math inline">\(n=32\)</span> hypothetical residents over Edinburgh &amp; Lothians, and include:</p>
<ul>
<li><code>wellbeing</code>: Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.<br />
</li>
<li><code>outdoor_time</code>: Self report estimated number of hours per week spent outdoors<br />
</li>
<li><code>social_int</code>: Self report estimated number of social interactions per week (both online and in-person)</li>
<li><code>routine</code>: Binary Yes/No response to the question “Do you follow a daily routine throughout the week?”</li>
<li><code>location</code>: Location of primary residence (City, Suburb, Rural)</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<div id="xpqxkbfqhg" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#xpqxkbfqhg .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xpqxkbfqhg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xpqxkbfqhg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xpqxkbfqhg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xpqxkbfqhg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xpqxkbfqhg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xpqxkbfqhg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xpqxkbfqhg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xpqxkbfqhg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xpqxkbfqhg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xpqxkbfqhg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xpqxkbfqhg .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#xpqxkbfqhg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xpqxkbfqhg .gt_from_md > :first-child {
  margin-top: 0;
}

#xpqxkbfqhg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xpqxkbfqhg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xpqxkbfqhg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#xpqxkbfqhg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xpqxkbfqhg .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#xpqxkbfqhg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xpqxkbfqhg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xpqxkbfqhg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xpqxkbfqhg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xpqxkbfqhg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xpqxkbfqhg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#xpqxkbfqhg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xpqxkbfqhg .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#xpqxkbfqhg .gt_left {
  text-align: left;
}

#xpqxkbfqhg .gt_center {
  text-align: center;
}

#xpqxkbfqhg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xpqxkbfqhg .gt_font_normal {
  font-weight: normal;
}

#xpqxkbfqhg .gt_font_bold {
  font-weight: bold;
}

#xpqxkbfqhg .gt_font_italic {
  font-style: italic;
}

#xpqxkbfqhg .gt_super {
  font-size: 65%;
}

#xpqxkbfqhg .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">wellbeing</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">outdoor_time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">social_int</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">location</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">routine</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">30</td>
<td class="gt_row gt_right">7</td>
<td class="gt_row gt_right">8</td>
<td class="gt_row gt_left">Suburb</td>
<td class="gt_row gt_left">Routine</td></tr>
    <tr><td class="gt_row gt_right">21</td>
<td class="gt_row gt_right">9</td>
<td class="gt_row gt_right">8</td>
<td class="gt_row gt_left">City</td>
<td class="gt_row gt_left">No Routine</td></tr>
    <tr><td class="gt_row gt_right">38</td>
<td class="gt_row gt_right">14</td>
<td class="gt_row gt_right">10</td>
<td class="gt_row gt_left">Suburb</td>
<td class="gt_row gt_left">Routine</td></tr>
    <tr><td class="gt_row gt_right">27</td>
<td class="gt_row gt_right">16</td>
<td class="gt_row gt_right">10</td>
<td class="gt_row gt_left">City</td>
<td class="gt_row gt_left">No Routine</td></tr>
    <tr><td class="gt_row gt_right">20</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">10</td>
<td class="gt_row gt_left">Rural</td>
<td class="gt_row gt_left">No Routine</td></tr>
    <tr><td class="gt_row gt_right">37</td>
<td class="gt_row gt_right">11</td>
<td class="gt_row gt_right">12</td>
<td class="gt_row gt_left">Suburb</td>
<td class="gt_row gt_left">No Routine</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
<p class="optional-end">
</p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Create a new RMarkdown, and in the first code-chunk, load the required libraries and import the wellbeing data into R. Assign them to a object called <code>mwdata</code>.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-46" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-46&#39;, &#39;sol-start-46&#39;)"> Solution </span>
</div>
<div id="sol-body-46" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in data</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>mwdata <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;https://uoepsy.github.io/data/wellbeing.csv&quot;</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mwdata)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   wellbeing outdoor_time social_int location routine   
##       &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;     
## 1        30            7          8 Suburb   Routine   
## 2        21            9          8 City     No Routine
## 3        38           14         10 Suburb   Routine   
## 4        27           16         10 City     No Routine
## 5        20            1         10 Rural    No Routine
## 6        37           11         12 Suburb   No Routine</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Produce plots of the <em>marginal distributions</em> (the distributions of each variable in the analysis without reference to the other variables) of the <code>wellbeing</code>, <code>outdoor_time</code>, and <code>social_int</code> variables.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-47" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-47&#39;, &#39;sol-start-47&#39;)"> Solution </span>
</div>
<div id="sol-body-47" class="solution-body" style="display: none;">
<p>We should be familiar now with how to visualise a marginal distribution. You might choose histograms, density curves, or boxplots, or a combination:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co">#used to arrange plots</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>wellbeing_plot <span class="ot">&lt;-</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">250</span>) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Score on WEMWBS (range 14-70)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Probability</span><span class="sc">\n</span><span class="st">density&quot;</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>outdoortime_plot <span class="ot">&lt;-</span> </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> outdoor_time)) <span class="sc">+</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">200</span>) <span class="sc">+</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time spent outdoors per week (hours)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Probability</span><span class="sc">\n</span><span class="st">density&quot;</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>social_plot <span class="ot">&lt;-</span> </span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> social_int)) <span class="sc">+</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">150</span>) <span class="sc">+</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Number of social interactions per week&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Probability</span><span class="sc">\n</span><span class="st">density&quot;</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="co"># the &quot;patchwork&quot; library allows us to arrange multiple plots</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>wellbeing_plot <span class="sc">/</span> outdoortime_plot <span class="sc">/</span> social_plot</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="1_04_mlr_files/figure-html/unnamed-chunk-3-1.png" alt="Marginal distribution plots of wellbeing sores, weekly hours spent outdoors, and social interactions" width="60%" />
<p class="caption">
Figure 1: Marginal distribution plots of wellbeing sores, weekly hours spent outdoors, and social interactions
</p>
</div>
<div class="int">
<ul>
<li>The marginal distribution of scores on the WEMWBS is unimodal with a mean of approximately 43. There is variation in WEMWBS scores (SD = 11.7).<br />
</li>
<li>The marginal distribution of weekly hours spent outdoors is unimodal with a mean of approximately 14.8. There is variation in weekly hours spent outdoors (SD = 6.9).<br />
</li>
<li>The marginal distribution of numbers of social interactions per week is unimodal with a mean of approximately 16. There is variation in numbers of social interactions (SD = 4.4).</li>
</ul>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Produce plots of the <em>marginal relationships</em> between the outcome variable (wellbeing) and each of the explanatory variables.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-48" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-48&#39;, &#39;sol-start-48&#39;)"> Solution </span>
</div>
<div id="sol-body-48" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>wellbeing_outdoor <span class="ot">&lt;-</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> outdoor_time, <span class="at">y =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time spent outdoors per week (hours)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Wellbeing score (WEMWBS)&quot;</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>wellbeing_social <span class="ot">&lt;-</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> social_int, <span class="at">y =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Number of social interactions per week&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Wellbeing score (WEMWBS)&quot;</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>wellbeing_outdoor <span class="sc">|</span> wellbeing_social</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:mwdata-mlr-rels"></span>
<img src="1_04_mlr_files/figure-html/mwdata-mlr-rels-1.png" alt="Scatterplots displaying the relationships between scores on the WEMWBS and a) weekly outdoor time (hours), and b) weekly number of social interactions" width="60%" />
<p class="caption">
Figure 2: Scatterplots displaying the relationships between scores on the WEMWBS and a) weekly outdoor time (hours), and b) weekly number of social interactions
</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Produce a correlation matrix of the variables which are to be used in the analysis, and write a short paragraph describing the relationships.</p>
<div class="statbox">
<p><strong>Correlation matrix</strong></p>
<p>A table showing the correlation coefficients - <span class="math inline">\(r_{(x,y)}=\frac{\mathrm{cov}(x,y)}{s_xs_y}\)</span> - between variables. Each cell in the table shows the relationship between two variables. The diagonals show the correlation of a variable with itself (and are therefore always equal to 1).</p>
<div class="rtip">
<p>We can create a correlation matrix easily by giving the <code>cor()</code> function a dataframe. However, we only want to give it 3 columns here. Think about how we select specific columns, either using <code>select()</code>, or giving the column numbers inside <code>[]</code>.</p>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-49" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-49&#39;, &#39;sol-start-49&#39;)"> Solution </span>
</div>
<div id="sol-body-49" class="solution-body" style="display: none;">
<p>We can either use:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># correlation matrix of the first 3 columns</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(mwdata[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span></code></pre></div>
<p>or:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select only the columns we want by name, and pass this to cor()</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mwdata <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(wellbeing, outdoor_time, social_int) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span></code></pre></div>
<pre><code>##              wellbeing outdoor_time social_int
## wellbeing    1.0000000    0.5815613  0.7939003
## outdoor_time 0.5815613    1.0000000  0.3394469
## social_int   0.7939003    0.3394469  1.0000000</code></pre>
<div class="int">
<p>There is a moderate, positive, linear relationship between weekly outdoor time and WEMWBS scores for the participants in the sample.
Participants’ wellbeing scores tend to increase, on average, with the number of hours spent outdoors each week.<br />
There is a moderate, positive, linear relationship between the weekly number of social interactions and WEMWBS scores for the participants in the sample.
Participants’ wellbeing scores tend to increase, on average, with the weekly number of social interactions.
There is also a weak positive correlation between weekly outdoor time and the weekly number of social interactions.</p>
</div>
<p><br>
Note that there is a weak correlation between our two explanatory variables (outdoor_time and social_int). We will return to how this might affect our model when later on we look at the assumptions of multiple regression.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>The scatterplots we created above show moderate, positive, and linear relationships both between outdoor time and wellbeing, and between numbers of social interactions and wellbeing.</p>
<p>Specify the form of your model, where <span class="math inline">\(x_1\)</span> = weekly outdoor time, <span class="math inline">\(x_2\)</span> = weekly numbers of social interactions and <span class="math inline">\(y\)</span> = scores on the WEMWBS.<br />
What are the <em>parameters</em> of the model. How do we denote <em>parameter estimates</em>?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-50" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-50&#39;, &#39;sol-start-50&#39;)"> Solution </span>
</div>
<div id="sol-body-50" class="solution-body" style="display: none;">
<p>A model for the relationship between <span class="math inline">\(x_1\)</span> = weekly outdoor time, <span class="math inline">\(x_2\)</span> = weekly numbers of social interactions and <span class="math inline">\(y\)</span> = scores on the WEMWBS is given by:
<span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon \\ \quad \\ \text{where} \quad \epsilon \sim N(0, \sigma) \text{ independently}
\]</span></p>
<p>In the model specified above,</p>
<ul>
<li><span class="math inline">\(\mu_{y|x_1, x_2} = \beta_0 + \beta_1 x + \beta_2 x_2\)</span> represents the systematic part of the model giving the mean of <span class="math inline">\(y\)</span> at each combination of values of <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>;</li>
<li><span class="math inline">\(\epsilon\)</span> represents the error (deviation) from that mean, and the errors are independent from one another.</li>
</ul>
<p>The parameters of our model are:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> (The intercept);</li>
<li><span class="math inline">\(\beta_1\)</span> (The slope across values of <span class="math inline">\(x_1\)</span>);</li>
<li><span class="math inline">\(\beta_2\)</span> (The slope across values of <span class="math inline">\(x_2\)</span>);<br />
</li>
<li><span class="math inline">\(\sigma\)</span> (The standard deviation of the errors).</li>
</ul>
<p>When we estimate these parameters from the available data, we have a <em>fitted model</em> (recall that the h<span class="math inline">\(\hat{\textrm{a}}\)</span>ts are used to distinguish our <em>estimates</em> from the <em>true unknown parameters</em>):
<span class="math display">\[
\widehat{Wellbeing} = \hat \beta_0 + \hat \beta_1 \cdot Outdoor Time + \hat \beta_2 \cdot Social Interactions
\]</span>
And we have residuals <span class="math inline">\(\hat \epsilon = y - \hat y\)</span> which are the deviations from the observed values and our model-predicted responses.</p>
</div>
<p class="solution-end">
</p>
<div class="statbox">
<p><strong>Visual</strong></p>
<p>Note that for simple linear regression we talked about our model as a <em>line</em> in 2 dimensions: the systematic part <span class="math inline">\(\beta_0 + \beta_1 x\)</span> defined a line for <span class="math inline">\(\mu_y\)</span> across the possible values of <span class="math inline">\(x\)</span>, with <span class="math inline">\(\epsilon\)</span> as the random deviations from that line. But in multiple regression we have more than two variables making up our model.</p>
<p>In this particular case of three variables (one outcome + two explanatory), we can think of our model as a <em>regression surface</em> (See Figure <a href="#fig:regsurf">3</a>). The systematic part of our model defines the surface across a range of possible values of both <span class="math inline">\(x_1\)</span> <em>and</em> <span class="math inline">\(x_2\)</span>. Deviations from the surface are determined by the random error component, <span class="math inline">\(\hat \epsilon\)</span>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:regsurf"></span>
<img src="1_04_mlr_files/figure-html/regsurf-1.png" alt="Regression surface for wellbeing ~ outdoor_time + social_int, from two different angles" width="100%" />
<p class="caption">
Figure 3: Regression surface for wellbeing ~ outdoor_time + social_int, from two different angles
</p>
</div>
<p>Don’t worry about trying to figure out how to visualise it if we had any more explanatory variables! We can only concieve of 3 spatial dimensions. One could imagine this surface changing over time, which would bring in a 4th dimension, but beyond that, it’s not worth trying!.</p>
</div>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Fit the linear model in R, assigning the output to an object called <code>mdl1</code>.</p>
As we did for simple linear regression, we can fit our multiple regression model using the <code>lm()</code> function. We can add as many explanatory variables as we like, separating them with a <code>+</code>.<br />
<br>
<center>
<code>lm( &lt;response variable&gt; ~ 1 + &lt;explanatory variable 1&gt; + &lt;explanatory variable 2&gt; + ... , data = &lt;dataframe&gt; )</code>
</center>
<p><br></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-51" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-51&#39;, &#39;sol-start-51&#39;)"> Solution </span>
</div>
<div id="sol-body-51" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mdl1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">+</span> social_int, <span class="at">data =</span> mwdata)</span></code></pre></div>
</div>
<p class="solution-end">
</p>
<div class="imp">
<p><strong>IMPORTANT!</strong></p>
<p>You can think of the sequence of steps involved in statistical modeling as:<br />
<span class="math display">\[
\text{Choose} \rightarrow \text{Fit} \rightarrow \text{Assess} \rightarrow \text{Use}
\]</span></p>
<div class="frame">
<strong>A general rule</strong><br />
<br>
<center>
Do not <strong>use</strong> (draw inferences or predictions from) a model <em>before</em> you have <strong>assessed</strong> whether the model satisfies the underlying assumptions
</center>
</div>
<p><br>
So far for our multiple regression model we have completed the first two steps (<strong>Choose</strong> and <strong>Fit</strong>) in that we have:</p>
<ol style="list-style-type: decimal">
<li>Explored/visualised our data and specified our model</li>
<li>fitted the model in R.</li>
</ol>
<p>We are going to skip straight to the <strong>Use</strong> step here, and move to interpreting our parameter estimates and construct confidence intervals around them. Please note that this when conducting real analyses, this would be an inappropriate thing to do. We will look at how to <strong>Assess</strong> whether a multiple regression model meets assumptions in a later lab.</p>
</div>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Using any of:</p>
<ul>
<li><code>mdl1</code></li>
<li><code>mdl1$coefficients</code></li>
<li><code>coef(mdl1)</code></li>
<li><code>coefficients(mdl1)</code></li>
<li><code>summary(mdl1)</code></li>
</ul>
<p>Write out the estimated parameter values of:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\hat \beta_0\)</span>, the estimated average wellbeing score associated with zero hours of outdoor time and zero social interactions per week.<br />
</li>
<li><span class="math inline">\(\hat \beta_1\)</span>, the estimated increase in average wellbeing score associated with one hour increase in weekly outdoor time, <em>holding the number of social interactions constant</em> (i.e., when the remaining explanatory variables are held at the same value or are fixed).</li>
<li><span class="math inline">\(\hat \beta_2\)</span>, the estimated increase in average wellbeing score associated with an additional social interaction per week (an increase of one), <em>holding weekly outdoor time constant</em>.</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-52" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-52&#39;, &#39;sol-start-52&#39;)"> Solution </span>
</div>
<div id="sol-body-52" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mdl1)</span></code></pre></div>
<pre><code>##  (Intercept) outdoor_time   social_int 
##    5.3703775    0.5923673    1.8034489</code></pre>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\hat \beta_0\)</span> = 5.37<br />
</li>
<li><span class="math inline">\(\hat \beta_1\)</span> = 0.59<br />
</li>
<li><span class="math inline">\(\hat \beta_2\)</span> = 1.8</li>
</ol>
</div>
<p class="solution-end">
</p>
<div class="statbox">
<p><strong>Interpretation of Muliple Regression Coefficients</strong></p>
<p>You’ll hear a lot of different ways that people explain multiple regression coefficients.<br />
For the model <span class="math inline">\(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon\)</span>, the estimate <span class="math inline">\(\hat \beta_1\)</span> will often be reported as:</p>
<p>the increase in <span class="math inline">\(y\)</span> for a one unit increase in <span class="math inline">\(x_1\)</span> when…</p>
<ul>
<li>holding the effect of <span class="math inline">\(x_2\)</span> constant.</li>
<li>controlling for differences in <span class="math inline">\(x_2\)</span>.</li>
<li>partialling out the effects of <span class="math inline">\(x_2\)</span>.</li>
<li>holding <span class="math inline">\(x_2\)</span> equal.</li>
<li>accounting for effects of <span class="math inline">\(x_2\)</span>.</li>
</ul>
<div class="int">
<pre><code>##               Estimate Std. Error  t value     Pr(&gt;|t|)
## (Intercept)  5.3703775  4.3205141 1.242995 2.238259e-01
## outdoor_time 0.5923673  0.1689445 3.506284 1.499467e-03
## social_int   1.8034489  0.2690982 6.701825 2.369845e-07</code></pre>
<p>The coefficient 0.59 of weekly outdoor time for predicting wellbeing score says that among those with the same number of social interactions per week, those who have one additional hour of outdoor time tend to, on average, score 0.59 higher on the WEMWBS wellbeing scale. The multiple regression coefficient measures that average <em>conditional</em> relationship.</p>
</div>
</div>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Within what distance from the model predicted values (the regression surface) would we expect 95% of wEMWBS wellbeing scores to be?</p>
<p><strong>Hint:</strong> either <code>sigma(mdl1)</code> or part of the output from <code>summary(mdl1)</code> will help you here.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-53" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-53&#39;, &#39;sol-start-53&#39;)"> Solution </span>
</div>
<div id="sol-body-53" class="solution-body" style="display: none;">
<p>The estimated standard deviation of the errors is <span class="math inline">\(\hat \sigma\)</span> = 6.15. We would expect 95% of wellbeing scores to be within about 12.3 (<span class="math inline">\(2 \hat \sigma\)</span>) from the model fit.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Obtain 95% confidence intervals for the regression coefficients, and write a sentence about each one.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-54" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-54&#39;, &#39;sol-start-54&#39;)"> Solution </span>
</div>
<div id="sol-body-54" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mdl1, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##                   2.5 %     97.5 %
## (Intercept)  -3.4660660 14.2068209
## outdoor_time  0.2468371  0.9378975
## social_int    1.2530813  2.3538164</code></pre>
<div class="int">
<ul>
<li>The average wellbeing score for all those with zero hours of outdoor time and zero social interactions per week is between -3.47 and 14.21.<br />
</li>
<li>When <em>holding the number of social interactions per week constant</em>, each one hour increase in weekly outdoor time is associated with a difference in wellbeing scores between 0.25 and 0.94, on average.<br />
</li>
<li>When <em>holding weekly outdoor time constant</em>, each increase of one social interaction per week is associated with a difference in wellbeing scores between 1.25 and 2.35, on average.</li>
</ul>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="numeric-categorical" class="section level1">
<h1>~ Numeric + Categorical</h1>
<p>Let’s do that again, but paying careful attention to where and how the process differs when we have a <em>categorical</em> (or “qualitative”) predictor.</p>
<blockquote>
<p>Suppose that the group of researchers were instead wanting to study the relationship between well-being and time spent outdoors after taking into account the relationship between well-being and <em>having a routine</em>.</p>
</blockquote>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>We have already visualised the marginal distribution of weekly outdoor time in an earlier question, as well as its relationship with wellbeing scores.<br />
Produce visualisations of:</p>
<ol style="list-style-type: decimal">
<li>the distribution of the <code>routine</code> variable</li>
<li>the relationship between <code>routine</code> and <code>wellbeing</code>.</li>
</ol>
<p><strong>Note:</strong> We cannot visualise the distribution of <code>routine</code> as a density curve or boxplot, because it is a <em>categorical</em> variable (observations can only take one of a set of discrete response values).</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-55" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-55&#39;, &#39;sol-start-55&#39;)"> Solution </span>
</div>
<div id="sol-body-55" class="solution-body" style="display: none;">
<p><code>geom_bar()</code> will count the number of observations falling into each unique level of the routine variable:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> routine)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()<span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Routine&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Frequency&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-10"></span>
<img src="1_04_mlr_files/figure-html/unnamed-chunk-10-1.png" alt="Marginal distribution plots of Routine (y/n)" width="60%" />
<p class="caption">
Figure 4: Marginal distribution plots of Routine (y/n)
</p>
</div>
<p>We might plot the relationship between routine and wellbeing as two boxplots:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mwdata, <span class="fu">aes</span>(<span class="at">x =</span> routine, <span class="at">y =</span> wellbeing)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Routine&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Wellbeing score (WEMWBS)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-11"></span>
<img src="1_04_mlr_files/figure-html/unnamed-chunk-11-1.png" alt="Relationship between wellbeing and presence of routine" width="60%" />
<p class="caption">
Figure 5: Relationship between wellbeing and presence of routine
</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Fit the multiple regression model below using <code>lm()</code>, and assign it to an object named <code>mdl2</code>. Examine the summary output of the model.</p>
<p><span class="math display">\[
Wellbeing = \beta_0 + \beta_1 \cdot OutdoorTime + \beta_2 \cdot Routine + \epsilon
\]</span></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-56" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-56&#39;, &#39;sol-start-56&#39;)"> Solution </span>
</div>
<div id="sol-body-56" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mdl2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">+</span> routine, <span class="at">data =</span> mwdata)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wellbeing ~ 1 + outdoor_time + routine, data = mwdata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -16.3597  -5.7983   0.1047   7.2899  12.5957 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     26.2525     3.9536   6.640  2.8e-07 ***
## outdoor_time     0.9152     0.2358   3.881 0.000552 ***
## routineRoutine   7.2947     3.2507   2.244 0.032633 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.06 on 29 degrees of freedom
## Multiple R-squared:  0.4361, Adjusted R-squared:  0.3972 
## F-statistic: 11.21 on 2 and 29 DF,  p-value: 0.0002467</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<p><span class="math inline">\(\hat \beta_0\)</span> (the intercept) is the estimated average wellbeing score associated with zero hours of weekly outdoor time and zero in the routine variable.</p>
<p>What group is the intercept the estimated wellbeing score for when they have zero hours of outdoor time? Why (think about what zero in the routine variable means)?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-57" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-57&#39;, &#39;sol-start-57&#39;)"> Solution </span>
</div>
<div id="sol-body-57" class="solution-body" style="display: none;">
<p>As you can see in the output of the model, we have a coefficient called <code>routineRoutine</code>. This is the parameter estimate for a dummy variable which has been inputted into the model. The <code>lm()</code> function will automatically name the dummy variables (and therefore the coefficients) according to what level is identified by the 1. It names them <code>&lt;variable&gt;&lt;Level&gt;</code>, so we can tell that <code>routineRoutine</code> is 1 for “Routine” and 0 for “No Routine.”</p>
<p>The intercept is therefore the estimated wellbeing score for those with No Routine and zero hours of outdoor time.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 13
</div>
<div class="question-body">
<p>In the previous example, we had a visualisation of our model as a regression surface (Figure <a href="#fig:regsurf">3</a>).<br />
Here, one of our explanatory variables has only two possible responses. How might we visualise the model?</p>
<ol style="list-style-type: lower-alpha">
<li>one line</li>
<li>one surface</li>
<li>two lines</li>
<li>two surfaces</li>
<li>a curved (not flat) surface</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-58" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-58&#39;, &#39;sol-start-58&#39;)"> Solution </span>
</div>
<div id="sol-body-58" class="solution-body" style="display: none;">
<p>We can visualise the model <span class="math inline">\(\widehat{Wellbeing} = \hat \beta_0 + \hat \beta_1 \cdot OutdoorTime + \hat \beta_2 \cdot Routine\)</span> as two lines.<br />
Each line represents the model predicted values for wellbeing scores across the range of weekly outdoor time, with one line for those who report having “Routine” and one for those with “No Routine.”</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 14
</div>
<div class="question-body">
<p>Get a pen and paper, and sketch out the plot shown in Figure <a href="#fig:plot-annotate">6</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-annotate"></span>
<img src="1_04_mlr_files/figure-html/plot-annotate-1.png" alt="Multiple regression model: Wellbeing ~ Outdoor Time + Routine" width="60%" />
<p class="caption">
Figure 6: Multiple regression model: Wellbeing ~ Outdoor Time + Routine
</p>
</div>
<p>Annotate your plot with labels for each of parameter estimates from your model:</p>
<table>
<thead>
<tr class="header">
<th>Parameter Estimate</th>
<th align="center">Model Coefficient</th>
<th align="right">Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\hat \beta_0\)</span></td>
<td align="center"><code>(Intercept)</code></td>
<td align="right">26.25</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\hat \beta_1\)</span></td>
<td align="center"><code>outdoor_time</code></td>
<td align="right">0.92</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat \beta_2\)</span></td>
<td align="center"><code>routineRoutine</code></td>
<td align="right">7.29</td>
</tr>
</tbody>
</table>
<div class="optional-begin">
<span id="opt-start-59" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-59&#39;, &#39;opt-start-59&#39;)"> Hint.</span>
</div>
<div id="opt-body-59" class="optional-body" style="display: none;">
<p>Below you can see where to add the labels, but we have not said which is which.</p>
<p><img src="1_04_mlr_files/figure-html/unnamed-chunk-13-1.png" width="60%" style="display: block; margin: auto;" /></p>
<ul>
<li>A is the vertical distance between the red and blue lines (the lines are parallel, so this distance is the same wherever you cut it on the x-axis).<br />
</li>
<li>B is the point at which the blue line cuts the y-axis.<br />
</li>
<li>C is the vertical increase (increase on the y-axis) for the blue line associated with a 1 unit increase on the x-axis (the lines are parallel, so this is the same for the red line).</li>
</ul>
</div>
<p class="optional-end">
</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-60" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-60&#39;, &#39;sol-start-60&#39;)"> Solution </span>
</div>
<div id="sol-body-60" class="solution-body" style="display: none;">
<ul>
<li>A = <span class="math inline">\(\hat \beta_2\)</span> = <code>routineRoutine</code> coefficient = 7.29</li>
<li>B = <span class="math inline">\(\hat \beta_0\)</span> = <code>(Intercept)</code> coefficient = 26.25</li>
<li>C = <span class="math inline">\(\hat \beta_1\)</span> = <code>outdoor_time</code> coefficient = 0.92</li>
</ul>
<p><img src="1_04_mlr_files/figure-html/unnamed-chunk-14-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 15
</div>
<div class="question-body">
<p>Load the <strong>sjPlot</strong> package using <code>library(sjPlot)</code> and try running the code below. (You may already have the <strong>sjPlot</strong> package installed from previous exercises on simple linear regression, if not, you will need to install it first).</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(mdl2)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(mdl2, <span class="at">type =</span> <span class="st">&quot;pred&quot;</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(mdl2, <span class="at">type =</span> <span class="st">&quot;pred&quot;</span>,  <span class="at">terms=</span><span class="fu">c</span>(<span class="st">&quot;outdoor_time&quot;</span>,<span class="st">&quot;routine&quot;</span>), <span class="at">show.data=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p>What do you think each one is showing?</p>
<div class="frame">
<p>The <code>plot_model</code> function (and the <strong>sjPlot</strong> package) can do a lot of different things. Most packages in R come with tutorials (or “vignettes”), for instance: <a href="https://strengejacke.github.io/sjPlot/articles/plot_model_estimates.html" class="uri">https://strengejacke.github.io/sjPlot/articles/plot_model_estimates.html</a></p>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-61" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-61&#39;, &#39;sol-start-61&#39;)"> Solution </span>
</div>
<div id="sol-body-61" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(mdl2)</span></code></pre></div>
<p><img src="1_04_mlr_files/figure-html/unnamed-chunk-16-1.png" width="60%" style="display: block; margin: auto;" />
These are the parameter estimates (the <span class="math inline">\(\hat \beta\)</span>’s), and the confidence intervals.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mdl2)</span></code></pre></div>
<pre><code>##                     2.5 %    97.5 %
## (Intercept)    18.1665376 34.338493
## outdoor_time    0.4329433  1.397409
## routineRoutine  0.6462090 13.943226</code></pre>
<p>When we add <code>type="pred"</code> we are asking for the predicted values. It will provide a separate plot for each explanatory variable, showing the predicted values at each level of that variable:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(mdl2, <span class="at">type =</span> <span class="st">&quot;pred&quot;</span>)</span></code></pre></div>
<pre><code>## $outdoor_time</code></pre>
<p><img src="1_04_mlr_files/figure-html/unnamed-chunk-18-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre><code>## 
## $routine</code></pre>
<p><img src="1_04_mlr_files/figure-html/unnamed-chunk-18-2.png" width="60%" style="display: block; margin: auto;" /></p>
<p>We can combine these into one plot, and ask it to show the raw data as well:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(mdl2, <span class="at">type =</span> <span class="st">&quot;pred&quot;</span>,  <span class="at">terms=</span><span class="fu">c</span>(<span class="st">&quot;outdoor_time&quot;</span>,<span class="st">&quot;routine&quot;</span>), <span class="at">show.data=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="1_04_mlr_files/figure-html/unnamed-chunk-19-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
<div id="categorical-predictors-with-k-levels" class="section level1">
<h1>Categorical Predictors with <span class="math inline">\(k\)</span> levels</h1>
<p>We saw that a <em>binary categorical</em> variable gets inputted into our model as a variable of 0s and 1s (these typically get called <strong>“dummy variables”</strong>).</p>
<div class="statbox">
<p><strong>Dummy variables</strong> are numeric variables that represent categorical data.</p>
</div>
<p>When we have a <em>categorical</em> explanatory variable with <strong>more than 2 levels</strong>, our model gets a bit more - it needs not just one, but <em>a number of</em> dummy variables. For a categorical variable with <span class="math inline">\(k\)</span> levels, we can express it in <span class="math inline">\(k-1\)</span> dummy variables.</p>
<p>For example, the “species” column below has three levels, and can be expressed by the two variables “species_dog” and “species_parrot”:</p>
<pre><code>##   species species_dog species_parrot
## 1     cat           0              0
## 2     cat           0              0
## 3     dog           1              0
## 4  parrot           0              1
## 5     dog           1              0
## 6     cat           0              0
## 7     ...         ...            ...</code></pre>
<ul>
<li>The “cat” level is expressed whenever both the “species_dog” and “species_parrot” variables are 0.</li>
<li>The “dog” level is expressed whenever the “species_dog” variable is 1 and the “species_parrot” variable is 0.</li>
<li>The “parrot” level is expressed whenever the “species_dog” variable is 0 and the “species_parrot” variable is 1.</li>
</ul>
<p>R will do all of this re-expression for us. If we include in our model a categorical explanatory variable with 4 different levels, the model will estimate 3 parameters - one for each dummy variable. We can interpret the parameter estimates (the coefficients we obtain using <code>coefficients()</code>,<code>coef()</code> or <code>summary()</code>) as the estimated increase in the outcome variable associated with an increase of one in each dummy variable (holding all other variables equal).</p>
<table style="width:92%;">
<colgroup>
<col width="27%" />
<col width="15%" />
<col width="18%" />
<col width="13%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">t value</th>
<th align="center">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>(Intercept)</strong></td>
<td align="center">60.28</td>
<td align="center">1.209</td>
<td align="center">49.86</td>
<td align="center">5.273e-39</td>
</tr>
<tr class="even">
<td align="center"><strong>speciesdog</strong></td>
<td align="center">-11.47</td>
<td align="center">1.71</td>
<td align="center">-6.708</td>
<td align="center">3.806e-08</td>
</tr>
<tr class="odd">
<td align="center"><strong>speciesparrot</strong></td>
<td align="center">-4.916</td>
<td align="center">1.71</td>
<td align="center">-2.875</td>
<td align="center">0.006319</td>
</tr>
</tbody>
</table>
<p>Note that in the above example, an increase in 1 of “species_dog” is the difference between a “cat” and a “dog.” An increase in one of “species_parrot” is the difference between a “cat” and a “parrot.” We think of the “cat” category in this example as the <em>reference level</em> - it is the category against which other categories are compared against.</p>
<p><img src="1_04_mlr_files/figure-html/unnamed-chunk-22-1.png" width="60%" style="display: block; margin: auto;" /></p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
