<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Bootstrap for regression</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Intro to Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="1_02_slr.html">1/2: Intro to Linear Regression</a>
    </li>
    <li>
      <a href="1_03_slr_model_fit.html">1/3: More Linear Regression</a>
    </li>
    <li>
      <a href="1_04_mlr.html">1/4: Multiple Predictors</a>
    </li>
    <li>
      <a href="1_05_int_nc.html">1/5: Interactions: Num * Cat</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    More Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_07_int_nn.html">1/7: Interactions: Num * Num</a>
    </li>
    <li>
      <a href="1_08_int_cc.html">1/8: Interactions: Cat * Cat</a>
    </li>
    <li>
      <a href="1_09_assumptions.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="1_10_bootstrap_reg.html">1/10: Bootstrap &amp; Troubleshooting</a>
    </li>
    <li>
      <a href="1_11_write_up.html">1/11: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Analyzing Experimental Studies
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="2_01_model_comp.html">2/1: Model Comparisons</a>
    </li>
    <li>
      <a href="2_02_coding_factors.html">2/2: Coding Factors</a>
    </li>
    <li>
      <a href="2_03_cont_design_factanova.html">2/3: Contrasts, Study Design, &amp; Factorial ANOVA</a>
    </li>
    <li>
      <a href="2_04_factorial_anova.html">2/4: Two-Way ANOVA</a>
    </li>
    <li>
      <a href="2_05_multi_comp_writeup.html">2/5: Assumptions, Multiple Comparisons, Corrections, &amp; Write-Up Example</a>
    </li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="2_07_binary.html">2/7: Binary Logistic Regression</a>
    </li>
    <li>
      <a href="2_08_morelogistic.html">2/8: More Logistic Regression</a>
    </li>
    <li>
      <a href="2_09_exp_vs_conf.html">2/9: Exploratory vs Confirmatory</a>
    </li>
    <li>
      <a href="2_10_power.html">2/10: Sample Size and Power Analysis</a>
    </li>
    <li class="dropdown-header">2/11: </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Bootstrap for regression</h1>

</div>


<p>Suppose in a linear model</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x + \epsilon
\]</span></p>
<p>we wish to test whether the slope for the predictor of interest <span class="math inline">\(x\)</span> is significantly different from 0:</p>
<p><span class="math display">\[
H_0 : \beta_1 = 0 \\
H_1 : \beta_1 \neq 0
\]</span></p>
<p>The fitted model is written:</p>
<p><span class="math display">\[
\hat y = \widehat \beta_0 + \widehat \beta_1 x
\]</span></p>
<p>and the estimated slope, <span class="math inline">\(\widehat \beta_1\)</span>, computed from the available sample data is an estimate of the unknown population slope <span class="math inline">\(\beta_1\)</span>, which corresponds to the slope if we had all the data for the entire population (but we don’t).</p>
<p>In the past weeks we have used the results from the t-test and corresponding p-values returned by the <code>summary()</code> function. However, such test results are valid only when the regression assumptions are satisfied. In fact, the numbers reported in the p-value column are only correct if the fitted model does not violate the regression assumptions. If it violates them, the results are not trustworthy.</p>
<p>Clearly, now you might wonder, what should we do then if there is no way we can get the model to satisfy the regression assumptions by transforming variables?</p>
<p>Here’s the answer: <strong>bootstrap!</strong></p>
<p>This week we examine bootstrapping, which is a technique for drawing inferences to the population from a regression model. This method is assumption-free and does not rely on conditions such as normality of the residuals.</p>
<p>Before continuing, this table summarises the new terms that will be explained throughout the exercises.</p>
<div class="frame">
<p><strong>Bootstrap Terminology</strong></p>
<ul>
<li>A <em>parameter</em> is a numerical summary for the population, e.g. the population slope <span class="math inline">\(\beta_1\)</span></li>
<li>A <em>statistic</em> is a numerical summary calculated from the sample data, e.g. the estimated slope in the sample <span class="math inline">\(\widehat \beta_1\)</span>. We use the sample statistic as a best guess, or estimate, for the unknown population parameter.</li>
<li>A <em>bootstrap sample</em> is chosen with replacement from an existing sample, using the same sample size.</li>
<li>A <em>bootstrap statistic</em> is a statistic computed for each bootstrap sample.</li>
<li>A <em>bootstrap distribution</em> collects bootstrap statistics for many bootstrap samples.</li>
</ul>
</div>
<div id="research-question" class="section level1">
<h1>Research question</h1>
<p>The research question we will investigate today is:</p>
<blockquote>
<p>Is age and knowledge about science associated with attitudes towards science and faith?</p>
</blockquote>
</div>
<div id="data-age-knowledge-and-attitudes-about-science" class="section level1">
<h1>Data: Age, Knowledge and Attitudes About Science</h1>
<p>This week’s lab explores whether knowledge about science and age are associated with attitudes towards science and faith. To examine these relationships, we will use a subset of data from the 2005 Eurobarometer 63.1 survey.</p>
<p>We can also state this in the form of two research hypotheses:</p>
<blockquote>
<ul>
<li>There is a significant linear relationship between people’s age and their attitudes to science and faith after accounting for their scientific knowledge.</li>
<li>There is a significant linear relationship between people’s scientific knowledge and their attitudes to science and faith after accounting for their age.</li>
</ul>
</blockquote>
<div id="description" class="section level4">
<h4>Description</h4>
<p>This example uses three variables from the Eurobarometer 63.1 survey:</p>
<div id="ezlgdzhkht" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ezlgdzhkht .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ezlgdzhkht .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ezlgdzhkht .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ezlgdzhkht .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ezlgdzhkht .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ezlgdzhkht .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ezlgdzhkht .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ezlgdzhkht .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ezlgdzhkht .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ezlgdzhkht .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ezlgdzhkht .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ezlgdzhkht .gt_from_md > :first-child {
  margin-top: 0;
}

#ezlgdzhkht .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ezlgdzhkht .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ezlgdzhkht .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#ezlgdzhkht .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#ezlgdzhkht .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ezlgdzhkht .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ezlgdzhkht .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ezlgdzhkht .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ezlgdzhkht .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#ezlgdzhkht .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ezlgdzhkht .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#ezlgdzhkht .gt_left {
  text-align: left;
}

#ezlgdzhkht .gt_center {
  text-align: center;
}

#ezlgdzhkht .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ezlgdzhkht .gt_font_normal {
  font-weight: normal;
}

#ezlgdzhkht .gt_font_bold {
  font-weight: bold;
}

#ezlgdzhkht .gt_font_italic {
  font-style: italic;
}

#ezlgdzhkht .gt_super {
  font-size: 65%;
}

#ezlgdzhkht .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Variable</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Description</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">kstot</td>
<td class="gt_row gt_left">Score on a science “quiz” composed of 13 true/false items.</td></tr>
    <tr><td class="gt_row gt_left">toomuchscience</td>
<td class="gt_row gt_left">Attitude to science and faith (question wording: "We rely too much on science and not enough on faith"; responses on a 5-point scale from strongly disagree to strongly agree).</td></tr>
    <tr><td class="gt_row gt_left">age</td>
<td class="gt_row gt_left">Age measured in years.</td></tr>
  </tbody>
  
  
</table>
</div>
<p>The science knowledge quiz has a range of 0 to 13. Its mean is about 8.7. The attitude to science and faith question has five categories, ranging from 0 to 4, with a mean of about 2.5. Age has a range of 15–93, with a mean of about 45. This is formally an ordinal variable but, in line with common practice in applied research, we regard it as continuous, as we do the other two variables as well.</p>
</div>
<div id="download-link" class="section level4">
<h4>Download link</h4>
<p>Download the data here: <a href="https://uoepsy.github.io/data/science-faith-attitude.csv" class="uri">https://uoepsy.github.io/data/science-faith-attitude.csv</a></p>
</div>
<div id="preview" class="section level4">
<h4>Preview</h4>
<div id="jwhphheblm" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#jwhphheblm .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#jwhphheblm .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jwhphheblm .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#jwhphheblm .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#jwhphheblm .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jwhphheblm .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jwhphheblm .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#jwhphheblm .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#jwhphheblm .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#jwhphheblm .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#jwhphheblm .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#jwhphheblm .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#jwhphheblm .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#jwhphheblm .gt_from_md > :first-child {
  margin-top: 0;
}

#jwhphheblm .gt_from_md > :last-child {
  margin-bottom: 0;
}

#jwhphheblm .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#jwhphheblm .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#jwhphheblm .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jwhphheblm .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#jwhphheblm .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jwhphheblm .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#jwhphheblm .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#jwhphheblm .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jwhphheblm .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jwhphheblm .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#jwhphheblm .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jwhphheblm .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#jwhphheblm .gt_left {
  text-align: left;
}

#jwhphheblm .gt_center {
  text-align: center;
}

#jwhphheblm .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#jwhphheblm .gt_font_normal {
  font-weight: normal;
}

#jwhphheblm .gt_font_bold {
  font-weight: bold;
}

#jwhphheblm .gt_font_italic {
  font-style: italic;
}

#jwhphheblm .gt_super {
  font-size: 65%;
}

#jwhphheblm .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">v5</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">v6</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">kstot</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">age</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">male</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">toomuchscience</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">solveprob</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">12</td>
<td class="gt_row gt_right">35</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">0</td></tr>
    <tr><td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">11</td>
<td class="gt_row gt_right">34</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td></tr>
    <tr><td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">7</td>
<td class="gt_row gt_right">40</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">NA</td>
<td class="gt_row gt_right">NA</td></tr>
    <tr><td class="gt_row gt_right">4</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">9</td>
<td class="gt_row gt_right">32</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">0</td></tr>
    <tr><td class="gt_row gt_right">5</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">6</td>
<td class="gt_row gt_right">35</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">1</td></tr>
    <tr><td class="gt_row gt_right">6</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">11</td>
<td class="gt_row gt_right">67</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">NA</td>
<td class="gt_row gt_right">NA</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<ul>
<li><p>Read the data into R, and call the data <code>ebsurvey</code>. Remember, you can download the data here: <a href="https://uoepsy.github.io/data/science-faith-attitude.csv" class="uri">https://uoepsy.github.io/data/science-faith-attitude.csv</a></p></li>
<li><p>How many observations and how many variables are there?</p></li>
<li><p>Today we will be only using the <code>kstot</code>, <code>age</code>, and <code>toomuchscience</code> columns. Subset the data to only have those 3 columns.</p></li>
<li><p>Is there any missing values? If yes, remove the rows with missing values.</p></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-97" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-97&#39;, &#39;sol-start-97&#39;)"> Solution </span>
</div>
<div id="sol-body-97" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the data</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ebsurvey <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://uoepsy.github.io/data/science-faith-attitude.csv&#39;</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect top 6 rows</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ebsurvey)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 7
##      v5    v6 kstot   age  male toomuchscience solveprob
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1     1     2    12    35     1              2         0
## 2     2     2    11    34     0              1         1
## 3     3     2     7    40     0             NA        NA
## 4     4     2     9    32     0              3         0
## 5     5     2     6    35     0              3         1
## 6     6     2    11    67     1             NA        NA</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check data dimensions</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ebsurvey)</span></code></pre></div>
<pre><code>## [1] 21886     7</code></pre>
<p>There are 21886 observations on 7 variables.</p>
<p>However, today we will be only using the <code>kstot</code>, <code>age</code>, and <code>toomuchscience</code> variables. We can subset the data:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ebsurvey <span class="ot">&lt;-</span> ebsurvey <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(kstot, age, toomuchscience)</span></code></pre></div>
<p>Are there any NA values in the data?</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anyNA</span>(ebsurvey)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Yes, so we omit them</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>ebsurvey <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(ebsurvey)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check new data dimensions</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ebsurvey)</span></code></pre></div>
<pre><code>## [1] 10503     3</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Give the variables more meaningful names. Rename <code>kstot</code> to <code>science_knowledge</code> and rename <code>toomuchscience</code> to <code>attitude</code>.</p>
<p><strong>Hint</strong></p>
<p>Have a look at the help page of the function rename: <code>?rename</code>.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-98" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-98&#39;, &#39;sol-start-98&#39;)"> Solution </span>
</div>
<div id="sol-body-98" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ebsurvey <span class="ot">&lt;-</span> ebsurvey <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">science_knowledge =</span> kstot,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">attitude =</span> toomuchscience)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ebsurvey)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   science_knowledge   age attitude
##               &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
## 1                12    35        2
## 2                11    34        1
## 3                 9    32        3
## 4                 6    35        3
## 5                 9    37        1
## 6                 5    63        2</code></pre>
</div>
<p class="solution-end">
</p>
<p><br></p>
<p>Before producing multiple regression models, it is a good idea to visually inspect each variable.</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Explore the distribution of age in years, <code>age</code>.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-99" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-99&#39;, &#39;sol-start-99&#39;)"> Solution </span>
</div>
<div id="sol-body-99" class="solution-body" style="display: none;">
<p>You may wish to consider using helpful bin sizes, see the <code>bindwidth</code> argument, but this is subjective and optional.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ebsurvey, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">&#39;white&#39;</span>, <span class="at">binwidth =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Age (years)&#39;</span>, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">&#39;Frequency&#39;</span>)</span></code></pre></div>
<p><img src="1_10_bootstrap_reg_files/figure-html/unnamed-chunk-8-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>We can obtain summary statistics as follows:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>ebsurvey <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">Min =</span> <span class="fu">min</span>(age),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">Median =</span> <span class="fu">quantile</span>(age, <span class="fl">0.5</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">IQR =</span> <span class="fu">IQR</span>(age),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">Mean =</span> <span class="fu">mean</span>(age),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">SD =</span> <span class="fu">sd</span>(age),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">Max =</span> <span class="fu">max</span>(age)) <span class="sc">%&gt;%</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>, </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">caption =</span> <span class="st">&#39;Descriptive statistics of age&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-9">Table 1: </span>Descriptive statistics of age
</caption>
<thead>
<tr>
<th style="text-align:right;">
Min
</th>
<th style="text-align:right;">
Median
</th>
<th style="text-align:right;">
IQR
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
<th style="text-align:right;">
Max
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
44.93
</td>
<td style="text-align:right;">
17.32
</td>
<td style="text-align:right;">
93
</td>
</tr>
</tbody>
</table>
<p>The mean age in the sample is about 45 years with a standard deviation of just over 17 years. The distribution looks approximately normal, with a slight positive skew.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Explore the distribution of science knowledge quiz scores, <code>science_knowledge</code>.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-100" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-100&#39;, &#39;sol-start-100&#39;)"> Solution </span>
</div>
<div id="sol-body-100" class="solution-body" style="display: none;">
<p>An histogram of science knowledge quiz scores is provided below:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ebsurvey, <span class="fu">aes</span>(<span class="at">x =</span> science_knowledge)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">&#39;white&#39;</span>) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Science knowledge quiz scores&#39;</span>, </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">&#39;Frequency&#39;</span>)</span></code></pre></div>
<p><img src="1_10_bootstrap_reg_files/figure-html/unnamed-chunk-10-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>We can obtain summary statistics as follows:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>ebsurvey <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">Min =</span> <span class="fu">min</span>(science_knowledge),</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">Median =</span> <span class="fu">quantile</span>(science_knowledge, <span class="fl">0.5</span>),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">IQR =</span> <span class="fu">IQR</span>(science_knowledge),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">Mean =</span> <span class="fu">mean</span>(science_knowledge),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">SD =</span> <span class="fu">sd</span>(science_knowledge),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">Max =</span> <span class="fu">max</span>(science_knowledge)) <span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>, </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">caption =</span> <span class="st">&#39;Descriptive statistics of science knowledge scores&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-11">Table 2: </span>Descriptive statistics of science knowledge scores
</caption>
<thead>
<tr>
<th style="text-align:right;">
Min
</th>
<th style="text-align:right;">
Median
</th>
<th style="text-align:right;">
IQR
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
<th style="text-align:right;">
Max
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
8.68
</td>
<td style="text-align:right;">
2.61
</td>
<td style="text-align:right;">
13
</td>
</tr>
</tbody>
</table>
<p>The histogram shows that the majority of values on the science knowledge quiz score cluster between about 5 and 11. There is a slight negative skew to the distribution. Overall there is little reason for concern as to the appropriateness of the variable for inclusion.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Explore the distribution of attitude to science and faith scores, <code>attitude</code>.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-101" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-101&#39;, &#39;sol-start-101&#39;)"> Solution </span>
</div>
<div id="sol-body-101" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ebsurvey, <span class="fu">aes</span>(<span class="at">x =</span> attitude)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">&#39;white&#39;</span>, <span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;We rely too much on science and not enough on faith&#39;</span>, </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">&#39;Frequency&#39;</span>)</span></code></pre></div>
<p><img src="1_10_bootstrap_reg_files/figure-html/unnamed-chunk-12-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>We can obtain summary statistics as follows:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ebsurvey <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">Min =</span> <span class="fu">min</span>(attitude),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">Median =</span> <span class="fu">quantile</span>(attitude, <span class="fl">0.5</span>),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">IQR =</span> <span class="fu">IQR</span>(attitude),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">Mean =</span> <span class="fu">mean</span>(attitude),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">SD =</span> <span class="fu">sd</span>(attitude),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">Max =</span> <span class="fu">max</span>(attitude)) <span class="sc">%&gt;%</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>, </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">caption =</span> <span class="st">&#39;Descriptive statistics of science attitude&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-13">Table 3: </span>Descriptive statistics of science attitude
</caption>
<thead>
<tr>
<th style="text-align:right;">
Min
</th>
<th style="text-align:right;">
Median
</th>
<th style="text-align:right;">
IQR
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
<th style="text-align:right;">
Max
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2.2
</td>
<td style="text-align:right;">
1.22
</td>
<td style="text-align:right;">
4
</td>
</tr>
</tbody>
</table>
<p>The mean score on the science and faith attitude variable is just over 2. There are only 5 discrete values possible in the distribution, based on the response options available, but the distribution looks approximately normal, with a slight negative skew.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Visualise the pairwise relationships between your variables and explore the possible correlations.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-102" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-102&#39;, &#39;sol-start-102&#39;)"> Solution </span>
</div>
<div id="sol-body-102" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ebsurvey, <span class="fu">aes</span>(age, science_knowledge)) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Age (years)&#39;</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">&#39;Science knowledge quiz scores&#39;</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ebsurvey, <span class="fu">aes</span>(age, attitude)) <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Age (years)&#39;</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">&#39;Science attitude&#39;</span>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ebsurvey, <span class="fu">aes</span>(science_knowledge, attitude)) <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Science knowledge quiz scores&#39;</span>,</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">&#39;Science attitude&#39;</span>)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">|</span> p2 <span class="sc">|</span> p3</span></code></pre></div>
<p><img src="1_10_bootstrap_reg_files/figure-html/unnamed-chunk-14-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>From the pairwise scatterplots, it does not seem like there is a strong linear dependence of attitude to science and faith on a person’s age and science knowledge.</p>
<p>Correlation matrix:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(ebsurvey)</span></code></pre></div>
<pre><code>##                   science_knowledge         age    attitude
## science_knowledge         1.0000000 -0.12239434 -0.17634507
## age                      -0.1223943  1.00000000  0.05496583
## attitude                 -0.1763451  0.05496583  1.00000000</code></pre>
<p>In this case, the Pearson correlation coefficient between <code>age</code> and <code>science_knowledge</code> is -0.12. The correlation is relatively small in absolute terms, and we therefore have little concern about multicollinearity influencing this regression analysis.</p>
<p>The correlation between <code>attitude</code> and <code>age</code> is 0.05, while with <code>science_knowledge</code> it is -0.17. So, overall there is a very weak linear relationship.</p>
</div>
<p class="solution-end">
</p>
<p><br></p>
<p>Now that we have explored each variable by itself, we can estimate the multiple regression model.</p>
<p><span class="math display">\[
\text{attitude}_i
= \beta_0 
+ \beta_1 \ \text{science_knowledge}_i
+ \beta_2 + \text{age}_i
+ \epsilon_i
\]</span></p>
<p>Regression results are often presented in a table that reports the coefficient estimates, their estimated standard errors, t-scores, and levels of statistical significance.</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<ul>
<li>Fit the model specified above using R</li>
<li>Check for violations of the model assumptions.</li>
<li>Do you believe the regression assumptions are violated?</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-103" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-103&#39;, &#39;sol-start-103&#39;)"> Solution </span>
</div>
<div id="sol-body-103" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(attitude <span class="sc">~</span> science_knowledge <span class="sc">+</span> age, <span class="at">data =</span> ebsurvey)</span></code></pre></div>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>)) <span class="co"># set 2 by 2 panels</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mdl)</span></code></pre></div>
<p><img src="1_10_bootstrap_reg_files/figure-html/unnamed-chunk-17-1.png" width="95%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)) <span class="co"># go back to 1 by 1 panels</span></span></code></pre></div>
<p>Based on the visual inspection of the plots, the assumptions appear to be violated.</p>
</div>
<p class="solution-end">
</p>
<p><br></p>
<p>If you are doubting that the model assumptions are satisfied, don’t throw your PC up in the air, but rather keep reading!</p>
</div>
<div id="the-bootstrap" class="section level1">
<h1>The Bootstrap</h1>
<p>The <em>bootstrap</em> is a general approach to assessing whether the sample results are statistically significant or not, which does not rely on specific distributional assumptions such as normality of the errors.
It is based on sampling repeatedly with replacement (to avoid always getting the original sample exactly) from the data at hand, and then computing the regression coefficients from each resample. We will equivalently use the word “bootstrap sample” or “resample” (for <strong>sample</strong> with <strong>re</strong>placement).</p>
<div class="frame">
<p>The basic principle is:</p>
<center>
<p><strong>The population is to the original sample</strong></p>
<p><strong>as</strong></p>
<p><strong>the original sample is to the bootstrap samples.</strong></p>
</center>
</div>
<p>Because we only have one sample of size <span class="math inline">\(n\)</span>, and we do not have access to the data for the entire population, we consider our original sample as our best approximation to the population.
To be more precise, we assume that the population is made up of many, many copies of our original sample. Then, we take multiple samples each of size <span class="math inline">\(n\)</span> from this assumed population. This is equivalent to sampling <em>with replacement</em> from the original sample.</p>
<p><img src="images/reg-boot.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Let’s see how this works in practice. Consider this as the original sample of <span class="math inline">\(n = 4\)</span> individuals:</p>
<p><span class="math display">\[
\begin{matrix}
\text{Individual, }i &amp; \text{Response, }y &amp; \text{Predictor, }x \\
1 &amp; 10.2 &amp; 7 \\
2 &amp; 5.7  &amp; 4 \\
3 &amp; 8.0  &amp; 5 \\
4 &amp; 9.1  &amp; 3 \\
\end{matrix}
\]</span></p>
<p>or, more compactly, the original sample is:</p>
<p><span class="math display">\[
(10.2, 7), (5.7, 4), (8.0, 5), (9.1, 3)
\]</span></p>
<p>A bootstrap sample is obtained by sampling 4 pairs from the original sample, with replacement. One such bootstrap sample could be:
<span class="math display">\[
(8.0, 5), (5.7, 4), (8.0, 5), (9.1, 3)
\]</span></p>
<p>You can see in the above, that it may happen to have repeated values in the bootstrap sample.</p>
<p>Then, fitting the linear model to these data, we can obtain a bootstrap intercept and bootstrap slope</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="fl">5.7</span>, <span class="dv">8</span>, <span class="fl">9.1</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">3</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x))</span></code></pre></div>
<pre><code>## (Intercept)           x 
##   8.9363636  -0.2909091</code></pre>
<p><span class="math display">\[
\widehat \beta_0^* = 8.94 \qquad \widehat \beta_1^* = -0.29
\]</span></p>
<p>Now, imagine doing this many times. That is, taking many bootstrap samples (say <span class="math inline">\(R = 1,000\)</span>), each of size <span class="math inline">\(n = 4\)</span> individuals, and computing the regression intercept and slope for each bootstrap sample.
You will obtain <span class="math inline">\(R\)</span> bootstrap intercepts and <span class="math inline">\(R\)</span> bootstrap slopes.</p>
<p>You can visualise the distribution of the bootstrap intercept and slopes with histograms:
<img src="1_10_bootstrap_reg_files/figure-html/unnamed-chunk-20-1.png" width="95%" style="display: block; margin: auto;" /></p>
<!-- 

<div class="optional-begin"><span id='opt-start-104' class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-104', 'opt-start-104')">  Using more equations... (optional)</span></div><div class="optional-body" id = "opt-body-104" style="display: none;">

 -->
<!-- We will explain, without loss of generality, the bootstrap for regression in the simple case where our sample data consist of measurements on a response $y$ and predictor $x$ for a sample of $n$ individuals (or units): -->
<!-- $$ -->
<!-- \begin{matrix} -->
<!-- \text{Individual, }i & \text{Response, }y & \text{Predictor, }x \\ -->
<!-- 1 & y_1 & x_1 \\ -->
<!-- 2 & y_2 & x_2 \\ -->
<!-- \vdots & \vdots & \vdots\\ -->
<!-- n & y_n & x_n \\ -->
<!-- \end{matrix} -->
<!-- $$ -->
<!-- We can write this in compact form by saying that we have sample data comprising $n$ pairs of (response, predictor) data. This is our _original sample_: -->
<!-- $$ -->
<!-- (y_1, x_1), (y_2, x_2), \dots, (y_n, x_n) -->
<!-- $$ -->
<!-- For the original sample, we can obtain estimated intercept and slope: -->
<!-- $$ -->
<!-- \begin{aligned} -->
<!-- \widehat \beta_0 &= \text{estimated intercept for original sample } (y_1, x_1), (y_2, x_2), \dots, (y_n, x_n)\\  -->
<!-- \widehat \beta_1 &= \text{estimated slope for original sample } (y_1, x_1), (y_2, x_2), \dots, (y_n, x_n) -->
<!-- \end{aligned} -->
<!-- $$ -->
<!-- To obtain one _bootstrap sample_ from the original sample, sample $n$ pairs with replacement from the original sample. Denote the new $n$ pairs with an asterisk. Note that we can have repetitions of pairs from the original sample: -->
<!-- $$ -->
<!-- (y_1, x_1)^*, (y_2, x_2)^*, \dots, (y_n, x_n)^* -->
<!-- $$ -->
<!-- Then, we can fit the linear model to the data in the bootstrap sample, and compute the regression coefficients in the bootstrap sample, $\widehat \beta_0^*$ and $\widehat \beta_1^*$. These two regression coefficients are examples of _bootstrap statistics_. We call _bootstrap statistic_ any numerical summary of the _bootstrap sample_, in the same way that a statistic is a numerical summary of a sample. -->
<!-- $$ -->
<!-- \begin{aligned} -->
<!-- \widehat \beta_0^* &= \text{estimated intercept for resample } (y_1, x_1)^*, (y_2, x_2)^*, \dots, (y_n, x_n)^*\\  -->
<!-- \widehat \beta_1^* &= \text{estimated slope for resample } (y_1, x_1)^*, (y_2, x_2)^*, \dots, (y_n, x_n)^* -->
<!-- \end{aligned} -->
<!-- $$ -->
<!-- Now, imagine doing this many times. That is, taking many bootstrap samples (say $R = 1,000$), each of size $n$ individuals, and computing the regression intercept and slope for each bootstrap sample. -->
<!-- You will obtain $R$ bootstrap intercepts and $R$ bootstrap slopes. Denote by $\widehat \beta_{0}^{(5)}$ the bootstrap intercept in the 5th bootstrap sample. Similarly, $\widehat \beta_{1}^{(5)}$ is the bootstrap slope in the 5th bootstrap sample. -->
<!-- $$ -->
<!-- \widehat \beta_{0}^{(1)}, \  -->
<!-- \widehat \beta_{0}^{(2)}, \dots, \  -->
<!-- \widehat \beta_{0}^{(R)} \\ -->
<!-- \widehat \beta_{1}^{(1)}, \  -->
<!-- \widehat \beta_{1}^{(2)}, \dots, \  -->
<!-- \widehat \beta_{1}^{(R)} -->
<!-- $$ -->
<!-- You can visualise the distribution of the $R = 1,000$ bootstrap intercepts and slopes with histograms: -->
<!-- ```{r echo = FALSE, fig.height = 4, fig.width = 10, out.width = '90%'} -->
<!-- par(mfrow = c(1,2), mar=c(4,5,1,1), mgp=c(2.5,.5,0)) -->
<!-- hist(rnorm(1000, 8, 0.2), xlab = expr(hat(beta)[0]^'*'), main = '',  -->
<!--      cex = 1.2, cex.lab = 1.2) -->
<!-- hist(rnorm(1000, -0.1, 0.1), xlab = expr(hat(beta)[1]^'*'), main = '',  -->
<!--      cex = 1.2, cex.lab = 1.2) -->
<!-- ``` -->
<!-- 

</div><p class="optional-end"></p>

 -->
<p><br></p>
<p>That sounds all nice in theory! But how do I actually do this in R? Is it difficult???</p>
<p>No, it’s super easy! Follow these steps:</p>
<p><strong>Step 1.</strong> Load the <code>car</code> library</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<p><strong>Step 2.</strong> Use the <code>Boot()</code> function (do not forget the uppercase B!) which takes as arguments:</p>
<ul>
<li>the fitted model</li>
<li><code>f</code>, saying which bootstrap statistics to compute on each bootstrap sample. By default <code>f = coef</code>, returning the regression coefficients.</li>
<li><code>R</code>, saying how many bootstrap samples to compute. By default <code>R = 999</code> but this could be any number. To experiment we recommend 1000, when you want to produce results for journals, it is typical to go with 10,000 or more.</li>
<li><code>ncores</code>, saying if to perform the calculations in parallel (and more efficiently). However, this will depend on your PC, and you need to find how many cores you have by running <code>parallel::detectCores()</code> on your PC. By default the function uses <code>ncores = 1</code>.</li>
</ul>
<p><strong>Step 3.</strong> Run the code. However, please remember that the <code>Boot()</code> function does <strong>not</strong> want a model which was fitted using data with NAs. In our case we are fine because we already removed them with <code>na.omit</code>.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>boot_mdl <span class="ot">&lt;-</span> <span class="fu">Boot</span>(mdl, <span class="at">R =</span> <span class="dv">1000</span>)</span></code></pre></div>
<p><strong>Step 4.</strong> Look at the summary of the bootstrap results:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(boot_mdl)</span></code></pre></div>
<pre><code>## 
## Number of bootstrap replications R = 1000 
##                     original    bootBias     bootSE    bootMed
## (Intercept)        2.7882487  1.7809e-03 0.05336055  2.7906120
## science_knowledge -0.0802763 -4.6092e-05 0.00442448 -0.0802842
## age                0.0023794 -2.5842e-05 0.00068194  0.0023333</code></pre>
<p>The above output shows, for each regression coefficient, the value in the original sample in the column <code>original</code>, and then we will focus on the <code>bootSE</code> column, which estimates the variability of the coefficient from bootstrap sample to bootstrap sample. The <code>bootSE</code> provides us the bootstrap standard error, or bootstrap SE in short. We use this to answer the key question of how accurate our estimate is.</p>
<p><strong>Step 5.</strong> Compute confidence intervals. Use your preferred confidence level, by default this is 95%:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Confint</span>(boot_mdl, <span class="at">level =</span> <span class="fl">0.95</span>, <span class="at">type =</span> <span class="st">&quot;perc&quot;</span>)</span></code></pre></div>
<pre><code>## Bootstrap percent confidence intervals
## 
##                       Estimate         2.5 %       97.5 %
## (Intercept)        2.788248712  2.6859109098  2.889940947
## science_knowledge -0.080276256 -0.0887702692 -0.071603932
## age                0.002379446  0.0009578011  0.003741873</code></pre>
<p>The <code>type = "perc"</code> argument tells R to return the values that comprise 95% of all values in between them, i.e. the value with 2.5% of observations below it and the value with 2.5% of observations above it and 97.5% of observations below it.</p>
<p>If you want to make it into a nice table:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Confint</span>(boot_mdl, <span class="at">type =</span> <span class="st">&quot;perc&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>, <span class="at">caption =</span> <span class="st">&#39;Bootstrap 95% CIs&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tbl-boot">Table 4: </span>Bootstrap 95% CIs
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
2.5 %
</th>
<th style="text-align:right;">
97.5 %
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
2.788
</td>
<td style="text-align:right;">
2.686
</td>
<td style="text-align:right;">
2.890
</td>
</tr>
<tr>
<td style="text-align:left;">
science_knowledge
</td>
<td style="text-align:right;">
-0.080
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
-0.072
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.001
</td>
<td style="text-align:right;">
0.004
</td>
</tr>
</tbody>
</table>
<div class="int">
<p>We are 95% confident that the population intercept is between 2.68 and 2.90.
We are 95% confident that the population slope for science knowledge is between -0.09 and -0.07.
We are 95% confident that the population slope for age is between 0.001 and 0.004.</p>
</div>
<div id="intercept" class="section level4">
<h4>Intercept</h4>
<p>The results in Table <a href="#tab:tbl-boot">4</a> report an estimate of the intercept (or constant) as equal to approximately 2.79.
The constant of a multiple regression model can be interpreted as the average expected value of the dependent variable when all of the independent variables equal zero. In this case, the independent variable science knowledge has only a handful of respondents that score zero, and no one is aged zero, so the constant by itself does not tell us much. Researchers do not often have predictions based on the intercept, so it often receives little attention. A better choice would be to mean centre age, and refit the model with a mean centred age variable!</p>
</div>
<div id="science-knowledge-slope" class="section level4">
<h4>Science knowledge slope</h4>
<p>The estimated value for the slope coefficient linking knowledge to attitude is estimated to be approximately -0.08. This represents the average marginal effect of knowledge on attitude, and can be interpreted as the expected change in the dependent variable on average for a one-unit increase in the independent variable, controlling for age. In this example, every increase in quiz score by one point is associated with a decrease in attitude score of about –0.08, adjusted for age.
Bearing in mind the valence of the question wording, this means that those who are more knowledgeable tend to be more favourable towards science – i.e. disagreeing with the statement.</p>
</div>
<div id="age-slope" class="section level4">
<h4>Age slope</h4>
<p>The slope coefficient linking age to attitude is estimated to be approximately 0.002. This represents the average marginal effect of each additional year on attitude, and can be interpreted as the expected change in the dependent variable on average for a one-unit increase in the independent variable, controlling for science knowledge. For this example, that means that for every year older a person is, their attitude score is expected to increase by 0.002, controlling for science knowledge. This may seem like a very small effect, but remember that this is the effect of only one additional year. Bearing in mind the valence of the question wording, this means that older people tend to be less favourable towards science – i.e. agreeing with the statement.</p>
<p>The bootstrap confidence intervals table also reports that the 95% confidence intervals for both slope estimates do not include 0. This leads us to reject both null hypotheses at the 5% significance level, and conclude that there appear to be relationships for both age and science knowledge with attitude to science and faith.</p>
<p>Remember the summary of them model:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = attitude ~ science_knowledge + age, data = ebsurvey)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.88643 -0.97484  0.00913  0.88427  2.21489 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        2.7882487  0.0537759  51.849  &lt; 2e-16 ***
## science_knowledge -0.0802763  0.0045095 -17.802  &lt; 2e-16 ***
## age                0.0023794  0.0006792   3.503 0.000461 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.196 on 10500 degrees of freedom
## Multiple R-squared:  0.03223,    Adjusted R-squared:  0.03204 
## F-statistic: 174.8 on 2 and 10500 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The R-squared for the model is 0.031, which means that approximately 3% of the variance in attitude is explained by science knowledge and age.</p>
<p><br></p>
<p>How can we visualise the bootstrap intercepts and slopes? They are stored in the <code>boot_mdl</code> object.</p>
<p>This will show you the <span class="math inline">\(R = 1000\)</span> estimates, using head to show only the top 6.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boot_mdl<span class="sc">$</span>t)</span></code></pre></div>
<pre><code>##      (Intercept) science_knowledge         age
## [1,]    2.736176       -0.07544872 0.002590834
## [2,]    2.798605       -0.07985701 0.001762165
## [3,]    2.748294       -0.07471438 0.001978664
## [4,]    2.822838       -0.08520539 0.002366432
## [5,]    2.800905       -0.07965154 0.002047476
## [6,]    2.873167       -0.08809269 0.002115399</code></pre>
<p>While this shows you the estimated intercept and slope in the original sample</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>boot_mdl<span class="sc">$</span>t0</span></code></pre></div>
<pre><code>##       (Intercept) science_knowledge               age 
##       2.788248712      -0.080276256       0.002379446</code></pre>
<p>You can visualise the uncertainty in the estimates by plotting histograms either manually:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(boot_mdl<span class="sc">$</span>t)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>plot_data</span></code></pre></div>
<pre><code>## # A tibble: 1,000 x 3
##    `(Intercept)` science_knowledge     age
##            &lt;dbl&gt;             &lt;dbl&gt;   &lt;dbl&gt;
##  1          2.74           -0.0754 0.00259
##  2          2.80           -0.0799 0.00176
##  3          2.75           -0.0747 0.00198
##  4          2.82           -0.0852 0.00237
##  5          2.80           -0.0797 0.00205
##  6          2.87           -0.0881 0.00212
##  7          2.83           -0.0847 0.00280
##  8          2.86           -0.0847 0.00179
##  9          2.82           -0.0795 0.00198
## 10          2.76           -0.0753 0.00231
## # ... with 990 more rows</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(science_knowledge)) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">&#39;white&#39;</span>)</span></code></pre></div>
<p><img src="1_10_bootstrap_reg_files/figure-html/unnamed-chunk-28-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Or using the built-in function from the <code>car</code> package, which simply takes the bootstrap results <code>boot_mdl</code>:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot_mdl, <span class="at">ci =</span> <span class="st">&quot;perc&quot;</span>, <span class="at">legend =</span> <span class="st">&quot;separate&quot;</span>)</span></code></pre></div>
<p><img src="1_10_bootstrap_reg_files/figure-html/unnamed-chunk-29-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="presenting-results" class="section level1">
<h1>Presenting results</h1>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Write a short paragraph summarising the results of this lab.</p>
<p>Include:</p>
<ol style="list-style-type: decimal">
<li>A brief description of which data were used to answer which questions.</li>
<li>A plot of your variables and summary statistics.</li>
<li>Describe your model and report results</li>
<li>Interpret results in context.</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-105" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-105&#39;, &#39;sol-start-105&#39;)"> Solution </span>
</div>
<div id="sol-body-105" class="solution-body" style="display: none;">
<p>We used a subset of data from the 2005 Eurobarometer 63.1 survey to investigate whether:</p>
<ul>
<li>There is a significant linear relationship between people’s age and their attitudes to science and faith after accounting for their scientific knowledge.</li>
<li>There is a significant linear relationship between people’s scientific knowledge and their attitudes to science and faith after accounting for their age.</li>
</ul>
<p>The data, excluding any missing values, include 10,503 individual respondents who were measured on 3 different attributes: (1) Score on a science “quiz” composed of 13 true/false items. (2) Attitude to science and faith (question wording: “We rely too much on science and not enough on faith”; responses on a 5-point scale from strongly disagree to strongly agree). (3) Age measured in years.
Figure <a href="#fig:res-descr-plot">1</a> displays the scatterplots of the pairwise relationships between the 3 variables. From the plot and the correlation matrix, displyed in Table <a href="#tab:res-descr-cor">5</a>, it appears that there is a weak negative linear association between attitude and science knowledge, and nearly no linear association between attitude and age.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:res-descr-plot"></span>
<img src="1_10_bootstrap_reg_files/figure-html/res-descr-plot-1.png" alt="Pairwise scatterplots of the variables." width="95%" />
<p class="caption">
Figure 1: Pairwise scatterplots of the variables.
</p>
</div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:res-descr-cor">Table 5: </span>Correlation matrix
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
science_knowledge
</th>
<th style="text-align:right;">
age
</th>
<th style="text-align:right;">
attitude
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
science_knowledge
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
-0.122
</td>
<td style="text-align:right;">
-0.176
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
-0.122
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.055
</td>
</tr>
<tr>
<td style="text-align:left;">
attitude
</td>
<td style="text-align:right;">
-0.176
</td>
<td style="text-align:right;">
0.055
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
</tbody>
</table>
<p>To answer the research hypotheses, we fitted the following regression model:
<span class="math display">\[
\text{attitude} = \beta_0 + \beta_1 \ \text{science_knowledge} + \beta_2 \ \text{age} + \epsilon
\]</span></p>
<p>Which resulted in the following estimated regression coefficients for the original sample:
<span class="math display">\[
\widehat{\text{attitude}} = 2.8 -0.08 \ \text{science_knowledge} + 0.0024 \ \text{age}
\]</span></p>
The model does not satisfy the regression assumptions, see Figure <a href="#fig:res-diag-plots">2</a>, and for this reason we will assess statistical significance using the boostrap approach with <span class="math inline">\(R = 1000\)</span> resamples.
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:res-diag-plots"></span>
<img src="1_10_bootstrap_reg_files/figure-html/res-diag-plots-1.png" alt="Diagnostic plots" width="95%" />
<p class="caption">
Figure 2: Diagnostic plots
</p>
</div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:resboottable">Table 6: </span>Bootstrap 95% CIs
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
2.5 %
</th>
<th style="text-align:right;">
97.5 %
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
2.788
</td>
<td style="text-align:right;">
2.686
</td>
<td style="text-align:right;">
2.890
</td>
</tr>
<tr>
<td style="text-align:left;">
science_knowledge
</td>
<td style="text-align:right;">
-0.080
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
-0.072
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.001
</td>
<td style="text-align:right;">
0.004
</td>
</tr>
</tbody>
</table>
<p>The 95% bootstrap confidence intervals are provided in Table <a href="#tab:resboottable">6</a>.
These results displayed suggest that there is a negative and statistically significant relationship between knowledge of science and attitude to science and faith. Specifically, the results show that for every additional correct quiz answer people give, we would expect the attitude score to be lower by about 0.08. For age, the effect is in the opposite direction. For every additional year older a person is, they are expected to score .002 more on the attitude scale. The R-squared for the model is 0.032, which means that approximately 3% of the variance in attitude is explained by science knowledge and age. This leaves the majority of variation in attitudes unexplained by our model. Thus we conclude that respondents with greater knowledge about science also tend to be more positive about it, regardless of their age, while older people are slightly less positive, irrespective of their level of knowledge.</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<p>Adapted from:</p>
<ul>
<li>Allum, N. (2015). Learn about multiple regression in SPSS with data from the eurobarometer (63.1, jan–feb 2005). In <em>SAGE Research Methods Datasets Part 1.</em> SAGE Publications, Ltd.</li>
</ul>
<!-- Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
