<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Model Comparison</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Intro to Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="1_02_slr.html">1/2: Intro to Linear Regression</a>
    </li>
    <li>
      <a href="1_03_slr_model_fit.html">1/3: More Linear Regression</a>
    </li>
    <li>
      <a href="1_04_mlr.html">1/4: Multiple Predictors</a>
    </li>
    <li>
      <a href="1_05_int_nc.html">1/5: Interactions: Num * Cat</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    More Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_07_int_nn.html">1/7: Interactions: Num * Num</a>
    </li>
    <li>
      <a href="1_08_int_cc.html">1/8: Interactions: Cat * Cat</a>
    </li>
    <li>
      <a href="1_09_assumptions.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="1_10_bootstrap_reg.html">1/10: Bootstrap &amp; Troubleshooting</a>
    </li>
    <li>
      <a href="1_11_write_up.html">1/11: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Analyzing Experimental Studies
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="2_01_model_comp.html">2/1: Model Comparisons</a>
    </li>
    <li class="dropdown-header">2/2: </li>
    <li class="dropdown-header">2/3: </li>
    <li class="dropdown-header">2/4: </li>
    <li class="dropdown-header">2/5: </li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">2/7: </li>
    <li class="dropdown-header">2/8: </li>
    <li class="dropdown-header">2/9: </li>
    <li class="dropdown-header">2/10: </li>
    <li class="dropdown-header">2/11: </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Model Comparison</h1>

</div>


<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand measures of model fit using F.<br />
</li>
<li>Understand the principles of model selection and how to compare models via F tests.</li>
<li>Understand AIC and BIC.</li>
</ol>
</div>
<div id="model-fit" class="section level1">
<h1>Model Fit</h1>
<div id="f-ratio" class="section level2 frame">
<h2>F-ratio</h2>
<p>As in simple linear regression, the F-ratio is used to test the null hypothesis that all regression slopes are zero.</p>
<p>It is called the F-ratio because it is the ratio of the how much of the variation is explained by the model (per paramater) versus how much of the variation is unexplained (per remaining degrees of freedom).</p>
<p><span class="math display">\[
F_{df_{model},df_{residual}} = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model}/df_{Model}}{SS_{Residual}/df_{Residual}} \\
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; df_{model} = k \\
&amp; df_{error} = n-k-1 \\
&amp; n = \text{sample size} \\
&amp; k  = \text{number of explanatory variables} \\
\end{align}
\]</span></p>
<hr />
<p><strong>In R,</strong> at the bottom of the output of <code>summary(&lt;modelname&gt;)</code>, you can view the F-ratio, along with an hypothesis test against the alternative hypothesis that the at least one of the coefficients <span class="math inline">\(\neq 0\)</span> (under the null hypothesis that all coefficients = 0, the ratio of explained:unexplained variance should be approximately 1):</p>
<div class="figure" style="text-align: left"><span style="display:block;" id="fig:mlroutputrf"></span>
<img src="images/mlroutputf.png" alt="Multiple regression output in R, summary.lm(). F statistic highlighted" width="60%" />
<p class="caption">
Figure 1: Multiple regression output in R, summary.lm(). F statistic highlighted
</p>
</div>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Run the code below. It reads in the wellbeing/rurality study data, and creates a new binary variable which specifies whether or not each participant lives in a rural location.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>mwdata2<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">&quot;https://uoepsy.github.io/data/wellbeing_rural.csv&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>mwdata2 <span class="ot">&lt;-</span> </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  mwdata2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">isRural =</span> <span class="fu">ifelse</span>(location<span class="sc">==</span><span class="st">&quot;rural&quot;</span>,<span class="st">&quot;rural&quot;</span>,<span class="st">&quot;notrural&quot;</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>Fit the following model, and assign it the name “wb_mdl1.”</p>
<p><span class="math inline">\(\text{Wellbeing} = \beta_0 + \beta_1 \cdot \text{Social Interactions} + \beta_2 \cdot \text{IsRural} + \epsilon\)</span></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-110" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-110&#39;, &#39;sol-start-110&#39;)"> Solution </span>
</div>
<div id="sol-body-110" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>wb_mdl1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> social_int <span class="sc">+</span> isRural, <span class="at">data=</span>mwdata2)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wb_mdl1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wellbeing ~ social_int + isRural, data = mwdata2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.3711  -3.1794   0.1097   2.5407  17.6324 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  34.11591    1.07052  31.868  &lt; 2e-16 ***
## social_int    0.38167    0.08257   4.622 6.85e-06 ***
## isRuralrural -4.85152    0.66283  -7.319 6.18e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.664 on 197 degrees of freedom
## Multiple R-squared:  0.2593, Adjusted R-squared:  0.2517 
## F-statistic: 34.47 on 2 and 197 DF,  p-value: 1.453e-13</code></pre>
</div>
<p class="solution-end">
</p>
</div>
<div id="model-comparison" class="section level1">
<h1>Model Comparison</h1>
<div id="incremental-f-test" class="section level2 frame">
<h2>Incremental F-test</h2>
<div class="yellow">
<p>If (<em>and only if</em>) two models are <strong>nested</strong>, can we compare them using an <strong>incremental F-test.</strong></p>
<div id="what-does-nested-mean" class="section level3">
<h3>What does <strong>nested</strong> mean?</h3>
<p>Consider that you have two regression models where Model 1 contains a subset of the predictors containted in the other Model 2 and is fitted to the same data. More simply, Model 2 contains all of the predictors included in Model 1, <strong>plus</strong> additional predictor(s). This means that Model 1 is <em>nested</em> within Model 2, or that Model 1 is a <em>submodel</em> of Model 2. These two terms, at least in this setting, are interchangeable - it might be easier to think of Model 1 as your null and Model 2 as your alternative.</p>
</div>
<div id="what-is-an-incremental-f-test" class="section level3">
<h3>What is an <strong>incremental F-test</strong>?</h3>
<p>This is a formal test of whether the additional predictors provide a better fitting model.<br />
Formally this is the test of:</p>
<ul>
<li><span class="math inline">\(H_0:\)</span> coefficients for the added/ommitted variables are all zero.</li>
<li><span class="math inline">\(H_1:\)</span> at least one of the added/ommitted variables has a coefficient that is not zero.</li>
</ul>
</div>
</div>
<p>The F-ratio for comparing the residual sums of squares between two models can be calculated as:</p>
<p><span class="math display">\[
F_{(df_R-df_F),df_F} = \frac{(SSR_R-SSR_F)/(df_R-df_F)}{SSR_F / df_F} \\
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; SSR_R = \text{residual sums of squares for the restricted model} \\
&amp; SSR_F = \text{residual sums of squares for the full model} \\
&amp; df_R = \text{residual degrees of freedom from the restricted model} \\
&amp; df_F = \text{residual degrees of freedom from the full model} \\
\end{align}
\]</span></p>
</div>
<div id="comparing-regression-models-with-anova" class="section level2 frame">
<h2>Comparing regression models with <code>anova()</code></h2>
<p>Remember that you want your models to be <em>parsimonious</em>, or in other words, only as complex as they need to be in order to describe the data well. This means that you need to be able to justify your model choice, and one way to do so is by comparing models via <code>anova()</code>. If your model with multiple IVs does not provide a significantly better fit to your data than a more simplistic model with less IVs, then the more simplistic model should be preferred.</p>
<p><strong>In R,</strong> we can conduct an incremental F-test by constructing two linear regression models, and passing them to the <code>anova()</code> function: <code>anova(model1, model2)</code>.</p>
<p>If the <em>p</em>-value is sufficiently low (i.e., below your predetermined significance level - usually .05), then you would conclude that model 2 is significantly better fitting than model 1. If p is not &lt; .05, then you should favour the more simplistic model.</p>
</div>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>The F-ratio you see at the bottom of <code>summary(model)</code> is actually a comparison between two models: your model (with some explanatory variables in predicting <span class="math inline">\(y\)</span>) and <strong>the null model.</strong> In regression, the null model can be thought of as the model in which all explanatory variables have zero regression coefficients. It is also referred to as the <strong>intercept-only model</strong>, because if all predictor variable coefficients are zero, then the only we are only estimating <span class="math inline">\(y\)</span> via an intercept (which will be the mean - <span class="math inline">\(\bar y\)</span>).</p>
<p>Use the code below to fit the null model.</p>
<p>Then, use the <code>anova()</code> function to perform a model comparison between your earlier model (wb_mdl1) and the null model. Remember that the null model tests the null hypothesis that all beta coefficients are zero. By comparing <em>null_model</em> to <em>wb_mdl1</em>, we can test whether we should include the two IVs of social_int and isRural.</p>
<p>Check that the F-statistic and the <em>p</em>-value are the the same as that which is given at the bottom of <code>summary(wb_mdl1)</code>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>null_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mwdata2)</span></code></pre></div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-111" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-111&#39;, &#39;sol-start-111&#39;)"> Solution </span>
</div>
<div id="sol-body-111" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the null model</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>null_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mwdata2)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># model comparison null vs wb_mdl1</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(null_model, wb_mdl1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: wellbeing ~ 1
## Model 2: wellbeing ~ social_int + isRural
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    199 5785.6                                  
## 2    197 4285.6  2      1500 34.475 1.453e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract f statistic from summary of wb_mdl1</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wb_mdl1)<span class="sc">$</span>fstatistic</span></code></pre></div>
<pre><code>##     value     numdf     dendf 
##  34.47463   2.00000 197.00000</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we can retrieve the p-value:</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>fstat <span class="ot">=</span> <span class="fu">summary</span>(wb_mdl1)<span class="sc">$</span>fstatistic[<span class="dv">1</span>]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>df_1 <span class="ot">=</span> <span class="fu">summary</span>(wb_mdl1)<span class="sc">$</span>fstatistic[<span class="dv">2</span>]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>df_2 <span class="ot">=</span> <span class="fu">summary</span>(wb_mdl1)<span class="sc">$</span>fstatistic[<span class="dv">3</span>]</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>(fstat, df_1, df_2, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>##        value 
## 1.452925e-13</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Does weekly outdoor time explain a significant amount of variance in wellbeing scores over and above weekly social interactions and location (rural vs not-rural)?</p>
<p>Provide an answer to this question by fitting and comparing two models (one of them you may already have fitted in an earlier question).</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-112" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-112&#39;, &#39;sol-start-112&#39;)"> Solution </span>
</div>
<div id="sol-body-112" class="solution-body" style="display: none;">
<p>We can compare the following models which predict wellbeing scores from weekly social interactions and location, with and without weekly outdoor time.</p>
<ul>
<li><span class="math inline">\(\text{Wellbeing} = \beta_0 + \beta_1 \cdot \text{Social Interactions} + \beta_2 \cdot \text{IsRural} + \epsilon\)</span></li>
<li><span class="math inline">\(\text{Wellbeing} = \beta_0 + \beta_1 \cdot \text{Social Interactions} + \beta_2 \cdot \text{IsRural} + \beta_3 \cdot \text{Outdoor time} + \epsilon\)</span></li>
</ul>
<p>We have already fitted the first model and assigned it the name <code>wb_mdl1</code>.</p>
<p>We need to fit the second:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>wb_mdl2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> social_int <span class="sc">+</span> isRural <span class="sc">+</span> outdoor_time, <span class="at">data=</span>mwdata2)</span></code></pre></div>
<p>Let’s look at the amount of variation in wellbeing scores explained by each model. Recall from semester 1 that this means looking at our R^2 value:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wb_mdl1)<span class="sc">$</span>adj.r.squared</span></code></pre></div>
<pre><code>## [1] 0.251737</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wb_mdl2)<span class="sc">$</span>adj.r.squared</span></code></pre></div>
<pre><code>## [1] 0.3037301</code></pre>
<p>The model <em>with</em> weekly outdoor time as a predictor explains 30% of the variance, and the model <em>without</em> explains 25%. But, from only looking at the proportion of variance accounted for in each model, we cannot determine which model is statistically a better fit. To answer the question ‘Does including weekly outdoor time as a predictor provide a significantly better fit of the data?’ we need to compare <strong>wb_mdl2</strong> to <strong>wb_mdl1</strong>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(wb_mdl1, wb_mdl2)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: wellbeing ~ social_int + isRural
## Model 2: wellbeing ~ 1 + social_int + isRural + outdoor_time
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    197 4285.6                                  
## 2    196 3967.6  1    318.03 15.711 0.0001033 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="int">
<p>Weekly outdoor time was found to explain a significant amount of variance in wellbeing scores over and above weekly social interactions and location (rural vs not-rural).<br />
<span class="math inline">\(F\)</span>(1 )=15.71, p&lt;.001.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Recall the data on Big 5 Personality traits, perceptions of social ranks, and depression and anxiety scale scores:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>scs_study <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://uoepsy.github.io/data/scs_study.csv&quot;</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(scs_study)</span></code></pre></div>
<pre><code>##        zo                 zc                 ze                 za          
##  Min.   :-2.81928   Min.   :-3.21819   Min.   :-3.00576   Min.   :-2.94429  
##  1st Qu.:-0.63089   1st Qu.:-0.66866   1st Qu.:-0.68895   1st Qu.:-0.69394  
##  Median : 0.08053   Median : 0.00257   Median :-0.04014   Median :-0.01854  
##  Mean   : 0.09202   Mean   : 0.01951   Mean   : 0.00000   Mean   : 0.00000  
##  3rd Qu.: 0.80823   3rd Qu.: 0.71215   3rd Qu.: 0.67085   3rd Qu.: 0.72762  
##  Max.   : 3.55034   Max.   : 3.08015   Max.   : 2.80010   Max.   : 2.97010  
##        zn               scs             dass      
##  Min.   :-1.4486   Min.   :27.00   Min.   :23.00  
##  1st Qu.:-0.7994   1st Qu.:33.00   1st Qu.:41.00  
##  Median :-0.2059   Median :35.00   Median :44.00  
##  Mean   : 0.0000   Mean   :35.77   Mean   :44.72  
##  3rd Qu.: 0.5903   3rd Qu.:38.00   3rd Qu.:49.00  
##  Max.   : 3.3491   Max.   :54.00   Max.   :68.00</code></pre>
<blockquote>
<p><strong>Research questions</strong></p>
<ul>
<li><p>Part 1: Beyond Neuroticism and its interaction with social comparison, does Openness predict symptoms of depression, anxiety and stress?</p></li>
<li><p>Part 2: Beyond Neuroticism and its interaction with social comparison, do other personality traits predict symptoms of depression, anxiety and stress?</p></li>
</ul>
</blockquote>
<p>Construct and compare multiple regression models to answer these two question. Remember to check that your models meet assumptions (for this exercises, a quick eyeball of the diagnostic plots will suffice. Were this an actual research project, you would want to provide a more thorough check, for instance conducting formal tests of the assumptions).<br />
<br>
Although the solutions are available immediately for this question, we strongly advocate that you attempt it yourself before looking at them.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-113" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-113&#39;, &#39;sol-start-113&#39;)"> Solution </span>
</div>
<div id="sol-body-113" class="solution-body" style="display: none;">
<p>First let us mean-center our social comparison scale scores, as we did in the previous labs.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>scs_study <span class="ot">&lt;-</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  scs_study <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">scs_mc =</span> scs <span class="sc">-</span> <span class="fu">mean</span>(scs)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>The first question is asking whether Openness improves model fit beyond a model with just Neuoriticism, social comparison score and their interaction.</p>
<p>Notice how our initial model has one very influential point, which we will remove:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dass_mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(dass <span class="sc">~</span> scs_mc <span class="sc">*</span> zn, <span class="at">data =</span> scs_study)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dass_mod1)</span></code></pre></div>
<p><img src="2_01_model_comp_files/figure-html/unnamed-chunk-14-1.png" width="60%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>dass_mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(dass <span class="sc">~</span> scs_mc <span class="sc">*</span> zn, <span class="at">data =</span> scs_study[<span class="sc">-</span><span class="dv">35</span>, ])</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dass_mod)</span></code></pre></div>
<p><img src="2_01_model_comp_files/figure-html/unnamed-chunk-16-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>And our model with the Openness included:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dass_mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(dass <span class="sc">~</span> scs_mc <span class="sc">*</span> zn <span class="sc">+</span> zo, <span class="at">data =</span> scs_study[<span class="sc">-</span><span class="dv">35</span>, ])</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dass_mod2)</span></code></pre></div>
<p><img src="2_01_model_comp_files/figure-html/unnamed-chunk-18-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Look at the summary of Model 2 - Openness is not a significant predictor of DASS scores (<em>p</em> = .18).</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dass_mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = dass ~ scs_mc * zn + zo, data = scs_study[-35, ])
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -16.4283  -3.9350  -0.0666   3.5911  17.1235 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 44.97898    0.22812 197.175  &lt; 2e-16 ***
## scs_mc      -0.54936    0.06554  -8.382 3.23e-16 ***
## zn           1.45113    0.22782   6.369 3.59e-10 ***
## zo          -0.30051    0.22204  -1.353    0.176    
## scs_mc:zn   -0.78795    0.06865 -11.478  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.778 on 650 degrees of freedom
## Multiple R-squared:  0.264,  Adjusted R-squared:  0.2595 
## F-statistic:  58.3 on 4 and 650 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Lets compare the two models:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(dass_mod1, dass_mod2)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: dass ~ scs_mc * zn
## Model 2: dass ~ scs_mc * zn + zo
##   Res.Df   RSS Df Sum of Sq      F Pr(&gt;F)
## 1    651 21763                           
## 2    650 21702  1    61.154 1.8316 0.1764</code></pre>
<div class="int">
<p>Openness did not explain a significant amount of variance in depression, anxiety and stress scores over and above Neuroticism and its interaction with social comparison.<br />
<span class="math inline">\(F\)</span>(1 )=1.83, p = 0.176.</p>
</div>
<p>The second question is asking whether including a group of predictors (the O, C, E, A personality traits) improves model fit beyond a model with just Neuoriticism, social comparison score and their interaction. We will need to compare this model (dass_mod3) to dass_mod1.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>dass_mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(dass <span class="sc">~</span> scs_mc <span class="sc">*</span> zn <span class="sc">+</span> zo <span class="sc">+</span> zc <span class="sc">+</span> ze <span class="sc">+</span> za, <span class="at">data =</span> scs_study[<span class="sc">-</span><span class="dv">35</span>, ])</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dass_mod3)</span></code></pre></div>
<p><img src="2_01_model_comp_files/figure-html/unnamed-chunk-22-1.png" width="60%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div>
<p>We can explore the individual coefficients of our full model, and we notice that none of the other personality variables (<code>zo</code>, <code>zc</code>, <code>ze</code>, <code>za</code>) significantly predict DASS-21 scores:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dass_mod3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = dass ~ scs_mc * zn + zo + zc + ze + za, data = scs_study[-35, 
##     ])
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -17.1455  -3.8155  -0.0066   3.6905  18.1483 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 44.97703    0.22635 198.708  &lt; 2e-16 ***
## scs_mc      -0.54832    0.06519  -8.412 2.58e-16 ***
## zn           1.41639    0.22661   6.250 7.44e-10 ***
## zo          -0.31435    0.22056  -1.425    0.155    
## zc           0.09134    0.22515   0.406    0.685    
## ze           0.52695    0.34233   1.539    0.124    
## za           0.33847    0.34281   0.987    0.324    
## scs_mc:zn   -0.78254    0.06817 -11.479  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.733 on 647 degrees of freedom
## Multiple R-squared:  0.279,  Adjusted R-squared:  0.2712 
## F-statistic: 35.76 on 7 and 647 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>However, when we compare the two models, we find that including these predictors does significantly improve model fit.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(dass_mod1, dass_mod3)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: dass ~ scs_mc * zn
## Model 2: dass ~ scs_mc * zn + zo + zc + ze + za
##   Res.Df   RSS Df Sum of Sq      F Pr(&gt;F)   
## 1    651 21763                              
## 2    647 21262  4    501.25 3.8133 0.0045 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="int">
<p>Whilst the other individual personality traits did not significantly predict DASS-21 scores, the model including these traits was significantly better fitting than the model including only Neuroticism and its interaction with social comparison.
<span class="math inline">\(F\)</span>(4 )=3.81, p = 0.004.</p>
</div>
<div id="stop-think" class="section level3">
<h3>Stop &amp; Think</h3>
<p>This conclusion may be a bit confusing - are we saying that none of Openness, Conscientiousness, Agreeableness, or Extraversion significantly predict DASS-21 scores, but collectively they do? This sort of discrepancy can often be the result of multicollinearity. Note that there may be some correlation between the personality variables - you could explore this by checking <code>vif()</code>. It could also be that one variable is <em>masking</em> the effect of the other. Check what happens when you remove one of the personality variables</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(dass_mod3)</span></code></pre></div>
<pre><code>##    scs_mc        zn        zo        zc        ze        za scs_mc:zn 
##  1.015133  1.015736  1.013310  1.008235  2.332486  2.342220  1.012475</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(dass <span class="sc">~</span> scs_mc <span class="sc">*</span> zn <span class="sc">+</span> zo <span class="sc">+</span> zc <span class="sc">+</span> ze, <span class="at">data =</span> scs_study[<span class="sc">-</span><span class="dv">35</span>, ]) <span class="sc">%&gt;%</span> summary</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = dass ~ scs_mc * zn + zo + zc + ze, data = scs_study[-35, 
##     ])
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -17.1327  -3.8012  -0.0145   3.7151  17.8952 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 44.97614    0.22634 198.709  &lt; 2e-16 ***
## scs_mc      -0.55175    0.06509  -8.476  &lt; 2e-16 ***
## zn           1.42834    0.22629   6.312 5.11e-10 ***
## zo          -0.30725    0.22044  -1.394 0.163853    
## zc           0.10062    0.22495   0.447 0.654794    
## ze           0.78223    0.22437   3.486 0.000523 ***
## scs_mc:zn   -0.78132    0.06816 -11.463  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.732 on 648 degrees of freedom
## Multiple R-squared:  0.2779, Adjusted R-squared:  0.2712 
## F-statistic: 41.56 on 6 and 648 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p class="solution-end">
</p>
<div id="aic-bic" class="section level2 frame">
<h2>AIC &amp; BIC</h2>
<div class="yellow">
<p>If models are <strong>not nested</strong>, we <strong>cannot</strong> compare them using an <strong>incremental F-test</strong>. Instead, for <strong>non-nested</strong> models, we can use information criterion statistics, such as <strong>AIC</strong> and <strong>BIC</strong>.</p>
<div id="what-does-non-nested-mean" class="section level3">
<h3>What does <strong>non-nested</strong> mean?</h3>
<p>Consider that you have two regression models where Model 1 contains different variables to those contained in Model 2, where both models are fitted to the same data. More simply, Model 1 and Model 2 contain unique variables that are not shared. This means that Model 1 and Model 2 are <strong>not</strong> nested.</p>
</div>
<div id="what-are-aic-bic" class="section level3">
<h3>What are <strong>AIC</strong> &amp; <strong>BIC</strong>?</h3>
<p>AIC (Akaike Information Criterion) and BIC (Bayesian Information Criterion) combine information about the sample size, the number of model parameters, and the residual sums of squares (<span class="math inline">\(SS_{residual}\)</span>). Models do not <em>need</em> to be nested to be compared via AIC and BIC, <strong>but</strong> they need to have been fit to the same dataset.</p>
<p>For both of these fit indices, lower values are better, and both include a penalty for the number of predictors in the model (although BIC’s penalty is harsher):</p>
<p><span class="math display">\[
AIC = n\,\text{ln}\left( \frac{SS_{residual}}{n} \right) + 2k \\
\quad \\
BIC = n\,\text{ln}\left( \frac{SS_{residual}}{n} \right) + k\,\text{ln}(n) \\
\quad \\
\begin{align}
&amp; \text{Where:} \\
&amp; SS_{residual} = \text{sum of squares residuals} \\
&amp; n = \text{sample size} \\
&amp; k = \text{number of explanatory variables} \\
&amp; \text{ln} = \text{natural log function} 
\end{align}
\]</span></p>
</div>
</div>
<hr />
<p><strong>In R,</strong> we can calculate AIC and BIC by using the <code>AIC()</code> and <code>BIC()</code> functions.</p>
</div>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Lets compare the AIC and BIC values of two models, each looking at the associations of DASS scores and two personality traits. Fit the following models, and compare using <code>AIC()</code> and <code>BIC()</code>. Report which model you think best fits the data.</p>
<ul>
<li><p><span class="math inline">\(\text{DASS} = \beta_0 + \beta_1 \cdot \text{Neuroticism} + \beta_2 \cdot \text{Extraversion} + \epsilon\)</span></p></li>
<li><p><span class="math inline">\(\text{DASS} = \beta_0 + \beta_1 \cdot \text{Openness} + \beta_2 \cdot \text{Agreeableness} +\epsilon\)</span></p></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-114" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-114&#39;, &#39;sol-start-114&#39;)"> Solution </span>
</div>
<div id="sol-body-114" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>dassNE <span class="ot">&lt;-</span> <span class="fu">lm</span>(dass <span class="sc">~</span> zn <span class="sc">+</span> ze, <span class="at">data =</span> scs_study[<span class="sc">-</span><span class="dv">35</span>, ])</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>dassOA <span class="ot">&lt;-</span> <span class="fu">lm</span>(dass <span class="sc">~</span> zo <span class="sc">+</span> za, <span class="at">data =</span> scs_study[<span class="sc">-</span><span class="dv">35</span>, ])</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(dassNE, dassOA)</span></code></pre></div>
<pre><code>##        df      AIC
## dassNE  4 4324.772
## dassOA  4 4348.892</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(dassNE, dassOA)</span></code></pre></div>
<pre><code>##        df      BIC
## dassNE  4 4342.710
## dassOA  4 4366.831</code></pre>
<div class="int">
<p>We used AIC and BIC model selection to distinguish between two possible models describing the relationship between several personality factors and DASS-21 scores. Our model with Neuroticism and Extroversion (AIC = 4324.77) included as predictors was better fitting than the alternative model with Openness and Agreeableness (AIC = 4348.89). Based on the BIC value of the dassNE model (BIC = 4342.71) we concluded that it was substantively better fitting than the alternative model (BIC = 4366.83).</p>
</div>
</div>
<p class="solution-end">
</p>
<div id="choosing-the-right-model-comparison-approach" class="section level2">
<h2>Choosing the Right Model Comparison Approach</h2>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>The code below fits 5 different models:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> social_int <span class="sc">+</span> outdoor_time, <span class="at">data =</span> mwdata2)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> social_int <span class="sc">+</span> outdoor_time <span class="sc">+</span> age, <span class="at">data =</span> mwdata2)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> social_int <span class="sc">+</span> outdoor_time <span class="sc">+</span> routine, <span class="at">data =</span> mwdata2)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> social_int <span class="sc">+</span> outdoor_time <span class="sc">+</span> routine <span class="sc">+</span> age, <span class="at">data =</span> mwdata2)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> social_int <span class="sc">+</span> outdoor_time <span class="sc">+</span> routine <span class="sc">+</span> steps_k, <span class="at">data =</span> mwdata2)</span></code></pre></div>
<p>For each of the below pairs of models, what methods are/are not available for us to use for comparison and why?</p>
<ul>
<li><code>model1</code> vs <code>model2</code></li>
<li><code>model2</code> vs <code>model3</code></li>
<li><code>model1</code> vs <code>model4</code></li>
<li><code>model3</code> vs <code>model5</code></li>
</ul>
<p>This flowchart might help you to reach your decision:</p>
<p><img src="images/comparisons_chart.png" width="100%" style="display: block; margin: auto auto auto 0;" /></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-115" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-115&#39;, &#39;sol-start-115&#39;)"> Solution </span>
</div>
<div id="sol-body-115" class="solution-body" style="display: none;">
<ul>
<li><p><code>model1</code> vs <code>model2</code><br />
These models are nested - <code>model2</code> contains all the variables of <code>model1</code> and they are fitted on the same dataset.<br />
We can therefore use an F-test or AIC and BIC.</p></li>
<li><p><code>model2</code> vs <code>model3</code><br />
These models are <strong>not</strong> nested, but they are fitted on the same dataset.<br />
We can therefore use AIC or BIC, but we cannot use an F-test.</p></li>
<li><p><code>model1</code> vs <code>model4</code>
These models are nested - <code>model4</code> contains all the variables of <code>model1</code> and they are fitted on the same dataset.<br />
We can therefore use an F-test or AIC and BIC.</p></li>
<li><p><code>model3</code> vs <code>model5</code><br />
These models are <strong>not</strong> nested, and they are <strong>not</strong> fitted on the same dataset. the “steps_k” variable contains missing values, and so these whole rows are excluded from <code>model5</code> (but they are included in <code>model3</code>). We cannot compare these models.</p></li>
</ul>
</div>
<p class="solution-end">
</p>
<hr />
<p>Extra reading: <a href="http://joshualoftus.com/post/model-selection-bias-invalidates-significance-tests/">Joshua Loftus’ Blog: Model selection bias invalidates significance tests</a></p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
