<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Coding Factors</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Intro to Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="1_02_slr.html">1/2: Intro to Linear Regression</a>
    </li>
    <li>
      <a href="1_03_slr_model_fit.html">1/3: More Linear Regression</a>
    </li>
    <li>
      <a href="1_04_mlr.html">1/4: Multiple Predictors</a>
    </li>
    <li>
      <a href="1_05_int_nc.html">1/5: Interactions: Num * Cat</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    More Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_07_int_nn.html">1/7: Interactions: Num * Num</a>
    </li>
    <li>
      <a href="1_08_int_cc.html">1/8: Interactions: Cat * Cat</a>
    </li>
    <li>
      <a href="1_09_assumptions.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="1_10_bootstrap_reg.html">1/10: Bootstrap &amp; Troubleshooting</a>
    </li>
    <li>
      <a href="1_11_write_up.html">1/11: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Analyzing Experimental Studies
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="2_01_model_comp.html">2/1: Model Comparisons</a>
    </li>
    <li>
      <a href="2_02_coding_factors.html">2/2: Coding Factors</a>
    </li>
    <li>
      <a href="2_03_cont_design_factanova.html">2/3: Contrasts, Study Design, &amp; Factorial ANOVA</a>
    </li>
    <li>
      <a href="2_04_factorial_anova.html">2/4: Two-Way ANOVA</a>
    </li>
    <li>
      <a href="2_05_multi_comp_writeup.html">2/5: Assumptions, Multiple Comparisons, Corrections, &amp; Write-Up Example</a>
    </li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="2_07_binary.html">2/7: Binary Logistic Regression</a>
    </li>
    <li class="dropdown-header">2/8: </li>
    <li class="dropdown-header">2/9: </li>
    <li class="dropdown-header">2/10: </li>
    <li class="dropdown-header">2/11: </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Coding Factors</h1>

</div>


<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand how to specify dummy and effects coding</li>
<li>Understand how to specify contracts to test specific effects</li>
</ol>
</div>
<div id="research-question" class="section level1">
<h1>Research question</h1>
<blockquote>
<p><em>Do you think the type of background music playing in a restaurant influences the amount of money that diners spend on their meal?</em></p>
</blockquote>
<div class="optional-begin">
<span id="opt-start-116" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-116&#39;, &#39;opt-start-116&#39;)"> Data: RestaurantSpending.csv</span>
</div>
<div id="opt-body-116" class="optional-body" style="display: none;">
<p><strong>Download link</strong></p>
<p><a href="https://uoepsy.github.io/data/RestaurantSpending.csv">Download the data
here</a></p>
<p><strong>Description</strong></p>
<p>A group of researchers wanted to test the claims reported in <span class="citation">(<a href="#ref-North2003" role="doc-biblioref">North, Shilcock, and Hargreaves 2003</a>)</span> on whether the type of background music playing in a restaurant influences the average amount of money spent by diners on their meal.</p>
<p>The group researchers got in touch with a restaurant and asked to alternate silence, popular music, and classical music on successive nights over 18 days. On those nights they recorded the mean spend per head for each table.</p>
<p>The following variables were collected:</p>
<ul>
<li><code>id</code>: Identifier for each diner</li>
<li><code>type</code>: type of music played (“Classical Music,” “Pop Music,” “No Music”)</li>
<li><code>amount</code>: restaurant spending per person (in pounds - £)</li>
</ul>
<p><strong>Preview</strong></p>
<p>The top six rows of the data are as follows:</p>
<center>
<table style="width:44%;">
<colgroup>
<col width="6%" />
<col width="25%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">id</th>
<th align="center">type</th>
<th align="center">amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">No Music</td>
<td align="center">23.15</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">Pop Music</td>
<td align="center">20.59</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">Pop Music</td>
<td align="center">19.18</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">Pop Music</td>
<td align="center">16.7</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">Classical Music</td>
<td align="center">25.91</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">Pop Music</td>
<td align="center">19.28</td>
</tr>
</tbody>
</table>
</center>
</div>
<p class="optional-end">
</p>
<div id="data-exploration-descriptives" class="section level2">
<h2>Data Exploration: Descriptives</h2>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<ol style="list-style-type: decimal">
<li>Load the <code>tidyverse</code> package.</li>
<li>Read the restaurant spending data into R using the function <code>read_csv()</code> and name the data <code>rest_spend</code>.</li>
<li>Check for the correct coding of all variables (i.e., categorical variables should be factors and numeric variables should be numeric).</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-117" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-117&#39;, &#39;sol-start-117&#39;)"> Solution </span>
</div>
<div id="sol-body-117" class="solution-body" style="display: none;">
<p>Load the tidyverse library:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>Read the data into R:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>rest_spend <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://uoepsy.github.io/data/RestaurantSpending.csv&#39;</span>)</span></code></pre></div>
<p>Check if the data were read into R correctly by examining the top six rows:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rest_spend)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##      id type            amount
##   &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
## 1     1 No Music          23.1
## 2     2 Pop Music         20.6
## 3     3 Pop Music         19.2
## 4     4 Pop Music         16.7
## 5     5 Classical Music   25.9
## 6     6 Pop Music         19.3</code></pre>
<p>Music type is a categorical variable but it is encoded as a character (<code>&lt;chr&gt;</code>) variable rather than a factor (<code>&lt;fctr&gt;</code>). Let’s fix this:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We could do this the standard way</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>rest_spend<span class="sc">$</span>type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(rest_spend<span class="sc">$</span>type)</span></code></pre></div>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Or the tidyverse way</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>rest_spend <span class="ot">&lt;-</span> rest_spend <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">type =</span> <span class="fu">as.factor</span>(type))</span></code></pre></div>
<p>And check again:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rest_spend)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##      id type            amount
##   &lt;dbl&gt; &lt;fct&gt;            &lt;dbl&gt;
## 1     1 No Music          23.1
## 2     2 Pop Music         20.6
## 3     3 Pop Music         19.2
## 4     4 Pop Music         16.7
## 5     5 Classical Music   25.9
## 6     6 Pop Music         19.3</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Produce a boxplot displaying the relationship between restaurant spending and music type, and comment on any visually observed differences among the sample means of the three background music types.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-118" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-118&#39;, &#39;sol-start-118&#39;)"> Solution </span>
</div>
<div id="sol-body-118" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> rest_spend, <span class="fu">aes</span>(<span class="at">x =</span> type, <span class="at">y =</span> amount)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Background music type&#39;</span>, <span class="at">y =</span> <span class="st">&#39;Restaurant spending (in GBP)&#39;</span>)</span></code></pre></div>
<p><img src="2_02_coding_factors_files/figure-html/unnamed-chunk-11-1.png" width="60%" style="display: block; margin: auto;" /></p>
<div class="int">
<p>From the boxplots, it seems that customers without background music or pop music had a similar average restaurant spending.</p>
<p>Furthermore, the average restaurant spending seems to be higher for those who had a classical music background compared to the customers either without music or with a pop music background.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>For the restaurant spending data, what is the number of groups (<span class="math inline">\(g\)</span>) and the numbers of observations per group (<span class="math inline">\(n\)</span>)? What was the average spending and standard deviation of each group?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-119" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-119&#39;, &#39;sol-start-119&#39;)"> Solution </span>
</div>
<div id="sol-body-119" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>rest_spend <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(type) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">M =</span> <span class="fu">mean</span>(amount), </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">SD =</span> <span class="fu">sd</span>(amount))</span></code></pre></div>
<pre><code>## # A tibble: 3 x 4
##   type                n     M    SD
##   &lt;fct&gt;           &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Classical Music   120  24.2  1.89
## 2 No Music          120  22.1  3.44
## 3 Pop Music         120  21.9  2.97</code></pre>
<p>There are three groups, one for each music type: “Classical Music,” “No Music,” “Pop Music.” Hence, <span class="math inline">\(g = 3\)</span>. There are 120 observations for each group, i.e. <span class="math inline">\(n = 120\)</span>.</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="levels-of-variable-side-constraints" class="section level2">
<h2>Levels of Variable &amp; Side Constraints</h2>
<div id="levels-of-variable" class="section level3">
<h3>Levels of variable</h3>
<p>R by default orders the levels of a categorical variable in alphabetical order:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(rest_spend<span class="sc">$</span>type)</span></code></pre></div>
<pre><code>## [1] &quot;Classical Music&quot; &quot;No Music&quot;        &quot;Pop Music&quot;</code></pre>
<p>If we follow the same approach and order the groups by alphabetical ordering, we can represent the data as follows:</p>
<table>
<thead>
<tr class="header">
<th align="center">Population Name</th>
<th align="center">Population ID</th>
<th align="center">Sample observations</th>
<th align="center">Population mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Classical Music</td>
<td align="center">1</td>
<td align="center"><span class="math inline">\(y_{1,1}, y_{1,2}, ..., y_{1,n}\)</span></td>
<td align="center"><span class="math inline">\(\mu_{1}\)</span></td>
</tr>
<tr class="even">
<td align="center">No Music</td>
<td align="center">2</td>
<td align="center"><span class="math inline">\(y_{2,1}, y_{2,2}, ..., y_{2,n}\)</span></td>
<td align="center"><span class="math inline">\(\mu_{2}\)</span></td>
</tr>
<tr class="odd">
<td align="center">Pop Music</td>
<td align="center">3</td>
<td align="center"><span class="math inline">\(y_{3,1}, y_{3,2}, ..., y_{3,n}\)</span></td>
<td align="center"><span class="math inline">\(\mu_{3}\)</span></td>
</tr>
</tbody>
</table>
<div id="sum-to-zero-constraint---effects-coding" class="section level4 frame">
<h4>Sum to zero constraint - effects coding</h4>
<p>Under the constraint <span class="math inline">\(\beta_1 + \beta_2 + \beta_3 = 0\)</span>, the model coefficients are interpreted as follows:</p>
<ul>
<li><span class="math inline">\(\beta_0 = \mu\)</span> is interpreted as the overall or global mean — that is, the population mean when all the groups are combined;</li>
<li><span class="math inline">\(\beta_i = \mu_i - \mu\)</span> is interpreted as the effect of group <span class="math inline">\(i\)</span> — that is, the difference between the population mean for group <span class="math inline">\(i\)</span>, <span class="math inline">\(\mu_i\)</span>, and the global population mean, <span class="math inline">\(\mu\)</span>.</li>
</ul>
<p>We can fit the linear regression model:</p>
<p><span class="math display">\[
y 
= b_0 
+ b_1 \ \text{EffectLevel1} 
+ b_2 \ \text{EffectLevel2} 
+ \epsilon
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\text{EffectLevel1} = \begin{cases}
1  &amp; \text{if observation is from category 1} \\
0  &amp; \text{if observation is from category 2} \\
-1 &amp; \text{otherwise}
\end{cases}
\\
\text{EffectLevel2} = \begin{cases}
0  &amp; \text{if observation is from category 1} \\
1  &amp; \text{if observation is from category 2} \\
-1 &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>Schematically,</p>
<p><span class="math display">\[
\begin{matrix}
\textbf{Level}  &amp; \textbf{EffectLevel1} &amp; \textbf{EffectLevel2} \\
\hline
\text{Classical Music} &amp; 1   &amp; 0    \\
\text{No Music}        &amp; 0   &amp; 1    \\
\text{Pop Music}       &amp; -1  &amp; -1
\end{matrix}
\]</span></p>
<div class="blue">
<p>In <strong>R</strong> this is simply done by saying:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(rest_spend<span class="sc">$</span>type) <span class="ot">&lt;-</span> <span class="st">&quot;contr.sum&quot;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>mdl_sum <span class="ot">&lt;-</span> <span class="fu">lm</span>(amount <span class="sc">~</span> type, <span class="at">data =</span> rest_spend)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mdl_sum)</span></code></pre></div>
<pre><code>## (Intercept)       type1       type2 
##  22.7381560   1.4359846  -0.5967688</code></pre>
<p>where <code>type</code> is a factor. In such case R will automatically create the two variables <code>EffectLevel1</code> and <code>EffectLevel2</code> for you!</p>
<p>The <code>summary(mdl)</code> will return 3 estimated coefficients:</p>
<ul>
<li><span class="math inline">\(b_0 = 22.74\)</span> is estimated overall mean</li>
<li><span class="math inline">\(b_1 = 1.44\)</span> is the effect of Classical Music</li>
<li><span class="math inline">\(b_2 = -0.6\)</span> is the effect of No Music</li>
<li><strong>NOTE</strong>: The effect of Pop Music is not shown by <code>summary</code> as it is found via the side-constraint as <span class="math inline">\(b_3 = -(b_1 + b_2) = -0.84\)</span>!</li>
</ul>
</div>
</div>
<div id="reference-group-constraint---dummy-coding" class="section level4 frame">
<h4>Reference group constraint - dummy coding</h4>
<p>Under the constraint <span class="math inline">\(\beta_1 = 0\)</span>, meaning that the first factor level is the reference group,</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is interpreted as <span class="math inline">\(\mu_1\)</span>, the mean response for the reference group (group 1);</li>
<li><span class="math inline">\(\beta_i\)</span> is interpreted as the difference between the mean response for group <span class="math inline">\(i\)</span> and the reference group.</li>
</ul>
<p>We can fit the linear regression model:</p>
<p><span class="math display">\[
y 
= b_0 
+ b_1 \ \text{IsTypeNoMusic} 
+ b_2 \ \text{IsTypePopMusic} 
+\epsilon
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\text{IsTypeNoMusic} = \begin{cases}
1 &amp; \text{if observation is from the No Music category} \\
0 &amp; \text{otherwise}
\end{cases}
\\
\text{IsTypePopMusic} = \begin{cases}
1 &amp; \text{if observation is from the Pop Music category} \\
0 &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>Schematically,</p>
<p><span class="math display">\[
\begin{matrix}
\textbf{Level}  &amp; \textbf{IsTypeNoMusic} &amp; \textbf{IsTypePopMusic} \\
\hline
\text{Classical Music} &amp; 0   &amp; 0   \\
\text{No Music}        &amp; 1   &amp; 0   \\
\text{Pop Music}       &amp; 0   &amp; 1
\end{matrix}
\]</span></p>
<div class="blue">
<p>In <strong>R</strong> this is simply done by saying:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(rest_spend<span class="sc">$</span>type) <span class="ot">&lt;-</span> <span class="st">&quot;contr.treatment&quot;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>mdl_trt <span class="ot">&lt;-</span> <span class="fu">lm</span>(amount <span class="sc">~</span> type, <span class="at">data =</span> rest_spend)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mdl_trt)</span></code></pre></div>
<pre><code>##   (Intercept)  typeNo Music typePop Music 
##     24.174141     -2.032753     -2.275200</code></pre>
<p>where <code>type</code> is a factor. In such case R will automatically create the two dummy variables <code>IsTypeNoMusic</code> and <code>IsTypePopMusic</code> for you!</p>
<p>The <code>summary(mdl)</code> will return 3 estimated coefficients:</p>
<ul>
<li><span class="math inline">\(b_0 = 24.17\)</span> is the mean of the base level (level 1)</li>
<li><span class="math inline">\(b_1 = -2.03\)</span> is the effect of No Music</li>
<li><span class="math inline">\(b_2 = -2.28\)</span> is the effect of Pop Music</li>
<li><strong>NOTE</strong>: The effect of Classical Music is not shown as it is equal to zero by the constraint!</li>
</ul>
</div>
</div>
</div>
<div id="side-contraints" class="section level3">
<h3>Side Contraints</h3>
<p>Possible side-constraints on the parameters are:</p>
<table>
<colgroup>
<col width="14%" />
<col width="30%" />
<col width="38%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Name</th>
<th align="center">Constraint</th>
<th align="center">Meaning of <span class="math inline">\(\beta_0\)</span></th>
<th align="center">R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Sum to zero (Effects Coding)</td>
<td align="center"><span class="math inline">\(\beta_1 + \beta_2 + \beta_3 = 0\)</span></td>
<td align="center"><span class="math inline">\(\beta_0 = \mu\)</span></td>
<td align="center"><code>contr.sum</code></td>
</tr>
<tr class="even">
<td align="center">Reference group (Dummy Coding)</td>
<td align="center"><span class="math inline">\(\beta_1 = 0\)</span></td>
<td align="center"><span class="math inline">\(\beta_0 = \mu_1\)</span></td>
<td align="center"><code>contr.treatment</code></td>
</tr>
</tbody>
</table>
<div class="yellow">
<p><strong>IMPORTANT</strong></p>
<ul>
<li><p>By default R uses the reference group constraint</p></li>
<li><p>If your factor has <span class="math inline">\(g\)</span> levels, your regression model will have <span class="math inline">\(g-1\)</span> dummy variables (R creates them for you)</p></li>
</ul>
</div>
</div>
</div>
</div>
<div id="anova-f-test" class="section level1">
<h1>ANOVA F-test</h1>
<p>Since R uses the reference group constraint, in this section and the next one, we will not specify any side-constraints, meaning that <span class="math inline">\(\beta_1 = 0\)</span>.</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Fit a linear model to the data, having <code>amount</code> as response variable and the factor <code>type</code> as predictor. Call the fitted model <code>mdl_rg</code> (for reference group constraint)</p>
<p>Identify the relevant pieces of information from the commands <code>anova(mdl_rg)</code> and <code>summary(mdl_rg)</code> that can be used to conduct an ANOVA F-test against the null hypothesis that all population means are equal.</p>
<p>Interpret the F-test results in the context of the ANOVA null hypothesis.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-120" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-120&#39;, &#39;sol-start-120&#39;)"> Solution </span>
</div>
<div id="sol-body-120" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mdl_rg <span class="ot">&lt;-</span> <span class="fu">lm</span>(amount <span class="sc">~</span> type, <span class="at">data =</span> rest_spend)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>mdl_rg</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Coefficients:
##   (Intercept)   typeNo Music  typePop Music  
##        24.174         -2.033         -2.275</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl_rg)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.433 -1.886  0.127  1.755 11.285 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    24.1741     0.2593  93.211  &lt; 2e-16 ***
## typeNo Music   -2.0328     0.3668  -5.542 5.81e-08 ***
## typePop Music  -2.2752     0.3668  -6.203 1.53e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.841 on 357 degrees of freedom
## Multiple R-squared:  0.1151, Adjusted R-squared:  0.1101 
## F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mdl_rg)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: amount
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## type        2  374.7 187.348  23.211 3.335e-10 ***
## Residuals 357 2881.5   8.071                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The model summary returns the F-test of model utility which, in this case, corresponds to the ANOVA F-test against the null hypothesis of equal population means.</p>
<p>The relevant line from <code>summary()</code> is:</p>
<pre><code>F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<p>The relevant parts from <code>anova()</code> are:</p>
<ul>
<li><code>F value</code> of <code>23.211</code></li>
<li>The <code>Df</code> column giving <code>2</code> and <code>357</code> degrees of freedom</li>
<li>The p-value of the test, reported under <code>Pr(&gt;F)</code> as <code>3.335e-10 ***</code>.</li>
</ul>
<p>We can write this up as follows:</p>
<div class="int">
<p>We performed an analysis of variance against the null hypothesis of equal population mean spending across three types of background music, <span class="math inline">\(F(2, 357) = 23.21\)</span>, <span class="math inline">\(p &lt; .001\)</span>.</p>
<p>The large observed F statistic leads to a very small <em>p</em>-value, meaning that such a large observed variability among the mean restaurant spending across the different music types, compared to the variability in the residuals, is very unlikely to happen by chance alone if the population means where all the same.</p>
<p>For this reason, at the 5% significance level we reject the null hypothesis as there is strong evidence that at least two population means differ.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="reference-group-dummy-constraint" class="section level1">
<h1>Reference group (dummy) constraint</h1>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Examine and investigate the meaning of the coefficients in the output of <code>summary(mdl_rg)</code>. Next, obtain the estimated (or predicted) group means for the “Classical Music,” “No Music,” and “Pop Music” groups by using the <code>predict(mdl_rg, newdata = ...)</code> function.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-121" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-121&#39;, &#39;sol-start-121&#39;)"> Solution </span>
</div>
<div id="sol-body-121" class="solution-body" style="display: none;">
<p>Let’s recall the model summary:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl_rg)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.433 -1.886  0.127  1.755 11.285 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    24.1741     0.2593  93.211  &lt; 2e-16 ***
## typeNo Music   -2.0328     0.3668  -5.542 5.81e-08 ***
## typePop Music  -2.2752     0.3668  -6.203 1.53e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.841 on 357 degrees of freedom
## Multiple R-squared:  0.1151, Adjusted R-squared:  0.1101 
## F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<p>The interpretation is as follows</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Coefficient</th>
<th align="center">Estimate</th>
<th align="center">Corresponds to</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">(Intercept)</td>
<td align="center">24.1741</td>
<td align="center"><span class="math inline">\(\hat \beta_0 = \hat \mu_1\)</span></td>
</tr>
<tr class="even">
<td align="center">typeNo Music</td>
<td align="center">-2.0328</td>
<td align="center"><span class="math inline">\(\hat \beta_2 = \hat \mu_2 - \hat \beta_0 = \hat \mu_2 - \hat \mu_1\)</span></td>
</tr>
<tr class="odd">
<td align="center">typePop Music</td>
<td align="center">-2.2752</td>
<td align="center"><span class="math inline">\(\hat \beta_3 = \hat \mu_3 - \hat \beta_0 = \hat \mu_3 - \hat \mu_1\)</span></td>
</tr>
</tbody>
</table>
<p>The estimate corresponding to (Intercept) contains <span class="math inline">\(\hat \beta_0 = \hat \mu_1 = 24.17\)</span>. The estimated average spending for those having a classical music background is approximately £24.2.</p>
<p>The next estimate corresponds to <code>typeNo Music</code> and is <span class="math inline">\(\hat \beta_2 = -2.033\)</span>. The difference in mean spending between <code>No Music</code> and <code>Classical Music</code> is estimated to be <span class="math inline">\(-2.033\)</span>. In other words, people with a silent background seem to spend approximately £2 less than those having a classical music background.</p>
<p>The estimate corresponding to <code>typePop Music</code> is <span class="math inline">\(\hat \beta_3 = -2.275\)</span>. This is the estimated difference in mean spending between <code>Pop Music</code> and <code>Classical Music</code>. People with a pop music background seem to spend approximately £2.3 less than those with a classical music background.</p>
<p>Hence, for all levels except the reference group we see differences to the reference group while the estimate of the reference level can be found next to <code>(Intercept)</code>.</p>
<p>It is also important to notice how the coefficients names are written. They are a combination of <code>factor name</code> and <code>level name</code>, such as <code>typeNo Music</code>.
The only coefficient that is missing is <code>typeClassical Music</code>, the one corresponding to the reference category <code>Classical Music</code>.</p>
<p>To use <code>preditct</code>, you first need to define a data frame with a column having the same name as the factor in the fitted model. Then, specify all the groups (= levels) for which you would like the predicted mean.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>query_groups <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">type =</span> <span class="fu">c</span>(<span class="st">&quot;Classical Music&quot;</span>, <span class="st">&quot;No Music&quot;</span>, <span class="st">&quot;Pop Music&quot;</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>query_groups</span></code></pre></div>
<pre><code>## # A tibble: 3 x 1
##   type           
##   &lt;chr&gt;          
## 1 Classical Music
## 2 No Music       
## 3 Pop Music</code></pre>
<p>Pass the data frame to the predict function using the <code>newdata =</code> argument. The predict function will match the column named <code>type</code> with the predictor called <code>type</code> in the fitted model <code>mdl_rg</code>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mdl_rg, <span class="at">newdata =</span> query_groups)</span></code></pre></div>
<pre><code>##        1        2        3 
## 24.17414 22.14139 21.89894</code></pre>
<p>Or:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>query_groups <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> <span class="fu">predict</span>(mdl_rg, <span class="at">newdata =</span> .))</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   type             pred
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 Classical Music  24.2
## 2 No Music         22.1
## 3 Pop Music        21.9</code></pre>
<p>Hence,</p>
<ul>
<li><span class="math inline">\(\hat \mu_\text{Classical Music} = \hat \mu_1 = 24.17\)</span></li>
<li><span class="math inline">\(\hat \mu_\text{No Music} = \hat \mu_2 = 22.14\)</span></li>
<li><span class="math inline">\(\hat \mu_\text{Pop Music} = \hat \mu_3 = 21.90\)</span></li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>It actually makes more sense to have “No Music” as reference group.</p>
<p>Open the help page of the function <code>fct_relevel()</code>, and look at the examples.</p>
<p>Within the <code>rest_sped</code> data, reorder the levels of the factor <code>type</code> so that your reference group is “No Music.”</p>
<div class="yellow">
<p><strong>NOTE</strong></p>
<p>Because you reordered the levels, now</p>
<ul>
<li><span class="math inline">\(\mu_1\)</span> = mean of no music group</li>
<li><span class="math inline">\(\mu_2\)</span> = mean of classical music group</li>
<li><span class="math inline">\(\mu_3\)</span> = mean of pop music group</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-122" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-122&#39;, &#39;sol-start-122&#39;)"> Solution </span>
</div>
<div id="sol-body-122" class="solution-body" style="display: none;">
<p>Check the help page:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>?fct_relevel</span></code></pre></div>
<p>Select “No Music” to be the first level:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>rest_spend<span class="sc">$</span>type <span class="ot">&lt;-</span> <span class="fu">fct_relevel</span>(rest_spend<span class="sc">$</span>type, <span class="st">&quot;No Music&quot;</span>)</span></code></pre></div>
<p>Check that the factor levels are now in the correct order:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(rest_spend<span class="sc">$</span>type)</span></code></pre></div>
<pre><code>## [1] &quot;No Music&quot;        &quot;Classical Music&quot; &quot;Pop Music&quot;</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Refit the linear model, and inspect the model summary once more.</p>
<p>Do you notice any change in the estimated coefficients? Do you notice any change in the F-test for model utility?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-123" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-123&#39;, &#39;sol-start-123&#39;)"> Solution </span>
</div>
<div id="sol-body-123" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>mdl_rg <span class="ot">&lt;-</span> <span class="fu">lm</span>(amount <span class="sc">~</span> type, <span class="at">data =</span> rest_spend)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl_rg)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.433 -1.886  0.127  1.755 11.285 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          22.1414     0.2593  85.373  &lt; 2e-16 ***
## typeClassical Music   2.0328     0.3668   5.542 5.81e-08 ***
## typePop Music        -0.2424     0.3668  -0.661    0.509    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.841 on 357 degrees of freedom
## Multiple R-squared:  0.1151, Adjusted R-squared:  0.1101 
## F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<p>The displayed coefficients have changed as now the (Intercept) represents the new reference group, which is “No Music.”</p>
<p>However, by checking the calculations, this model is equivalent to the previous one as the predicted group means are the same.</p>
<ul>
<li>Predicted mean of “No Music” <span class="math inline">\(\hat \mu_\text{No Music}\)</span> = 22.1414</li>
<li>Predicted mean of “Classical Music” <span class="math inline">\(\hat \mu_\text{Classical Music}\)</span> = 22.1414 + 2.0328 = 24.1742</li>
<li>Predicted mean of “Pop Music” = <span class="math inline">\(\hat \mu_\text{Pop Music}\)</span> = 22.1414 - 0.2424 = 21.899</li>
</ul>
<p>The <code>predict</code> function returns the same output:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>query_groups <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">type =</span> <span class="fu">levels</span>(rest_spend<span class="sc">$</span>type))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>query_groups</span></code></pre></div>
<pre><code>## # A tibble: 3 x 1
##   type           
##   &lt;chr&gt;          
## 1 No Music       
## 2 Classical Music
## 3 Pop Music</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>query_groups <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> <span class="fu">predict</span>(mdl_rg, <span class="at">newdata =</span> .))</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   type             pred
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 No Music         22.1
## 2 Classical Music  24.2
## 3 Pop Music        21.9</code></pre>
</div>
<p class="solution-end">
</p>
</div>
<div id="sum-to-zero-effects-constraint" class="section level1">
<h1>Sum-to-zero (effects) constraint</h1>
<p>Let’s now change the side-constraint from the R default (the reference group or <code>contr.treatment</code> constraint) to the sum-to-zero constraint using <code>contr.sum</code>.</p>
<p>Recall that under this constraint the interpretation of the coefficients becomes:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> represents the global mean</li>
<li><span class="math inline">\(\beta_i\)</span> the effect due to group <span class="math inline">\(i\)</span> — that is, the mean response in group <span class="math inline">\(i\)</span> minus the global mean</li>
</ul>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Set the sum to zero constraint for the factor <code>type</code> of background music.</p>
<p>Fit again the linear model using <code>amount</code> as response variable and <code>type</code> as predictor. Call the fitted model using the sum to zero constraint <code>mdl_stz</code> (for sum to zero).</p>
<p>Examine the output of the <code>summary(mdl_stz)</code> function:</p>
<ul>
<li>Do the displayed coefficients change? What do they represent now?</li>
<li>Do the predicted group means change?</li>
<li>Is the model utility F-test still the same? Why do you think it’s the case?</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-124" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-124&#39;, &#39;sol-start-124&#39;)"> Solution </span>
</div>
<div id="sol-body-124" class="solution-body" style="display: none;">
<p>Set the sum to zero contrast to the <code>type</code> factor:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(rest_spend<span class="sc">$</span>type) <span class="ot">&lt;-</span> <span class="st">&quot;contr.sum&quot;</span></span></code></pre></div>
<p>Re-fit the model and inspect the summary output:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>mdl_stz <span class="ot">&lt;-</span> <span class="fu">lm</span>(amount <span class="sc">~</span> type, <span class="at">data =</span> rest_spend)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl_stz)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.433 -1.886  0.127  1.755 11.285 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  22.7382     0.1497 151.856  &lt; 2e-16 ***
## type1        -0.5968     0.2118  -2.818   0.0051 ** 
## type2         1.4360     0.2118   6.781 4.95e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.841 on 357 degrees of freedom
## Multiple R-squared:  0.1151, Adjusted R-squared:  0.1101 
## F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<p>With the new side-constraint, we get different values for the model coefficients because the meaning of the parameters has changed. If we closely inspect the output, we can also notice that a slightly different naming has been used.</p>
<p>Instead of <code>factor name</code> and <code>level name</code> (such as <code>typeNo Music</code>), we get <code>factor name</code> and <code>level number</code> (e.g. <code>type1</code>).
Here, <code>type1</code> simply means the first level of the factor <code>type</code>, while <code>type2</code> means the second level of the factor <code>type</code>.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(rest_spend<span class="sc">$</span>type)</span></code></pre></div>
<pre><code>## [1] &quot;No Music&quot;        &quot;Classical Music&quot; &quot;Pop Music&quot;</code></pre>
<p>The first level is “No Music,” while the second level is “Classical Music.”</p>
<ul>
<li>The estimate for <code>(Intercept)</code> is now the <em>global mean</em> of the data.</li>
<li>The estimate for <code>type1</code> is now the difference of the first group (“No Music”) to the global mean</li>
<li>The estimate for <code>type2</code> is now the difference of the second group (“Classical Music”) to the global mean</li>
</ul>
<p>The estimate for <code>type3</code>, representing the difference of “Pop Music” to the global mean is not shown. Because of the side-constraint, we know it must be <span class="math inline">\(\beta_3 = - (\beta_1 + \beta_2) = - (-0.5968 + 1.4360) = -0.8392\)</span>.</p>
<p>Underneath we see the group effects that need to be added to the global mean to obtain the predicted group means.</p>
<p>Compute the predicted group means:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>query_groups <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> <span class="fu">predict</span>(mdl_stz, <span class="at">newdata =</span> .))</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   type             pred
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 No Music         22.1
## 2 Classical Music  24.2
## 3 Pop Music        21.9</code></pre>
<p>We notice that we get the same predicted group means independently of the side-constraint.</p>
<p>The predicted means do <em>not</em> depend on the side-constraint that we apply. However, the side-constraint influences the meaning of the parameters in the model.</p>
</div>
<p class="solution-end">
</p>
<div class="blue">
<p><strong>In <strong>R</strong>, we can switch back to the default reference group constraint by either of these</strong></p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Option 1</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(rest_spend<span class="sc">$</span>type) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Option 2</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(rest_spend<span class="sc">$</span>type) <span class="ot">&lt;-</span> <span class="st">&quot;contr.treatment&quot;</span></span></code></pre></div>
</div>
</div>
<div id="contrasts" class="section level1">
<h1>Contrasts</h1>
<p>We have seen that the F-test (and incremental F-test using <code>anova()</code>) provide overall tests of whether there are differences in the group means. When we use dummy (reference) coding, this could be a difference between one group and the reference group. When we use effects (sum-to-zero) coding, this could be a difference between one group and the grand mean. In some cases the investigators will have pre-planned comparisons they would like to make, and it is this we will look at next. To do so, we will use a package called <code>emmeans</code>.</p>
<div class="yellow">
<p><strong>Contrasts</strong> represent a wide range of hypotheses about the population means that can be tested using the fitted model.</p>
<p>However, they need to match the following general form. A contrast only allows us to test hypotheses that can be written as a linear combination of the population means with coefficients summing to zero:
<span class="math display">\[
H_0 : c_1 \mu_1 + c_2 \mu_2 + c_3 \mu_3 = 0 \qquad \text{with} \qquad c_1 + c_2 + c_3 = 0
\]</span></p>
</div>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;emmeans&quot;) remember that you only install packages once, and you should do so in the console, not your .Rmd script</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span></code></pre></div>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>We were interested in the following comparisons:</p>
<ul>
<li>Whether having some kind of background music, rather than no music, makes a difference in mean restaurant spending</li>
<li>Whether there is any difference in mean restaurant spending between those with no background music and those with pop music</li>
</ul>
<p>These are planned comparisons and can be translated to the following research hypotheses:
<span class="math display">\[
\begin{aligned}
1. \quad H_0 &amp;: \mu_\text{No Music} = \frac{1}{2} (\mu_\text{Classical Music} + \mu_\text{Pop Music}) \\
2. \quad H_0 &amp;: \mu_\text{No Music} = \mu_\text{Pop Music}
\end{aligned}
\]</span></p>
<p>First of all check the levels of the factor <code>type</code>, as the contrast coefficients need to match the order of the levels:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(rest_spend<span class="sc">$</span>type)</span></code></pre></div>
<pre><code>## [1] &quot;No Music&quot;        &quot;Classical Music&quot; &quot;Pop Music&quot;</code></pre>
<p>We specify the hypotheses by first giving each a name, and then specify the coefficients of the comparisons:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>comp <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">&quot;No Music - Some Music&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>, <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>),</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>             <span class="st">&quot;No Music - Pop Music&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>))</span></code></pre></div>
<p>Use the <code>emmeans()</code> function to obtain the estimated treatment means and uncertainties for your factor:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mdl_stz, <span class="sc">~</span> type)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>emm</span></code></pre></div>
<pre><code>##  type            emmean    SE  df lower.CL upper.CL
##  No Music          22.1 0.259 357     21.6     22.7
##  Classical Music   24.2 0.259 357     23.7     24.7
##  Pop Music         21.9 0.259 357     21.4     22.4
## 
## Confidence level used: 0.95</code></pre>
<p>Next, we run the contrast analysis. To do so, we use the <code>contrast()</code> function:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>comp_res <span class="ot">&lt;-</span> <span class="fu">contrast</span>(emm, <span class="at">method =</span> comp)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>comp_res</span></code></pre></div>
<pre><code>##  contrast              estimate    SE  df t.ratio p.value
##  No Music - Some Music   -0.895 0.318 357  -2.818  0.0051
##  No Music - Pop Music     0.242 0.367 357   0.661  0.5090</code></pre>
<p>Finally, we can ask for 95% confidence intervals:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(comp_res)</span></code></pre></div>
<pre><code>##  contrast              estimate    SE  df lower.CL upper.CL
##  No Music - Some Music   -0.895 0.318 357   -1.520   -0.270
##  No Music - Pop Music     0.242 0.367 357   -0.479    0.964
## 
## Confidence level used: 0.95</code></pre>
<p>Interpret the result of the contrast analysis.</p>
<ul>
<li>What do the p-values tell us?</li>
<li>Interpret the confidence intervals in the context of the study.</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-125" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-125&#39;, &#39;sol-start-125&#39;)"> Solution </span>
</div>
<div id="sol-body-125" class="solution-body" style="display: none;">
<p>The hypothesis test for the first contrast could be reported as follows:</p>
<div class="int">
<p>We performed a test against <span class="math inline">\(H_0: \mu_1 - \frac{1}{2}(\mu_2 + \mu_3) = 0\)</span>, resulting in <span class="math inline">\(t(357) = -2.818, p = .005\)</span>, two-sided.
At the 5% significance level, there is strong evidence that the mean spending for those with no music is different than the mean spending for those with some of background music.</p>
</div>
<p>The 95% confidence interval for <span class="math inline">\(\mu_1 - \frac{1}{2}(\mu_2 + \mu_3)\)</span> is given by <span class="math inline">\([-1.520, -0.270]\)</span>.</p>
<p>The corresponding confidence interval could be written up as:</p>
<div class="int">
<p>We are 95% confident that diners with no background music will spend, on average, between £1.52 and £0.27 pounds less than those with some background music.</p>
</div>
<p><br></p>
<p>The hypothesis test for the second contrast could be reported as follows:</p>
<div class="int">
<p>We performed a test against <span class="math inline">\(H_0: \mu_1 - \mu_3 = 0\)</span>, resulting in <span class="math inline">\(t(357) = 0.661, p = .509\)</span>, two-sided.
At the 5% significance level, there is not sufficient evidence to reject the null hypothesis that the mean spending for those with no music is the same as the mean spending for those with pop music.</p>
</div>
<p>The 95% confidence interval for <span class="math inline">\(\mu_1 - \mu_3\)</span> is given by <span class="math inline">\([-0.479, 0.964]\)</span>.</p>
<p>Because we have established that there isn’t a significant difference between the mean spending for those with no music and those with pop music, we will not interpret the confidence interval.</p>
</div>
<p class="solution-end">
</p>
<p>A final situation is where an investigator has no predetermined ideas at all where differences may lie, and they may wish to explore the data. We will discuss methods for such analyses in future weeks.</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<!-- Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-North2003" class="csl-entry">
North, A., A. Shilcock, and D. Hargreaves. 2003. <span>“The Effect of Musical Style on Restaurant Customers’ Spending.”</span> <em>Environment and Behavior</em> 35: 712–18.
</div>
</div>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
