<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Two-way ANOVA</title>

<script src="site_libs/header-attrs-2.12/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Intro to Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="1_02_slr.html">1/2: Intro to Linear Regression</a>
    </li>
    <li>
      <a href="1_03_slr_model_fit.html">1/3: More Linear Regression</a>
    </li>
    <li>
      <a href="1_04_mlr.html">1/4: Multiple Predictors</a>
    </li>
    <li>
      <a href="1_05_int_nc.html">1/5: Interactions: Num * Cat</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    More Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_07_int_nn.html">1/7: Interactions: Num * Num</a>
    </li>
    <li>
      <a href="1_08_int_cc.html">1/8: Interactions: Cat * Cat</a>
    </li>
    <li>
      <a href="1_09_assumptions.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="1_10_bootstrap_reg.html">1/10: Bootstrap &amp; Troubleshooting</a>
    </li>
    <li>
      <a href="1_11_write_up.html">1/11: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Analyzing Experimental Studies
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="2_01_model_comp.html">2/1: Model Comparisons</a>
    </li>
    <li>
      <a href="2_02_coding_factors.html">2/2: Coding Factors</a>
    </li>
    <li>
      <a href="2_03_cont_design_factanova.html">2/3: Contrasts, Study Design, &amp; Factorial ANOVA</a>
    </li>
    <li>
      <a href="2_04_factorial_anova.html">2/4: Two-Way ANOVA</a>
    </li>
    <li>
      <a href="2_05_multi_comp_writeup.html">2/5: Assumptions, Multiple Comparisons, Corrections, &amp; Write-Up Example</a>
    </li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="2_07_binary.html">2/7: Binary Logistic Regression</a>
    </li>
    <li>
      <a href="2_08_morelogistic.html">2/8: More Logistic Regression</a>
    </li>
    <li>
      <a href="2_09_exp_vs_conf.html">2/9: Exploratory vs Confirmatory</a>
    </li>
    <li class="dropdown-header">2/10: </li>
    <li class="dropdown-header">2/11: </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Two-way ANOVA</h1>

</div>


<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand how to interpret interactions with effects coding.<br />
</li>
<li>Understand how to interpret simple effects for experimental designs.</li>
<li>Understand how to conduct pairwise comparisons.</li>
</ol>
</div>
<div id="recap" class="section level1">
<h1>Recap</h1>
<p>You have (hopefully) already made a head start on this weeks exercises if you completed the Factorial ANOVA section of <a href="https://uoepsy.github.io/dapr2/labs/2_03_cont_design_factanova.html#Factorial_ANOVA">last week’s lab</a>. If you haven’t yet completed these two questions, do so before reading any further.</p>
<p>In this week’s exercises, we will further explore questions such as:</p>
<ul>
<li>Does level <span class="math inline">\(i\)</span> of the first factor have an effect on the response?</li>
<li>Does level <span class="math inline">\(j\)</span> of the second factor have an effect on the response?</li>
<li>Is there a combined effect of level <span class="math inline">\(i\)</span> of the first factor and level <span class="math inline">\(j\)</span> of the second factor on the response? In other words, is there interaction of the two factors so that the combined effect is not simply the additive effect of level <span class="math inline">\(i\)</span> of the first factor plus the effect of level <span class="math inline">\(j\)</span> of the second factor?</li>
</ul>
<div id="research-question-and-data" class="section level2">
<h2>Research question and data</h2>
<p>As a reminder, we are working with data from a study yielding a <span class="math inline">\(3 \times 3\)</span> factorial design to test whether there are differences in types of memory deficits for those experiencing different cognitive impairment(s).</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Task
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Diagnosis
</th>
<th style="text-align:left;">
grammar
</th>
<th style="text-align:left;">
classification
</th>
<th style="text-align:left;">
recognition
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
amnesic
</td>
<td style="text-align:left;">
44, 63, 76, 72, 45
</td>
<td style="text-align:left;">
72, 66, 55, 82, 75
</td>
<td style="text-align:left;">
70, 51, 82, 66, 56
</td>
</tr>
<tr>
<td style="text-align:left;">
huntingtons
</td>
<td style="text-align:left;">
24, 30, 51, 55, 40
</td>
<td style="text-align:left;">
53, 59, 33, 37, 43
</td>
<td style="text-align:left;">
107, 80, 98, 82, 108
</td>
</tr>
<tr>
<td style="text-align:left;">
control
</td>
<td style="text-align:left;">
76, 98, 71, 70, 85
</td>
<td style="text-align:left;">
92, 65, 86, 67, 90
</td>
<td style="text-align:left;">
107, 80, 101, 82, 105
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="interaction-model" class="section level1">
<h1>Interaction Model</h1>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Let’s look at the <code>summary()</code> and <code>anova()</code> output in detail from the model you should have previously fitted with the sum to zero constraint. As a reminder, the model with interaction is:</p>
<span class="math display">\[\begin{aligned}
Score &amp;= \beta_0 \\
      &amp;+ \beta_1 D_\text{Control} + \beta_2 D_\text{Amnesic}   \\
      &amp;+ \beta_3 T_\text{Recognition}  + \beta_4 T_\text{Grammar} \\
      &amp;+ \beta_5 (D_\text{Control} * T_\text{Recognition}) + \beta_6 (D_\text{Amnesic} * T_\text{Recognition})  \\
      &amp;+ \beta_7 (D_\text{Control} * T_\text{Grammar}) + \beta_8 (D_\text{Amnesic} * T_\text{Grammar})  \\
      &amp;+ \epsilon
\end{aligned}\]</span>
<p>Applying the sum to zero constraint (for <code>Diagnosis</code> of ‘Control’ and <code>Task</code> of ‘Recognition’), we would have:</p>
<span class="math display">\[\begin{aligned}
\text{Intercept (global mean)} &amp;= \beta_0 \frac{\mu_{1,1} + \mu_{1,2} + \cdots + \mu_{3,3}}{9} \\
\beta_{Huntingtons} &amp;= -(\beta_1 + \beta_2) \\
\beta_{Classification} &amp;= -(\beta_3 + \beta_4) \\
\beta_{Huntingtons:Classification} &amp;= -(\beta_5 + \beta_6 + \beta_7 + \beta_8)
\end{aligned}\]</span>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-138" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-138&#39;, &#39;sol-start-138&#39;)"> Solution </span>
</div>
<div id="sol-body-138" class="solution-body" style="display: none;">
<p>Let’s look at the <code>anova()</code> and <code>summary()</code> output:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(cog<span class="sc">$</span>Diagnosis) <span class="ot">&lt;-</span> <span class="st">&quot;contr.sum&quot;</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(cog<span class="sc">$</span>Task) <span class="ot">&lt;-</span> <span class="st">&quot;contr.sum&quot;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>mdl_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(Score <span class="sc">~</span> Diagnosis <span class="sc">*</span> Task, <span class="at">data =</span> cog)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mdl_int)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Score
##                Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## Diagnosis       2   5250 2625.00 16.6373  7.64e-06 ***
## Task            2   5250 2625.00 16.6373  7.64e-06 ***
## Diagnosis:Task  4   5000 1250.00  7.9225 0.0001092 ***
## Residuals      36   5680  157.78                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="int">
<p>Scores significantly differed by both Diagnosis (<span class="math inline">\(F(2, 36)=16.63, p &lt; .001\)</span>) and by Task (<span class="math inline">\(F(2, 36)=16.63, p &lt; .001\)</span>). The interaction between Diagnosis and Task was significant (<span class="math inline">\(F(4, 36)=7.92, p &lt; 0.001\)</span>). This provides evidence against the null hypothesis that effect of Task is constant across the different levels of Diagnosis.</p>
</div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl_int)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Score ~ Diagnosis * Task, data = cog)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##    -16    -12      2     11     18 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        70.000      1.872  37.384  &lt; 2e-16 ***
## Diagnosis1         15.000      2.648   5.664 1.95e-06 ***
## Diagnosis2         -5.000      2.648  -1.888 0.067085 .  
## Task1              15.000      2.648   5.664 1.95e-06 ***
## Task2             -10.000      2.648  -3.776 0.000576 ***
## Diagnosis1:Task1   -5.000      3.745  -1.335 0.190216    
## Diagnosis2:Task1  -15.000      3.745  -4.005 0.000297 ***
## Diagnosis1:Task2    5.000      3.745   1.335 0.190216    
## Diagnosis2:Task2    5.000      3.745   1.335 0.190216    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.56 on 36 degrees of freedom
## Multiple R-squared:  0.7318, Adjusted R-squared:  0.6722 
## F-statistic: 12.28 on 8 and 36 DF,  p-value: 2.844e-08</code></pre>
<div class="int">
<p>The F-test for model utility is again significant at the 5% level: <span class="math inline">\(F(8,36) = 12.28, p &lt; .001\)</span>. An F-statistic this large or larger occurring by chance only is very small. In the presence of a significant interaction we <strong>do not</strong> interpret the main effects as their interpretation changes with the level of the other factor.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Based on previous plotting, it does seem that there is a clear interaction between diagnosis and task (as well as from our output above). However, we have not statistically compared our interaction model to an additive model (same model but without the interaction). Until we do so, we cannot confidently progress on the <em>assumption</em> that the interaction model is the most suitable for answering the research question.</p>
<p>We also want to consider the best coding constraint to apply in order to best answer the research question - are we interested in whether group X (e.g., Amnesic) differed from group Y (e.g., Huntingtons), or whether group X (e.g., Amnesic) differed from the overall group mean?</p>
<p>Since we are interested in comparing groups, we should reset to dummy coding, and thus should re-run our interaction model. Next, we need to perform a model comparison between the additive model and the interaction model using the <code>anova()</code> function.</p>
<p>After re-running your model with dummy coding, interpret the result of the model comparison.</p>
<span class="math display">\[\begin{aligned}
Additive Model: Score &amp;= \beta_0 \\
      &amp;+ \beta_1 D_\text{Amnseic} + \beta_2 D_\text{Huntingtons}   \\
      &amp;+ \beta_3 T_\text{Grammar}  + \beta_4 T_\text{Classification} \\
      &amp;+ \epsilon
\end{aligned}\]</span>
<span class="math display">\[\begin{aligned}
Interaction Model: Score &amp;= \beta_0 \\
      &amp;+ \beta_1 D_\text{Amnseic} + \beta_2 D_\text{Huntingtons}   \\
      &amp;+ \beta_3 T_\text{Grammar}  + \beta_4 T_\text{Classification} \\
      &amp;+ \beta_5 (D_\text{Amnseic} * T_\text{Grammar}) + \beta_6 (D_\text{Huntingtons} * T_\text{Grammar})  \\
      &amp;+ \beta_7 (D_\text{Amnseic} * T_\text{Classification}) + \beta_8 (D_\text{Huntingtons} * T_\text{Classification})  \\
      &amp;+ \epsilon
\end{aligned}\]</span>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-139" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-139&#39;, &#39;sol-start-139&#39;)"> Solution </span>
</div>
<div id="sol-body-139" class="solution-body" style="display: none;">
<p>Switch back to dummy coding:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(cog<span class="sc">$</span>Diagnosis) <span class="ot">&lt;-</span> <span class="st">&quot;contr.treatment&quot;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(cog<span class="sc">$</span>Task) <span class="ot">&lt;-</span> <span class="st">&quot;contr.treatment&quot;</span></span></code></pre></div>
<p>Build additive model and re-run interaction model:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mdl_add <span class="ot">&lt;-</span> <span class="fu">lm</span>(Score <span class="sc">~</span> Diagnosis <span class="sc">+</span> Task, <span class="at">data =</span> cog)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mdl_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(Score <span class="sc">~</span> Diagnosis <span class="sc">*</span> Task, <span class="at">data =</span> cog)</span></code></pre></div>
<p>The relevant function is <code>anova()</code> with the two models as inputs to conduct a model comparison:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mdl_add, mdl_int)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Score ~ Diagnosis + Task
## Model 2: Score ~ Diagnosis * Task
##   Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1     40 10680                                  
## 2     36  5680  4      5000 7.9225 0.0001092 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="int">
<p>We performed an F-test to compare two nested models: an additive two-factor ANOVA against a two-factor model with interaction. The test results are <span class="math inline">\(F(4, 36) = 7.92, p &lt; .001\)</span>.</p>
<p>At the 5% significance level, the probability of obtaining an F-statistic as large as 7.92 or larger is &lt;.001.</p>
<p>Hence, the comparison of nested models provides evidence against the additive effects model, suggesting that we should use the interaction model as each factor has a different effect on the response depending the level of the other factor.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Using <code>plot_model()</code> (note that this function is from <code>sjPlot</code> package - make sure that you load this), generate a plot showing the predicted mean scores for each combination of levels of the diagnosis and task factors.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-140" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-140&#39;, &#39;sol-start-140&#39;)"> Solution </span>
</div>
<div id="sol-body-140" class="solution-body" style="display: none;">
<p>To visualize the interaction between Diagnosis and Task, we will use <code>plot_model()</code>, and ask for a plot of predicted values by specifying <code>type = "pred"</code>. Because the interaction involves the two variables, we need to specify a list of the <code>terms</code> (or names) from the model that should be plotted.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(mdl_int, <span class="at">type =</span> <span class="st">&quot;pred&quot;</span>, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">&quot;Diagnosis&quot;</span>, <span class="st">&quot;Task&quot;</span>))</span></code></pre></div>
<p><img src="2_04_factorial_anova_files/figure-html/unnamed-chunk-8-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
<div id="contrast-analysis" class="section level1">
<h1>Contrast analysis</h1>
<p>We will begin by looking at each factor separately.</p>
<p>In terms of the diagnostic groups, recall that we want to compare the amnesiacs to the Huntington individuals. This corresponds to a contrast with coefficients of 0, 1, and −1, for control, amnesic, and Huntingtons, respectively.</p>
<p>Similarly, in terms of the tasks, we want to compare the average of the two implicit memory tasks with the explicit memory task. This corresponds to a contrast with coefficients of 0.5, 0.5, and −1 for the three tasks.</p>
<p>When we are in presence of a significant interaction, the coefficients for a contrast between the means are found by multiplying each row coefficient with all column coefficients as shown below:</p>
<p><img src="images/contr_interaction.png" width="100%" style="display: block; margin: auto;" /></p>
<p>This can be done in R using:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>diag_coef  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;control&#39;</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">&#39;amnesic&#39;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&#39;huntingtons&#39;</span> <span class="ot">=</span> <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>task_coef  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;grammar&#39;</span> <span class="ot">=</span> <span class="fl">0.5</span>, <span class="st">&#39;classification&#39;</span> <span class="ot">=</span> <span class="fl">0.5</span>, <span class="st">&#39;recognition&#39;</span> <span class="ot">=</span> <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>contr_coef <span class="ot">&lt;-</span> <span class="fu">outer</span>(diag_coef, task_coef)   <span class="co"># or: diag_coef %o% task_coef</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>contr_coef</span></code></pre></div>
<pre><code>##             grammar classification recognition
## control         0.0            0.0           0
## amnesic         0.5            0.5          -1
## huntingtons    -0.5           -0.5           1</code></pre>
<p>The above coefficients correspond to testing the null hypothesis</p>
<p><span class="math display">\[
H_0 : \frac{\mu_{2,1} + \mu_{2,2}}{2} - \mu_{2,3} - \left( \frac{\mu_{3,1} + \mu_{3,2}}{2} - \mu_{3,3} \right) = 0
\]</span></p>
<p>or, equivalently,</p>
<p><span class="math display">\[
H_0 : \frac{\mu_{2,1} + \mu_{2,2}}{2} - \mu_{2,3} = \frac{\mu_{3,1} + \mu_{3,2}}{2} - \mu_{3,3}
\]</span></p>
<p>which says that, in the population, the difference between the mean implicit memory and the explicit memory score is the same for amnesic patients and Huntingtons individuals. Note that the scores for the grammar and classification tasks have been averaged to obtain a single measure of ‘implicit memory’ score.</p>
<p>Now that we have the coefficients, let’s call the <code>emmeans</code> function (this is helpful to look at the ordering of the groups):</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mdl_int, <span class="sc">~</span> Diagnosis<span class="sc">*</span>Task)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>emm</span></code></pre></div>
<pre><code>##  Diagnosis   Task           emmean   SE df lower.CL upper.CL
##  control     recognition        95 5.62 36     83.6    106.4
##  amnesic     recognition        65 5.62 36     53.6     76.4
##  huntingtons recognition        95 5.62 36     83.6    106.4
##  control     grammar            80 5.62 36     68.6     91.4
##  amnesic     grammar            60 5.62 36     48.6     71.4
##  huntingtons grammar            40 5.62 36     28.6     51.4
##  control     classification     80 5.62 36     68.6     91.4
##  amnesic     classification     70 5.62 36     58.6     81.4
##  huntingtons classification     45 5.62 36     33.6     56.4
## 
## Confidence level used: 0.95</code></pre>
<p>Next, from <code>contr_coef</code>, insert the coefficients following the order specified by the rows of <code>emm</code> above. That is, the first one should be for <code>control</code> <code>recognition</code> and have a value of 0, the second for <code>amnesic</code> <code>recognition</code> with a value of -1, and so on…</p>
<p>We also give a name to this contrast, such as ‘Research Hyp’.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>comp_res <span class="ot">&lt;-</span> <span class="fu">contrast</span>(emm, <span class="at">method =</span> <span class="fu">list</span>(<span class="st">&#39;Research Hyp&#39;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>, <span class="dv">0</span>, <span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>)))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>comp_res</span></code></pre></div>
<pre><code>##  contrast     estimate   SE df t.ratio p.value
##  Research Hyp     52.5 9.73 36   5.396  &lt;.0001</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(comp_res)</span></code></pre></div>
<pre><code>##  contrast     estimate   SE df lower.CL upper.CL
##  Research Hyp     52.5 9.73 36     32.8     72.2
## 
## Confidence level used: 0.95</code></pre>
<p>or:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(comp_res, <span class="at">infer =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##  contrast     estimate   SE df lower.CL upper.CL t.ratio p.value
##  Research Hyp     52.5 9.73 36     32.8     72.2   5.396  &lt;.0001
## 
## Confidence level used: 0.95</code></pre>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Interpret the results of the contrast analysis.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-141" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-141&#39;, &#39;sol-start-141&#39;)"> Solution </span>
</div>
<div id="sol-body-141" class="solution-body" style="display: none;">
<p>The contrast analysis yielded a <span class="math inline">\(t\)</span>-value of 5.4 and a corresponding <span class="math inline">\(p\)</span>-value &lt; .001. Thus, there is evidence that the contrast is not zero in the population. In other words, Amnesics and Huntingtons patients differ in the difference between implicit and explicit recognition memory tasks.</p>
<p>The contrast analysis shows that the 95% confidence interval for our contrast stretches from 32.8 to 72.2. This interval does not contain zero. Thus, we can be 95% confident that the task difference is not the same for amnesiacs as for Huntingtons, which is why we can reject the null hypothesis that the difference in differences is zero.</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="simple-effects" class="section level1">
<h1>Simple Effects</h1>
<p>By considering the simple effects, we can identify at which levels of the interacting condition we see different effects.</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Since we have a significant interaction, we should also look at the simple main effects. Simple effects are the effect of one factor (e.g., Task) at each level of another factor (e.g., Diagnosis - Control, Huntingtons, and Amnesic).</p>
<p>Examine the simple effects for Task at each level of Diagnosis; and then the simple effects for Diagnosis at each level of Task.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-142" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-142&#39;, &#39;sol-start-142&#39;)"> Solution </span>
</div>
<div id="sol-body-142" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>mdl_int_simple1 <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm, <span class="at">simple =</span> <span class="st">&quot;Task&quot;</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>mdl_int_simple1</span></code></pre></div>
<pre><code>## Diagnosis = control:
##  contrast                     estimate   SE df t.ratio p.value
##  recognition - grammar              15 7.94 36   1.888  0.1567
##  recognition - classification       15 7.94 36   1.888  0.1567
##  grammar - classification            0 7.94 36   0.000  1.0000
## 
## Diagnosis = amnesic:
##  contrast                     estimate   SE df t.ratio p.value
##  recognition - grammar               5 7.94 36   0.629  0.8050
##  recognition - classification       -5 7.94 36  -0.629  0.8050
##  grammar - classification          -10 7.94 36  -1.259  0.4273
## 
## Diagnosis = huntingtons:
##  contrast                     estimate   SE df t.ratio p.value
##  recognition - grammar              55 7.94 36   6.923  &lt;.0001
##  recognition - classification       50 7.94 36   6.294  &lt;.0001
##  grammar - classification           -5 7.94 36  -0.629  0.8050
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mdl_int_simple2 <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm, <span class="at">simple =</span> <span class="st">&quot;Diagnosis&quot;</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>mdl_int_simple2</span></code></pre></div>
<pre><code>## Task = recognition:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           30 7.94 36   3.776  0.0016
##  control - huntingtons        0 7.94 36   0.000  1.0000
##  amnesic - huntingtons      -30 7.94 36  -3.776  0.0016
## 
## Task = grammar:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           20 7.94 36   2.518  0.0424
##  control - huntingtons       40 7.94 36   5.035  &lt;.0001
##  amnesic - huntingtons       20 7.94 36   2.518  0.0424
## 
## Task = classification:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           10 7.94 36   1.259  0.4273
##  control - huntingtons       35 7.94 36   4.406  0.0003
##  amnesic - huntingtons       25 7.94 36   3.147  0.0091
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>From <code>mdl_int_simple1</code> we can see the differences between between tasks for each diagnosis group, and from <code>mdl_int_simple2</code> the differences between diagnoses for each task group.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>There are various ways we can create an interaction plot, for instance, try this code:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmip</span>(mdl_int, Diagnosis <span class="sc">~</span> Task, <span class="at">CIs =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Considering the simple effects that we just saw in Question 5, identify the significant effects and match them to the parts of an interaction plot.</p>
<div class="optional-begin">
<span id="opt-start-143" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-143&#39;, &#39;opt-start-143&#39;)"> Optional: You can change what is plotted on the x-axis</span>
</div>
<div id="opt-body-143" class="optional-body" style="display: none;">
<p>We can switch what is on the x-axis pretty easily:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co">#loading this package so that I can display plots in a grid</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>plt_1 <span class="ot">&lt;-</span> <span class="fu">emmip</span>(mdl_int, Diagnosis <span class="sc">~</span> Task, <span class="at">CIs =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>plt_2 <span class="ot">&lt;-</span> <span class="fu">emmip</span>(mdl_int, Task <span class="sc">~</span> Diagnosis, <span class="at">CIs =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>plt_1 <span class="sc">/</span> plt_2</span></code></pre></div>
</div>
<p class="optional-end">
</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-144" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-144&#39;, &#39;sol-start-144&#39;)"> Solution </span>
</div>
<div class="solution-body" id = "sol-body-144" style="display: none;">


<p>For the simple effects of Task, the significant differences (those for which <span class="math inline">\(p&lt;.05\)</span>) are only seen in the Huntingtons group, between recognition &amp; grammar and recognition &amp; classification tasks.<br />
In the plot below, we can see this is the left-most blue point compared to the middle blue point, and then compared to the right-most blue point.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmip</span>(mdl_int, Diagnosis <span class="sc">~</span> Task, <span class="at">CIs =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="2_04_factorial_anova_files/figure-html/unnamed-chunk-17-1.png" width="60%" style="display: block; margin: auto;" /></p>
<hr>
<p>For the simple effects of Diagnosis, we saw significant differences</p>
<ul>
<li>in the recognition task, between control &amp; amnesic<br />
(in the plot below: left-most red point to middle red-point)<br />
</li>
<li>in the recognition task, between amnesic &amp; huntingtons<br />
(in the plot below: middle red-point to right-most red point)<br />
</li>
<li>in the grammar task, between control &amp; huntingtons<br />
(in the plot below: left-most green point to right-most green point)</li>
<li>in the classification task, between control &amp; huntingtons<br />
(in the plot below: left-most blue point to right-most blue point)</li>
</ul>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmip</span>(mdl_int, Task <span class="sc">~</span> Diagnosis, <span class="at">CIs =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="2_04_factorial_anova_files/figure-html/unnamed-chunk-18-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
<div id="pairwise-comparisons" class="section level1">
<h1>Pairwise Comparisons</h1>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Conduct exploratory pairwise comparisons to compare all levels of Diagnosis with all levels of Task.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-145" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-145&#39;, &#39;sol-start-145&#39;)"> Solution </span>
</div>
<div id="sol-body-145" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>pairs_res <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>pairs_res</span></code></pre></div>
<pre><code>##  contrast                                             estimate   SE df t.ratio
##  control recognition - amnesic recognition                  30 7.94 36   3.776
##  control recognition - huntingtons recognition               0 7.94 36   0.000
##  control recognition - control grammar                      15 7.94 36   1.888
##  control recognition - amnesic grammar                      35 7.94 36   4.406
##  control recognition - huntingtons grammar                  55 7.94 36   6.923
##  control recognition - control classification               15 7.94 36   1.888
##  control recognition - amnesic classification               25 7.94 36   3.147
##  control recognition - huntingtons classification           50 7.94 36   6.294
##  amnesic recognition - huntingtons recognition             -30 7.94 36  -3.776
##  amnesic recognition - control grammar                     -15 7.94 36  -1.888
##  amnesic recognition - amnesic grammar                       5 7.94 36   0.629
##  amnesic recognition - huntingtons grammar                  25 7.94 36   3.147
##  amnesic recognition - control classification              -15 7.94 36  -1.888
##  amnesic recognition - amnesic classification               -5 7.94 36  -0.629
##  amnesic recognition - huntingtons classification           20 7.94 36   2.518
##  huntingtons recognition - control grammar                  15 7.94 36   1.888
##  huntingtons recognition - amnesic grammar                  35 7.94 36   4.406
##  huntingtons recognition - huntingtons grammar              55 7.94 36   6.923
##  huntingtons recognition - control classification           15 7.94 36   1.888
##  huntingtons recognition - amnesic classification           25 7.94 36   3.147
##  huntingtons recognition - huntingtons classification       50 7.94 36   6.294
##  control grammar - amnesic grammar                          20 7.94 36   2.518
##  control grammar - huntingtons grammar                      40 7.94 36   5.035
##  control grammar - control classification                    0 7.94 36   0.000
##  control grammar - amnesic classification                   10 7.94 36   1.259
##  control grammar - huntingtons classification               35 7.94 36   4.406
##  amnesic grammar - huntingtons grammar                      20 7.94 36   2.518
##  amnesic grammar - control classification                  -20 7.94 36  -2.518
##  amnesic grammar - amnesic classification                  -10 7.94 36  -1.259
##  amnesic grammar - huntingtons classification               15 7.94 36   1.888
##  huntingtons grammar - control classification              -40 7.94 36  -5.035
##  huntingtons grammar - amnesic classification              -30 7.94 36  -3.776
##  huntingtons grammar - huntingtons classification           -5 7.94 36  -0.629
##  control classification - amnesic classification            10 7.94 36   1.259
##  control classification - huntingtons classification        35 7.94 36   4.406
##  amnesic classification - huntingtons classification        25 7.94 36   3.147
##  p.value
##   0.0149
##   1.0000
##   0.6257
##   0.0026
##   &lt;.0001
##   0.6257
##   0.0711
##   &lt;.0001
##   0.0149
##   0.6257
##   0.9993
##   0.0711
##   0.6257
##   0.9993
##   0.2575
##   0.6257
##   0.0026
##   &lt;.0001
##   0.6257
##   0.0711
##   &lt;.0001
##   0.2575
##   0.0004
##   1.0000
##   0.9367
##   0.0026
##   0.2575
##   0.2575
##   0.9367
##   0.6257
##   0.0004
##   0.0149
##   0.9993
##   0.9367
##   0.0026
##   0.0711
## 
## P value adjustment: tukey method for comparing a family of 9 estimates</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#can also plot if you&#39;d like:</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pairs_res)</span></code></pre></div>
<p><img src="2_04_factorial_anova_files/figure-html/unnamed-chunk-19-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>From the above, we can see comparisons for all different possible pairs of diagnosis-task combinations. As well as recapping assumption checks, next week we will also explore how we can adjust our pairwise comparisons (<em>think</em> about how many comparisons were conducted above - without adjusting our <span class="math inline">\(\alpha\)</span> (or <span class="math inline">\(p\)</span>-value), why might any inferences drawn be problematic?)</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<!-- Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Maxwell2017" class="csl-entry">
Maxwell, Scott E, Harold D Delaney, and Ken Kelley. 2017. <em>Designing Experiments and Analyzing Data: A Model Comparison Perspective</em>. Routledge.
</div>
</div>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
