<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Multiple Comparisons, Corrections, &amp; Write-Up</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Intro to Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="1_02_slr.html">1/2: Intro to Linear Regression</a>
    </li>
    <li>
      <a href="1_03_slr_model_fit.html">1/3: More Linear Regression</a>
    </li>
    <li>
      <a href="1_04_mlr.html">1/4: Multiple Predictors</a>
    </li>
    <li>
      <a href="1_05_int_nc.html">1/5: Interactions: Num * Cat</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    More Linear Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_07_int_nn.html">1/7: Interactions: Num * Num</a>
    </li>
    <li>
      <a href="1_08_int_cc.html">1/8: Interactions: Cat * Cat</a>
    </li>
    <li>
      <a href="1_09_assumptions.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="1_10_bootstrap_reg.html">1/10: Bootstrap &amp; Troubleshooting</a>
    </li>
    <li>
      <a href="1_11_write_up.html">1/11: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Analyzing Experimental Studies
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="2_01_model_comp.html">2/1: Model Comparisons</a>
    </li>
    <li>
      <a href="2_02_coding_factors.html">2/2: Coding Factors</a>
    </li>
    <li>
      <a href="2_03_cont_design_factanova.html">2/3: Contrasts, Study Design, &amp; Factorial ANOVA</a>
    </li>
    <li>
      <a href="2_04_factorial_anova.html">2/4: Two-Way ANOVA</a>
    </li>
    <li class="dropdown-header">2/5: </li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">2/7: </li>
    <li class="dropdown-header">2/8: </li>
    <li class="dropdown-header">2/9: </li>
    <li class="dropdown-header">2/10: </li>
    <li class="dropdown-header">2/11: </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Multiple Comparisons, Corrections, &amp; Write-Up</h1>

</div>


<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand how to apply corrections available for multiple comparisons.<br />
</li>
<li>Understand how to write-up and provide interpretation of a 2x2 factorial ANOVA.</li>
</ol>
</div>
<div id="multiple-comparisons" class="section level1">
<h1>Multiple Comparisons</h1>
<p>In last week’s exercises we began to look at how we compare different groups, by using contrast analysis to conduct tests of specific comparisons between groups. We also saw how we might conduct <em>pairwise comparisons</em>, where we test all possible pairs of group means within a given set.</p>
<p>For instance, we can compare the means of the different diagnosis groups for each task:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>emm_task <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mdl_int, <span class="sc">~</span> Diagnosis <span class="sc">|</span> Task)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>contr_task <span class="ot">&lt;-</span> <span class="fu">contrast</span>(emm_task, <span class="at">method =</span> <span class="st">&#39;pairwise&#39;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>contr_task</span></code></pre></div>
<pre><code>## Task = recognition:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           30 7.94 36   3.776  0.0016
##  control - huntingtons        0 7.94 36   0.000  1.0000
##  amnesic - huntingtons      -30 7.94 36  -3.776  0.0016
## 
## Task = grammar:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           20 7.94 36   2.518  0.0424
##  control - huntingtons       40 7.94 36   5.035  &lt;.0001
##  amnesic - huntingtons       20 7.94 36   2.518  0.0424
## 
## Task = classification:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           10 7.94 36   1.259  0.4273
##  control - huntingtons       35 7.94 36   4.406  0.0003
##  amnesic - huntingtons       25 7.94 36   3.147  0.0091
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>or we can test all different combinations of task and diagnosis group (if that was something we were theoretically interested in, which is unlikely!) which would equate to conducting 36 comparisons!</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>emm_task <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mdl_int, <span class="sc">~</span> Diagnosis <span class="sc">*</span> Task)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>contr_task <span class="ot">&lt;-</span> <span class="fu">contrast</span>(emm_task, <span class="at">method =</span> <span class="st">&#39;pairwise&#39;</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>contr_task</span></code></pre></div>
<pre><code>##  contrast                                             estimate   SE df t.ratio
##  control recognition - amnesic recognition                  30 7.94 36   3.776
##  control recognition - huntingtons recognition               0 7.94 36   0.000
##  control recognition - control grammar                      15 7.94 36   1.888
##  control recognition - amnesic grammar                      35 7.94 36   4.406
##  control recognition - huntingtons grammar                  55 7.94 36   6.923
##  control recognition - control classification               15 7.94 36   1.888
##  control recognition - amnesic classification               25 7.94 36   3.147
##  control recognition - huntingtons classification           50 7.94 36   6.294
##  amnesic recognition - huntingtons recognition             -30 7.94 36  -3.776
##  amnesic recognition - control grammar                     -15 7.94 36  -1.888
##  amnesic recognition - amnesic grammar                       5 7.94 36   0.629
##  amnesic recognition - huntingtons grammar                  25 7.94 36   3.147
##  amnesic recognition - control classification              -15 7.94 36  -1.888
##  amnesic recognition - amnesic classification               -5 7.94 36  -0.629
##  amnesic recognition - huntingtons classification           20 7.94 36   2.518
##  huntingtons recognition - control grammar                  15 7.94 36   1.888
##  huntingtons recognition - amnesic grammar                  35 7.94 36   4.406
##  huntingtons recognition - huntingtons grammar              55 7.94 36   6.923
##  huntingtons recognition - control classification           15 7.94 36   1.888
##  huntingtons recognition - amnesic classification           25 7.94 36   3.147
##  huntingtons recognition - huntingtons classification       50 7.94 36   6.294
##  control grammar - amnesic grammar                          20 7.94 36   2.518
##  control grammar - huntingtons grammar                      40 7.94 36   5.035
##  control grammar - control classification                    0 7.94 36   0.000
##  control grammar - amnesic classification                   10 7.94 36   1.259
##  control grammar - huntingtons classification               35 7.94 36   4.406
##  amnesic grammar - huntingtons grammar                      20 7.94 36   2.518
##  amnesic grammar - control classification                  -20 7.94 36  -2.518
##  amnesic grammar - amnesic classification                  -10 7.94 36  -1.259
##  amnesic grammar - huntingtons classification               15 7.94 36   1.888
##  huntingtons grammar - control classification              -40 7.94 36  -5.035
##  huntingtons grammar - amnesic classification              -30 7.94 36  -3.776
##  huntingtons grammar - huntingtons classification           -5 7.94 36  -0.629
##  control classification - amnesic classification            10 7.94 36   1.259
##  control classification - huntingtons classification        35 7.94 36   4.406
##  amnesic classification - huntingtons classification        25 7.94 36   3.147
##  p.value
##   0.0149
##   1.0000
##   0.6257
##   0.0026
##   &lt;.0001
##   0.6257
##   0.0711
##   &lt;.0001
##   0.0149
##   0.6257
##   0.9993
##   0.0711
##   0.6257
##   0.9993
##   0.2575
##   0.6257
##   0.0026
##   &lt;.0001
##   0.6257
##   0.0711
##   &lt;.0001
##   0.2575
##   0.0004
##   1.0000
##   0.9367
##   0.0026
##   0.2575
##   0.2575
##   0.9367
##   0.6257
##   0.0004
##   0.0149
##   0.9993
##   0.9367
##   0.0026
##   0.0711
## 
## P value adjustment: tukey method for comparing a family of 9 estimates</code></pre>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-1&#39;, &#39;opt-start-1&#39;)"> 36? how do we know there are 36?</span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p>There are 3 diagnosis groups, and 3 tasks, meaning there are 9 different group means. All possible pairwise comparisons would is all different possible combinations of 2 from a set of 9. We can work this out using the rule:</p>
<p>$$
_nC_r =  \
<span class="math display">\[\begin{align} \\
&amp; \text{Where:} \\
&amp; n = \text{total number in the set} \\
&amp; r = \text{number chosen} \\
&amp; _nC_r = \text{number of combinations of r from n} \\
\end{align}\]</span></p>
<p>$$
In R:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">factorial</span>(<span class="dv">9</span>)<span class="sc">/</span>(<span class="fu">factorial</span>(<span class="dv">2</span>)<span class="sc">*</span>(<span class="fu">factorial</span>(<span class="dv">9-2</span>)))</span></code></pre></div>
<pre><code>## [1] 36</code></pre>
<p>Or, easier still:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(<span class="fu">combn</span>(<span class="dv">9</span>, <span class="dv">2</span>))</span></code></pre></div>
<pre><code>## [1]  2 36</code></pre>
</div>
<p class="optional-end">
</p>
<div id="why-does-the-number-of-tests-matter" class="section level2">
<h2>Why does the number of tests matter?</h2>
<div class="optional-begin">
<span id="opt-start-2" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-2&#39;, &#39;opt-start-2&#39;)"> refresher on making errors in hypothesis tests</span>
</div>
<div id="opt-body-2" class="optional-body" style="display: none;">
<p>Think back to <a href="https://uoe-psychology.github.io/uoe_psystats/dapr1/book/chap-typeerror.html">“Type 1 errors” from DAPR1</a> - when we conduct an hypothesis test, and we set <span class="math inline">\(\alpha=0.05\)</span>, we will reject the null hypothesis <span class="math inline">\(H_0\)</span> when we find a <span class="math inline">\(p &lt; .05\)</span>. Now remember what a <span class="math inline">\(p\)</span>-value represents - it is the chance of observing a statistic at least as extreme as the one we do have, assuming the null hypothesis to be true. This means that <em>if</em> <span class="math inline">\(H_0\)</span> <strong>is</strong> true, then we will still observe a <span class="math inline">\(p &lt; .05\)</span> 5% of the time. So our chance of making this error = the threshold (<span class="math inline">\(\alpha\)</span>) at which below a p-value results in us rejecting <span class="math inline">\(H_0\)</span>.</p>
</div>
<p class="optional-end">
</p>
<p>But this error-rate applies to each statistical hypothesis we test. So if we conduct an experiment in which we plan on conducting lots of tests of different comparisons, the chance of an error being made increases substantially. Across the family of tests performed that chance will be much higher than 5%.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<p>Each test conducted at <span class="math inline">\(\alpha = 0.05\)</span> has a 0.05 (or 5%) probability of Type I error (wrongly rejecting the null hypothesis). If we do 9 tests, that experimentwise error rate is <span class="math inline">\(\alpha_{ew} \leq 9 \times 0.05\)</span>, where 9 is the number of comparisons made as part of the experiment.</p>
<p>Thus, if nine <strong>independent</strong> comparisons were made at the <span class="math inline">\(\alpha = 0.05\)</span> level, the experimentwise Type I error rate <span class="math inline">\(\alpha_{ew}\)</span> would be at most <span class="math inline">\(9 \times 0.05 = 0.45\)</span>. That is, we could wrongly reject the null hypothesis on average 45 times out of 100.
To make this more confusing, many of the tests in a family are not <strong>independent</strong> (see the lecture slides for the calculation of error rate for dependent tests).</p>
<p>Here, we go through some of the different options available to us to control, or ‘correct’ for this problem.</p>
</div>
</div>
<div id="corrections" class="section level1">
<h1>Corrections</h1>
<div id="bonferroni" class="section level2">
<h2>Bonferroni</h2>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Load the data from last week, and re-acquaint yourself with it.</p>
<p>Provide a plot of the Diagnosis*Task group mean scores.</p>
<p>The data is at <a href="https://uoepsy.github.io/data/cognitive_experiment.csv" class="uri">https://uoepsy.github.io/data/cognitive_experiment.csv</a>.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-3&#39;, &#39;sol-start-3&#39;)"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>cog <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://uoepsy.github.io/data/cognitive_experiment.csv&#39;</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># head(df)</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>cog<span class="sc">$</span>Diagnosis <span class="ot">&lt;-</span> <span class="fu">factor</span>(cog<span class="sc">$</span>Diagnosis, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;amnesic&quot;</span>, <span class="st">&quot;huntingtons&quot;</span>, <span class="st">&quot;control&quot;</span>),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">ordered =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>cog<span class="sc">$</span>Task <span class="ot">&lt;-</span> <span class="fu">factor</span>(cog<span class="sc">$</span>Task, </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;grammar&quot;</span>, <span class="st">&quot;classification&quot;</span>, <span class="st">&quot;recognition&quot;</span>), </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ordered =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>cog<span class="sc">$</span>Diagnosis <span class="ot">&lt;-</span> <span class="fu">fct_relevel</span>(cog<span class="sc">$</span>Diagnosis, <span class="st">&quot;control&quot;</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>cog<span class="sc">$</span>Task <span class="ot">&lt;-</span> <span class="fu">fct_relevel</span>(cog<span class="sc">$</span>Task, <span class="st">&quot;recognition&quot;</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>cog <span class="ot">&lt;-</span> cog <span class="sc">%&gt;%</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">Score =</span> Y)</span></code></pre></div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Fit the interaction model, using <code>lm()</code>.
Pass your model to the <code>anova()</code> function, to remind yourself that there is a significant interaction present.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-4&#39;, &#39;sol-start-4&#39;)"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>mdl_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(Score <span class="sc">~</span> Task<span class="sc">*</span>Diagnosis, <span class="at">data =</span> cog)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mdl_int)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Score
##                Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## Task            2   5250 2625.00 16.6373  7.64e-06 ***
## Diagnosis       2   5250 2625.00 16.6373  7.64e-06 ***
## Task:Diagnosis  4   5000 1250.00  7.9225 0.0001092 ***
## Residuals      36   5680  157.78                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>There are various ways to make nice tables in RMarkdown.<br />
Some of the most well known are:</p>
<ul>
<li>The <strong>knitr</strong> package has <code>kable()</code><br />
</li>
<li>The <strong>pander</strong> package has <code>pander()</code></li>
</ul>
<p>Pick one (or find go googling and find a package you like the look of), install the package (if you don’t already have it), then try to create a nice pretty ANOVA table rather than the one given by <code>anova(model)</code>.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-5&#39;, &#39;sol-start-5&#39;)"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">anova</span>(mdl_int))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Df</th>
<th align="right">Sum Sq</th>
<th align="right">Mean Sq</th>
<th align="right">F value</th>
<th align="right">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Task</td>
<td align="right">2</td>
<td align="right">5250</td>
<td align="right">2625.0000</td>
<td align="right">16.637324</td>
<td align="right">0.0000076</td>
</tr>
<tr class="even">
<td align="left">Diagnosis</td>
<td align="right">2</td>
<td align="right">5250</td>
<td align="right">2625.0000</td>
<td align="right">16.637324</td>
<td align="right">0.0000076</td>
</tr>
<tr class="odd">
<td align="left">Task:Diagnosis</td>
<td align="right">4</td>
<td align="right">5000</td>
<td align="right">1250.0000</td>
<td align="right">7.922535</td>
<td align="right">0.0001092</td>
</tr>
<tr class="even">
<td align="left">Residuals</td>
<td align="right">36</td>
<td align="right">5680</td>
<td align="right">157.7778</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pander)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pander</span>(<span class="fu">anova</span>(mdl_int))</span></code></pre></div>
<table style="width:93%;">
<caption>Analysis of Variance Table</caption>
<colgroup>
<col width="29%" />
<col width="6%" />
<col width="12%" />
<col width="13%" />
<col width="13%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Df</th>
<th align="center">Sum Sq</th>
<th align="center">Mean Sq</th>
<th align="center">F value</th>
<th align="center">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>Task</strong></td>
<td align="center">2</td>
<td align="center">5250</td>
<td align="center">2625</td>
<td align="center">16.64</td>
<td align="center">7.64e-06</td>
</tr>
<tr class="even">
<td align="center"><strong>Diagnosis</strong></td>
<td align="center">2</td>
<td align="center">5250</td>
<td align="center">2625</td>
<td align="center">16.64</td>
<td align="center">7.64e-06</td>
</tr>
<tr class="odd">
<td align="center"><strong>Task:Diagnosis</strong></td>
<td align="center">4</td>
<td align="center">5000</td>
<td align="center">1250</td>
<td align="center">7.923</td>
<td align="center">0.0001092</td>
</tr>
<tr class="even">
<td align="center"><strong>Residuals</strong></td>
<td align="center">36</td>
<td align="center">5680</td>
<td align="center">157.8</td>
<td align="center">NA</td>
<td align="center">NA</td>
</tr>
</tbody>
</table>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>As in the previous week’s exercises, let us suppose that we are specifically interested in comparisons of the mean score <em>across the different diagnosis groups for a given task</em>.</p>
<p>Edit the code below to obtain the pairwise comparisons of diagnosis groups for each task. Use the Bonferroni method to adjust for multiple comparisons, and then obtain confidence intervals.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>emm_task <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mdl_int, ? )</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>contr_task <span class="ot">&lt;-</span> <span class="fu">contrast</span>(emm_task, <span class="at">method =</span> ?, <span class="at">adjust =</span> ? )</span></code></pre></div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-6&#39;, &#39;sol-start-6&#39;)"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>emm_task <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mdl_int, <span class="sc">~</span> Diagnosis <span class="sc">|</span> Task)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>contr_task <span class="ot">&lt;-</span> <span class="fu">contrast</span>(emm_task, <span class="at">method =</span> <span class="st">&quot;pairwise&quot;</span>, <span class="at">adjust=</span><span class="st">&quot;bonferroni&quot;</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>contr_task</span></code></pre></div>
<pre><code>## Task = recognition:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           30 7.94 36   3.776  0.0017
##  control - huntingtons        0 7.94 36   0.000  1.0000
##  amnesic - huntingtons      -30 7.94 36  -3.776  0.0017
## 
## Task = grammar:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           20 7.94 36   2.518  0.0492
##  control - huntingtons       40 7.94 36   5.035  &lt;.0001
##  amnesic - huntingtons       20 7.94 36   2.518  0.0492
## 
## Task = classification:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           10 7.94 36   1.259  0.6486
##  control - huntingtons       35 7.94 36   4.406  0.0003
##  amnesic - huntingtons       25 7.94 36   3.147  0.0099
## 
## P value adjustment: bonferroni method for 3 tests</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(contr_task)</span></code></pre></div>
<pre><code>## Task = recognition:
##  contrast              estimate   SE df lower.CL upper.CL
##  control - amnesic           30 7.94 36  10.0517     49.9
##  control - huntingtons        0 7.94 36 -19.9483     19.9
##  amnesic - huntingtons      -30 7.94 36 -49.9483    -10.1
## 
## Task = grammar:
##  contrast              estimate   SE df lower.CL upper.CL
##  control - amnesic           20 7.94 36   0.0517     39.9
##  control - huntingtons       40 7.94 36  20.0517     59.9
##  amnesic - huntingtons       20 7.94 36   0.0517     39.9
## 
## Task = classification:
##  contrast              estimate   SE df lower.CL upper.CL
##  control - amnesic           10 7.94 36  -9.9483     29.9
##  control - huntingtons       35 7.94 36  15.0517     54.9
##  amnesic - huntingtons       25 7.94 36   5.0517     44.9
## 
## Confidence level used: 0.95 
## Conf-level adjustment: bonferroni method for 3 estimates</code></pre>
</div>
<p class="solution-end">
</p>
<div class="frame">
<p><strong>adjusting <span class="math inline">\(\alpha\)</span>, adjusting p</strong></p>
<p>In the lecture we talked about adjusting the <span class="math inline">\(\alpha\)</span> level (i.e., instead of determining significance at <span class="math inline">\(p &lt; .05\)</span>, we might adjust and determine a result to be statistically significant if <span class="math inline">\(p &lt; .005\)</span>, depending on how many tests are in our family of tests).</p>
<p>Note what the functions in R do is adjust the <span class="math inline">\(p\)</span>-value, rather than the <span class="math inline">\(\alpha\)</span>. The Bonferroni method simply multiplies the ‘raw’ p-value by the number of the tests.</p>
</div>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>In question 4 above, there are 9 tests being performed, but there are 3 in each ‘family’ (each <code>Task</code>).</p>
<p>Try changing your answer to question 4 to use <code>adjust = "none"</code>, rather than <code>"bonferroni"</code>, and confirm that the p-values are 1/3 of the size.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-7&#39;, &#39;sol-start-7&#39;)"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>The first Bonferroni adjusted p-value is 0.0492.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.0492</span><span class="sc">/</span><span class="dv">3</span></span></code></pre></div>
<pre><code>## [1] 0.0164</code></pre>
<p>Let’s check that this is the raw p-value:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(emm_task, <span class="at">method =</span> <span class="st">&quot;pairwise&quot;</span>, <span class="at">adjust=</span><span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<pre><code>## Task = recognition:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           30 7.94 36   3.776  0.0006
##  control - huntingtons        0 7.94 36   0.000  1.0000
##  amnesic - huntingtons      -30 7.94 36  -3.776  0.0006
## 
## Task = grammar:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           20 7.94 36   2.518  0.0164
##  control - huntingtons       40 7.94 36   5.035  &lt;.0001
##  amnesic - huntingtons       20 7.94 36   2.518  0.0164
## 
## Task = classification:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           10 7.94 36   1.259  0.2162
##  control - huntingtons       35 7.94 36   4.406  0.0001
##  amnesic - huntingtons       25 7.94 36   3.147  0.0033</code></pre>
</div>
<p class="solution-end">
</p>
</div>
<div id="šídák" class="section level2">
<h2>Šídák</h2>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>The Sidak approach is slightly less conservative than the Bonferroni adjustment. Doing this with the <strong>emmeans</strong> package is easy, can you figure out how?</p>
<p><strong>Hint:</strong> you just have to change the <code>adjust</code> argument in <code>contrast()</code> function.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-8&#39;, &#39;sol-start-8&#39;)"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(emm_task, <span class="at">method =</span> <span class="st">&quot;pairwise&quot;</span>, <span class="at">adjust =</span> <span class="st">&quot;sidak&quot;</span>)</span></code></pre></div>
<pre><code>## Task = recognition:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           30 7.94 36   3.776  0.0017
##  control - huntingtons        0 7.94 36   0.000  1.0000
##  amnesic - huntingtons      -30 7.94 36  -3.776  0.0017
## 
## Task = grammar:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           20 7.94 36   2.518  0.0484
##  control - huntingtons       40 7.94 36   5.035  &lt;.0001
##  amnesic - huntingtons       20 7.94 36   2.518  0.0484
## 
## Task = classification:
##  contrast              estimate   SE df t.ratio p.value
##  control - amnesic           10 7.94 36   1.259  0.5185
##  control - huntingtons       35 7.94 36   4.406  0.0003
##  amnesic - huntingtons       25 7.94 36   3.147  0.0099
## 
## P value adjustment: sidak method for 3 tests</code></pre>
</div>
<p class="solution-end">
</p>
</div>
<div id="tukey" class="section level2">
<h2>Tukey</h2>
<p>Like with Šídák, in R we can easily change to Tukey. For instance, if we wanted to conduct pairwise comparisons of the scores of different Diagnosis groups on different Task types (i.e., the interaction):</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>emm_task <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mdl_int, <span class="sc">~</span> Diagnosis<span class="sc">*</span>Task)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>contr_task <span class="ot">&lt;-</span> <span class="fu">contrast</span>(emm_task, <span class="at">method =</span> <span class="st">&quot;pairwise&quot;</span>, <span class="at">adjust=</span><span class="st">&quot;tukey&quot;</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>contr_task</span></code></pre></div>
<pre><code>##  contrast                                             estimate   SE df t.ratio
##  control recognition - amnesic recognition                  30 7.94 36   3.776
##  control recognition - huntingtons recognition               0 7.94 36   0.000
##  control recognition - control grammar                      15 7.94 36   1.888
##  control recognition - amnesic grammar                      35 7.94 36   4.406
##  control recognition - huntingtons grammar                  55 7.94 36   6.923
##  control recognition - control classification               15 7.94 36   1.888
##  control recognition - amnesic classification               25 7.94 36   3.147
##  control recognition - huntingtons classification           50 7.94 36   6.294
##  amnesic recognition - huntingtons recognition             -30 7.94 36  -3.776
##  amnesic recognition - control grammar                     -15 7.94 36  -1.888
##  amnesic recognition - amnesic grammar                       5 7.94 36   0.629
##  amnesic recognition - huntingtons grammar                  25 7.94 36   3.147
##  amnesic recognition - control classification              -15 7.94 36  -1.888
##  amnesic recognition - amnesic classification               -5 7.94 36  -0.629
##  amnesic recognition - huntingtons classification           20 7.94 36   2.518
##  huntingtons recognition - control grammar                  15 7.94 36   1.888
##  huntingtons recognition - amnesic grammar                  35 7.94 36   4.406
##  huntingtons recognition - huntingtons grammar              55 7.94 36   6.923
##  huntingtons recognition - control classification           15 7.94 36   1.888
##  huntingtons recognition - amnesic classification           25 7.94 36   3.147
##  huntingtons recognition - huntingtons classification       50 7.94 36   6.294
##  control grammar - amnesic grammar                          20 7.94 36   2.518
##  control grammar - huntingtons grammar                      40 7.94 36   5.035
##  control grammar - control classification                    0 7.94 36   0.000
##  control grammar - amnesic classification                   10 7.94 36   1.259
##  control grammar - huntingtons classification               35 7.94 36   4.406
##  amnesic grammar - huntingtons grammar                      20 7.94 36   2.518
##  amnesic grammar - control classification                  -20 7.94 36  -2.518
##  amnesic grammar - amnesic classification                  -10 7.94 36  -1.259
##  amnesic grammar - huntingtons classification               15 7.94 36   1.888
##  huntingtons grammar - control classification              -40 7.94 36  -5.035
##  huntingtons grammar - amnesic classification              -30 7.94 36  -3.776
##  huntingtons grammar - huntingtons classification           -5 7.94 36  -0.629
##  control classification - amnesic classification            10 7.94 36   1.259
##  control classification - huntingtons classification        35 7.94 36   4.406
##  amnesic classification - huntingtons classification        25 7.94 36   3.147
##  p.value
##   0.0149
##   1.0000
##   0.6257
##   0.0026
##   &lt;.0001
##   0.6257
##   0.0711
##   &lt;.0001
##   0.0149
##   0.6257
##   0.9993
##   0.0711
##   0.6257
##   0.9993
##   0.2575
##   0.6257
##   0.0026
##   &lt;.0001
##   0.6257
##   0.0711
##   &lt;.0001
##   0.2575
##   0.0004
##   1.0000
##   0.9367
##   0.0026
##   0.2575
##   0.2575
##   0.9367
##   0.6257
##   0.0004
##   0.0149
##   0.9993
##   0.9367
##   0.0026
##   0.0711
## 
## P value adjustment: tukey method for comparing a family of 9 estimates</code></pre>
<p>We can also use the following, which doesn’t require the <strong>emmeans</strong> package. You might see this when you look online for resources. The <code>aov()</code> function is fitting an ANOVA model, and then <code>TukeyHSD()</code> compares between Diagnosis group; between Task type; and between Diagnosis*Task.</p>
<p>Run the code below yourself to see the output.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(Score <span class="sc">~</span> Diagnosis <span class="sc">*</span> Task, <span class="at">data =</span> cog))</span></code></pre></div>
</div>
<div id="scheffe" class="section level2">
<h2>Scheffe</h2>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>emm_task <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mdl_int, <span class="sc">~</span> Diagnosis <span class="sc">*</span> Task)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>contr_task <span class="ot">&lt;-</span> <span class="fu">contrast</span>(emm_task, <span class="at">method =</span> <span class="st">&quot;pairwise&quot;</span>, <span class="at">adjust=</span><span class="st">&quot;scheffe&quot;</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>contr_task</span></code></pre></div>
<pre><code>##  contrast                                             estimate   SE df t.ratio
##  control recognition - amnesic recognition                  30 7.94 36   3.776
##  control recognition - huntingtons recognition               0 7.94 36   0.000
##  control recognition - control grammar                      15 7.94 36   1.888
##  control recognition - amnesic grammar                      35 7.94 36   4.406
##  control recognition - huntingtons grammar                  55 7.94 36   6.923
##  control recognition - control classification               15 7.94 36   1.888
##  control recognition - amnesic classification               25 7.94 36   3.147
##  control recognition - huntingtons classification           50 7.94 36   6.294
##  amnesic recognition - huntingtons recognition             -30 7.94 36  -3.776
##  amnesic recognition - control grammar                     -15 7.94 36  -1.888
##  amnesic recognition - amnesic grammar                       5 7.94 36   0.629
##  amnesic recognition - huntingtons grammar                  25 7.94 36   3.147
##  amnesic recognition - control classification              -15 7.94 36  -1.888
##  amnesic recognition - amnesic classification               -5 7.94 36  -0.629
##  amnesic recognition - huntingtons classification           20 7.94 36   2.518
##  huntingtons recognition - control grammar                  15 7.94 36   1.888
##  huntingtons recognition - amnesic grammar                  35 7.94 36   4.406
##  huntingtons recognition - huntingtons grammar              55 7.94 36   6.923
##  huntingtons recognition - control classification           15 7.94 36   1.888
##  huntingtons recognition - amnesic classification           25 7.94 36   3.147
##  huntingtons recognition - huntingtons classification       50 7.94 36   6.294
##  control grammar - amnesic grammar                          20 7.94 36   2.518
##  control grammar - huntingtons grammar                      40 7.94 36   5.035
##  control grammar - control classification                    0 7.94 36   0.000
##  control grammar - amnesic classification                   10 7.94 36   1.259
##  control grammar - huntingtons classification               35 7.94 36   4.406
##  amnesic grammar - huntingtons grammar                      20 7.94 36   2.518
##  amnesic grammar - control classification                  -20 7.94 36  -2.518
##  amnesic grammar - amnesic classification                  -10 7.94 36  -1.259
##  amnesic grammar - huntingtons classification               15 7.94 36   1.888
##  huntingtons grammar - control classification              -40 7.94 36  -5.035
##  huntingtons grammar - amnesic classification              -30 7.94 36  -3.776
##  huntingtons grammar - huntingtons classification           -5 7.94 36  -0.629
##  control classification - amnesic classification            10 7.94 36   1.259
##  control classification - huntingtons classification        35 7.94 36   4.406
##  amnesic classification - huntingtons classification        25 7.94 36   3.147
##  p.value
##   0.1131
##   1.0000
##   0.8852
##   0.0329
##   0.0001
##   0.8852
##   0.3060
##   0.0003
##   0.1131
##   0.8852
##   0.9999
##   0.3060
##   0.8852
##   0.9999
##   0.6128
##   0.8852
##   0.0329
##   0.0001
##   0.8852
##   0.3060
##   0.0003
##   0.6128
##   0.0080
##   1.0000
##   0.9894
##   0.0329
##   0.6128
##   0.6128
##   0.9894
##   0.8852
##   0.0080
##   0.1131
##   0.9999
##   0.9894
##   0.0329
##   0.3060
## 
## P value adjustment: scheffe method with rank 8</code></pre>
<div id="when-to-use-which-correction" class="section level3">
<h3>When to use Which Correction</h3>
<div class="yellow">
<p><strong>Bonferroni</strong></p>
<ul>
<li>Use Bonferroni’s method when you are interested in a small number of planned contrasts (or pairwise comparisons).</li>
<li>Bonferroni’s method is to divide alpha by the number of tests/confidence intervals.</li>
<li>Assumes that all comparisons are independent of one another.<br />
</li>
<li>It sacrifices slightly more power than Tukey’s method (discussed below), but it can be applied to any set of contrasts or linear combinations (i.e., it is useful in more situations than Tukey).</li>
<li>It is usually better than Tukey if we want to do a small number of planned comparisons.</li>
</ul>
<p><strong>Šídák</strong></p>
<ul>
<li>(A bit) more powerful than the Bonferroni method.</li>
<li>Assumes that all comparisons are independent of one another.</li>
<li>Less common than Bonferroni method, largely because it is more difficult to calculate (not a problem now we have computers).</li>
</ul>
<p><strong>Tukey</strong></p>
<ul>
<li>It specifies an exact family significance level for comparing all pairs of treatment means.<br />
</li>
<li>Use Tukey’s method when you are interested in all (or most) pairwise comparisons of means.</li>
</ul>
<p><strong>Scheffe</strong></p>
<ul>
<li>It is the most conservative (least powerful) of all tests.</li>
<li>It controls the family alpha level for testing all possible contrasts.</li>
<li>It should be used if you have not planned contrasts in advance.</li>
<li>For testing pairs of treatment means it is too conservative (you should use Bonferroni or Šídák).</li>
</ul>
<div class="blue">
<p>In <strong>R</strong>, you can easily change which correction you are using via the <code>adjust =</code> argument.</p>
</div>
</div>
</div>
</div>
</div>
<div id="lie-detection-experiment---write-up-example" class="section level1">
<h1>Lie Detection Experiment - Write Up Example</h1>
<p>In this section of the lab, you will be presented with a research question, and tasked with writing up and presenting your analyses. Try to write three complete sections - Analysis Strategy, Results, and Discussion. Make sure to familiarise yourself with the data available in the codebook below. We will use the questions to go through the analysis step by step, before writing up. Please note that the lab includes short example write ups that may not be complete for every question you are asked. It is intended to give you a sense of the style. Think about the steps you need to complete in order to answer the research question, and the order in which you should complete these.</p>
<div class="optional-begin">
<span id="opt-start-9" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-9&#39;, &#39;opt-start-9&#39;)"> Lie detectors: Data Codebook</span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p>120 participants took part in a study in which they were presented with 100 recordings, and were tasked with guessing whether the speaker in each recording was lying or whether they were telling the truth.</p>
<p>Participants scored points every time they correctly identified a truth or a lie, and lost points whenever they mistook a lie for a truth (or vice versa). The maximum possible points to be scored was 100.</p>
<p>Half of the participants (60) were shown recordings in audio and video, the other half were presented with only the audio track.</p>
<p>Prior to taking part in the experiment, participants were given material to read for 10 minutes. Half of the participants in each condition (30 in the audio-only condition, and 30 in the audiovideo condition) were given instructional material used by the Police Force to train detectives to pick up on dishonesty during interrogations via various verbal and non-verbal cues. The remaining 30 participants in each condition were given a series of <a href="https://external-preview.redd.it/OY7xRuBBRkx8JFrjYoh3PswM2VMBDHBv4oXbpIEcB3Q.jpg?auto=webp&amp;s=1a12316259fdfd314d4060f44f30260735741da5">cartoon strips to read</a>.</p>
<p>The data is available at <a href="https://uoepsy.github.io/data/lietraining.csv" class="uri">https://uoepsy.github.io/data/lietraining.csv</a></p>
</div>
<p class="optional-end">
</p>
<blockquote>
<p>Research Question</p>
<p>Do Police training materials and the mode of communication influence the accuracy of veracity judgements?</p>
</blockquote>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Step 1 is always to read in the data, then to explore, check, describe, and visualise it.</p>
<ul>
<li>Load the data</li>
<li>Examine the data</li>
<li>Check coding of variables (ie., are categorical variables factors?)</li>
<li>Produce a descriptives table for the variables of interest</li>
<li>Produce a plot showing the mean points for each condition</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-10&#39;, &#39;sol-start-10&#39;)"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#read in data</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>liedat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://uoepsy.github.io/data/lietraining.csv&quot;</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co">#check coding</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(liedat)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##   pid     age trained audiovideo  points
##   &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt;
## 1 ppt_1    26 y       audio+video   36.2
## 2 ppt_2    22 y       audio+video   38.5
## 3 ppt_3    18 y       audio+video   34.2
## 4 ppt_4    22 y       audio+video   52.6
## 5 ppt_5    21 y       audio+video   38.9
## 6 ppt_6    27 y       audio+video   37.5</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#make variables factors &amp; label</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>liedat<span class="sc">$</span>audiovideo <span class="ot">&lt;-</span> <span class="fu">factor</span>(liedat<span class="sc">$</span>audiovideo, <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;audio&quot;</span>,<span class="st">&quot;audio+video&quot;</span>))</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>liedat<span class="sc">$</span>trained <span class="ot">&lt;-</span> <span class="fu">factor</span>(liedat<span class="sc">$</span>trained, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;untrained&quot;</span>,<span class="st">&quot;trained&quot;</span>))</span></code></pre></div>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#descriptives table</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>liestats <span class="ot">&lt;-</span> liedat <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(audiovideo, trained) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanpoints =</span> <span class="fu">mean</span>(points),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">se =</span> <span class="fu">sd</span>(points)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>())</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>liestats</span></code></pre></div>
<pre><code>## # A tibble: 4 x 4
## # Groups:   audiovideo [2]
##   audiovideo  trained   meanpoints    se
##   &lt;fct&gt;       &lt;fct&gt;          &lt;dbl&gt; &lt;dbl&gt;
## 1 audio       untrained       52.8  1.27
## 2 audio       trained         53.7  1.55
## 3 audio+video untrained       49.9  1.01
## 4 audio+video trained         40.4  1.12</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(liestats, <span class="fu">aes</span>(<span class="at">x =</span> audiovideo, <span class="at">y =</span> meanpoints, <span class="at">color =</span> trained)) <span class="sc">+</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_linerange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> meanpoints <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> se, <span class="at">ymax =</span> meanpoints <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> se)) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.numeric</span>(audiovideo)))</span></code></pre></div>
<p><img src="2_05_multi_comp_writeup_files/figure-html/unnamed-chunk-19-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Step 2 is to run your model(s) of interest to answer your research question, and make sure that the data meet the assumptions of your chosen test.</p>
<ul>
<li>Conduct a two-way ANOVA</li>
<li>Check assumptions</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-11&#39;, &#39;sol-start-11&#39;)"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#build model</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>lie_mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(points <span class="sc">~</span> audiovideo <span class="sc">*</span> trained, <span class="at">data =</span> liedat)</span></code></pre></div>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lie_mdl)</span></code></pre></div>
<p><img src="2_05_multi_comp_writeup_files/figure-html/unnamed-chunk-21-1.png" width="60%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># look at model output - summary() and anova()</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lie_mdl)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = points ~ audiovideo * trained, data = liedat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -15.1947  -4.2134  -0.7559   4.5235  21.1755 
## 
## Coefficients:
##                                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                           52.7591     1.2576  41.953  &lt; 2e-16 ***
## audiovideoaudio+video                 -2.8367     1.7785  -1.595    0.113    
## trainedtrained                         0.9759     1.7785   0.549    0.584    
## audiovideoaudio+video:trainedtrained -10.4830     2.5152  -4.168 5.95e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.888 on 116 degrees of freedom
## Multiple R-squared:  0.3768, Adjusted R-squared:  0.3607 
## F-statistic: 23.38 on 3 and 116 DF,  p-value: 6.591e-12</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lie_mdl)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: points
##                     Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## audiovideo           1 1957.7 1957.71  41.263 3.046e-09 ***
## trained              1  545.8  545.85  11.505   0.00095 ***
## audiovideo:trained   1  824.2  824.20  17.372 5.949e-05 ***
## Residuals          116 5503.6   47.45                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>The third and final step(s) somewhat depends on the outcomes of step 2. Here, you may need to consider conducting further analyses before writing up / describing your results in relation to the research question.</p>
<ul>
<li>Perform a pairwise comparison of the mean accuracy (as measured by points accrued) across the 2×2 factorial design, making sure to adjust for multiple comparisons by the method of your choice.</li>
<li>Interpret your results in relation to the research question (remember you can refer to your previous plotting when doing this!).</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-12&#39;, &#39;sol-start-12&#39;)"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>emms_lie <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(lie_mdl, <span class="sc">~</span> audiovideo <span class="sc">*</span> trained)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>lie_con <span class="ot">&lt;-</span> <span class="fu">contrast</span>(emms_lie, <span class="at">method =</span> <span class="st">&quot;pairwise&quot;</span>, <span class="at">adjust=</span><span class="st">&quot;tukey&quot;</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>lie_con</span></code></pre></div>
<pre><code>##  contrast                                        estimate   SE  df t.ratio
##  audio untrained - (audio+video untrained)          2.837 1.78 116   1.595
##  audio untrained - audio trained                   -0.976 1.78 116  -0.549
##  audio untrained - (audio+video trained)           12.344 1.78 116   6.941
##  (audio+video untrained) - audio trained           -3.813 1.78 116  -2.144
##  (audio+video untrained) - (audio+video trained)    9.507 1.78 116   5.346
##  audio trained - (audio+video trained)             13.320 1.78 116   7.489
##  p.value
##   0.3855
##   0.9467
##   &lt;.0001
##   0.1456
##   &lt;.0001
##   &lt;.0001
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confidence intervals</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lie_con)</span></code></pre></div>
<pre><code>##  contrast                                        estimate   SE  df lower.CL
##  audio untrained - (audio+video untrained)          2.837 1.78 116    -1.80
##  audio untrained - audio trained                   -0.976 1.78 116    -5.61
##  audio untrained - (audio+video trained)           12.344 1.78 116     7.71
##  (audio+video untrained) - audio trained           -3.813 1.78 116    -8.45
##  (audio+video untrained) - (audio+video trained)    9.507 1.78 116     4.87
##  audio trained - (audio+video trained)             13.320 1.78 116     8.68
##  upper.CL
##     7.473
##     3.660
##    16.980
##     0.823
##    14.143
##    17.956
## 
## Confidence level used: 0.95 
## Conf-level adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lie_con)</span></code></pre></div>
<p><img src="2_05_multi_comp_writeup_files/figure-html/unnamed-chunk-23-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div id="analysis-strategy" class="section level3">
<h3>Analysis Strategy</h3>
<div class="optional-begin">
<span id="opt-start-13" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-13&#39;, &#39;opt-start-13&#39;)"> Example Write-Up of Analysis Strategy Section</span>
</div>
<div id="opt-body-13" class="optional-body" style="display: none;">
<p>Data obtained from <a href="https://uoepsy.github.io/data/lietraining.csv" class="uri">https://uoepsy.github.io/data/lietraining.csv</a> contained information on <code>nrow(liedat)</code> participants who took part in a study concerning lie detection. Participants were each presented with 100 recordings (half were shown recordings in audio and video, and the other half audio only), and were tasked with guessing whether the speaker in each recording was lying or whether they were telling the truth. Participants scored 1 point each time they correctly identified a truth or a lie, and lost 1 point whenever they mistook a lie for a truth (or vice versa). The maximum score was 100, where higher scores reflected higher levels of accuracy. Prior to taking part in the experiment participants were given materials to read. Half of the participants in each condition were given instructional material used by the Police Force (used to train detectives to pick up on dishonesty during interrogations via various verbal and non-verbal cues) and the remaining 30 participants in each condition were given a series of <a href="https://external-preview.redd.it/OY7xRuBBRkx8JFrjYoh3PswM2VMBDHBv4oXbpIEcB3Q.jpg?auto=webp&amp;s=1a12316259fdfd314d4060f44f30260735741da5">cartoon strips to read</a>.</p>
<p>All participant data was complete, and accuracy scores (points) within range i.e., 0-100. Categorical variables were coded as factors, where audio was the reference level for mode of communication, and untrained was the reference level for training materials.</p>
<p>To investigate whether police training materials (trained vs untrained) and the mode of communication (audio vs audiovideo) interacted to influence the accuracy of veracity judgements, a two-way ANOVA model was used. Effects were be considered statistically significant at <span class="math inline">\(\alpha = 0.05\)</span>. Using dummy coding, the following model specification was used:</p>
<span class="math display">\[\begin{aligned}
\text{Points} &amp;= \beta_0 \\
&amp;+ \beta_1 D_\text{AudioVideo} + \beta_2 D_\text{Trained} \\
&amp;+ \beta_3 (D_\text{AudioVideo} * T_\text{Trained}) \\
&amp;+ \epsilon 
\end{aligned}\]</span>
<p>To address the research question of whether the interaction between training materials and mode of communication is significant, this corresponded to testing whether the interaction coefficient was equal to zero:</p>
<p><span class="math display">\[
H_0: \beta_3 = 0 \\
H_1: \beta_3 \neq 0
\]</span>
The following assumptions were visually assessed using diagnostic plots: linearity (via plot of residuals vs fitted values), independence (with the previous plot and a plot of residuals vs index), equal variances (via a scale-location plot), and normality (via a qqplot of the residuals). We will also check if there is any evidence of multicollinearity by checking the VIF values, where values &gt; 5 will be considered to indicate moderate multicollinearity, and values &gt; 10 severe.</p>
</div>
<p class="optional-end">
</p>
</div>
<div id="results" class="section level3">
<h3>Results</h3>
<div class="optional-begin">
<span id="opt-start-14" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-14&#39;, &#39;opt-start-14&#39;)"> Example Write-Up of Results Section</span>
</div>
<div id="opt-body-14" class="optional-body" style="display: none;">
<p>Descriptive statistics are displayed in Table <a href="#tab:descript">1</a>.</p>
<table>
<caption><span id="tab:descript">Table 1: </span>Descriptive Statistics</caption>
<thead>
<tr class="header">
<th align="left">audiovideo</th>
<th align="left">trained</th>
<th align="right">meanpoints</th>
<th align="right">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">audio</td>
<td align="left">untrained</td>
<td align="right">52.76</td>
<td align="right">1.27</td>
</tr>
<tr class="even">
<td align="left">audio</td>
<td align="left">trained</td>
<td align="right">53.74</td>
<td align="right">1.55</td>
</tr>
<tr class="odd">
<td align="left">audio+video</td>
<td align="left">untrained</td>
<td align="right">49.92</td>
<td align="right">1.01</td>
</tr>
<tr class="even">
<td align="left">audio+video</td>
<td align="left">trained</td>
<td align="right">40.42</td>
<td align="right">1.12</td>
</tr>
</tbody>
</table>
<p>In the audio condition, there did not appear to be a difference between trained and non-trained scores. However, untrained scored higher than trained in the audio+video condition. There appeared to be an interaction (see Figure <a href="#fig:lieplot">1</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:lieplot"></span>
<img src="2_05_multi_comp_writeup_files/figure-html/lieplot-1.png" alt="Interaction Plot" width="60%" />
<p class="caption">
Figure 1: Interaction Plot
</p>
</div>
<p>Accuracy of veracity judgements (measured by points scored in lie-detecting game) were analysed with a 2 (audio vs audiovideo) <span class="math inline">\(\times\)</span> 2 (untrained vs trained) between-subjects ANOVA.</p>
<p>The model met assumptions of linearity and independence (see top left panel of Figure <a href="#fig:assumpt">2</a>), homoscedasticity (see bottom left panel of Figure <a href="#fig:assumpt">2</a>), and normality (see top right panel of Figure <a href="#fig:assumpt">2</a>) where QQplot showed very little deviation from the diagonal line.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:assumpt"></span>
<img src="2_05_multi_comp_writeup_files/figure-html/assumpt-1.png" alt="Assumption Checks" width="60%" />
<p class="caption">
Figure 2: Assumption Checks
</p>
</div>
<p>There was a significant interaction between presentation mode and whether or not participants had received training for detecting lies <span class="math inline">\(F(1, 116) = 17.37, p &lt;. 001\)</span> (see Table <a href="#tab:aovtable"><strong>??</strong></a> and Figure <a href="#fig:predint">3</a>).</p>
<table style="width:100%;">
<caption>Analysis of Variance Table</caption>
<colgroup>
<col width="34%" />
<col width="8%" />
<col width="12%" />
<col width="13%" />
<col width="13%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Df</th>
<th align="center">Sum Sq</th>
<th align="center">Mean Sq</th>
<th align="center">F value</th>
<th align="center">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>audiovideo</strong></td>
<td align="center">1</td>
<td align="center">1958</td>
<td align="center">1958</td>
<td align="center">41.26</td>
<td align="center">3.046e-09</td>
</tr>
<tr class="even">
<td align="center"><strong>trained</strong></td>
<td align="center">1</td>
<td align="center">545.8</td>
<td align="center">545.8</td>
<td align="center">11.5</td>
<td align="center">0.00095</td>
</tr>
<tr class="odd">
<td align="center"><strong>audiovideo:trained</strong></td>
<td align="center">1</td>
<td align="center">824.2</td>
<td align="center">824.2</td>
<td align="center">17.37</td>
<td align="center">5.949e-05</td>
</tr>
<tr class="even">
<td align="center"><strong>Residuals</strong></td>
<td align="center">116</td>
<td align="center">5504</td>
<td align="center">47.45</td>
<td align="center">NA</td>
<td align="center">NA</td>
</tr>
</tbody>
</table>
<p>Results suggested that the difference in points did not differ significantly in the audio condition regardless of training, but that there were significant differences in the audio video condition.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:predint"></span>
<img src="2_05_multi_comp_writeup_files/figure-html/predint-1.png" alt="Predicted Scores" width="60%" />
<p class="caption">
Figure 3: Predicted Scores
</p>
</div>
<p>To explore the interaction further, pairwise comparisons were conducted. Tukey’s Honestly Significant Difference comparisons (see Figure <a href="#fig:contrastplot">4</a>) indicated that, contrary to what one might expect, participants who were presented with audiovisual recordings scored on average 9.5 points lower when they had read the police training materials compared to when they had received no training (95% CI [4.87 — 14.14]). The presentation mode (audio vs audio-video) was not found to result in a significantly different average score for those who were untrained (95% CI [-1.80 — 7.47]), and nor did training appear to have any effect on detecting lies in the audio-only condition (95% CI [-5.61 — 3.66]).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:contrastplot"></span>
<img src="2_05_multi_comp_writeup_files/figure-html/contrastplot-1.png" alt="Tukey HSD Pairwise Comparisons" width="80%" />
<p class="caption">
Figure 4: Tukey HSD Pairwise Comparisons
</p>
</div>
</div>
<p class="optional-end">
</p>
</div>
<div id="discussion" class="section level3">
<h3>Discussion</h3>
<div class="optional-begin">
<span id="opt-start-15" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-15&#39;, &#39;opt-start-15&#39;)"> Example Write-Up of Discussion Section</span>
</div>
<div class="optional-body" id = "opt-body-15" style="display: none;">



<p>The findings indicated that, on the whole, people are bad at determining whether they are being presented with a lie or the truth, as the overall mean score was 49.2 out of 100 (SD = 8.61), where a series of completely random guesses expected to score 50/100. The police training materials did not appear to improve lie detection, in fact with trained participants performing worse (compared to untrained) in the audiovisual condition. This may indicate that the training materials focus too heavily on visual cues, which perhaps are not actually associated with dishonesty in the appropriate way.</p>
<!-- Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>what defines a ‘family’ of tests is debateable.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
