# Assumptions of the linear regression model {#chap-slr-assumptions}


```{r echo=FALSE}
# Solutions
SHOW_SOLS = TRUE

# Chunk options
knitr::opts_chunk$set(
    message = FALSE, 
    warning = FALSE, 
    fig.align = 'center',
    out.width = '60%'
)

# ggplot settings
library(ggplot2)
theme_set(
  theme_bw(base_size = 15) + 
    theme(plot.title = element_text(hjust = 0.5))
)

# reproducibility
set.seed(1)
```

:::red
**PRE-LAB ACTIVITIES**

Before attempting the lab please read [Chapter 2 of Lewis-Beck by clicking this link](https://discovered.ed.ac.uk/permalink/f/gfso8q/44UOE_ALMA51187817940002466).
:::

:::lo
**LEARNING OBJECTIVES**

1. Being able to state the assumptions underlying a linear regression model
2. Understand how to assess if a fitted model satisfies the regression assumptions
3. Understand how to use transformations when these assumptions are not met
:::


## Assess {-}

In this lab we will continue the analysis of the [riverview.csv](#dc-riverview) data to examine whether education level is related to income. 

Recall the four-step process to modelling that we will be following throughout the course:

1. CHOOSE
2. FIT
3. ASSESS
4. USE

In the previous lab we

- specified the research question;
- read the data into R;
- performed exploratory data analysis by investigating marginal distributions of the variables and relationships between them;
- chose a form for the model based on the data exploration;
- fitted the specified model using R;
- investigated how to extract relevant information from the fitted model;
- examined in detail the output returned by R.


<br />

This lab will be about the *assess* phase. This is a fundamental step in the statistical analysis as:

:::frame
**KEY CONCEPT**

Every statistical model has basic underlying assumptions that need to be checked before any valid conclusions can be drawn.

Throughout this lab, we will evaluate residual plots to determine whether the model assumptions are met. 

When model assumptions are not met, the test statistics do not follow the corresponding t-distribution or F-distribution. 
Thus, the p-values may not be correct. No conclusions should be drawn from any statistical model without checking the appropriate assumptions.
:::


### Assumptions of the simple linear regression model {-}

Recall from the previous lab that, based on the data exploration, we specified the following model between $x$ = education level and $y$ = income:
$$
y = \beta_0 + \beta_1 x + \epsilon \quad \text{where} \quad \epsilon \sim N(0, \sigma)
$$
where 

- $\mu_{y|x} = \beta_0 + \beta_1 x$ represents the systematic part of the model giving the mean of $y$ at each value of $x$;
- $\epsilon$ represents the error (deviation) from that mean, and the errors are independent from one another.


We can summarise the assumptions of the simple linear regression model with the following easy to memorise acronym:

**L I N E**

- Linearity: The response variable $y$ should be linearly associated to the predictor $x$

- Independence: The error terms should be independent from one another.
That is, is no relationship between one observation and the next. For example, knowing that the 8th unit had a higher income than average does not provide any information about whether the 7th or 9th unit will be above or below the average.

- Normality: The subpopulations of responses at the different values of the explanatory variable all have normal distributions.

- Equal variances: The spread of the responses around the straight line is the same at all levels of the explanatory variable.

We will analyse each assumption in turn by understanding its meaning in more depth, exploring how to verify it using R, and understand how to address situations in which the assumption doesn't hold.

### Linearity {-}


### Independence {-}


### Normality {-}


### Equal variances {-}



