project:
  type: website
  render: 
    - "*.qmd"
    - "!archive/"
  output-dir: ../docs/2627/tutors/

website:
  title: "DAPR2 Lab Exercises"
  navbar: 
    background: primary
    search: true
    left:
      - text: "Block 1: Intro LM"
        menu: 
          - 01.qmd
      - text: "Block 2: Extending LM"
      - text: "Block 3: Interactions"
      - text: "Block 4: Logistic regression"


format:
  html:
    page-layout: full
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    link-citations: true
    number-sections: false
    code-copy: true


