project:
  type: website
  render: 
    - "*.qmd"
    - "!archive/"
  output-dir: ../docs/2627/tutors/

website:
  title: "DAPR2 Lab Exercises"
  navbar: 
    background: primary
    search: true
    left:
      - text: "Block 1: Intro LM"
        menu: 
            - block1_introLM/01.qmd
            - block1_introLM/02.qmd
            - block1_introLM/03.qmd
            - block1_introLM/04.qmd
            - block1_introLM/05.qmd
      - text: "Block 2: Extending LM"
        menu:
            - block2_moreLM/06.qmd
            - block2_moreLM/07.qmd
            - block2_moreLM/08.qmd
            - block2_moreLM/09.qmd
            - block2_moreLM/10.qmd
      - text: "Block 3: Interactions"
      - text: "Block 4: Logistic regression"
        menu:
            - block4_logistic/16.qmd


format:
  html:
    page-layout: full
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    link-citations: true
    number-sections: false
    code-copy: true


