---
title: "Home"
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
---

Welcome to the Data Analysis for Psychology in R 2 (DAPR2) lab workbook. Using the menu on the left, you can find lab materials for each week. 

## Group Work

You are expected to work through the lab tasks in groups of up to 5 students. In each group, each week one person is the driver and the rest are navigators. Each week the driver will rotate so that everyone experiences being a driver at least once.
  
### Roles   
  
+ **Driver**: Responsible for typing the code and written solutions for their designated week, and sharing the resulting RMarkdown file with the group via the Learn group discussion space.  
  
+ **Navigator**: Responsible for suggesting and commenting on the code, spotting typos, fixing errors, and generating the text-based solutions.    
  
## Help, Support & Feedback

### Within Lab Workbook

#### Hints, Notes, and Example Write-Up / Interpretation

Hints are shown in a green box, with the title 'Hint'. If you are unsure what to do, check the collapsible hint provided.

:::{.callout-tip appearance="simple" collapse="true"}

### Hint

This is an example of a hint. They will usually link you to the course flashcards page that we will build on as we progress throughout the course. 

:::

Notes are displayed in blue boxes, with the title 'Note'. These are occasionally used to draw your attention to a specific point. 

:::{.callout-note}

This is an example of a note.

:::

Example write-ups and/or interpretations are shown with a red right border. These are helpful to check your interpretation against, and a useful guide to use in future when interpreting and/or writing up results. 


::: {.callout-important icon=false appearance="minimal"}

This is an example write-up / interpretation block. 

:::

#### Flashcards

The purpose of the flashcards is to complement your core learning materials i.e., your lecture and lab materials, by offering additional guidance and examples on key concepts/topics. They are designed to deepen your understanding, clarify complex concepts, and help you make connections between different areas of study. Think of it as an extra resource that supports what you’re learning in the classroom. 

You may want to consider using these as a supporting document whilst your work through lab exercises, and/or refer to in order to aid revision. 

#### Solutions 

Solutions are made available each Friday (usually around 12 noon). To view solutions, click the drop down 'Solution' button within the lab sheet. 

__Important__
<br>
Before checking the solution you should review the lecture slides and lab hints. You should also avoid copying and pasting code from previous solutions.  
  
Instead, you should:

1. Try to figure out the answer yourself in collaboration with your peers (and/or ask for help from a staff member if needed).
2. Type the code out yourself if adapting from previous exercises (and annotate your `R` code chunks so you know what your code is doing & why - future you will thank you for this). 

### Asking Questions

- During labs, if you have a question, please ask one of the Tutors for support. 
- Outside of labs, we encourage you to use the various support options, details of which can be found on the course Learn page.

## Tips on Googling / Using AI in Relation to Statistics and R
  
Searching online for help with statistics and R can be both a help and a hindrance.
  
If you have an error message in `R`, copy the error message into Google/AI. The results returned can sometimes just cause more confusion, but sometimes something might jump out at you and help you solve the problem. The same applies with searching for help with statistics - search for “what is a $p$-value”, and you’ll find many many different articles and forum discussions etc. Some of them you will find too technical, but don’t be scared - the vast majority of people work in statistics will find these too technical too. Some of them you might feel are too simple/not helpful. As a general guide, keep clicking around the search responses, and you may end up finding that someone, somewhere, has provided an explanation at the right level. If you find something during your search which you don’t quite understand, feel free to link it in a post on the discussion forum!

## Feedback on Labs
 
If you wish to make suggestions for improvements to these workbooks (or if you spot any typos!), please email ppls.psych.stats@ed.ac.uk making sure to include the course name in the subject.