---
title: '<h1 style="color:#BF1932">Welcome to Data Analysis for Psychology in R - 2</h1>'
output: 
  bookdown::html_document2:
    toc: false
---


Data Analysis for Psychology in R 2 (DAPR2) is a course designed for those wishing to extend their knowledge of statistics and data analysis, while consolidating the topics found in most introductory to statistics courses. Specifically, the course provides a thorough introduction to linear models, with a focus on applications to both correlational and experimental study designs for answering psychological questions.  

### Pre-requisites

It is strongly recommended that students have taken Data Analysis for Psychology in R 1 (DAPR1). For those who were unable to take it and those who wish to refresh their knowledge of the course from last year (recommended), the workbook for DAPR1 in 2019/20 can be found [here](https://uoe-psychology.github.io/uoe_psystats/dapr1/book/). 

# How to approach DAPR2

Learning statistics can be daunting at times. Often it feels like things get more confusing before they get clearer! Sometimes it can be difficult to even identify what it is that you're struggling to understand. However, you can also look forward to little light-bulb moments where suddenly your understanding slots in to place.  

Try to keep up with course material, be inquisitive, and do not be afraid to ask questions. You will love this course as you will then have the skills to answer a broad range of research questions. It is really important that you establish good working patterns for the DAPR2 course early. It will help you throughout the rest of your degree. The DAPR2 course has been structured to encourage continual engagement, based on the fact that these types of skills are best acquired through regular practice. We strongly encourage students to engage with one another and with the team of tutors, teaching coordinators and lecturers, through the various channels detailed below. These are your chance to come and clarify any points of misunderstanding with the teaching team while it is all still fresh in your mind. Working with friends, sharing ideas, explaining concepts, and discussing with the teaching team are all highly effective tools for learning. We hope we can build an atmosphere that will encourage these things.  

There are a variety of ways in which you can interact with the teaching team and with other students. Details of these can be found on the weekly materials pages on Learn: 

+ **Lab Drop-in sessions.** We have an excellent team of tutors who are available at various slots throughout the week (all at different times of day). You can join a session and ask them anything about the exercises. 
+ **Discussion Forums.** There are weekly discussion forums for you to ask questions on any of the content from that week (or for you to share with other students any relevant materials you might have found useful). There are separate forums for questions concerning, for instance, course assessments, as well as a general forum for anything else. 
+ **Office Hours of Lecturers and STCs.** Lecturers and Senior Teaching Coordinators hold office hours every week. Feel free to drop in and ask any questions you might have about the materials, logistics about the course, or just come and say hi! You can also email the STCs at [ug.ppls.stats@ed.ac.uk](mailto:ug.ppls.stats@ed.ac.uk).  


### Tips on googling statistics and R

Searching online for help with statistics and R can be both a help and a hindrance.  
If you have an error message in R, copy the error message into google. The results returned can sometimes just cause more confusion, but sometimes something might jump out at you and help you solve the problem. The same applies with searching the internet for help with statistics - search for "what is a p-value", and you'll find many many different articles and forum discussions etc. Some of them you will find too technical, but don't be scared - the vast majority of people work in statistics will find these too technical too. Some of them you might feel are too simple/not helpful. As a general guide, keep clicking around the search responses, and you may end up finding that someone, somewhere, has provided an explanation at the right level. If you find something during your search which you don't quite understand, feel free to link it in a post on the discussion forum!  


# Teaching team


Lecturer: ?

STCs:

tutor team:
