---
title: "Assumptions for LMMs"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

## Why do models make assumptions?

We can think of a linear model as a way to describe the process of how our data was generated.

Models are simplifications of processes going on in the world.
In order to simplify these processes, a model will specify or "hard-code" certain aspects of the data generating process, and those aspects cannot be changed.
Unchangeable aspects of a model's data generating process are what we call "assumptions".

Assumptions are not like significance tests: it's not the case that the assumption is either "accepted" or "rejected".
The decision process is blurrier than that.
When evaluating a model's assumptions, we are asking ourselves: **Are we satisfied that the unchangeable aspects of the model are reasonable enough simplifications, so that the model will still give us reasonable parameter estimates?**


An acronym for the four assumptions a linear model makes is **"LINE".**


## L = Linearity of association

- A linear model can **only** model associations between predictor and outcome in terms of a straight line. Within the basic linear model machinery, this cannot be changed, and we just have to accept it. That's what it means to be an "assumption".
  - If an association *doesn't* follow a straight line, then a linear model cannot accurately capture it.
  -  Think of predicting height as a function of age, or `height ~ age`, for example. Height rises steeply when ages are small and then eventually tapers off (and may even start to decrease in old age!).
  - If we used a linear model to model `height ~ age`, then our model will give us the best straight line it can.
- To be satisfied with a linear model of that data, **we have to assume that the best possible straight line is a good representation of the data.**
  
  
## I = Independence of errors

- A linear model can **only** model errors as residuals that are independent from one another. Within the basic linear model machinery, this cannot be changed.
- To be satisfied with a simple linear model of our data, **we have to assume that independent residuals are a good representation of the data.**
- One common source of non-independence are data points that come from the same source (e.g., in repeated-measures data, the same person will contribute multiple observations). In DAPR3, you'll learn how to deal with this scenario.

  
## N = Normality of errors

  - A linear model can **only** model errors as residuals that are normally distributed. Within the basic linear model machinery, this cannot be changed.
  - To be satisfied with a linear model of our data, **we have to assume that normally-distributed residuals are a good representation of the data.**
  
## E = Equal variance of errors

- A linear model can **only** model errors as residuals that have equal variance. Within the basic linear model machinery, this cannot be changed.
- To be satisfied with a linear model of our data, **we have to assume that residuals with equal variance are a good representation of the data.**


## Linked flash cards

### Outgoing links

- TODO


### Backlinks

- TODO
