{
  "hash": "a2ae1ceff67064d505a8dac0cf7e432e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assumptions and Diagnostics\"\nlink-citations: TRUE\nparams: \n    SHOW_SOLS: TRUE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n:::lo\n\n### <i class=\"fa fa-graduation-cap\"></i> Learning Objectives\nAt the end of this lab, you will:\n\n1. Be able to state the assumptions underlying a linear model\n2. Specify the assumptions underlying a linear model with multiple predictors\n3. Assess if a fitted model satisfies the assumptions of your model\n4. Assess the effect of influential cases on linear model coefficients and overall model evaluations\n\n### <i class=\"fa fa-check-square-o fa-2\"></i> What You Need\n\n1. Be up to date with lectures\n2. Have completed [Week 2](https://uoepsy.github.io/dapr2/2425/labs/1_02_mlr.html) lab exercises\n\n### <i class=\"fab fa-r-project\"></i> Required R Packages\nRemember to load all packages within a code chunk at the start of your RMarkdown file using `library()`. If you do not have a package and need to install, do so within the console using `install.packages(\" \")`. For further guidance on installing/updating packages, see Section C [here](https://uoepsy.github.io/files/install-update-r#update-pkgs). \n\nFor this lab, you will need to load the following package(s):\n\n* **tidyverse** \n* **car**\n* **performance**\n* **kableExtra**\n* **sjPlot**\n\n### <i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i> Presenting Results\nAll results should be presented following [APA guidelines](https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf).If you need a reminder on how to hide code, format tables/plots, etc., make sure to review the [rmd bootcamp](https://uoepsy.github.io/scs/rmd-bootcamp/).\n\nThe example write-up sections included as part of the solutions are **not perfect** - they instead should give you a good example of what information you should include and how to structure this. Note that you must **not** copy any of the write-ups included below for future reports - if you do, you will be committing plagiarism, and this type of academic misconduct is taken very seriously by the University. You can find out more [here](https://www.ed.ac.uk/academic-services/students/conduct/academic-misconduct).\n\n### <i class=\"fa fa-file\"></i> Lab Data\nYou can download the data required for this lab [here](https://uoepsy.github.io/data/wellbeing_rural.csv) or read it in via this link https://uoepsy.github.io/data/wellbeing_rural.csv \n:::\n\n# Lab Overview\n\nIn the previous labs, we have fitted a number of regression models, including some with multiple predictors. In each case, we first specified the model, then visually explored the marginal distributions and associations among variables which would be used in the analysis. Finally, we fit the model, and began to examine the fit by studying what the various parameter estimates represented, and the spread of the residuals.\n\nBut before we draw inferences using our model estimates or use our model to make predictions, we need to be satisfied that our model meets a specific set of assumptions. If these assumptions are not satisfied, the results will not hold.\n\nIn this lab, we will check the assumptions of one of the multiple linear regression models that we have previously fitted in Block 1 using the 'mwdata' dataset (see [Week 2](https://uoepsy.github.io/dapr2/2425/labs/1_02_mlr.html)). \n\n# Study Overview {#sec-studyview}\n\n> **Research Question** \n>\n> Is there an association between wellbeing and time spent outdoors *after* taking into account the association between wellbeing and social interactions? \n\n\n\n<div class=\"optional-begin\"><span id='opt-start-1' class=\"fa-solid fa-circle-right optional-icon clickable\" onclick=\"toggle_visibility('opt-body-1', 'opt-start-1')\"> <span class=\"olab\">Wellbeing/Rurality data codebook.</span></span></div><div class=\"optional-body\" id = \"opt-body-1\" style=\"display: none;\">\n\n  \n\n__Description__\n\nFrom the Edinburgh & Lothians, 100 city/suburb residences and 100 rural residences were chosen at random and contacted to participate in the study. The Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), was used to measure mental health and well-being. \n\nParticipants filled out a questionnaire including items concerning: estimated average number of hours spent outdoors each week, estimated average number of social interactions each week (whether on-line or in-person), whether a daily routine is followed (yes/no). For those respondents who had an activity tracker app or smart watch, they were asked to provide their average weekly number of steps.  \n  \n  \n__Data Dictionary__\n\nThe data in `wellbeing_rural.csv` contain seven attributes collected from a random sample of $n=200$ hypothetical residents over Edinburgh & Lothians, and include: \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xpqxkbfqhg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xpqxkbfqhg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xpqxkbfqhg thead, #xpqxkbfqhg tbody, #xpqxkbfqhg tfoot, #xpqxkbfqhg tr, #xpqxkbfqhg td, #xpqxkbfqhg th {\n  border-style: none;\n}\n\n#xpqxkbfqhg p {\n  margin: 0;\n  padding: 0;\n}\n\n#xpqxkbfqhg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xpqxkbfqhg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xpqxkbfqhg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xpqxkbfqhg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xpqxkbfqhg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xpqxkbfqhg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xpqxkbfqhg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xpqxkbfqhg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xpqxkbfqhg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xpqxkbfqhg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xpqxkbfqhg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xpqxkbfqhg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xpqxkbfqhg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xpqxkbfqhg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xpqxkbfqhg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpqxkbfqhg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xpqxkbfqhg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xpqxkbfqhg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xpqxkbfqhg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpqxkbfqhg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xpqxkbfqhg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpqxkbfqhg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xpqxkbfqhg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpqxkbfqhg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xpqxkbfqhg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xpqxkbfqhg .gt_left {\n  text-align: left;\n}\n\n#xpqxkbfqhg .gt_center {\n  text-align: center;\n}\n\n#xpqxkbfqhg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xpqxkbfqhg .gt_font_normal {\n  font-weight: normal;\n}\n\n#xpqxkbfqhg .gt_font_bold {\n  font-weight: bold;\n}\n\n#xpqxkbfqhg .gt_font_italic {\n  font-style: italic;\n}\n\n#xpqxkbfqhg .gt_super {\n  font-size: 65%;\n}\n\n#xpqxkbfqhg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xpqxkbfqhg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xpqxkbfqhg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xpqxkbfqhg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xpqxkbfqhg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xpqxkbfqhg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xpqxkbfqhg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xpqxkbfqhg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xpqxkbfqhg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Age in years of respondent</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">outdoor_time</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Self report estimated number of hours per week spent outdoors </td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">social_int</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Self report estimated number of social interactions per week (both online and in-person)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">routine</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Binary 1=Yes/0=No response to the question 'Do you follow a daily routine throughout the week?'</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">wellbeing</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">location</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Location of primary residence (City, Suburb, Rural)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">steps_k</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Average weekly number of steps in thousands (as given by activity tracker if available)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n  \n  \n__Preview__\n\nThe first six rows of the data are:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jxqiwkyfqa\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jxqiwkyfqa table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jxqiwkyfqa thead, #jxqiwkyfqa tbody, #jxqiwkyfqa tfoot, #jxqiwkyfqa tr, #jxqiwkyfqa td, #jxqiwkyfqa th {\n  border-style: none;\n}\n\n#jxqiwkyfqa p {\n  margin: 0;\n  padding: 0;\n}\n\n#jxqiwkyfqa .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jxqiwkyfqa .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jxqiwkyfqa .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jxqiwkyfqa .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jxqiwkyfqa .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jxqiwkyfqa .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jxqiwkyfqa .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jxqiwkyfqa .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jxqiwkyfqa .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jxqiwkyfqa .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jxqiwkyfqa .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jxqiwkyfqa .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jxqiwkyfqa .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jxqiwkyfqa .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jxqiwkyfqa .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxqiwkyfqa .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jxqiwkyfqa .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jxqiwkyfqa .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jxqiwkyfqa .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxqiwkyfqa .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jxqiwkyfqa .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxqiwkyfqa .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jxqiwkyfqa .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxqiwkyfqa .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jxqiwkyfqa .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jxqiwkyfqa .gt_left {\n  text-align: left;\n}\n\n#jxqiwkyfqa .gt_center {\n  text-align: center;\n}\n\n#jxqiwkyfqa .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jxqiwkyfqa .gt_font_normal {\n  font-weight: normal;\n}\n\n#jxqiwkyfqa .gt_font_bold {\n  font-weight: bold;\n}\n\n#jxqiwkyfqa .gt_font_italic {\n  font-style: italic;\n}\n\n#jxqiwkyfqa .gt_super {\n  font-size: 65%;\n}\n\n#jxqiwkyfqa .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jxqiwkyfqa .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jxqiwkyfqa .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jxqiwkyfqa .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jxqiwkyfqa .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jxqiwkyfqa .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jxqiwkyfqa .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jxqiwkyfqa .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jxqiwkyfqa div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age\">age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"outdoor_time\">outdoor_time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"social_int\">social_int</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"routine\">routine</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wellbeing\">wellbeing</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"location\">location</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"steps_k\">steps_k</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">28</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">12</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">13</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">36</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">21.6</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">56</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">5</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">15</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">41</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">12.3</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">25</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">19</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">11</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">35</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">49.8</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">60</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">25</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">15</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">0</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">35</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">19</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">9</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">18</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">32</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">48.1</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">34</td>\n<td headers=\"outdoor_time\" class=\"gt_row gt_right\">18</td>\n<td headers=\"social_int\" class=\"gt_row gt_right\">13</td>\n<td headers=\"routine\" class=\"gt_row gt_right\">1</td>\n<td headers=\"wellbeing\" class=\"gt_row gt_right\">34</td>\n<td headers=\"location\" class=\"gt_row gt_left\">rural</td>\n<td headers=\"steps_k\" class=\"gt_row gt_right\">67.3</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n  \n\n\n</div><p class=\"optional-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Setup\n\n\n\n<div class='question-begin'>Setup</div><div class='question-body'>\n\n  \n\n1. Create a new RMarkdown file\n2. Load the required package(s)\n3. Read the wellbeing dataset into R, assigning it to an object named `mwdata`\n4. Fit the following model:\n\n$$\n\\text{Wellbeing} = \\beta_0 + \\beta_1 \\cdot \\text{Social Interactions} + \\beta_2 \\cdot \\text{Outdoor Time} + \\epsilon\n$$\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-2' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#Loading the required package(s)\nlibrary(tidyverse)\nlibrary(car)\nlibrary(performance)\nlibrary(kableExtra)\nlibrary(sjPlot)\n\n# Reading in data and storing to an object named 'mwdata'\nmwdata <- read_csv(\"https://uoepsy.github.io/data/wellbeing_rural.csv\")\n\n# wellbeing model\nwb_mdl1 <- lm(wellbeing ~ outdoor_time + social_int, data = mwdata) \n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Exercises\n\n## Assumptions\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\n\nLet's start by using `check_model()` for our `wb_mdl1` model - we can refer to these plots as a guide as we work through the assumptions questions of the lab.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nSee the [useful assumptions plots > check_model() flaschard](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions).\n\n:::\n\n:::{.callout-note appearance=\"simple\" collapse=\"true\"}\n\nThese plots **cannot** be used in your reports - they are to be used as a guide only.\n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-3' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(wb_mdl1)\n```\n\n::: {.cell-output-display}\n![](1_08_assump_diag_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nThe `check_model()` function is a useful way to check the assumptions of models, as it also returns some useful notes to aid your interpretation. There does appear to be evidence that some assumptions may have been violated, **but** to be sure we need to check each assumption individually with plots that are more suitable for a statistics report. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\n\nCheck if the fitted model satisfies the linearity assumption for `wb_mdl1`. \n\nWrite a sentence summarising whether or not you consider the assumption to have been met. Justify your answer with reference to the plots.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nHow you check this assumption depends on the number of predictors in your model:\n\n+ Single predictor: Use either residual vs fitted values plot (`plot(model, which = 1)`), and/or a scatterplot with loess lines  \n+ Multiple predictors: Use component-residual plots (also known as partial-residual plots) to check the assumption of linearity  \n\nFor more information, as well as tips to aid your interpretation, review the [linearity flashcard](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions).\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-4' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncrPlots(wb_mdl1)\n```\n\n::: {.cell-output-display}\n![](1_08_assump_diag_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nThe smoother (the pink line) follows quite closely to a linear relationship (the dashed blue line), though there was some deviation. Overall, the evidence suggested that the linearity assumption was met.\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\n\nCheck if the fitted model `wb_mdl1` satisfy the equal variance (homoscedasticity) assumption. \n\nWrite a sentence summarising whether or not you consider the assumption to have been met. Justify your answer with reference to the plot.\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nUse `residualPlots()` to plot residuals against the predictor. Since we are only interested in visually assessing our assumption checks, we can suppress the curvature test output by specifying `tests = FALSE`.\n\nFor more information, as well as tips to aid your interpretation, review the [equal variances (homoscedasticity) flashcard](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions).\n\n:::{.callout-hint collapse=\"true\"}\n\n**Quick Tip if plotting using `plot(model)`** \n\nAs the residuals can be positive or negative, we can make it easier to assess equal spread by improving the 'resolution' of the points.\n\nWe can make all residuals positive by discarding the sign (take the absolute value), and then take the square root to make them closer to each other.\n\nA plot of $\\sqrt{|\\text{Standardized residuals}|}$ against the fitted values can be obtained via `plot(model, which = 3)`.\n\n:::\n \n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-5' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\nWe can visually assess by plotting the Pearson residuals against the fitted values:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresidualPlots(wb_mdl1, tests = FALSE)\n```\n\n::: {.cell-output-display}\n![](1_08_assump_diag_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n\nOr by plotting the $\\sqrt{|\\text{Standardized residuals}|}$ against the fitted values:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(wb_mdl1, which = 3)\n```\n\n::: {.cell-output-display}\n![](1_08_assump_diag_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nPartial residual plots did show non-linear trends between residuals and predictors, hence there is evidence of non-constant variance i.e., heteroscedasticity. Thus, the data did not meet the assumption of equal variance, as the spread of the standardized residuals did not appear to be constant (for the most part) as the fitted values varied.\n\nIn the second plot, all points are above 0, but the majority of the points are not very close to each other. The line does not appear to be relatively flat, and so this also suggested that the error variance does change across the fitted values.\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br> \n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\n\nAssess whether there is autocorrelation in the error terms.\n  \nWrite a sentence summarising whether or not you consider the assumption of independence to have been met (you may have to assume certain aspects of the study design).  \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nReview the [independence (of errors) flashcard](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions).\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-6' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nSince our data were collected from a between-persons study design, we can assume (i.e., based on design, we believe) the errors to be independent.\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\n\nCheck if the fitted model `wb_mdl1` satisfies the normality assumption. \n  \nWrite a sentence summarising whether or not you consider the assumption to have been met. Justify your answer with reference to the plots. \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nFor more information, as well as tips to aid your interpretation, review the [normality (of errors) flashcard](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions).\n \n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-7' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\n\n:::{.panel-tabset}\n\n### Histogram\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = mwdata, aes(x = wb_mdl1$residuals)) +\n    geom_histogram() \n```\n\n::: {.cell-output-display}\n![](1_08_assump_diag_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nThe histogram indicated that the residuals (the differences between observed and predicted values) followed close to a normal distribution. \n\n:::\n\n### QQ Plot\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(wb_mdl1, which = 2)\n```\n\n::: {.cell-output-display}\n![](1_08_assump_diag_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nThe QQplot indicated that the residuals followed close to a normal distribution, as the points followed a linear pattern and there was no substantial skew or departure from normality. There was some evidence of heavier tails, and we may want to examine some observations more closely (i.e., 16, 78, 109).\n\n:::\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Multicollinearity \n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\n\nFor `wb_mdl1`, calculate the variance inflation factor (VIF) for the predictors in the model.  \n\nWrite a sentence summarising whether or not you consider multicollinearity to be a problem here.  \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nFor more information, as well as tips to aid your interpretation, review the [multicollinearity flashcard](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions).\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-8' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-8', 'sol-start-8')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-8\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvif(wb_mdl1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\noutdoor_time   social_int \n    1.001306     1.001306 \n```\n\n\n:::\n:::\n\n\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nThe VIF values for all predictors are <5, indicating that multicollinearity is not adversely affecting model estimates. \n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Diagnostics \n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\n\nCreate a new tibble which contains:  \n\n1. The original variables from the model (Hint, what does `wb_mdl1$model` give you?)\n2. The fitted values from the model $\\hat y$  \n3. The residuals $\\hat \\epsilon$\n4. The studentised residuals\n5. The hat values\n6. The Cook's Distance values\n\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nFor following will likely be useful to consider when creating your `tibble()`:\n\n1. Think about what `wb_mdl1$model` gives you\n2. `fitted()`\n3. `residuals()`\n4. `rstudent()`\n5. `hatvalues()`\n6. `cooks.distance()`\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-9' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-9', 'sol-start-9')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-9\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmdl_diagnost <- \n  tibble(\n  wb_mdl1$model,\n  fitted = fitted(wb_mdl1),\n  resid = residuals(wb_mdl1),\n  studres = rstudent(wb_mdl1),\n  hats = hatvalues(wb_mdl1),\n  cooksd = cooks.distance(wb_mdl1)\n)\n```\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\n\nFrom the tibble above, comment on the following:\n\n* Looking at the studentised residuals, are there any outliers? \n* Looking at the hat values, are there any observations with high leverage? \n* Looking at the Cook's Distance values, are there any highly influential points?  \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n\nAlongside the lecture materials, review the [individual case diagnostics flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions) and consider the commonly used cut-off criteria.\n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-10' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-10', 'sol-start-10')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-10\" style=\"display: none;\">\n\n\n\n::: {.panel-tabset}\n\n## Outliers\n\nIn a standard normal distribution, 95% of the values are roughly between -2 and 2. Because of this, studentised residuals of $>2$ or $< -2$ indicate potential outlyingness. \n\nWe can ask `R` how many of the *absolute* values (by specifying `abs()`) are $>2$:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(abs(mdl_diagnost$studres) > 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n  189    11 \n```\n\n\n:::\n:::\n\n\n\n\nWe have 11 `TRUE` observations, which tells us that they have |studentised residuals| $>2$. \n\nWe can identify which of our observations have these values:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwhich(abs(mdl_diagnost$studres) > 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 16  50  53  58  62  76  78 109 126 151 163 \n 16  50  53  58  62  76  78 109 126 151 163 \n```\n\n\n:::\n:::\n\n\n\n\nSo we know that observations (or rows) 16, 50, 53, 58, 62, 76, 78, 109, 126, 151, and 163 have absolute values that have studentised residuals of $>2$ or $< -2$.\n\nWe could also *filter* our newly created tibble to these observations to examine the values further:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmwdata %>%\n    mutate(\n    studres = rstudent(wb_mdl1)) %>%\n  dplyr::filter(., studres > 2 | studres < -2) %>%\n  arrange(., desc(studres)) %>%\n  kable(.)  %>%   \n    kable_styling(., full_width = F)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> age </th>\n   <th style=\"text-align:right;\"> outdoor_time </th>\n   <th style=\"text-align:right;\"> social_int </th>\n   <th style=\"text-align:right;\"> routine </th>\n   <th style=\"text-align:right;\"> wellbeing </th>\n   <th style=\"text-align:left;\"> location </th>\n   <th style=\"text-align:right;\"> steps_k </th>\n   <th style=\"text-align:right;\"> studres </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 23 </td>\n   <td style=\"text-align:right;\"> 26 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 59 </td>\n   <td style=\"text-align:left;\"> city </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> 3.904186 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 34 </td>\n   <td style=\"text-align:right;\"> 29 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 50 </td>\n   <td style=\"text-align:left;\"> suburb </td>\n   <td style=\"text-align:right;\"> 61.1 </td>\n   <td style=\"text-align:right;\"> 2.402389 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 39 </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 49 </td>\n   <td style=\"text-align:left;\"> suburb </td>\n   <td style=\"text-align:right;\"> 65.6 </td>\n   <td style=\"text-align:right;\"> 2.234367 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 47 </td>\n   <td style=\"text-align:left;\"> city </td>\n   <td style=\"text-align:right;\"> 80.1 </td>\n   <td style=\"text-align:right;\"> 2.060351 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 58 </td>\n   <td style=\"text-align:right;\"> 31 </td>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 46.6 </td>\n   <td style=\"text-align:right;\"> -2.047644 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 34.8 </td>\n   <td style=\"text-align:right;\"> -2.167219 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 44 </td>\n   <td style=\"text-align:right;\"> 25 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 26 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 66.6 </td>\n   <td style=\"text-align:right;\"> -2.261542 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 47 </td>\n   <td style=\"text-align:right;\"> 24 </td>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 27 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 53.5 </td>\n   <td style=\"text-align:right;\"> -2.292089 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 35 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 26 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 66.1 </td>\n   <td style=\"text-align:right;\"> -2.433253 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 23 </td>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 26 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 60.0 </td>\n   <td style=\"text-align:right;\"> -2.602129 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 36 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 51.6 </td>\n   <td style=\"text-align:right;\"> -3.199777 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nThere were 11 observations identified as potential outliers.\n\n:::\n\n## High Leverage\n\nHat values of more than $2 \\bar{h}$ (2 times the average hat value) are considered high leverage. The average hat value, $\\bar{h}$ is calculated as $\\frac{k + 1}{n}$, where $k$ is the number of predictors, and $n$ is the sample size.\n\nFor our model:\n$$\n\\bar h = \\frac{k+1}{n} = \\frac{2+1}{200} = \\frac{3}{200} = 0.015\n$$\nWe can ask whether any of observations have hat values which are greater than $2 \\bar h$:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(mdl_diagnost$hats > (2*0.015))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n  184    16 \n```\n\n\n:::\n:::\n\n\n\n\nWe have 16 `TRUE` observations, which tells us that they have high leverage.\n\nWe can identify which of our observations have these values:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwhich(mdl_diagnost$hats > (2*0.015))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 25  56  59  60  72  73  75  79 127 131 149 159 165 169 176 197 \n 25  56  59  60  72  73  75  79 127 131 149 159 165 169 176 197 \n```\n\n\n:::\n:::\n\n\n\n\nSo we know that observations (or rows) 25, 56, 59, 60, 72, 73, 75, 79, 127, 131, 149, 159, 165, 169, 176, and 197 have hat values which are greater than $2 \\bar h$.\n\nWe could also *filter* our newly created tibble to these observations to examine the values further:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmwdata %>%\n    mutate(\n    hats = hatvalues(wb_mdl1)) %>%\n  dplyr::filter(., hats > (2*0.015)) %>%\n  arrange(., desc(hats)) %>%\n  kable(.)  %>%   \n    kable_styling(., full_width = F)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> age </th>\n   <th style=\"text-align:right;\"> outdoor_time </th>\n   <th style=\"text-align:right;\"> social_int </th>\n   <th style=\"text-align:right;\"> routine </th>\n   <th style=\"text-align:right;\"> wellbeing </th>\n   <th style=\"text-align:left;\"> location </th>\n   <th style=\"text-align:right;\"> steps_k </th>\n   <th style=\"text-align:right;\"> hats </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:right;\"> 24 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 35 </td>\n   <td style=\"text-align:left;\"> suburb </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> 0.0564084 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 62 </td>\n   <td style=\"text-align:right;\"> 31 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 37 </td>\n   <td style=\"text-align:left;\"> city </td>\n   <td style=\"text-align:right;\"> 49.2 </td>\n   <td style=\"text-align:right;\"> 0.0452765 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 69 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 39 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 5.9 </td>\n   <td style=\"text-align:right;\"> 0.0448793 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 39 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 40.0 </td>\n   <td style=\"text-align:right;\"> 0.0411712 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 41 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 24.3 </td>\n   <td style=\"text-align:right;\"> 0.0356713 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 27 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 38 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> 0.0352975 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 53 </td>\n   <td style=\"text-align:right;\"> 35 </td>\n   <td style=\"text-align:right;\"> 14 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 35 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 24.4 </td>\n   <td style=\"text-align:right;\"> 0.0345566 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:left;\"> suburb </td>\n   <td style=\"text-align:right;\"> 3.3 </td>\n   <td style=\"text-align:right;\"> 0.0341635 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:left;\"> city </td>\n   <td style=\"text-align:right;\"> 71.6 </td>\n   <td style=\"text-align:right;\"> 0.0336901 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 36 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 29.7 </td>\n   <td style=\"text-align:right;\"> 0.0328599 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 44 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 35 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 15.1 </td>\n   <td style=\"text-align:right;\"> 0.0313589 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 69 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 31 </td>\n   <td style=\"text-align:left;\"> suburb </td>\n   <td style=\"text-align:right;\"> 15.6 </td>\n   <td style=\"text-align:right;\"> 0.0312095 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 23 </td>\n   <td style=\"text-align:right;\"> 29 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 36 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> 0.0310672 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 56 </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 41 </td>\n   <td style=\"text-align:left;\"> city </td>\n   <td style=\"text-align:right;\"> 58.6 </td>\n   <td style=\"text-align:right;\"> 0.0309399 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 35 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:left;\"> city </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> 0.0305338 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:right;\"> 34 </td>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 48 </td>\n   <td style=\"text-align:left;\"> suburb </td>\n   <td style=\"text-align:right;\"> 35.1 </td>\n   <td style=\"text-align:right;\"> 0.0301977 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nThere were 16 observations that had high leverage (> $2 \\bar h$).  \n\n:::\n\n## Influential Points\n\nWe are using a Cook's Distance cut-off of $\\frac{4}{n-k-1}$, where $k$ is the number of predictors, and $n$ is the sample size.  \n\nFor our model:\n$$\nD_{cutoff} = \\frac{4}{n-k-1} = \\frac{4}{200 - 2 - 1} = \\frac{4}{197} = 0.020\n$$\n\nWe can ask whether any of observations have a high influence on our model estimates:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(mdl_diagnost$cooksd > 0.020)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n  189    11 \n```\n\n\n:::\n:::\n\n\n\n\nYes, we have 11 `TRUE` observations, which tells us that they are above the $D_{cutoff} = 0.020$.\n\nWe can identify which of our observations have these values:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwhich(mdl_diagnost$cooksd > 0.020)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 16  53  58  76  78 109 125 126 149 151 169 \n 16  53  58  76  78 109 125 126 149 151 169 \n```\n\n\n:::\n:::\n\n\n\n\nSo we know that observations (or rows) 16, 53, 58, 76, 78, 109, 125, 126, 149, 151, and 169 have $D > 0.020$. \n\nWe could also *filter* our newly created tibble to these observations to examine the values further:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmwdata %>%\n    mutate(\n    cooksd = cooks.distance(wb_mdl1)) %>%\n  dplyr::filter(., cooksd > 4/(200-2-1)) %>%\n  arrange(., desc(cooksd)) %>%\n  kable(.)  %>%   \n    kable_styling(., full_width = F)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> age </th>\n   <th style=\"text-align:right;\"> outdoor_time </th>\n   <th style=\"text-align:right;\"> social_int </th>\n   <th style=\"text-align:right;\"> routine </th>\n   <th style=\"text-align:right;\"> wellbeing </th>\n   <th style=\"text-align:left;\"> location </th>\n   <th style=\"text-align:right;\"> steps_k </th>\n   <th style=\"text-align:right;\"> cooksd </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 23 </td>\n   <td style=\"text-align:right;\"> 26 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 59 </td>\n   <td style=\"text-align:left;\"> city </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> 0.1295568 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 58 </td>\n   <td style=\"text-align:right;\"> 31 </td>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 46.6 </td>\n   <td style=\"text-align:right;\"> 0.0376693 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 23 </td>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 26 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 60.0 </td>\n   <td style=\"text-align:right;\"> 0.0336478 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 36 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 51.6 </td>\n   <td style=\"text-align:right;\"> 0.0326114 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 34 </td>\n   <td style=\"text-align:right;\"> 29 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 50 </td>\n   <td style=\"text-align:left;\"> suburb </td>\n   <td style=\"text-align:right;\"> 61.1 </td>\n   <td style=\"text-align:right;\"> 0.0319559 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 35 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:left;\"> city </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> 0.0318858 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 34.8 </td>\n   <td style=\"text-align:right;\"> 0.0314694 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:right;\"> 34 </td>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 48 </td>\n   <td style=\"text-align:left;\"> suburb </td>\n   <td style=\"text-align:right;\"> 35.1 </td>\n   <td style=\"text-align:right;\"> 0.0284437 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 35 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 26 </td>\n   <td style=\"text-align:left;\"> rural </td>\n   <td style=\"text-align:right;\"> 66.1 </td>\n   <td style=\"text-align:right;\"> 0.0247096 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 39 </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 49 </td>\n   <td style=\"text-align:left;\"> suburb </td>\n   <td style=\"text-align:right;\"> 65.6 </td>\n   <td style=\"text-align:right;\"> 0.0243298 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n\nYou can also display the Cook's Distance values themselves using `plot(model, which = 4)`, and add a horizontal line at the $D_{cutoff} = 0.020$ using `abline(h = ???)`:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(wb_mdl1, which = 4, abline(h=0.020, col=\"blue\"))\n```\n\n::: {.cell-output-display}\n![](1_08_assump_diag_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n::: {.callout-important icon=false appearance=\"minimal\"}\n\nThere were 11 observations that had a high influence on our model estimates.\n\n:::\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\n\nUse the function `influence.measures()` to extract these delete-1 measures^[leave-one-out deletion diagnostics] of influence.  \n\nChoose a couple of these measures to focus on, exploring in more detail (you may want to examine values or even try plotting distributions). \n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Hint\n \nReview the [individual case diagnostics flashcards](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions).  \n\nThe function `influence.measures()` returns an `infl`-type object. To plot this, we need to find a way to extract the actual numbers from it.  \n\nWhat do you think `names(influence.measures(wb_mdl1))` shows you? How can we use `influence.measures(wb_mdl1)$<insert name here>` to extract the matrix of numbers?  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-11' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-11', 'sol-start-11')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-11\" style=\"display: none;\">\n\n\n\n::: {.panel-tabset}\n\n## Extracting `influence.measures()`\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#extract measures\ninf_mes <- influence.measures(wb_mdl1)\n\n#examine top ten rows, and round to 3 decimal places\nround(inf_mes$infmat[1:10,], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   dfb.1_ dfb.otd_ dfb.scl_  dffit cov.r cook.d   hat\n1   0.006   -0.008    0.002  0.012 1.024  0.000 0.009\n2   0.083   -0.168    0.061  0.203 1.016  0.014 0.025\n3  -0.006   -0.001    0.004 -0.016 1.020  0.000 0.005\n4   0.047   -0.050   -0.039 -0.081 1.020  0.002 0.012\n5   0.001    0.080   -0.091 -0.138 1.028  0.006 0.024\n6  -0.003    0.001   -0.008 -0.037 1.017  0.000 0.005\n7  -0.008   -0.001    0.015  0.018 1.036  0.000 0.020\n8   0.106   -0.119   -0.006  0.166 0.985  0.009 0.010\n9  -0.003    0.004   -0.001 -0.007 1.025  0.000 0.009\n10  0.002   -0.008    0.008  0.015 1.026  0.000 0.010\n```\n\n\n:::\n:::\n\n\n\n\n\n## Examine `DFBETA` values\n\nDFbeta represents the difference in the beta coefficients when a case is excluded from the model versus when it's included. A large DFbeta value would suggest that a case has a substantial impact on the estimated coefficients, and thus a high influence on the model results; a small DFbeta value would suggest that the case has less influence on the estimated coefficients.\n\nA commonly used cut-off or threshold to compare $|DFBETA|$ values (absolute values) against is $\\frac{2}{\\sqrt{n}}$ (see Belsley et al., (1980) p. 28 for more info)^[Belsley, D. A., Kuh, E., & Welsch, R. E. (2005). Regression diagnostics: Identifying influential data and sources of collinearity. John Wiley & Sons. DOI: 10.1002/0471725153]. \n\nFor our model:\n\n$$\n|DFBETA_{cutoff}| \\quad = \\quad \\frac{2}{\\sqrt{n}} \\quad = \\quad  \\frac{2}{\\sqrt{200}}  = 0.141\n$$\n\nIn order to extract these in order to arrange in descending order, we need to save our delete-1 measures of influence as a dataframe (via `as.data.frame()`). Then we can then arrange our DFBETA values in descending order (via `arrange(desc(???))`). To avoid returning 200 rows of output (i.e., the length of the dataframe), we can ask for the first 15 rows via (`head(., 15)`):\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#save as a dataframe\ninf_mes1 <- as.data.frame(inf_mes$infmat)\n\n#arrange dfbeta values in descending order using the absolute value, and show first 10 rows\ninf_mes1 %>%\n    arrange(desc(abs(dfb.1_))) %>%\n    head(., 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        dfb.1_    dfb.otd_    dfb.scl_      dffit     cov.r      cook.d\n109 -0.4918246  0.32363373  0.49483157  0.6455776 0.8332377 0.129556799\n53   0.2430892 -0.26944443 -0.15351312 -0.3388798 0.9790122 0.037669317\n16   0.2060412 -0.13252138 -0.23259175 -0.3223359 0.9310954 0.033647762\n101 -0.1947109  0.09412063  0.15487642 -0.2046876 1.0063119 0.013897196\n179  0.1902832 -0.07096434 -0.16598552  0.2085435 0.9990240 0.014401828\n76   0.1730591 -0.02595756 -0.26823452 -0.3101290 0.9651183 0.031469445\n85  -0.1646134  0.10294561  0.11084731 -0.1711913 1.0143158 0.009748336\n149 -0.1638458  0.26658339  0.03742045  0.2934205 1.0039126 0.028443695\n56   0.1604565 -0.19478940 -0.02813891  0.2114811 1.0330872 0.014891276\n173 -0.1561237  0.10614219  0.15969174  0.2161367 1.0033339 0.015479111\n75   0.1457701 -0.07234892 -0.11988282  0.1497178 1.0393526 0.007484738\n50   0.1353661 -0.13659118 -0.12403587 -0.2437762 0.9485325 0.019390273\n26   0.1300856 -0.08559983 -0.13088097 -0.1707527 1.0263050 0.009715555\n58   0.1291280 -0.02591707 -0.21369424 -0.2756455 0.9405759 0.024709605\n78   0.1272542 -0.03198691 -0.22393152 -0.3200349 0.8802619 0.032611416\n            hat\n109 0.026614646\n53  0.026659223\n16  0.015112834\n101 0.020817727\n179 0.018565852\n76  0.020066684\n85  0.020304231\n149 0.030197659\n56  0.035297538\n173 0.020995260\n75  0.032859874\n50  0.011184976\n26  0.026614646\n58  0.012670376\n78  0.009904492\n```\n\n\n:::\n:::\n\n\n\n\nWe can see that we have 11 $|DFBETA|$ values > $\\frac{2}{\\sqrt{200}}$, from observations (or rows) 16, 53, 56, 75, 76, 85, 101, 109, 149, 173, and 179 that we may want to examine further:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwhich(abs(inf_mes1$dfb.1_) > (2/sqrt(200)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  16  53  56  75  76  85 101 109 149 173 179\n```\n\n\n:::\n:::\n\n\n\n\n## Plotting COVRATIO statistics\n\nValues which are $>1+\\frac{3(k+1)}{n}$ or $<1-\\frac{3(k+1)}{n}$ are considered as having strong influence.  \n\nFor our model, this is:\n$$\n1 \\pm \\frac{3(k+1)}{n} \\quad = \\quad 1 \\pm\\frac{3(2+1)}{200} \\quad = \\quad 1\\pm \\frac{9}{200} \\quad = \\quad 1\\pm0.045\n$$\n\nThe \"infmat\" bit of an `infl`-type object contains the numbers, as we can see from out output above. To use it with `ggplot()`, we will need to turn it into a dataframe (`as.data.frame()`), or a tibble (`as_tibble()`):   \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninfdata <- inf_mes$infmat %>%\n  as_tibble()\n```\n:::\n\n\n\n\nNow we can build our plot. It would be useful to add vertical lines at the values $\\quad 1\\pm0.045$. To do so, we can use the `geom_vline()` function: \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = infdata, aes(x = cov.r)) + \n  geom_histogram() +\n  geom_vline(aes(xintercept = c(1-0.045), col = \"blue\")) +\n  geom_vline(aes(xintercept = c(1+0.045), col = \"red\")) + \n  theme(legend.position = \"none\")  #remove legend\n```\n\n::: {.cell-output-display}\n![](1_08_assump_diag_files/figure-html/unnamed-chunk-26-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nIt looks like a few observations may be having quite a strong influence on the standard errors here. We can check specifically how many observations are potentially having a having strong influence using the cut off $1\\pm0.045$:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(infdata$cov.r < 1 - 0.045 | infdata$cov.r > 1 + 0.045)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n  185    15 \n```\n\n\n:::\n:::\n\n\n\n\nWe can identify these 15 observations to investigate further:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwhich(infdata$cov.r < 1 - 0.045 | infdata$cov.r > 1 + 0.045)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  16  25  50  58  62  72  73  78  79 109 127 151 159 165 176\n```\n\n\n:::\n:::\n\n\n\n\nWe know that observations (or rows) 16, 25, 50, 58, 62, 72, 73, 78, 79, 109, 127, 151, 159, 165, and 176 have $\\text{COVRATIO  }  1\\pm0.045$. \n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\n\nWhat approaches would be appropriate to take given the issues highlighted above with the violations of assumptions and case diagnostic results?\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-12' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-12', 'sol-start-12')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-12\" style=\"display: none;\">\n\n\n\nThere are lots of different options available to us. We may want to consider one of the approaches described in the [next steps: what to do with violations of assumptions / problematic case diagnostic results flashcard](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions). \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Compile Report\n\n\n\n<div class='question-begin'>Compile Report</div><div class='question-body'>\n\n  \n\nKnit your report to PDF, and check over your work. To do so, you should make sure:\n\n- Only the output you want your reader to see is visible (e.g., do you want to hide your code?)\n- Check that the **tinytex** package is installed\n- Ensure that the ‘yaml’ (bit at the very top of your document) looks something like this:\n\n```{}\n---\ntitle: \"this is my report title\"\nauthor: \"B1234506\"\ndate: \"07/09/2024\"\noutput: bookdown::pdf_document2\n---\n```\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n# What to do if you cannot knit to PDF\nIf you are having issues knitting directly to PDF, try the following:  \n\n- Knit to HTML file  \n- Open your HTML in a web-browser (e.g. Chrome, Firefox)  \n- Print to PDF (Ctrl+P, then choose to save to PDF)  \n- Open file to check formatting\n:::\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n# Hiding Code and/or Output\n\n:::{.panel-tabset}\n## Hiding R Code\n\nTo not show the code of an R code chunk, and only show the output, write:\n\n````\n```{{r, echo=FALSE}}\n# code goes here\n```\n````\n\n## Hiding R Output\n\nTo show the code of an R code chunk, but hide the output, write:\n\n````\n```{{r, results='hide'}}\n# code goes here\n```\n````\n\n## Hiding R Code and Output\n\nTo hide both code and output of an R code chunk, write:\n\n````\n```{{r, include=FALSE}}\n# code goes here\n```\n````\n:::\n\n:::\n\n:::{.callout-tip appearance=\"simple\" collapse=\"true\"}\n\n### Tinytex\nYou must make sure you have **tinytex** installed in R so that you can “Knit” your Rmd document to a PDF file:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninstall.packages(\"tinytex\")\ntinytex::install_tinytex()\n```\n:::\n\n\n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><span id='sol-start-13' class=\"fa-solid fa-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-13', 'sol-start-13')\">  Solution </span></div><div class=\"solution-body\" id = \"sol-body-13\" style=\"display: none;\">\n\n\n\nYou should end up with a PDF file. If you have followed the above instructions and still have issues with knitting, speak with a Tutor. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n",
    "supporting": [
      "1_08_assump_diag_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}