project:
  type: website
  render: 
    - "*.qmd"
    - "!working/*"
  output-dir: ./wipdocs/

website:  
  title: "DAPR2 Flashcards"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - index.qmd
      - section: "Block 1: Intro to LM"
        contents:
          - csstests.qmd
              
      - section: "Block 2: Extending LM"
        contents:
          - block2/assump.qmd
              
      - section: "Block 3: Interactions"
        contents:
          - csstests.qmd
          
      - section: "Block 4: Logistic regression"
        contents:
          - csstests.qmd
          
      - section: "More resources"
        contents:
          - resources/workflow.qmd

format:
  html:
    toc: true
    toc_float: true
    link-citations: true
    theme: 
      - cosmo
      - assets/style-readings.scss
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


