project:
  type: website
  render: 
    - "*.qmd"
    - "!working/*"
  output-dir: ./wipdocs/

website:  
  title: "DAPR2 Flashcards"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - index.qmd
      - section: "Block 1: Intro to LM"
        contents:
          - block1/terminology.qmd
          - block1/functions.qmd
          - block1/deterministic-probabilistic.qmd
          - block1/marginal-vs-bivariate.qmd
          - block1/exploration-numeric.qmd
          - block1/exploration-visual.qmd
          - block1/hypotheses.qmd
          - block1/simple-regression.qmd
          - block1/multiple-regression.qmd
          - block1/extract-from-model.qmd
          - block1/model-fitted-values.qmd
          - block1/transformation.qmd
          - block1/lm-fit.qmd
          - block1/lm-comparisons.qmd
              
      - section: "Block 2: Extending LM"
        contents:
          - block2/contrast-coding.qmd
          - block2/treatment-coding.qmd
          - block2/sum-coding.qmd
          - block2/assump.qmd
          - block2/multicollinearity.qmd
          - block2/influence.qmd
          - block2/sensitivity-analysis.qmd
          - block2/bootstrapping.qmd
              
      - section: "Block 3: Interactions"
        contents:
          - block3/overview-ixn.qmd
          - block3/num-cat.qmd
          - block3/num-num.qmd
          - block3/cat-cat.qmd
          - block3/multiple-comparisons.qmd
          
      - section: "Block 4: Logistic regression"
        contents:
          - block4/binary-outcomes.qmd
          - block4/link-function.qmd
          - block4/probs-logodds.qmd
          - block4/logreg-example.qmd
          - block4/lm-vs-glm.qmd
          - block4/logreg-fit-comparison.qmd
          - block4/logreg-assumptions.qmd
          - block4/logreg-influence.qmd
          
      - section: "More resources"
        contents:
          - resources/workflow.qmd
          - resources/reporting-lm.qmd
          - resources/formatting.qmd

format:
  html:
    toc: true
    toc_float: true
    link-citations: true
    theme: 
      - cosmo
      - assets/style-readings.scss
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


