{
  "hash": "c87387ab9fa418fb544784bbbf24822c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Categorical predictors and dummy coding\"\nauthor: \"Elizabeth Pankratz (elizabeth.pankratz@ed.ac.uk)\"\neditor_options: \n  chunk_output_type: console\nformat:\n  revealjs:\n    smaller: true\n---\n\n\n\n\n\n\n\n\n\n# Course Overview {.smaller}\n\n<br>\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n<table style=\"border: 1px solid black;>\n  <tr style=\"padding: 0 1em 0 1em;\">\n    <td rowspan=\"5\" style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1;text-align:center;vertical-align: middle\">\n        <b>Introduction to Linear Models</b></td>\n    <td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        Intro to Linear Regression</td>\n  </tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        Interpreting Linear Models</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        Testing Individual Predictors</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        Model Testing & Comparison</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        Linear Model Analysis</td></tr>\n\n  <tr style=\"padding: 0 1em 0 1em;\">\n    <td rowspan=\"5\" style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1;text-align:center;vertical-align: middle\">\n        <b>Analysing Experimental Studies</b></td>\n    <td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:1\">\n        <b>Categorical Predictors & Dummy Coding</b></td>\n  </tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        \tEffects Coding & Coding Specific Contrasts</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Assumptions & Diagnostics</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Bootstrapping</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        \tCategorical Predictor Analysis</td></tr>\n</table>\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n<table style=\"border: 1px solid black;>\n  <tr style=\"padding: 0 1em 0 1em;\">\n    <td rowspan=\"5\" style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4;text-align:center;vertical-align: middle\">\n        <b>Interactions</b></td>\n    <td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Interactions I</td>\n  </tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Interactions II</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Interactions III</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Analysing Experiments</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Interaction Analysis</td></tr>\n\n  <tr style=\"padding: 0 1em 0 1em;\">\n    <td rowspan=\"5\" style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4;text-align:center;vertical-align: middle\">\n        <b>Advanced Topics</b></td>\n    <td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Power Analysis</td>\n  </tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Binary Logistic Regression I</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Binary Logistic Regression II</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        Logistic Regression Analysis</td></tr>\n  <tr><td style=\"border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4\">\n        \tExam Prep and Course Q&A</td></tr>\n</table>\n\n\n:::\n\n::::\n\n## This week's learning objectives\n\n<br>\n\n::: {.fragment}\n::: {.dapr2callout}\nHow can we include categorical variables as predictors in a linear model?\n:::\n:::\n\n::: {.fragment}\n::: {.dapr2callout}\nWhen we use a categorical predictor, how do we interpret the linear model’s coefficients?\n:::\n:::\n\n::: {.fragment}\n::: {.dapr2callout}\nWhat hypotheses are tested by the default way that R represents categorical predictors?\n:::\n:::\n\n::: {.fragment}\n::: {.dapr2callout}\nIf we wanted to test different hypotheses after fitting the model, how would we do that?\n:::\n:::\n\n\n\n\n<!-- ======================================== -->\n\n# Categorical predictors with two levels <br>(\"binary\" predictors)\n\n## Examples of binary predictors  {.smaller}\n\n![](figs/TODO-binary.jpeg){fig-align=\"center\"}\n\n<!-- TODO: use study data as example -->\n\nBut: linear models can only deal with input in number form.\n\nSo we need some way of representing these variables numerically.\n\nToday: **dummy coding**, aka **treatment coding**.\n\n\n## How does dummy/treatment coding represent categories as numbers?\n\nRepresent one level as 0, and the other level as 1.\n\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Schematic:**\n\n![](figs/TODO-trtmt.jpeg){fig-align=\"center\"}\nHere, `alone` is coded as 0, `others` is coded as 1.\n\n<!-- TODO: use study data as example -->\n\n:::\n::: {.column width=\"50%\"}\n**In the data:**\n\n:::{ style=\"font-size: 80%;\" }\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscore_data |>\n  select(ID, study, study_num) |>\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      ID  study study_num\n1  ID101 others         1\n2  ID102  alone         0\n3  ID103  alone         0\n4  ID104 others         1\n5  ID105  alone         0\n6  ID106 others         1\n7  ID107  alone         0\n8  ID108  alone         0\n9  ID109 others         1\n10 ID110  alone         0\n```\n\n\n:::\n:::\n\n\n:::\n\n:::\n::::\n\n\n## Does it matter which level is coded as 0 and which level is coded as 1?\n\n:::{.hcenter}\nYes.\n\n:::\n\n:::{style=\"font-size: 70%;\"}\n\nTo illustrate: Here are some test scores from students who studied either `alone` (blue) or with `others` (pink).\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/plot violin-1.svg){fig-align='center'}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/plot xy 1-1.svg){fig-align='center'}\n:::\n:::\n\n\n\n:::\n::::\n\n\n\n## Does it matter which level is coded as 0 and which level is coded as 1? {.smaller}\n\n<!-- TODO: dont' just use fragments, fully duplicate slides, so that there's a version of the PEOE slide that doesn't overlay the solution on the main slide -->\n\n:::{.hcenter}\nYes.\n\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.r-stack}\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/plot xy 2-1.svg)\n:::\n:::\n\n\n::: {.fragment}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/plot xy with line-1.svg)\n:::\n:::\n\n:::\n\n:::\n\n\nA linear model will fit a line to this data.\n\nBefore I show you this line, I want you to make predictions about it.\n\n<!-- (You'll learn better long-term if you genuinely guess and avoid peeking ahead in the slides.) -->\n\n\n\n:::\n::: {.column width=\"50%\" style=\"font-size: 70%;\"}\n**Activity! Individual {{< iconify material-symbols person-rounded size=1.5em >}} and in pairs/threes {{< iconify material-symbols group-outline-rounded size=1.5em >}} :**\n\n- **{{< iconify material-symbols person-rounded size=1.5em >}} Predict**: Write down your guesses: \n\n  1. The line's intercept will be the same as the mean of either **alone** or **others**. Which one? Why?\n  2. Will the slope of the line be **positive** or **negative**? Why?\n\n\n- **{{< iconify material-symbols group-outline-rounded size=1.5em >}} Explain**: \nWhy do you think your guesses are likely to be correct?\n\n\n- **{{< iconify material-symbols person-rounded size=1.5em >}} Observe**: Did your guesses match the results?\n\n\n- **{{< iconify material-symbols group-outline-rounded size=1.5em >}} Explain**: Why are the results the way they are?\n\n:::\n::::\n\n<!-- at Observe, show line, annotate it with Intercept and Slope. ask someone to articulate it in plenum (wait til several hands raised). -->\n\n## How do we describe this line?\n\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n:::{.r-stack}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/plot xy pre betas-1.svg)\n:::\n:::\n\n\n:::{.fragment}\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/plot xy with betas-1.svg)\n:::\n:::\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"  style=\"font-size: 70%;\"}\nUsing our mathematical toolkit:\n\n$$\nscore_i = \\beta_0 + (\\beta_1 \\times study) + \\epsilon_i\n$$\n\n<br>\n\n**$\\beta_0$:** intercept, mean of `alone` (the level coded as 0):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_alone\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22.8\n```\n\n\n:::\n:::\n\n\n<br>\n\n**$\\beta_1$:** slope, the difference between mean of `others` (coded as 1) and mean of `alone` (coded as 0):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_others - mean_alone\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.73\n```\n\n\n:::\n:::\n\n\n<br>\n\n**$\\epsilon_i$:** error for each individual data point $i$\n\n:::\n::::\n\n<br>\n\n::: {.hcenter}\n**Questions!**\n:::\n\n\n---\n\n<br>\n\nWe can find these parameters values all on our own, without a linear model.\n\nBut we need a linear model to answer research questions like:\n\n**Do students who study with others score significantly better than students who study alone?**\n\n<br>\n\nNext, we'll fit a model that predicts score as a function of study patterns: `score ~ study`.\n\n<!-- my instinct is to want students to do some predictions here, see what param estimates would be consistent with each outcome. but I think they don't know yet what hyps are being tested by each param. so it might be premature. we can do it later.-->\n\n\n\n## Modelling `score ~ study` {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(score ~ study, data = score_data)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = score ~ study, data = score_data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-22.79  -4.79   0.21   5.48  18.21 \n\nCoefficients:\n            Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)    22.79       0.66   34.51   < 2e-16 ***\nstudyothers     4.73       1.01    4.69 0.0000045 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.9 on 248 degrees of freedom\nMultiple R-squared:  0.0815,\tAdjusted R-squared:  0.0777 \nF-statistic:   22 on 1 and 248 DF,  p-value: 0.00000453\n```\n\n\n:::\n:::\n\n\n<br>\n\n**Those coefficient estimates look familiar...**\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_alone\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22.8\n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_others - mean_alone\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.73\n```\n\n\n:::\n:::\n\n\n:::\n::::\n\n\n\n\n## Model evaluation works the same as before\n\n<br>\n\n**$R^2$:**\n\n- Still tells us how much variance in the data is accounted for by the model.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nMultiple R-squared:  0.0815,\tAdjusted R-squared:  0.0777 \n```\n\n\n:::\n:::\n\n\n<br>\n\n**$F$-ratio (aka $F$-statistic):**\n\n- Still tells us the ratio of explained variance to unexplained variance.\n- Still tests the hypothesis that all regression slopes in the model = 0.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nF-statistic:   22 on 1 and 248 DF,  p-value: 0.00000453\n```\n\n\n:::\n:::\n\n\n<br>\n\n(Revisit Lecture 4 for a refresher!)\n\n\n## What hypotheses are being tested for each coefficient? {.smaller}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)    22.79       0.66   34.51 1.12e-96\nstudyothers     4.73       1.01    4.69 4.53e-06\n```\n\n\n:::\n:::\n\n\n<br> \n\n**`(Intercept)` aka $\\beta_0$:**\n\n- Null hypothesis (aka H0): the intercept is equal to zero (aka $\\beta_0 = 0$).\n- $p$-value (aka `Pr(>|t|)`): the probability of observing an intercept of 22.79, assuming that the true value of the intercept is zero.\n\n\n**`studyothers` aka $\\beta_1$:**\n\n- Null hypothesis (aka H0): the difference between levels is equal to zero (aka $\\beta_1 = 0$).\n- $p$-value: the probability of observing a difference of 4.73, assuming that the true value of the difference is zero.\n\n<br>\n\nOur research question was about how studying alone or with others is associated with test score.\n\n**Are both of these hypothesis tests relevant to our research question?**\n\n<!-- if time, could do a three-minute TPS here -->\n\n\n\n## Reporting the model's estimates\n\n> Study habits significantly predicted student test scores, F(1, 248) = 21.992, p < 0.001.\n\n\n\n```{.default}\nStudy habits significantly predicted student test scores, F(`r summary(m1)$fstatistic[['numdf']]`, `r summary(m1)$fstatistic[['dendf']]`) = `r summary(m1)$fstatistic[['value']]`, p < 0.001.\n```\n\n\n> Study habits explained 8.15% of the variance in test scores.\n\n\n\n```{.default}\nStudy habits explained `r round( summary(m1)$r.squared * 100, 2)`% of the variance in test scores.\n```\n\n\n> Specifically, students who studied with others (M = 27.52, SD = 7.94) scored significantly higher than students who studied alone (M = 22.79, SD = 7.86), \n$\\beta_1$ = 4.73, \nSE = 1.01, \nt = 4.69, \np < 0.001.\n\n\n\n```{.default}\nSpecifically, students who studied with others (M = `r round(mean_others, 2)`, SD = `r round(sd_others, 2)`) scored significantly higher than students who studied alone (M = `r round(mean_alone, 2)`, SD = `r round(sd_alone, 2)`), $\\beta_1$ = `r round( summary(m1)$coefficients['studyothers', 'Estimate'], 2)`, SE = `r round( summary(m1)$coefficients['studyothers', 'Std. Error'], 2)`, t = `r summary(m1)$coefficients['studyothers', 't value']`, p < 0.001.\n```\n\n\n<br>\n\n::: {.hcenter}\n**Questions!**\n:::\n\n\n## Visualising the model's estimates\n\n![](figs/TODO-nonref-ci.jpeg){fig-align=\"center\"}\n\nWe have almost all the pieces!\n\nBut finding the 95% CI for the non-reference level is mathematically a little complicated.\n(It's not just the 95% CI of $\\beta_1$, the slope parameter.)\n\nA nice shortcut: **an R package called `emmeans`.**\n\n<!-- - The linear model gives us intercept and slope parameters. -->\n<!-- - We have mean and 95% CI for the reference level (= the intercept). -->\n<!-- - What if we want mean and 95% CI for the non-reference level? -->\n<!-- - To get the mean, we can just add intercept and slope parameters together. -->\n<!-- - But finding the CI is mathematically more complicated, so, here's a shortcut: -->\n\n\n## `emmeans` = \"Estimated Marginal Means\"\n\n- **\"Estimated\"** $\\rightarrow$ based on a model's estimates\n- **\"Marginal\"**  $\\rightarrow$ for each level of the predictor\n- **\"Means\"**  $\\rightarrow$ means of the estimated outcomes for each level of the predictor—but also confidence intervals!\n\n\n## `emmeans` = \"Estimated Marginal Means\"\n\nWe already have our model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(score ~ study, data = score_data)\n```\n:::\n\n\n<br> \n\nUse `emmeans()` to get each group's estimated mean and the variability associated with it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_emm <- emmeans(m1, ~study)\nm1_emm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n study  emmean    SE  df lower.CL upper.CL\n alone    22.8 0.660 248     21.5     24.1\n others   27.5 0.763 248     26.0     29.0\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n<br>\n\nIn `lower.CL` and `upper.CL` are our 95% confidence intervals.\n\n\n## Plotting marginal means and CIs\n\n`emmeans` has a built-in plot style.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(m1_emm) + coord_flip()\n```\n\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/unnamed-chunk-18-1.svg){fig-align='center'}\n:::\n:::\n\n\n\nIt's OK, but a bit boring. We can definitely do better.\n\n\n## Plotting marginal means and CIs\n\n:::: {.columns}\n::: {.column width=\"50%\" style=\"font-size: 70%;\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Save EMMs in tibble format, \n# with compatible column names\nm1_emm_df <- m1_emm |>\n  as_tibble() |>\n  rename(score = emmean)\n\n# Plot the data like before, \n# and now overlay EMMs\nscore_data |>\n  ggplot(aes(x = study, y = score, fill = study, colour = study)) +\n  geom_violin(alpha = 0.5) +\n  geom_jitter(alpha = 0.5, width = 0.3, size = 5) +\n  theme(legend.position = 'none') +\n  scale_colour_manual(values = pal) +\n  scale_fill_manual(values = pal) +\n  geom_errorbar(\n    data = m1_emm_df, \n    aes(ymin = lower.CL, ymax = upper.CL), \n    colour = 'black', \n    width = 0.2,\n    linewidth = 2\n  ) +\n  geom_point(\n    data = m1_emm_df, \n    colour = 'black', \n    size = 5\n  )\n```\n:::\n\n:::\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/unnamed-chunk-20-1.svg)\n:::\n:::\n\n:::\n::::\n\n`emmeans` is an amazingly useful tool.\n\nIt can do LOTS more than we've seen here!\n\nWe'll see more examples in the coming days and weeks.\n\n\n## Building an analysis workflow\n\n<br> \n\n::: {.r-stack}\n![](figs/block2-flowchart-06-0.svg){.fragment height=\"550\" }\n\n![](figs/block2-flowchart-06-1.svg){.fragment height=\"550\" }\n\n![](figs/block2-flowchart-06-2.svg){.fragment height=\"550\" }\n:::\n\n\n\n\n## Extension: Changing the reference level {.smaller}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\nIf reference level = `alone`:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/plot xy ref alone-1.svg)\n:::\n:::\n\n\n:::\n::: {.column width=\"50%\"}\n\nIf reference level = `others`:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/plot xy ref others-1.svg)\n:::\n:::\n\n\n:::\n::::\n\nWhen `others` is the reference level (that is, the level represented as 0):\n\n- What does the intercept represent?\n- What does the slope represent?\n- Why is the slope negative now, when before it was positive?\n- Challenge: What hypotheses would a linear model test about this data?\n\n\n<!-- ======================================== -->\n\n# Categorical predictors with >2 levels\n\n## Examples of categorical predictors with >2 levels\n\n![](figs/TODO-categ.jpeg){fig-align=\"center\"}\n\n\n## Today's data: Study method\n\n\n\n\n\n:::{.r-stack}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/unnamed-chunk-22-1.svg){fig-align='center'}\n:::\n:::\n\n:::{.fragment}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/unnamed-chunk-23-1.svg){fig-align='center'}\n:::\n:::\n\n:::\n:::\n\n:::{style=\"font-size: 80%;\"}\nHow do we fit a line to data from three groups?\n\n- It's impossible to draw one single straight line through all three group means.\n- The smallest number of straight lines that connect all three group means is **two**.\n- For this reason, we're going to use **two** predictors, called **\"dummy variables\"**.\n:::\n\n\n\n## Dummy variables let us extend dummy/treatment coding to >2 levels\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/unnamed-chunk-24-1.svg){fig-align='center'}\n:::\n:::\n\n\n\n:::\n::: {.column width=\"50%\"}\n\nBoth dummy variables have the same reference level: `read`.\n\nThe first dummy variable will compare `self-test` back to `read`.\n\nThe second dummy variable will compare `summarise` back to `read`.\n\n:::\n::::\n\nLet's look at the dummy variables in numeric space.\n\n\n## Dummy variables let us extend dummy/treatment coding to >2 levels {.smaller}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\nFirst dummy variable: `self-test` vs. `read`.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/xy dummy 1-1.svg)\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n\nSecond dummy variable: `summarise` vs. `read`.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/xy dummy 2-1.svg)\n:::\n:::\n\n\n:::\n::::\n\n1. Is the slope of the first dummy variable **positive or negative**? {{< iconify codicon thumbsup-filled size=1em >}} {{< iconify codicon thumbsdown-filled size=1em >}}\n2. Is the slope of the second dummy variable **positive or negative**? {{< iconify codicon thumbsup-filled size=1em >}} {{< iconify codicon thumbsdown-filled size=1em >}}\n3. Is the **slope** of the first dummy variable **bigger** than the slope of the second dummy variable? {{< iconify codicon thumbsup-filled size=1em >}} {{< iconify codicon thumbsdown-filled size=1em >}} \n4. Is the **intercept** of the first dummy variable **bigger** than the intercept of the second dummy variable? {{< iconify codicon thumbsup-filled size=1em >}} {{< iconify codicon thumbsdown-filled size=1em >}}\n\n\n## How can we tell that a model will use *these* particular dummy variables? {.smaller}\n\n<br>\n\nWith the function `contrasts()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(score_data$method)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          self-test summarise\nread              0         0\nself-test         1         0\nsummarise         0         1\n```\n\n\n:::\n:::\n\n\n<br>\n\n- Each **column** contains one dummy variable.\n  - `self-test` compares `self-test` (the 1 in that column) to `read`.\n  - `summarise` compares `summarise` (the 1 in that column) to `read`.\n\n- We know that the reference level is `read` because **in BOTH dummy variables, `read` is coded as 0.**\n\n\n## Modelling `score ~ method` {.smaller}\n\nThe linear expression in maths notation:\n\n$$\nscore_i = \\beta_0 + (\\beta_1 \\times method_{self-test}) + (\\beta_2 \\times method_{summarise}) + \\epsilon_i\n$$\n\nIn R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- lm(score ~ method, data = score_data)\n```\n:::\n\n\nWrite down your prediction: **How many coefficients will this model estimate?**\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = score ~ method, data = score_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-23.414  -5.359  -0.196   5.750  17.804 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       23.414      0.866   27.03   <2e-16 ***\nmethodself-test    4.162      1.319    3.16   0.0018 ** \nmethodsummarise    0.782      1.193    0.66   0.5127    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.08 on 247 degrees of freedom\nMultiple R-squared:  0.0422,\tAdjusted R-squared:  0.0345 \nF-statistic: 5.45 on 2 and 247 DF,  p-value: 0.00484\n```\n\n\n:::\n:::\n\n\n\n## What does each coefficient mean? {.smaller}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n (Intercept)       23.414      0.866   27.03   <2e-16 ***\n methodself-test    4.162      1.319    3.16   0.0018 ** \n methodsummarise    0.782      1.193    0.66   0.5127    \n```\n\n\n:::\n:::\n\n\n<br>\n\n**`(Intercept)` aka $\\beta_0$:**\nThe mean score for the reference level (`read`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_read\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23.4\n```\n\n\n:::\n:::\n\n\n<br>\n\n**`methodself-test` aka $\\beta_1$:**\nThe difference between the mean score of `self-test` and the mean score of `read`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_self - mean_read\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.16\n```\n\n\n:::\n:::\n\n\n<br>\n\n**`methodsummarise` aka $\\beta_2$:**\nThe difference between the mean score of `summarise` and the mean score of `read`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_summ - mean_read\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.782\n```\n\n\n:::\n:::\n\n\n<!-- TODO: activity, predict what these coefs actually mean. -->\n\n\n## What hypotheses are being tested for each coefficient? {.smaller}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate Std. Error t value Pr(>|t|)    \n (Intercept)       23.414      0.866   27.03   <2e-16 ***\n methodself-test    4.162      1.319    3.16   0.0018 ** \n methodsummarise    0.782      1.193    0.66   0.5127    \n```\n\n\n:::\n:::\n\n\n<br>\n\n**`(Intercept)` aka $\\beta_0$:**\n\n- Null hypothesis: The mean score for the reference level (`read`) is equal to zero.\n- $p$-value: the probability of observing an intercept of 23.414, assuming that the true intercept is zero.\n\n\n**`methodself-test` aka $\\beta_1$:**\n\n- Null hypothesis: The difference between the mean score of `self-test` and the mean score of `read` is equal to zero.\n- $p$-value: the probability of observing a difference of 4.162, assuming that the true difference is zero.\n\n\n**`methodsummarise` aka $\\beta_2$:**\n\n- Null hypothesis: The difference between the mean score of `summarise` and the mean score of `read` is equal to zero.\n- $p$-value: the probability of observing a difference of 0.782, assuming that the true difference is zero.\n\n\n<!-- **Can we reject each of these null hypotheses?** {{< iconify codicon thumbsup-filled size=1em >}} {{< iconify codicon thumbsdown-filled size=1em >}} -->\n\n\n## What if we want to test different hypotheses? {.smaller}\n\nFor example, what if we want to know about how the two non-reference levels `self-test` and `summarise` are different from each other?\n\n<br>\n\nThe solution: use our old friend `emmeans`, \"Estimated Marginal Means\".\n\n- **\"Estimated\"** $\\rightarrow$ based on a model's estimates\n- **\"Marginal\"**  $\\rightarrow$ for each level of the predictor\n- **\"Means\"**  $\\rightarrow$ means (and CIs) of the estimated outcomes for each level of the predictor\n\n\n\n## Intro to testing hypotheses with `emmeans` {.smaller}\n\n1. Get estimated means and 95% CIs for each level of the predictor. (We could plot these like we did last time, if we wanted!)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m2_emm <- emmeans(m2, ~method))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n method    emmean    SE  df lower.CL upper.CL\n read        23.4 0.866 247     21.7     25.1\n self-test   27.6 0.994 247     25.6     29.5\n summarise   24.2 0.820 247     22.6     25.8\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n<br>\n\n2. Based on those estimates, we can run hypothesis tests on any two levels of the predictor we want.\nOr phrased differently: \"we can test any contrasts we want\".\n\n\n## Intro to testing our own contrasts {.smaller}\n\nFirst, we need to know the order of levels in the categorical predictor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(score_data$method)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"read\"      \"self-test\" \"summarise\"\n```\n\n\n:::\n:::\n\n\n<br>\n\nFor every contrast you want to test, assign `1` to the level you're interested in and `-1` to the level you want to compare it to, using the level order above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2_comparisons <- list(\n  'self-test vs. read'      = c(-1, 1,  0), # read -1, self-test 1, summarise  0\n  'summarise vs. read'      = c(-1, 0,  1), # read -1, self-test 0, summarise  1\n  'self-test vs. summarise' = c( 0, 1, -1)  # read  0, self-test 1, summarise -1\n)\n```\n:::\n\n\nThe level coded as –1 will be subtracted from the level coded as 1, and we'll test the significance of that difference.\n\n\n\n## Intro to testing our own contrasts {.smaller}\n\nUse `contrast()` to find the $p$-value for each contrast.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m2_emm_contr <- contrast(m2_emm, m2_comparisons))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                estimate   SE  df t.ratio p.value\n self-test vs. read          4.16 1.32 247   3.156  0.0020\n summarise vs. read          0.78 1.19 247   0.656  0.5130\n self-test vs. summarise     3.38 1.29 247   2.622  0.0090\n```\n\n\n:::\n:::\n\n\n<br>\n\nThese `estimate`s look familiar:\n\n:::: {.columns}\n::: {.column width=\"33%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_self - mean_read\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.16\n```\n\n\n:::\n:::\n\n\n:::\n::: {.column width=\"33%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_summ - mean_read\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.782\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"33%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_self - mean_summ\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.38\n```\n\n\n:::\n:::\n\n:::\n::::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/unnamed-chunk-40-1.svg){fig-align='center'}\n:::\n:::\n\n\n\n## Intro to testing our own contrasts {.smaller}\n\nUse `contrast()` to find the $p$-value for each contrast.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m2_emm_contr <- contrast(m2_emm, m2_comparisons))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                estimate   SE  df t.ratio p.value\n self-test vs. read          4.16 1.32 247   3.156  0.0020\n summarise vs. read          0.78 1.19 247   0.656  0.5130\n self-test vs. summarise     3.38 1.29 247   2.622  0.0090\n```\n\n\n:::\n:::\n\n\n<br>\n\nFinally, use `confint()` to get the 95% CIs of each contrast:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(m2_emm_contr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                estimate   SE  df lower.CL upper.CL\n self-test vs. read          4.16 1.32 247    1.564     6.76\n summarise vs. read          0.78 1.19 247   -1.568     3.13\n self-test vs. summarise     3.38 1.29 247    0.841     5.92\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n\n<br>\n\n**Testing our own contrasts using `emmeans` is not necessary for every analysis.**\n\nBut it is useful if the hypotheses we want to test are not the same hypotheses that our *a priori* contrast coding (e.g., our dummy coding) will test.\n\n<br>\n\n::: {.hcenter}\n**Questions!**\n:::\n\n\n## Changing the reference level {.smaller}\n\n<br>\n\nFirst: another prediction activity, individually {{< iconify material-symbols person-rounded size=1.5em >}} and in pairs/threes {{< iconify material-symbols group-outline-rounded size=1.5em >}}.\n\n<br>\n\n:::{.dapr2callout}\n\nImagine the reference level of `method` was `summarise`, instead of `read`.\n\n- Would you expect **the model coefficients** to be the same or different?\n- Would you expect **the set of hypotheses that the model tests** to be the same or different?\n- Would you expect **the estimated marginal means** to be the same or different?\n\n:::\n\n<br>\n\n**{{< iconify material-symbols person-rounded size=1.5em >}} Predict:**\nWrite down your guesses about each question.\n\n**{{< iconify material-symbols group-outline-rounded size=1.5em >}} Explain:**\nWhy do you think your guesses are likely to be correct?\n\n\n## Changing the reference level: In R {.smaller}\n\nThe original coding scheme:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(score_data$method)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          self-test summarise\nread              0         0\nself-test         1         0\nsummarise         0         1\n```\n\n\n:::\n:::\n\n\n<br>\n\nManually relevel the `method` factor so that **our desired reference level comes first**.\n\n(The order of the remaining levels doesn't matter.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscore_data <- score_data |>\n  mutate(\n    method = factor(method, levels = c('summarise', 'read', 'self-test'))\n  )\n```\n:::\n\n\n<br>\n\nNow check the contrasts. How can we tell that `summarise` is now the reference level?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(score_data$method)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          read self-test\nsummarise    0         0\nread         1         0\nself-test    0         1\n```\n\n\n:::\n:::\n\n\n\n\n\n## Changing the reference level: Dummy variables {.smaller}\n\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\nFirst new dummy variable:\n\n`read` vs. `summarise`.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/xy dummy relevel 1-1.svg)\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\nSecond new dummy variable:\n\n`self-test` vs. `summarise`.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/xy dummy relevel 2-1.svg)\n:::\n:::\n\n\n:::\n::::\n\n\n1. Is the slope of the first dummy variable **positive or negative**? {{< iconify codicon thumbsup-filled size=1em >}} {{< iconify codicon thumbsdown-filled size=1em >}}\n2. Is the slope of the second dummy variable **positive or negative**? {{< iconify codicon thumbsup-filled size=1em >}} {{< iconify codicon thumbsdown-filled size=1em >}}\n3. Will the coefficient estimates be **the same or different** compared to our previous model? {{< iconify codicon thumbsup-filled size=1em >}} {{< iconify codicon thumbsdown-filled size=1em >}} \n\n\n## Changing the reference level: Hypothesis tests {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- lm(score ~ method, data = score_data)\n```\n:::\n\n\n<br>\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nReference level = `summmarise`.\n\n:::{ style=\"font-size: 75%;\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = score ~ method, data = score_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-23.414  -5.359  -0.196   5.750  17.804 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       24.196      0.820   29.50   <2e-16 ***\nmethodread        -0.782      1.193   -0.66   0.5127    \nmethodself-test    3.380      1.289    2.62   0.0093 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.08 on 247 degrees of freedom\nMultiple R-squared:  0.0422,\tAdjusted R-squared:  0.0345 \nF-statistic: 5.45 on 2 and 247 DF,  p-value: 0.00484\n```\n\n\n:::\n:::\n\n:::\n\n:::\n::: {.column width=\"50%\"}\nReference level = `read`.\n\n:::{ style=\"font-size: 75%;\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = score ~ method, data = score_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-23.414  -5.359  -0.196   5.750  17.804 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       23.414      0.866   27.03   <2e-16 ***\nmethodself-test    4.162      1.319    3.16   0.0018 ** \nmethodsummarise    0.782      1.193    0.66   0.5127    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.08 on 247 degrees of freedom\nMultiple R-squared:  0.0422,\tAdjusted R-squared:  0.0345 \nF-statistic: 5.45 on 2 and 247 DF,  p-value: 0.00484\n```\n\n\n:::\n:::\n\n:::\n\n:::\n::::\n\n<br>\n\nIn the `summarise` model (`m3`, on the left), **what hypotheses are being tested for each coefficient?**\n\n\n## Changing the reference level: `emmeans` {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3_emm <- emmeans(m3, ~method)\n```\n:::\n\n\n<br>\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nReference level = `summmarise`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(m3_emm) + coord_flip()\n```\n\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/unnamed-chunk-50-1.svg)\n:::\n:::\n\n\n:::\n::: {.column width=\"50%\"}\nReference level = `read`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(m2_emm) + coord_flip()\n```\n\n::: {.cell-output-display}\n![](dapr2_06_categ_dummy_files/figure-revealjs/unnamed-chunk-51-1.svg)\n:::\n:::\n\n\n:::\n::::\n\n<br>\n\nAre the estimated marginal means and 95% CIs from each model **the same or different**? {{< iconify codicon thumbsup-filled size=1em >}} {{< iconify codicon thumbsdown-filled size=1em >}}\n\n\n## Changing the reference level {.smaller}\n\n<br>\n\n:::{.dapr2callout}\n\nWhen the reference level of `method` is `summarise`, instead of `read`:\n\n- **The model coefficients** are different.\n- **The set of hypotheses that the model tests** are different.\n- **The estimated marginal means** are the same.\n\n:::\n\n<br>\n\n**{{< iconify material-symbols person-rounded size=1.5em >}} Observe:**\nDid your guesses match these results?\n\n**{{< iconify material-symbols group-outline-rounded size=1.5em >}} Explain:**\nWhy are the results the way they are?\n\n\n<!-- ======================================== -->\n\n## Building an analysis workflow\n\n<br> \n\n::: {.r-stack}\n![](figs/block2-flowchart-06-0.svg){.fragment height=\"550\" }\n\n![](figs/block2-flowchart-06-1.svg){.fragment height=\"550\" }\n\n![](figs/block2-flowchart-06-2.svg){.fragment height=\"550\" }\n:::\n\n\n\n<!-- ======================================== -->\n\n\n## Revisiting this week's learning objectives\n\n<!-- ::: {.fragment} -->\n::: {.dapr2callout}\n**How can we include categorical variables as predictors in a linear model?**\n\n::: {style=\"font-size: 80%;\"}\n- Represent the variable numerically, for example using dummy coding (also called treatment coding).\n- In dummy coding, the reference level (also called baseline level) is represented (\"coded\") as 0, and the non-reference level is coded as 1.\n- For categorical predictors with >2 levels, dummy coding uses \"dummy variables\" to individually compare each non-reference level to the same reference level.\n:::\n\n:::\n<!-- ::: -->\n\n<!-- ::: {.fragment} -->\n::: {.dapr2callout}\n**When we use a categorical predictor, how do we interpret the linear model's coefficients?**\n\n::: {style=\"font-size: 80%;\"}\n- Intercept (also written as $\\beta_0$): The mean outcome for the reference level.\n- Slope (also written as $\\beta_1$, $\\beta_2$, etc., or for short, $\\beta_j$): The difference between (1) the mean outcome for the non-reference level and (2) the mean outcome for the reference level (when all other predictors are at zero).\n:::\n:::\n<!-- ::: -->\n\n## Revisiting this week's learning objectives\n\n<!-- ::: {.fragment} -->\n::: {.dapr2callout}\n**What hypotheses are tested by the default way that R represents categorical predictors?**\n\n::: {style=\"font-size: 80%;\"}\n- By default, R uses dummy coding/treatment coding. And by default, the reference level is the level that comes first in the alphabet.\n- The intercept's hypothesis test: The mean outcome for the reference level is different from zero.\n- The slope's hypothesis test: The difference between the (1) mean outcome for the non-reference level and (2) the mean outcome for the reference level is different from zero.\n:::\n:::\n<!-- ::: -->\n\n<!-- ::: {.fragment} -->\n::: {.dapr2callout}\n**If we wanted to test different hypotheses after fitting the model, how might we do that?**\n\n::: {style=\"font-size: 80%;\"}\n- We can use a linear model to estimate what we'd expect our outcome variable to be for every value of our predictor(s).\n- These expected outcome values are called \"expected marginal means\".\n- By comparing expected marginal means after fitting the model, we can test basically any hypotheses we want.\n\n:::\n:::\n<!-- ::: -->\n\n<!-- ======================================== -->\n\n## This week \n\n<br>\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n### Tasks\n\n<br>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figs/labs.svg){width=15%}\n:::\n:::\n\n\n**Attend your lab and work together on the exercises** \n\n:::\n::: {.column width=\"50%\"}\n\n### Support\n\n<br>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figs/forum.svg){width=15%}\n:::\n:::\n\n\n**Help each other on the Piazza forum**\n\n:::\n::::\n\n<br>\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figs/exam.svg){width=15%}\n:::\n:::\n\n\n**Complete the weekly quiz**\n\n:::\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figs/oh.png){width=15%}\n:::\n:::\n\n\n**Attend office hours (see Learn page for details)**\n\n:::\n::::\n\n\n# Appendix {.appendix}\n\n## Prediction equations: `score ~ study` <br> (two levels) {.smaller}\n\nThe linear expression that the model assumes has generated each data point $i$ (the reference level is `alone`:\n\n$$\nscore_i = \\beta_0 + (\\beta_1 \\times study) + \\epsilon_i\n$$\n\nA little hat over the variable means that that's an estimated value, so the model will estimate:\n\n$$\n\\widehat{score} = \\hat{\\beta_0} + (\\hat{\\beta_1} \\times study)\n$$\n\nWith simple algebra, we can work out how the $\\beta$ coefficients relate to the estimated score of each group.\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Studying alone is represented as `study = 0`.**\n\n$$\n\\begin{align}\n\\widehat{score}_{alone} &= \\hat{\\beta_0} + (\\hat{\\beta_1} \\times study) \\\\\n\\widehat{score}_{alone} &= \\hat{\\beta_0} + (\\hat{\\beta_1} \\times 0) \\\\\n\\widehat{score}_{alone} &= \\hat{\\beta_0} + 0 \\\\\n\\widehat{score}_{alone} &= \\hat{\\beta_0} \\\\\n\\end{align}\n$$\n\n:::\n::: {.column width=\"50%\"}\n\n**Studying with others is represented as `study = 1`.**\n\n\n$$\n\\begin{align}\n\\widehat{score}_{others} &= \\hat{\\beta_0} + (\\hat{\\beta_1} \\times study) \\\\\n\\widehat{score}_{others} &= \\hat{\\beta_0} + (\\hat{\\beta_1} \\times 1) \\\\\n\\widehat{score}_{others} &= \\hat{\\beta_0} + \\hat{\\beta_1} \\\\\n\\end{align}\n$$\n\n:::\n::::\n\n\n\n\n## Prediction equations: `score ~ method` (three levels) {.smaller}\n\nThe linear expression that the model assumes has generated each data point $i$ (the reference level is `read`):\n\n$$\nscore_i = \\beta_0 + (\\beta_1 \\times method_{self-test}) + (\\beta_2 \\times method_{summarise}) + \\epsilon_i\n$$\n\nA little hat over the variable means that that's an estimated value, so the model will estimate:\n\n$$\n\\widehat{score} = \\beta_0 +  (\\hat{\\beta_1} \\times method_{self-test}) + (\\hat{\\beta_2} \\times method_{summarise})\n$$\n\nWith simple algebra and with the help of the `contrasts()` function, we can work out how the $\\beta$ coefficients relate to the estimated score of each group.\n\n:::: {.columns}\n::: {.column width=\"40%\"}\n\n<br>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(score_data$method)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          self-test summarise\nread              0         0\nself-test         1         0\nsummarise         0         1\n```\n\n\n:::\n:::\n\n\n\n:::\n::: {.column width=\"60%\"}\n\nFirst: **Studying by reading is represented as $method_{self-test} = 0$ and $method_{summarise} = 0$.**\nWe get these numbers from the `read` row of the contrast matrix from `contrasts()`.\n\n\n$$\n\\begin{align}\n\\widehat{score}_{read} &= \\hat{\\beta_0} +(\\hat{\\beta_1} \\times method_{self-test}) + (\\hat{\\beta_2} \\times method_{summarise}) \\\\\n\\widehat{score}_{read} &= \\hat{\\beta_0} +(\\hat{\\beta_1} \\times 0) + (\\hat{\\beta_2} \\times 0) \\\\\n\\widehat{score}_{read} &= \\hat{\\beta_0} + 0 + 0 \\\\\n\\widehat{score}_{read} &= \\hat{\\beta_0} \\\\\n\\end{align}\n$$\n\n:::\n::::\n\n\n\n## Prediction equations: `score ~ method` (three levels) {.smaller}\n\nThe linear expression that the model assumes has generated each data point $i$ (the reference level is `read`):\n\n$$\nscore_i = \\beta_0 + (\\beta_1 \\times method_{self-test}) + (\\beta_2 \\times method_{summarise}) + \\epsilon_i\n$$\n\nA little hat over the variable means that that's an estimated value, so the model will estimate:\n\n$$\n\\widehat{score} = \\beta_0 +  (\\hat{\\beta_1} \\times method_{self-test}) + (\\hat{\\beta_2} \\times method_{summarise})\n$$\n\nWith simple algebra and with the help of the `contrasts()` function, we can work out how the $\\beta$ coefficients relate to the estimated score of each group.\n\n:::: {.columns}\n::: {.column width=\"40%\"}\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(score_data$method)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          self-test summarise\nread              0         0\nself-test         1         0\nsummarise         0         1\n```\n\n\n:::\n:::\n\n\n\n:::\n::: {.column width=\"60%\"}\n\nSecond: **Studying by self-testing is represented as $method_{self-test} = 1$ and $method_{summarise} = 0$.**\nWe get these numbers from the `self-test` row of the contrast matrix from `contrasts()`.\n\n\n$$\n\\begin{align}\n\\widehat{score}_{self} &=  \\hat{\\beta_0} +(\\hat{\\beta_1} \\times method_{self-test}) + (\\hat{\\beta_2} \\times method_{summarise}) \\\\\n\\widehat{score}_{self} &=  \\hat{\\beta_0} +(\\hat{\\beta_1} \\times 1) + (\\hat{\\beta_2} \\times 0) \\\\\n\\widehat{score}_{self} &=  \\hat{\\beta_0} + \\hat{\\beta_1} + 0 \\\\\n\\widehat{score}_{self} &=  \\hat{\\beta_0} + \\hat{\\beta_1}\\\\\n\\end{align}\n$$\n\n:::\n::::\n\n\n\n\n## Prediction equations: `score ~ method` (three levels) {.smaller}\n\nThe linear expression that the model assumes has generated each data point $i$ (the reference level is `read`):\n\n$$\nscore_i = \\beta_0 + (\\beta_1 \\times method_{self-test}) + (\\beta_2 \\times method_{summarise}) + \\epsilon_i\n$$\n\nA little hat over the variable means that that's an estimated value, so the model will estimate:\n\n$$\n\\widehat{score} = \\beta_0 +  (\\hat{\\beta_1} \\times method_{self-test}) + (\\hat{\\beta_2} \\times method_{summarise})\n$$\n\nWith simple algebra and with the help of the `contrasts()` function, we can work out how the $\\beta$ coefficients relate to the estimated score of each group.\n\n:::: {.columns}\n::: {.column width=\"40%\"}\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(score_data$method)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          self-test summarise\nread              0         0\nself-test         1         0\nsummarise         0         1\n```\n\n\n:::\n:::\n\n\n\n:::\n::: {.column width=\"60%\"}\n\nThird: **Studying by summarising is represented as $method_{self-test} = 0$ and $method_{summarise} = 1$.**\nWe get these numbers from the `summarise` row of the contrast matrix from `contrasts()`.\n\n\n$$\n\\begin{align}\n\\widehat{score}_{summ} &=  \\hat{\\beta_0} +(\\hat{\\beta_1} \\times method_{self-test}) + (\\hat{\\beta_2} \\times method_{summarise}) \\\\\n\\widehat{score}_{summ} &=  \\hat{\\beta_0} +(\\hat{\\beta_1} \\times 0) + (\\hat{\\beta_2} \\times 1) \\\\\n\\widehat{score}_{summ} &=  \\hat{\\beta_0} + 0 + \\hat{\\beta_2} \\\\\n\\widehat{score}_{summ} &=  \\hat{\\beta_0} + \\hat{\\beta_2} \\\\\n\\end{align}\n$$\n\n:::\n::::\n\n\n\n\n\n## Why bother with a reference level?  {.smaller}\n\nWhy can't we just compare each group individually to the overall mean? \n\nSuch a model might look something like this:\n\n$$\nscore_i = \\beta_0 + (\\beta_1 \\times read) + (\\beta_2 \\times selftest) +  (\\beta_3 \\times summarise) + \\epsilon_i\n$$\n\nEach score is given by an intercept plus the difference between that intercept and each group's scores.\nThe mean $\\mu$ of each group would be:\n\n$$\n\\begin{align}\n\\mu_{read} &= \\beta_0 + (\\beta_1 \\times read)\\\\\n\\mu_{selftest} &= \\beta_0 + (\\beta_2 \\times selftest)\\\\\n\\mu_{summarise} &= \\beta_0 + (\\beta_3 \\times summarise)\\\\\n\\end{align}\n$$\n\n**For technical reasons, we cannot model this data this way.**\n\nWe are trying to estimate three group means: $\\mu_{read}$,  $\\mu_{selftest}$,  $\\mu_{summarise}$.\nAnd for mathematical reasons, that means we can only have three parameters in our model.\nBut the model above has four: $\\beta_0$,  $\\beta_1$, $\\beta_2$, $\\beta_3$.\n\nIn technical terms, we say the model above is **overparameterised**.\n\n<br>\n\nDummy coding with a reference level is one way to achieve **three parameters for three group means**: one intercept for the reference level and two differences between groups for the other two levels.\n\n\n\n\n\n<!-- :::: {.columns} -->\n<!-- ::: {.column width=\"50%\"} -->\n<!-- a -->\n<!-- ::: -->\n<!-- ::: {.column width=\"50%\"} -->\n<!-- b -->\n<!-- ::: -->\n<!-- :::: -->\n\n\n\n<!-- style=\"font-size: 70%;\" -->",
    "supporting": [
      "dapr2_06_categ_dummy_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}