---
title: "Logistic regression: Study brief"
author: "Emma Waterston, Elizabeth Pankratz"
format: 
  html:
    toc: true
    number_sections: false
    toc-location: left
editor_options: 
  chunk_output_type: console
---

# Research question

Does the probability of delaying gratification change as a function of age, marshmallow visibility, and time of day?


# Study background

The data are available at: <https://uoepsy.github.io/data/mallow2_cleaned.csv>.

The data used for this write-up exercise are simulated, drawing on the Stanford marshmallow experiment - a study on delayed gratification in children. The simulated data are loosely based on the findings of this work, and acted to expand upon the methods and results reported in the paper:

Mischel, W., Ebbesen, E. B., & Raskoff Zeiss, A. (1972). Cognitive and attentional mechanisms in delay of gratification. *Journal of Personality and Social Psychology, 21*(2), 204–218. [https://doi.org/10.1037/h0032198](https://doi.org/10.1037/h0032198)

*NOTE: You are not expected to write an introduction, so you do not have to read this article.*



# Study procedure

In the current study, a sample of 304 children, ranging in ages from 3 to 10 years old, took part. Each child was shown a marshmallow, and it was explained that they were about to be left alone for 10 minutes. They were told that they were welcome to eat the marshmallow while they were waiting, but if the marshmallow was still there after 10 minutes, they would be rewarded with **two** marshmallows.

For half of the children who took part, the marshmallow was visible for the entire 10 minutes (or until they ate it!). For the other half, the marshmallow was placed under a plastic cup.

The experiment took part at various times throughout the working day, and researchers were worried about children being more hungry at certain times of day, so they kept track of whether each child completed the task in the morning or the afternoon, so that they could control for this in their analyses.

For an example of the marshmallow experiment, watch the following video:

<p align="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/QX_oy9614HQ?si=xC0fAVA34i3ha_7L" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><br>



# Data dictionary

The data in `mallow2_cleaned.csv` contain five attributes collected from a simulated sample of $n=301$ hypothetical individuals, and includes:

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
delay_data <- read_csv("https://uoepsy.github.io/data/mallow2_cleaned.csv")
tibble(
  Variable = names(delay_data),
  Description = c("Participant name", "Age (in months)", "Time of day that the experiment took place ('am' = morning, 'pm' = afternoon)", "Experimental condition – whether the marshmallow was 'visible' or 'hidden' for the 10 minutes", "Whether or not the participant took ('taken') the marshmallow within the 10 minutes or left it ('waited')", "Age (in years)")
) %>% gt::gt()
```