---
title: 'dapR2 (week 13 Lect2): Activity1'
author: "Department of Psychology<br>University of Edinburgh"
date: "AY 2020-2021"
output:
  html_document:
    theme: flatly
---

# Question 1

If there is a difference between treatment A in Hospital1 vs. Hospital2, That's definitely a sign of an interaction. 

True or False

# Question 2

If there is a difference between the difference between treatment A and treatment B in Hospital1 vs. Hospital2, That's definitely a sign of an interaction. 

True or False

# Question 3

If you have IV1 and IV2, the interaction plot with IV1 on the x-axis will have completely different information than the interaction plot with IV2 on the x-axis. 

True or False

<br>
<br>

---  

*Scroll down for answers*  
  
---

<div style="margin-bottom:750px;">

</div>




# Answers

1. False -- not necessarily. There could, for instance, be just an effect of hospital. Maybe treatment B and C are also different in the same way as A between hosptial1 and hospital2. 

2. True -- A difference in the difference of levels of one IV depending on the level of the second IV is an interaction. 
3. False -- An interaction plot with either IV1 or IV2 on the x-axis has the same basic information, it is just presented differently. Some patterns might be easier to see one way vs. the other though. 



