---
title: 'dapR: Confidence Interval task'
author: UoePsy Statistics
date: "AY 2020-2021"
output:
  html_document:
    theme: flatly
---

# A little trivia game.

In the form below, you will be asked some trivia questions, to which you must respond with a RANGE of plausible values for which you are 90% confident that the correct answer is within.  

PLEASE DO NOT CHEAT (that defeats the purpose. Everything is anonymous anyway!)

Don't overthink the task, "90% confident" is obviously subjective. Just imagine you are taking part in a (slightly weird) pub quiz. 

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdqlrlbX3WPUjiDYj62mC0fSjFXyHXtpPodpDh-iAL3c5YmVg/viewform?embedded=true" width="640" height="450" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>


---

*Scroll down to find some thinking points.. and the answers!*

---

<div style="margin-bottom:750px;"></div>


Although this is a simple trivia game, it does help to clarify the notion of a confidence interval. Our confidence is our confidence that our interval *contains* the true answer. 
This quiz has been made available on the DAPR1 and DAPR2 courses, totalling approx 500 students.  
If you *all* complete the quiz above, we will have about 500 sets of intervals. 

+ **Question**: Recall the last trivia question "on average, how many seeds on a Strawberry?". Let's imagine that you had all gone out and taken a sample of strawberries and counted the seeds on each one, and then computer the mean, and created an interval, like we saw in the lecture. How many of your intervals would we expect to contain the "true" answer?   
  
+ Take a look at the results here: https://josiahpjking.shinyapps.io/dapr1ci/   
  
+ **Thinking point**: Paying close attention to the bottom plot, which shows the numbers of intervals each respondent gave that contained the correct answer. Does it look like students are providing overly confident ranges?  

