---
title: "dapR2 Week 2 Live R"
output: html_document
date: "2022-09-27"
---

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(simglm)
```


```{r}
set.seed(7284) # change this number to generate different data with approximately the same beta

sim_arguments <- list(
  formula = y ~ 1 + hours + motivation,
  fixed = list(hours = list(var_type = 'ordinal', levels = 0:15),
               motivation = list(var_type = 'continuous', mean = 0, sd = 1)),
  error = list(variance = 20),
  sample_size = 150, # change this number to change the sample size
  reg_weights = c(0.6, 1.4, 1.5) # change these numbers to change the beta. the 1st number is intercept, 2nd beta for hours, 3rd beta for motivation
)

df <- simulate_fixed(data = NULL, sim_arguments) %>%
  simulate_error(sim_arguments) %>%
  generate_response(sim_arguments)

test_study2 <- df %>%
  dplyr::select(y, hours, motivation) %>%
  mutate(
    ID = paste("ID", 101:250, sep = ""),
    score = round(y+abs(min(y))),
    motivation = round(motivation, 2)
  ) %>%
  dplyr::select(ID, score, hours, motivation)

```

Tasks for this data:

1. Plot `hours` and `motivation` against `score`.
2. Run a linear mode with all 3 variables
3. Write down interpretations of the $\beta$ coefficients